### ISSUE TITLE
关于 对 Jellyfin 的支持

### ISSUE THREAD

**Issue by yfdoor** [allanpk716/ChineseSubFinder#10]
请问下是否支持 Jellyfin，支持的话没有看到给出库连接，不支持的话是否有这个计划呢？谢谢

**Comment by CODYI1** [comment]
1. jellyifn和emby一样的，jellyfin是emby闭源后的分支而已，挂削完成nfo就能使用，
2. 这不是emby/jellyfin 的插件 ，需要docker支持 
3. emby的字幕插件在已关闭的issue中有位作者以提供 ，可以去那里问问看那位作者有没有写jellyfin插件的计划。

**Comment by yfdoor** [comment]
好的，多谢
