### ISSUE TITLE
关于Jellyfin支持的问题

### ISSUE THREAD

**Issue by Li-xp** [allanpk716/ChineseSubFinder#100]
本插件是否支持Jellyfin API

**Comment by allanpk716** [comment]
1. 还没有做，Jellyfin 能直接启动 API 调试的 Web 页面吗？类似下图。
2. 有打算支持的，以及 Plex。
3. 应该会重构一次项目，把接口做出来，然后如果有人做出了对应的实现，对接就很容易了。

## 截图
![image](https://user-images.githubusercontent.com/1176000/139609815-2982e22c-812b-4958-a224-8b9740a542a0.png)

**Comment by allanpk716** [comment]
先说结论，等他们搞稳定了，再考虑做 jellyfin 的 API 支持吧····:joy:

刚腾出服务器的资源装了 jellyfin ，看起来 API 接口跟 Emby 很像，然后测试了下，没法正常的返回数据。
如，截图 1-3

PS：考虑到他们的 swagger 没有直接的接口使用，也许是我使用的问题，我还测试了 PostMan 提交数据。

## 版本
![image](https://user-images.githubusercontent.com/1176000/139619812-5b235f0e-5465-47d0-bdca-a082282e19fb.png)

## 截图1
![image](https://user-images.githubusercontent.com/1176000/139619393-2b9b5eca-97c1-4fce-868b-e9ceba22f6dc.png)

## 截图2
![image](https://user-images.githubusercontent.com/1176000/139619442-0a374316-d874-41c9-b86e-5df9b31cbe37.png)

## 截图3
![image](https://user-images.githubusercontent.com/1176000/139619518-eaf4db56-0d12-44fe-87fc-67e734d97a8b.png)

但也有接口也是能正确返回的（所以我理解我应该 url 传参用对了吧，抄他们 swagger 的），如下图：

## 截图 4
![image](https://user-images.githubusercontent.com/1176000/139619616-2fd76177-f54c-4c4d-9937-1b0f7786084b.png)

**Comment by allanpk716** [comment]
再提一下，个人当时搭建家庭的媒体播放平台，粗略体验了 Emby、Jellyfin、Plex，最后选择了 Emby。

个人建议，你想全平台：
1. Windows （Web）
2. MACOS（Web）
3. Android
4. iOS

想都用的顺心一点，建议是上 Emby，快黑五了，**慎重**考虑下。

**Comment by Li-xp** [comment]
感谢大佬解答，Emby我也在蹲折扣😂

**Comment by alwaystest** [comment]
摸了一下 Jellyfin 的官方文档，确实跑不通的样子，不知道是维护落后了还是没找对地方。
想起来 Kodi 有 Plugin 支持从 Jellyfin 读取数据，于是找了一下 API 定义，发现是可以使用的。

[jellyfin-kodi](https://github.com/jellyfin/jellyfin-kodi/blob/master/jellyfin_kodi/jellyfin/api.py)

测试了一下能拿到 Track 信息的 Curl 大致应该这么写

```
curl -H "X-MediaBrowser-Token: $YOUR_TOKEN"  http://$IP:$PORT/Users/$USER_ID/Items/Latest\?Limit\=20\&Fields\=MediaSources
```

**Comment by allanpk716** [comment]
> 摸了一下 Jellyfin 的官方文档，确实跑不通的样子，不知道是维护落后了还是没找对地方。 想起来 Kodi 有 Plugin 支持从 Jellyfin 读取数据，于是找了一下 API 定义，发现是可以使用的。
> 
> [jellyfin-kodi](https://github.com/jellyfin/jellyfin-kodi/blob/master/jellyfin_kodi/jellyfin/api.py)
> 
> 测试了一下能拿到 Track 信息的 Curl 大致应该这么写
> 
> ```
> // 获取 UserID
> curl -H "X-MediaBrowser-Token: $YOUR_TOKEN"  http://$IP:$PORT/Users
> // 获取字幕信息
> curl -H "X-MediaBrowser-Token: $YOUR_TOKEN"  http://$IP:$PORT/Users/$USER_ID/Items/Latest\?Limit\=20\&Fields\=MediaSources
> ```

OK，先记一下这个项目，后续再确认下，因为需要使用不少 API 去提取信息，看看能不能满足吧。

**Comment by crotoc** [comment]
emby的确很好用，只是因为服务器端不是免费的，主流的种子盒子不会默认安装emby，而会安装plex和jellyfin。jellyfin作为完全开源免费的软件，还是很棒的。不好意思麻烦你们有时间再看看能不能搞起来。我不太懂这个原理，不然我也可以来帮忙开发调试一下。说实话字幕软件才是国人看剧片的刚需。我用了个emby的share，因为服务端是在别人那里，只能用opensub下载字幕，基本上没有正确过，时间轴也是乱的一塌糊涂，所以大部分时候就是闲置状态。辛苦你们了！

**Comment by allanpk716** [comment]
> 

jellyfin API 目前没法支持，等他们自己搞清楚先吧。plex 的支持计划应该在年后，需要把 Web 做完先。

**Comment by crotoc** [comment]
好的，感谢！期待！

**Comment by szxypi** [comment]
参数改成1，手动上传的字幕格式，还是Emby的格式

**Comment by androiddisk** [comment]
插眼 静候佳音 大佬辛苦了
