### ISSUE TITLE
windows版启动报错

### ISSUE THREAD

**Issue by OdysseyLinux** [allanpk716/ChineseSubFinder#101]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
chinesesubfinder-0.18.7-Windows-x86_64      win11和win10ltsc版

## 你遇到什么问题了？

启动的时候报缺少dll文件，修复之后报0xc000007b错误，已经试过修复运行库什么的但是没什么用。

## 你的问题弄重现嘛？

能够重现

**Comment by allanpk716** [comment]
https://zhuanlan.zhihu.com/p/395557318

参考上述的方案，看是少了什么。有什么结果截图反馈下。

**Comment by OdysseyLinux** [comment]
只有第二种方法有用，提示这个，麻烦帮忙看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allanpk716/ChineseSubFinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allanpk716/ChineseSubFinder] windows版启动报错 (Issue #101)





 
https://zhuanlan.zhihu.com/p/395557318
 
参考上述的方案，看是少了什么。有什么结果截图反馈下。

**Comment by allanpk716** [comment]
:sweat_smile: 没看到你的反馈信息啊···提示了啥？

**Comment by OdysseyLinux** [comment]
啊？看不到图吗？
用的dumpbin看的，我也不懂这个输出是什么意思😂方便的话你可以加下我微信17551022365

---原始邮件---
发件人: "Chin ***@***.***&gt;
发送时间: 2021年11月3日(周三) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [allanpk716/ChineseSubFinder] windows版启动报错 (Issue #101)




 
😅 没看到你的反馈信息啊···提示了啥？

**Comment by allanpk716** [comment]
> 啊？看不到图吗？ 用的dumpbin看的，我也不懂这个输出是什么意思😂方便的话你可以加下我微信17551022365
> […](#)
> ---原始邮件--- 发件人: "Chin ***@***.***&gt; 发送时间: 2021年11月3日(周三) 上午9:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [allanpk716/ChineseSubFinder] windows版启动报错 (Issue #101) 😅 没看到你的反馈信息啊···提示了啥？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

还是在 github 的 issues 中发图交流吧，可以直接复制你的截图粘贴上传的。交流群暂时没有打算做，见谅。

**Comment by OdysseyLinux** [comment]
![360截图20211102191009308](https://user-images.githubusercontent.com/48606361/140023865-b15a3ad9-4c2f-4743-9475-a8d407e21148.jpg)

**Comment by OdysseyLinux** [comment]
第一次用github 我以为一直用的邮件交流呢。。。

**Comment by allanpk716** [comment]
你看看有什么搜索工具，在你的 Windows 上看看这几个 dll 是否存在，不存在应该需要找一下下载，放到同级目录应该就行了。

## 截图
![image](https://user-images.githubusercontent.com/1176000/140037670-690e0750-473c-468b-b867-f2c32cc7fd5b.png)

**Comment by OdysseyLinux** [comment]
![image](https://user-images.githubusercontent.com/48606361/140040410-7cb457c9-4fc2-46a0-a115-ae95353b6f00.png)
![image](https://user-images.githubusercontent.com/48606361/140040489-1dd9fa11-5584-48fe-9b80-699571911333.png)
![image](https://user-images.githubusercontent.com/48606361/140040558-144b68fe-b8b1-4be4-9830-9f2ebee79cdb.png)
三个都有

**Comment by allanpk716** [comment]
报错的截图发来看看

**Comment by OdysseyLinux** [comment]
![image](https://user-images.githubusercontent.com/48606361/140041811-4a621097-8253-4480-b80c-53b675bf5d2f.png)

**Comment by allanpk716** [comment]
猜是 VC 运行时可能不兼容，你找一下 VC 运行时安装包试试。我电脑都是开发机，环境齐全无法复现。晚点我弄个虚拟机再试试。

**Comment by OdysseyLinux** [comment]
![image](https://user-images.githubusercontent.com/48606361/140065612-f6731be3-b1e3-481e-bb2f-daee5f963de7.png)
wo'ye我也不知道装的对不对，反正没起作用。。。

**Comment by allanpk716** [comment]
https://zhuanlan.zhihu.com/p/404653498

这些方案能试试吗？我试了虚拟机也能用···暂时没得头绪。不然就只能看你是否能自行编译来试试了:joy:

**Comment by OdysseyLinux** [comment]
试过了，没用，请问一下你用的是什么版本的虚拟机？



---原始邮件---
发件人: "Chin ***@***.***&gt;
发送时间: 2021年11月4日(周四) 上午8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [allanpk716/ChineseSubFinder] windows版启动报错 (Issue #101)




 
https://zhuanlan.zhihu.com/p/404653498
 
这些方案能试试吗？我试了虚拟机也能用···暂时没得头绪。不然就只能看你是否能自行编译来试试了😂

**Comment by allanpk716** [comment]
> 试过了，没用，请问一下你用的是什么版本的虚拟机？
> […](#)
> ---原始邮件--- 发件人: "Chin ***@***.***&gt; 发送时间: 2021年11月4日(周四) 上午8:30 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [allanpk716/ChineseSubFinder] windows版启动报错 (Issue #101) https://zhuanlan.zhihu.com/p/404653498 这些方案能试试吗？我试了虚拟机也能用···暂时没得头绪。不然就只能看你是否能自行编译来试试了😂 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Windows 11 ，然后自动更新到最新。

**Comment by macazy** [comment]
WIN10表示也不行~

**Comment by macazy** [comment]
> WIN10表示也不行~

自己配置GCC后OK
使用的版本是：x86_64-8.1.0-release-posix-seh-rt_v6-rev0

**Comment by allanpk716** [comment]
> > WIN10表示也不行~
> 
> 自己配置GCC后OK 使用的版本是：x86_64-8.1.0-release-posix-seh-rt_v6-rev0

能知道是少什么 dll 吗？

**Comment by OdysseyLinux** [comment]
> > WIN10表示也不行~
> 
> 自己配置GCC后OK 使用的版本是：x86_64-8.1.0-release-posix-seh-rt_v6-rev0

可以指导一下具体操作步骤吗？没看懂😂

**Comment by macazy** [comment]
> > > WIN10表示也不行~
> > 
> > 
> > 自己配置GCC后OK 使用的版本是：x86_64-8.1.0-release-posix-seh-rt_v6-rev0
> 
> 能知道是少什么 dll 吗？

就是上面图中的依赖

**Comment by allanpk716** [comment]
> > > > WIN10表示也不行~
> > > 
> > > 
> > > 自己配置GCC后OK 使用的版本是：x86_64-8.1.0-release-posix-seh-rt_v6-rev0
> > 
> > 
> > 能知道是少什么 dll 吗？
> 
> 就是上面图中的依赖

😂他分享的依赖截图上，他系统也有，也就是说可能版本不对咯？

**Comment by yysudp** [comment]
楼主解决了吗  我也是一样的问题

**Comment by OdysseyLinux** [comment]
没呢，放弃了😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月6日(周六) 凌晨2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [allanpk716/ChineseSubFinder] windows版启动报错 (Issue #101)




 
楼主解决了吗  我也是一样的问题

**Comment by allanpk716** [comment]
下载这个安装呢？
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjeorzZy4L0AhV6JTQIHUbnDN0QFnoECA4QAQ&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2Ffiles%2FToolchains%2520targetting%2520Win64%2FPersonal%2520Builds%2Fmingw-builds%2F8.1.0%2Fthreads-posix%2Fseh%2Fx86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z%2Fdownload&usg=AOvVaw1WUmbXLk9E7wGTjq61F-fz

## 截图
![image](https://user-images.githubusercontent.com/1176000/140593443-92e69624-0b8b-4648-a34c-18ea08253615.png)

**Comment by OdysseyLinux** [comment]
> 下载这个安装呢？ https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjeorzZy4L0AhV6JTQIHUbnDN0QFnoECA4QAQ&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2Ffiles%2FToolchains%2520targetting%2520Win64%2FPersonal%2520Builds%2Fmingw-builds%2F8.1.0%2Fthreads-posix%2Fseh%2Fx86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z%2Fdownload&usg=AOvVaw1WUmbXLk9E7wGTjq61F-fz
> 
> ## 截图
> ![image](https://user-images.githubusercontent.com/1176000/140593443-92e69624-0b8b-4648-a34c-18ea08253615.png)

成了！谢谢大佬

**Comment by Jessie722** [comment]
> 下载这个安装呢？ https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjeorzZy4L0AhV6JTQIHUbnDN0QFnoECA4QAQ&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmingw-w64%2Ffiles%2FToolchains%2520targetting%2520Win64%2FPersonal%2520Builds%2Fmingw-builds%2F8.1.0%2Fthreads-posix%2Fseh%2Fx86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z%2Fdownload&usg=AOvVaw1WUmbXLk9E7wGTjq61F-fz
> 
> ## 截图
> ![image](https://user-images.githubusercontent.com/1176000/140593443-92e69624-0b8b-4648-a34c-18ea08253615.png)

你好，我也是碰到上述情况，安装完MinGW不报错了，但是一打开就闪退是什么原因，也没有出现任何提示

**Comment by yysudp** [comment]
能说一下怎么安装吗。。。谢谢

**Comment by yysudp** [comment]
我也全安装了  也是不行 无法定位程序输入点。。

**Comment by allanpk716** [comment]
> 我也全安装了  也是不行 无法定位程序输入点。。

截图有吗？

**Comment by enzowangxin** [comment]
![Snipaste_2021-11-13_19-38-45](https://user-images.githubusercontent.com/30770490/141642374-90aaf0d6-ecfc-4ea8-8392-52461d69e351.png)
无法定位程序输入点

**Comment by enzowangxin** [comment]
> > 我也全安装了  也是不行 无法定位程序输入点。。
> 
> 截图有吗？

![Uploading Snipaste_2021-11-13_19-38-45.png…]()

**Comment by enzowangxin** [comment]
> > 我也全安装了  也是不行 无法定位程序输入点。。
> 
> 截图有吗？

![Snipaste_2021-11-13_19-38-45](https://user-images.githubusercontent.com/30770490/141642418-bd1bfcfa-00bf-4f11-953e-655bc39dfc69.png)

**Comment by allanpk716** [comment]
> > > 我也全安装了  也是不行 无法定位程序输入点。。
> 
> > 
> 
> > 截图有吗？
> 
> 
> 
> ![Snipaste_2021-11-13_19-38-45](https://user-images.githubusercontent.com/30770490/141642418-bd1bfcfa-00bf-4f11-953e-655bc39dfc69.png)
> 
> 

你需要看看上面提及的工具，定位需要的 dll 有哪些，然后是否都有了

**Comment by yysudp** [comment]
![屏幕截图 2021-11-17 173612](https://user-images.githubusercontent.com/93736216/142175349-ea15bd01-60b2-4719-961b-33ef4ef1efb7.png)看不懂了

**Comment by yysudp** [comment]
![屏幕截图 2021-11-17 174020](https://user-images.githubusercontent.com/93736216/142176006-bf85e1e6-8ac8-4f8a-bf23-d6b80526e7db.png
![屏幕截图 2021-11-17 174212](https://user-images.githubusercontent.com/93736216/142176286-b9d07d7d-fe82-4f96-bb6d-24f240f535ab.png)
)    运行库也装了

**Comment by yysudp** [comment]
解决了......把单独下载的dll删掉就能运行了..
