### ISSUE TITLE
目前出现zmk.pw提示ip被屏蔽，已经超过字幕下载个数限制

### ISSUE THREAD

**Issue by yilin101** [allanpk716/ChineseSubFinder#102]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.x 

环境: docker

设置的是12h一次下载字幕
目前出现zmk.pw提示ip被屏蔽，已经超过字幕下载个数限制

建议只搜索新增电影文件的字幕

全部搜索一遍 容易被屏蔽

**Comment by allanpk716** [comment]
[如何判断视频是否需要下载、更新字幕的](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md)

第一次是会大批量扫描的。后续扫描逻辑看上述文档。如果有类似问题出现了，可能就需要本程序加入缓存记录功能了。

**Comment by allanpk716** [comment]
缓存的功能会跟着本程序的字幕分享功能一起做出来吧，总归会有服务器承受压力的（不是这些字幕网站，就是个人的小水管了）:joy:

**Comment by yilin101** [comment]
> 缓存的功能会跟着本程序的字幕分享功能一起做出来吧，总归会有服务器承受压力的（不是这些字幕网站，就是个人的小水管了）😂

那就期待了

**Comment by WenkeRen** [comment]
@yilin101 我也遇到了同样的尴尬，在zmk网站上没有找到封IP相关的说明，不知道这个会封多久，你那边是否解封了呢？

**Comment by allanpk716** [comment]
> @yilin101 我也遇到了同样的尴尬，在zmk网站上没有找到封IP相关的说明，不知道这个会封多久，你那边是否解封了呢？

每一天

**Comment by palemoky** [comment]
@allanpk716 我发现这个问题用代理 IP 可解，请问是否可以有一个用户配置代理池的地方？我有几个代理服务器，优先用原生 IP，zmk 这样的发现 IP 屏蔽的就启用代理池中的 IP 进行字幕爬取

**Comment by allanpk716** [comment]
> @allanpk716 我发现这个问题用代理 IP 可解，请问是否可以有一个用户配置代理池的地方？我有几个代理服务器，优先用原生 IP，zmk 这样的发现 IP 屏蔽的就启用代理池中的 IP 进行字幕爬取

嗯···其实我有做过一个“代理池”的工具，简单就是把你有的代理地址配置好，这个工具会根据请求的目标地址进行统计和分析，伪随机给出适合的代理去使用。后来我发现了一个项目，https://github.com/v2rayA/v2rayA 配合这个工具使用，自带负载均衡（虽然没有做到我自己那个模块的统计，但是够用）

web做完初版 -> 时间轴校正新版本算法 -> 然后就是共享字幕的实现，忍一忍，22年底前应该稳 😂
