### ISSUE TITLE
建议不要修改既有字幕的文件名，以及跳过文件夹下有.ignore文件的文件夹

### ISSUE THREAD

**Issue by devome** [allanpk716/ChineseSubFinder#103]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.8.7

环境: docker

## 你想要新增或者改进什么功能？

1. 现在的逻辑是如果存在以`.chs.srt` `.cht.srt`结尾的字幕文件，软件好像会自动改名。但对pt用户来说，有些种子中本身就带有了`.chs.srt` `.cht.srt`的字幕文件，把它们名字改掉就不能正常做种了。虽然有一种方法是将视频文件硬连接到其他地方，在其他地方来处理字幕，但这对许多人并不友好。因此建议，不修改既有的任何字幕名称，只新增加字幕，或者创建软连接。
2. Jellyfin和Emby都支持在文件夹下手动创建一个`.ignore`文件使其跳过扫描，既然本项目也是向它们看齐的，所以也建议跳过扫描文件夹下有.ignore文件的文件夹。

## 这个功能有什么可以参考的资料吗？

无需。

**Comment by allanpk716** [comment]
1. 你提到的这个自动改名的问题，确实会在第一次的时候进行扫描判断是否需要改名 settings 中的 `SubNameFormatter` 控制字幕的命名格式。之前没有预计到会有你这样做种的情况。硬链接和软链接这个思路应该是不会考虑实现，因为需要兼容 Windows。虽然 Windows 也可以做类似的逻辑，但是对于一般 Windows 使用者这个功能会增加他们的负担。所以以你的需求，我可以提供的方案是，提供一个特殊的“做种模式”，程序只扫描是否有中文字幕而不修改字幕的格式，然后字幕下载也会外置到固定目录，因为我不能确定下载的字幕是否与你现有的字幕重名，那么无非就得选择是否覆盖，这就麻烦了。

2. 这个可以做。

**Comment by devome** [comment]
> 1. 你提到的这个自动改名的问题，确实会在第一次的时候进行扫描判断是否需要改名 settings 中的 `SubNameFormatter` 控制字幕的命名格式。之前没有预计到会有你这样做种的情况。硬链接和软链接这个思路应该是不会考虑实现，因为需要兼容 Windows。虽然 Windows 也可以做类似的逻辑，但是对于一般 Windows 使用者这个功能会增加他们的负担。所以以你的需求，我可以提供的方案是，提供一个特殊的“做种模式”，程序只扫描是否有中文字幕而不修改字幕的格式，然后字幕下载也会外置到固定目录，因为我不能确定下载的字幕是否与你现有的字幕重名，那么无非就得选择是否覆盖，这就麻烦了。

下载到固定目录，播放时就不能自动选择字幕了。这个问题确实有点麻烦，我暂时也没有好的想法。

**Comment by devome** [comment]
另外，大佬，我也尝试基于alpine做了个镜像，见：https://hub.docker.com/r/nevinee/chinesesubfinder
层数只有3层，不使用s6-overlay进程只有1个，直接在`/config`目录运行程序，所以日志、setting.db都能直接在`/config`看见。因为chromium的关系导致无法构建armv7镜像。现在无法但还有两个疑问，希望大佬能解惑一下：
1. alpine中`chromium`在armv7平台上没有，是不是只有subhd才需要用到`chromium`这个包，如果目前屏蔽了subhd，是不是可以不安装chromium？
2. 目前软件读取配置文件`config.yaml`的逻辑是怎样的？是每次启动扫描任务时都读取一次，还是只在启动`chinesesubfinder`这个进程时读取一次呢？

**Comment by allanpk716** [comment]
> 另外，大佬，我也尝试基于alpine做了个镜像，见：https://hub.docker.com/r/nevinee/chinesesubfinder 层数只有3层，不使用s6-overlay进程只有1个，直接在`/config`目录运行程序，所以日志、setting.db都能直接在`/config`看见。但由于chromium的关系导致无法构建armv7镜像（alpine中`chromium`在armv7平台上没有）。所以有两个疑问，希望大佬能解惑一下：
> 
> 1. 是不是只有subhd才需要用到`chromium`这个包，如果目前屏蔽了subhd，是不是可以不安装chromium？
> 2. 目前软件读取配置文件`config.yaml`的逻辑是怎样的？是每次启动扫描任务时都读取一次，还是只在启动`chinesesubfinder`这个进程时读取一次呢？

我对于 Linux 和 Docker 都是了解很基础的，有些东西是网友帮做的。
1. 后续是否使用 chrome 这个不确定，所以暂时就懒得换了。后续准备使用 ffmpeg 这个工具，更换镜像得折腾一下，如果你找到好用的，更新频率高的 ffmpeg 的基础镜像，可以分享下。我找到的都是比较旧的，或者更新频度太低。（这里有个梗，因为编译阶段的基础镜像一般都用最新的，那么有一次遇到一个问题，就是部署docker打包的镜像的底层库与编译的不一致，把我给弄的很烦。主要是现阶段倾向于写业务逻辑，而不太想折腾基础环境问题。）
2. 启动第一次读取，本来做了文件监控的逻辑，发现在容器映射文件后无效，暂时就懒得写扫描前的 reload 逻辑了。

**Comment by allanpk716** [comment]
> 2. Jellyfin和Emby都支持在文件夹下手动创建一个`.ignore`文件使其跳过扫描，既然本项目也是向它们看齐的，所以也建议跳过扫描文件夹下有.ignore文件的文件夹。
> 


这个功能已经实现了，等下一个版本一并发布，就不为这个小功能单独升版本了

**Comment by devome** [comment]
> 我对于 Linux 和 Docker 都是了解很基础的，有些东西是网友帮做的。
> 1. 后续是否使用 chrome 这个不确定，所以暂时就懒得换了。多架构支持还是希望能有，因为最终这个工具还是希望能够在一般专业吃灰 pi 上使用:joy:。准备使用 ffmpeg 这个工具，更换镜像得折腾一下，如果你找到好用的，更新频率高的 ffmpeg 的基础镜像，可以分享下。我找到的都是比较旧的，或者更新频度太低。（这里有个梗，因为编译阶段的基础镜像一般都用最新的，那么有一次遇到一个问题，就是部署docker打包的镜像的底层库与编译的不一致，把我给弄的很烦。主要是现阶段倾向于写业务逻辑，而不太想折腾基础环境问题。）
如果要用到chromium的库，那估计基础镜像用ubuntu还是比较好的，只是目前用的lsio的ubuntu版本比较老，如果需要，我可以尝试改进到官方ubuntu20.04或者甚至最新的官方ubuntu21.10。
用了新版ubuntu以后，自然ffmepg也会新很多。如果想要保持编译阶段的和发布阶段的ffmpeg版本完全一致，我可以尝试改成发布的也基于官方debian而不是官方ubuntu，看大佬需要。
但要提醒一下，如果不基于lsio的ubuntu，而是基于官方的debian哮ubuntu镜像，可能会让最终发布镜像更大一些。
如果不需要用到并且未来也不会再用到chromium的话，就可以考虑编译和布阶段都基于alpine了。

> 2. 启动第一次读取，本来做了文件监控的逻辑，发现在容器映射文件后无效，暂时就懒得写扫描前的 reload 逻辑了。
目前你仓库中的逻辑是启动时将用户的/config/config.yaml复制一份到/app/config.yaml，而软件是读取的后者，这样当然即使实时监控配置文件变化，也监控不到/config/config.yaml。我可以先改掉，改成直接读取/config/config.yaml，后面chinesesubfinder再慢慢恢复实时监控配置的代码。

**Comment by allanpk716** [comment]
> > 我对于 Linux 和 Docker 都是了解很基础的，有些东西是网友帮做的。
> > 
> > 1. 后续是否使用 chrome 这个不确定，所以暂时就懒得换了。多架构支持还是希望能有，因为最终这个工具还是希望能够在一般专业吃灰 pi 上使用😂。准备使用 ffmpeg 这个工具，更换镜像得折腾一下，如果你找到好用的，更新频率高的 ffmpeg 的基础镜像，可以分享下。我找到的都是比较旧的，或者更新频度太低。（这里有个梗，因为编译阶段的基础镜像一般都用最新的，那么有一次遇到一个问题，就是部署docker打包的镜像的底层库与编译的不一致，把我给弄的很烦。主要是现阶段倾向于写业务逻辑，而不太想折腾基础环境问题。）
> 
> 如果要用到chromium的库，那估计基础镜像用ubuntu还是比较好的，只是目前用的lsio的ubuntu版本比较老，如果需要，我可以尝试改进到官方ubuntu20.04或者甚至最新的官方ubuntu21.10。 用了新版ubuntu以后，自然ffmepg也会新很多。如果想要保持编译阶段的和发布阶段的ffmpeg版本完全一致，我可以尝试改成发布的也基于官方debian而不是官方ubuntu，看大佬需要。 但要提醒一下，如果不基于lsio的ubuntu，而是基于官方的debian或ubuntu镜像，可能会让最终发布镜像更大一些。 如果不需要用到并且未来也不会再用到chromium的话，就可以考虑编译和发布阶段都基于alpine了，也就可以支持armv7了，体积也会小一些。
> 
> > 1. 启动第一次读取，本来做了文件监控的逻辑，发现在容器映射文件后无效，暂时就懒得写扫描前的 reload 逻辑了。
> 
> 目前你仓库中的逻辑是启动时将用户的/config/config.yaml复制一份到/app/config.yaml，而软件是读取的后者，这样当然即使实时监控配置文件变化，也监控不到/config/config.yaml。我可以先改掉，改成直接读取/config/config.yaml，后面chinesesubfinder再慢慢恢复实时监控配置的代码。

哦，想起来了，有网友帮提交了这个启动前的脚本功能，我都忘记这回事了··· 😂 

突然想起来之前为了解决不同平台数据库保存的问题，还专门去看过这个实现。这个问题也算历史遗留问题了，为了保证兼容性没改，改了怕大家现在的配置 docker 的信息就不能正确用了。

当时的打算是等 Web 配置界面做出来了，一次性给解决。

**Comment by devome** [comment]
> 哦，想起来了，有网友帮提交了这个启动前的脚本功能，我都忘记这回事了··· 😂 
> 
> 突然想起来之前为了解决不同平台数据库保存的问题，还专门去看过这个实现。这个问题也算历史遗留问题了，为了保证兼容性没改，改了怕大家现在的配置 docker 的信息就不能正确用了。
> 
> 当时的打算是等 Web 配置界面做出来了，一次性给解决。

好吧

**Comment by kuenming** [comment]
请问 目前版本有支援 跳过文件夹下有.ignore文件的文件夹,有包含下一层文件夹吗?
因为有.ignore档的文件夹会跳过,全部下一层文件夹还是不会跳过

**Comment by allanpk716** [comment]
> 请问 目前版本有支援 跳过文件夹下有.ignore文件的文件夹,有包含下一层文件夹吗? 因为有.ignore档的文件夹会跳过,全部下一层文件夹还是不会跳过

你能举例下你的目录结构吗？或者说具体的情况。这个功能是临时给出来的，后续会把 web 对接上排除逻辑，这样操作和验证起来会更加容易些，当然这个没那么快，需要把缓存和视频简介展示都做了才能够把这个功能顺带做出来。

**Comment by kuenming** [comment]
例如 目前有这些档案与目录 
\video\.ignore
\video\movie.mkv

\video\movie1\movie1.mkv

\video\movie2\movie2.mkv
\video\movie2\.ignore

执行ChineseSubFinder 后 
\video\.ignore
\video\movie.mkv

\video\movie1\movie1.mkv
\video\movie1\movie1.srt
\video\movie1\movie1.srt-csf-bk

\video\movie2\movie2.mkv
\video\movie2\.ignore

请问有办法 只要在\video 放一个 .ignore档 ,目录下movie1 与movie2(不需另外放.ignore在movie2目录里)與其他目录就不会下载字幕

**Comment by allanpk716** [comment]
> 例如 目前有这些档案与目录 \video.ignore \video\movie.mkv
> 
> \video\movie1\movie1.mkv
> 
> \video\movie2\movie2.mkv \video\movie2.ignore
> 
> 执行ChineseSubFinder 后 \video.ignore \video\movie.mkv
> 
> \video\movie1\movie1.mkv \video\movie1\movie1.srt \video\movie1\movie1.srt-csf-bk
> 
> \video\movie2\movie2.mkv \video\movie2.ignore
> 
> 请问有办法 只要在\video 放一个 .ignore档 ,目录下movie1 与movie2(不需另外放.ignore在movie2目录里)與其他目录就不会下载字幕

应该不会马上做出来，而且还是在每个视频的根目录做更好，而不是上级目录出现，下级目录跳过，这样后续如果有人需求是交叉排除的功能，就更加不好做了。还是得 web 做出缓存后一并解决吧。
