### ISSUE TITLE
好像我移动光纤访问字幕库网站很慢，但是我路由器设置hosts强制走代理，有些还是不行

### ISSUE THREAD

**Issue by heavy008** [allanpk716/ChineseSubFinder#104]
有百分之70是成功下载 了，有些不行，但是手动访问却可以，类似警告
[WARNING]: 2021-11-05 16:56:48 - Step2,sub download url not found https://zmk.pw/detail/92337.html

**Comment by allanpk716** [comment]
> 有百分之70是成功下载 了，有些不行，但是手动访问却可以，类似警告
> 
> [WARNING]: 2021-11-05 16:56:48 - Step2,sub download url not found https://zmk.pw/detail/92337.html

一般是网速问题，反正挂机，等几个扫描周期基本就OK了

**Comment by heavy008** [comment]
确实是的，周末挂了两天，现在基本都有字幕了  ，👍🏻

**Comment by allanpk716** [comment]
> 确实是的，周末挂了两天，现在基本都有字幕了 ，👍🏻

有啥再反馈。
