### ISSUE TITLE
windows版启动闪退

### ISSUE THREAD

**Issue by Jessie722** [allanpk716/ChineseSubFinder#105]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.7

环境: Windows10

## 你遇到什么问题了？
https://github.com/allanpk716/ChineseSubFinder/issues/101#issue-1041190387
我也是碰到跟这个帖子一样的启动报错问题，虽然在安装完MinGW不报错了，但是一打开就闪退，也没有出现任何提示

## 你的问题能重现嘛？

能够重现

**Comment by allanpk716** [comment]
看 Log 文件夹

**Comment by Jessie722** [comment]
log文件夹是在当前程序的目录吗？但是我这并没有生成log文件夹

**Comment by allanpk716** [comment]
> 看 Log 文件夹

那你需要使用 cmd 去执行本程序，这样应该会有信息输出的

**Comment by Jessie722** [comment]
知道原因了，配置文件命名错了，居然没发现= =（眼瞎） ，感谢作者！！
