### ISSUE TITLE
指定字幕格式下载

### ISSUE THREAD

**Issue by OdysseyLinux** [allanpk716/ChineseSubFinder#106]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: Window 

## 你想要新增或者改进什么功能？

指定下载ass格式的字幕或者srt模式的字幕

**Comment by allanpk716** [comment]
[配置建议以及解释](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%85%8D%E7%BD%AE%E5%BB%BA%E8%AE%AE%E4%BB%A5%E5%8F%8A%E8%A7%A3%E9%87%8A.md)
