### ISSUE TITLE
windows版本启动后一直卡住不继续

### ISSUE THREAD

**Issue by OliverGrace** [allanpk716/ChineseSubFinder#107]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.7

环境: Windows  10

## 你遇到什么问题了？
启动后一直卡在这里，重启几次都是这样
```
[INFO]: 2021-11-09 03:58:03 - ChineseSubFinder Version: v0.18.7
[INFO]: 2021-11-09 03:58:03 - UseProxy = false
[INFO]: 2021-11-09 03:58:03 - MovieFolder: X:\Oliver\movie
[INFO]: 2021-11-09 03:58:03 - SeriesFolder: X:\Oliver\tv
[INFO]: 2021-11-09 03:58:03 - HotFix Start...
[INFO]: 2021-11-09 03:58:03 - HotFix End
[INFO]: 2021-11-09 03:58:03 - Change Sub Name Format Start...

2021/11/09 03:58:03 [31;1m/home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/sub_formatter/sub_format_changer.go:180 [35;1mrecord not found
[0m[33m[0.000ms] [34;1m[rows:0][0m SELECT * FROM `sub_format_recs` WHERE `sub_format_recs`.`deleted_at` IS NULL ORDER BY `sub_format_recs`.`id` LIMIT 1
[WARNING]: 2021-11-09 03:59:58 - IsSubHasChinese.HasChineseLang X:\Oliver\movie\Dune (2021)\Dune (2021).zh-cn.srt not chinese sub, is  英
```

## 你的问题弄重现嘛？

能够重现

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

X:\Oliver\movie\Dune (2021)\Dune (2021).zh-cn.srt

## 出错的日志信息可以复制一些出来吗？
[INFO]: 2021-11-09 03:57:57 - ChineseSubFinder Version: v0.18.7
[INFO]: 2021-11-09 03:57:57 - UseProxy = false
[INFO]: 2021-11-09 03:57:57 - MovieFolder: X:\Oliver\movie
[INFO]: 2021-11-09 03:57:57 - SeriesFolder: X:\Oliver\tv
[INFO]: 2021-11-09 03:57:57 - HotFix Start...
[INFO]: 2021-11-09 03:57:57 - HotFix End
[INFO]: 2021-11-09 03:57:57 - Change Sub Name Format Start...
[INFO]: 2021-11-09 03:58:03 - ChineseSubFinder Version: v0.18.7
[INFO]: 2021-11-09 03:58:03 - UseProxy = false
[INFO]: 2021-11-09 03:58:03 - MovieFolder: X:\Oliver\movie
[INFO]: 2021-11-09 03:58:03 - SeriesFolder: X:\Oliver\tv
[INFO]: 2021-11-09 03:58:03 - HotFix Start...
[INFO]: 2021-11-09 03:58:03 - HotFix End
[INFO]: 2021-11-09 03:58:03 - Change Sub Name Format Start...
[WARNING]: 2021-11-09 03:59:58 - IsSubHasChinese.HasChineseLang X:\Oliver\movie\Dune (2021)\Dune (2021).zh-cn.srt not chinese sub, is  英

**Comment by allanpk716** [comment]
在执行字幕命名规范格式化操作，等，有日志的。
