### ISSUE TITLE
ForceFullScanAndDownloadSub 强制扫描并没有把之前下载的没有字幕的视频扫字幕

### ISSUE THREAD

**Issue by OliverGrace** [allanpk716/ChineseSubFinder#108]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.7

环境: Windows

## 你遇到什么问题了？

ForceFullScanAndDownloadSub 强制扫描并没有把之前下载的没有字幕的视频扫字幕

## 你的问题弄重现嘛？

能够重现

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: X:\Oliver\tv\Rick and Morty\S5

视频的信息: Rick and Morty (2013) - S05E01 - WEBDL-1080p.mkv

## 出错的日志信息可以复制一些出来吗？

日志中没有处理过这个文件夹

**Comment by OliverGrace** [comment]
S5目录下包含有每一集的nfo文件，并且里面含有imdb号

**Comment by allanpk716** [comment]
你这是想用配置文件，指定这一个目录使用？如果是，是不支持的，你依然要按教程中的要求目录结构。

**Comment by OliverGrace** [comment]
> 你这是想用配置文件，指定这一个目录使用？如果是，是不支持的，你依然要按教程中的要求目录结构。

不是的，我是想把默认设置的所有电视剧电影目录下的视频扫一次下载字幕然后调轨（因为之前挺多没调轨的）

**Comment by OliverGrace** [comment]
已经解决了，把emby配置去掉就能刮到所有视频了

**Comment by allanpk716** [comment]
> 已经解决了，把emby配置去掉就能刮到所有视频了

这个我看看，估计是bug
