### ISSUE TITLE
下载的ass字幕在emby中播放时没有字幕出现

### ISSUE THREAD

**Issue by SiIentZephyrus** [allanpk716/ChineseSubFinder#109]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.7

环境:  群晖918 6.23 docker

## 你遇到什么问题了？

良医第五季下载字幕的时候，前两集下载的时SRT字幕，播放能正常显示，后三集下载的时ass字幕，在emby能看到这个字幕选项，但是选择了没有办法看到字幕，使用potplayer直接播放，字幕使用正常，很奇怪，不确定是不是字幕问题。

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

ass字幕能正常使用

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: \\ip\videos\tvs\The Good Doctor\Season 5

视频的信息: The Good Doctor - S05E05 - Crazytown WEBDL-1080p.mkv

## 出错的日志信息可以复制一些出来吗？

日志无问题

**Comment by SiIentZephyrus** [comment]
想问问其他人有过这种情况么，是emby支持的不好，还是就是字幕有问题

**Comment by allanpk716** [comment]
你可以把字幕发送上来看看，一个是正确能够使用的，一个是你说的不能正确加载的。这样有个对比，排除下是否是时间轴问题等。

**Comment by SiIentZephyrus** [comment]
https://mega.nz/folder/h7gClQZa#7kNKKvcumAADh7f98KrEVQ
两个字幕都是自动下的，S05E02就能正常在emby上显示，而E03就显示不出来，但是使用potplayer播放都是能正常看的。

还有一个小问题，我每次重启容器之后，会进行一次下载字幕操作，有时候这个操作会把我emby媒体库里面的资源全部清除掉，要重新点击扫描媒体库才能恢复。

**Comment by SiIentZephyrus** [comment]
https://mega.nz/file/Jr4iDQAK#LfLIkIewwzvc0RiEwcH4ZEhzPJ5Id80di0lmalOiohE
这个是上面说的清空emby媒体库的日志文件

**Comment by allanpk716** [comment]
> https://mega.nz/file/Jr4iDQAK#LfLIkIewwzvc0RiEwcH4ZEhzPJ5Id80di0lmalOiohE 这个是上面说的清空emby媒体库的日志文件

不太理解你说的清空媒体库的意思，日志看起来只有超时，而且没有进行下载。

**Comment by allanpk716** [comment]
> https://mega.nz/folder/h7gClQZa#7kNKKvcumAADh7f98KrEVQ 两个字幕都是自动下的，S05E02就能正常在emby上显示，而E03就显示不出来，但是使用potplayer播放都是能正常看的。
> 
> 还有一个小问题，我每次重启容器之后，会进行一次下载字幕操作，有时候这个操作会把我emby媒体库里面的资源全部清除掉，要重新点击扫描媒体库才能恢复。

感觉是 Emby 的问题，本程序只有刷新单个视频的操作（接口是 Emby 的）

**Comment by SiIentZephyrus** [comment]
关于清空媒体库就是类似emby清空了数据库，但是文件还是都存在的，就是页面上找不到视频了，要重新进行扫描才能找回。关于这个问题并不是经常发生，每次重启docker之后有概率会发生这个情况，清空的也正好是我要下字幕的那两个媒体库。

**Comment by allanpk716** [comment]
> 关于清空媒体库就是类似emby清空了数据库，但是文件还是都存在的，就是页面上找不到视频了，要重新进行扫描才能找回。关于这个问题并不是经常发生，每次重启docker之后有概率会发生这个情况，清空的也正好是我要下字幕的那两个媒体库。

Emby 什么版本的？你日志上 Emby 的 API 操作能超时，这个就有问题。一般局域网的话不应该。

**Comment by SiIentZephyrus** [comment]
emby：4.6.4，运行在群晖套件中

**Comment by allanpk716** [comment]
想不出问题点，要不你先关闭 Emby API 功能吧。

**Comment by BrikerMan** [comment]
遇到一样的问题了，也没有头绪。我是群晖中使用 docker 跑的
Emby: 4.6.7.0
chinesesubfinder: v0.19.6

一个奇怪的现象， The Bing Bang Theory S1 全部字幕下载完毕，但都看不到下载的字幕。
如果我在 S01E01 播放页面点击下载字幕，随便下载一个，然后就可以看到之前 chinesesubfinder 下载好的字幕。

尝试了关闭 Emby API 功能，没有效果。

**Comment by allanpk716** [comment]
> 遇到一样的问题了，也没有头绪。我是群晖中使用 docker 跑的 Emby: 4.6.7.0 chinesesubfinder: v0.19.6
> 
> 一个奇怪的现象， The Bing Bang Theory S1 全部字幕下载完毕，但都看不到下载的字幕。 如果我在 S01E01 播放页面点击下载字幕，随便下载一个，然后就可以看到之前 chinesesubfinder 下载好的字幕。
> 
> 尝试了关闭 Emby API 功能，没有效果。

能截图看看你下载好的字幕以及视频列表吗？挺好奇啥情况的

**Comment by BrikerMan** [comment]
> > 遇到一样的问题了，也没有头绪。我是群晖中使用 docker 跑的 Emby: 4.6.7.0 chinesesubfinder: v0.19.6
> > 一个奇怪的现象， The Bing Bang Theory S1 全部字幕下载完毕，但都看不到下载的字幕。 如果我在 S01E01 播放页面点击下载字幕，随便下载一个，然后就可以看到之前 chinesesubfinder 下载好的字幕。
> > 尝试了关闭 Emby API 功能，没有效果。
> 
> 能截图看看你下载好的字幕以及视频列表吗？挺好奇啥情况的

我重启了一顿，一顿操作后现在有正常了。还在总结规律。我看看能不能复现出来。现在这个配置，运行正常了。

```yaml
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 1
RunAtStartup: true
SaveMultiSub: true
MovieFolder: /media/电影
SeriesFolder: /media/tv
EmbyConfig:
    Url: http://192.168.2.5:8096
    ApiKey: xxxxxxxxxx
    LimitCount: 3000
    SkipWatched: false
```

**Comment by allanpk716** [comment]
猜测是 Emby 媒体库刷新的问题，虽然程序在下载完毕后会统一刷新刚才下载的视频，看来 Emby 没有真正刷新（就我测试的情况是可以刷新，也许是它的bug）。

**Comment by fkueyu** [comment]
应该是ass字幕的字体问题
