### ISSUE TITLE
可以把配置文件中的”电影“”电视剧“的目录名称换成英文吗？

### ISSUE THREAD

**Issue by luotao21** [allanpk716/ChineseSubFinder#110]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.7 市场中下载的

环境:群晖 docker

## 你想要新增或者改进什么功能？
希望能将默认配置文件中的”电影“”电视剧“中文目录名称改为英文的，因为在英文的软件上，无法输入中文路径，比如英文版Kodi。
以下是第三方教程中建议的目录结构，仅供参考。
--media
 |--downloads
 |--movies
 |--tv
 |--others

**Comment by allanpk716** [comment]
支持的，示例是举例而已，为了中文用户好看，具体用什么文件夹又使用者自行修改即可。但是请自己理解映射的关系，有相关文档说明的。看看主页中的教程和建议文档。
