### ISSUE TITLE
不能下载字幕

### ISSUE THREAD

**Issue by lugasg** [allanpk716/ChineseSubFinder#111]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.7

环境: docker （on DSM）

## 你遇到什么问题了？

在first download以后就没有了动静。第一次使用。字幕没有被下载

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

能够下载字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

目录已经用tmm清理过了的。有同文件名的nfo。

视频的目录: \video\movie\万世魔星 (1979)

视频的信息: 万世魔星 (1979) 1080p DTS.mkv
![image](https://user-images.githubusercontent.com/94726724/142710307-67fe07ba-f467-40a4-8aa4-21c565976ff8.png)

## 出错的日志信息可以复制一些出来吗？
...
[INFO]: 2021-11-19 17:33:02 - Download One End...
[INFO]: 2021-11-19 17:33:02 - First Time Download End

[INFO]: 2021-11-19 22:52:02 - ChineseSubFinder Version: v0.18.7
[INFO]: 2021-11-19 22:52:02 - UseProxy = false
[INFO]: 2021-11-19 22:52:02 - MovieFolder: /media/电影
[INFO]: 2021-11-19 22:52:02 - SeriesFolder: /media/连续剧
[INFO]: 2021-11-19 22:52:02 - HotFix Start...
[INFO]: 2021-11-19 22:52:02 - HotFix End
[INFO]: 2021-11-19 22:52:02 - Change Sub Name Format Start...
[INFO]: 2021-11-19 22:52:02 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-11-19 22:52:02 - Change Sub Name Format End
[INFO]: 2021-11-19 22:52:02 - First Time Download Start
[INFO]: 2021-11-19 22:52:02 - Download One Started...
[INFO]: 2021-11-19 22:52:03 - Refresh Emby Sub List Success
[INFO]: 2021-11-19 22:52:10 - Download Movie Sub Started...
[INFO]: 2021-11-19 22:52:10 - Movie Sub Dl From Emby API...
[INFO]: 2021-11-19 22:52:10 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-11-19 22:52:10 - Download Movie Sub End...
[INFO]: 2021-11-19 22:52:10 - Download Series Sub Started...
[INFO]: 2021-11-19 22:52:10 - Download Series Sub End...
[INFO]: 2021-11-19 22:53:33 - Refresh Emby Sub List Success
[INFO]: 2021-11-19 22:53:33 - Auto Fix Sub Timeline Start...
[INFO]: 2021-11-19 22:53:33 - Auto Fix Sub Timeline End
[INFO]: 2021-11-19 22:53:36 - Refresh Emby Sub List Success
[INFO]: 2021-11-19 22:53:36 - Download One End...
[INFO]: 2021-11-19 22:53:36 - First Time Download End

**Comment by allanpk716** [comment]
1. 你可以开启 `DebugMode: true`，会有详细一些的日志。
2. 你现在的日志提示是没有需要下载字幕，而且速度很快（1s 内完成电影和连续剧扫描）。看看下面两个文档，确认下跳过的原因。
3. 你的配置文件也发一下吧

[如何判断视频是否需要下载、更新字幕的](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md)

[高阶设置 - Emby API 支持](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md)

**Comment by lugasg** [comment]
感谢回复。好像是挂载路径原本设置的是中文的，\media\电影，而emby里面设置的是\media\movie，导致虽然subfinder能找到路径，可是与emby不同。按照高阶设置里面改好后，有在下载了。多谢帮助！
