### ISSUE TITLE
刮削不到字幕了

### ISSUE THREAD

**Issue by laobanbiefangcu** [allanpk716/ChineseSubFinder#112]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: ChineseSubFinder Version: v0.18.7

环境: docker or Window or Linux or MAC
Unraid

描述一下你遇到的问题
下载新电影（比如毒液2）不会刮削字幕，显示Movie Sub Dl From Emby API no movie need Dl sub

能够重新，不能够重现
能够重现

能够搜到需要下载字幕的电影
描述以下你期望的结果

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: H:\PT\movie\Venom Let There Be Carnage (2021)

视频的信息: Venom Let There Be Carnage (2021) WEBDL-2160p.mkv

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
[INFO]: 2021-11-23 16:16:40 - ChineseSubFinder Version: v0.18.7

[INFO]: 2021-11-23 16:16:40 - UseProxy = false
[INFO]: 2021-11-23 16:16:40 - MovieFolder: /media/movie
[INFO]: 2021-11-23 16:16:40 - SeriesFolder: /media/tv
[INFO]: 2021-11-23 16:16:40 - HotFix Start...
[INFO]: 2021-11-23 16:16:40 - HotFix End
[INFO]: 2021-11-23 16:16:40 - Change Sub Name Format Start...
[INFO]: 2021-11-23 16:16:40 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-11-23 16:16:40 - Change Sub Name Format End
[INFO]: 2021-11-23 16:16:40 - First Time Download Start
[INFO]: 2021-11-23 16:16:40 - Download One Started...
[INFO]: 2021-11-23 16:16:41 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 16:16:43 - Download Movie Sub Started...
[INFO]: 2021-11-23 16:16:43 - Movie Sub Dl From Emby API...
[INFO]: 2021-11-23 16:16:43 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-11-23 16:16:43 - Download Movie Sub End...
[INFO]: 2021-11-23 16:16:43 - Download Series Sub Started...
[INFO]: 2021-11-23 16:16:43 - Download Series Sub End...
[INFO]: 2021-11-23 16:16:43 - Download Movie Sub Started...
[INFO]: 2021-11-23 16:16:43 - Movie Sub Dl From Emby API...
[INFO]: 2021-11-23 16:16:43 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-11-23 16:16:43 - Download Movie Sub End...
[INFO]: 2021-11-23 16:16:43 - Download Series Sub Started...
[INFO]: 2021-11-23 16:16:43 - Download Series Sub End...
[INFO]: 2021-11-23 16:16:43 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 16:16:43 - Auto Fix Sub Timeline Start...
[INFO]: 2021-11-23 16:16:43 - Auto Fix Sub Timeline End
[INFO]: 2021-11-23 16:16:44 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 16:16:44 - Download One End...
[INFO]: 2021-11-23 16:16:44 - First Time Download End

**Comment by laobanbiefangcu** [comment]
不知道是emby的问题还是什么， 就是会显示没有电影需要下载字幕。看了一下api也是正常的

**Comment by allanpk716** [comment]
见 #111 的回复，提供更多信息。以及自己定位下问题。

**Comment by laobanbiefangcu** [comment]
> 见 #111 的回复，提供更多信息。以及自己定位下问题。
已开启DebugMode: true，然后重启后log显示如下，就卡在hotfix 001 start了
[INFO]: 2021-11-23 16:51:23 - ChineseSubFinder Version: v0.18.7

[INFO]: 2021-11-23 16:51:23 - UseProxy = false
[INFO]: 2021-11-23 16:51:23 - MovieFolder: /media/电影
[INFO]: 2021-11-23 16:51:23 - SeriesFolder: /media/连续剧
[INFO]: 2021-11-23 16:51:23 - HotFix Start...
[INFO]: 2021-11-23 16:51:23 - hotfix 001 start..

**Comment by allanpk716** [comment]
> > 见 #111 的回复，提供更多信息。以及自己定位下问题。
> 
> 已开启DebugMode: true，然后重启后log显示如下，就卡在hotfix 001 start了 [INFO]: 2021-11-23 16:51:23 - ChineseSubFinder Version: v0.18.7
> 
> [INFO]: 2021-11-23 16:51:23 - UseProxy = false [INFO]: 2021-11-23 16:51:23 - MovieFolder: /media/电影 [INFO]: 2021-11-23 16:51:23 - SeriesFolder: /media/连续剧 [INFO]: 2021-11-23 16:51:23 - HotFix Start... [INFO]: 2021-11-23 16:51:23 - hotfix 001 start..

等程序处理

**Comment by laobanbiefangcu** [comment]
> > > 见 #111 的回复，提供更多信息。以及自己定位下问题。
> > 
> > 
> > 已开启DebugMode: true，然后重启后log显示如下，就卡在hotfix 001 start了 [INFO]: 2021-11-23 16:51:23 - ChineseSubFinder Version: v0.18.7
> > [INFO]: 2021-11-23 16:51:23 - UseProxy = false [INFO]: 2021-11-23 16:51:23 - MovieFolder: /media/电影 [INFO]: 2021-11-23 16:51:23 - SeriesFolder: /media/连续剧 [INFO]: 2021-11-23 16:51:23 - HotFix Start... [INFO]: 2021-11-23 16:51:23 - hotfix 001 start..
> 
> 等程序处理

[INFO]: 2021-11-23 17:25:21 - ChineseSubFinder Version: v0.18.7

[INFO]: 2021-11-23 17:25:21 - UseProxy = false
[INFO]: 2021-11-23 17:25:21 - MovieFolder: /media/电影
[INFO]: 2021-11-23 17:25:21 - SeriesFolder: /media/连续剧
[INFO]: 2021-11-23 17:25:21 - HotFix Start...
[INFO]: 2021-11-23 17:25:21 - HotFix End
[INFO]: 2021-11-23 17:25:21 - Change Sub Name Format Start...
[INFO]: 2021-11-23 17:25:21 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-11-23 17:25:21 - Change Sub Name Format End
[INFO]: 2021-11-23 17:25:21 - First Time Download Start
[INFO]: 2021-11-23 17:25:21 - Download One Started...
[INFO]: 2021-11-23 17:25:21 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 17:25:23 - Download Movie Sub Started...
[INFO]: 2021-11-23 17:25:23 - Movie Sub Dl From Emby API...
[INFO]: 2021-11-23 17:25:23 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-11-23 17:25:23 - Download Movie Sub End...
[INFO]: 2021-11-23 17:25:23 - Download Series Sub Started...
[INFO]: 2021-11-23 17:25:23 - Download Series Sub End...
[INFO]: 2021-11-23 17:25:24 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 17:25:24 - Auto Fix Sub Timeline Start...
[INFO]: 2021-11-23 17:25:24 - Auto Fix Sub Timeline End
[INFO]: 2021-11-23 17:25:24 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 17:25:24 - Download One End...
[INFO]: 2021-11-23 17:25:24 - First Time Download End

映射路径我觉得应该不会出错
docker create \
  --name=chinesesubfinder  \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Asia/Shanghai \
  -v /mnt/user/appdata/chinesesubfinder:/config \
  -v /mnt/user/PT/movie:/media/电影 \
  -v /mnt/user/PT/tv:/media/连续剧 \
  allanpk716/chinesesubfinder:latest


emby的映射路径
mnt/user/PT/movie:/movies
mnt/user/PT/tv:/tv

**Comment by allanpk716** [comment]
1. 程序执行正常的，能够获取 emby 的视频信息  [DEBUG]: 2021-11-23 17:31:12 - GetRecentlyAddVideoList - GetRecentlyItems Count 900
2. Venom Let There Be Carnage (2021) 首先要 Emby 它自己扫描后，才能传递过来，这个你需要去 Emby 中确认
3. 900 个的参数，是最近的数据，而且是 Emby 所有视频的排序，如果你有 moive 和 TV 之外的最新被 Emby 扫描到的，也会被获取到，从而挤兑掉了 movie 和 tv 新视频的更新排序，建议的提高数量再试试。这个你得排除是否是第一次使用 Emby。如果是第一次，那么设置一个较大的值，比如 5000
4. 你的 Emby 映射逻辑跟文档有差异，可能存在无法转换。https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md

**Comment by laobanbiefangcu** [comment]
> 1. 程序执行正常的，能够获取 emby 的视频信息  [DEBUG]: 2021-11-23 17:31:12 - GetRecentlyAddVideoList - GetRecentlyItems Count 900
> 2. Venom Let There Be Carnage (2021) 首先要 Emby 它自己扫描后，才能传递过来，这个你需要去 Emby 中确认
> 3. 900 个的参数，是最近的数据，而且是 Emby 所有视频的排序，如果你有 moive 和 TV 之外的最新被 Emby 扫描到的，也会被获取到，从而挤兑掉了 movie 和 tv 新视频的更新排序，建议的提高数量再试试。这个你得排除是否是第一次使用 Emby。如果是第一次，那么设置一个较大的值，比如 5000
> 4. 你的 Emby 映射逻辑跟文档有差异，可能存在无法转换。https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md
LimitCount设置5000后，又继续重新映射两个docker路径后

emby的映射路径
/mnt/user/PT/movie:/media/movies
/mnt/user/PT/tv:/media/tv

chinesesubfinder
/mnt/user/PT/movie:/media/movies
/mnt/user/PT/tv:/media/tv


最后log还是显示这样
[INFO]: 2021-11-23 21:16:27 - ChineseSubFinder Version: v0.18.7

[INFO]: 2021-11-23 21:16:27 - UseProxy = false
[INFO]: 2021-11-23 21:16:27 - MovieFolder: /media/movie
[INFO]: 2021-11-23 21:16:27 - SeriesFolder: /media/tv
[INFO]: 2021-11-23 21:16:27 - HotFix Start...
[INFO]: 2021-11-23 21:16:27 - HotFix End
[INFO]: 2021-11-23 21:16:27 - Change Sub Name Format Start...
[INFO]: 2021-11-23 21:16:27 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-11-23 21:16:27 - Change Sub Name Format End
[INFO]: 2021-11-23 21:16:27 - First Time Download Start
[INFO]: 2021-11-23 21:16:27 - Download One Started...
[DEBUG]: 2021-11-23 21:16:27 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-23 21:16:27 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 938
[INFO]: 2021-11-23 21:16:28 - Refresh Emby Sub List Success
[DEBUG]: 2021-11-23 21:16:28 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-23 21:16:28 - GetRecentlyAddVideoList - GetRecentlyItems Count 938
[DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap Start
[DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap End
[DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList Start
[DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList End
[INFO]: 2021-11-23 21:16:30 - Download Movie Sub Started...
[INFO]: 2021-11-23 21:16:30 - Movie Sub Dl From Emby API...
[INFO]: 2021-11-23 21:16:30 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-11-23 21:16:30 - Download Movie Sub End...
[INFO]: 2021-11-23 21:16:30 - Download Series Sub Started...
[INFO]: 2021-11-23 21:16:30 - Download Series Sub End...
[DEBUG]: 2021-11-23 21:16:30 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-23 21:16:30 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 938
[INFO]: 2021-11-23 21:16:30 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 21:16:30 - Auto Fix Sub Timeline Start...
[DEBUG]: 2021-11-23 21:16:30 - EmbyConfig.FixTimeLine = false, Skip
[INFO]: 2021-11-23 21:16:30 - Auto Fix Sub Timeline End
[DEBUG]: 2021-11-23 21:16:30 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-23 21:16:30 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 938
[INFO]: 2021-11-23 21:16:31 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 21:16:31 - Download One End...
[INFO]: 2021-11-23 21:16:31 - First Time Download End
[INFO]: 2021-11-23 21:16:31 - Refresh Emby Sub List Success
[INFO]: 2021-11-23 21:16:31 - Download One End...
[INFO]: 2021-11-23 21:16:31 - First Time Download End

**Comment by allanpk716** [comment]
> > 1. 程序执行正常的，能够获取 emby 的视频信息  [DEBUG]: 2021-11-23 17:31:12 - GetRecentlyAddVideoList - GetRecentlyItems Count 900
> 
> > 2. Venom Let There Be Carnage (2021) 首先要 Emby 它自己扫描后，才能传递过来，这个你需要去 Emby 中确认
> 
> > 3. 900 个的参数，是最近的数据，而且是 Emby 所有视频的排序，如果你有 moive 和 TV 之外的最新被 Emby 扫描到的，也会被获取到，从而挤兑掉了 movie 和 tv 新视频的更新排序，建议的提高数量再试试。这个你得排除是否是第一次使用 Emby。如果是第一次，那么设置一个较大的值，比如 5000
> 
> > 4. 你的 Emby 映射逻辑跟文档有差异，可能存在无法转换。https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md
> 
> 
> 
> 
> 
> 
> 
> LimitCount设置5000后，又继续重新映射两个docker路径后
> 
> 
> 
> emby的映射路径
> 
> /mnt/user/PT/movie:/media/movies
> 
> /mnt/user/PT/tv:/media/tv
> 
> 
> 
> chinesesubfinder
> 
> /mnt/user/PT/movie:/media/movies
> 
> /mnt/user/PT/tv:/media/tv
> 
> 配置：
> 
> UseProxy: false
> 
> HttpProxy: http://127.0.0.1:10809
> 
> EveryTime: 1h
> 
> Threads: 2
> 
> RunAtStartup: true
> 
> MovieFolder: /media/movie
> 
> SeriesFolder: /media/tv
> 
> DebugMode: true
> 
> 
> 
> EmbyConfig:
> 
>     Url: http://192.168.1.131:8097
> 
>     ApiKey: ******8f66e4d8e49e3a9666d19d79a828d
> 
>     LimitCount: 5000
> 
>     SkipWatched: false
> 
> 
> 
> 最后log还是显示这样
> 
> [INFO]: 2021-11-23 21:16:27 - ChineseSubFinder Version: v0.18.7
> 
> 
> 
> [INFO]: 2021-11-23 21:16:27 - UseProxy = false
> 
> [INFO]: 2021-11-23 21:16:27 - MovieFolder: /media/movie
> 
> [INFO]: 2021-11-23 21:16:27 - SeriesFolder: /media/tv
> 
> [INFO]: 2021-11-23 21:16:27 - HotFix Start...
> 
> [INFO]: 2021-11-23 21:16:27 - HotFix End
> 
> [INFO]: 2021-11-23 21:16:27 - Change Sub Name Format Start...
> 
> [INFO]: 2021-11-23 21:16:27 - DesSubFormatter == LateTimeSubFormatter then skip process
> 
> [INFO]: 2021-11-23 21:16:27 - Change Sub Name Format End
> 
> [INFO]: 2021-11-23 21:16:27 - First Time Download Start
> 
> [INFO]: 2021-11-23 21:16:27 - Download One Started...
> 
> [DEBUG]: 2021-11-23 21:16:27 - Emby Setting SkipWatched = false
> 
> [DEBUG]: 2021-11-23 21:16:27 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 938
> 
> [INFO]: 2021-11-23 21:16:28 - Refresh Emby Sub List Success
> 
> [DEBUG]: 2021-11-23 21:16:28 - Emby Setting SkipWatched = false
> 
> [DEBUG]: 2021-11-23 21:16:28 - GetRecentlyAddVideoList - GetRecentlyItems Count 938
> 
> [DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap Start
> 
> [DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap End
> 
> [DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList Start
> 
> [DEBUG]: 2021-11-23 21:16:30 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList End
> 
> [INFO]: 2021-11-23 21:16:30 - Download Movie Sub Started...
> 
> [INFO]: 2021-11-23 21:16:30 - Movie Sub Dl From Emby API...
> 
> [INFO]: 2021-11-23 21:16:30 - Movie Sub Dl From Emby API no movie need Dl sub
> 
> [INFO]: 2021-11-23 21:16:30 - Download Movie Sub End...
> 
> [INFO]: 2021-11-23 21:16:30 - Download Series Sub Started...
> 
> [INFO]: 2021-11-23 21:16:30 - Download Series Sub End...
> 
> [DEBUG]: 2021-11-23 21:16:30 - Emby Setting SkipWatched = false
> 
> [DEBUG]: 2021-11-23 21:16:30 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 938
> 
> [INFO]: 2021-11-23 21:16:30 - Refresh Emby Sub List Success
> 
> [INFO]: 2021-11-23 21:16:30 - Auto Fix Sub Timeline Start...
> 
> [DEBUG]: 2021-11-23 21:16:30 - EmbyConfig.FixTimeLine = false, Skip
> 
> [INFO]: 2021-11-23 21:16:30 - Auto Fix Sub Timeline End
> 
> [DEBUG]: 2021-11-23 21:16:30 - Emby Setting SkipWatched = false
> 
> [DEBUG]: 2021-11-23 21:16:30 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 938
> 
> [INFO]: 2021-11-23 21:16:31 - Refresh Emby Sub List Success
> 
> [INFO]: 2021-11-23 21:16:31 - Download One End...
> 
> [INFO]: 2021-11-23 21:16:31 - First Time Download End
> 
> [INFO]: 2021-11-23 21:16:31 - Refresh Emby Sub List Success
> 
> [INFO]: 2021-11-23 21:16:31 - Download One End...
> 
> [INFO]: 2021-11-23 21:16:31 - First Time Download End

明天我加一下更详细的日志，推新版本

**Comment by allanpk716** [comment]
1. 推送了 v0.18.8，又加详细日志了，如果没有更多的定位需求，应该一段时间不打算再加类似的调试日志了，主要是这样的日志混在代码中“太难看了”，我想一下怎么改进日志这块先。
2. 输出的日志应该很多，麻烦把一次运行的输出都发上来吧。

**Comment by laobanbiefangcu** [comment]
可以正常下载字幕了，感谢作者更新
