### ISSUE TITLE
因为有三个月逻辑，我把原有字幕删除了，然后不刮削了。

### ISSUE THREAD

**Issue by mephisX** [allanpk716/ChineseSubFinder#113]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: Window

## 你遇到什么问题了？

因为有三个月逻辑，我把原有字幕删除了，然后不刮削了。

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

期望刮削到字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: E:\电视剧\黄石公园 (2018)

## 出错的日志信息可以复制一些出来吗？

`[INFO]: 2021-11-24 11:19:55 - ChineseSubFinder Version: v0.18.8
[INFO]: 2021-11-24 11:19:55 - UseProxy = false
[INFO]: 2021-11-24 11:19:55 - MovieFolder: D:\电影
[INFO]: 2021-11-24 11:19:55 - SeriesFolder: E:\电视剧
[INFO]: 2021-11-24 11:19:55 - HotFix Start...
[INFO]: 2021-11-24 11:19:55 - HotFix End
[INFO]: 2021-11-24 11:19:55 - Change Sub Name Format Start...
[INFO]: 2021-11-24 11:19:55 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-11-24 11:19:55 - Change Sub Name Format End
[INFO]: 2021-11-24 11:19:55 - First Time Download Start
[INFO]: 2021-11-24 11:19:55 - Download One Started...
[DEBUG]: 2021-11-24 11:19:55 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-24 11:19:55 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 0
[INFO]: 2021-11-24 11:19:55 - Refresh Emby Sub List Success
[DEBUG]: 2021-11-24 11:19:55 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - GetRecentlyAddVideoList - GetRecentlyItems Count 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterEmbyVideoList found valid movie 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterEmbyVideoList found valid series 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterNoChineseSubVideoList found no chinese movie 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterNoChineseSubVideoList found no chinese series 0
[DEBUG]: 2021-11-24 11:19:55 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap Start
[DEBUG]: 2021-11-24 11:19:55 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap End
[DEBUG]: 2021-11-24 11:19:55 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList Start
[DEBUG]: 2021-11-24 11:19:55 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList End
[INFO]: 2021-11-24 11:19:55 - Download Movie Sub Started...
[INFO]: 2021-11-24 11:19:55 - Movie Sub Dl From Emby API...
[INFO]: 2021-11-24 11:19:55 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-11-24 11:19:55 - Download Movie Sub End...
[INFO]: 2021-11-24 11:19:55 - Download Series Sub Started...
[INFO]: 2021-11-24 11:19:55 - Download Series Sub End...
[DEBUG]: 2021-11-24 11:19:55 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-24 11:19:55 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 0
[INFO]: 2021-11-24 11:19:55 - Refresh Emby Sub List Success
[INFO]: 2021-11-24 11:19:55 - Auto Fix Sub Timeline Start...
[DEBUG]: 2021-11-24 11:19:55 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - GetRecentlyAddVideoList - GetRecentlyItems Count 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterEmbyVideoList found valid movie 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterEmbyVideoList found valid series 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterNoChineseSubVideoList found no chinese movie 0
[DEBUG]: 2021-11-24 11:19:55 - -----------------
[DEBUG]: 2021-11-24 11:19:55 - filterNoChineseSubVideoList found no chinese series 0
[DEBUG]: 2021-11-24 11:19:55 - FixRecentlyItemsSubTimeline - DebugInfo - movieList Start
[DEBUG]: 2021-11-24 11:19:55 - FixRecentlyItemsSubTimeline - DebugInfo - movieList End
[DEBUG]: 2021-11-24 11:19:55 - FixRecentlyItemsSubTimeline - DebugInfo - seriesList Start
[DEBUG]: 2021-11-24 11:19:55 - FixRecentlyItemsSubTimeline - DebugInfo - seriesList End
[DEBUG]: 2021-11-24 11:19:55 - Start movieList fix Timeline
[DEBUG]: 2021-11-24 11:19:55 - End movieList fix Timeline
[DEBUG]: 2021-11-24 11:19:55 - Start seriesList fix Timeline
[DEBUG]: 2021-11-24 11:19:55 - End seriesList fix Timeline
[DEBUG]: 2021-11-24 11:19:55 - VAD Mode 3
[INFO]: 2021-11-24 11:19:55 - Auto Fix Sub Timeline End
[DEBUG]: 2021-11-24 11:19:55 - Emby Setting SkipWatched = false
[DEBUG]: 2021-11-24 11:19:55 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 0
[INFO]: 2021-11-24 11:19:55 - Refresh Emby Sub List Success
[INFO]: 2021-11-24 11:19:55 - Download One End...
[INFO]: 2021-11-24 11:19:55 - First Time Download End`

**Comment by allanpk716** [comment]
[强制扫描所有的视频文件下载字幕](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%BC%BA%E5%88%B6%E6%89%AB%E6%8F%8F%E6%89%80%E6%9C%89%E7%9A%84%E8%A7%86%E9%A2%91%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E5%AD%97%E5%B9%95.md)
