### ISSUE TITLE
这个程序适配jellyfin的api吗？

### ISSUE THREAD

**Issue by PQ0000** [allanpk716/ChineseSubFinder#114]
按照作者的指示去配置好之后没有成功  
看了日志是说 获取emby api 然后提示不需要D1 sub 然后就结束了 
直接从jellyfin获取api后填入了示例中
启动程序后在添加视频进入jellyfin
添加视频后在启动  返回结果一样
是哪里出了问题 哈哈

**Comment by allanpk716** [comment]
暂时不支持，相关讨论可以见 #100

**Comment by PQ0000** [comment]
好的 辛苦了，程序很好用，加油

在 2021-11-25 19:14:56，"Chin allan" ***@***.***> 写道：


暂时不支持，相关讨论可以见 #100

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by allanpk716** [comment]
> 好的 辛苦了，程序很好用，加油 在 2021-11-25 19:14:56，"Chin allan" ***@***.***> 写道： 暂时不支持，相关讨论可以见 #100 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

多谢支持，有什么在反馈。
