### ISSUE TITLE
shooter api error

### ISSUE THREAD

**Issue by shcjosh** [allanpk716/ChineseSubFinder#118]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: docker @ unraid

## 你遇到什么问题了？

於log中不斷顯示有個shooter的error
====
2021/12/06 17:40:23.567908 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 1

2021/12/06 17:40:23.748689 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 2

[ERROR]: 2021-12-06 17:40:23 - Yellowjackets 第一季
===
2021/12/06 17:40:10.246415 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 1

2021/12/06 17:40:10.427320 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 2

2021/12/06 17:40:10.683025 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 3

[ERROR]: 2021-12-06 17:40:10 - 23 shooter GetSubListFromFile4Series Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn

## 你的问题弄重现嘛？

每次執行字幕搜尋時皆會出現

## 你期望的结果

可以正常從shooter下載字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

每次執行shooter皆會出現

## 出错的日志信息可以复制一些出来吗？

2021/12/06 17:40:18.117031 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 1

2021/12/06 17:40:18.297381 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 2

2021/12/06 17:40:18.494119 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 3

[ERROR]: 2021-12-06 17:40:18 - 24 shooter GetSubListFromFile4Series Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn

[INFO]: 2021-12-06 17:40:18 - 24 shooter End...
[INFO]: 2021-12-06 17:40:19 - 23 zimuku End...
[INFO]: 2021-12-06 17:40:19 - 23 DlSub End /media/tv/The Wheel of Time
[INFO]: 2021-12-06 17:40:23 - 25 DlSub Start /media/tv/Yellowjackets
[INFO]: 2021-12-06 17:40:23 - Yellowjackets IMDB ID: tt11041332 NeedDownloadSubs: 4
[INFO]: 2021-12-06 17:40:23 - S1E1
[INFO]: 2021-12-06 17:40:23 - S1E2
[INFO]: 2021-12-06 17:40:23 - S1E3
[INFO]: 2021-12-06 17:40:23 - S1E4
[INFO]: 2021-12-06 17:40:23 - 25 shooter Start...
[INFO]: 2021-12-06 17:40:23 - 25 zimuku Start...
[INFO]: 2021-12-06 17:40:23 - 25 xunlei Start...
2021/12/06 17:40:23.567908 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 1

2021/12/06 17:40:23.748689 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 2

[ERROR]: 2021-12-06 17:40:23 - Yellowjackets 第一季

[INFO]: 2021-12-06 17:40:23 - Retry Yellowjackets
2021/12/06 17:40:23.997177 ERROR RESTY Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn, Attempt 3

[INFO]: 2021-12-06 17:40:24 - 24 xunlei End...
[ERROR]: 2021-12-06 17:40:24 - 25 shooter GetSubListFromFile4Series Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn

[INFO]: 2021-12-06 17:40:24 - 25 shooter End...
[INFO]: 2021-12-06 17:40:25 - ZiMuKu Not Find Sub can be download Yellowjackets 1 3
[INFO]: 2021-12-06 17:40:25 - ZiMuKu Not Find Sub can be download Yellowjackets 1 4
[INFO]: 2021-12-06 17:40:25 - ZiMuKu Not Find Sub can be download Yellowjackets 1 1
[INFO]: 2021-12-06 17:40:25 - 25 xunlei End...
[INFO]: 2021-12-06 17:40:26 - 25 zimuku End...
[INFO]: 2021-12-06 17:40:26 - 25 DlSub End /media/tv/Yellowjackets
[INFO]: 2021-12-06 17:40:29 - Skip 逆局 Sub Download, because series is Chinese
[INFO]: 2021-12-06 17:40:29 - no sub found 逆局
[INFO]: 2021-12-06 17:40:36 - 24 zimuku End...
[INFO]: 2021-12-06 17:40:36 - 24 DlSub End /media/tv/What If…!
[INFO]: 2021-12-06 17:40:36 - Download Series Sub End...
[INFO]: 2021-12-06 17:40:36 - Auto Fix Sub Timeline Start...
[INFO]: 2021-12-06 17:40:36 - Auto Fix Sub Timeline End
[INFO]: 2021-12-06 17:40:36 - Download One End...
[INFO]: 2021-12-06 17:40:36 - First Time Download End

**Comment by allanpk716** [comment]
应该这个网站更新了 https 证书，需要等缓存更新。建议的清理 docker ，重新开一次，应该就好了的。

**Comment by shcjosh** [comment]
瞭解 謝謝你
