### ISSUE TITLE
無法從射手網下載字幕

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#119]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 0.18.8

环境: docker / Synology NAS DSM7

## 你遇到什么问题了？

沒法下載字幕

## 你的问题弄重现嘛？

能夠

## 你期望的结果

能正常下載字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

![image](https://user-images.githubusercontent.com/66216186/144865915-7d18e8f3-d0b5-45bc-9efa-44f4b7152460.png)
![image](https://user-images.githubusercontent.com/66216186/144866260-29f00d88-7f31-4818-b371-9abafdeca2aa.png)

**Comment by allanpk716** [comment]
应该这个网站更新了 https 证书，需要等缓存更新。建议的清理 docker ，重新开一次，应该就好了的。
