### ISSUE TITLE
Jellyfin，配置了EmbyConfig，无法获取最新电影并下载字幕

### ISSUE THREAD

**Issue by frank-we** [allanpk716/ChineseSubFinder#120]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: Docker

## 你遇到什么问题了？

使用Jellyfin，配置了EmbyConfig，却一直无法自动关联下载最新电影的字幕。
在Jellyfin中配置刮削并由Jellyfin生成NFO文件。

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

自动关联下载最新电影的字幕。

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: /video-cache/movies/Catch.Me.If.You.Can.2002.1080p.BluRay.x265-RARBG

视频的信息: Catch.Me.If.You.Can.2002.1080p.BluRay.x265-RARBG.mp4

## 出错的日志信息可以复制一些出来吗？

[INFO]: 2021-12-07 14:58:17 - ChineseSubFinder Version: v0.18.8
[INFO]: 2021-12-07 14:58:17 - UseProxy = false
[INFO]: 2021-12-07 14:58:17 - MovieFolder: /media/movies
[INFO]: 2021-12-07 14:58:17 - SeriesFolder: /media/tvShow/AmericanTv
[INFO]: 2021-12-07 14:58:17 - HotFix Start...
[INFO]: 2021-12-07 14:58:17 - HotFix End
[INFO]: 2021-12-07 14:58:17 - Change Sub Name Format Start...
[INFO]: 2021-12-07 14:58:17 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-12-07 14:58:17 - Change Sub Name Format End
[INFO]: 2021-12-07 14:58:17 - First Time Download Start
[INFO]: 2021-12-07 14:58:17 - Download One Started...
[DEBUG]: 2021-12-07 14:58:17 - Emby Setting SkipWatched = false
[DEBUG]: 2021-12-07 14:58:17 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 0
[INFO]: 2021-12-07 14:58:17 - Refresh Emby Sub List Success
[DEBUG]: 2021-12-07 14:58:17 - Emby Setting SkipWatched = false
[DEBUG]: 2021-12-07 14:58:17 - -----------------
[DEBUG]: 2021-12-07 14:58:17 - GetRecentlyAddVideoList - GetRecentlyItems Count 0
[DEBUG]: 2021-12-07 14:58:17 - -----------------
[DEBUG]: 2021-12-07 14:58:17 - filterEmbyVideoList found valid movie 0
[DEBUG]: 2021-12-07 14:58:17 - -----------------
[DEBUG]: 2021-12-07 14:58:17 - filterEmbyVideoList found valid series 0
[DEBUG]: 2021-12-07 14:58:17 - -----------------
[DEBUG]: 2021-12-07 14:58:17 - filterNoChineseSubVideoList found no chinese movie 0
[DEBUG]: 2021-12-07 14:58:17 - -----------------
[DEBUG]: 2021-12-07 14:58:17 - filterNoChineseSubVideoList found no chinese series 0
[DEBUG]: 2021-12-07 14:58:17 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap Start
[DEBUG]: 2021-12-07 14:58:17 - GetUpdateVideoListFromEmby - DebugInfo - seriesSubNeedDlMap End
[DEBUG]: 2021-12-07 14:58:17 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList Start
[DEBUG]: 2021-12-07 14:58:17 - GetUpdateVideoListFromEmby - DebugInfo - movieFileFullPathList End
[INFO]: 2021-12-07 14:58:17 - Download Movie Sub Started...
[INFO]: 2021-12-07 14:58:17 - Movie Sub Dl From Emby API...
[INFO]: 2021-12-07 14:58:17 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-12-07 14:58:17 - Download Movie Sub End...
[INFO]: 2021-12-07 14:58:17 - Download Series Sub Started...
[INFO]: 2021-12-07 14:58:17 - Download Series Sub End...
[DEBUG]: 2021-12-07 14:58:17 - Emby Setting SkipWatched = false
[DEBUG]: 2021-12-07 14:58:17 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 0
[INFO]: 2021-12-07 14:58:17 - Refresh Emby Sub List Success
[INFO]: 2021-12-07 14:58:17 - Auto Fix Sub Timeline Start...
[DEBUG]: 2021-12-07 14:58:17 - EmbyConfig.FixTimeLine = false, Skip
[INFO]: 2021-12-07 14:58:17 - Auto Fix Sub Timeline End
[DEBUG]: 2021-12-07 14:58:17 - Emby Setting SkipWatched = false
[DEBUG]: 2021-12-07 14:58:17 - RefreshRecentlyVideoInfo - GetRecentlyItems Count 0
[INFO]: 2021-12-07 14:58:17 - Refresh Emby Sub List Success
[INFO]: 2021-12-07 14:58:17 - Download One End...
[INFO]: 2021-12-07 14:58:17 - First Time Download End

**Comment by allanpk716** [comment]
#114

**Comment by frank-we** [comment]
> #100 #114

噢噢，谢谢回复，那我试试定时任务啥的
