### ISSUE TITLE
是否支持电影存在多个不同目录呢？

### ISSUE THREAD

**Issue by toniexly** [allanpk716/ChineseSubFinder#121]
我的电影存在多个不同的位置，如/aa/MOVIE和/BB/movie  那么要如何 设置呢？目前我看好象只支持一个目录。

**Comment by allanpk716** [comment]
> 我的电影存在多个不同的位置，如/aa/MOVIE和/BB/movie  那么要如何 设置呢？目前我看好象只支持一个目录。

目前只能开两个程序来解决

**Comment by cute-angelia** [comment]
希望支持一下，配置文件可配置数组

我的文件夹一个是 movie 一个是 movie-child  还有几个是 movie-

现在就指定顶级文件夹

**Comment by allanpk716** [comment]
movie 应该支持嵌套了，但是依然有每个文件夹的格式规范。这个需求有人提了，后续会抽时间完成。

**Comment by allanpk716** [comment]
现在升级至 v0.20.x 应该可以满足你现在的需求。

**Comment by toniexly** [comment]
> 现在升级至 v0.20.x 应该可以满足你现在的需求。

太好了，我来更新试试
