### ISSUE TITLE
能否也下载英文字幕呀？

### ISSUE THREAD

**Issue by toniexly** [allanpk716/ChineseSubFinder#122]
如题，毕竟大部分电影是英语的，且英文字幕出最早，方便啃生肉的童鞋。

另：有些字幕语言后缀是zh-hans的，其实是中文，但现在是识别成未知语言，望修正。

**Comment by allanpk716** [comment]
> 如题，毕竟大部分电影是英语的，且英文字幕出最早，方便啃生肉的童鞋。
> 
> 
> 
> 另：有些字幕语言后缀是zh-hans的，其实是中文，但现在是识别成未知语言，望修正。

不是通过后缀名判断语言的，有问题可以上传有问题的字幕上来。不打算下载英文字幕。

**Comment by toniexly** [comment]
>
