### ISSUE TITLE
下载的字幕在文件名中多了00031或者00051

### ISSUE THREAD

**Issue by le0zh0u** [allanpk716/ChineseSubFinder#123]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: docker 

## 你遇到什么问题了？

下载的字幕在文件名中多了00031或者00051，导致字幕无法被识别出来

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

在00031之前加个.进行分隔，或者删除这个字符串

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: Hawkeye

视频的信息: Hawkeye.2021.S01E03.Echoes.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-TEPES[eztv.re]

## 出错的日志信息可以复制一些出来吗？

感觉不一定是出错

其他项目的相似问题：https://github.com/ausaki/subfinder/issues/76

**Comment by le0zh0u** [comment]
还有一个问题，日志中出现了，字幕跳过的记录，因为电影超过了2年。这个有什么背景吗

**Comment by allanpk716** [comment]
1. 你需要上传字幕上来看看，或者至少字幕具体的名称显示是什么样的
2. 内置字幕有中文，超过两年就可能会跳过  https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md

**Comment by le0zh0u** [comment]
你的邮件已收到。谢谢。~

**Comment by le0zh0u** [comment]
![image](https://user-images.githubusercontent.com/4425506/145739724-eb2b85ab-7da6-4530-a7f4-4523926e291b.png)

**Comment by allanpk716** [comment]
> ![image](https://user-images.githubusercontent.com/4425506/145739724-eb2b85ab-7da6-4530-a7f4-4523926e291b.png)

收到，我把字幕保存和重命名的方法给统一一下应该可以解决。等 v0.19.x ，还有一些坑没有踩完，争取年前发布。

**Comment by allanpk716** [comment]
我去检查了字幕保存的代码：internal/pkg/sub_formatter/emby/emby.go，这个之前重构过的，写入字幕时候，字幕的名称都是通过这个生成器做的，大概的意思是，通过视频文件名去生成字幕名称的。

以你现在截图来看，从这个视频不应该会出现这个字幕的 00031  00032 这样的后缀，除非是从视频文件名引入的。

写入字幕的代码都统一在一个地方了，见图1.

所以你得把程序的日志上传，具体写入字幕的时候会有记录，比如原始名称是什么，然后保存的名称是什么。见图2.你看看代码应该懂是指那些日志。有前缀的。

那么暂时不会归类为 bug。

## 图1
![image](https://user-images.githubusercontent.com/1176000/147657788-515a12bd-e674-4b41-8262-50fc8a03772f.png)

## 图2
![image](https://user-images.githubusercontent.com/1176000/147657918-f0af7b87-4691-45bf-a756-9453dbf35f37.png)

**Comment by le0zh0u** [comment]
你的邮件已收到。谢谢。~
