### ISSUE TITLE
部分剧集好像程序会识别错剧集的语言类型

### ISSUE THREAD

**Issue by fengdong1989** [allanpk716/ChineseSubFinder#124]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 最新版

环境: docker

## 你遇到什么问题了？

部分剧集好像程序会识别错剧集的语言类型
[WARNING]: 2021-12-14 23:33:15 - SkipChineseSeries /media/电视剧/My Name (2021) XML syntax error on line 30: invalid character entity &id (no semicolon)
[ERROR]: 2021-12-14 23:33:15 - subSupplierHub.DownloadSub4Series /media/电视剧/My Name (2021) ReadSeriesInfoFromDir /media/电视剧/My Name (2021) XML syntax error on line 30: invalid character entity &id (no semicolon)
[ERROR]: 2021-12-14 23:33:15 - DownloadSub4Series.NewPoolWithFunc done with Error ReadSeriesInfoFromDir /media/电视剧/My Name (2021) XML syntax error on line 30: invalid character entity &id (no semicolon)
line 30就是sonnar生成NFO信息的最后一行（所有不能刮削字幕的剧集都是这个提示，区别就是Line后面的行数不同）

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

不确定是程序识别问题还是各大剧集网站的语言标识类别本身有问题，但是剧不是中文剧毫无疑问

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: /media/电视剧/My Name (2021)

视频的信息: My Name - S01E01 - Episode 1.mp4

## 出错的日志信息可以复制一些出来吗？
可以

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs
[chinesesubfinder.csv](https://github.com/allanpk716/ChineseSubFinder/files/7715919/chinesesubfinder.csv)

**Comment by allanpk716** [comment]
你需要把 /media/电视剧/My Name (2021)  下面的剧集的配置信息发上来，nfo 或者是 xml 后缀名的。

**Comment by Jessie722** [comment]
是不是在sonarr-matadata里勾选了Series Metadata URL，取消再刷新库就可以了

**Comment by allanpk716** [comment]
> 是不是在sonarr-matadata里勾选了Series Metadata URL，取消再刷新库就可以了

我猜是 sonarr 写入连续剧的信息的时候不全，然后本程序去解析的时候挂了，这个需要你发送对应剧集的信息文件上来我看看，看看能解决没有。

如图举例：
## 图片1
![image](https://user-images.githubusercontent.com/1176000/146149660-e73b8dd1-6e8d-4ac9-bd5d-596a9652599b.png)


## 图片2
![image](https://user-images.githubusercontent.com/1176000/146149780-24a525cb-192d-47f6-a458-d90f5809be1a.png)

**Comment by Jessie722** [comment]
<img width="583" alt="Shot 12-15 at 16 23 54@2x" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了

**Comment by allanpk716** [comment]
> <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> 
> 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了

能发送有问题的这个文件上来吗？我看看怎么解决。

**Comment by fengdong1989** [comment]
> > <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> > 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了
> 
> 能发送有问题的这个文件上来吗？我看看怎么解决。
[tvshow.zip](https://github.com/allanpk716/ChineseSubFinder/files/7724468/tvshow.zip)
tvshow.nfo是剧元数据；
My Name - S01E01 - Episode 1.nfo是剧集元数据

**Comment by fengdong1989** [comment]
> <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> 
> 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了

感谢帮助，我去试试。

**Comment by fengdong1989** [comment]
> <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> 
> 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了

您好，我的sonarr界面好像跟您的不一样？
![image](https://user-images.githubusercontent.com/91931484/146308857-0a363f7b-7b2e-4fe6-9b5a-5c12954eacef.png)
![image](https://user-images.githubusercontent.com/91931484/146308885-f5191c70-9735-41ac-b976-fb45412bd978.png)
取消series Metadata后的界面就只有TVBD一行了
![image](https://user-images.githubusercontent.com/91931484/146309240-4ef31820-80ca-4f99-93b2-70b0eba16cb8.png)

**Comment by Jessie722** [comment]
> > <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> > 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了
> 
> 您好，我的sonarr界面好像跟您的不一样？ ![image](https://user-images.githubusercontent.com/91931484/146308857-0a363f7b-7b2e-4fe6-9b5a-5c12954eacef.png) ![image](https://user-images.githubusercontent.com/91931484/146308885-f5191c70-9735-41ac-b976-fb45412bd978.png) 取消series Metadata后的界面就只有TVBD一行了 ![image](https://user-images.githubusercontent.com/91931484/146309240-4ef31820-80ca-4f99-93b2-70b0eba16cb8.png)
<img width="658" alt="Shot 12-16 at 12 41 13@2x" src="https://user-images.githubusercontent.com/49652932/146309431-6450ee02-debe-47f4-945a-ed1f2b4e452e.png">
<img width="147" alt="Shot 12-16 at 12 41 17@2x" src="https://user-images.githubusercontent.com/49652932/146309436-0bd7ae79-9080-42b7-ad96-4743757c178d.png">s
是不是没开显示高级设置

**Comment by fengdong1989** [comment]
> > > <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> > > 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了
> > 
> > 
> > 您好，我的sonarr界面好像跟您的不一样？ ![image](https://user-images.githubusercontent.com/91931484/146308857-0a363f7b-7b2e-4fe6-9b5a-5c12954eacef.png) ![image](https://user-images.githubusercontent.com/91931484/146308885-f5191c70-9735-41ac-b976-fb45412bd978.png) 取消series Metadata后的界面就只有TVBD一行了 ![image](https://user-images.githubusercontent.com/91931484/146309240-4ef31820-80ca-4f99-93b2-70b0eba16cb8.png)
> 
> <img alt="Shot 12-16 at 12 41 13@2x" width="658" src="https://user-images.githubusercontent.com/49652932/146309431-6450ee02-debe-47f4-945a-ed1f2b4e452e.png">
> 
> <img alt="Shot 12-16 at 12 41 17@2x" width="147" src="https://user-images.githubusercontent.com/49652932/146309436-0bd7ae79-9080-42b7-ad96-4743757c178d.png">
> 
> s 是不是没开显示高级设置

的确如此，现已成功下载字幕。感谢！
我之所以以为只是部分剧集未下载成功的原因，大概是我下载网飞的剧集居多，MKV里面大多数都带有中文字幕。
原来从来就没通过程序下载没成功过（捂脸）

**Comment by fengdong1989** [comment]
> > <img alt="Shot 12-15 at 16 23 54@2x" width="583" src="https://user-images.githubusercontent.com/49652932/146150147-f565e1d9-8b2a-413c-a48c-cba95a027f98.png">
> > 因为我之前遇到过类似的问题，就是勾选了这个选项后，tvshow.nfo后面会加一行tvdb的URL导致解析失败了
> 
> 能发送有问题的这个文件上来吗？我看看怎么解决。

感谢大佬回复，已在 Jessie722 大哥的帮助下解决。

**Comment by allanpk716** [comment]
@fengdong1989  你反馈的文件我看到了，我考虑下，看怎么处理下吧。他们在这个文件后面写一个 web 地址挺神奇的，服了。 😂

**Comment by allanpk716** [comment]
看了下，解析 nfo 的逻辑不会因为这个触发崩溃。如果 nfo 文件内容只有 web 地址，那么会触发的是 error："can not find IMDB Id"，也算是期望的结果 。所以这样看来这个不算是 bug，只是他们使用 nfo 文件不规范的问题。需要按照上述的设置去避免才行。
