### ISSUE TITLE
跑了一下就停止了

### ISSUE THREAD

**Issue by willie91** [allanpk716/ChineseSubFinder#125]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC
docker
## 你遇到什么问题了？
从日志看都是跑了一下就停了，不知道咋回事

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: X:\连续剧\杀死伊芙 (2018)

视频的信息: 杀死伊芙 - S01E01 - 姣好面容.mp4

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
[ChineseSubFinder--202112150000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7721137/ChineseSubFinder--202112150000--.log)
nfo的信息看这里 https://pi.qaq.ee:6/s/YzYFrq

谢谢，麻烦你了

**Comment by allanpk716** [comment]
开启 DebugMode: true ，里面会把更详细的写出来。[配置建议以及解释](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%85%8D%E7%BD%AE%E5%BB%BA%E8%AE%AE%E4%BB%A5%E5%8F%8A%E8%A7%A3%E9%87%8A.md)

**Comment by willie91** [comment]
> 开启 DebugMode: true ，里面会把更详细的写出来。[配置建议以及解释](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%85%8D%E7%BD%AE%E5%BB%BA%E8%AE%AE%E4%BB%A5%E5%8F%8A%E8%A7%A3%E9%87%8A.md)
[ChineseSubFinder.log](https://github.com/allanpk716/ChineseSubFinder/files/7724348/ChineseSubFinder.log)
你好，这是开启后的日志

**Comment by allanpk716** [comment]
看到你使用的是 Emby API 的，那么建议试一下最新的 v0.20.x ，之前你使用的版本对于路径映射有比较严格的要求（自动推断的），现在新版本应该更加好用一些。
