### ISSUE TITLE
字幕时间轴校正失效

### ISSUE THREAD

**Issue by CyberRim** [allanpk716/ChineseSubFinder#126]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

ChineseSubFinder Version: v0.19-DockerBeta5

环境: docker

## 你遇到什么问题了？

无法为不同步的字幕文件进行时间轴校正
电影为：The Last Duel (2021)
字幕文件为：The.Last.Duel.2021.Bluray-2160p.x265.10bit.TrueHD.Atmos.7.1-SWTYBLZ.zh.ass
项目运行后，成功为电影自动下载了上面的字幕文件，但字幕的时间轴不同步。我之后在配置文件中加入了DebugMode: true寻找原因，发现校正字幕时，/app/CSF-TmpThings/目录下的字幕都报DetermineFileTypeFromBytes can't found Dialogues, Skip，例如：
[DEBUG]: 2021-12-16 06:22:39 - DetermineFileTypeFromFile ass /app/CSF-TmpThings/The.Last.Duel.2021.Bluray-2160p.x265.10bit.TrueHD.Atmos.7.1-SWTYBLZ.mkv/[zimuku]_11_[最后的决斗] The.Last.Duel.2021.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT.Chs-4-1.srt
[DEBUG]: 2021-12-16 06:22:39 - DetermineFileTypeFromBytes can't found Dialogues, Skip
[DEBUG]: 2021-12-16 06:22:39 - DetermineFileTypeFromFile srt /app/CSF-TmpThings/The.Last.Duel.2021.Bluray-2160p.x265.10bit.TrueHD.Atmos.7.1-SWTYBLZ.mkv/[zimuku]_11_[最后的决斗] The.Last.Duel.2021.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT.Chs-4-1.srt
[DEBUG]: 2021-12-16 06:22:40 - DetermineFileTypeFromFile ass /app/CSF-TmpThings/The.Last.Duel.2021.Bluray-2160p.x265.10bit.TrueHD.Atmos.7.1-SWTYBLZ.mkv/[zimuku]_11_[最后的决斗] The.Last.Duel.2021.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT.Chs-4-2.ass
[DEBUG]: 2021-12-16 06:22:40 - DetermineFileTypeFromFile ass /app/CSF-TmpThings/The.Last.Duel.2021.Bluray-2160p.x265.10bit.TrueHD.Atmos.7.1-SWTYBLZ.mkv/[zimuku]_12_最后的决斗 The Last Duel_S0E0.srt
[DEBUG]: 2021-12-16 06:22:40 - DetermineFileTypeFromBytes can't found Dialogues, Skip
最终
[INFO]: 2021-12-16 06:36:08 - FFTAligner Old Mean: 0 SD: 0 Per: 1
[INFO]: 2021-12-16 06:36:08 - FFTAligner New Mean: 0 SD: 0 Per: 1
[INFO]: 2021-12-16 06:36:08 - FFTAligner Max score: 382078.00000000006 Time: 0
[INFO]: 2021-12-16 06:36:08 - Skip, processBySub offset: 0 > -0.3 && 0 < 0.3
[INFO]: 2021-12-16 06:36:08 - Skip TimeLine Fix -- /media/movies/The Last Duel (2021)/The.Last.Duel.2021.Bluray-2160p.x265.10bit.TrueHD.Atmos.7.1-SWTYBLZ.zh.ass
似乎项目没有检测到这个字幕文件是不同步的。
完整的日志和CSF-SubFixCache、CSF-DebugThings以及不同步的字幕文件已经打包好在下文的链接中。

## 你的问题弄重现嘛？

能够重新。

## 你期望的结果

校正时间轴。

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: /media/movies/The Last Duel (2021)/

视频的信息: The Last Duel (2021)

## 出错的日志信息可以复制一些出来吗？

[issue.zip](https://github.com/allanpk716/ChineseSubFinder/files/7723503/issue.zip)

**Comment by allanpk716** [comment]
V1 版本的校正只支持使用内置的英文字幕校正外部的中英文字幕

**Comment by CyberRim** [comment]
@allanpk716  谢谢答复
我的项目版本是0.19 beta5，按照v2文档所写，0.19也不支持v2吗？（因为环境中没有emby）
而且字幕是择优自动选择下载的，没有配合时间轴矫正功能来特定选取中英字幕下载吗？

**Comment by allanpk716** [comment]
> @allanpk716 谢谢答复 我的项目版本是0.19 beta5，按照v2文档所写，0.19也不支持v2吗？（因为环境中没有emby） 而且字幕是择优自动选择下载的，没有配合时间轴矫正功能来特定选取中英字幕下载吗？

不好意思，眼花了，以为是 V1。稍等，我需要看看。

**Comment by allanpk716** [comment]
是一个 bug，因为内置或者外置字幕，可能导出或者下载到的，内容是残缺的。如下图1.
我虽然做了判断，但是眼花写错了，如图2，写错成外置字幕列表的数组了。

v0.19 beta 版本我还发现一个问题，有些视频的字幕，前 30% 是偏移 -4s，后 70% 偏移 -6s。我看 ffsubfinder 解决了这个特殊的问题，我现在也在尝试解决。建议暂时不使用 beta 版本先。也就是你发现的这个 bug，会修复，但是暂时不发布新版本 docker。等月底吧，如果抽的出时间的话。


## 图1
![image](https://user-images.githubusercontent.com/1176000/146289723-bf98dafe-d8d4-455d-92de-35e4640d40b5.png)

## 图2
![image](https://user-images.githubusercontent.com/1176000/146289904-1ca08e2b-6011-4d14-ba7a-0c364e909324.png)
