### ISSUE TITLE
个别剧集无法获取字幕

### ISSUE THREAD

**Issue by JassyLyn** [allanpk716/ChineseSubFinder#127]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: docker 

## 你遇到什么问题了？

看日志是获取到IMDB了，也能从字幕库手动搜索到，为什么还是显示无法下载呢，中间几个ERROR也没看懂

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

正确获取并下载

## 可以提供遇到问题时候，电影、连续剧的信息吗？

IMDB ID: tt15835776

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

[INFO]: 2021-12-16 00:29:22 - 7 DlSub Start /media/tv/Saiai (2021)
[INFO]: 2021-12-16 00:29:22 - Saiai IMDB ID: tt15835776 NeedDownloadSubs: 8
[INFO]: 2021-12-16 00:29:22 - S1E4
[INFO]: 2021-12-16 00:29:22 - S1E5
[INFO]: 2021-12-16 00:29:22 - S1E6
[INFO]: 2021-12-16 00:29:22 - S1E7
[INFO]: 2021-12-16 00:29:22 - S1E8
[INFO]: 2021-12-16 00:29:22 - S1E1
[INFO]: 2021-12-16 00:29:22 - S1E2
[INFO]: 2021-12-16 00:29:22 - S1E3
[INFO]: 2021-12-16 00:29:22 - 7 shooter Start...
[INFO]: 2021-12-16 00:29:22 - 7 zimuku Start...
[INFO]: 2021-12-16 00:29:22 - 7 xunlei Start...
2021/12/16 00:29:22.890648 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/B3E371E1C8CA052C1450D7CDD9D9BB24E0D27D20.json": EOF, Attempt 1

[ERROR]: 2021-12-16 00:29:23 - Saiai 第一季

[INFO]: 2021-12-16 00:29:23 - Retry Saiai
2021/12/16 00:29:23.223454 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/B3E371E1C8CA052C1450D7CDD9D9BB24E0D27D20.json": EOF, Attempt 2

2021/12/16 00:29:23.909609 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/9E50CF9CB3778EA1E781F9D2A1CCFD08658E0207.json": EOF, Attempt 1

2021/12/16 00:29:24.595729 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/9E50CF9CB3778EA1E781F9D2A1CCFD08658E0207.json": EOF, Attempt 2

2021/12/16 00:29:24.797895 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/9E50CF9CB3778EA1E781F9D2A1CCFD08658E0207.json": EOF, Attempt 3

[ERROR]: 2021-12-16 00:29:25 - xunlei NewHttpClient:

[ERROR]: 2021-12-16 00:29:25 - 7 xunlei GetSubListFromFile4Series Get "http://sub.xmp.sandai.net:8000/subxl/9E50CF9CB3778EA1E781F9D2A1CCFD08658E0207.json": EOF

[INFO]: 2021-12-16 00:29:25 - 7 xunlei End...
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 4
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 5
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 6
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 7
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 8
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 1
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 2
[INFO]: 2021-12-16 00:29:25 - ZiMuKu Not Find Sub can be download Saiai 1 3
[INFO]: 2021-12-16 00:29:25 - 7 zimuku End...
[INFO]: 2021-12-16 00:29:42 - 7 shooter End...
[INFO]: 2021-12-16 00:29:42 - 7 DlSub End /media/tv/Saiai (2021)
[INFO]: 2021-12-16 00:29:42 - OrgSubName: [shooter]_0_Saiai _S1E1.srt
[INFO]: 2021-12-16 00:29:42 - SubDownAt: /media/tv/Saiai (2021)/Season 1/Saiai - S01E01 - TBA WEBDL-1080p.zh.srt
[INFO]: 2021-12-16 00:29:42 - OrgSubName: [shooter]_0_Saiai _S1E2.srt
[INFO]: 2021-12-16 00:29:42 - SubDownAt: /media/tv/Saiai (2021)/Season 1/Saiai - S01E02 - TBA WEBDL-1080p.zh.srt
[INFO]: 2021-12-16 00:29:42 - OrgSubName: [shooter]_0_Saiai _S1E3.srt
[INFO]: 2021-12-16 00:29:42 - SubDownAt: /media/tv/Saiai (2021)/Season 1/Saiai - S01E03 - TBA WEBDL-1080p.zh.srt
[INFO]: 2021-12-16 00:29:42 - OrgSubName: [shooter]_0_Saiai _S1E4.srt
[INFO]: 2021-12-16 00:29:42 - SubDownAt: /media/tv/Saiai (2021)/Season 1/Saiai - S01E04 - TBA WEBDL-1080p.zh.srt

**Comment by allanpk716** [comment]
因为字幕的命名规范性问题，老梗了。这种哪怕是只有一季的，也应该是 S01E0X，暂时没有好办法，不太想写太多的硬编码规则，还是打算从视频唯一 ID 的方式去解决。

## 图片
![image](https://user-images.githubusercontent.com/1176000/146296867-69da87dc-0df2-4488-9781-2488b5777b2c.png)

**Comment by fishbao1973** [comment]
命名规则下，有些剧集也不能下载
[INFO]: 2021-12-16 08:27:46 - 5 DlSub Start /media/tvshows/Unforgotten
[INFO]: 2021-12-16 08:27:46 - Unforgotten IMDB ID: tt4192812 NeedDownloadSubs: 5
[INFO]: 2021-12-16 08:27:46 - S3E1
[INFO]: 2021-12-16 08:27:46 - S3E6
[INFO]: 2021-12-16 08:27:46 - S3E3
[INFO]: 2021-12-16 08:27:46 - S3E4
[INFO]: 2021-12-16 08:27:46 - S3E5
[INFO]: 2021-12-16 08:27:46 - 5 shooter Start...
[INFO]: 2021-12-16 08:27:46 - 5 zimuku Start...
[INFO]: 2021-12-16 08:27:46 - 5 xunlei Start...
[INFO]: 2021-12-16 08:27:47 - 5 xunlei End...
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 1
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 6
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 3
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 4
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 5

**Comment by Jessie722** [comment]
> 因为字幕的命名规范性问题，老梗了。这种哪怕是只有一季的，也应该是 S01E0X，暂时没有好办法，不太想写太多的硬编码规则，还是打算从视频唯一 ID 的方式去解决。
> 
> ## 图片
> ![image](https://user-images.githubusercontent.com/1176000/146296867-69da87dc-0df2-4488-9781-2488b5777b2c.png)

感谢回复。明白了，希望未来会有更好的解决方案吧。

**Comment by allanpk716** [comment]
> 

1. imdb 搜索结果，图1。
2. 搜索 Unforgotten，见图2，图3

他就是没有，所以没法下载。kodi 怎么下载的没关注过。

## 图1
![image](https://user-images.githubusercontent.com/1176000/146299932-a4f9638c-37c9-48b5-994e-3ee22e8b6ea2.png)

## 图2
![image](https://user-images.githubusercontent.com/1176000/146299963-b0589e00-3c46-41d2-a4bc-a9ca41de85a6.png)

##  图3
![image](https://user-images.githubusercontent.com/1176000/146300020-7b46a953-b560-4c52-a1c1-afcaa318e0c3.png)

**Comment by fishbao1973** [comment]
不好意思，没有仔细核查，但是部分电视剧是存在不能刷新，或者多次刷新后才下载完成，在目前电视剧方面，有部分还是没有下载完成 
![Screenshot-20211216115811-643x564](https://user-images.githubusercontent.com/44134804/146305745-322ae512-328d-490d-a8f1-e8b37776e946.png)

> ``
![Uploading Screenshot-20211216115904-595x499.png…]()


[INFO]: 2021-12-16 08:27:37 - 2 DlSub End /media/tvshows/Syria.The.Worlds.War
[INFO]: 2021-12-16 08:27:37 - no sub found Syria.The.Worlds.War
[INFO]: 2021-12-16 08:27:38 - 3 xunlei End...
[INFO]: 2021-12-16 08:27:39 - 3 shooter End...
[INFO]: 2021-12-16 08:27:40 - 4 DlSub Start /media/tvshows/Narcos.Mexico
[INFO]: 2021-12-16 08:27:40 - Narcos: México IMDB ID: tt8714904 NeedDownloadSubs: 14
[INFO]: 2021-12-16 08:27:40 - S2E9
[INFO]: 2021-12-16 08:27:40 - S2E2
[INFO]: 2021-12-16 08:27:40 - S2E6
[INFO]: 2021-12-16 08:27:40 - S1E4
[INFO]: 2021-12-16 08:27:40 - S2E8
[INFO]: 2021-12-16 08:27:40 - S1E10
[INFO]: 2021-12-16 08:27:40 - S2E7
[INFO]: 2021-12-16 08:27:40 - S1E881
[INFO]: 2021-12-16 08:27:40 - S3E2
[INFO]: 2021-12-16 08:27:40 - S2E3
[INFO]: 2021-12-16 08:27:40 - S2E5
[INFO]: 2021-12-16 08:27:40 - S2E10
[INFO]: 2021-12-16 08:27:40 - S2E1
[INFO]: 2021-12-16 08:27:40 - S2E4
[INFO]: 2021-12-16 08:27:40 - 4 shooter Start...
[INFO]: 2021-12-16 08:27:40 - 4 zimuku Start...
[INFO]: 2021-12-16 08:27:40 - 4 xunlei Start...
[ERROR]: 2021-12-16 08:27:41 - Narcos: México 第三季
[INFO]: 2021-12-16 08:27:41 - Retry Narcos: México
[ERROR]: 2021-12-16 08:27:43 - Narcos: México
[ERROR]: 2021-12-16 08:27:43 - 4 zimuku GetSubListFromFile4Series zimuku search keyword step0 not found, detail page url
[INFO]: 2021-12-16 08:27:43 - 4 zimuku End...
[INFO]: 2021-12-16 08:27:43 - 3 zimuku End...
[INFO]: 2021-12-16 08:27:43 - 3 DlSub End /media/tvshows/The Morning Show
[INFO]: 2021-12-16 08:27:43 - 4 xunlei End...
[INFO]: 2021-12-16 08:27:43 - OrgSubName: [shooter]_0_The Morning Show _S2E2.ass
[INFO]: 2021-12-16 08:27:43 - SubDownAt: /media/tvshows/The Morning Show/Season 02/The Morning Show - S02E02 - It’s Like the Flu WEBDL-1080p.chinese(简英,shooter).default.ass
[WARNING]: 2021-12-16 08:27:46 - ReadSeriesInfoFromDir.GetImdbInfo4SeriesDir.strconv.Atoi strconv.Atoi: parsing "": invalid syntax
[INFO]: 2021-12-16 08:27:46 - 5 DlSub Start /media/tvshows/Unforgotten
[INFO]: 2021-12-16 08:27:46 - Unforgotten IMDB ID: tt4192812 NeedDownloadSubs: 5
[INFO]: 2021-12-16 08:27:46 - S3E1
[INFO]: 2021-12-16 08:27:46 - S3E6
[INFO]: 2021-12-16 08:27:46 - S3E3
[INFO]: 2021-12-16 08:27:46 - S3E4
[INFO]: 2021-12-16 08:27:46 - S3E5
[INFO]: 2021-12-16 08:27:46 - 5 shooter Start...
[INFO]: 2021-12-16 08:27:46 - 5 zimuku Start...
[INFO]: 2021-12-16 08:27:46 - 5 xunlei Start...
[INFO]: 2021-12-16 08:27:47 - 5 xunlei End...
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 1
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 6
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 3
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 4
[INFO]: 2021-12-16 08:27:48 - ZiMuKu Not Find Sub can be download Unforgotten  3 5
[INFO]: 2021-12-16 08:27:48 - 5 zimuku End...
[INFO]: 2021-12-16 08:27:49 - 5 shooter End...
[INFO]: 2021-12-16 08:27:49 - 5 DlSub End /media/tvshows/Unforgotten
[INFO]: 2021-12-16 08:27:49 - no sub found Unforgotten
[INFO]: 2021-12-16 08:27:49 - 4 shooter End...
[INFO]: 2021-12-16 08:27:49 - 4 DlSub End /media/tvshows/Narcos.Mexico
[INFO]: 2021-12-16 08:27:49 - OrgSubName: [shooter]_0_Narcos  Mexico _S3E2.srt
[INFO]: 2021-12-16 08:27:49 - SubDownAt: /media/tvshows/Narcos.Mexico/Season 03/Narcos - Mexico - S03E02 - Como La Flor WEBRip-720p.chinese(繁,shooter).default.srt
[WARNING]: 2021-12-16 08:27:49 - DetermineFileTypeFromFile /app/tmpthings/Narcos.Mexico/[xunlei]_0_���ɣ�ī����_S1E4.srt not support SubType
[WARNING]: 2021-12-16 08:27:49 - DetermineFileTypeFromFile /app/tmpthings/Narcos.Mexico/[xunlei]_0_Narcos Mexico_S1E10.srt not support SubType
[WARNING]: 2021-12-16 08:27:49 - DetermineFileTypeFromFile /app/tmpthings/Narcos.Mexico/[xunlei]_0_���ɣ�ī����_S1E9.srt not support SubType

**Comment by allanpk716** [comment]
@fishbao1973  很多时候都是网络问题导致的，比如最近迅雷的接口和shooter 的接口会有些问题，但是挂机等几个轮询一般也就细下来了。还是建议控制下载的线程为1（可能后续会强制为1），然后轮询时间在 6h差不多了，太快也没啥用。
