### ISSUE TITLE
日志在HotFix Start停止不动

### ISSUE THREAD

**Issue by africa1207** [allanpk716/ChineseSubFinder#129]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: docker

## 你遇到什么问题了？

docker部署在ubuntu20.4，其配置文件挂载自同局域网群晖共享目录，协议cifs
媒体库也挂载自群晖共享目录，其中电影文件夹只有一部电影，连续剧文件夹为空
ubuntu是root登录，挂载协议所用账号对配置文件夹和媒体库文件夹都具有777

/root/MountDir/Nas/Video/Movie----/media/电影
/root/MountDir/Nas/Video/TV Series----/media/连续剧
docker开始运行一直停留在HotFix Start，不进行后续下载字幕等操作

> [INFO]: 2021-12-16 16:59:02 - HotFix Start...,
To support LSIO projects visit:,
-------------------------------------,
https://www.linuxserver.io/donate/,
[services.d] done.,
[cont-init.d] done.,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] 50-config: executing... ,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: exited 0.,
User gid:    100,
User uid:    1026,
GID/UID,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[cont-init.d] 99-custom-scripts: exited 0.,
[services.d] starting services,
[INFO]: 2021-12-16 16:59:02 - ChineseSubFinder Version: v0.18.8,
[INFO]: 2021-12-16 16:59:02 - UseProxy = false,
[INFO]: 2021-12-16 16:59:02 - MovieFolder: /media/电影,
[INFO]: 2021-12-16 16:59:02 - SeriesFolder: /media/连续剧
[INFO]: 2021-12-16 16:59:02 - HotFix Start...

GUID PGID都改成0 还是同样问题

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: /root/MountDir/Nas/Video/Movie/目击者之追凶（2017）/

视频的信息: 目击者之追凶（2017）.mp4

## 出错的日志信息可以复制一些出来吗？

已经开启debug模式导出来看了下日志，就是上面那段日志，

**Comment by allanpk716** [comment]
没报错就需要等。

**Comment by africa1207** [comment]
> 

但是只有一部电影都需要等这么久吗？

**Comment by allanpk716** [comment]
你日志补全，没有看到这句话，你先把日志完整发上来先把。

![image](https://user-images.githubusercontent.com/1176000/146723166-c379b4ac-926b-4b5f-9a66-c4379cc4f3ba.png)
