### ISSUE TITLE
关于emby字幕后缀的命名格式

### ISSUE THREAD

**Issue by syq0806** [allanpk716/ChineseSubFinder#13]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.11.1

环境: docker

## 你遇到什么问题了？

现在下载的中英文格式的字幕，会自动命名*.chs_eng.srt或者*.chs_en.ass，但是emby是识别不了这个chs_en，在字幕选择里会出现Chen(srt)，很怪，虽然不影响使用，但是如果设置默认字幕为chinese，就选不到这个字幕。如果字幕后缀是*.chs.srt，emby里的字幕选择就会正常出现chinese(srt)，默认字幕也正常

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

描述以下你期望的结果
因为很多字幕其实都是中英文，对于一般人来说，除非有特定的英语学习需求，不然我建议能不能自动命名的字幕直接采用*.chs.srt或者*.cht.srt，或者*.chs.default.srt

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/125600114-67bb5173-76dd-4d86-81cf-7923cc472ed7.png)

个人喜欢开启 SaveMultiSub: true，那么就类似上面图片中的字幕保存效果。
SaveMultiSub: false 的时候就会类似你那样的保存命名，因为很久没有切换到单字幕下载模式了，所以我需要确认下。

如果是上图， Emby 加载没有问题（我的都保持在最新的 Emby ，用 watchtower 做到的）。会把 chs_en 缩写为 chsen 来显示。如下图：

![image](https://user-images.githubusercontent.com/1176000/125600689-dbd0c1f0-1190-4721-b3bc-f857a051ffe3.png)

之所以命名成这样，是因为如果是双语字幕的时候，不知道在 Emby 中如何命名才合适，然后测试了下这样的命名也能读取出来所以才使用这个方案的。

Emby 的版本你是多少呢？如果升级到最新的 Emby 呢？

**Comment by allanpk716** [comment]
> ## 你期望的结果
> 描述以下你期望的结果
> 因为很多字幕其实都是中英文，对于一般人来说，除非有特定的英语学习需求，不然我建议能不能自动命名的字幕直接采用*.chs.srt或者*.cht.srt，或者*.chs.default.srt

因为没有完整的去把 Emby 支持的字幕命名规则给试出来，如果可能的话，欢迎分享一下你的 Emby 版本下，字幕命名会在其中显示的效果。有列表就最好了。

**Comment by syq0806** [comment]
我的emby版本是4.6.4.0，我举个例子，
![1626259722949](https://user-images.githubusercontent.com/61413903/125610009-bd74bcd0-34ba-4be6-8d5d-6e281f39a46a.jpg)
![1626259792829](https://user-images.githubusercontent.com/61413903/125610104-54c21fbc-29aa-4ede-9fdc-6aab1b3e197e.jpg)
如果直接 片名.srt，在emby里显示是Und(srt);片名.chs.srt，emby里显示chinese(srt);片名.chs_en.srt，emby里显示是chsen(srt);如果是片名.chs.deadault.srt，emby里显示Deafault(srt)

**Comment by syq0806** [comment]
顺便附一下emby官方关于字幕命名的wiki链接：https://support.emby.media/support/solutions/articles/44001159160-subtitles，感谢大佬耐心回复。

**Comment by mhqschen** [comment]
我觉得emby没有考虑双语字幕的情况。所以字幕选项里也只支持一个语言。
要让emby自动选择双语字幕，就得让它把字幕识别成单中文。
如果的确如此的话，可以让用户选择是否默认把chs-en字幕重命名为chs字幕，也算是一个折衷方案。

**Comment by allanpk716** [comment]
> 顺便附一下emby官方关于字幕命名的wiki链接：[https://support.emby.media/support/solutions/articles/44001159160-subtitles，](https://support.emby.media/support/solutions/articles/44001159160-subtitles%EF%BC%8C) 感谢大佬耐心回复。我这边的意思是能否直接让其字幕在emby显示chinese，而不是chen，这样在emby控制台-字幕里，选择默认字幕为chinese的时候，能自动加载中文字幕，而不是每次都要手动选择名字为chen的字幕，我没试过SaveMultiSub: true，感觉不是很喜欢目录下太多文件。

感谢分享 Emby 字幕命名格式相关的链接。我先看看，然后考虑下怎么兼容现在的字幕命名。有一定的改动，估计不会很快完成。

**Comment by allanpk716** [comment]
> 我觉得emby没有考虑双语字幕的情况。所以字幕选项里也只支持一个语言，这个很正常，opensubtitles也没有。
> 要让emby自动选择双语字幕，就得让它把字幕识别成单中文。
> 如果的确如此的话，可以让用户选择是否默认把chs-en字幕重命名为chs字幕，也算是一个折衷方案。
> SaveMultiSub: true的时候也需要把平台名称放在语言前面，变成.[zimuku].chs.srt

嗯，需要考虑写怎么改。

**Comment by SuperNG6** [comment]
支持，字幕命名规范更改后，建议增加重命名选项，把已下载的字幕重命名

**Comment by allanpk716** [comment]
> 支持，字幕命名规范更改后，建议增加重命名选项，把已下载的字幕重命名

是想怎么重命名字幕呢？

1. 如果选择的功能是 SaveMultiSub: false，单个字幕，单个语言字幕问题不大，可以延用官方的改。
2. 双语字幕，重命名后是叫啥就很犹豫，大家可以列一下想要的双语字幕命名格式。
3. SaveMultiSub: true 的时候，想要命名成什么样，也可以提一下建议

**Comment by allanpk716** [comment]
> 支持，字幕命名规范更改后，建议增加重命名选项，把已下载的字幕重命名

如果是设置保存单字幕（SaveMultiSub: false）自动把之前的重命名没问题，如果是设置保存多个字幕（SaveMultiSub: true）估计就没啥好办法去重命名多个字幕了哦。

**Comment by mhqschen** [comment]
SaveMultiSub: true
RenameBilingualSub:true
XXX.[zimuku_chs_en].chs.srt/ XXX.[subhd_chs_en].chs.srt

SaveMultiSub: false
RenameBilingualSub:true
XXX.[chs_en].chs.srt

**Comment by SuperNG6** [comment]
> > 支持，字幕命名规范更改后，建议增加重命名选项，把已下载的字幕重命名
> 
> 如果是设置保存单字幕（SaveMultiSub: false）自动把之前的重命名没问题，如果是设置保存多个字幕（SaveMultiSub: true）估计就没啥好办法去重命名多个字幕了哦。

# 在启用`SaveMultiSub`选项时和存在多字幕时，可以命名为以下格式
最优字幕`黑袍纠察队 - S01E01 - 最重要的部分.zh.default.ass`
其他字幕`黑袍纠察队 - S01E01 - 最重要的部分.Chinese (中英，zimuku).ass`
# 效果图
![Xnip2021-07-15_16-55-15](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2021-07-15/Xnip2021-07-15_16-55-15.jpg)
![Xnip2021-07-15_16-51-48](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2021-07-15/Xnip2021-07-15_16-51-48.jpg)
![Xnip2021-07-15_16-52-04](https://cdn.jsdelivr.net/gh/SuperNG6/pic@master/uPic/2021-07-15/Xnip2021-07-15_16-52-04.jpg)

**Comment by mhqschen** [comment]
> > > 支持，字幕命名规范更改后，建议增加重命名选项，把已下载的字幕重命名
> > 
> > 
> > 如果是设置保存单字幕（SaveMultiSub: false）自动把之前的重命名没问题，如果是设置保存多个字幕（SaveMultiSub: true）估计就没啥好办法去重命名多个字幕了哦。
> 
> # 在启用`SaveMultiSub`选项时和存在多字幕时，可以命名为以下格式
> 最优字幕`黑袍纠察队 - S01E01 - 最重要的部分.zh.default.ass`
> 其他字幕`黑袍纠察队 - S01E01 - 最重要的部分.Chinese (中英，zimuku).ass`
> 
> # 效果图
> ![Xnip2021-07-15_16-55-15](https://camo.githubusercontent.com/88d6459469e06cf8805a8d4e31749c74ddaf54967a2817f0f3c50b1630063ad7/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f53757065724e47362f706963406d61737465722f755069632f323032312d30372d31352f586e6970323032312d30372d31355f31362d35352d31352e6a7067)
> ![Xnip2021-07-15_16-51-48](https://camo.githubusercontent.com/e7024e82fb7efbd065552a0d27f286b00b728bf5b90b0c9548b126d00a684805/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f53757065724e47362f706963406d61737465722f755069632f323032312d30372d31352f586e6970323032312d30372d31355f31362d35312d34382e6a7067)
> ![Xnip2021-07-15_16-52-04](https://camo.githubusercontent.com/022c923eebbc967a51e9ec95410e03981a2ba6ad407e1239ce6db793ba73247c/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f53757065724e47362f706963406d61737465722f755069632f323032312d30372d31352f586e6970323032312d30372d31355f31362d35322d30342e6a7067)

哈哈哈这个办法妙。试了下jellyfin也可以正常默认选择到这样命名的字幕

**Comment by allanpk716** [comment]
今天抽点时间把这个先给给改了

**Comment by xiNeRoar** [comment]
請問該怎麼設定才能令jellyfin自動優先選擇中文字幕? 如果字幕命名格式是.zh的話是會自動選擇沒有問題
可是chinesesubfinder下載的字幕全部都是.chinese後綴導致jellyfin怎麼設定都無法讀取到中文字幕
![image](https://user-images.githubusercontent.com/66216186/131261255-bf84fe81-3791-4fe3-8833-e1763a3d4d2c.png)
![image](https://user-images.githubusercontent.com/66216186/131261263-41cfbac5-e687-425f-a24e-4b049bb072fa.png)
![image](https://user-images.githubusercontent.com/66216186/131261277-e09ee792-04fc-481b-b23f-26fa6e6dfc63.png)

還想請問有辦法可以自主選擇要.zh後綴還是.chinese後綴嗎?
我同時在使用bazarr跟chinesesubfinder, 發現如果chinesesubfinder下載的字幕全部都是.chinese後綴的話 bazarr會讀取不到從而把該影片當成欠缺中文字幕, 必須得手動把每個.chinese改回.zh才能讓bazarr知道該影片已經有中文字幕檔案存在

**Comment by allanpk716** [comment]
> 請問該怎麼設定才能令jellyfin自動優先選擇中文字幕? 如果字幕命名格式是.zh的話是會自動選擇沒有問題
> 可是chinesesubfinder下載的字幕全部都是.chinese後綴導致jellyfin怎麼設定都無法讀取到中文字幕
> 還想請問有辦法可以自主選擇要.zh後綴還是.chinese後綴嗎?
> 我同時在使用bazarr跟chinesesubfinder, 發現如果chinesesubfinder下載的字幕全部都是.chinese後綴的話 bazarr會讀取不到從而把該影片當成欠缺中文字幕, 必須得手動把每個.chinese改回.zh才能讓bazarr知道該影片已經有中文字幕檔案存在


根据你的反馈，Emby 和 jellyfin 读取字幕的逻辑应该不兼容，或者说是 Emby 兼容 jellyfin 的，但是 jellyfin 不兼容 Emby 的。
jellyfin 的[字幕文档](https://jellyfin.org/docs/general/server/media/subtitles.html)

现在你遇到的问题我个人建议是，暂时只使用 bazarr。最近我会抽时间出来，把字幕命名的功能完善了，至少支持 jellyfin 。完成上述功能改进后，如果仅仅搜索中文字幕，应该用本程序足够替代 bazarr 了。

**Comment by EmmaSamules** [comment]
![1](https://github.com/user-attachments/assets/5e6f2421-a697-4e96-b1ff-137a12f96546)
改成这样出现Divehi (ASS)了
