### ISSUE TITLE
第一次下载无法抓取字幕

### ISSUE THREAD

**Issue by YoshiPark** [allanpk716/ChineseSubFinder#130]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

环境: docker 

## 你遇到什么问题了？

按照指南设置好路径之后，发现日志可以扫描对应的剧集名字，但是没法下载字幕
对应的路径设置
Emby路径设置截图：

![emby](https://user-images.githubusercontent.com/20967749/146714000-a13a4424-e102-4aa2-bfb6-ceaf639a215a.png)
ChineseSubfinder路径设置截图：
![chinesesubfinder](https://user-images.githubusercontent.com/20967749/146714027-b7e8a0bf-107d-44a1-8994-0aadc71f297f.png)
yaml文件的设置如下：
UseProxy: true
HttpProxy: xxx
EveryTime: 12h
Threads: 2
RunAtStartup: true
MovieFolder: /media/电影
SeriesFolder: /media/电视剧
DebugMode: True
FixTimeLine: true

EmbyConfig:
    Url: XXX
    ApiKey: XXX
    LimitCount: 3000
    SkipWatched: false
物理路径映射是一样的，然后日志也可以看到也能扫描到对应文件，刮削使用的是sonarr和emby，都有tvshow.nfo和season.nfo，而且每一集都有对应的nfo文件，但是日志显示没有下载字幕，想请问是什么问题
## 你的问题弄重现嘛？

能够重新，能够重现

## 你期望的结果

可以正常下载字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: ./TV/美剧/The Sex Lives of College Girls/Season 1

视频的信息: The Sex Lives of College Girls - S01E01 - Welcome to Essex WEBDL-1080p.mkv

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

[allanpk716-chinesesubfinder1.csv](https://github.com/allanpk716/ChineseSubFinder/files/7742722/allanpk716-chinesesubfinder1.csv)
![erroe](https://user-images.githubusercontent.com/20967749/146714618-185603dc-658d-4d6d-9a1c-e0e118d37efb.png)

**Comment by allanpk716** [comment]
映射不对

**Comment by YoshiPark** [comment]
想请问一下如何修改，能否举个TV的例子，谢谢

**Comment by allanpk716** [comment]
[高阶设置 - Emby API 支持](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md)

[问题列表](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8.md)

[电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)

[连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

**Comment by allanpk716** [comment]
建议升级到 v0.20 或者最新，看最新教程应该可以解决你的问题。
