### ISSUE TITLE
咨询下，如果有多个剧集目录，配置文件应该怎么写，如下

### ISSUE THREAD

**Issue by wisinfun** [allanpk716/ChineseSubFinder#131]
<img width="519" alt="CleanShot 2021-12-20 at 15 46 13@2x" src="https://user-images.githubusercontent.com/41355260/146730958-a1acfa6e-025d-4127-be6e-b482dbb13262.png">
连续剧、儿童、动漫都属于剧集

**Comment by allanpk716** [comment]
暂时不支持，需要开多个，

**Comment by wyq977** [comment]
Related #153

**Comment by allanpk716** [comment]
现在升级至 v0.20.x 应该可以满足你现在的需求。

**Comment by wisinfun** [comment]
> 现在升级至 v0.20.x 应该可以满足你现在的需求。

不胜感激
