### ISSUE TITLE
字幕下载数量一直增加 

### ISSUE THREAD

**Issue by yybinpitaya** [allanpk716/ChineseSubFinder#133]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

ChineseSubFinder Version: v0.18.8

环境: docker

## 你遇到什么问题了？

电影下载的字幕一直在自动增加文件

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

保证字幕 相同文件 保证只有一个即可

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: /media/电影/The Brand New Testament (2015)

视频的信息: The Brand New Testament (2015) Bluray-1080p.mkv

## 出错的日志信息可以复制一些出来吗？

![image](https://user-images.githubusercontent.com/73825545/147177247-e6628fe9-837e-4921-b22b-87de6be6de35.png)

**Comment by yybinpitaya** [comment]
删除较多的字幕后
![image](https://user-images.githubusercontent.com/73825545/147177457-a6a7c04a-5664-4aaf-b0b3-681c2d2cc163.png)

**Comment by yybinpitaya** [comment]
/media/电影/The.Forever.Purge.2021.HDR.2160p.WEB-DL.DD5.1.HEVC-EVO/The.Forever.Purge.2021.HDR.2160p.WEB-DL.DD5.1.HEVC-EVO.mkv

此路径也会一样

**Comment by yybinpitaya** [comment]
[INFO]: 2021-12-23 03:09:33 - Movie Sub Dl From Emby API...
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.1.zh-cn.srt not chinese sub, is  未知语言
[INFO]: 2021-12-23 03:09:36 - 1 DlSub Start /media/电影/Beckman.2020.1080p.BluRay.DTS.x265-10bit-LHD/Beckman.2020.1080p.BluRay.DTS.x265-10bit-LHD.mkv
[INFO]: 2021-12-23 03:09:36 - 1 shooter Start...
[INFO]: 2021-12-23 03:09:36 - 1 zimuku Start...
[INFO]: 2021-12-23 03:09:36 - 1 xunlei Start...
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.10.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.11.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.12.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.13.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.14.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.15.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.16.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:36 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.17.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.18.zh-cn.srt not chinese sub, is  未知语言
[INFO]: 2021-12-23 03:09:37 - 1 xunlei End...
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.19.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.2.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.20.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.21.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.22.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.23.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.24.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.25.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.26.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.27.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.28.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.29.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.3.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.30.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.31.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.32.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.33.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.34.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.35.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.36.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.37.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.38.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.39.zh-cn.srt not chinese sub, is  未知语言
[WARNING]: 2021-12-23 03:09:37 - IsSubHasChinese.HasChineseLang /media/电影/Resident Evil Welcome to Raccoon City (2021)/Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.4.zh-cn.srt not chinese sub, is  未知语言
[ERROR]: 2021-12-23 03:09:37 - zimuku keyword: tt10989808

**Comment by allanpk716** [comment]
1. 你挑选重复的几个字幕文件发上来
2. 你能确认下本程序扫描了几次就出现那么多个字幕吗？
3. 你的配置信息也贴一下

如果是一次扫描就出现那么多字幕的话，就明显有逻辑bug。之前也看到有人反馈类似的问题，猜测是字幕文件后面带有 .number.srt 这种情况触发的。但是你这里出现很多个，我觉得很奇怪。

**Comment by yybinpitaya** [comment]
这样的 我这边看时间 大概是10分钟 就重新下载了一次 随着时间递增 他字幕文件就越多

配置环境:
unraid->docker

配置
UseProxy: false
HttpProxy: http://192.168.10.10:1088
EveryTime: 12h
Threads: 2
RunAtStartup: true
MovieFolder: /media/电影
SeriesFolder: /media/电视剧


目录文件结构
└─Resident Evil Welcome to Raccoon City (2021)
        movie.nfo
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.1.zh-cn.srt  这里是自动下载的
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.2.zh-cn.srt  这里是自动下载的 后期会增加到xxx.zh-cn.srt
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.chinese(简).srt 这里是文件自带字幕文件
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.chinese(简英).ass 这里是文件自带字幕文件
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.chinese(简英).default.srt 这里是文件自带字幕文件
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.mkv
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.nfo
        Resident Evil Welcome to Raccoon City (2021) WEBRip-1080p.zh-cn.srt 这个好像也是自动下载的


文件资源包下载 mkv 只有文件名 避免文件过大
https://52nyg.lanzout.com/isRzJxw1y1g

**Comment by yybinpitaya** [comment]
internal/pkg/language/whatlanggo.go:151

我看这里比例过不去


   // 如果比例达不到，那么就是单语言，所以最多的那个就是当前的语言
		// 这里的字典是有可能出现
		if hasChinese {
			// 那么起码要占比 80% 对吧
			perLines = float32(countChinese) / AllLines
			if perLines > basePer {
				return chIsChsOrCht(language.ChineseSimple, isNoOrChsOrCht)
			}
		}

**Comment by allanpk716** [comment]
> internal/pkg/language/whatlanggo.go:151
> 
> 我看这里比例过不去 返回了 return language.Unknown
> 
> // 如果比例达不到，那么就是单语言，所以最多的那个就是当前的语言 // 这里的字典是有可能出现 if hasChinese { // 那么起码要占比 80% 对吧 perLines = float32(countChinese) / AllLines if perLines > basePer { return chIsChsOrCht(language.ChineseSimple, isNoOrChsOrCht) } }

所以你需要把字幕文件上传给我看看，字幕解析器写的比较随意，遇到问题再补

**Comment by yybinpitaya** [comment]
我上传了呀== 上面那个蓝奏网盘里面

**Comment by allanpk716** [comment]
> 我上传了呀== 上面那个蓝奏网盘里面

我现在的电脑和网速都肯定···没刷新出来···不好意思

**Comment by allanpk716** [comment]
1. 字幕语言识别的问题，修复了。但是不会马上发布，应该会合并最近做的功能一起发布。
2. 保存多个字幕这个问题我觉得比较奇怪，因为如下图1，按你的配置，应该是这些才是本程序下载的。因为默认的字幕命名格式是 emby 的，就是这样的。其他的字幕文件本程序会进行扫描，所以未必能确认是自动下载的（也不排除 bug）。
3. 需要你帮排除以下，设置 DebugMode: true ，然后删除（记得备份）这个视频的所有字幕，然后再次启动本程序，然后把相应的日志文件发上来（可以直接拖拽到 github 的issues回复中，无需第三方文件共享）。

## 图1
![image](https://user-images.githubusercontent.com/1176000/147186551-8e249771-40a3-42fb-a90a-6c545162d8b7.png)

**Comment by yybinpitaya** [comment]
我先关闭 emby 自动下载字幕功能 测试看看效果
