### ISSUE TITLE
软件无法运行

### ISSUE THREAD

**Issue by uni-pai** [allanpk716/ChineseSubFinder#134]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.8.8

环境: Windows

## 你遇到什么问题了？
无法打开exe文件，提示缺少dll文件

chinesesubfinder.exe-系统错误
由于找不到libgcc5seh-1.dll,无法继续执行代码。重新安装程序可能会解决此问题。
![image](https://user-images.githubusercontent.com/56943441/147406674-1a94f080-42a7-49d4-830c-ceea3812b6b6.png)

chinesesubfinder.exe-系统错误
由于找不到libstdc++-.dll,无法继续执行代码。重新安装程序可能会解决此问题。
![image](https://user-images.githubusercontent.com/56943441/147406681-00c94745-31b3-409f-8390-cca466151628.png)

## 你的问题弄重现嘛？

能够重现

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

无日志

**Comment by allanpk716** [comment]
#101
