### ISSUE TITLE
Better IsSubHasChinese for embedded Chinese subtitles or FILENAME.chi.ext or FILENAME.zho.ext

### ISSUE THREAD

**Issue by wyq977** [allanpk716/ChineseSubFinder#139]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.8

```
$ sw_vers
ProductName:    macOS
ProductVersion: 11.6
```

`[INFO]: 2021-12-28 18:28:38 - ChineseSubFinder Version: v0.18.8`

环境: docker on macOS

## 你遇到什么问题了？

re-Downloads for movies/tv shows with embedded chinese subtitles  and `*.chi/zho.ass`.

1. Cant scan files with  embbed sub
Some videos from NETFLIX or Apple TV, downloaded videos has subtitles embedded on them and usually ships with Chinese, but `IsSubHasChinese` cant scan them.

2. Re download with .chi .zho

I previously organize library by setting the Traditional Chinese as `.zho.ext` and simplfied as `.chi.ext` so that player and jellyfin can auto recongize subtitles. However, since ChineseSubFinder will automatically skip those 2 encoded files, redownloading of those video will happen.

I checked the code as well as [config](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%85%8D%E7%BD%AE%E5%BB%BA%E8%AE%AE%E4%BB%A5%E5%8F%8A%E8%A7%A3%E9%87%8A.md), it seems that theres no ez way to MARK certain subtitles as Chinese so that it wont re download.

As for [naming subtitles](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%85%B3%E4%BA%8E%E5%AD%97%E5%B9%95%E5%90%8D%E7%A7%B0%E5%91%BD%E5%90%8D%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E.md), it looks like `chi` and `zho` are supported code for chinese but in my setup the scan/downloads were performed anyway.

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

1. Add checking/scanning for embbed subtitles
2. Prevent searching for movie with `movie.chi.ass`

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: /media/tv/Squid Game (2021) [imdbid-tt10919420]

视频的信息: ./Season 01/Squid Game (2021) - s01e01.mp4

## 出错的日志信息可以复制一些出来吗？

Both traditional and simplified chinese subtitles can be found using `ffmpeg` or `ffprobe`:

```shell
$ ffmpeg -i Squid\ Game\ \(2021\)\ -\ s01e01.mkv

#.........
#.........
  Stream #0:36(chi): Subtitle: subrip
    Metadata:
      title           : Simplified
      BPS             : 45
      DURATION        : 00:58:06.357000000
      NUMBER_OF_FRAMES: 648
      NUMBER_OF_BYTES : 19721
      _STATISTICS_WRITING_APP: mkvmerge v61.0.0 ('So') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:37(chi): Subtitle: subrip
    Metadata:
      title           : Traditional
      BPS             : 46
      DURATION        : 00:58:06.357000000
      NUMBER_OF_FRAMES: 648
      NUMBER_OF_BYTES : 20069
      _STATISTICS_WRITING_APP: mkvmerge v61.0.0 ('So') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

$ ffprobe -loglevel error -select_streams s -show_entries stream=index:stream_tags=language -of csv=p=0 Squid\ Game\ \(2021\)\ -\ s01e01.mkv 
3,kor
# .....
36,chi
37,chi
```

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

```log
[INFO]: 2021-12-30 07:46:37 - 22 DlSub Start /media/tv/Squid Game (2021) [imdbid-tt10919420]
[INFO]: 2021-12-30 07:46:37 - Squid Game IMDB ID: tt10919420 NeedDownloadSubs: 9
[INFO]: 2021-12-30 07:46:37 - S1E9
[INFO]: 2021-12-30 07:46:37 - S1E1
[INFO]: 2021-12-30 07:46:37 - S1E8
[INFO]: 2021-12-30 07:46:37 - S1E3
[INFO]: 2021-12-30 07:46:37 - S1E7
[INFO]: 2021-12-30 07:46:37 - S1E2
[INFO]: 2021-12-30 07:46:37 - S1E6
[INFO]: 2021-12-30 07:46:37 - S1E4
[INFO]: 2021-12-30 07:46:37 - S1E5
[INFO]: 2021-12-30 07:46:37 - 22 shooter Start...
[INFO]: 2021-12-30 07:46:37 - 22 zimuku Start...
[INFO]: 2021-12-30 07:46:37 - 22 xunlei Start...
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 8
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 3
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 7
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 9
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 1
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 6
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 4
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 5
[INFO]: 2021-12-30 07:46:37 - ZiMuKu Not Find Sub can be download Squid Game 1 2
[INFO]: 2021-12-30 07:46:38 - 22 zimuku End...
[ERROR]: 2021-12-30 07:46:39 - 22 shooter GetSubListFromFile4Series Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn
[INFO]: 2021-12-30 07:46:39 - 22 shooter End...
[INFO]: 2021-12-30 07:46:46 - 22 xunlei End...
[INFO]: 2021-12-30 07:46:46 - 22 DlSub End /media/tv/Squid Game (2021) [imdbid-tt10919420]
[INFO]: 2021-12-30 07:46:46 - OrgSubName: [xunlei]_0_D3A5CE8BF85E99BB7E4B88BE8BDBD5CSquid Game_S1E0.ass
[INFO]: 2021-12-30 07:46:46 - SubDownAt: /media/tv/Squid Game (2021) [imdbid-tt10919420]/Season 01/Squid Game (2021) - s01e04.zh.ass
[INFO]: 2021-12-30 07:46:46 - OrgSubName: [xunlei]_0_Squid Game_S1E3.srt
[INFO]: 2021-12-30 07:46:46 - SubDownAt: /media/tv/Squid Game (2021) [imdbid-tt10919420]/Season 01/Squid Game (2021) - s01e03.zh.srt
[INFO]: 2021-12-30 07:46:47 - OrgSubName: [xunlei]_0_srt_S0E0.srt
[INFO]: 2021-12-30 07:46:47 - SubDownAt: /media/tv/Squid Game (2021) [imdbid-tt10919420]/Season 01/Squid Game (2021) - s01e07.zh.srt
[WARNING]: 2021-12-30 07:46:49 - ReadSeriesInfoFromDir.GetImdbInfo4SeriesDir.strconv.Atoi strconv.Atoi: parsing "": invalid syntax
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 2: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:46:50 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
```

**Comment by allanpk716** [comment]
1. Add checking/scanning for embbed subtitles

This function can be considered to increase, but the priority is to achieve the caching mechanism of this program, otherwise there will be a large number of read file requests


2. Prevent searching for movie with movie.chi.ass

I need to confirm whether there is a logical problem with the corresponding local Chinese subtitles scanning function

**Comment by wyq977** [comment]
I also run into a xml parsing issue with episode xml files generated using sonarr. the xml file exmaple:

part of the log
```
[ERROR]: 2021-12-30 07:50:18 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:50:18 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: invalid character entity & (no semicolon)
```

I am not sure if the sonarr xml parsing did sth or parsed the xml in wrong format as it has happened before where they added a url at the end of the file and I had to change setting and re scan the media library thanks to *arr #124

```
<episodedetails>
  <title>The Conjugal Configuration</title>
  <season>12</season>
  <episode>1</episode>
  <aired>2018-09-24</aired>
  <plot>Sheldon and Amy’s honeymoon runs aground in New York, while Penny and Leonard discover they are uncomfortably similar to Amy’s parents, Mr. and Mrs. Fowler. Also, Koothrappali insults physicist Neil deGrasse Tyson and starts a Twitter war.</plot>
  <uniqueid type="sonarr" default="true">1598</uniqueid>
  <thumb>https://artworks.thetvdb.com/banners/episodes/80379/6755587.jpg</thumb>
  <watched>false</watched>
  <rating>7.9</rating>
  <fileinfo>
    <streamdetails>
      <video>
        <aspect>1.77777779</aspect>
        <bitrate>3374007</bitrate>
        <codec>x265</codec>
        <framerate>23.976</framerate>
        <height>1080</height>
        <scantype></scantype>
        <width>1920</width>
        <duration>20.609033333333333</duration>
        <durationinseconds>1237</durationinseconds>
      </video>
      <audio>
        <bitrate>352800</bitrate>
        <channels>6</channels>
        <codec>AAC</codec>
        <language>English</language>
      </audio>
      <subtitle>
        <language>English</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
</episodedetails>
```

**Comment by wyq977** [comment]
@allanpk716 I guess I can git and try testing and modify a bit to check for problem 2. Should be quite ez. But right now I stopped the docker instance just for the time being.

As for problem 1, theres a go lib for ffprobe, could be useful for getting video info. but we can also just invoke ffmpeg in the instance, assuming chinesesubfinder has it installed. 

I'll see if I can test it locally on my mac .

**Comment by allanpk716** [comment]
> I also run into a xml parsing issue with episode xml files generated using sonarr. the xml file exmaple:
> 
> part of the log
> 
> ```
> [ERROR]: 2021-12-30 07:50:18 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
> [ERROR]: 2021-12-30 07:50:18 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: invalid character entity & (no semicolon)
> ```
> 
> I am not sure if the sonarr xml parsing did sth or parsed the xml in wrong format as it has happened before where they added a url at the end of the file and I had to change setting and re scan the media library thanks to *arr #124
> 
> ```
> <episodedetails>
>   <title>The Conjugal Configuration</title>
>   <season>12</season>
>   <episode>1</episode>
>   <aired>2018-09-24</aired>
>   <plot>Sheldon and Amy’s honeymoon runs aground in New York, while Penny and Leonard discover they are uncomfortably similar to Amy’s parents, Mr. and Mrs. Fowler. Also, Koothrappali insults physicist Neil deGrasse Tyson and starts a Twitter war.</plot>
>   <uniqueid type="sonarr" default="true">1598</uniqueid>
>   <thumb>https://artworks.thetvdb.com/banners/episodes/80379/6755587.jpg</thumb>
>   <watched>false</watched>
>   <rating>7.9</rating>
>   <fileinfo>
>     <streamdetails>
>       <video>
>         <aspect>1.77777779</aspect>
>         <bitrate>3374007</bitrate>
>         <codec>x265</codec>
>         <framerate>23.976</framerate>
>         <height>1080</height>
>         <scantype></scantype>
>         <width>1920</width>
>         <duration>20.609033333333333</duration>
>         <durationinseconds>1237</durationinseconds>
>       </video>
>       <audio>
>         <bitrate>352800</bitrate>
>         <channels>6</channels>
>         <codec>AAC</codec>
>         <language>English</language>
>       </audio>
>       <subtitle>
>         <language>English</language>
>       </subtitle>
>     </streamdetails>
>   </fileinfo>
> </episodedetails>
> ```

Can you just upload the XML file? When this program reads these files, it makes a guess at the encoding and then transcodes, which is probably caused by this part. At present, no good solution has been found to solve the problem of file coding. If it is UTF-8, it is easy to manage, and other failure rates are relatively high.

**Comment by wyq977** [comment]
Yep, trying to upload it beforfe but gh doesnt support nfo file... I zipped it uploaded now.

[example_episode_nfo.zip](https://github.com/allanpk716/ChineseSubFinder/files/7792613/example_episode_nfo.zip)

**Comment by allanpk716** [comment]
> 

problem 1:
If this feature is implemented, additional Settings will have to be given to the user to choose from. For example, in fact, many Chinese users like the function of Chinese and English subtitles, not because there are built-in subtitles, they want to skip the subtitles download, so there should be additional Settings. More inclined to let the general user hang up to use the program, rather than entanglement and Settings and selection of the program's functions.

It will also be guided on the Web interface to let users choose the environment suitable for their use, which will automatically help them to configure, but not so fast, first wait for friends to make the Web.

**Comment by wyq977** [comment]
Yep the first problem is indeed more of a personal preference thing that
should be placed in settings.

A brief example/explanation should be added since a lot of users would
still prefer chi&eng.ass over the embedded ones, myself included.

Apart for that, maybe more setting can be set in the future as some users
have manually downloaded and curated for their collection and preferred not
to update.

Like Friends and Seinfeld tv shows I have. I have manually downloaded
before and selected the best ones, would rlly just leave that part alone.

Kind of like the monitoring /unmonitored settings in sonarr and radarr

**Comment by allanpk716** [comment]
> Yep the first problem is indeed more of a personal preference thing that should be placed in settings. A brief example/explanation should be added since a lot of users would still prefer chi&eng.ass over the embedded ones, myself included. Apart for that, maybe more setting can be set in the future as some users have manually downloaded and curated for their collection and preferred not to update. Like Friends and Seinfeld tv shows I have. I have manually downloaded before and selected the best ones, would rlly just leave that part alone. Kind of like the monitoring /unmonitored settings in sonarr and radarr


There should be no need to worry about this situation. Generally speaking, as long as your video has external Chinese subtitles under it, and the video has been published for two years, it will be skipped.

**Comment by allanpk716** [comment]
> Yep, trying to upload it beforfe but gh doesnt support nfo file... I zipped it uploaded now.
> 
> [example_episode_nfo.zip](https://github.com/allanpk716/ChineseSubFinder/files/7792613/example_episode_nfo.zip)

There is no problem with this file you uploaded, I see your fault log is about 《Squid Game (2021)》, There is no problem with this file you uploaded, I see your fault log is about

**Comment by wyq977** [comment]
> > Yep, trying to upload it beforfe but gh doesnt support nfo file... I zipped it uploaded now.
> > [example_episode_nfo.zip](https://github.com/allanpk716/ChineseSubFinder/files/7792613/example_episode_nfo.zip)
> 
> There is no problem with this file you uploaded, I see your fault log is about 《Squid Game (2021)》, There is no problem with this file you uploaded, I see your fault log is about

There are many cases I saw that error I just picked one and uploaded, Heres another with TV shows, weird enough, in this case, the `.chi.ass` were recongized and skipped downloads, still with the xml parsing error tho.

```
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e01.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e02.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e03.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e04.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e05.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e06.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e07.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e08.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:41 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Backup/._American Crime Story (2016) - s03e09.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e01.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e02.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e03.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e04.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e05.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e06.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e07.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e08.chi.ass not support SubType
[WARNING]: 2021-12-30 07:37:43 - IsSubHasChinese.DetermineFileTypeFromFile /media/tv/American Crime Story (2016) [imdbid-tt2788432]/Season 03/._American Crime Story (2016) - s03e09.chi.ass not support SubType
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:44 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[INFO]: 2021-12-30 07:37:44 - Skip because find sub file and downloaded or aired over 3 months, American Crime Story 3 3
[INFO]: 2021-12-30 07:37:44 - Skip because find sub file and downloaded or aired over 3 months, American Crime Story 3 4
[INFO]: 2021-12-30 07:37:44 - Skip because find sub file and downloaded or aired over 3 months, American Crime Story 3 1
[INFO]: 2021-12-30 07:37:44 - Skip because find sub file and downloaded or aired over 3 months, American Crime Story 3 2
[INFO]: 2021-12-30 07:37:44 - 0 DlSub Start /media/tv/American Crime Story (2016) [imdbid-tt2788432]
[INFO]: 2021-12-30 07:37:44 - American Crime Story IMDB ID: tt2788432 NeedDownloadSubs: 6
[INFO]: 2021-12-30 07:37:44 - S3E5
[INFO]: 2021-12-30 07:37:44 - S3E7
[INFO]: 2021-12-30 07:37:44 - S3E8
[INFO]: 2021-12-30 07:37:44 - S3E10
[INFO]: 2021-12-30 07:37:44 - S3E6
[INFO]: 2021-12-30 07:37:44 - S3E9
[INFO]: 2021-12-30 07:37:44 - 0 shooter Start...
[INFO]: 2021-12-30 07:37:44 - 0 zimuku Start...
[INFO]: 2021-12-30 07:37:44 - 0 xunlei Start...
[ERROR]: 2021-12-30 07:37:47 - 0 shooter GetSubListFromFile4Series Post "https://www.shooter.cn/api/subapi.php": x509: certificate is valid for shooter.cn, not www.shooter.cn
[INFO]: 2021-12-30 07:37:47 - 0 shooter End...
[INFO]: 2021-12-30 07:37:48 - 0 xunlei End...
[INFO]: 2021-12-30 07:37:53 - 0 zimuku End...
[INFO]: 2021-12-30 07:37:53 - 0 DlSub End /media/tv/American Crime Story (2016) [imdbid-tt2788432]
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: illegal character code U+0000
[ERROR]: 2021-12-30 07:37:56 - model.GetImdbInfo4OneSeriesEpisode XML syntax error on line 1: invalid character entity &� (no semicolon)
```
[tmp.zip](https://github.com/allanpk716/ChineseSubFinder/files/7793117/tmp.zip)

**Comment by allanpk716** [comment]
There is no problem with the test of this batch of files. It is estimated that the log did not print out which file was read, so it is not convenient for you to find the specific file. I updated the print of this partial log. 😂
