### ISSUE TITLE
Embyapi: 大量的tcp连接导致connect: cannot assign requested address

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#140]
# 问题
当前程序至少会请求embyapi, LimitCount * 2(电影+剧集 filterEmbyVideoList()) * 2(GetItemAncestors()+GetItemVideoInfo())次, 每次请求都会重新打开一个tcp连接, 而端口数又是有限的(sysctl net.ipv4.ip_local_port_range, 默认大概2.8w个端口可用于打开连接), 从而导致标题的报错

# 分析
golang的http支持端口复用, 但目前emby_api()内部每个连接就会实例化(getNewClient())一个resty(内部封装的http.clent()).

# 可能的解决方法
emby_api保存http.clent()指针, 根据需要来重用.

**Comment by allanpk716** [comment]
1. 之前测试刷新 Emby 媒体库的时候太慢，所以用了并发，考虑到这一点才是每一次请求开一个实例。EmbyApi.RefreshRecentlyVideoInfo，这个函数 6 线程（chan）去刷新
2. 理论上其他时候使用 getNewClient 问题不大，还是说其实回收这个实例太慢了，导致不够用了？
3. 我还没测试过 resty 一个实例的时候，是否支持并发玩。

**Comment by wloot** [comment]
尝试修改了下, 感觉已经有改善了:
https://github.com/wloot/ChineseSubFinder/commit/3bce44d167165ba55db2b9ee6cd5caad3bafa3c8 和 https://github.com/wloot/ChineseSubFinder/commit/b6c221e9dbdf3630b0d18fa1b130d0fd02c2d9d6

配置LimitCount为10000, 通过命令`netstat -ant |wc -l`观察连接数, 更改之前可以到大约3w然后日志开始报错. 应用更改后, 连接数大约在1000左右, 日志正常.

主要改了以下两点:
1. 保存resty.client指针, 后续请求重用它. 由于是线程安全的, 所以不用担心多线程情况.
2. 增加传输层参数MaxIdleConnsPerHost到100(golang默认MaxIdleConnsPerHost为2, MaxIdleConns为100). 由于我们的api请求都是同一个host的情况下, 所以只能有2个idle连接, 导致复用基本没效果.

**Comment by allanpk716** [comment]
> 尝试修改了下, 感觉已经有改善了:
> 
> https://github.com/wloot/ChineseSubFinder/commit/3bce44d167165ba55db2b9ee6cd5caad3bafa3c8 和 https://github.com/wloot/ChineseSubFinder/commit/b6c221e9dbdf3630b0d18fa1b130d0fd02c2d9d6
> 
> 
> 
> 配置LimitCount为10000, 通过命令`netstat -ant |wc -l`观察连接数, 更改之前可以到大约3w然后日志开始报错. 应用更改后, 连接数大约在1000左右, 日志正常.
> 
> 
> 
> 主要改了以下两点:
> 
> 1. 保存resty.client指针, 后续请求重用它. 由于是线程安全的, 所以不用担心多线程情况.
> 
> 2. 增加传输层参数MaxIdleConnsPerHost到100(golang默认MaxIdleConnsPerHost为2, MaxIdleConns为100). 由于我们的api请求都是同一个host的情况下, 所以只能有2个idle连接, 导致强并发下连接复用基本没效果.

明天我看看，你提及的内容没接触过。有啥再问你。

**Comment by allanpk716** [comment]
按照你的思路改了，我且到 beta 丢家里挂机试试，过几天没啥就推送正式版本上。
