### ISSUE TITLE
[feat] Better commit msg, better issue categories

### ISSUE THREAD

**Issue by wyq977** [allanpk716/ChineseSubFinder#143]
I think the commit and issues in this repo could use a bit formatting, like this:

Example:

Better commit msg:
```
<type>(<scope>): <subject>
```

* build: Build related changes (eg: npm related/ adding external dependencies)
* chore: A code change that external user won't see (eg: change to .gitignore file or .prettierrc file)
* feat: A new feature
* fix: A bug fix
* docs: Documentation related changes
* refactor: A code that neither fix bug nor adds a feature. (eg: You can use this when there is semantic changes like renaming a variable/ function name)
* perf: A code that improves performance
* style: A code that is related to styling
* test: Adding new test or making changes to existing test

Ref:
https://github.com/fteem/git-semantic-commits
https://www.conventionalcommits.org/zh-hans/v1.0.0/
https://dev.to/i5han3/git-commit-message-convention-that-you-can-follow-1709

**Comment by wyq977** [comment]
Issues should be more easier to organized, a `[feat]` and `[bug]` should be enough.

**Comment by allanpk716** [comment]
The project was done in the middle of a variety of things, probably half of which needed to be done on other things, so I had to quickly record and describe the current changes. The submitted remarks are clearly unfriendly to others. But I can make sure there are good notes to explain and guide anyone interested in the code logic, while leaving as much documentation as possible.

Your suggestions are good and help to standardize the development process of the project. I think I will try your proposal after the main functions are finished and the stable version comes out. More comments are welcome.

**Comment by wyq977** [comment]
Yep i cant agree more on that. Its better to have a no-so-clean code that runs than a clean one that does nothing. This project is great for the few ones that really needs it.

[ChineseSubFinder--2021Len12300000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7795683/ChineseSubFinder--2021Len12300000--.log)


I have run into another issue with queue in Series download task and maybe will open another issue to discuss that, attached is the log and part of the important ones. Basically, the problem seems that theres only 1 queue for all 3 series (A, B, C) instead of downloading for A - s**e**, B - s**e** and C - s**e**, logs and files shows it only searchs for tvshow B (BONDING in my test case)

```log
[INFO]: 2021-12-30 19:51:11 - Download Movie Sub End...
[INFO]: 2021-12-30 19:51:11 - Download Series Sub Started...
[ERROR]: 2021-12-30 19:51:13 - Video:  American Crime Story (2016) - s03e01.mkv
[ERROR]: 2021-12-30 19:51:13 - Video:  BONDiNG (2019) - s01e01.mkv
[ERROR]: 2021-12-30 19:51:13 - Video:  Dexter - New Blood (2021) - s01e03.mkv
[ERROR]: 2021-12-30 19:51:13 - Videos in this folder:  3
[ERROR]: 2021-12-30 19:51:13 - Subs in this folder:  0
[INFO]: 2021-12-30 19:51:13 - Queue 0 DlSub Start /Users/wyq977/Documents/media/tv
[INFO]: 2021-12-30 19:51:13 - Queue 0 Bonding IMDB ID: tt7718088 NeedDownloadSubs: 3
[INFO]: 2021-12-30 19:51:13 - Queue 0 Bonding - S3E1
[INFO]: 2021-12-30 19:51:13 - Queue 0 Bonding - S1E1
[INFO]: 2021-12-30 19:51:13 - Queue 0 Bonding - S1E3
[INFO]: 2021-12-30 19:51:13 - Queue 0 shooter Start...
[INFO]: 2021-12-30 19:51:13 - Queue 0 zimuku Start...
[INFO]: 2021-12-30 19:51:13 - Queue 0 xunlei Start...
```

**Comment by allanpk716** [comment]
If you can communicate in Chinese, it is estimated that it will be more efficient.  Mainly, my English is relatively poor, and it seems that I need to think about it. It is possible to understand that I can also understand that communicating in English is more suitable for serving the public, but the current goal may be to serve Chinese users, and it may be possible to produce English documents after stability.  More suitable.

Of course, Chinese has to be your main language, otherwise it will be a burden to you.  If it is not, it is okay to continue to use English.

**Comment by wyq977** [comment]
中文交流没问题 只是懒得换 sorry 

我在开一个repo放test files 但是现在一步步开test files都用到了什么文件

建议事你另开一个issue for tracking example files，当然在这也行

**Comment by wyq977** [comment]
Happy new year btw!

**Comment by wyq977** [comment]
首先谢谢你的贡献 中文字幕下载确实一直是个痛点 希望能实现无缝全自动追剧 
这两天主要看了test file 提一两点建议 欢迎讨论 希望 @allanpk716 给点意见

1. 字幕下载器主要功能下载   
    * __应少涉及文件更改__ 尽量只“碰”字幕文件，防止用户 library 爆炸
    * 理想情况下应该有个 database 指向字幕位置 没仔细看 好像现在已经是了
2. 字幕矫正涉及读写操作比较多  rename mv files
    * 应该迁移到另一个library CSF只调动api就好了，保证视频音频文件不会被误删 或者复制读写 影响虚拟机/服务器 IO
    * e.g. `if needSyncSub == true: sync(movie.mp4, movie.zh.ass)`
    * 现在 formatter 还要一些提取文件名的操作还有 bug, 应该是不会误删的 但我觉得还是以防万一为好
    * 这样也方便测试 开发 因为同步字幕的这些操作理论上不涉及 sonarr/plex/emby 数据 也不需要联网 
    * 理想情况下 https://github.com/smacke/ffsubsync 就够了 不过有双语字幕应该会复杂不少
    * golang有字幕处理的pkg https://github.com/martinlindhe/subtitles
3. test files 需要标准化, 如果不涉及文件读写只是读取名字的话 尽量采用 TempDir 或者 TempFile
    * 现在正在整理测试文件, copyTestData 应该之后就不用了
    * integration test：复杂 具体的测试 TODO
    
    
    
测试需要的音频视频字幕文件 （上传到另一个 repo）
ffmpeg_helper: videos with multiple audio tracks, subtitles, and the json
sub_timeline_fixer: 待同步的字幕、音轨、视频

**Comment by wyq977** [comment]
Some resources just FYI

https://github.com/nutbread/ass
https://github.com/nattofriends/python-ass
Good https://github.com/tkarabela/pysubs2
Good https://github.com/byroot/pysrt

**Comment by allanpk716** [comment]
> Happy new year btw!
> 
> 

新年快乐哈

**Comment by allanpk716** [comment]
其实 ffsubcync 的原理跳过了语言问题，直接是用语音检测 VAD 的思想把字幕和人声音频挂钩，然后通过 FFT 计算比较得到的。目前我复现的情况来看，可以确定，对于一些情况的字幕它还是有待提高的，个人觉得有希望解决，这也就是为什么不不想直接使用这个项目，自己重写到 golang 后，有些改动就可以在本项目中完成，如果效果可以，再抽取出来给大家用就好了。

**Comment by allanpk716** [comment]
因为重构的问题，目前测试用例依赖的额外的文件已经移到额外的项目中，但是目录结构大方向是确定的（为了更好的单元测试），但是具体怎么分类，我暂时是偷懒了以快速解决单元测试通过为主。近期会把下一阶段要做的功能整理一下，然后根据进度需求再调整吧。
