### ISSUE TITLE
v0.19.3 docker容器体积无限膨胀

### ISSUE THREAD

**Issue by ptbsare** [allanpk716/ChineseSubFinder#145]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.3

环境: docker

## 你遇到什么问题了？
运行一晚上后docker容器体积会膨胀到硕大无比，达到警戒值，而且在继续变大。
描述一下你遇到的问题
docker容器体积无限膨胀
## 你的问题弄重现嘛？

能够重现

## 你期望的结果
docker容器体积正常
描述以下你期望的结果
docker容器体积保持稳定正常
## 可以提供遇到问题时候，电影、连续剧的信息吗？

![Screen Shot 2021-12-31 at 09 25 33](https://user-images.githubusercontent.com/3147576/147797829-924ab3b3-301f-426e-9cdd-04b06a08b22e.png)

## 出错的日志信息可以复制一些出来吗？

没有出错日志。

**Comment by ptbsare** [comment]
看了下说明，开启了fix字幕后可能需要映射/app/CSF-SubFixCache，建议更新docker映射目录说明的readme，否则容器体积会变得很大。

**Comment by allanpk716** [comment]
> 看了下说明，开启了fix字幕后可能需要映射/app/CSF-SubFixCache，建议更新docker映射目录说明的readme，否则容器体积会变得很大。

不好意思，这个是我疏忽。如何发现还有其他问题再提。

**Comment by allanpk716** [comment]
@SuperNG6 有空估计也麻烦你更新下你的博文（变相催更了:joy:），估计很多人是看你的才会去使用本工具，应该也会遇到类似的问题。

**Comment by SuperNG6** [comment]
> @SuperNG6 有空估计也麻烦你更新下你的博文（变相催更了😂），估计很多人是看你的才会去使用本工具，应该也会遇到类似的问题。

好的，这就更新😂
