### ISSUE TITLE
[bug] How to run test for some pkg

### ISSUE THREAD

**Issue by wyq977** [allanpk716/ChineseSubFinder#147]
Hi i am not familar with testing in golang, wondering if `config.yaml` is needed for testing like sub_parser_hub

```shell
go test -v  ./internal/pkg/sub_parser_hub/ # error
# after sample config
cp config.yaml ./internal/pkg/sub_parser_hub/
# normal test
```

```log
panic: GetConfig - initConfigure error reading config:Config File "config" Not Found in "[/Users/wyq977/projects/ChineseSubFinder/internal/pkg/sub_parser_hub]" [recovered]
        panic: GetConfig - initConfigure error reading config:Config File "config" Not Found in "[/Users/wyq977/projects/ChineseSubFinder/internal/pkg/sub_parser_hub]"

```

**Comment by allanpk716** [comment]
This is my laziness. In order to facilitate the introduction of the unified log function, after confirming that the function of v0.19 is stable recently, I plan to refactor to solve these problems.

**Comment by wyq977** [comment]
我看到了在config.go那里 我先看看能不能改了 做个PR

**Comment by wyq977** [comment]
```go
package config

import (
	"errors"
	"github.com/allanpk716/ChineseSubFinder/internal/pkg/global_value"
	"github.com/allanpk716/ChineseSubFinder/internal/types"
	"github.com/spf13/viper"
	"strings"
	"sync"
	"os"
	"fmt"
	"runtime"
)

// GetConfig 统一获取配置的接口
func GetConfig() *types.Config {
	configOnce.Do(func() {
		configViper, err := initConfigure()
		if err != nil {
			panic("GetConfig - initConfigure " + err.Error())
		}
		config, err = readConfig(configViper)
		if err != nil {
			panic("GetConfig - readConfig " + err.Error())
		}
		// 读取用户自定义的视频后缀名列表
		for _, customExt := range strings.Split(config.CustomVideoExts, ",") {
			global_value.CustomVideoExts = append(global_value.CustomVideoExts, "."+customExt)
		}

		// 这里进行 Default 值的判断
		config.SubTimelineFixerConfig.CheckDefault()
	})
	return config
}

// initConfigure 初始化配置文件实例
func initConfigure() (*viper.Viper, error) {
	nowConfigDir := getConfigDir()
	if nowConfigDir == "" {
		fmt.Sprintf("initConfigure().getConfigDir()")
	}

	v := viper.New()
	v.SetConfigName("config") // 设置文件名称（无后缀）
	v.SetConfigType("yaml")   // 设置后缀名 {"1.6以后的版本可以不设置该后缀"}
	v.AddConfigPath(nowConfigDir)      // 设置文件所在路径

	err := v.ReadInConfig()
	if err != nil {
		return nil, errors.New("error reading config:" + err.Error())
	}

	return v, nil
}

// readConfig 读取配置文件
func readConfig(viper *viper.Viper) (*types.Config, error) {
	conf := &types.Config{}
	err := viper.Unmarshal(conf)
	if err != nil {
		return nil, err
	}
	return conf, nil
}

func getConfigDir() string {
	nowConfigDir := ""
	sysType := runtime.GOOS
	if sysType == "linux" {
		nowConfigDir = configDirLinux
	}
	if sysType == "windows" {
		nowConfigDir = configDirWindows
	}
	if sysType == "darwin" {
		home, _ := os.UserHomeDir()
		nowConfigDir = home + "/.config/chinesesubfinder/" + configDirDarwin
	}
	return nowConfigDir
}

var (
	config     *types.Config
	configOnce sync.Once
)

const (
	configDirLinux   = "/config/"
	configDirWindows = ""
	configDirDarwin  = ""
)
```

**Comment by wyq977** [comment]
我稍微改了下 linux`/config/ ` macos: `.config` 等我把 test 看完再push上来吧

**Comment by wyq977** [comment]
see c0c1fa168183e5f9354664381ce576a7085afd74

**Comment by allanpk716** [comment]
日志梗的问题，我会进行重构，保持目前的用法，但是不予 config 文件强制关联

**Comment by allanpk716** [comment]
我在修复测试用例的问题，按你大致方法把文件给抽取到另一个项目了，目录暂时先继承之前的。如果要改动的话，建议按我重构的方向吧。放到本项目同级目录即可，https://github.com/allanpk716/ChineseSubFinder-TestData，有些数据在本地跑测试用例的时候，为了不用去还原，所以有部分是做的 copye 操作再跑测试用例的。

还没有完全改完，一点点来，顺带发现了一些bug，一并修复。如果不急的话，等我把现有的测试用例都修复完毕再改动更佳。

**Comment by wyq977** [comment]
ok 不急不急
我写了个script 你看看有没有用

**Comment by allanpk716** [comment]
> 

部分改完了，剩下几个功能的单元测试还没改：
* ffmpeg、ffprobe 读取视频和音频信息
* shooter、xunlei 计算视频唯一ID，然后下载字幕
* emby 以及后续的 plex 和 Jellyfin API 测试

目前有想法的是，shooter、xunlei 计算视频唯一ID，这个可以用代码动态制作一个带有其算法抽取特征点的视频出来，应该问题不大。但是其他两个，暂时没啥思路。

你看看是否可能有办法伪造某个视频的字幕和音频信息，这样在
https://github.com/allanpk716/ChineseSubFinder/blob/dev/internal/logic/sub_timeline_fixer/SubTimelineFixerHelperEx_test.go
这个测试用例中，就能够完整的测试整个流程了。

**Comment by wyq977** [comment]
ffmpeg 的测试用那个生成视频的应该就可以了 字幕语言之类的 metadata 应该也可以改

单纯的生成视频字幕没关系 但好像那个 fixer 是提取音轨然后再同步的 随机生成的字幕和合成的 audio 好像不太行？ 具体实现细节我没太看

**Comment by allanpk716** [comment]
1. ffmpeg 你可以基于现在的 dev 分支改一下，我好学习下你是怎么做的。目前我都是用 goland 去跑单元测试。
2. SubTimelineFixerHelperEx 这个优先提取字幕（没有则是音频），然后进行字幕时间轴的匹配再修正和导出字幕。或许会考虑制作一个真实的短视频（用  ffmpeg 去截取一个视频几分钟，主要是不确定字幕也可以同步被截取）样本来做测试也行

**Comment by wyq977** [comment]
1. 你是说ffmpeg 的test 还是生成随机视频呢
2. 我得回头看看FixerHelper的逻辑 你能稍微给我说一下吗 大概 因为如果是ffsubsync的思路的话 随机的音频字幕是不行的好像
得要real data （正常的电视剧/电影audio sync with 字幕）ffmpeg 生成的audio都是那种有规律的frequency
wave 和random noise sound 估计没发测试同步。而且有个真实的视频片段也好人工后面核对

**Comment by wyq977** [comment]
我周末看看fixer


ffmpeg现在生产的就是标准的sample video

像这种
![0EE214CF-DAB0-4934-A5CF-762EE947B118](https://user-images.githubusercontent.com/27303600/148553048-52e19cfb-3fe5-413c-b0a8-514e971fc313.jpeg)

**Comment by allanpk716** [comment]
shooter 和 xunlei 下载器的单元测试也更新了，使用了 https://github.com/allanpk716/ChineseSubFinder-TestData 中的特征点文件去生成视频测试的。

上面提到的项目参考你的项目改了下，目录结构不一定合理，主要是先修复单元测试的问题···有啥再调整吧。

我去看看 ffmpeg 怎么截取视频，截取后是否能带对应的字幕和音频导出先。如何可以，就截取个5min，然后人为制造字幕偏移做测试就好了。

**Comment by wyq977** [comment]
ChineseSubFinder-TestData he ChineseSubFinder 是放在同一个目录下的嘛？


> 我去看看 ffmpeg 怎么截取视频，截取后是否能带对应的字幕和音频导出先。如何可以，就截取个5min，然后人为制造字幕偏移做测试就好了。

ffmpeg提取片段: https://stackoverflow.com/questions/18444194/cutting-the-videos-based-on-start-and-end-time-using-ffmpeg
> try using this. It is the fastest and best ffmpeg-way I have figure it out:

```
ffmpeg -ss 00:01:00 -i input.mp4 -to 00:02:00 -c copy output.mp4
```
截取字幕其实都可以手动操作删掉不要的就行了

**Comment by wyq977** [comment]
make test 我跑好像还有一个fail了

```
$ go test ./internal/pkg/sub_helper/
../../../../ChineseSubFinder-TestData/sub_helper/test/Sub_S1E0 /Users/wyq977/projects/ChineseSubFinder/internal/pkg/sub_helper/CSF-DebugThings/XXX/Sub_S1E0
--- FAIL: TestDeleteOneSeasonSubCacheFolder (0.00s)
    sub_helper_test.go:30: stat ../../../../ChineseSubFinder-TestData/sub_helper/test/Sub_S1E0: no such file or directory
FAIL
FAIL    github.com/allanpk716/ChineseSubFinder/internal/pkg/sub_helper  0.236s
FAIL
```

https://github.com/allanpk716/ChineseSubFinder/blob/06b210dc9cede703f98ad7d013f3c1d9f41fbfbc/internal/pkg/sub_helper/sub_helper_test.go#L28

**Comment by allanpk716** [comment]
再试试，最新 dev 应该可以

**Comment by wyq977** [comment]
我试了 👌

emby的我先不测了 没有装

先看看 fixer 有问题告诉你

**Comment by allanpk716** [comment]
> 

我主要对比测试了 ffsubsync 与 go 复现版本的，字幕校正字幕的功能。原始的算法还是有一定改进的空间的（偏移的时间越长，越容易出现视频尾部时间有轻微的对应不上），我抽时间整理下，然后把单元测试和对比的资源给出来。改进的思路大致有了，就是得找时间去尝试。

**Comment by wyq977** [comment]
最新的dev 

$ go test -v ./internal/pkg/sub_timeline_fixer/ -count 1

pass 了

**Comment by allanpk716** [comment]
确实可以，只不过现在还不完善，临时写的东西太多，等把想做的主要功能做完，再抽取里面一些模块出来，后续其他人想做啥东西都方便。

**Comment by wyq977** [comment]
bro 你push的好勤快啊hhhh 是放假了嘛 我可能没之前那么勤快了 不过有什么修改CI unit testing 可以 @我 或者assign 给我。例如让我生成个随机字幕，随机音频视频文件的 shell script 什么的

webui 可以参考一下这个 也是用golang 写的 https://github.com/stashapp/stash ~~（小电影整理）~~
提个小小的建议啊 我在想之后你重构的时候 涉及字幕同步/读写的可以考虑写在另一个包里 主要是ChineseSubFinder单纯来说其实不需要读写字幕，i.e. 提取字幕dialogue 修改字幕ass等。而我看了看实际字幕读写的主要就是sync时间轴，其余的大多是只需要验证文件名的。

不过现在不要紧 能跑就行hhh 个人项目太正常了 你也不要比自己写得太快 慢慢来就好 不用急

**Comment by allanpk716** [comment]
都是碎片时间，想着点啥就弄点。理清后，有些需要麻烦你帮实现的。 @wyq977 

@iMyon 可以看看上面提到的这个小电影程序，后续可能会用把类似的视频预览图界面弄出来，便于选择视频和字幕的调整。

**Comment by allanpk716** [comment]
经过这次重构几乎能够（改动容易的）单元测试的都支持了，不容易（需要依赖 Emby 等）做单元测试的都进行了注释···后续再想想怎么提高单元测试的覆盖吧
