### ISSUE TITLE
双语字幕优先拉取

### ISSUE THREAD

**Issue by LiuZhangshu** [allanpk716/ChineseSubFinder#149]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.4

环境: docker

## 你想要新增或者改进什么功能？

作者您好，感谢提供了这样一个非常好用的工具；后续是否考虑支持优先下载双语字幕。主要是希望通过双语字幕提高一下英语水平。感谢

## 这个功能有什么可以参考的资料吗？

暂无

**Comment by wyq977** [comment]
好像这些网站中只有subhd 有标记`简英双语` 但是作者暂时屏蔽了

本地的判断双语的功能好像暂时还没有

**Comment by allanpk716** [comment]
程序默认是双语优先，也会读取字幕去判断是否是双语字幕。具体设置你看看文档，或者遇到bug，再具体提。

**Comment by allanpk716** [comment]
> 好像这些网站中只有subhd 有标记`简英双语` 但是作者暂时屏蔽了
> 
> 
> 
> 本地的判断双语的功能好像暂时还没有
> 
> 
> 
> 所以这问题大概率暂时无法解决

本地判断有，就怕写的逻辑有 bug 没触发
