### ISSUE TITLE
[feat] better GetLogger() location

### ISSUE THREAD

**Issue by wyq977** [allanpk716/ChineseSubFinder#150]
现在跑, Log 会直接写在当前 dir 下面 考虑在不同 OS 设置默认 log 位置 类似 getDb() getConfigDir()

```
$ go test ./internal/pkg/my_util/
```

**Comment by allanpk716** [comment]
> 现在跑, Log 会直接写在当前 dir 下面 考虑在不同 OS 设置默认 log 位置 类似 getDb() getConfigDir()
> 
> 
> 
> ```
> 
> $ go test ./internal/pkg/my_util/
> 
> ```

现在这个日志得用法很难受，也是与配置文件相关导致的。初期的思路是把err 丢到尽可能上层再输出，后面为了协助用户定位问题，日志输出越来越偏向基础模块就需要了，导致没有重构就临时去使用了。
 
想法是日志只需要一个日志级别的设置而已，可能会像你说的，不同平台在不用地方写一个特殊文件即可。这样用起来方便，也不会导致模块的单元测试那么恶心。

**Comment by wyq977** [comment]
should be fixed in #154

**Comment by allanpk716** [comment]
暂时不动这个部分。后续重构，直接把日志与配置分离。间接与配置文件相关。

**Comment by allanpk716** [comment]
已经大范围重构了一次，只能说暂时适合现在的应用场景吧···
