### ISSUE TITLE
停在 First Time Download End 版本v0.19.4 问题已经解决 开始下载了。。

### ISSUE THREAD

**Issue by huiyuerandy** [allanpk716/ChineseSubFinder#152]
[INFO]: 2022-01-01 22:47:33 - Download One Started...
[INFO]: 2022-01-01 22:47:33 - Refresh Emby Sub List Success
[INFO]: 2022-01-01 22:47:34 - Download Movie Sub Started...
[INFO]: 2022-01-01 22:47:34 - Movie Sub Dl From Emby API...
[INFO]: 2022-01-01 22:47:34 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2022-01-01 22:47:34 - Download Movie Sub End...
[INFO]: 2022-01-01 22:47:34 - Download Series Sub Started...
[INFO]: 2022-01-01 22:47:34 - Download Series Sub End...
[INFO]: 2022-01-01 22:47:34 - Refresh Emby Sub List Success
[INFO]: 2022-01-01 22:47:34 - Download One End...
[INFO]: 2022-01-01 22:47:34 - First Time Download End

**Comment by huiyuerandy** [comment]
看别人的问题知道了 config.yaml
MovieFolder: /media/movies14 
要和emby对应就行了

**Comment by allanpk716** [comment]
那就好，今年争取把 Web 设置界面做出来，附带设置的引导功能，期望能做到新手无教程完成基础的设置。

**Comment by huiyuerandy** [comment]
早上起来看有出现同样的问题啦。下了几个字幕又开始了。
[INFO]: 2022-01-02 06:41:47 - Skip /media/movies14/Wolf.Warriors.2.2017.WEB-DL.1080p.H264.AAC-FDHD.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-01-02 06:41:50 - Skip /media/movies14/一秒钟.One.Second.2020.WEB-DL.1080p.H264.AAC@48kHz-LMovHD/一秒钟.One.Second.2020.Bonus.1.张艺谋-这是一个我心心念念了很久的故事.WEB-DL.1080p.H264.AAC@48kHz-LMovHD.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-01-02 06:41:53 - Skip /media/movies14/一秒钟.One.Second.2020.WEB-DL.1080p.H264.AAC@48kHz-LMovHD/一秒钟.One.Second.2020.Bonus.2.张译vs范伟-哪里有演什么像什么,只有不断努力地靠近.WEB-DL.1080p.H264.AAC@48kHz-LMovHD.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-01-02 06:41:56 - Skip /media/movies14/一秒钟.One.Second.2020.WEB-DL.1080p.H264.AAC@48kHz-LMovHD/一秒钟.One.Second.2020.Bonus.3.刘浩存-成为谋女郎的几率是三千分之一.WEB-DL.1080p.H264.AAC@48kHz-LMovHD.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-01-02 06:41:59 - Skip /media/movies14/一秒钟.One.Second.2020.WEB-DL.1080p.H264.AAC@48kHz-LMovHD/一秒钟.One.Second.2020.WEB-DL.1080p.H264.AAC@48kHz-LMovHD.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-01-02 06:42:02 - Skip The.Age.of.Adaline.2015.720p.WEB-DL.DD5.1.H264-RARBG.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-01-02 06:42:06 - Skip 疯狂原始人.The.Croods.2013.BD1080P.X264.AAC.Mandarin&English.CHS-ENG.Adans.mp4 Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-01-02 06:42:06 - Download Movie Sub End...
[INFO]: 2022-01-02 06:42:06 - Download Series Sub Started...
[INFO]: 2022-01-02 06:42:06 - Download Series Sub End...
[INFO]: 2022-01-02 06:42:06 - Refresh Emby Sub List Success
[INFO]: 2022-01-02 06:42:06 - Download One End...

年前想看到web界面，哈哈。大佬辛苦了！

**Comment by allanpk716** [comment]
新历2022年，农历年估计赶不及，最近反馈的问题都是需要重构去解决的，看样子最好不能拖着，不然后续只会更加混乱，让其他人无从下手去协助改进本项目。

**Comment by huiyuerandy** [comment]
本身emby的字幕问题就很多， 大小 上下   还是有ass字幕我这边都是und 直接不识别。。。这些问题是不是要emby自己去解决，我们只能等。
祝大佬元旦快乐 哈哈！

**Comment by allanpk716** [comment]
> 本身emby的字幕问题就很多， 大小 上下 还是有ass字幕我这边都是und 直接不识别。。。这些问题是不是要emby自己去解决，我们只能等。 祝大佬元旦快乐 哈哈！

同乐。暂时没有发现 Emby 对于字幕的问题，估计我这边都是比较理想的使用环境。如何你发现有特殊的情况，可以具体列举下，看看是否能在外部解决。
