### ISSUE TITLE
纪录片如何设置目录呢？

### ISSUE THREAD

**Issue by palemoky** [allanpk716/ChineseSubFinder#153]
> 首先感谢作者开发了这款非常好用的软件，感谢！

## chinesesubfinder 的版本和环境
chinesesubfinder 版本: v0.19.4

环境: 群晖 Docker

## 我遇到的问题
我当前有电影、电视剧、纪录片三种类型的视频都放在了 Videos 目录下，并把Videos整个目录映射到了容器中，Videos的目录结构如下：
```
Videos
    ├-- Movies
    ├-- TV_Series
    └─Documents
```

这是我的相关配置文件内容
```
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 2
RunAtStartup: true
MovieFolder: /media/Movies
SeriesFolder: /media/TV_Series
DebugMode: false
```

我查看了 docker 的[路径设置文档](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%89%A9%E7%90%86%E8%B7%AF%E5%BE%84%E4%B8%8E%20docker%20%E5%AE%B9%E5%99%A8%E8%B7%AF%E5%8A%B2%E6%98%A0%E5%B0%84%E6%8C%87%E5%AF%BC.md)，发现只有MovieFolder和SeriesFolder，我该如何配置才能扫到纪录片呢？

**Comment by allanpk716** [comment]
暂时没有考虑纪录片进去，因为我不确定纪录片是电影的存储结构还是连续剧的，我你现在的纪录片削刮过吗？是否可以提供以下纪录片的目录结构看看，比如：纪录片的整体结构，以及具体一个纪录片的结构，具体的纪录片是否有按季划分的，如果有也希望能提供出来。

纪录片
    ├-- 纪录片A
    ├-- 纪录片B
    └─纪录片C

纪录片A
    ├-- XX
    ├-- XX
    └─XX

**Comment by palemoky** [comment]
> 暂时没有考虑纪录片进去，因为我不确定纪录片是电影的存储结构还是连续剧的，我你现在的纪录片削刮过吗？是否可以提供以下纪录片的目录结构看看，比如：纪录片的整体结构，以及具体一个纪录片的结构，具体的纪录片是否有按季划分的，如果有也希望能提供出来。
> 
> 纪录片 ├-- 纪录片A ├-- 纪录片B └─纪录片C
> 
> 纪录片A ├-- XX ├-- XX └─XX

纪录片是削刮过的，我看有 nfo 文件，现在的纪录片结构如下：
```
Videos
    ├-- Movies
    ├-- TV_Series
   └─ Documents
			  ├--- 我们的星球
			   |			├-- S01E01
			   |		    └─ S01E02
			  └─ 地球脉动
			             ├- 地球脉动第一季
						 |			├-- S01E01
						 |			└─S01E02
			             └─ 地球脉动第二季
									├─ S02E01
									└─ S02E02
```

**Comment by allanpk716** [comment]
1. 如果是这样，那临时方案可以是，你新开一个版程序的 docker，把你的纪录片路径填入“连续剧”的 config 设置中，然后把 movie 的路径指向到一个存在的空目录。
2. 如果纪录片削刮后的目录结构跟连续剧一样，那么可以新增一个专用纪录片的路径就好了
3. 但是，蓝光的字幕扫描支持有问题，记得有人提过，应该是字幕下载存储的路径不对。所以纪录片估计会更容易遇到这个问题。

**Comment by palemoky** [comment]
> 1. 如果是这样，那临时方案可以是，你新开一个版程序的 docker，把你的纪录片路径填入“连续剧”的 config 设置中，然后把 movie 的路径指向到一个存在的空目录。
> 2. 如果纪录片削刮后的目录结构跟连续剧一样，那么可以新增一个专用纪录片的路径就好了
> 3. 但是，蓝光的字幕扫描支持有问题，记得有人提过，应该是字幕下载存储的路径不对。所以纪录片估计会更容易遇到这个问题。

好的，期待后续新增纪录片的路径，多谢了~

**Comment by allanpk716** [comment]
现在升级至 v0.20.x 应该可以满足你现在的需求。蓝光支持的问题需要我下载资源进行调试。
