### ISSUE TITLE
出现大量DownFile.GetFileName is string.empty

### ISSUE THREAD

**Issue by everstarmy** [allanpk716/ChineseSubFinder#155]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.4

环境: docker  or Linux

## 你遇到什么问题了？

**下载字幕时无法分析文件名，手动复制链接地址到浏览器打开中会进入下载页，并没有直接下载文件。**
日志如下。
[ERROR]: 2022-01-02 18:52:14 - DownFile.GetFileName is string.empty https://zmk.pw/download/NjI5Njl8YWNhNWQwOTQwMDk2YzI5ZjEwM2E5OTRkfDE2NDExMjA3MzN8ZGRiNDk5ODF8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:15 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTMwNjI3fGMxNGNlZGIyYzk3OGNiMzg0OWZkNmJjOXwxNjQxMTIwNzM0fGNmNjY4NDIyfHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:17 - DownFile.GetFileName is string.empty https://zmk.pw/download/Nzk4OTR8YjVjOWY3MDQ2MzBhYjVmMDMwMTAwOTkxfDE2NDExMjA3MzZ8ZjE2MzY1ODh8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:19 - DownFile.GetFileName is string.empty https://zmk.pw/download/Nzc5NDZ8MWNlYmJlNDAzYmY1ODUzM2IzMjM1MjMyfDE2NDExMjA3Mzh8ZjA4ZmYwMzZ8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:20 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTI4Njc5fDc4MDNiMjBlMjRhZDNjMDFiNzY1Zjk4MnwxNjQxMTIwNzM5fDA1OWQ5YTlkfHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:22 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTMwNjI5fDViZTU5YTg2ODFjZTAxMWRiMzRlNDEzNXwxNjQxMTIwNzQxfDFjNGY3ZjlmfHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:23 - DownFile.GetFileName is string.empty https://zmk.pw/download/NjEwOTF8YzViYzEzYTcxOWM3OGFkYjVmZjFhYmU3fDE2NDExMjA3NDJ8MDcyMDI2ODh8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:25 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTMyNDcwfDkzZjlmOWExZTVhYjA5OTQwNTNlNWQwNXwxNjQxMTIwNzQ0fGExMmFlNDg0fHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:27 - DownFile.GetFileName is string.empty https://zmk.pw/download/Nzc1Njd8N2IzYTQ1YzA2YjE0MGE1NTkwOGY0ZDQ3fDE2NDExMjA3NDZ8ZjQwYmE4ODl8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:28 - DownFile.GetFileName is string.empty https://zmk.pw/download/ODc3MDN8NGJkYzFkNmU1MzcwZTVlYWE2MTg2OWU5fDE2NDExMjA3NDd8ZjMxNGQxOTN8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:30 - DownFile.GetFileName is string.empty https://zmk.pw/download/OTcyMDh8ZTMzZGY1Yzk4OGJkZWQxZjY1M2ZkODlhfDE2NDExMjA3NDl8M2E2ODdlNWV8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:32 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTI3MTE4fGQ5MWIwNjM3MTJiNmRjMmFlMmRiMWJhYXwxNjQxMTIwNzUxfDA3OTZmNjRjfHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:33 - DownFile.GetFileName is string.empty https://zmk.pw/download/NjM1NjJ8ZGEzYTRlOTkzZDk3YjkxY2EwYjYyMDY1fDE2NDExMjA3NTJ8ZGJhNjBkYTV8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:35 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTI0MTM4fGFhODk5ZTY5ZDViNGZlNmQ0ZmY1ODBkMXwxNjQxMTIwNzU0fDhmY2ExOTRifHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:36 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTYxNzc5fGI5NTQ3MDliNDliYjc1NjJhNGNiMDhkMnwxNjQxMTIwNzU1fGJkOWM3OTQ5fHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:38 - DownFile.GetFileName is string.empty https://zmk.pw/download/NzcxNDR8NjNkYzlmZGE3M2U3ODdmMzg4YjVlODkzfDE2NDExMjA3NTd8NzdhOTAzNzR8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:40 - DownFile.GetFileName is string.empty https://zmk.pw/download/OTc1Mzh8MzQwNzNhMzkzNmE4ZWViM2MyYjBlM2NifDE2NDExMjA3NTl8MjMwYzFiMGJ8cmVtb3Rl/svr/dx1
[ERROR]: 2022-01-02 18:52:41 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTA5OTYwfGQ0ZGQwMzM1YzY3YWRiMTcwZTVmMzEzZnwxNjQxMTIwNzYwfDlkODgxYzZjfHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:43 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTU5NTMwfDdhZDZmMTFhMzk2NGZjZGMxNWVmZTMyYXwxNjQxMTIwNzYyfDg1YmIyYWQ0fHJlbW90ZQ%3D%3D/svr/dx1
[ERROR]: 2022-01-02 18:52:44 - DownFile.GetFileName is string.empty https://zmk.pw/download/MTYyMjM0fDEyZTI0N2FjNDFlNmIyMzNhYmY4NTEzN3wxNjQxMTIwNzYzfGIxYWZhY2JkfHJlbW90ZQ%3D%3D/svr/dx1

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

处理下载文件逻辑，像是在下载时，无法直接下载到抓取的地址。

## 可以提供遇到问题时候，电影、连续剧的信息吗？

最近的版本基本没有看到可以正常下载的字幕。

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
[ChineseSubFinder--2022Len01020000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7799163/ChineseSubFinder--2022Len01020000--.log)

日志见附件。

**Comment by everstarmy** [comment]
试过挂代理也不行. 😳

**Comment by allanpk716** [comment]
这个问题我也发现有人反馈了，相同的下载地址在我这里就能够获取到下载字幕的文件名。见 #136 暂时没有什么想法，问题先挂着吧，看看是否有人能帮忙定位下问题。

**Comment by everstarmy** [comment]
我试过将https://zmk.pw/download/MTYyMjM0fDEyZTI0N2FjNDFlNmIyMzNhYmY4NTEzN3wxNjQxMTIwNzYzfGIxYWZhY2JkfHJlbW90ZQ%3D%3D/svr/dx1  地址直接用浏览器打开也不是直接下载文件，而是到下载字幕的页面。

**Comment by allanpk716** [comment]
反馈问题的当天，你使用本工具已经下载多少字幕了？是否可能是触发了网站的下载量限制导致的？这样的话就挂机，等几天一般能下载的都下载好了的。

**Comment by devome** [comment]
> 反馈问题的当天，你使用本工具已经下载多少字幕了？是否可能是触发了网站的下载量限制导致的？这样的话就挂机，等几天一般能下载的都下载好了的。

这个问题就是同一天下载字幕数量过多导致的。

**Comment by mendosaxie** [comment]
> > 反馈问题的当天，你使用本工具已经下载多少字幕了？是否可能是触发了网站的下载量限制导致的？这样的话就挂机，等几天一般能下载的都下载好了的。
> 
> 这个问题就是同一天下载字幕数量过多导致的。

不一定，因为报错不是出现在靠后的下载序列中，比如Queue6就报错，但后面继续下载了很多其他的字幕， 另外程序不是会从几个接口中下载字幕吗？如果一个受限了为什么不从其他接口下载？

**Comment by allanpk716** [comment]
> > > 反馈问题的当天，你使用本工具已经下载多少字幕了？是否可能是触发了网站的下载量限制导致的？这样的话就挂机，等几天一般能下载的都下载好了的。
> > 
> > 
> > 这个问题就是同一天下载字幕数量过多导致的。
> 
> 不一定，因为报错不是出现在靠后的下载序列中，比如Queue6就报错，但后面继续下载了很多其他的字幕， 另外程序不是会从几个接口中下载字幕吗？如果一个受限了为什么不从其他接口下载？

每个视频都会从多个接口同时下载，新的视频大概率 shooter 和 xunlei 都是没得的，所以基本就是 zimuzu
