### ISSUE TITLE
重复下载已有的字幕

### ISSUE THREAD

**Issue by JassyLyn** [allanpk716/ChineseSubFinder#158]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.0

docker
## 你遇到什么问题了？

我手动放置字幕后，程序会自动下载字幕并覆盖

## 你的问题弄重现嘛？

能够

## 你期望的结果

如果检测到已有字幕应该跳过下载

## 可以提供遇到问题时候，电影、连续剧的信息吗？

<img width="284" alt="Shot 01-08 at 21 23 13@2x" src="https://user-images.githubusercontent.com/49652932/148645786-982bef68-770b-43dd-b988-3eefb3ac35dc.png">

## 出错的日志信息可以复制一些出来吗？

[INFO]: 2022-01-08 14:28:42 - ----------------------------------
[INFO]: 2022-01-08 14:28:45 - Queue 14 DlSub Start /media/tv/Lie to Me (2009)
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me IMDB ID: tt1235099 NeedDownloadSubs: 35
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E15
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E11
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E16
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E3
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E8
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E12
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E4
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E2
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E7
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E3
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E6
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E6
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E8
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E13
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E10
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E22
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E1
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E13
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E1
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E20
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E4
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E5
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E21
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E14
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E17
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E9
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E2
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E5
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E12
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E19
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E10
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E18
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E11
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S2E9
[INFO]: 2022-01-08 14:28:45 - Queue 14 Lie to Me - S1E7
[INFO]: 2022-01-08 14:28:45 - Queue 14 shooter Start...
[INFO]: 2022-01-08 14:28:45 - Queue 14 xunlei Start...

**Comment by allanpk716** [comment]
看主页中的实现文档有解释

**Comment by JassyLyn** [comment]
> 看主页中的实现文档有解释

https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md
是这个文档吗，可是我检查了nfo上映时间和文件修改时间都超过了三个月

**Comment by allanpk716** [comment]
你开启 debugmode 再看，有详细的描述

**Comment by JassyLyn** [comment]
我一直开的debugmode ，而且我发现它自己下载字幕后，每次轮询还是会下载一遍这个字幕，就很奇怪，我也没动文件
<img width="604" alt="Shot 01-09 at 20 51 24@2x" src="https://user-images.githubusercontent.com/49652932/148682933-687f6567-2622-45f2-a9b0-af1d484d04b7.png">
<img width="588" alt="Shot 01-09 at 20 51 36@2x" src="https://user-images.githubusercontent.com/49652932/148682935-2fbe7bec-d90f-4a9e-9ccf-1f85bb0121f0.png">
<img width="602" alt="Shot 01-09 at 20 51 49@2x" src="https://user-images.githubusercontent.com/49652932/148682936-a145e709-fe5f-4bee-9115-5bc400c69b51.png">

**Comment by JassyLyn** [comment]
我把debug的日志复制出来了
[log.txt](https://github.com/allanpk716/ChineseSubFinder/files/7835059/log.txt)

**Comment by allanpk716** [comment]
1. zimuku 下载超限了，其他接口没得数据。
2. 升级到最新

**Comment by JassyLyn** [comment]
更新到最新了，发现还有挺多的剧一直在重复下载字幕
<img width="616" alt="Shot 01-12 at 20 36 38@2x" src="https://user-images.githubusercontent.com/49652932/149141740-9173d782-f3b8-42a9-a939-d631f8d50c95.png">
<img width="617" alt="Shot 01-12 at 20 36 26@2x" src="https://user-images.githubusercontent.com/49652932/149141748-cde81f8b-568a-4ed1-bfd6-c2516f811800.png">

日志
[log.txt](https://github.com/allanpk716/ChineseSubFinder/files/7854570/log.txt)

**Comment by allanpk716** [comment]
如果需要上传日志分析，那么你应该把连续两到三轮扫描的日志一并发上来，单独一轮没有意义。
