### ISSUE TITLE
“多个影片来源文件夹”的支持

### ISSUE THREAD

**Issue by EEEricZer** [allanpk716/ChineseSubFinder#16]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

疑似 版本: v0.11.1，于2021年7月14日拉取的latest docker镜像。

环境: docker 

## 你想要新增或者改进什么功能？

在我的nas设置中，不同的影片分布在不同的硬盘中的不同文件夹中。

因为电影分布在两个硬盘中，容器的挂载方式如下
```
  -v /share/Multimedia:/media1 \
  -v /share/Multimedia2_open:/media2 \
```

而后，因为还分了不同的文件夹储存，config文件中理想的“MovieFolder"项目配置如下
```
MovieFolder: 
  - /media1/Movies_all   #全年龄
  - /media1/Movies_oth  #少儿不宜
  - /media2/Movies_all
  - /media2/Movies_oth
```

然而docker会显示这是错误的输入。
请问是没有添加对这种影片的分布情况的支持，还是说有其他写法？

## 这个功能有什么可以参考的资料吗？

 无

**Comment by allanpk716** [comment]
暂时不支持多个文件夹的输入。这个功能会加入，但是近期应该不会实现，应该会配合 Web 设置界面一同发布。

**Comment by fzfz** [comment]
电影是支持二层文件夹的，所以可以用这样的结构：
/media/mov/movie1
/media/mov/movie2
...
我就是这样挂载的
但是连续剧不行

**Comment by allanpk716** [comment]
> 电影是支持二层文件夹的，所以可以用这样的结构：
> /media/mov/movie1
> /media/mov/movie2
> ...
> 我就是这样挂载的
> 但是连续剧不行

连续剧的扫描比较特殊（为了提高正确率），见 [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

**Comment by allanpk716** [comment]
这个功能会遇到一个问题，如果支持了，就会有一定的机率，你的多媒体文件路径是多个盘上的，比如：
* c:/123
* d:/123

那么就没法使用 [Emby API 的高级功能](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md)了。

为什么也在上述文档中说了，建议看一下。

使用 Emby API 这个功能，后续会有更多针对性的特殊功能出现（比如，自动字幕时间轴的校正，更好的字幕列表刷新，更快的最近更新媒体的获取，等等功能）

**Comment by meiyadudu** [comment]
想问下，多个媒体目录当前是不是还是只有通过开多个docker解决呢？

**Comment by allanpk716** [comment]
> 想问下，多个媒体目录当前是不是还是只有通过开多个docker解决呢？

是的

**Comment by allanpk716** [comment]
现在升级至 v0.20.x 应该可以满足你现在的需求。
