### ISSUE TITLE
请问下不用docker能够部署么

### ISSUE THREAD

**Issue by crotoc** [allanpk716/ChineseSubFinder#160]
终于发现了这个宝藏！字幕问题总是最大的问题！非常感谢你们的这个软件！
我自己买了个种子盒子，上面运行不了docker，请问下是否有办法进行部署呢？谢谢！

**Comment by allanpk716** [comment]
能给出具体的信息吗？比如是什么处理器的，什么系统的。

**Comment by crotoc** [comment]
我是用uname -a：
Linux juno.whatbox.ca 5.10.27-gentoo-whatbox #2 SMP Mon Apr 26 12:23:23 UTC 2021 x86_64 Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz GenuineIntel GNU/Linux

**Comment by crotoc** [comment]
刚刚尝试在上面使用singularity，失败了，丢出来的error是：
ERROR  : Failed to create user namespace: user namespace not supported by your system

**Comment by allanpk716** [comment]
你这个配置就是 x86 的板子，装了 Linux，应该可以用 Docker 的，我觉得这样更容易使用。Linux 单独部署的版本没有折腾过，需要的支持库挺多的，所以才考虑做 docker。

**Comment by crotoc** [comment]
> 你这个配置就是 x86 的板子，装了 Linux，应该可以用 Docker 的，我觉得这样更容易使用。Linux 单独部署的版本没有折腾过，需要的支持库挺多的，所以才考虑做 docker。

这种种子盒没有root短setuid权限，所以docker这类都输不行的。库的话，我可以通过conda来想办法解决。有个说明教教我怎么弄么？麻烦你了

**Comment by crotoc** [comment]
singularity要是可以用就好了。我这条路也应该再尝试尝试。

**Comment by allanpk716** [comment]
Linux 我不是很熟，singularity 这个我没有接触过，不过制作 docker 的时候是有需要的脚本的，其实也是在一个干净的 Linux 上装支持库，具体你看看 https://github.com/allanpk716/ChineseSubFinder/blob/master/Dockerfile

然后 Linux 下，config.yaml 文件的放置路径比较特别，在 /config/config.yaml 这里。其他的没有什么特别的了

**Comment by crotoc** [comment]
好的，我来试一下，有问题再来问你，谢谢了！

**Comment by crotoc** [comment]
我改了一些代码，把目录修改了一下，现在可以运行了。目前出了个问题：
![image](https://user-images.githubusercontent.com/12446554/148716066-4afb6c83-a8fa-4b89-89e1-73f5fcebb442.png)
麻烦你帮忙看下这是什么问题？谢谢~

**Comment by allanpk716** [comment]
证书问题，具体没有解决过，你可以向这个方向看看

**Comment by crotoc** [comment]
我将www.shooter.cn修改成shooter.cn就不报错了，但是也下载不到任何字幕，感觉shooter的api是不是已经坏掉了。我之前在kodi里面看到的的shooter是这个：
https://assrt.net/api/doc

我看了下shooter.go，是不是我按照shooter.go的思路写一个新的fakeshooter.go，就相当于多加了一个字幕网站？麻烦你了！

**Comment by allanpk716** [comment]
1. 我看今天凌晨的日志是正确的，是否是下载数量太大导致的。
2. 我记得 shooter 跟 伪shooter 应该是两个站点

**Comment by crotoc** [comment]
的确是两个不同的站点。
shooter.go的同文件夹里面还有个test文件，我怎么能测试一下shooter是正确工作的呢？我现在只放了一个剧集，所以应该不是数量造成的。

**Comment by allanpk716** [comment]
> 的确是两个不同的站点。
> 
> shooter.go的同文件夹里面还有个test文件，我怎么能测试一下shooter是正确工作的呢？我现在只放了一个剧集，所以应该不是数量造成的。

你需要使用 dev 分支，然后找到我另一个项目，ChineseSubFinder-TestData ，大概这个吧，与本项目放在同级目录下，就行了。手机打字，不确定项目名称对，但是你应该能找出来的。以及，还没空写文档。

**Comment by crotoc** [comment]
好的，我来试试，非常感谢！
