### ISSUE TITLE
自动清理 CSF-SubFixCache 文件夹

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#161]
`CSF-SubFixCache`文件夹存放视频提取出来的音轨和字幕, 可能会随时间的增长变得很大. 如果使用 Emby api, 只扫描最新的N个视频, 就意味着`CSF-SubFixCache`下旧视频的缓存再也不会被使用了.

可以考虑允许设置一个最大大小, 然后按最后被使用的时间依次删除, 可以参考 https://github.com/rclone/rclone/blob/d252816706a3226dbc055616df91f2e1793a0459/vfs/vfscache/item.go#L882

在此之前可以使用以下替代方案手动删除, 最近1天以内都没有被读取的文件:
```
find /patch/to/CSF-SubFixCache/ -type f -atime +1 -delete
find /patch/to/CSF-SubFixCache/ -type d -empty -delete
```

**Comment by allanpk716** [comment]
这个提议很有必要。暂定考虑以时间和空间进行文件的删除。 @wyq977 有兴趣可以实现下这个功能，应该可以认为是独立的模块，提供模块和单元测试就好了。近期应该可以把 Web 对接完毕，配置的部分会一并添加，就不再现有版本加配置了。

**Comment by wyq977** [comment]
ok 我写在internal/pkg/sub_timeline_fix 下面？

cache删除的默认就根据时间吧？ 超过多少时间就都删了

**Comment by allanpk716** [comment]
> ok 我写在internal/pkg/sub_timeline_fix 下面？
> 
> 
> 
> cache删除的默认就根据时间吧？ 超过多少时间就都删了

my_util 下面有个 folder.go ，里面都是文件夹操作的方法，可以写在这里，建议是复合的条件，最大空间或者最大时间范围。

**Comment by wyq977** [comment]
golang 有个问题想问下

文件的accesstime 好像os没有直接的借口

那我这离怎么compile for windows/darwin/linux 我在header那里加build constraint好像也不行


https://github.com/wyq977/ChineseSubFinder/blob/31846580650066d28f9ab6f7ca51d2e115bb92f2/internal/pkg/my_util/folder.go#L359

现在的逻辑是`RemoveNotInUseTmpFolderByName `会清理大于8MiB __或者__ 超过24小时的文件

**Comment by allanpk716** [comment]
build constraint 还没弄过，看了下文档，貌似可能跟 goreleaser 的配置会有冲突（至少要同步设置一致）

https://www.jetbrains.com/help/go/configuring-build-constraints-and-vendoring.html#build-constraints

如果要使用这个特性，我猜你需要把获取文件信息的方法做成独立的 Interface ，然后分别把三个平台的代码用三个 go 文件去实现，每个里面只能由一种构建约束，这样应该就能通过编译了。（没有实践过，但是看文档猜，某个文件中的代码如果不是跨平台的，应该就无法写在一个文件中···）

后续还需要备注如果修改了 goreleaser 的支持列表，这些文件也需要同步修改。

**Comment by wyq977** [comment]
access time 好像就是要麻烦一点 我看看怎么写吧 不过目前darwin的我测试已经可以了

如果modTime golang os直接有API 就简洁很多

文件大小限制你有建议吗 不是很清楚cache那些文件的大小

**Comment by allanpk716** [comment]
想了下，好像仅仅是「最后访问时间」这个判断也足够了。单个文件体积限制不太好做，因为可能会到处音频，可能有1到2百MB。如果是以整个缓存文件夹的总占用大小，来做整体限制，也不错。

**Comment by wloot** [comment]
非常建议只考虑 最后访问时间, 文件夹总大小可以使用Emby API的LimitCount来控制. 否则的话, 文件夹达到限制删除旧的缓存文件后, 下一轮执行获取字幕时也会重新创建.

**Comment by wyq977** [comment]
> 想了下，好像仅仅是「最后访问时间」这个判断也足够了。单个文件体积限制不太好做，因为可能会到处音频，可能有1到2百MB。如果是以整个缓存文件夹的总占用大小，来做整体限制，也不错。

最后访问时间就是LastAccessedTime吧 不是ModTime（这个FileInfo有借口）

文件夹体积 你是说SubFixCache的size不超过一个阈值么 感觉怪怪的：比如超过200MiB 删除LastAccessedTime最老的先被删除掉？

**Comment by wyq977** [comment]
golang 我不是很熟 这样子的好像不能编译 得分成3个吗

```go
	if sysType == "windows" {
	aTime := fi.Sys().(*syscall.Win32FileAttributeData).LastAccessTime
	return aTime, nil
	}
	if sysType == "darwin" {
		aTime := fi.Sys().(*syscall.Stat_t).Atimespec
		return time.Unix(int64(aTime.Sec), int64(aTime.Nsec)), nil
	}
	if sysType == "linux" {
		aTime := fi.Sys().(*syscall.Stat_t).Atim
		return aTime, nil
	}
```

**Comment by allanpk716** [comment]
> 非常建议只考虑 最后访问时间, 文件夹总大小可以使用Emby API的LimitCount来控制. 否则的话, 文件夹达到限制删除旧的缓存文件后, 下一轮执行获取字幕时也会重新创建, 这就没有意义了.

如果是最后访问时间，就需要与字幕扫描的逻辑挂钩，比如，强制的三个月内视频都扫描的逻辑。那么这个最后访问时间也需要至少三个月。

**Comment by allanpk716** [comment]
> golang 我不是很熟 这样子的好像不能编译 得分成3个吗
> 
> ```go
> 	if sysType == "windows" {
> 	    aTime := fi.Sys().(*syscall.Win32FileAttributeData).LastAccessTime
>         	return aTime, nil
> 	}
> 	if sysType == "darwin" {
> 		aTime := fi.Sys().(*syscall.Stat_t).Atimespec
> 		return time.Unix(int64(aTime.Sec), int64(aTime.Nsec)), nil
> 	}
> 	if sysType == "linux" {
> 		aTime := fi.Sys().(*syscall.Stat_t).Atim
> 		return aTime, nil
> 	}
> ```

我推送上去了，跟我之前说的有出入，但是思路类似。就是把 C 那边宏来控制代码的思路延续，只不过分为三个文件去实现，然后都一模一样的 Struct name 就好了。
