### ISSUE TITLE
字幕下载不正确

### ISSUE THREAD

**Issue by zhouad** [allanpk716/ChineseSubFinder#162]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.6

环境: docker 

## 你遇到什么问题了？

发现 凯瑟琳大帝的字幕下载的是 绝命毒师的

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

修正错误

## 可以提供遇到问题时候，电影、连续剧的信息吗？
![image](https://user-images.githubusercontent.com/2617660/149076868-e3d30cb0-3e6f-42c5-a1ae-f8ef51a56f69.png)

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs

**Comment by allanpk716** [comment]
xunlei 错就是xunlei 错，这个是唯一 ID 得到的，无法控制
