### ISSUE TITLE
添加指定剧集字幕扫描功能

### ISSUE THREAD

**Issue by palemoky** [allanpk716/ChineseSubFinder#164]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.6

环境: docker 

## 你想要新增或者改进什么功能？
1. 手动指定扫描某个剧集的字幕。最近囤了 4T 的剧，发现想看的某部剧好几天都没有加载到字幕，所以希望有类似优先级的功能
2. 扫描到手动下载的字幕可以修复时间轴。虽然手动从 zmk 可以下载到正确字幕，但还要手动修改字幕文件名，希望可以添加此功能

## 这个功能有什么可以参考的资料吗？
Emby 中允许手动填写 IMDB ID 以纠正影片信息，所以希望某些影片字幕信息错误时可以手动纠正

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
> Emby 中允许手动填写 IMDB ID 以纠正影片信息，所以希望某些影片字幕信息错误时可以手动纠正

这个功能应该不会去做，超过设计边界了。应该是 TMM 或者 Emby 类似的系统去完成。

> 1. 手动指定扫描某个剧集的字幕。最近囤了 4T 的剧，发现想看的某部剧好几天都没有加载到字幕，所以希望有类似优先级的功能
> 2. 扫描到手动下载的字幕可以修复时间轴。虽然手动从 zmk 可以下载到正确字幕，但还要手动修改字幕文件名，希望可以添加此功能

1. 加入 Web 界面后，应该会给出手动字幕下载的操作逻辑，或者是你提及的优先级问题。但是本项目的目标还是优先挂机完成字幕下载的事情，尽可能无需人为干预。
2. 这个想做，但是以目前得到的测试结果来看，一部视频的时间轴并非是统一一个偏移值就可能搞定的（没想到吧），所以后续搞定web基础功能后，会优化现在时间轴的匹配校正算法（有思路，但是需要实现和验证）

**Comment by allanpk716** [comment]
v0.26 会增加这个功能，正式发布后，使用再反馈吧

**Comment by allanpk716** [comment]
最新版本有 webui 了，不算完美解决，但是也应该够用···后续再优化吧
