### ISSUE TITLE
请问下韩剧目前的时间轴矫正都是错误的是什么原因

### ISSUE THREAD

**Issue by crotoc** [allanpk716/ChineseSubFinder#165]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC

## 你想要新增或者改进什么功能？

希望能支持亚洲的语言，韩剧和日剧之类的

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
时间轴矫正不区分需要，检测的是语音。你需要按文档里提到的方式，收集数据，反馈问题。

**Comment by crotoc** [comment]
好的，谢谢！我整理一下再发上来！

**Comment by crotoc** [comment]
文件比较大，好像不太能传到github上面，所以我都放在google drive的这个文件夹里面了：
https://drive.google.com/drive/folders/19vGLcie8_teWTEgDtJwEeAYtauCbwuba?usp=sharing

如果没有办法下载，请告诉我，我再看看怎么分享给你！非常感谢！
经过矫正的字幕都在一个时间点上面。

**Comment by allanpk716** [comment]
> 文件比较大，好像不太能传到github上面，所以我都放在google drive的这个文件夹里面了：
> 
> https://drive.google.com/drive/folders/19vGLcie8_teWTEgDtJwEeAYtauCbwuba?usp=sharing
> 
> 
> 
> 如果没有办法下载，请告诉我，我再看看怎么分享给你！非常感谢！
> 
> 经过矫正的字幕都在一个时间点上面。

最近比较忙，应该会晚几天才有空看

**Comment by crotoc** [comment]
好的，谢谢！

**Comment by allanpk716** [comment]
> 好的，谢谢！

需要你授权查看共享的文件

**Comment by allanpk716** [comment]
> 不好意思，才看到你的消息！我已经给你授权了，有问题联系我哈。

看年前是否有空吧···刚在对接 Web 部分

**Comment by crotoc** [comment]
好的，新年快乐：）Sent from my Huawei phone-------- Original message --------From: Chin allan ***@***.***>Date: Tue, Jan 25, 2022, 10:40 PMTo: allanpk716/ChineseSubFinder ***@***.***>Cc: Rui chen ***@***.***>, Author ***@***.***>Subject: Re: [allanpk716/ChineseSubFinder] 请问下韩剧目前的时间轴矫正都是错误的是什么原因 (Issue #165)



不好意思，才看到你的消息！我已经给你授权了，有问题联系我哈。



看年前是否有空吧···刚在对接 Web 部分

**Comment by allanpk716** [comment]
共享文件我看了，但是有个严重的问题，因为我不会韩语。而这个视频内置是没有字幕的，那么就会导出音频去做校正。问题来了，我看字幕是看不懂的，音频我也听不懂···所以我也不知道怎么帮你定位问题···

如果有原始的字幕（韩语），然后下载的字幕是韩中字幕，估计我还能用字符去搜索对比。

当然也不是完全没有办法，就是得输出音频和字幕的 VAD 图来对比，但是不利于抠细节。让我再想想怎么处理这种非英语的校正调试问题先。

**Comment by crotoc** [comment]
我来找找看能不能找到

**Comment by crotoc** [comment]
我重新下载了一集韩剧，这个韩剧是mkv文件，里面包含有韩语字幕和中文字幕。我用ffmpeg这两种字幕提取出来，然后用网上的一个程序将两个字幕合并在一起。，现在的问题是我不知道怎么使用csf将mkv做成pcm文件。麻烦你能不能给个命令行的教程，我将mkv里面的语言提取出来，做成pcm文件，这样再分享给你。谢谢了！

**Comment by allanpk716** [comment]
你给我内置的中文字幕（确定这个是时间轴对的就行）就好了，校正可以是音频和字幕作为基准的。

**Comment by crotoc** [comment]
> 你给我内置的中文字幕（确定这个是时间轴对的就行）就好了，校正可以是音频和字幕作为基准的。

这一集是另外一部韩剧的，不是之前那个，那个我找不到内置的字幕。那我把音频解出来和字幕一起放到网盘上。音频就是size会大一些。

**Comment by allanpk716** [comment]
最好是内置的字幕，然后外置字幕能与内置的有关联性（相同语言），不然非英语类的处理起来有点麻烦。

你提到的 ffmpeg 的命令是这个

```
		导出多个字幕
		ffmpeg.exe -i xx.mp4 -vn -an -map 0:7 subs-7.srt -map 0:6 subs-6.srt
		导出音频，从 1m 27s 开始，导出向后的 28 s，转换为 mp3 格式
		ffmpeg.exe -i xx.mp4 -vn -map 0:1 -ss 00:1:27 -f mp3 -t 28 audio.mp3
		导出音频，转换为 mp3 格式
		ffmpeg.exe -i xx.mp4 -vn -map 0:1 -f mp3 audio.mp3
		导出音频，转换为 16000k 16bit 单通道 采样率的 test.pcm
		ffmpeg.exe -i xx.mp4 -vn -map 0:1 -ss 00:1:27 -t 28 -acodec pcm_s16le -f s16le -ac 1 -ar 16000 test.pcm
		截取字幕的时间片段
		ffmpeg.exe -i "subs-3.srt" -ss 00:1:27 -t 28 subs-3-cut-from-org.srt
```

**Comment by crotoc** [comment]
你好，我现在重新上传了这些文件，将里面已经有的文件移除了：
![image](https://user-images.githubusercontent.com/12446554/152811173-0e7da79a-c200-45d5-b1d1-d2eff9b3d926.png)

其中：
subs.korean.srt - 从视频中提取的韩语字幕
subs.chinese.srt - 从视频中提取的中文字幕
Bulgasal.Immortal.Souls.S01E15.1080p.NF.WEB-DL.DDP2.0.x264-REVOLT.korean.chinese.srt - 用网上的工具将上面的韩语和中文字幕进行了合并得到的融合字幕。大部分是完全对应的，很小的几条可能出现一些不匹配。
audio.mp3 - 从视频中提取的音频
audio.pcm - 按照你上面的命令将mp3转换成的pcm

我想找这个剧的外挂字幕但是没有找到。我想你是否能够用上面的几个文件跑一次（CSF）矫正，如果出现问题的话会把我提取的字幕矫正成错误的时间轴，这样就可以进行后续分析了。

如果有问题，我再看看能不能找到更合适的样本进行调试。非常感谢！

**Comment by allanpk716** [comment]
把你给的文件加入测试用例了，从音频校正你给的内置字幕，偏移在 0.01s，没通过的原因是因为期望是 0s（这一点不影响）。

![image](https://user-images.githubusercontent.com/1176000/153315868-246e48ee-e46f-45ae-8ac1-8a8195ce893e.png)


![image](https://user-images.githubusercontent.com/1176000/153315848-a14ce43f-bc25-44d0-9c8c-116ce7c8c75b.png)

**Comment by crotoc** [comment]
谢谢！看起来这一集没啥问题。请问你能不能帮忙把怎么做一集矫正的代码发一下。我看你上面那张图里面写了一个简单的。麻烦教我运行一下，这样我找个合适的例子给你。：）

**Comment by allanpk716** [comment]
> 谢谢！看起来这一集没啥问题。请问你能不能帮忙把怎么做一集矫正的代码发一下。我看你上面那张图里面写了一个简单的。麻烦教我运行一下，这样我找个合适的例子给你。：）

好啊，就在工程中，这两天有空写个使用、调试的文档出来吧

**Comment by allanpk716** [comment]
看看这个文档

https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E6%97%B6%E9%97%B4%E8%BD%B4%E6%A0%A1%E6%AD%A3%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/%E6%97%B6%E9%97%B4%E8%BD%B4%E6%A0%A1%E6%AD%A3%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md

**Comment by allanpk716** [comment]
先关闭。有问题再提。
