### ISSUE TITLE
突然出现no such file or directory

### ISSUE THREAD

**Issue by xcgx** [allanpk716/ChineseSubFinder#166]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 0.19.4

环境: docker/unraid

## 你遇到什么问题了？

未修改任何设置，突然出现no such file or directory

## 你的问题弄重现嘛？

能够重现，重新运行docker后依然出现

## 出错的日志信息可以复制一些出来吗？
[INFO]: 2022-01-21 19:51:27 - SubDownAt: /media/tv/良医 (2017)/Season 2/良医 - S02E17 - 崩溃.zh.ass
[INFO]: 2022-01-21 19:51:27 - shooter Not Find Sub can be download 雪中悍刀行  1 9
[INFO]: 2022-01-21 19:51:27 - shooter Not Find Sub can be download 雪中悍刀行  1 25
[INFO]: 2022-01-21 19:51:28 - shooter Not Find Sub can be download 雪中悍刀行  1 15
[INFO]: 2022-01-21 19:51:28 - shooter Not Find Sub can be download 雪中悍刀行  1 17
[INFO]: 2022-01-21 19:51:28 - Queue 12 shooter End...
[INFO]: 2022-01-21 19:51:28 - 12 DlSub End /media/tv/雪中悍刀行 (2021)
[INFO]: 2022-01-21 19:51:28 - no sub found 雪中悍刀行 (2021)
[INFO]: 2022-01-21 19:51:28 - Download Series Sub End...
[INFO]: 2022-01-21 19:51:28 - Download One End...
[INFO]: 2022-01-21 19:51:28 - Skip TimeLine Fix -- OffsetTime: 0.01 /media/tv/生活大爆炸 (2007)/Season 8/生活大爆炸 - S08E19 - 天行者入侵.zh.srt
[INFO]: 2022-01-21 19:51:28 - ----------------------------------
[INFO]: 2022-01-21 19:51:28 - ----------------------------------
[INFO]: 2022-01-21 19:51:28 - OrgSubName: [xunlei]_0_The Big Bang Theory_S8E19.srt
[INFO]: 2022-01-21 19:51:28 - SubDownAt: /media/tv/生活大爆炸 (2007)/Season 8/生活大爆炸 - S08E19 - 天行者入侵.zh.srt
[INFO]: 2022-01-21 19:51:28 - Skip TimeLine Fix -- OffsetTime: -0.04 /media/tv/良医 (2017)/Season 2/良医 - S02E17 - 崩溃.zh.ass
[INFO]: 2022-01-21 19:51:28 - ----------------------------------
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[shooter]_0_良医 _S4E18.ass open /config/CSF-TmpThings/良医 (2017)/[shooter]_0_良医 _S4E18.ass: no such file or directory
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[xunlei]_0_The Good Doctor_S4E8.ass open /config/CSF-TmpThings/良医 (2017)/[xunlei]_0_The Good Doctor_S4E8.ass: no such file or directory
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[shooter]_0_良医 _S4E8.ass open /config/CSF-TmpThings/良医 (2017)/[shooter]_0_良医 _S4E8.ass: no such file or directory
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[xunlei]_0_The Good Doctor_S2E4.ass open /config/CSF-TmpThings/良医 (2017)/[xunlei]_0_The Good Doctor_S2E4.ass: no such file or directory
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[xunlei]_1_The Good Doctor_S2E0.ass open /config/CSF-TmpThings/良医 (2017)/[xunlei]_1_The Good Doctor_S2E0.ass: no such file or directory
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[xunlei]_2_The Good Doctor_S2E0.ass open /config/CSF-TmpThings/良医 (2017)/[xunlei]_2_The Good Doctor_S2E0.ass: no such file or directory
[ERROR]: 2022-01-21 19:51:28 - DetermineFileTypeFromFile /config/CSF-TmpThings/良医 (2017)/[xunlei]_3_The Good Doctor_S2E4.srt open /config/CSF-TmpThings/良医 (2017)/[xunlei]_3_The Good Doctor_S2E4.srt: no such file or directory

之后无限报错至其它剧集
[ERROR]: 2022-01-21 19:51:30 - DetermineFileTypeFromFile /config/CSF-TmpThings/生活大爆炸 (2007)/[xunlei]_0_the big bang theory_S8E8.srt open /config/CSF-TmpThings/生活大爆炸 (2007)/[xunlei]_0_the big bang theory_S8E8.srt: no such file or directory
[ERROR]: 2022-01-21 19:51:30 - DetermineFileTypeFromFile /config/CSF-TmpThings/生活大爆炸 (2007)/[xunlei]_1_��_S8E8.srt open /config/CSF-TmpThings/生活大爆炸 (2007)/[xunlei]_1_��_S8E8.srt: no such file or directory
[ERROR]: 2022-01-21 19:51:30 - DetermineFileTypeFromFile /config/CSF-TmpThings/生活大爆炸 (2007)/[xunlei]_2_��谢耳朵字幕组生活大爆炸第八季第8集 简体英文 srt_S0E0.srt open /config/CSF-TmpThings/生活大爆炸 (2007)/[xunlei]_2_��谢耳朵字幕组生活大爆炸第八季第8集 简体英文 srt_S0E0.srt: no such file or directory
[ERROR]: 2022-01-21 19:51:30 - DetermineFileTypeFromFile /config/CSF-TmpThings/生活大爆炸 (2007)/[shooter]_0_生活大爆炸 _S8E8.ass open /config/CSF-TmpThings/生活大爆炸 (2007)/[shooter]_0_生活大爆炸 _S8E8.ass: no such file or directory

##  我的映射
/config    /mnt/user/appdata/chinesesubfinder/config
/media    /mnt/user/media/
/app/CSF-SubFixCache    /mnt/user/appdata/chinesesubfinder/CSF-SubFixCache

**Comment by xcgx** [comment]
最后正常的log
[ChineseSubFinder--2022Len01190000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7918148/ChineseSubFinder--2022Len01190000--.log)
首次出现此问题的log
[ChineseSubFinder--2022Len01200000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7918149/ChineseSubFinder--2022Len01200000--.log)

**Comment by congnews** [comment]
**我好像也有同样的问题**
```
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E3.ass open /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E3.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_6_[简体中英ASS]Mayor.of.Kingstown.S01E03.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_6_[简体中英ASS]Mayor.of.Kingstown.S01E03.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_6_[繁体中英ASS]Mayor.of.Kingstown.S01E03.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_6_[繁体中英ASS]Mayor.of.Kingstown.S01E03.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E6.ass open /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E6.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_7_[简体中英ASS]Mayor.of.Kingstown.S01E06.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_7_[简体中英ASS]Mayor.of.Kingstown.S01E06.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_7_[繁体中英ASS]Mayor.of.Kingstown.S01E06.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_7_[繁体中英ASS]Mayor.of.Kingstown.S01E06.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E5.ass open /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E5.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_3_[简体中英ASS]Mayor.of.Kingstown.S01E05.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_3_[简体中英ASS]Mayor.of.Kingstown.S01E05.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_3_[繁体中英ASS]Mayor.of.Kingstown.S01E05.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_3_[繁体中英ASS]Mayor.of.Kingstown.S01E05.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_4_[简体中英ASS]Mayor.of.Kingstown.S01E01.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_4_[简体中英ASS]Mayor.of.Kingstown.S01E01.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_4_[繁体中英ASS]Mayor.of.Kingstown.S01E01.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_4_[繁体中英ASS]Mayor.of.Kingstown.S01E01.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_0_mayor of kingstown_S1E7.srt open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_0_mayor of kingstown_S1E7.srt: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E2.ass open /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E2.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_1_[简体中英ASS]Mayor.of.Kingstown.S01E02.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_1_[简体中英ASS]Mayor.of.Kingstown.S01E02.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_1_[繁体中英ASS]Mayor.of.Kingstown.S01E02.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_1_[繁体中英ASS]Mayor.of.Kingstown.S01E02.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E4.ass open /app/CSF-TmpThings/Mayor of Kingstown/[shooter]_0_Mayor of Kingstown _S1E4.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_2_[简体中英ASS]Mayor.of.Kingstown.S01E04.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_2_[简体中英ASS]Mayor.of.Kingstown.S01E04.WEBDL.FIX字幕侠.ass: no such file or directory
[ERROR]: 2022-01-22 19:52:23 - DetermineFileTypeFromFile /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_2_[繁体中英ASS]Mayor.of.Kingstown.S01E04.WEBDL.FIX字幕侠.ass open /app/CSF-TmpThings/Mayor of Kingstown/[zimuku]_2_[繁体中英ASS]Mayor.of.Kingstown.S01E04.WEBDL.FIX字幕侠.ass: no such file or directory

```

**Comment by allanpk716** [comment]
你们试试，开启 DebugMode: true，然后映射 CSF-DebugThings 出来，再次运行程序，在这里面找到上述提及的连续剧或者电影的目录，可以打包发上来，或者截图也行，最好打包发上来，附上日志。

**Comment by xcgx** [comment]
今天突然正常了
