### ISSUE TITLE
无法正常下载字幕,显示无权限，HotFixProcess() open /media/电影: permission denied

### ISSUE THREAD

**Issue by 907739769** [allanpk716/ChineseSubFinder#167]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
最新版、群晖nas ds220+最新版本
chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC
docker
## 你遇到什么问题了？
无法正常下载字幕,显示无权限
[ERROR]: 2022-01-27 12:48:04 - HotFixProcess() open /media/电影: permission denied

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

正常下载字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

无

## 出错的日志信息可以复制一些出来吗？

[INFO]: 2022-01-27 12:47:45 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:45 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:45 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:45 - HotFix End
[INFO]: 2022-01-27 12:47:46 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:46 - UseProxy = false
[INFO]: 2022-01-27 12:47:46 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:46 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:46 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:46 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:46 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:46 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:46 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:46 - HotFix End
[INFO]: 2022-01-27 12:47:47 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:47 - UseProxy = false
[INFO]: 2022-01-27 12:47:47 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:47 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:47 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:47 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:47 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:47 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:47 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:47 - HotFix End
[INFO]: 2022-01-27 12:47:48 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:48 - UseProxy = false
[INFO]: 2022-01-27 12:47:48 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:48 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:48 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:48 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:48 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:48 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:48 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:48 - HotFix End
[INFO]: 2022-01-27 12:47:49 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:49 - UseProxy = false
[INFO]: 2022-01-27 12:47:49 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:49 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:49 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:49 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:49 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:49 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:49 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:49 - HotFix End
[INFO]: 2022-01-27 12:47:50 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:50 - UseProxy = false
[INFO]: 2022-01-27 12:47:50 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:50 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:50 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:50 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:50 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:50 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:50 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:50 - HotFix End
[INFO]: 2022-01-27 12:47:51 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:51 - UseProxy = false
[INFO]: 2022-01-27 12:47:51 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:51 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:51 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:51 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:51 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:51 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:51 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:51 - HotFix End
[INFO]: 2022-01-27 12:47:52 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:52 - UseProxy = false
[INFO]: 2022-01-27 12:47:52 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:52 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:52 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:52 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:52 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:52 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:52 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:52 - HotFix End
[INFO]: 2022-01-27 12:47:53 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:53 - UseProxy = false
[INFO]: 2022-01-27 12:47:53 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:53 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:53 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:53 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:53 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:53 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:53 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:53 - HotFix End
[INFO]: 2022-01-27 12:47:54 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:54 - UseProxy = false
[INFO]: 2022-01-27 12:47:54 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:54 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:54 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:54 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:54 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:54 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:54 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:54 - HotFix End
[INFO]: 2022-01-27 12:47:55 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:55 - UseProxy = false
[INFO]: 2022-01-27 12:47:55 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:55 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:55 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:55 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:55 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:55 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:55 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:55 - HotFix End
[INFO]: 2022-01-27 12:47:56 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:56 - UseProxy = false
[INFO]: 2022-01-27 12:47:56 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:56 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:56 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:56 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:56 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:56 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:56 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:56 - HotFix End
[INFO]: 2022-01-27 12:47:57 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:57 - UseProxy = false
[INFO]: 2022-01-27 12:47:57 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:57 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:57 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:57 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:57 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:57 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:57 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:57 - HotFix End
[INFO]: 2022-01-27 12:47:58 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:58 - UseProxy = false
[INFO]: 2022-01-27 12:47:58 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:58 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:58 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:58 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:58 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:58 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:58 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:58 - HotFix End
[INFO]: 2022-01-27 12:47:59 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:47:59 - UseProxy = false
[INFO]: 2022-01-27 12:47:59 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:47:59 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:47:59 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:47:59 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:47:59 - hotfix 001 start...
[ERROR]: 2022-01-27 12:47:59 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:47:59 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:47:59 - HotFix End
[INFO]: 2022-01-27 12:48:00 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-01-27 12:48:00 - UseProxy = false
[INFO]: 2022-01-27 12:48:00 - MovieFolder: /media/电影
[INFO]: 2022-01-27 12:48:00 - SeriesFolder: /media/连续剧
[INFO]: 2022-01-27 12:48:00 - HotFix Start, wait ...
[INFO]: 2022-01-27 12:48:00 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-01-27 12:48:00 - hotfix 001 start...
[ERROR]: 2022-01-27 12:48:00 - hotfix 001 failed, break
[ERROR]: 2022-01-27 12:48:00 - HotFixProcess() open /media/电影: permission denied
[INFO]: 2022-01-27 12:48:00 - HotFix End
[ChineseSubFinder--2022Len01270000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7947687/ChineseSubFinder--2022Len01270000--.log)

**Comment by 907739769** [comment]
<img width="909" alt="屏幕截图 2022-01-27 124248" src="https://user-images.githubusercontent.com/27858369/151294547-abda0298-387c-4407-9a9f-3451fffd3c1c.png">
<img width="491" alt="屏幕截图 2022-01-27 125558" src="https://user-images.githubusercontent.com/27858369/151294548-573ccb84-bab5-48b3-8da9-4d8c36e7f9e5.png">
<img width="496" alt="屏幕截图 2022-01-27 125617" src="https://user-images.githubusercontent.com/27858369/151294550-09383bfe-4e7e-4ad3-94e8-4f1b522eff15.png">
<img width="752" alt="屏幕截图 2022-01-27 125730" src="https://user-images.githubusercontent.com/27858369/151294725-4cf6e88e-8e83-42e1-b29c-95e1095d7256.png">
<img width="287" alt="屏幕截图 2022-01-27 125821" src="https://user-images.githubusercontent.com/27858369/151294731-d421614e-acab-4097-af9c-c5002d4cdc85.png">

**Comment by xcgx** [comment]
改文件夹权限777试试？

**Comment by 907739769** [comment]
改成777权限了，不过会不会有风险。。。发现sonarr也要777权限才能增加根目录
