### ISSUE TITLE
增加字幕搜尋網站 - Assrt

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#168]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 0.19.6

环境: docker in Synology NAS

## 你想要新增或者改进什么功能？

增加字幕網站;
https://assrt.net/
不知道現在有沒有使用這個網站當搜尋來源 可是他的字幕數量跟SUBHD和ZIMUKU也不遑多讓，可以考慮看看

**Comment by allanpk716** [comment]
这个需要个人申请 api 接口去使用（对于一般使用者可能略显麻烦），可能后续会考虑支持。

**Comment by xiNeRoar** [comment]
好的謝謝
