### ISSUE TITLE
能否对config影视路径进行详细的说明

### ISSUE THREAD

**Issue by smilejoker365** [allanpk716/ChineseSubFinder#17]
无论我如何填写config文件中的影视目录路径

在docker的日志里一直报错

报错内容就是movie folder not found

我使用的是群晖docker

请问能否详细说明一下关于路径的填写

或者能否和以前SuperNG6大佬写的subfinder一样，只在config文件配置软件，不需要填写路径信息

**Comment by allanpk716** [comment]
这个一定需要一定的 docker 经验的，写固定后期改动就很麻烦。发配置信息上来，容器配置和本程序的配置，以及你的物理媒体路径

**Comment by SuperNG6** [comment]
看这条回复
https://sleele.com/2021/06/25/docker-chinesesubfinder-中文字幕自动下载/comment-page-1/#comment-1601

**Comment by allanpk716** [comment]
> 无论我如何填写config文件中的影视目录路径
> 
> 在docker的日志里一直报错
> 
> 报错内容就是movie folder not found
> 
> 我使用的是群晖docker
> 
> 请问能否详细说明一下关于路径的填写
> 
> 或者能否和以前SuperNG6大佬写的subfinder一样，只在config文件配置软件，不需要填写路径信息

新增了说明文档，看看。 [物理路径与 docker 容器路劲映射指导](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%89%A9%E7%90%86%E8%B7%AF%E5%BE%84%E4%B8%8E%20docker%20%E5%AE%B9%E5%99%A8%E8%B7%AF%E5%8A%B2%E6%98%A0%E5%B0%84%E6%8C%87%E5%AF%BC.md)

**Comment by smilejoker365** [comment]
好的，谢谢两位大佬
