### ISSUE TITLE
IsSubHasChinese.HasChineseLang /media/电影/听风者 (2012).en.srt not chinese sub, is  英

### ISSUE THREAD

**Issue by odincs** [allanpk716/ChineseSubFinder#171]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.6

环境: Docker for Synology

## 你遇到什么问题了？

IsSubHasChinese.HasChineseLang /media/电影/听风者 (2012).en.srt not chinese sub, is  英
全是这样的信息，完全不会下载字幕

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

下载中文字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

所有的电影文件都一样的错误。
IsSubHasChinese.HasChineseLang /media/电影/听风者 (2012).en.srt not chinese sub, is  英

**Comment by allanpk716** [comment]
没得日志没法分析
