### ISSUE TITLE
电影全部跳过 无法抓取字幕

### ISSUE THREAD

**Issue by yefoenix** [allanpk716/ChineseSubFinder#172]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

ChineseSubFinder Version: 0.19.6

环境: docker

## 你遇到什么问题了？

设定目录内的电影被全部跳过，没有抓取

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

没有字幕的电影能够启动抓取不要跳过

## 可以提供遇到问题时候，电影、连续剧的信息吗？
###部分文件截图（按名称排序，可以看到没有字幕文件）
<img width="1541" alt="文件列表" src="https://user-images.githubusercontent.com/8215230/152467039-67689b9e-0cfa-46ec-8311-b7ea9f5ae0ca.png">
###举例：《德州巴黎》Jellyfin截图，显示没有字幕
<img width="1920" alt="德州巴黎截图" src="https://user-images.githubusercontent.com/8215230/152467117-8c1c336d-252e-47f4-ac90-beabb8e59b35.png">
###附件：《德州巴黎》nfo文件
[Paris.Texas (1984) - REMASTERED.1080p.BluRay.x265-RARBG.nfo.txt](https://github.com/allanpk716/ChineseSubFinder/files/7999824/Paris.Texas.1984.-.REMASTERED.1080p.BluRay.x265-RARBG.nfo.txt)

## 配置文件内容如下
UseProxy: true
HttpProxy: http://192.168.1.113:1081
EveryTime: 9h
Threads: 1
RunAtStartup: true
MovieFolder: /media/Movie
SeriesFolder: /media/Show
SubNameFormatter: 1

###配置文件下载：
[config.yaml.txt](https://github.com/allanpk716/ChineseSubFinder/files/7999840/config.yaml.txt)

## 出错的日志信息可以复制一些出来吗？
log文件：
[ChineseSubFinder--2022Len02040000--.log.txt](https://github.com/allanpk716/ChineseSubFinder/files/7999834/ChineseSubFinder--2022Len02040000--.log.txt)

下载最新配置示例文件...,
文件 "/config/config.yaml" 已存在，使用该文件作为配置...,
启动ChineseSubFinder，生成的日志以及setting.db和config.yaml保存在一起...,
[INFO]: 2022-02-04 11:01:26 - ChineseSubFinder Version: 0.19.6,
[INFO]: 2022-02-04 11:01:26 - UseProxy: http://192.168.1.113:1081,
[INFO]: 2022-02-04 11:01:28 - ProxyTest Target Site http://google.com Speed: 1610 Status: 200,
[INFO]: 2022-02-04 11:01:28 - MovieFolder: /media/Movie,
[INFO]: 2022-02-04 11:01:28 - SeriesFolder: /media/Show,
[INFO]: 2022-02-04 11:01:28 - HotFix Start, wait ...,
[INFO]: 2022-02-04 11:01:28 - If you have a lot of videos, it may take a lot of time, just wait...,

,
2022/02/04 11:01:28 /build/internal/dao/init.go:74 SLOW SQL >= 200ms,
[318.359ms] [rows:0] CREATE TABLE `hot_fixes` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`key` text,`done` numeric,PRIMARY KEY (`id`)),

,
2022/02/04 11:01:29 /build/internal/pkg/sqlite/migrator.go:242 SLOW SQL >= 200ms,
[422.070ms] [rows:0] CREATE INDEX `idx_hot_fixes_deleted_at` ON `hot_fixes`(`deleted_at`),

,
2022/02/04 11:01:30 /build/internal/dao/init.go:74 SLOW SQL >= 200ms,
[757.043ms] [rows:0] CREATE TABLE `sub_format_recs` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`format_name` integer,`done` numeric,PRIMARY KEY (`id`)),

,
2022/02/04 11:01:30 /build/internal/pkg/sqlite/migrator.go:242 SLOW SQL >= 200ms,
[611.239ms] [rows:0] CREATE INDEX `idx_sub_format_recs_deleted_at` ON `sub_format_recs`(`deleted_at`),
[INFO]: 2022-02-04 11:01:30 - hotfix 001 start...,
[INFO]: 2022-02-04 11:06:01 - hotfix 001 is done,
[INFO]: 2022-02-04 11:06:01 - HotFix End,
[INFO]: 2022-02-04 11:06:01 - Change Sub Name Format Start...,
[INFO]: 2022-02-04 11:06:01 - If you have a lot of videos, it may take a lot of time, just wait...,

,
2022/02/04 11:06:01 /build/internal/pkg/hot_fix/hot_fix_hub.go:58 SLOW SQL >= 200ms,
[328.660ms] [rows:1] INSERT INTO `hot_fixes` (`created_at`,`updated_at`,`deleted_at`,`key`,`done`) VALUES ("2022-02-04 11:06:00.734","2022-02-04 11:06:00.734",NULL,"001",true),

,
2022/02/04 11:06:01 /build/internal/pkg/sub_formatter/sub_format_changer.go:222 record not found,
[1.191ms] [rows:0] SELECT * FROM `sub_format_recs` WHERE `sub_format_recs`.`deleted_at` IS NULL ORDER BY `sub_format_recs`.`id` LIMIT 1,
[INFO]: 2022-02-04 11:10:27 - Change Sub Name Format End,
[INFO]: 2022-02-04 11:10:27 - First Time Download Start,

,
2022/02/04 11:10:27 /build/internal/pkg/sub_formatter/sub_format_changer.go:234 SLOW SQL >= 200ms,
[291.134ms] [rows:1] INSERT INTO `sub_format_recs` (`created_at`,`updated_at`,`deleted_at`,`format_name`,`done`) VALUES ("2022-02-04 11:10:27.652","2022-02-04 11:10:27.652",NULL,1,true),
[INFO]: 2022-02-04 11:10:27 - Download One Started...,
[INFO]: 2022-02-04 11:10:27 - Download Movie Sub Started...,
[INFO]: 2022-02-04 11:10:41 - Skip Amadeus (1984) - Directors.Cut.BD-1080p.X264.AAC-99Mp4.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:10:53 - Skip Another.Round (2020) - 1080p.BluRay.H264.AAC-VXT.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:11:06 - Skip Asako.I.&.II (2018) - BD1080P.X264.AAC.Japanese.CHS.Mp4Ba.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:11:18 - Skip Bad Luck Banging or Loony Porn (2021).mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:11:31 - Skip Confessions (2010) - JAPANESE.1080p.BluRay.H264.AAC-VXT.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:11:44 - Skip Devils on the Doorstep(2000) - 1080p.DVD-CnSCG.mkv Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:11:57 - Skip Dont.Look.Up (2021) - 1080p.WEBRip.x264-RARBG.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:12:09 - Skip Drive.My.Car (2021) - JAPANESE.1080p.HC.WEBSCR.DD2.0.x264.mkv Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:12:21 - Skip Eros (2004) - 1080p.WEBRip.x264-RARBG.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:12:33 - Skip Fellini.Satyricon (1969) - ITALIAN.1080p.BluRay.H264.AAC-VXT.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:12:45 - Skip From.Up.on.Poppy.Hill (2011) - PROPER.JAPANESE.1080p.BluRay.H264.AAC-VXT.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:12:56 - Skip Funny Face (1957) - 1080p.BluRay.H264.AAC-RARBG.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:13:09 - Skip Hokusai (2020).mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:13:20 - Skip It.Feels.So.Good(2019) - BD1080P.X264.AAC.Japanese.CHS.BdRar.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:13:32 - Skip La.Belle.Epoque (2019) - BluRay.1080p.DTS-HD.MA.5.1.x265.10bit.mkv Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:13:44 - Skip Lolita (1962) - 1080p.BluRay.x265-RARBG.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:13:56 - Skip Paprika (2006) - JAPANESE.1080p.BluRay.x264.DTS-FGT.mkv Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:14:08 - Skip Paris.Texas (1984) - REMASTERED.1080p.BluRay.x265-RARBG.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:14:20 - Skip Rose Island (2020).mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:14:32 - Skip Solaris (1972) - BDRip1080p.mkv Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:14:44 - Skip Taxi.Driver (1976) - 4K.Remastered.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BBQDDQ.mkv Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:14:57 - Skip The Year Earth Changed (2021) - 1080p.BD.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:15:10 - Skip The.Adventures.of.Picasso (1978) - SWEDISH.1080p.WEBRip.x264-VXT.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:15:23 - Skip The.Fabulous.Baker.Boys (1989) - 1080p.BluRay.H264.AAC-RARBG.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:15:35 - Skip The.French.Dispatch (2021) - 1080p.BluRay.DTS.x265-10bit-fh.mkv Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:15:47 - Skip The.Great.Buddha.Plus (2017) - CHINESE.1080p.BluRay.H264.AAC-VXT.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:15:59 - Skip The.Scent.Of.Green.Papaya (1993) - VIETNAMESE.1080p.BluRay.x265-VXT.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:16:12 - Skip The.Unbearable.Lightness.of.Being (1988) - 1080p.WEBRip.x265-RARBG.mp4 Sub Download, because movie has sub and published more than 2 years,
[INFO]: 2022-02-04 11:16:24 - Skip Wheel.of.Fortune.and.Fantasy (2021) - JAPANESE.1080p.BluRay.H264.AAC-VXT.mp4 Sub Download, because movie has sub and downloaded or aired more than 3 months,
[INFO]: 2022-02-04 11:16:25 - Download Movie Sub End...,
[INFO]: 2022-02-04 11:16:25 - Download Series Sub Started...,
[INFO]: 2022-02-04 11:16:25 - Download Series Sub End...,
[INFO]: 2022-02-04 11:16:25 - Download One End...,
[INFO]: 2022-02-04 11:16:25 - First Time Download End,

**Comment by allanpk716** [comment]
去看主页的电影和连续剧目录结构要求，（手机不方便给出）

**Comment by yefoenix** [comment]
> 去看主页的电影和连续剧目录结构要求，（手机不方便给出）
好的，看首页写的是推荐结构，实际是必需的？

**Comment by allanpk716** [comment]
> > 去看主页的电影和连续剧目录结构要求，（手机不方便给出）
> 
> 
> 
> 
> 
> 好的，看首页写的是推荐结构，实际是必需的？

理论上最差可以用影片的名称搜索，但是我没有测试过全部放在一个文件夹的情况。代码逻辑上优先读取 imdb 信息，但是，全部在一起可能会有误识别问题，也就无法触发文件名搜索。

**Comment by yefoenix** [comment]
> > > 去看主页的电影和连续剧目录结构要求，（手机不方便给出）
> > 
> > 
> > 好的，看首页写的是推荐结构，实际是必需的？
> 
> 理论上最差可以用影片的名称搜索，但是我没有测试过全部放在一个文件夹的情况。代码逻辑上优先读取 imdb 信息，但是，全部在一起可能会有误识别问题，也就无法触发文件名搜索。

明白了，谢谢！
