### ISSUE TITLE
v0.20.1 用户密码过长前台不提示无法完成

### ISSUE THREAD

**Issue by NV3S** [allanpk716/ChineseSubFinder#179]
allan新年好，感谢也恭喜新版本的推出。
v0.20.1 刚刚上手部署用了，发现引导界面没办法点“完成”，看了下日志
`[ERROR]: 2022-02-06 15:59:39 - SetupHandler Key: 'ReqSetupInfo.Settings.UserInfo.Password' Error:Field validation for 'Password' failed on the 'max' tag`
用的密码管理器自动生成的密码，这里应该超限了，但前台页面似乎没提示。
（最后改短后就过了）

另：刚发现这里的$VERSION可能没引对
<img width="416" alt="image" src="https://user-images.githubusercontent.com/17755534/152672620-80fe39ee-0a5a-4b29-be67-e59a1ed1f72e.png">

**Comment by john5du** [comment]
出现了同样的问题

**Comment by allanpk716** [comment]
应该是前端和后端的限制没有一致，我们排查下

**Comment by allanpk716** [comment]
version 的问题尝试修复了，一并在 v0.20.2 中修复，正在推送编译。
