### ISSUE TITLE
401后前端不会跳转登录界面

### ISSUE THREAD

**Issue by john5du** [allanpk716/ChineseSubFinder#182]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.3

环境: docker  群晖

## 你遇到什么问题了？

401后前端不会跳转登录界面

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

登录过期后跳转登录界面

![image](https://user-images.githubusercontent.com/45614150/152720937-6737c02c-c484-4f5d-89c2-5bc0156ffa06.png)

**Comment by le0zh0u** [comment]
也出现这个问题，可以先在右上角的退出登录临时解决下
