### ISSUE TITLE
群晖docker安装后，运行时报错。

### ISSUE THREAD

**Issue by Johnhpure** [allanpk716/ChineseSubFinder#185]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker 群晖

## 你遇到什么问题了？
![image](https://user-images.githubusercontent.com/26353341/152960313-401cf015-241e-48ad-8540-7af7a2c30acc.png)
![image](https://user-images.githubusercontent.com/26353341/152960468-c70906d3-930d-495f-b8d5-eec8c139168d.png)

描述一下你遇到的问题
容器启动后报错，web页面无法访问
## 你的问题弄重现嘛？

能够重新

## 你期望的结果

描述以下你期望的结果

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: X:\连续剧\杀死伊芙 (2018)

视频的信息: 杀死伊芙 - S01E01 - 姣好面容.mp4

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs

**Comment by Johnhpure** [comment]
![image](https://user-images.githubusercontent.com/26353341/152960924-f52089b3-5410-4cea-b4f7-0ad50c182215.png)
附上配置文件截图

**Comment by Johnhpure** [comment]
[INFO]: 2022-02-08 17:47:03 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:03 - UseProxy = false
[ERROR]: 2022-02-08 17:47:03 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:04 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:04 - UseProxy = false
[ERROR]: 2022-02-08 17:47:04 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:05 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:05 - UseProxy = false
[ERROR]: 2022-02-08 17:47:05 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:06 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:06 - UseProxy = false
[ERROR]: 2022-02-08 17:47:06 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:07 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:07 - UseProxy = false
[ERROR]: 2022-02-08 17:47:07 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:08 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:08 - UseProxy = false
[ERROR]: 2022-02-08 17:47:08 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:09 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:09 - UseProxy = false
[ERROR]: 2022-02-08 17:47:09 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:10 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:10 - UseProxy = false
[ERROR]: 2022-02-08 17:47:10 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:11 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:11 - UseProxy = false
[ERROR]: 2022-02-08 17:47:11 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:12 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:12 - UseProxy = false
[ERROR]: 2022-02-08 17:47:12 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:13 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:13 - UseProxy = false
[ERROR]: 2022-02-08 17:47:13 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:14 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:14 - UseProxy = false
[ERROR]: 2022-02-08 17:47:14 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:15 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:15 - UseProxy = false
[ERROR]: 2022-02-08 17:47:15 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:16 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:16 - UseProxy = false
[ERROR]: 2022-02-08 17:47:16 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:17 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:17 - UseProxy = false
[ERROR]: 2022-02-08 17:47:17 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:18 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:18 - UseProxy = false
[ERROR]: 2022-02-08 17:47:18 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:19 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:19 - UseProxy = false
[ERROR]: 2022-02-08 17:47:19 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:20 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:20 - UseProxy = false
[ERROR]: 2022-02-08 17:47:20 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:21 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:21 - UseProxy = false
[ERROR]: 2022-02-08 17:47:21 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:22 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:22 - UseProxy = false
[ERROR]: 2022-02-08 17:47:22 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:23 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:23 - UseProxy = false
[ERROR]: 2022-02-08 17:47:23 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:24 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:24 - UseProxy = false
[ERROR]: 2022-02-08 17:47:24 - MovieFolder not found -- /media/电影
[INFO]: 2022-02-08 17:47:25 - ChineseSubFinder Version: v0.19.6
[INFO]: 2022-02-08 17:47:25 - UseProxy = false
[ERROR]: 2022-02-08 17:47:25 - MovieFolder not found -- /media/电影




附上log

**Comment by allanpk716** [comment]
看看最新的v0.20教程

**Comment by Johnhpure** [comment]
> 看看最新的v0.20教程

大佬，我就是按照v0.20教程进行配置的啊

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/153097286-f1bd7e45-d81a-483d-a380-ee302eb8c786.png)

**Comment by john5du** [comment]
我也遇到了这个问题，最近群晖的docker套件使用latest的tag拉不下来本项目最新的镜像。可以把tag改成最新的版本号试试，我成功了。
