### ISSUE TITLE
向导配置和扫描问题

### ISSUE THREAD

**Issue by caolicong** [allanpk716/ChineseSubFinder#187]
chinesesubfinder 版本: v0.20.3

环境: 群晖DOCKER

## 你遇到什么问题了？

1、在向导部分，配置选择JELLYFIN的时候，点击完成无响应，只好选：无
不太清楚这点配置对使用是否存在影响。重新配置能够重现；

2、配置完成后，无法正常扫描；
日志只有：[GIN] 2022/02/09 - 11:07:05 | 200 |      34.976µs |      172.17.0.1 | GET      "/v1/jobs/status"
任务状态是：运行中
 刚开始怀疑目录错误，经过反复检查确认配置正常。并且通过了向导的检查（目录配置错误，好像不能通过向导）

**Comment by caolicong** [comment]
扫描问题已解决：原因是网络问题，调整网络后可正常扫描。

**Comment by sanxk** [comment]
@caolicong  我这也是同样的现象，请问是什么网络问题？要怎么调整
