### ISSUE TITLE
能否关掉[GIN]的输出

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#188]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.3

环境: docker

## 你想要新增或者改进什么功能？

是否可以关掉[GIN]的输出

## 这个功能有什么可以参考的资料吗？

[GIN] 2022/02/09 - 11:23:59 | 200 |    1.471488ms |      172.17.0.1 | GET      "/"
[GIN] 2022/02/09 - 11:23:59 | 200 |    7.437237ms |      172.17.0.1 | GET      "/js/app.9347084d.js"
[GIN] 2022/02/09 - 11:23:59 | 200 |    6.456019ms |      172.17.0.1 | GET      "/css/app.31d6cfe0.css"
[GIN] 2022/02/09 - 11:23:59 | 200 |    7.458617ms |      172.17.0.1 | GET      "/css/vendor.e2b73879.css"
[GIN] 2022/02/09 - 11:23:59 | 200 |    9.902662ms |      172.17.0.1 | GET      "/js/vendor.16cd73ee.js"
[GIN] 2022/02/09 - 11:23:59 | 200 |       57.34µs |      172.17.0.1 | GET      "/system-status"
[GIN] 2022/02/09 - 11:23:59 | 401 |       45.93µs |      172.17.0.1 | GET      "/v1/jobs/status"
[GIN] 2022/02/09 - 11:23:59 | 200 |       96.49µs |      172.17.0.1 | GET      "/js/500.fee67d6f.js"
[GIN] 2022/02/09 - 11:23:59 | 200 |      152.32µs |      172.17.0.1 | GET      "/js/663.4878be69.js"
[GIN] 2022/02/09 - 11:23:59 | 401 |       35.58µs |      172.17.0.1 | GET      "/v1/settings"
[GIN] 2022/02/09 - 11:23:59 | 200 |       227.3µs |      172.17.0.1 | GET      "/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.c934fe77.woff2"
[GIN] 2022/02/09 - 11:23:59 | 200 |      122.93µs |      172.17.0.1 | GET      "/fonts/KFOmCnqEu92Fr1Mu4mxM.9b78ea3b.woff"
[GIN] 2022/02/09 - 11:23:59 | 200 |      119.84µs |      172.17.0.1 | GET      "/fonts/KFOlCnqEu92Fr1MmEU9fBBc-.ddd11dab.woff"
[GIN] 2022/02/09 - 11:24:03 | 401 |          27µs |      172.17.0.1 | POST     "/logout"
[GIN] 2022/02/09 - 11:24:03 | 200 |       33.56µs |      172.17.0.1 | GET      "/css/372.22acee98.css"
[GIN] 2022/02/09 - 11:24:03 | 200 |       77.54µs |      172.17.0.1 | GET      "/js/372.bd760330.js"
[GIN] 2022/02/09 - 11:24:06 | 200 |     396.399µs |      172.17.0.1 | POST     "/login"
[GIN] 2022/02/09 - 11:24:06 | 200 |       78.59µs |      172.17.0.1 | GET      "/v1/settings"
[GIN] 2022/02/09 - 11:24:07 | 200 |       49.21µs |      172.17.0.1 | GET      "/v1/jobs/status"
[GIN] 2022/02/09 - 11:24:11 | 200 |      121.66µs |      172.17.0.1 | GET      "/js/252.3693b1e5.js"
[GIN] 2022/02/09 - 11:24:11 | 200 |       22.53µs |      172.17.0.1 | GET      "/v1/jobs/status"
[GIN] 2022/02/09 - 11:24:12 | 200 |      117.28µs |      172.17.0.1 | GET      "/v1/settings"
[GIN] 2022/02/09 - 11:24:15 | 200 |       24.17µs |      172.17.0.1 | GET      "/v1/jobs/status"

**Comment by allanpk716** [comment]
有考虑，但是怎么分离两个日志还需要想一下，试一下。

**Comment by jasonhorga** [comment]
终于可以关掉了
![image](https://user-images.githubusercontent.com/60920512/153742066-bcd93d72-5185-405e-b017-f06f222fba62.png)
