### ISSUE TITLE
适配播放软件自动选择字幕的优先级

### ISSUE THREAD

**Issue by mhqschen** [allanpk716/ChineseSubFinder#19]
提供设置选项，允许用户自定义通过几个条件的排序，确定最优选字幕（比如人人影视字幕组的双语字幕）。
在plex, emby, jellyfin或其他播放软件上实现自动选择最优选字幕。

想到的问题:
1.不同软件挑选默认字幕的逻辑可能需要单独适配。
2.适配的方法。怎样修改文件名。

**Comment by allanpk716** [comment]
> 提供设置选项，允许用户自定义通过几个条件的排序，确定最优选字幕（比如人人影视字幕组的双语字幕）。
> 在plex, emby, jellyfin或其他播放软件上实现自动选择最优选字幕。
> 
> 想到的问题:
> 1.不同软件挑选默认字幕的逻辑可能需要单独适配。
> 2.适配的方法。怎样修改文件名。

1. 业余时间不多，就不搭建那么多个测试环境了。
2. 需要 plex, jellyfin 用户反馈。先整 emby 的，知道其他几个规则了，重构一下问题不大。
3. 设置现在感觉越来越多，一般人 hold 不住。如果要兼容多个系统的字幕先择优先级，估计会考虑在 Web 设置功能出来后再加吧。
4. Web 页面相关的开发大概 7 年前弄过，现在忘完了，看同事在玩 Quasar V2，得学一下先···估计时间很长。[doge]

**Comment by mhqschen** [comment]
嗯，不是优先级很高的事情。这个适配主要是命名规则的适配。这个可以通过用户反馈，甚至用户自定义的形式完成。

**Comment by allanpk716** [comment]
> 嗯，不是优先级很高的事情。这个适配主要是命名规则的适配。这个可以通过用户反馈，甚至用户自定义的形式完成。

嗯，这个可以观察下大家的使用反馈，再确定功能如何实现。

**Comment by allanpk716** [comment]
最新 v0.14.x 应该可以满足此需求，见[文档](https://github.com/allanpk716/ChineseSubFinder/issues/49)
