### ISSUE TITLE
docker的内存占用非常大，而且停止后也不会释放

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#190]

**Comment by allanpk716** [comment]
有图吗？

**Comment by chuckGG** [comment]
![捕获](https://user-images.githubusercontent.com/9331357/153148374-6da64887-076f-4ca0-8dd7-3fa2eb4ab049.PNG)
基本在5G左右

**Comment by chuckGG** [comment]
> 有图吗？

![Uploading 捕获.PNG…]()

**Comment by allanpk716** [comment]
截图这个

![image](https://user-images.githubusercontent.com/1176000/153170512-42c41b68-7646-4077-9f8f-18446a75c5dd.png)


以及见下图

![image](https://user-images.githubusercontent.com/1176000/153170826-c72846ab-44b8-4b1f-b573-7c1978444e40.png)


![image](https://user-images.githubusercontent.com/1176000/153170601-4ad44f09-efbd-4cb3-b813-acf92e25e0fa.png)

注意看差别，缓存和真实使用的内存是不一样的。

**Comment by jasonhorga** [comment]
图在这里

[cid:709E075B-E7C0-4F06-94FD-F45ACF50E489-L0-001]


何佳

在 2022年2月9日，17:49，Chin allan ***@***.***> 写道：

﻿

截图这个

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1176000%2F153170512-42c41b68-7646-4077-9f8f-18446a75c5dd.png&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8JFkuo8fYxC3378RogBfBQ%2FkEqoYzIxBZgB3rUe73K4%3D&reserved=0>

以及见下图

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1176000%2F153170826-c72846ab-44b8-4b1f-b573-7c1978444e40.png&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fBVRjpY5ykmKhhHLblGK2cWG2Lx3aBzDoIvsPdMBGUM%3D&reserved=0>

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1176000%2F153170601-4ad44f09-efbd-4cb3-b813-acf92e25e0fa.png&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wFbqbA2bXYLkcKkEwZWXeoifKKp1aAjpOdpmh%2Bf0Cyk%3D&reserved=0>

注意看差别，缓存和真实使用的内存是不一样的。

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fallanpk716%2FChineseSubFinder%2Fissues%2F190%23issuecomment-1033568445&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uW1LZt%2BK9OatrOpf0bWlJye3n1UoG7FnmPbFIFgmAYo%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOQZFQCOM5DL62YCS4SMJ4TU2I2BFANCNFSM5N4MHPAA&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6sDPGT%2BcjPhtrsSGSyuq1nJTfNJ98PZJY4XBZBUe2xA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e%2FZw4FGqbx7gocXxUMcB4i2RhLDo8QkGavzaPgNkH68%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8d8d9c83c1cb41e68f9f08d9ebb16aea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637799969515587124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v1QuTw%2FKmYNf4Hkb87QXMEK%2F%2FqUPYx4pmAPd8PWfXHI%3D&reserved=0>.

**Comment by allanpk716** [comment]
你把格式整理好吧，看起来累

**Comment by jasonhorga** [comment]
![Uploading 7E197121-15F4-42F2-B634-BFAEC0FED69F.png…]()

**Comment by jasonhorga** [comment]
> 你把格式整理好吧，看起来累

对不起，直接回复的邮件，格式乱了，我重新在网页上上传了截图

**Comment by allanpk716** [comment]
没看到上传的截图。

最近把 subhd 又对接回来了，如果还是导致内存持续变大。虽然在我这里都是正常的，如果反馈的人多大话，我一时也找不到怎么继续优化的想法，后续应该会屏蔽这个网站的字幕功能。下图是我本地的待机效果。

![image](https://user-images.githubusercontent.com/1176000/153314272-c26659e3-8d58-42ad-bf42-f22a5d37633e.png)

**Comment by jasonhorga** [comment]
![8E881F18-8CCD-42E3-A611-453720593EAC](https://user-images.githubusercontent.com/60920512/153321742-f4672dab-33bd-4c81-ad99-bf83e8540301.png)
![978A3626-758D-4027-8B7B-94341420F721](https://user-images.githubusercontent.com/60920512/153321751-9f680026-1ff4-4e75-9dd3-aa2bc624d931.png)

**Comment by allanpk716** [comment]
> ![8E881F18-8CCD-42E3-A611-453720593EAC](https://user-images.githubusercontent.com/60920512/153321742-f4672dab-33bd-4c81-ad99-bf83e8540301.png)
> 
> ![978A3626-758D-4027-8B7B-94341420F721](https://user-images.githubusercontent.com/60920512/153321751-9f680026-1ff4-4e75-9dd3-aa2bc624d931.png)
> 
> 

进程截图看看

**Comment by jasonhorga** [comment]
我刚停了容器，但是进程页面每个进程显示的内存占用都不大

**Comment by allanpk716** [comment]
> 我刚停了容器，但是进程页面每个进程显示的内存占用都不大

还是需要截图有什么进程才行，不然不清楚是什么占用

**Comment by allanpk716** [comment]
> > 没看到上传的截图。
> > 最近把 subhd 又对接回来了，如果还是导致内存持续变大。虽然在我这里都是正常的，如果反馈的人多大话，我一时也找不到怎么继续优化的想法，后续应该会屏蔽这个网站的字幕功能。下图是我本地的待机效果。
> > ![image](https://user-images.githubusercontent.com/1176000/153314272-c26659e3-8d58-42ad-bf42-f22a5d37633e.png)
> 
> 如果真不用subhd的话，去掉虚拟X视窗环境和Chromium可以大大减小镜像体积。另外，想问下，go-rod这个项目是一定要有X视窗环境才可以使用的么？可以无头headless运行么？

因为要过验证码，需要视图。

**Comment by devome** [comment]
> > > 没看到上传的截图。
> > > 最近把 subhd 又对接回来了，如果还是导致内存持续变大。虽然在我这里都是正常的，如果反馈的人多大话，我一时也找不到怎么继续优化的想法，后续应该会屏蔽这个网站的字幕功能。下图是我本地的待机效果。
> > > ![image](https://user-images.githubusercontent.com/1176000/153314272-c26659e3-8d58-42ad-bf42-f22a5d37633e.png)
> > 
> > 
> > 如果真不用subhd的话，去掉虚拟X视窗环境和Chromium可以大大减小镜像体积。另外，想问下，go-rod这个项目是一定要有X视窗环境才可以使用的么？可以无头headless运行么？
> 
> 因为要过验证码，需要视图。

好吧，subhd这个滑动验证码确实麻烦。

**Comment by allanpk716** [comment]
目前看群晖这个统计的内存不是真实的占用，应该无需关心。而且限制了并发数，应该不会明显占用多才对。

**Comment by devome** [comment]
@jasonhorga @allanpk716 在主机上用`docker stats`命令看看，这个显示的`MEM USAGE`比较可靠。

**Comment by jasonhorga** [comment]
> @jasonhorga @allanpk716 在主机上用`docker stats`命令看看，这个显示的`MEM USAGE`比较可靠。

看起来没问题，多谢各位
![image](https://user-images.githubusercontent.com/60920512/153558795-0fe1ca0d-9176-42dc-b73f-a986e80b96c3.png)

**Comment by allanpk716** [comment]
> @jasonhorga @allanpk716 在主机上用`docker stats`命令看看，这个显示的`MEM USAGE`比较可靠。

好的，对于 linux 和 docker 不太熟悉，多谢给出方向。

**Comment by jasonhorga** [comment]
可以关闭了
