### ISSUE TITLE
电视剧只会下载第一集的字幕，已经通过TMM削刮

### ISSUE THREAD

**Issue by chuckGG** [allanpk716/ChineseSubFinder#193]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker 

## 你遇到什么问题了？

电视剧只会下载第一集的字幕文件
![捕获1](https://user-images.githubusercontent.com/9331357/153160557-1fabceba-a4db-4bfb-b109-723d2f1222f0.PNG)
![捕获2](https://user-images.githubusercontent.com/9331357/153160588-6193c999-9373-4f97-b731-5cb4da01ae11.PNG)

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

完整下载整季的字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: video\连续剧\僵尸校园

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs

**Comment by allanpk716** [comment]
没有足够信息无法定位。
