### ISSUE TITLE
用了最新版的docker image，latest version，还是无法获取版本号

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#196]
![image](https://user-images.githubusercontent.com/60920512/153328803-54827ddb-6097-4a22-8cba-903631e66b4c.png)

**Comment by allanpk716** [comment]
我这边测试 docker 相关东西挺痛苦的，我等下找上次帮提交修复这个问题得朋友再帮看看吧

**Comment by allanpk716** [comment]
以及你需要说一下你现在拉取的是那个版本的

**Comment by jasonhorga** [comment]
﻿就是latest


何佳

在 2022年2月10日，11:20，Chin allan ***@***.***> 写道：

﻿

以及你需要说一下你现在拉取的是那个版本的

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fallanpk716%2FChineseSubFinder%2Fissues%2F196%23issuecomment-1034451198&data=04%7C01%7C%7C47b56fba346343f31d4d08d9ec44459c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800600251198417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=21a%2BlaCPubGm6fDdewE%2Bw%2FUbQbAjwywlfgQmA6Dzx8w%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOQZFQE2R5HH6JRFQ7BJI3TU2MVHJANCNFSM5N7MMN4A&data=04%7C01%7C%7C47b56fba346343f31d4d08d9ec44459c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800600251198417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GEY%2BAhV2Jes8HAtBI%2FvvFGImTz8Aitt%2F44OxZXBAhaA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C47b56fba346343f31d4d08d9ec44459c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800600251198417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IAKsWDDade2FsxTmQca41ReI030MJ83Q7egF6j8rAsI%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C47b56fba346343f31d4d08d9ec44459c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800600251198417%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jznzpjcvrxEFhOQTx1MrMKqooQRsLIJKaQPeautT7%2B0%3D&reserved=0>.

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/153333203-c4bd5a78-a839-40ed-8b08-37b36c4542c6.png)

#195 跟这个问题一致

**Comment by devome** [comment]
> ![image](https://user-images.githubusercontent.com/60920512/153328803-54827ddb-6097-4a22-8cba-903631e66b4c.png)

页面刷新试试

**Comment by devome** [comment]
容器启动日志中能显示版本，那么页面就没问题。刷新试试。

**Comment by devome** [comment]
顺便看看容器的启动日志。

**Comment by jasonhorga** [comment]
应该就是latest没有对应最新的20.5，和#195问题一样


何佳

在 2022年2月10日，11:55，devome ***@***.***> 写道：

﻿

顺便看看容器的启动日志。

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fallanpk716%2FChineseSubFinder%2Fissues%2F196%23issuecomment-1034467147&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p%2BsQU%2FlEVbvC45UsSZ9z5SdAwT%2FuRiBANHHR9lTGVlo%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOQZFQHKV43IKLLKLYEQ65LU2MZKTANCNFSM5N7MMN4A&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r4xVcCF%2BDXFb7hR9zlXMC35WmS%2FmXO6DhMv8ypT2Rng%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qDOMvOTSACC3S9%2BNhN%2FYJEQHqbma5Gn4Kw2HkJZcUvM%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5VKvk1JaUfgGy5BYIwS6UzEabZ%2BcFHmkkt0YhKfMxsw%3D&reserved=0>.

**Comment by devome** [comment]
> 应该就是latest没有对应最新的20.5，和#195问题一样
> 
> 
> 何佳
> 
> 在 2022年2月10日，11:55，devome ***@***.***> 写道：
> 
> ﻿
> 
> 顺便看看容器的启动日志。
> 
> —
> Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fallanpk716%2FChineseSubFinder%2Fissues%2F196%23issuecomment-1034467147&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p%2BsQU%2FlEVbvC45UsSZ9z5SdAwT%2FuRiBANHHR9lTGVlo%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOQZFQHKV43IKLLKLYEQ65LU2MZKTANCNFSM5N7MMN4A&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r4xVcCF%2BDXFb7hR9zlXMC35WmS%2FmXO6DhMv8ypT2Rng%3D&reserved=0>.
> Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qDOMvOTSACC3S9%2BNhN%2FYJEQHqbma5Gn4Kw2HkJZcUvM%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca907e6a8ef994b9b7a5d08d9ec4929fc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800621264171469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5VKvk1JaUfgGy5BYIwS6UzEabZ%2BcFHmkkt0YhKfMxsw%3D&reserved=0>.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
> 

那你先更新啊。

**Comment by devome** [comment]
![IMG_20220210_120754.jpg](https://user-images.githubusercontent.com/93664269/153335311-6451d6c8-5ff8-406c-89cb-cfbc96eb5b09.jpg)

**Comment by lucienfc** [comment]
我删除了之前的镜像重新下就解决了
