### ISSUE TITLE
对于BDMV目录的支持问题

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#197]
首先都是BDMV原盘的问题，不知道这种格式的影片是否支持外挂字幕，以及chinesesubfinder是否支持相应的字幕下载

如果是支持的，那么问题如下

（1）目前有些是存在根目录下，并没有存到相应的目录下
![image](https://user-images.githubusercontent.com/60920512/153551437-bd10d791-d4b9-4e41-a408-7f460044b3ab.png)
（2）还有很多影片找不到movie.nfo等，所以并没有进行search和下载的任务，但这些nfo实际上都是存在的
![image](https://user-images.githubusercontent.com/60920512/153551701-a321c4b5-5227-4174-bc90-51b0edde4847.png)
例如超能查派
![image](https://user-images.githubusercontent.com/60920512/153551762-bf430767-ed2f-4dbc-8051-1eda29cf52c2.png)

**Comment by allanpk716** [comment]
目前没有支持 BDMV 目录（没有下载过，没有测试样本），所以才会导致你现在遇到的问题。

**Comment by jasonhorga** [comment]
理解，谢谢

**Comment by allanpk716** [comment]
> 理解，谢谢

如果可能，需要给一个视频，我去下载了，然后做支持就好了。

**Comment by jasonhorga** [comment]
> > 理解，谢谢
> 
> 如果可能，需要给一个视频，我去下载了，然后做支持就好了。

我是在pt上下载的，虽然现在很多都是remux或者iso但也有很多原盘bdmv格式的，看怎么给你？其实做个目录结构也可以吧

例如，https://www.4kpro.cn/thread-86938-1-1.html

其实就可以根据目录名搜索，把字幕按照目录名+ass的方式存下来，放在一级目录中和BDMV文件夹同一级，类似
![image](https://user-images.githubusercontent.com/60920512/153558468-cac2b6d7-2bcd-4fcb-a4ce-1a4e81007ce9.png)

**Comment by allanpk716** [comment]
1. 单纯目录结构也不是不行，就是可能无法触发 xunlei、shooter 的下载接口，这个是需要具体的视频文件的
2. 这类视频到底在本地存储结构和内容是我需要弄清楚的，否则可能会有兼容性问题
3. 字幕应该放在哪才能够被类似 Emby 自动识别
4. 如上述，其实就是需要能够下载多种这类型的高清或者原盘视频，然后通过削刮后，进入 Emby，再去适配

你能够列举出有那些类型是这种视频吗，关键词，高清？原盘？蓝光？我可以自己去找资源下载一下。

**Comment by jasonhorga** [comment]
> 1. 单纯目录结构也不是不行，就是可能无法触发 xunlei、shooter 的下载接口，这个是需要具体的视频文件的
这两个网站其实可以从tmdv id来获取
> 2. 这类视频到底在本地存储结构和内容是我需要弄清楚的，否则可能会有兼容性问题
这个其实是有标准文档的，是蓝光的存储文件夹格式
> 3. 字幕应该放在哪才能够被类似 Emby 自动识别
这个可以测试包括命名，我理解放在BDMV的同级目录并用title的方式命名（和上层目录同名）
> 4. 如上述，其实就是需要能够下载多种这类型的高清或者原盘视频，然后通过削刮后，进入 Emby，再去适配
> 
> 你能够列举出有那些类型是这种视频吗，关键词，高清？原盘？蓝光？我可以自己去找资源下载一下。
基本上UHD Blu-ray的，例如Infinite 2021 2160p UHD Blu-ray HEVC DoVi TrueHD Atmos 7.1，https://kp.m-team.cc/details.php?id=545065&hit=1，但也有可能是iso，如果是iso的话可以直接解压出来就是这个所谓的BDMV格式

**Comment by jasonhorga** [comment]
重复问题，关闭这个
