### ISSUE TITLE
最新版本仍无法支持镶套文件夹

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#198]
例如,   连续剧目录设置为`/gd/欧美剧`, 然后像`/gd/欧美剧/2022/Reacher (2022) [tvdbid=366924]`这样, 在2022子目录下的剧集还是无法支持: 目录会被解析成`/gd/欧美剧/Reacher (2022) [tvdbid=366924]`, 其中2022子文件夹被丢弃.

可能的解决方案: https://github.com/wloot/ChineseSubFinder/commit/5f0fc8649d41bb03771cc81efc98bea58aaa8ae7

**Comment by allanpk716** [comment]
目前搜索连续剧最准确的方式就是只搜索当前目录，所以你说这种嵌套的，在教程中也提了，是不保证能支持的。

也不是不行，就是得以每个连续剧的 nfo 或者 xml 为锚点再推断位置，但是这样搜索逻辑得改。

**Comment by allanpk716** [comment]
而且你现在提到的改动，我不理解哪里有问题，已经给出 Emby 映射的设置了，这个跟搜索连续剧目录没有关系，如果有问题也是`em.findMappingPath`的问题。

现在需要解决的嵌套问题是不适用 Emby 的情况。

**Comment by allanpk716** [comment]
你把你的设置界面截图看看，常规的和 Emby 的，看看映射对不对。这里就是个排序替换的逻辑，没有什么特别的，不应该又问题。

**Comment by allanpk716** [comment]
你说的嵌套问题是存在的，但是Emby的话就不应该，因为不是程序去搜索的，是从 Emby 拿到的路径仅仅是替换前缀而已。

非 Emby的是有你描述的问题的，之前写的比较理想情况，需要再多考虑一些情况。

## 连续剧搜索逻辑

![image](https://user-images.githubusercontent.com/1176000/153695552-a5eb4fff-f0c3-471b-be2d-c89b5b6f5eba.png)

**Comment by wloot** [comment]
> 你把你的设置界面截图看看，常规的和 Emby 的，看看映射对不对。这里就是个排序替换的逻辑，没有什么特别的，不应该又问题。

问题大概是这样的，`em.findMappingPath`返回的`physicalRootPath`是不包含子目录的，预先设置的映射路径`nowPhPath`。

**Comment by allanpk716** [comment]
> > 你把你的设置界面截图看看，常规的和 Emby 的，看看映射对不对。这里就是个排序替换的逻辑，没有什么特别的，不应该又问题。
> 
> 问题大概是这样的，`em.findMappingPath`返回的`physicalRootPath`是不包含子目录的，预先设置的映射路径`nowPhPath`。

我觉得比较奇怪，这里应该是从 emby 拿到的全路径，你能断点看一眼这里的值吗？

## 代码截图

![image](https://user-images.githubusercontent.com/1176000/153695867-1f2e0851-bc99-4d39-97cd-8e59ce8b620c.png)

**Comment by wloot** [comment]
> > > 你把你的设置界面截图看看，常规的和 Emby 的，看看映射对不对。这里就是个排序替换的逻辑，没有什么特别的，不应该又问题。
> > 
> > 
> > 问题大概是这样的，`em.findMappingPath`返回的`physicalRootPath`是不包含子目录的，预先设置的映射路径`nowPhPath`。
> 
> 我觉得比较奇怪，这里应该是从 emby 拿到的全路径，你能断点看一眼这里的值吗？
> 
> ## 代码截图
> ![image](https://user-images.githubusercontent.com/1176000/153695867-1f2e0851-bc99-4d39-97cd-8e59ce8b620c.png)

实际上，`PhysicalRootPath`就没使用从emby获取的路径: https://github.com/wloot/ChineseSubFinder/blob/8bf6b313e4af9639b22bf961a6bae44124ea0958/internal/logic/emby_helper/embyhelper.go#L163-L187

**Comment by allanpk716** [comment]
你看上图，传入的是不是 Emby 得到的路径？然后传入进入就是这个 videoEmbyFullPath

**Comment by wloot** [comment]
videoEmbyFullPath没有问题，可是后续逻辑直接把PhysicalRootPath和VideoFolderName拼接得到文件夹路径，子目录信息就丢失了。

**Comment by wloot** [comment]
传入:
https://github.com/allanpk716/ChineseSubFinder/blob/e3f62bbef44bdceead2a27a7a28a07f641d9e2e4/internal/pkg/downloader/downloader.go#L344

拼接:
https://github.com/allanpk716/ChineseSubFinder/blob/e3f62bbef44bdceead2a27a7a28a07f641d9e2e4/internal/pkg/downloader/downloader.go#L489

> VideoFileFullPath没有问题，可是后续逻辑直接把PhysicalRootPath和VideoFolderName拼接得到文件夹路径，子目录信息就丢失了。



> VideoFileFullPath没有问题，可是后续逻辑直接把PhysicalRootPath和VideoFolderName拼接得到文件夹路径，子目录信息就丢失了。

**Comment by allanpk716** [comment]
大概懂你说的意思了，这里有问题。其实也是前面没有拿到子目录的问题导致的。我想想看怎么把连续剧的目录正确的转换出来。

## PhysicalRootPath  using 的地方
![image](https://user-images.githubusercontent.com/1176000/153696250-4698b8bb-f0d3-4b03-8519-0af550f2d70c.png)

![image](https://user-images.githubusercontent.com/1176000/153696325-b36cd972-743e-48b5-b760-9c81a9da8102.png)
