### ISSUE TITLE
使用最新版本，plex无法加载外挂字幕

### ISSUE THREAD

**Issue by zjc1994** [allanpk716/ChineseSubFinder#199]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker

## 你遇到什么问题了？

plex无法加载外挂字幕 字幕格式如 1:七号房的礼物 (2013) 1080p AC3.zh.ass  2:龙猫 (1988) 1080p DTS.zh.srt

**Comment by allanpk716** [comment]
具体，截图

**Comment by zjc1994** [comment]
<img width="1243" alt="未命名" src="https://user-images.githubusercontent.com/24852256/153694992-04a6c495-6b3e-46c9-95ec-6fc7b2e428de.png">

**Comment by allanpk716** [comment]
大概率是 plex 没有刷新它自己的资源库

**Comment by zjc1994** [comment]
我已经尝试重新删除资料库，并重新添加媒体库扫描，还是不行，但之前老版本自己配置config那个版本是可以的

**Comment by allanpk716** [comment]
那你应该对比你的 srt 文件的差别，程序又没法操作 plex
