### ISSUE TITLE
点了强制运行之后看日志是停了，但是页面依旧没显示在运行

### ISSUE THREAD

**Issue by willie91** [allanpk716/ChineseSubFinder#202]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.5，v0.20.6都这样

环境: docker or Window or Linux or MAC

## 你遇到什么问题了？
点了强制运行之后看日志是停了，但是页面依旧没显示在运行

## 你的问题弄重现嘛？

能够重新

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs
[ChineseSubFinder.log](https://github.com/allanpk716/ChineseSubFinder/files/8054113/ChineseSubFinder.log)

**Comment by allanpk716** [comment]
开debug看日志

**Comment by allanpk716** [comment]
推送 v0.20.9 升级，发送完整日志

**Comment by willie91** [comment]
> 推送 v0.20.9 升级，发送完整日志

不好意思，忘记回来反馈了，我升级后已经没问题了

**Comment by allanpk716** [comment]
ok，有问题再提
