### ISSUE TITLE
连不上EMBY,这个报错是怎么了

### ISSUE THREAD

**Issue by kunude** [allanpk716/ChineseSubFinder#203]
[INFO]: 2022-02-13 01:24:17 - Download One Started...
[INFO]: 2022-02-13 01:24:17 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-02-13 01:24:17 - Refresh Emby Sub List Start...
**[ERROR]: 2022-02-13 01:26:24 - Refresh Emby Sub List Error
[ERROR]: 2022-02-13 01:26:24 - RefreshEmbySubList Get "http://192.168.x.x:8096//emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=3000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=XXXXXXXXXXXXX": dial tcp 192.168.X.X:8096: connect: connection timed out**
[INFO]: 2022-02-13 01:26:24 - Download One End...
[WARNING]: 2022-02-13 01:26:24 - CloseChrome exit status 1
**[ERROR]: 2022-02-13 01:26:24 - downloader_helper.Start() Error: Get "http://192.168.X.X:8096//emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=3000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=XXXXXXXXXX": dial tcp 192.168.X.X:8096: connect: connection timed out**
[INFO]: 2022-02-13 01:26:24 - First Time coreSubDownloadProcess End
[INFO]: 2022-02-13 01:26:24 - CronHelper Start...
[INFO]: 2022-02-13 01:26:24 - Next Sub Scan Will Process After 6h

**Comment by allanpk716** [comment]
地址多了个 /

**Comment by allanpk716** [comment]
@iMyon 需要在前端帮过滤一下地址输入时候，多一个 / 的问题。后端我也加一下。

**Comment by iMyon** [comment]
> 

你那边改了我就先不改了，有斜杠本身也是合法的url
话说应该有类似`path.join`的方法吧，拼接会自动处理斜杠

**Comment by allanpk716** [comment]
> 你那边改了我就先不改了，有斜杠本身也是合法的url 话说应该有类似`path.join`的方法吧，拼接会自动处理斜杠 @allanpk716

我先在保存配置的时候进行一次检查和调整。你提到的`path.join`我看看是否支持 url 的，这部分我都是简单的 + 去拼接是有问题的。
