### ISSUE TITLE
无法正确识别剧集目录下tvshow.nfo文件

### ISSUE THREAD

**Issue by grayson-kuo** [allanpk716/ChineseSubFinder#207]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.6

环境: docker

## 你遇到什么问题了？

无法正确识别剧集目录下tvshow.nfo文件，提示XML syntax error on line XXX: invalid character entity &id (no semicolon)
附上log截图、tvshow.nfo文件截图、文件目录结构截图

![Snipaste_2022-02-13_23-41-34](https://user-images.githubusercontent.com/17007382/153761077-72800a7a-fc9a-49f3-bdc8-8fc71eeeabe4.png)
![Snipaste_2022-02-13_23-42-04](https://user-images.githubusercontent.com/17007382/153761079-7e7c561f-ec78-4f6b-b334-ffb53bcc44a1.png)
![Snipaste_2022-02-13_23-47-15](https://user-images.githubusercontent.com/17007382/153761081-e1ddbdcc-c23b-488b-afc5-191645a622b1.png)

## 你的问题弄重现嘛？

能

## 你期望的结果

请问可能是什么原因导致的？电影都能识别，剧集都不能识别

**Comment by allanpk716** [comment]
传文件看看。这种乱改 xml 内容导致的（某些项目的规范不严谨导致），也有人反馈过。

**Comment by allanpk716** [comment]
你把对应的
1. 日志
2. xml
发上来，之前有人反馈过，相同文件相同结尾有这个 url 的梗，我调试是没得问题的。

**Comment by grayson-kuo** [comment]
[a50149425358724ee32abaf8e64f46883a94e2962d58d49f13c4958740fbb6c8-json.log](https://github.com/allanpk716/ChineseSubFinder/files/8060251/a50149425358724ee32abaf8e64f46883a94e2962d58d49f13c4958740fbb6c8-json.log)
[tvshow.nfo.log](https://github.com/allanpk716/ChineseSubFinder/files/8060260/tvshow.nfo.log)
剧集都是经过TMM/sonarr/Plex刮削的，没有手动修改过nfo文件，而且电影的都没问题，就是剧集的不行

**Comment by grayson-kuo** [comment]
nfo文件不支持上传，请手动修改下后缀

**Comment by allanpk716** [comment]
本程序有导出日志的，你这日志合适看的难受

**Comment by grayson-kuo** [comment]
[ChineseSubFinder.log](https://github.com/allanpk716/ChineseSubFinder/files/8060750/ChineseSubFinder.log)

**Comment by allanpk716** [comment]
还可以都给我几个吗（组好你有的 tv nfo 都给）？我好看看是否有更多情况出现，一并修复

**Comment by grayson-kuo** [comment]
[tvshow.nfo.zip](https://github.com/allanpk716/ChineseSubFinder/files/8068676/tvshow.nfo.zip)

**Comment by allanpk716** [comment]
> [tvshow.nfo.zip](https://github.com/allanpk716/ChineseSubFinder/files/8068676/tvshow.nfo.zip)

谢谢。这个是使用的第三方库的bug，看样子作者很久不维护了，我看看怎么解决先，至少要这周末才有结论。

**Comment by grayson-kuo** [comment]
原来如此，辛苦了！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Chin allan ***@***.***>
发送时间: Wednesday, February 16, 2022 9:21:38 AM
收件人: allanpk716/ChineseSubFinder ***@***.***>
抄送: Grayson Kuo ***@***.***>; Author ***@***.***>
主题: Re: [allanpk716/ChineseSubFinder] 无法正确识别剧集目录下tvshow.nfo文件 (Issue #207)


tvshow.nfo.zip<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fallanpk716%2FChineseSubFinder%2Ffiles%2F8068676%2Ftvshow.nfo.zip&data=04%7C01%7C%7C8a43fc63c40b432ec30208d9f0eaaeb5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637805713028047579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=37tJAIQWB590JDE96p3mtlVUZ4IuXt7YNZRwYsMF5ew%3D&reserved=0>

谢谢。这个是使用的第三方库的bug，看样子作者很久不维护了，我看看怎么解决先，至少要这周末才有结论。

―
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fallanpk716%2FChineseSubFinder%2Fissues%2F207%23issuecomment-1040993288&data=04%7C01%7C%7C8a43fc63c40b432ec30208d9f0eaaeb5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637805713028047579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4sBr2AvVDFMDwUvKhqdaCzW%2FbmTcPfH0YtKkSz1uq0E%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEBYGFSYGGSYQRSVG2YWRQLU3L32FANCNFSM5OJGT7OQ&data=04%7C01%7C%7C8a43fc63c40b432ec30208d9f0eaaeb5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637805713028047579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MsDaAbC5zC9P4nM4kbby%2FgP4AUjfszJZCK9Raepq5ig%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8a43fc63c40b432ec30208d9f0eaaeb5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637805713028047579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jOjcLigZveL2t5XGmzQ2j86M6uUjpPIHZiCyLmY3csw%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8a43fc63c40b432ec30208d9f0eaaeb5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637805713028047579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E3N26keFJS2aGnyESunN196x2JSZrhD5WGmik%2FdoLnA%3D&reserved=0>.

**Comment by chancenju** [comment]
咋解决的啊
