### ISSUE TITLE
/tmp/rod 占用大量空间

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#209]
连续运行几天后此目录的体积已经达到了 100g 以上

**Comment by allanpk716** [comment]
1. 见 https://github.com/go-rod/rod/issues/181
2. 也算 bug，因为本程序的容器没有重启的逻辑，且我看了，忘记什么时候加了代码但是忘记用了···

**Comment by allanpk716** [comment]
推送了 v0.20.8
