### ISSUE TITLE
加入字幕源 A4K 

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#21]
https://www.a4k.net/
這個網站有的字幕更新得比zimuku更快，有考慮支援嗎?

**Comment by allanpk716** [comment]
> https://www.a4k.net/
> 這個網站有的字幕更新得比zimuku更快，有考慮支援嗎?

一个字幕网站是否加入搜索的支持，会考虑以下几点：
1. 网址是否稳定，是否经常换？
2. 页面的布局经常更新吗？
3. 是否支持 IMDB ID 搜索影片？
4. 连续剧是否支持类似  Loki S0101 这样的搜索结果？

刚试了下：
1. 不支持 IMDB ID 搜索影片，这样的话就很依赖网站搜索字幕的排序，以及字幕的命名规范
2. 同时也不支持类似  Loki S0101 这样的搜索结果
3. 同时搜索 Loki 得到的结果很差

那么字幕自动化下载的匹配度就很低，如果需要支持的话，可以考虑在后面完成了 Web 配置页面的功能，提供手动在这个网站下载字幕的功能。

**Comment by Gwq1003** [comment]
https://subhd.tv/这个网站呢？
