### ISSUE TITLE
希望增加是否要忽略内嵌中文字幕的选项

### ISSUE THREAD

**Issue by techmovie** [allanpk716/ChineseSubFinder#210]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.8

环境: docker

## 你想要新增或者改进什么功能？

有时候视频的内嵌字幕是蓝光的sup字幕，可能为繁体或者翻译质量不如字幕组的字幕，希望增加个选项，让用户选择是否要忽略内嵌的中文字幕，而不是像现在这样检测到有中文字幕就直接跳过不下载字幕了。

感谢🙏

## 这个功能有什么可以参考的资料吗？

 无

**Comment by allanpk716** [comment]
see #173
