### ISSUE TITLE
能否实现字幕文件编码选择（utf-8/GBK）?

### ISSUE THREAD

**Issue by alt-bao** [allanpk716/ChineseSubFinder#212]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.5

环境:群辉7 docker

## 你想要新增或者改进什么功能？
首先感谢作者，很棒的一个软件，解决中文字幕下载的问题，辛苦了。
我使用锋哲v203的蓝光播放机，oppo的65固件。对于utf-8编码的字幕文件不显示中文或者乱码。只能改成GBK编码才可以。一个字幕文件一个字幕文件的修改很繁琐。能否考虑增加个选项，下载字幕自动保存成对应的编码？

**Comment by allanpk716** [comment]
1. 如果仅仅是实现特定的编码转换到特定的编码（utf-8 to GBK）应该是可行的，如果是随意源编码到 GBK，大概率会踩到坑
2. 目前项目中对于文件编码是自动“检测”的，正确率是未知的，从而向后转换编码正确率也是未知的
3. 如果开放这个功能（作为实验室功能），需要大范围测试才清楚是否能够检测源编码正确，且转换到目标编码不乱码

**Comment by alt-bao** [comment]
感谢作者超神速回复。
1、目前我所有下载的字幕（大概不到200条）都是UTF-8的。
2、目前我手动改编码也确实遇到过转编码后中文字符丢失的情况，具体原因是原UTF-8字幕中包含GBK编码外字符，比如（䲟）、（o）等

**Comment by alt-bao** [comment]
3、我自己的处理方式是把这个不支持的字符串改成GBK编码内的字符串，如（鱼印）（。）等。然后再整文件转编码

**Comment by alt-bao** [comment]
感谢，辛苦！

**Comment by allanpk716** [comment]
想到一个梗啊，utf-8 可能有 BOM 头，导致解析有问题，你要不发一个你打开乱码的字幕文件给我，我看看。

或者你自己用二进制工具打开你的乱码的 uft-8 的字幕文件，看看前面三个字节是不是下面这几个。如果是，你可以把这三个字节给删除了（注意，一定是三个字符都符合再删除），保存到本地，在你的环境再试试看看是否乱码。我觉得都这个年代了，国内软件产品搞不定 UTF-8 挺神奇的。

在线打开二进制查看，https://hexed.it/

## 头部 BOM 截图
![image](https://user-images.githubusercontent.com/1176000/154401595-1478f2ec-9127-4a91-a431-271a866f21d5.png)

**Comment by alt-bao** [comment]
![1111](https://user-images.githubusercontent.com/99849666/154428683-54ad128b-06f0-4bd8-bee4-140049cb93be.png)
![2222](https://user-images.githubusercontent.com/99849666/154428751-977463d7-7ab3-4603-9a2a-b171808da4db.png)
好像没有。字幕本事没问题，除了我那个蓝光播放器其他都正常显示。

**Comment by alt-bao** [comment]
[sub.zip](https://github.com/allanpk716/ChineseSubFinder/files/8086587/sub.zip)

**Comment by allanpk716** [comment]
使用你提供的字幕转换到 gbk2312，看看是否可用

[sub_gbk2312.zip](https://github.com/allanpk716/ChineseSubFinder/files/8087438/sub_gbk2312.zip)

**Comment by alt-bao** [comment]
感谢作者，测试该编码可以在锋哲v203的蓝光播放机上正常显示中文，没有乱码

**Comment by allanpk716** [comment]
好的，需要跟前端的朋友对接下功能接口。估计本周可以更新吧。

**Comment by alt-bao** [comment]
期待更新，辛苦

**Comment by allanpk716** [comment]
v0.21.x 已经有初版
