### ISSUE TITLE
这个skipchinesemovie啥意思？

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#213]
[WARNING]: 2022-02-17 19:44:03 - SkipChineseMovie /media/movie/超体 (2014) no metadata file, movie.xml or *.nfo
[INFO]: 2022-02-17 19:44:04 - Skip 超体 (2014) Sub Download, because movie has sub and published more than 2 years
紧接着还有这么一句，所以到底是表达个什么意思...

**Comment by allanpk716** [comment]
看后面
