### ISSUE TITLE
 群晖 docker 下最新版 IO 率过高

### ISSUE THREAD

**Issue by palemoky** [allanpk716/ChineseSubFinder#215]
最近的 0.20.6 和 0.20.9 我都有收到群晖的 IO 率超过 80% 的报警，基本都出现在刚开机后字幕扫描过程中，因为群晖无法自行安装Linux软件包，我看日志也没有关于 IO 的详细报警信息，不知是否其他人也遇到了同样的问题

**Comment by allanpk716** [comment]
多高？截图？硬件信息呢？

**Comment by palemoky** [comment]
> 多高？截图？硬件信息呢？
群晖硬件是 DS218+，硬盘是西数两个 10T 硬盘，型号都是 WD100EMAZ，以下是两次 IO 报警截图。昨晚因为没开 NAS，就没截图，不好意思
<img width="637" alt="image" src="https://user-images.githubusercontent.com/21208635/154612188-0be8d496-0fa2-4aee-8b8b-af713d571ab4.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/21208635/154612382-0ed1ec6c-4f57-4377-bbf7-64ce96b51b95.png">

**Comment by allanpk716** [comment]
如果开启了自动校正字幕时间轴，那么可能是正常的
