### ISSUE TITLE
connect: connection timed out

### ISSUE THREAD

**Issue by kunude** [allanpk716/ChineseSubFinder#216]
不知道使我emby设置不对还是什么原因，一直报这个错误
[ERROR]: 2022-02-18 06:54:33 - RefreshEmbySubList Get "http://**********:*****/emby/Users/Query?api_key=****************": dial tcp **********: connect: connection timed out
不适用emby倒是可以下载字幕

**Comment by kunude** [comment]
不使用emby

**Comment by allanpk716** [comment]
"http://:***

多个 :

**Comment by kunude** [comment]
[ERROR]: 2022-02-18 08:12:21 - RefreshEmbySubList Get "http://192.168.5.2:8096/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=3000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=27a018f815b5490f": dial tcp 192.168.5.2:8096: connect: connection timed out

[ERROR]: 2022-02-18 08:12:21 - downloader_helper.Start() Error: Get "http://192.168.5.2:8096/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=3000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=27a018f8812f": dial tcp 192.168.5.2:8096: connect: connection timed out

应该没多，刚复制错误

**Comment by kunude** [comment]
复制这个地址到浏览器可以看到我的文件
