### ISSUE TITLE
启动后报[INFO]: 2022-02-18 17:20:38 - RunAtStartup: false, so will not Run At Startup, wait 6h to Download

### ISSUE THREAD

**Issue by ericlokz** [allanpk716/ChineseSubFinder#217]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

群晖docker

chinesesubfinder 版本: v0.20.10

环境: 群晖DSM7 docker 
## 你遇到什么问题了？

启动显示RunAtStartup: false, so will not Run At Startup, wait 6h to Download，然后一直这样。

## 你的问题弄重现嘛？

一直出现。

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

[INFO]: 2022-02-18 17:44:12 - ChineseSubFinder Version: v0.20.10
[INFO]: 2022-02-18 17:44:12 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-02-18 17:44:12 - Try Start Server At Port 19035
[INFO]: 2022-02-18 17:44:12 - Setup is Done
[INFO]: 2022-02-18 17:44:12 - RunAtStartup: false, so will not Run At Startup, wait 6h to Download
[INFO]: 2022-02-18 17:44:12 - CronHelper Start...
[INFO]: 2022-02-18 17:44:12 - Next Sub Scan Will Process After 6h

**Comment by ericlokz** [comment]
> 看教程

已经严格按照教程操作了，还是不行。

**Comment by allanpk716** [comment]
https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.20%E6%95%99%E7%A8%8B/03.%E7%99%BB%E5%BD%95Web%E8%AE%BE%E7%BD%AE%E7%95%8C%E9%9D%A2.md

## 图1
![image](https://user-images.githubusercontent.com/1176000/154897999-6b90d090-e95f-4f7d-80bc-fdfeb8c94dbe.png)

## 图2
![image](https://user-images.githubusercontent.com/1176000/154898052-722d6801-421e-403f-9aa4-40616fd07ef8.png)
