### ISSUE TITLE
按照说明配置v0.20.x后无法打开web端页面

### ISSUE THREAD

**Issue by shenquan1997** [allanpk716/ChineseSubFinder#218]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.10

环境: 群晖docker

## 你遇到什么问题了？

按照说明（https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.20教程/00.Docker部署教程.md ）配置v0.20.x后无法打开web端页面，浏览器提示未发送任何数据。

## 你的问题弄重现嘛？

能够重现

**Comment by shenquan1997** [comment]
<img width="514" alt="1" src="https://user-images.githubusercontent.com/68632089/154698304-a43f09bb-f05a-49ab-ba4a-8a80c793b8ff.png">
<img width="514" alt="2" src="https://user-images.githubusercontent.com/68632089/154698313-acd8ec4d-7f5b-4c0b-b52b-cdfba6127648.png">
<img width="514" alt="3" src="https://user-images.githubusercontent.com/68632089/154698314-a98141cd-de8f-4bba-8c15-ccc1e8c4aa7f.png">
<img width="368" alt="4" src="https://user-images.githubusercontent.com/68632089/154698317-6846c2dd-c620-4bca-a68c-7f630c2c4f4c.png">

**Comment by shenquan1997** [comment]
搞定了，原来是配置文件的编码问题，改成utf-8就好了

**Comment by 0x11901** [comment]
我也有同样问题，不过不像是配置文件的编码问题，我改成了utf-8依然不信（再说这个配置文件是程序自己创建的

**Comment by qiuyuyang910** [comment]
> 搞定了，原来是配置文件的编码问题，改成utf-8就好了

怎么解决的啊？

**Comment by allanpk716** [comment]
see #220
