### ISSUE TITLE
如果影片内嵌字幕但字幕中不含中文字幕时，如果开启强制字幕下载。

### ISSUE THREAD

**Issue by luotao21** [allanpk716/ChineseSubFinder#219]
如果影片包含了字幕，但是恰好又没有中文字幕时，字幕下载似乎就跳过了，在设置页面中没有找到可以强制下载字幕的选项，不知道这种使用场景如何使用？

chinesesubfinder 版本: v0.20.6
环境: docker 群晖 DSM 7.0.1

例如下面这些美剧就会有上述问题：
The.Mandalorian.S01.INTERNAL.HDR.2160p.WEB.H265-SKGTV[rartv]
The.Witcher.US.S01.COMPLETE.1080p.WEB.x264-STRiFE[TGx]

**Comment by allanpk716** [comment]
开debug，上传完整日志，且包含需要定位问题的视频内容
