### ISSUE TITLE
按照教程docker版v0.20.x不能正常安装

### ISSUE THREAD

**Issue by qiuyuyang910** [allanpk716/ChineseSubFinder#220]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v.0.20.x

环境: docker

## 你遇到什么问题了？

按照教程不能正确安装

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

能够按照教程正常安装

![image](https://user-images.githubusercontent.com/60593418/154810315-0af0a697-0555-480b-84a5-44592a6e878e.png)
![image](https://user-images.githubusercontent.com/60593418/154810332-a1034f95-968f-4ea7-8ce1-7e8a1423f4c2.png)
![image](https://user-images.githubusercontent.com/60593418/154810351-d23acf4d-a25d-4170-9dde-24d420847d6d.png)
![image](https://user-images.githubusercontent.com/60593418/154810361-e522406b-e2fe-4923-ac9a-d8ba018c0043.png)
![image](https://user-images.githubusercontent.com/60593418/154810366-91ad3f05-52c6-4d9c-9859-f41142316e1b.png)
![image](https://user-images.githubusercontent.com/60593418/154810412-125bf373-8923-4e17-a566-d12eb3aac9f6.png)

**Comment by allanpk716** [comment]
因为你装的是  v0.19.6，现在的教程都是 v0.20.x，是否又是使用了 docker 国内源dao导致的问题。latest 获取不到最新的 v0.20.x

## 你日志的截图
![image](https://user-images.githubusercontent.com/1176000/154898422-a4944663-3121-4470-8b0a-3db8cd3204f0.png)

**Comment by Totobo** [comment]
我用的阿里云Docker加速源，也有一样的问题，下载到了ChineseSubFinder Version: v0.19.6。
进命令行用下面命令临时解决一下吧

`docker pull allanpk716/chinesesubfinder:v0.20.10`
`docker tag allanpk716/chinesesubfinder:v0.20.10 allanpk716/chinesesubfinder:latest`
