### ISSUE TITLE
web界面配置反向代理

### ISSUE THREAD

**Issue by pingowin** [allanpk716/ChineseSubFinder#222]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.10

环境: docker

## 你想要新增或者改进什么功能？

给web界面添加“URL Base”设置项，使之可以用类似这种形式 https://domain.com/csf/ 来访问

## 这个功能有什么可以参考的资料吗？

https://caddy.community/t/the-subfolder-problem-or-why-cant-i-reverse-proxy-my-app-into-a-subfolder/8575

**Comment by allanpk716** [comment]
1. 我不清楚你需要的功能是否是：本程序自我校验基础访问域名，如果不是则提示用户的功能。
2. 如果是上述的功能，暂时没有计划做
3. 但是本程序只要你配置前置进入你服务器的 https 流量就好了，应该是正常的

这里需要特别注意，非常不推荐把本程序直接暴露给外网访问，因为我们没有十分注意去设计“安全”相关的问题，之前设计的目标是针对内网使用的情景，如果你们期望外网使用，我们的建议是慎重。
对于内网访问，就是“防君子”，对于外网访问，这个需要额外的人员帮忙审查是否有设计不合理的地方，引发安全风险。

就目前我测试了直接用群晖内置的“登录门户”->“高级”->“反向代理服务器” 功能，就可以达到 https 访问本程序的功能了。

再次提示，不建议直接外网访问，除非有人能够协助我们完成本程序的安全审查！

## 截图
![image](https://user-images.githubusercontent.com/1176000/154899336-a5c8c916-7ef5-40cc-93f1-a8f813e0e7e6.png)

**Comment by laobanbiefangcu** [comment]
这个应用设置好之后，长期开着就行了，是没必要开外网访问的

**Comment by pingowin** [comment]
能否使用子文件夹来反向代理，而不是用网站根目录来反代？
问题应该在：有两个js在调用system-status和/v1/settings这两个页面的时候，没有自动添加前缀

**Comment by allanpk716** [comment]
> 

额，你提的问题超过我的知识范围了，得换个人跟进下你提的问题。 @iMyon

**Comment by iMyon** [comment]
> 能否使用子文件夹来反向代理，而不是用网站根目录来反代？ 问题应该在：有两个js在调用system-status和/v1/settings这两个页面的时候，没有自动添加前缀

类似Ariang那样可以自己设置服务地址大概可以满足你的需求，不过本程序现在前后端打包在一起了，单独弄个设置出来又有点怪。
单纯根据相对路径请求后台服务倒是可以，我先想一下怎么实现比较优雅

**Comment by iMyon** [comment]
下个发布版本会自动处理路径问题
