### ISSUE TITLE
另一個中文字幕下載的程序

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#223]
在Github看到另一個中文字幕下載的程序，不知道對這個程序的發展有沒有幫助
https://github.com/caryyu/jellyfin-plugin-maxsubtitle

**Comment by allanpk716** [comment]
1. 本程序早期就有一些长期的规划 #20 
2. 进过一段时间的开发，部分目标会调整
3. 目前可以确定有几个功能会做出来：
   1. 字幕的分享功能（类似 xunlei、shooter 唯一ID的玩法，但是资源怎么共享、评分还有待评估）
   2. 更好的时间轴校正功能（现在的还有改进的空间，需要抽时间完善）
   3. 各个字幕下载源功能的插件化（万一后续没有时间维护，可以交给社区）

**Comment by allanpk716** [comment]
你提到的这个程序，想法挺好的，给统一的 API 出来给第三方应用使用。之前有考虑过这个方向，不过，个人比较懒，不太想去跟其他媒体播放器和服务器的项目提需求，个人倾向于更少的依赖完成目标任务。如果非要做 API 接口出来，其实在上述3点完成后，并不难，有很多 API 接口可以借鉴。

**Comment by allanpk716** [comment]
1. 就目前看到的情况，只认为 shooter 和 xunlei 的接口才是终极方案，但是它们没有很好的字幕评分逻辑，以至于接口拿到的数据哪怕是匹配唯一ID也可能是错的。而且，他们都有做播放器，也就是有统一的入口，完全可以知道这个字幕是否是用户认可的。Emby 类似的媒体服务器也有这个入口，只是他们想不想做而已。所以有时候我在做这个功能的时候就比较担心（过度），出现官方比斯同人的情况。 doge。
2. 容在下调侃以下，字幕分享，需要设计类似分布式存储和投票机制的系统（误，过度设计，哈哈）。

**Comment by laobanbiefangcu** [comment]
> 1. 就目前看到的情况，只认为 shooter 和 xunlei 的接口才是终极方案，但是它们没有很好的字幕评分逻辑，以至于接口拿到的数据哪怕是匹配唯一ID也可能是错的。而且，他们都有做播放器，也就是有统一的入口，完全可以知道这个字幕是否是用户认可的。Emby 类似的媒体服务器也有这个入口，只是他们想不想做而已。所以有时候我在做这个功能的时候就比较担心（过度），出现官方比斯同人的情况。 doge。
> 2. 容在下调侃以下，字幕分享，需要设计类似分布式存储和投票机制的系统（误，过度设计，哈哈）。

大佬，现在是不是取消下载subhd网站的字幕了

**Comment by allanpk716** [comment]
> 
> 大佬，现在是不是取消下载subhd网站的字幕了，我看最近下载的都是射手跟字幕库的字幕

其实又上线了 的，但是需要时不时人为干预维护，所以不能保证能用。
