### ISSUE TITLE
Windows版本的无法下载字幕

### ISSUE THREAD

**Issue by jaylen000** [allanpk716/ChineseSubFinder#225]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: Version: v0.20.10

环境: window x86

## 你遇到什么问题了？

描述一下你遇到的问题

无法下载字幕

## 出错的日志信息可以复制一些出来吗？

![image](https://user-images.githubusercontent.com/100186701/155074043-5fe93b7f-f2d7-42f2-933f-87fa131932f3.png)

**Comment by allanpk716** [comment]
因为程序无法访问 baidu 所以跳过

**Comment by jaylen000** [comment]
为什么程序会访问百度啊  有什么解决方法吗

**Comment by allanpk716** [comment]
总得有个判断联网通畅的锚点是吧，下个版本考虑去掉，仅仅提示。
