### ISSUE TITLE
支持英文字幕吗？

### ISSUE THREAD

**Issue by plsharevme** [allanpk716/ChineseSubFinder#226]
刚刚看了下，windows 设置教学，很简单但好像对字幕服务网站的设置没有，比如可以下载英文还是简体。

正在用 bazarr 但好像bazarr 很吃服务器资源，想换这个试试。

谢谢

**Comment by allanpk716** [comment]
目标仅仅是下载中文字幕，英文字幕目前看新的视频都差不多内置有。
