### ISSUE TITLE
两个疑问，save_multi_sub"和ax_request_video_number":500,

### ISSUE THREAD

**Issue by fireflycao** [allanpk716/ChineseSubFinder#227]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v20.10
环境: docker在unraid

## 你遇到什么问题了？
想要下载多个字幕，在页面没找到设置的地方，进入ChineseSubFinderSettings修改save_multi_sub"后无法保存，提示已在别的文件打开。这时候已经关闭设置页面在unraid的docker里也停止chinesesubfinder 的运行了，还是无法修改。
请问这个max_request_video_number":500,是什么意思，最多只能搜索500部电影？

**Comment by allanpk716** [comment]
`max_request_video_number":500`这个是 emby 的搜索传参，最多获取多少最近更新的视频。如果第一次你可以设置比较大以便覆盖你的视频库，之后 500 基本满足绝大部分人的需求。

修改设置还是建议在 Web 上操作，应该在高级设置中。

**Comment by fireflycao** [comment]
高级设置中未见到上面的两项
![Screenshot 2022-02-27 091048](https://user-images.githubusercontent.com/20470524/155864155-532ce901-061e-4f12-93cc-e9b2e0510f05.jpg)

**Comment by allanpk716** [comment]
Emby 才给出 Web 的设置方法，直接修改配置文件也可以（为什么不能修改你得自己排查）

## Emby 多字幕
![image](https://user-images.githubusercontent.com/1176000/155907246-b4cced1b-2d03-42a2-8e6b-51b7849085d0.png)
