### ISSUE TITLE
字幕错误

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#228]
![image](https://user-images.githubusercontent.com/60920512/155307406-7dc50b3d-e2b2-4d52-8151-53a610992aa1.png)
这应该是古驰家族的字幕，不知道为什么放在这里了，而且经过了时间轴校对。。。
![image](https://user-images.githubusercontent.com/60920512/155307520-42213ade-5beb-4c6b-82fc-d15944ff7486.png)

**Comment by allanpk716** [comment]
开 debug 去缓存目录找原始网站下载的字幕出来，再反馈。没得日志没得意义。

**Comment by jasonhorga** [comment]
[INFO]: 2022-02-25 00:13:15 - Queue 314 DlSub Start /media/movie/爱国者 (2000) [tmdbid=2024]
[INFO]: 2022-02-25 00:13:15 - Queue 314 shooter Start...
[INFO]: 2022-02-25 00:13:15 - Queue 314 shooter End...
[ERROR]: 2022-02-25 00:13:15 - Queue 314 shooter oneMovieDlSubInOneSite video file is too small
[INFO]: 2022-02-25 00:13:15 - Queue 314 zimuku Start...
[INFO]: 2022-02-25 00:13:15 - Queue 314 xunlei Start...
[INFO]: 2022-02-25 00:13:15 - Queue 314 xunlei End...
[ERROR]: 2022-02-25 00:13:15 - Queue 314 xunlei oneMovieDlSubInOneSite cid is empty
[ERROR]: 2022-02-25 00:13:15 - model.GetImdbInfo no metadata file, movie.xml or *.nfo
[ERROR]: 2022-02-25 00:13:15 - VideoNameSearchKeywordMaker year to int strconv.Atoi: parsing "": invalid syntax
[INFO]: 2022-02-25 00:14:26 - Queue 314 zimuku End...
[INFO]: 2022-02-25 00:14:26 - Queue 314 DlSub End /media/movie/爱国者 (2000) [tmdbid=2024]
[INFO]: 2022-02-25 00:14:27 - ----------------------------------
[INFO]: 2022-02-25 00:14:27 - OrgSubName: [zimuku]_1_Patriots.Day.2016.BluRay.1080p.x264.DTS-HD.MA.7.1-HDChina.ass
[INFO]: 2022-02-25 00:14:27 - SubDownAt: /media/movie/爱国者 (2000) [tmdbid=2024].zh.ass
[INFO]: 2022-02-25 00:14:28 - ----------------------------------
[ERROR]: 2022-02-25 00:14:28 - SaveMultiSub: false writeSubFile2VideoPath: exit status 1

**Comment by allanpk716** [comment]
优先 IMDB 下载，你这个都没得，只能文件名，你看看你文件名是啥，那存储就是啥。没得 IMDB 作为基准其他信息都不作为基准去识别，没得意义。

**Comment by allanpk716** [comment]
吐槽下，为什么有那么多字幕下载工具效果不佳，源头问题就是规范性问题（乱七八糟的文件名谁能解析正确率高，然后还是通过文件名去下载字幕，能有多高正确率，效果不佳怪不了工具），以我现在看到的反馈，有不少人的视频目录名称中带有 IMDB 或者 TMDB ID 的，这都什么鬼规范，好好的 nfo 和 xml 的标注规范不用，有些工具非要整自己的特殊化，以及还有在 xml 最后一行写入 http 地址信息的。都什么鬼。

本工具没有任何神奇的地方，仅仅是强调了需要严格的削刮，无非就是要输出 xml 和 nfo，如果想要文件唯一 ID 匹配只有 xunlei 和 shooter 接口。剩下的两个字幕源优先级永远是 IMDB 然后才是文件名，后者效果差我解决不了，因为这个是你们削刮器决定的。

**Comment by allanpk716** [comment]
说白了，也是因为 subhd 和 zimuzu 支持了 IMDB ID 搜索带来了优势，不然效果也是一样糟糕。得感谢他们。

**Comment by jasonhorga** [comment]
你要的nfo

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movie>
  <plot><![CDATA[梅尔·吉布森又一次为自由而战。故事发生在美国独立战争期间，一位爱好和平的父亲被逼上梁山，跟残暴的英国军队作殊死搏斗。本杰明·马丁早已告别戎马生涯，虽然他曾经同英国人并肩与法国人和印第安人浴血奋战，但终于有一天，他的儿子成为对抗英国军队的民兵组织头领，而英军掠夺了他的家园及他所挚爱的一切，于是他从一个理想主义的爱国者演变为现实主义的爱国者。]]></plot>
  <outline />
  <lockdata>false</lockdata>
  <dateadded>2022-02-23 14:40:20</dateadded>
  <title>爱国者</title>
  <originaltitle>The Patriot</originaltitle>
  <actor>
    <name>Mel Gibson</name>
    <role>Benjamin Martin</role>
    <type>Actor</type>
    <tmdbid>2461</tmdbid>
  </actor>
  <actor>
    <name>Heath Ledger</name>
    <role>Gabriel Martin</role>
    <type>Actor</type>
    <tmdbid>1810</tmdbid>
  </actor>
  <actor>
    <name>Joely Richardson</name>
    <role>Charlotte Selton</role>
    <type>Actor</type>
    <tmdbid>20810</tmdbid>
  </actor>
  <actor>
    <name>Jason Isaacs</name>
    <role>Col. William Tavington</role>
    <type>Actor</type>
    <tmdbid>11355</tmdbid>
  </actor>
  <actor>
    <name>Chris Cooper</name>
    <role>Col. Harry Burwell</role>
    <type>Actor</type>
    <tmdbid>2955</tmdbid>
  </actor>
  <actor>
    <name>Tchéky Karyo</name>
    <role>Jean Villeneuve</role>
    <type>Actor</type>
    <tmdbid>10698</tmdbid>
  </actor>
  <actor>
    <name>René Auberjonois</name>
    <role>Reverend Oliver</role>
    <type>Actor</type>
    <tmdbid>9807</tmdbid>
  </actor>
  <actor>
    <name>Lisa Brenner</name>
    <role>Anne Howard</role>
    <type>Actor</type>
    <tmdbid>20811</tmdbid>
  </actor>
  <actor>
    <name>Tom Wilkinson</name>
    <role>Gen. Cornwallis</role>
    <type>Actor</type>
    <tmdbid>207</tmdbid>
  </actor>
  <actor>
    <name>Donal Logue</name>
    <role>Dan Scott</role>
    <type>Actor</type>
    <tmdbid>10825</tmdbid>
  </actor>
  <actor>
    <name>Leon Rippy</name>
    <role>John Billings</role>
    <type>Actor</type>
    <tmdbid>15374</tmdbid>
  </actor>
  <actor>
    <name>Adam Baldwin</name>
    <role>Capt. Wilkins</role>
    <type>Actor</type>
    <tmdbid>2059</tmdbid>
  </actor>
  <actor>
    <name>Jay Arlen Jones</name>
    <role>Occam</role>
    <type>Actor</type>
    <tmdbid>20812</tmdbid>
  </actor>
  <actor>
    <name>Joey D. Vieira</name>
    <role>Peter Howard</role>
    <type>Actor</type>
    <tmdbid>20813</tmdbid>
  </actor>
  <actor>
    <name>Gregory Smith</name>
    <role>Thomas Martin</role>
    <type>Actor</type>
    <tmdbid>20814</tmdbid>
  </actor>
  <actor>
    <name>Mika Boorem</name>
    <role>Margaret Martin</role>
    <type>Actor</type>
    <tmdbid>21027</tmdbid>
  </actor>
  <actor>
    <name>Skye McCole Bartusiak</name>
    <role>Susan Martin</role>
    <type>Actor</type>
    <tmdbid>20815</tmdbid>
  </actor>
  <actor>
    <name>Trevor Morgan</name>
    <role>Nathan Martin</role>
    <type>Actor</type>
    <tmdbid>4940</tmdbid>
  </actor>
  <actor>
    <name>Bryan Chafin</name>
    <role>Samuel Martin</role>
    <type>Actor</type>
    <tmdbid>20816</tmdbid>
  </actor>
  <actor>
    <name>Logan Lerman</name>
    <role>William Martin</role>
    <type>Actor</type>
    <tmdbid>33235</tmdbid>
  </actor>
  <actor>
    <name>Mary Jo Deschanel</name>
    <role>Mrs. Howard</role>
    <type>Actor</type>
    <tmdbid>271352</tmdbid>
  </actor>
  <actor>
    <name>Jamieson Price</name>
    <role>Capt. Bordon</role>
    <type>Actor</type>
    <tmdbid>155397</tmdbid>
  </actor>
  <actor>
    <name>Peter Woodward</name>
    <role>Charles O'Hara</role>
    <type>Actor</type>
    <tmdbid>20817</tmdbid>
  </actor>
  <actor>
    <name>Grahame Wood</name>
    <role>Redcoat Lieutenant</role>
    <type>Actor</type>
    <tmdbid>145072</tmdbid>
  </actor>
  <actor>
    <name>Beatrice Bush</name>
    <role>Abigale the Housekeeper</role>
    <type>Actor</type>
    <tmdbid>1534420</tmdbid>
  </actor>
  <actor>
    <name>Shane Ayon</name>
    <role>Grinadier Soldier</role>
    <type>Actor</type>
    <tmdbid>1839449</tmdbid>
  </actor>
  <actor>
    <name>Shan Omar Huey</name>
    <role>Joshua</role>
    <type>Actor</type>
    <tmdbid>20583</tmdbid>
  </actor>
  <actor>
    <name>Hank Stone</name>
    <role>Rollins</role>
    <type>Actor</type>
    <tmdbid>112100</tmdbid>
  </actor>
  <actor>
    <name>Kirk Fox</name>
    <role>Skunk</role>
    <type>Actor</type>
    <tmdbid>300990</tmdbid>
  </actor>
  <actor>
    <name>Jack Moore</name>
    <role>Curly</role>
    <type>Actor</type>
    <tmdbid>117564</tmdbid>
  </actor>
  <actor>
    <name>Mark Twogood</name>
    <role>Danvers</role>
    <type>Actor</type>
    <tmdbid>126847</tmdbid>
  </actor>
  <actor>
    <name>Colt Romberger</name>
    <role>Colt</role>
    <type>Actor</type>
    <tmdbid>2020769</tmdbid>
  </actor>
  <actor>
    <name>Terry Layman</name>
    <role>Gen. George Washington</role>
    <type>Actor</type>
    <tmdbid>2020770</tmdbid>
  </actor>
  <actor>
    <name>Shannon Eubanks</name>
    <role>Mrs. Simms</role>
    <type>Actor</type>
    <tmdbid>80784</tmdbid>
  </actor>
  <actor>
    <name>Bill Roberson</name>
    <role>Loyalist Simms</role>
    <type>Actor</type>
    <tmdbid>1682751</tmdbid>
  </actor>
  <actor>
    <name>Charles Black</name>
    <role>Matthew</role>
    <type>Actor</type>
    <tmdbid>1615196</tmdbid>
  </actor>
  <actor>
    <name>Andy Stahl</name>
    <role>Gen. Nathanel Greene</role>
    <type>Actor</type>
    <tmdbid>21083</tmdbid>
  </actor>
  <actor>
    <name>Kristian Truelsen</name>
    <role>Hardwick</role>
    <type>Actor</type>
    <tmdbid>980746</tmdbid>
  </actor>
  <actor>
    <name>Kanin Howell</name>
    <role>Postrider</role>
    <type>Actor</type>
    <tmdbid>179851</tmdbid>
  </actor>
  <actor>
    <name>Mark Jeffrey Miller</name>
    <role>Wounded Continental</role>
    <type>Actor</type>
    <tmdbid>1249175</tmdbid>
  </actor>
  <actor>
    <name>Zach Hanner</name>
    <role>British Field Officer</role>
    <type>Actor</type>
    <tmdbid>1392671</tmdbid>
  </actor>
  <actor>
    <name>Randell Haynes</name>
    <role>Patriot Middleton</role>
    <type>Actor</type>
    <tmdbid>1473943</tmdbid>
  </actor>
  <actor>
    <name>John Storey</name>
    <role>Cowpens Militiaman</role>
    <type>Actor</type>
    <tmdbid>1172430</tmdbid>
  </actor>
  <actor>
    <name>Greg Good</name>
    <role>Cowpens Militiaman</role>
    <type>Actor</type>
    <tmdbid>1852407</tmdbid>
  </actor>
  <actor>
    <name>John F. Dzencelowcz II</name>
    <role>Continental Soldier</role>
    <type>Actor</type>
    <tmdbid>2020771</tmdbid>
  </actor>
  <actor>
    <name>Kyle Richard Engels</name>
    <role>Billings' Son</role>
    <type>Actor</type>
    <tmdbid>2020774</tmdbid>
  </actor>
  <actor>
    <name>John Bennes</name>
    <role>Speaker</role>
    <type>Actor</type>
    <tmdbid>72181</tmdbid>
  </actor>
  <actor>
    <name>John Curran</name>
    <role>Redcoat Sergeant #1</role>
    <type>Actor</type>
    <tmdbid>1587358</tmdbid>
  </actor>
  <actor>
    <name>Dara Coleman</name>
    <role>Redcoat Sergeant #2</role>
    <type>Actor</type>
    <tmdbid>1217568</tmdbid>
  </actor>
  <actor>
    <name>Roy McCrerey</name>
    <role>Redcoat</role>
    <type>Actor</type>
    <tmdbid>51464</tmdbid>
  </actor>
  <actor>
    <name>P. Dion Moore</name>
    <role>Redcoat</role>
    <type>Actor</type>
    <tmdbid>2020775</tmdbid>
  </actor>
  <actor>
    <name>Tyler Long</name>
    <role>Page Poy</role>
    <type>Actor</type>
    <tmdbid>2020776</tmdbid>
  </actor>
  <actor>
    <name>John H. Bush</name>
    <role>Abner</role>
    <type>Actor</type>
    <tmdbid>2020777</tmdbid>
  </actor>
  <actor>
    <name>Gil Johnson</name>
    <role>Militiaman</role>
    <type>Actor</type>
    <tmdbid>168676</tmdbid>
  </actor>
  <actor>
    <name>Scott Miles</name>
    <role>Patriot Private</role>
    <type>Actor</type>
    <tmdbid>74584</tmdbid>
  </actor>
  <actor>
    <name>Derrick B. Young</name>
    <role>Slave Boy</role>
    <type>Actor</type>
    <tmdbid>2020781</tmdbid>
  </actor>
  <actor>
    <name>Le Roy Seabrook</name>
    <role>Gullah Minister</role>
    <type>Actor</type>
    <tmdbid>2020782</tmdbid>
  </actor>
  <actor>
    <name>Samuel Brown Jr.</name>
    <role>Gullah Musician</role>
    <type>Actor</type>
    <tmdbid>2020783</tmdbid>
  </actor>
  <actor>
    <name>Samuel Brown Sr.</name>
    <role>Gullah Musician</role>
    <type>Actor</type>
    <tmdbid>2020784</tmdbid>
  </actor>
  <actor>
    <name>Lillie L. Harris</name>
    <role>Gullah Musician</role>
    <type>Actor</type>
    <tmdbid>2020785</tmdbid>
  </actor>
  <actor>
    <name>Braima Moiwai</name>
    <role>Gullah Musician</role>
    <type>Actor</type>
    <tmdbid>2020788</tmdbid>
  </actor>
  <actor>
    <name>Patrick Tatopoulos</name>
    <role>French Naval Officer</role>
    <type>Actor</type>
    <tmdbid>3964</tmdbid>
  </actor>
  <director tmdbid="6046">Roland Emmerich</director>
  <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=R_C_dPHEWN0</trailer>
  <rating>7.2</rating>
  <year>2000</year>
  <mpaa>R</mpaa>
  <imdbid>tt0187393</imdbid>
  <tmdbid>2024</tmdbid>
  <premiered>2000-06-28</premiered>
  <releasedate>2000-06-28</releasedate>
  <criticrating>62</criticrating>
  <runtime>165</runtime>
  <country>Germany</country>
  <country>United States of America</country>
  <genre>剧情</genre>
  <genre>历史</genre>
  <genre>战争</genre>
  <genre>动作</genre>
  <studio>Centropolis Entertainment</studio>
  <studio>Mutual Film Company</studio>
  <studio>Global Medien KG</studio>
  <studio>Columbia Pictures</studio>
  <studio>Sony Pictures</studio>
  <uniqueid type="Tmdb">2024</uniqueid>
  <uniqueid type="Imdb">tt0187393</uniqueid>
  <id>tt0187393</id>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>hevc</codec>
        <micodec>hevc</micodec>
        <bitrate>67507281</bitrate>
        <width>3840</width>
        <height>2160</height>
        <aspect>16:9</aspect>
        <aspectratio>16:9</aspectratio>
        <framerate>23.976025</framerate>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
        <duration>164</duration>
        <durationinseconds>9886</durationinseconds>
      </video>
      <audio>
        <codec>truehd</codec>
        <micodec>truehd</micodec>
        <scantype>progressive</scantype>
        <channels>8</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>640000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>dts</codec>
        <micodec>dts</micodec>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>448000</bitrate>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>192000</bitrate>
        <scantype>progressive</scantype>
        <channels>2</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>PGSSUB</codec>
        <micodec>PGSSUB</micodec>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
    </streamdetails>
  </fileinfo>
</movie>

**Comment by jasonhorga** [comment]
tmdbid是emby的规范，如下

![image](https://user-images.githubusercontent.com/60920512/155643810-94c5a0fd-4d74-4746-8ad3-5ed58c8a67b1.png)

这不是为了取代nfo的，是我在下载影片后，emby削刮前做的一个预备工作，为了是让emby的削刮更准确，结果也是如此，从来不需要再手动处理

我前面确实写错了，这个不是给下载工具用的，另附上nfo供参考

![image](https://user-images.githubusercontent.com/60920512/155644007-6a8fa4f6-4e44-4454-9612-e6cef8af9af5.png)
[爱国者 (2000) [tmdbid=2024].zip](https://github.com/allanpk716/ChineseSubFinder/files/8138061/2000.tmdbid.2024.zip)

**Comment by jasonhorga** [comment]
> 优先 IMDB 下载，你这个都没得，只能文件名，你看看你文件名是啥，那存储就是啥。没得 IMDB 作为基准其他信息都不作为基准去识别，没得意义。

后面补充了nfo信息，请查收

**Comment by jasonhorga** [comment]
可以看到这里面是有非常清晰的imdb编号的

![image](https://user-images.githubusercontent.com/60920512/155645535-c186a824-44a4-4ee9-9532-f2a47c61e98c.png)

**Comment by allanpk716** [comment]
以你给到日志，无法从具体的电影绝对路径去找到对应的 xml 或者 nfo 文件，你给的文件我调试是没有问题的

## 日志截图
![image](https://user-images.githubusercontent.com/1176000/155669754-6e1d21c7-1a12-40d8-9750-9958b6134169.png)


## 调试截图
![image](https://user-images.githubusercontent.com/1176000/155672764-0560a149-8205-414c-be87-f45250bef249.png)

**Comment by allanpk716** [comment]
在看了下你的视频文件目录，目前是不支持蓝光的，出问题的原因在这。:joy:

**Comment by allanpk716** [comment]
> 在看了下你的视频文件目录，目前是不支持蓝光的，出问题的原因在这。😂

以及，我现在还没下载到一部蓝光，so，这个支持需要等我下载至少一部完毕。

**Comment by jasonhorga** [comment]
原盘的问题还在check list上么

**Comment by jasonhorga** [comment]
在pt网站上还是可以找到很多的原盘种子的，只是没法直接提供给你

**Comment by allanpk716** [comment]
我联系我朋友人肉 copy 一份来测试吧，看看这个月能搞定没有

**Comment by jasonhorga** [comment]
我有个想法啊，探讨一下

目前CSF从emby api取影片的list，假设找到一个原盘文件，返回的应该是一个目录而不是iso或者mkv，但是对应的类型是BLURAY，如下图

![image](https://user-images.githubusercontent.com/60920512/160238605-87c5535a-7f75-4792-a677-fed397f98dbb.png)

这时候其实你是取不到具体的文件名的，只是一个目录名，我不知道你的机制是不是还会去这个目录下取nfo文件，我觉得不会吧，然后就会弹出没有nfo文件的提示

![image](https://user-images.githubusercontent.com/60920512/160238799-e3892ac1-033b-493e-8f13-fccae2011008.png)

实际上这个目录下是有nfo的

![image](https://user-images.githubusercontent.com/60920512/160239373-84151248-0221-4e1d-bd62-9c8f2bee3c35.png)

而且这时候你还是去下载了字幕（应该是根据关键字），最后存到了根目录下

![image](https://user-images.githubusercontent.com/60920512/160238825-3314a3fd-a314-43b2-b47b-990a49489ac7.png)

我能否建议这时候把字幕存到相应的目录中，例如

![image](https://user-images.githubusercontent.com/60920512/160238935-9211b1c4-3dc0-4697-bdb7-01729062e60a.png)

在根目录（上层目录）是无法被emby读出的，但是放到这里就可以了，也可以正常播放加载，包括从infuse连接emby的时候，所以我想是不是可以稍微修改一下代码在这种情况下把字幕放到对应的目录中而不是放到根目录

**Comment by allanpk716** [comment]
连续剧有蓝光的范例吗？

**Comment by jasonhorga** [comment]
我没有下载过蓝光原盘的电视剧，这个感觉非常非常罕见，而且大部分电视剧都是web-dl吧，你就先别考虑了

**Comment by jasonhorga** [comment]
这样是不行的，
![image](https://user-images.githubusercontent.com/60920512/160978731-aee1cc5f-1766-40e2-8c81-0662c7823170.png)
这样就可以了，
![image](https://user-images.githubusercontent.com/60920512/160978799-4a41a879-a566-48c2-8be5-8f548a0bd637.png)
Emby也能认出来字幕了
![image](https://user-images.githubusercontent.com/60920512/160978880-601699d7-fc6e-4d65-a248-d6e4c3318206.png)
改一下存储位置就好啦~allan加油~

**Comment by allanpk716** [comment]
我弄到一部蓝光，为啥 Emby 提示我没法看啊···什么梗，还有啥 Emby 程序支持播放蓝光？我下的也是官方的 Emby APP 啊··· :joy:

我看看怎么兼容先，应该不难

## 截图
![image](https://user-images.githubusercontent.com/1176000/160986222-3c2f0bd7-8c8d-4d0e-a1de-e43a717a6aa9.png)

**Comment by jasonhorga** [comment]
emby处理蓝光原盘是有bug的，可以参考这篇文章，我写了个python程序专门用来替换这里面提到的一些字符
[https://emby.media/community/index.php?/topic/100644-a-problem-use-infuse-stream-video-from-emby-server/](url)
另外我其实是通过infuse连接到我的emby进行播放的，emby只是起到了削刮和数据库的作用，给infuse吐一个连接，infuse直接连接就可以播放了，类似Kodi也是如此处理的，所以你可以先试着把字幕文件放在不同的位置，emby的UI中会显示是不是能找到这个字幕，例如我上面comment中的截图

**Comment by jasonhorga** [comment]
你可以先用那个文章中的代码处理一下你的蓝光原盘目录，然后再重新扫描媒体库文件，就可以正确识别出来了

**Comment by allanpk716** [comment]
v0.23 已经支持蓝光电影了，你先试试
