### ISSUE TITLE
字幕后缀名导致可能保存多个字幕

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#230]
即使设置了只保存一个字幕文件, 但在重新抓取字幕的时候, 还是可能因为后缀问题(比如原本已经有了一个`.ass`文件的字幕, 但这次又抓取准备保存一个`.srt`格式的字幕)导致实际有多个字幕文件被保存.

**Comment by allanpk716** [comment]
没有把缓存机制做出来前，这个问题暂时不处理。

**Comment by allanpk716** [comment]
目前下载字幕的质量并不是很高，所以本地留下几个字幕，也许目前阶段是比较合适的。后续还有个功能上线后，你想要的只有唯一一个字幕的功能是可以给出来的。
