### ISSUE TITLE
容器大小异常增大

### ISSUE THREAD

**Issue by zxcdeyouxiang** [allanpk716/ChineseSubFinder#231]
chinesesubfinder 版本: 0.20.10

环境: Unraid docker

容器大小突然增大，检查过/app/cache映射，没有问题可以正常访问，/app目录下也没有被创建老版本用的SubFixCache目录，但是整个容器大小突破了3GB，占满了我专门给Docker用的小固态，通过强制重新激活新容器可以恢复大小。。

**Comment by allanpk716** [comment]
具体配置截图或者发出来

**Comment by cgl0013** [comment]
![Uploading image.png…]()

**Comment by cgl0013** [comment]
检查了配置 发现cache 文件夹在容器内的目录是 /app/cache 而不是/cache 请检查配置 @zxcdeyouxiang

**Comment by zxcdeyouxiang** [comment]
> 检查了配置 发现cache 文件夹在容器内的目录是 /app/cache 而不是/cache 请检查配置 @zxcdeyouxiang

我检查了的字幕调轴缓存文件夹是映射在/app/cache，从容器内和容器外都可以访问到，而且没出现异常增大之前已经运行超过7天，按设置每6个小时运行一次的话，也已运行超过14次，一直没有出现这个问题。如果是目录映射错误的话，第一次就应该出现磁盘爆了的问题..

**Comment by zxcdeyouxiang** [comment]
> 具体配置截图或者发出来

docker run -d --name='chinesesubfinder' --net='bridge' --cpuset-cpus='3,9,4,10' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -p '19035:19035/tcp' -v '/mnt/cache/CSF-SubFixCache':'/app/cache':'rw' -v '/mnt/user/media/':'/media':'rw' -v '/mnt/user/appdata/chinesesubfinder':'/config':'rw' 'allanpk716/chinesesubfinder'

**Comment by allanpk716** [comment]
你这样反馈信息无法定位问题，建议你想一下如何反馈问题，有效的提问。

https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.20%E6%95%99%E7%A8%8B/00.Docker%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B.md

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by zxcdeyouxiang** [comment]
> 你这样反馈信息无法定位问题，建议你想一下如何反馈问题，有效的提问。
> 
> https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.20%E6%95%99%E7%A8%8B/00.Docker%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B.md
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

目前的状况是，因为我强制重新拉取了镜像，这个现象暂时没有复现，所以我也提供不了更多的信息了

**Comment by allanpk716** [comment]
> > 你这样反馈信息无法定位问题，建议你想一下如何反馈问题，有效的提问。
> > https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.20%E6%95%99%E7%A8%8B/00.Docker%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B.md
> > https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> 好像我定位了异常目录，在/root/.cache，这个目录是干啥的。。

应该没有使用这个目录，你这个目录中有什么内容？

**Comment by zxcdeyouxiang** [comment]
> 



> > > 你这样反馈信息无法定位问题，建议你想一下如何反馈问题，有效的提问。
> > > https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.20%E6%95%99%E7%A8%8B/00.Docker%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B.md
> > > https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> > 
> > 
> > 好像我定位了异常目录，在/root/.cache，这个目录是干啥的。。
> 
> 应该没有使用这个目录，你这个目录中有什么内容？

du -h /root
5.8M    /root/.cache/rod/browser/chromium-901912/chrome-linux/ClearKeyCdm/_platform_specific/linux_x64
5.8M    /root/.cache/rod/browser/chromium-901912/chrome-linux/ClearKeyCdm/_platform_specific
5.8M    /root/.cache/rod/browser/chromium-901912/chrome-linux/ClearKeyCdm
68K     /root/.cache/rod/browser/chromium-901912/chrome-linux/resources/inspector_overlay
68K     /root/.cache/rod/browser/chromium-901912/chrome-linux/resources
12K     /root/.cache/rod/browser/chromium-901912/chrome-linux/MEIPreload
57M     /root/.cache/rod/browser/chromium-901912/chrome-linux/locales
3.9M    /root/.cache/rod/browser/chromium-901912/chrome-linux/swiftshader
400M    /root/.cache/rod/browser/chromium-901912/chrome-linux
400M    /root/.cache/rod/browser/chromium-901912
400M    /root/.cache/rod/browser
400M    /root/.cache/rod
160K    /root/.cache/fontconfig
400M    /root/.cache
0       /root/.config/chromium/Crash Reports/new
0       /root/.config/chromium/Crash Reports/pending
0       /root/.config/chromium/Crash Reports/completed
0       /root/.config/chromium/Crash Reports/attachments
4.0K    /root/.config/chromium/Crash Reports
4.0K    /root/.config/chromium
4.0K    /root/.config
68K     /root/.pki/nssdb
68K     /root/.pki
400M    /root

**Comment by allanpk716** [comment]
/root/.cache/rod 这个是爬虫的缓存，最新版本应该解决了缓存清理问题，你继续观察在反馈

**Comment by allanpk716** [comment]
每一个视频下载是并发，其他操作都是线性执行的逻辑，日志有体现。理论是完毕一轮才清理，如果你发现不对，可以看日志。更加详细的日志需要开启 debug。

**Comment by zxcdeyouxiang** [comment]
目前我把/root/.cache映射到容器外/mnt/cache/CSF-SubFixCache/CrawlerCache目录，占用400MB，这个目录基本就这么大，没有新的变化
然后/tmp/rod映射到容器外/mnt/user/CSF-SubFixCache/RodCache目录，占用能达到15GB以上
把这两个目录映射到容器外后，容器本身的大小就不怎么变化了

**Comment by allanpk716** [comment]
> 目前我把/root/.cache映射到容器外/mnt/cache/CSF-SubFixCache/CrawlerCache目录，占用400MB，这个目录基本就这么大，没有新的变化 然后/tmp/rod映射到容器外/mnt/user/CSF-SubFixCache/RodCache目录，占用能达到15GB以上 把这两个目录映射到容器外后，容器本身的大小就不怎么变化了

试最新 v0.21.x 的，接管了 rod 的缓存目录，你用几天观察下
