### ISSUE TITLE
请教下linux安装问题

### ISSUE THREAD

**Issue by tackleyang** [allanpk716/ChineseSubFinder#233]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
chinesesubfinder 版本: v0.20.10
环境: Linux
请教下，我有个vps，想安装这个，已经解压进去了，但是不会安装，能否帮忙出个linux的安装教程（chinesesubfinder 文件无法运行，解压后这个文件没有后缀，不知道用什么命令来执行）。
谢谢。

**Comment by allanpk716** [comment]
我依然建议是使用 docker，不然你会遇到支持库的问题（大概率），比如需要手动下载 ffmpeg 等。而且你需要确认你的 VPS 由多少内存，因为使用 chrome，所以内存大户

**Comment by tackleyang** [comment]
谢谢回复，docker不是太熟悉，是不是emby也要使用docker，配套 chinesesubfinder 一起使用才比较好。

**Comment by allanpk716** [comment]
> 谢谢回复，docker不是太熟悉，是不是emby也要使用docker，配套 chinesesubfinder 一起使用才比较好。

也是建议使用 docker ，这样无需关心详细的依赖部署问题。

**Comment by allanpk716** [comment]
已经推出 Lite 版本，试试。具体见首页的部署教程。
