### ISSUE TITLE
申请增加：手动调整下载字幕的媒体列表顺序 的功能

### ISSUE THREAD

**Issue by xmumeyu** [allanpk716/ChineseSubFinder#235]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.19.6

环境: docker

## 你想要新增或者改进什么功能？

能否接收命令行或者其他输入方式，允许手动添加需要下载字幕的媒体列表；

我现在媒体库里的没有字幕的电影电视剧过多（5000+），每天下载的字幕数量是有限的，已经调整为每两小时执行一次，不知道什么时候才能排到想看的视频。

手动下载还能应对这种情况：媒体下载后，搜刮软件搜刮错误，保存了错误的nfo信息，导致字幕下载错误，此时手动删除了字幕，但是媒体文件名不变，chinesesubfinder 不会再次下载字幕的（是否去哪里手动清理下载缓存）

## 这个功能有什么可以参考的资料吗？

无

**Comment by allanpk716** [comment]
> 
> 手动下载还能应对这种情况：媒体下载后，搜刮软件搜刮错误，保存了错误的nfo信息，导致字幕下载错误，此时手动删除了字幕，但是媒体文件名不变，chinesesubfinder 不会再次下载字幕的（是否去哪里手动清理下载缓存）
> 

你没有使用 Emby 的话，字幕的搜索逻辑是全部搜索视频，然后推算视频的名称和位置检测字幕是否存在，理论上不应该出现你说的删除字幕就不会再次下载的逻辑，只要没得字幕都会走下载逻辑。目前也还没有把是否下载字幕的缓存加上，现在的缓存都是针对下载缓存和字幕校正的。

1. 你提的这个需求我得想一下怎么做，毕竟那么大量的扫描没有测试过。至少目前考虑应该需要先进行一次全部视频扫描，然后再拆分多批扫描。但是涉及到错误的视频还需要再次排入队列，所以得有缓存以及附带的逻辑，应该不会很快能够实现。
2. 也许会在缓存逻辑做出来后再做你这个功能会容易些，但是具体时间未知。
3. 目前有个功能是隐蔽的，没有给出 UI 设置接口。在你的具体的一部电影或者连续剧的根目录下，新建 `.ignore` 文件，可以跳过扫描。也许可以暂时对你这种情况有那么点用。
4. 如果你有更好的实现想法可以补充。

**Comment by xmumeyu** [comment]
1. 既然有.ignore的设定，能不能加个 .force 的选项，扫描到这里就强制开始搜索字幕？
2. 是否可以手动带参数（IMDB ID+存储目录)单点下载某字幕，不走扫描等待逻辑，虽然是手动，但是省去自己开字幕库网站搜索和下载并改名及调时间轴的工作量。

**Comment by allanpk716** [comment]
1. 应该不会考虑，跟你提的 2 重复
2. 有计划提供媒体库视频列表界面，让用户手动选择批量视频下载

**Comment by allanpk716** [comment]
试试最新版本
