### ISSUE TITLE
不能下载字幕

### ISSUE THREAD

**Issue by lightman173** [allanpk716/ChineseSubFinder#237]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.10

环境: docker

## 你遇到什么问题了？

点击启动任务后，看了下进程发现没有跳动

GID/UID
-------------------------------------

User uid:    1026
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 50-config: executing... 
chown: cannot access '/media3': No such file or directory
chown: cannot access '/media4': No such file or directory
chown: cannot access '/media5': No such file or directory
chown: cannot access '/media6': No such file or directory
chown: cannot access '/media7': No such file or directory
chown: cannot access '/media8': No such file or directory
chown: cannot access '/media9': No such file or directory
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO]: 2022-03-03 02:28:29 - ChineseSubFinder Version: v0.20.10
[INFO]: 2022-03-03 02:28:29 - Need do Setup
[INFO]: 2022-03-03 02:28:29 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-03-03 02:28:29 - Try Start Server At Port 19035
[INFO]: 2022-03-03 02:30:21 - RunAtStartup: false, so will not Run At Startup, wait 6h to Download
[INFO]: 2022-03-03 02:30:21 - CronHelper Start...
[INFO]: 2022-03-03 02:30:21 - Next Sub Scan Will Process After 6h

## 你的问题弄重现嘛？

一直如此

## 你期望的结果

请问一下如何解决？是我docker部署有问题吗？

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs

[INFO]: 2022-03-03 02:39:14 - ChineseSubFinder Version: v0.20.10
[INFO]: 2022-03-03 02:39:14 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-03-03 02:39:14 - Try Start Server At Port 19035
[INFO]: 2022-03-03 02:39:14 - Setup is Done
[INFO]: 2022-03-03 02:39:14 - RunAtStartup: false, so will not Run At Startup, wait 6h to Download
[INFO]: 2022-03-03 02:39:14 - CronHelper Start...
[INFO]: 2022-03-03 02:39:14 - Next Sub Scan Will Process After 6h
[INFO]: 2022-03-03 02:40:03 - CronHelper.Stop() Done.
[INFO]: 2022-03-03 02:43:22 - ChineseSubFinder Version: v0.20.10
[INFO]: 2022-03-03 02:43:22 - Need do Setup
[INFO]: 2022-03-03 02:43:22 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-03-03 02:43:22 - Try Start Server At Port 19035
[INFO]: 2022-03-03 02:45:48 - RunAtStartup: false, so will not Run At Startup, wait 6h to Download
[INFO]: 2022-03-03 02:45:48 - CronHelper Start...
[INFO]: 2022-03-03 02:45:48 - Next Sub Scan Will Process After 6h

**Comment by allanpk716** [comment]
#217
