### ISSUE TITLE
浏览器留下了很多临时文件？占用较大空间

### ISSUE THREAD

**Issue by PQ0000** [allanpk716/ChineseSubFinder#239]
v0.20.10 最新版本 发现磁盘很快就满了 后来查找了一下 发现是一些字幕搜索后浏览器留下的一些东西吧  现在已经6个g了 开了一个月吧  
会自动删除吗？
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod# du -h --max-depth=1
6.3G    ./user-data
4.0K    ./downloads
6.3G    .
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod# cd user-data/
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod/user-data# ls
0163a172bb0b0139  2b0dae10092adde4  58ff03349962382c  8b064ec5d104c6bd  bfee190895301581
0417b759aebc0540  2b9ea5efc68f7626  59168a70a662af5b  8b48ab8ee88a9448  c100f9c5544972cf
042b0b3c1b0344c3  2bbba444a74f0534  5974773881b7f95e  8c5f2535a3e7f354  c102d8a0dd454ca0
04f5a836bf166587  2dea2ef586d5c096  5998e3bf415d34c8  8cec43bf76af5408  c16bbdd9707e5e3a
050e1c3de524b75c  2e79e8fe3e64a28b  5a577655884e5d42  8ee380fde376cf89  c26915910881187d
05b749c31fff7219  2ecdc7dfa1fa6a6d  5b1640e9a03845f4  8f1e6d388d6e40c0  c32daa4bace5f28a
06317320e0f619d9  2efb109f3a2b99f8  5c5fc62b0f74b72c  8f6ecd185968d054  c336142ac2c17e67
0638a8ef0db77e6a  2f41f50e43c6cc0c  5db34fb4e7e4d289  8f76bd56e2aecaf3  c3472e5c1948e590
06aa347e2e258e1a  2ff42b89775b1eb3  5e6ec28354f61d0b  8fee41868bd7345c  c3b5ea50586c6bb1
0727334f0b006cf2  305d4cd031381a3a  5eaf04b5464713ba  91650c6578a3e102  c424f8431659078d
0992aad67d1efd8d  310c2c3bff5a4709  5eb481fb436ebea6  9250fbd4907e9e1a  c59ed1aaf44ee99a
09da9a05fd15817a  31ae3fb5e36bfdfe  5f827d1bf9e5c28b  9345822ce1117809  c627ac63b834ad55
0b0b6740da78355b  32e4de7132cde591  5fc82effd16d9bd7  93e414856dd32d91  c7d215de27ad6c36
0c3b0ea0ee51c8ba  3599e62bb3e0624a  608802a6a3ef23aa  9457c49d4b506cec  c8a30fcf399bd280
0d11fbf77ae12891  36042e1b437691a9  61a0f185ed652833  957a2fcff5da560a  c906ea6d6e516b7f
0d76898b6d393186  364ce7f8aaab80d8  61eca052108a6f19  963cc4334aaa317b  c93977a814c6cc97
0e9a69a9656da8a3  371842a9c1f1028b  61f1a43f8e74900c  9887988a913c39c8  c95add2e23be4476
0f9d86aa26e7dc1f  380f8f597fcdd1f2  61f6464f5aedf6de  9b02f2fd524d3c01  caa927f2ec1c623b
102a0f69972f2a7a  381fb5bdcd0f0db0  6379833f2e405cd5  9b1d2779346a3c8d  cac8057fa162e7dd
1045b0b5db32bf88  3a0cb02916deb496  657ea43d17ba7c99  9d04872c52179285  cad0ba1fca04aab9
1073abcdd8f66dbb  3acb22b662f25b3a  6646d785f9a2e1d9  9e2fc71561de1315  cc8f661cc9d653df
109601c191b87ff5  3b36a39cc6e9f775  670864283109d325  9ed2f0dfc416ce6d  cd8e804328aaa0aa
10d19c4c0586f167  3b9803131e69c134  67597342c4422735  9f9b18db074bcd0e  cdee5a4d464fbc82
10fc11969d3bc1d9  3bc6550b0c04aa93  676e8d66b41892a8  9fcfce3bd09e9027  cf62a5e5ff8e50d6
118da0303b2c27dd  3c22720b1063a71d  68a4060526f207d8  a1cbabfafa964a90  cf8e88e93e3a4fd4
11c3aca5a35b373d  3d865f5809b914ff  69680b5eb6ee7e88  a212d92f57259172  cf96decae1a48b0f
1318aeab109b1ec9  3dc9ea6103c15fc4  697efd7129052488  a28934ea525e1b67  d0e38735035e90cc
13415c0ef95f9128  3eece42e149d7249  6a6bf1d4aa7101d6  a2d68bcdb7c2d663  d17c002bdae231df
13dde7b41702ee5c  40dcb0f89539f741  6ab93e6bcd1b51cf  a453c07ec85ee477  d1a77405d72b5257
14dd479802c097b6  4290104afe600322  6b660a477651f266  a583271f11bf5f76  d38d1fc504cb3cbf
14f17778b624d255  446d970a76b362d9  6bc44b9e89abfccd  a68910a35ca0a77f  d3c141bad713fcee
15daabc1943faf46  45764c390dfa9aa9  6c4892894f180960  a7381c0a744557e3  d71f7c3096c9d58b
164df178aca21660  4721713914f81d1d  6c5682ae6371bd87  a7443bd7d323d4f2  d73eaf8edffa8747
174f9eaadf606894  4775a550ce8f5147  6c5dcf7c0bce56c8  a993b8e98abfb69c  d79404b5c6103fde
17dac86749f6a50f  47d23dce68495521  6c617dfff579bf0d  ab1f6c9507ffc66d  d7a54228db061e95
1865dbda2576207b  4873f79fc08c25a6  6d61faa654e62a05  ab4bb05ae81e9684  d7c6c41287fae6b8
191135df9d7da88e  49b36e1c1bea0c79  6dc7a024a42d3b73  ac3e7a18b8e9679f  d7f46526c05d6af0
195011d3a3b07e50  4a5472ad57727017  6dfcfac5e99e7a49  acaac26e57497d78  db40be8dba93d555
1a00f298ba4bd7b8  4a91b65ab0b72e54  6e8470f5e8bc160c  aee9a9540156a69f  dcd4bfe1f1006d65
1cef78a689dc6ed2  4ae59280d065553d  6f55d38f1c5d02c5  afa9e45c84b26e71  decfeefcb16412ef
1eb1197d8b3adb55  4b0abe5729f6e2a1  6ffc1a3736cd9935  b0dd8b3ec0a6f149  e0b4a3ae7483cc85
1f28149ad988d5ae  4b29092f6f634b55  70f1d10fff542eca  b1372b3be66c812c  e18359e644e47b7f
1f3792faae97422e  4b3af8b6197efd6a  7205d757cf7dd145  b271537e293241c8  e1dc299716d779a1
1f3b2714efa46c4a  4b69ba8af0461e86  746270fcdaa32408  b35cd1bb6f7f2746  e334b4c6a3a3d473
1f57564b1f30b08f  4bcad6ac1f76112a  74648464a631d2a6  b45cb6b1700bdfb6  e3823dfe256205c6
2001804c2c229584  4d979e786cf20c2d  7675db5242fac7e8  b6f2bdeef159c98b  e531d8218a2622e3
20803363190f159f  4e0dbf8ed9ee28d0  7682f73d91234a17  b80283de47c192c2  e78a1094b99b66fa
21b367b6c10139bf  4e897bc33b5f4692  768cebfe6adcfdfb  b82385cf50e60ee8  e7918511b90d0a92
21c042d41cb68df7  4eed2a642262432a  76cae1a1f87992b3  b887bd7c7acbc978  e803f40b3b797a15
220680ee57e220fd  4fbdb57c8c41c294  7736c497b7d147ec  b8af8c2cff69cf7d  eb845355dd93e8ea
22d955f6c3cc30da  508b042b8709c7f6  79065d82e46d98b7  b8b460cd76c6c916  ebd478ea2a7c7108
24961f371eab4683  50e51a0f09cc8cd3  79a03b3dd25e0f41  b8e671042ef243a2  ebf762958c39e16e
2531bf3de281b451  52aed4d8ebd0e38e  7b577cf1f246bb32  b906ce1a1eeafe88  ec4f83a44b4d7a11
2548c097717ef718  52b48e4223628d48  7ba86d37849e64e8  b975c01a9c86ef83  edc27aaf4b4ee91d
259adca3c2ffc010  52d04654323af48a  7c3d45abd2f659d1  b984f58c6101b9bf  ee3361213aaec6f7
2616c430a659d443  52d0ee72ba4fc523  7e951b8a47688878  ba3b0c9ec550d2df  ef935d6d376acdaa
263089fd968924fc  52d4df521447878e  7eae1622861b0cee  baa83f3ee22f1517  efa17152eb0ba4e3
266800710e1c072f  5313546518b5776d  7f3a50a0f6815f6b  bacd3aee2e31a319  f0f263c5b9b54067
267b62e17f0ce46d  540ab9d46baebefa  7f8bef6a41e162cc  bc080cd1af089b3e  f12d2f677bc94073
2688b791404aa0eb  546eab1f4b89d0e9  80fef440b2e03686  bc618566ed9127c7  f642a37217cd3a21
272a35be6d1df5d0  55756660aa30f6d8  81b2c4fb10a1a2c7  bc67b0013de88fd0  fac9b027389c95c3
279cb46a2035b17b  56d8fad526f8599b  87b0175b8ba25b32  bcf659c76e53da72  fd95b6627f22851d
2959b85a11177ece  571ffd146c622b68  89c01921e0a76e2f  bf0a6c36a29ab398  fdb80e935f641087
2a69c4ff4817a5db  585185fdcbc8a033  8a3682d64a5e2670  bf70ee6e01136c9b  ff7a9d10dd6b73e9
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod/user-data# cd 58
585185fdcbc8a033/ 58ff03349962382c/ 
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod/user-data# cd 58
585185fdcbc8a033/ 58ff03349962382c/ 
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod/user-data# cd 58ff03349962382c/
root@pq:/var/lib/docker/overlay2/cb5bca0fc1559045f186a36c7e6e6544897f0e24de84ed51a5d215ee1b852861/merged/tmp/rod/user-data/58ff03349962382c# ls
 AutofillRegex            FileTypePolicies           OriginTrials
 AutofillStates           FirstPartySetsPreloaded    pnacl
 CertificateRevocation    Floc                      'Safe Browsing'
 chrome_shutdown_ms.txt   GrShaderCache              SafetyTips
 ClientSidePhishing       hyphen-data                ShaderCache
'Crowd Deny'             'Last Version'              SSLErrorAssistant
 Default                 'Local State'              'Subresource Filter'
 DesktopSharingHub        OnDeviceHeadSuggestModel   TrustTokenKeyCommitments
 DevToolsActivePort       OptimizationHints          ZxcvbnData

**Comment by allanpk716** [comment]
#238 
#231

**Comment by PQ0000** [comment]
嗯！ 辛苦了 ！
