### ISSUE TITLE
自动解压字幕文件并重命名字幕文件

### ISSUE THREAD

**Issue by Linon419** [allanpk716/ChineseSubFinder#24]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 最新

环境: docker 

## 你想要新增或者改进什么功能？

有很多剧集或者动漫在字幕库只有打包好的文件，并且解压后字幕文件与视频文件的名称也不同。所以可以增加自动解压字幕文件并对里面的文件进行重命名

## 这个功能有什么可以参考的资料吗？

https://learnku.com/articles/23434/golang-learning-notes-five-archivezip-to-achieve-compression-and-decompression
https://github.com/qwqcode/SubRenamer

**Comment by allanpk716** [comment]
你提到的这个功能是有做的，目前测试过暂时没有问题到提。以下是代码截图，以及实际使用的截图：

# 截图

具体的代码位置，可以通过打开项目的代码，查看 TODO 的列表，即可找到。downloader.go 中
![image](https://user-images.githubusercontent.com/1176000/126106094-9cc182f8-b5e2-4704-9830-94001866e967.png)

这个是一部剧集的下载好的匹配字幕
![image](https://user-images.githubusercontent.com/1176000/126105981-e7e84232-2e39-4c8e-9f29-135dad4f875f.png)

这个的下载的整季的字幕缓存
![image](https://user-images.githubusercontent.com/1176000/126106307-69b57a43-ecbe-44c0-9995-d483809e8a61.png)

这个是日志
![image](https://user-images.githubusercontent.com/1176000/126106630-20c77167-4cad-428c-b9f5-491c98c1c7b7.png)


大概想表达的是，这个就是会用整个季度的字幕包内的字幕取替换单独下载的字幕。希望有能表述清楚我的意思····

**Comment by allanpk716** [comment]
多提一句，这个功能生效没有，主要是看上传者在字幕打包的时候命名是否有 S01 这样的描述，以及压缩包内的字幕是否有 S01E01 这样的命名，否则是无法正确识别的。

还是那个问题，字幕的命名规范很重要···

**Comment by Linon419** [comment]
嗯嗯，最新的版本我看配置文件里有Anime标签，但是日志并没有遍历到Anime设置的路径，是没生效吗

**Comment by allanpk716** [comment]
> 嗯嗯，最新的版本我看配置文件里有Anime标签，但是日志并没有遍历到Anime设置的路径，是没生效吗

[关于动画字幕下载--日本](https://github.com/allanpk716/ChineseSubFinder/issues/1)  见这个讨论，日本动画有熟肉下载且很稳定。所以很可能未必会实现这个功能。
