### ISSUE TITLE
关于emby添加新的电影/电视剧后自动下载字幕的问题

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#242]
如果关联了emby，是否可以当emby添加新的电影/电视剧的时候出发CSF自动下载该资源的字幕？

**Comment by allanpk716** [comment]
得看看，看看是否有“触发点”

**Comment by Lcc1ccl** [comment]
> 

应该是有的，Emby的插件ScripterX里面就有这个触发点，目前的用法是用来触发影视入库然后运行脚本发送企业微信通知，可以检测影片类型是电影还是剧集。感觉这个入口完美契合字幕下载的时机判断，当emby检测到入库信息，csf这边就可以对此项目进行搜索动作！Cool！希望作者可以去康康，如果能早日集成就太爽啦！
![image](https://user-images.githubusercontent.com/60082605/159213273-a64b32b7-bbf0-4545-801c-9c50de1ce23f.png)

**Comment by allanpk716** [comment]
1. 好的，有空我去看看
2. 其实后续对接 emby 估计使用的接口会逐步减少，有些新的想法需要去尝试，emby 目前最必要的 API 是刷新字幕，然后是搜索最近的加入的视频。

**Comment by allanpk716** [comment]
看看项目主页的 readme ，已经有 http api 和 示例代码
