### ISSUE TITLE
parse "10.10.10.8:8096/emby/Items": first path segment in URL cannot contain colon 提示错误

### ISSUE THREAD

**Issue by ericlokz** [allanpk716/ChineseSubFinder#243]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.21
>
> 环境: docker or Window or Linux or MAC
>chinesesubfinder在群晖的docker里,emby是架设在win环境的

> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 描述一下你遇到的问题

在emby配置里,emby读取的配置无法配置,提示以下错误.

parse "10.10.10.8:8096/emby/Items": first path segment in URL cannot contain colon
--
 

<br class="Apple-interchange-newline">
</body>
</html>
## 你的问题弄重现嘛？

> 能够

**Comment by allanpk716** [comment]
#238

**Comment by ltkun** [comment]
same problem use url
http://192.168.2.53:8097

**Comment by jasonchio-cn** [comment]
> same problem use url http://192.168.2.53:8097

问题解决了吗，我的也是这个error

**Comment by mmiluy** [comment]
这个问题有解决吗？？？？？
