### ISSUE TITLE
项目本地运行失败

### ISSUE THREAD

**Issue by le0zh0u** [allanpk716/ChineseSubFinder#244]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 最新master代码
>
> 环境: MAC
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 本地编译项目，出现异常报错
<img width="685" alt="image" src="https://user-images.githubusercontent.com/4425506/158050861-d22dc1e7-7b01-4510-9cf7-7d0a608cac95.png">

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 正确启动应用

## 给出当前程序的配置文件
frontEnd部分已经根据frontend/README.md进行启动。

还有一个问题是，项目执行`go mod tidy`时出现部分依赖checksum失败，自行通过删除go.sum的方式解决，但是这个应该是一致的，所以是你们这没有上传最新的checksum吗

**Comment by allanpk716** [comment]
1. 需要截图的你 frontend 目录，确认编译出来了
2. go mod 看截图

## 图1
![image](https://user-images.githubusercontent.com/1176000/158087298-fd274c93-48af-42b8-8f94-94ee6c96eb14.png)

**Comment by le0zh0u** [comment]
你的邮件已收到。谢谢。~

**Comment by le0zh0u** [comment]
frontend相关的截图
<img width="288" alt="image" src="https://user-images.githubusercontent.com/4425506/159014558-d2981aad-d0c6-46ae-b8e5-39e9fcd495a4.png">
提示应该是 `// go:embed spa/css`这里的文件找不到

**Comment by allanpk716** [comment]
因为没有编译出来，当然就没得。看 front 内 readme 说明

**Comment by le0zh0u** [comment]
我以为运行了`npm run dev`能运行起来是已经编译完成了。没想到是需要先运行`npm run build`。
直接运行了main.go，程序可以跑起来了。
这个有开发相关的文档吗，code层面的

**Comment by allanpk716** [comment]
> 我以为运行了`npm run dev`能运行起来是已经编译完成了。没想到是需要先运行`npm run build`。 直接运行了main.go，程序可以跑起来了。 这个有开发相关的文档吗，code层面的

没有完整的文档，属于有空写两行的情况。注释应该算详尽的。

**Comment by le0zh0u** [comment]
好的。想再问下，本地成功运行后，在docker中使用的的/media和/config的目录配置会映射到哪里
