### ISSUE TITLE
目录不可以

### ISSUE THREAD

**Issue by yeysxh** [allanpk716/ChineseSubFinder#248]
> chinesesubfinder 版本: 0.21.1
>
> 环境: docker or 群晖nas
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 目录不可用，请输入正确的Emby目录；emby上未开启共享的网络文件夹，subfinder输入地址还是无效
![image](https://user-images.githubusercontent.com/101821962/158852876-f38d2ebd-fb12-4b91-8042-9342d38456bd.png)
![image](https://user-images.githubusercontent.com/101821962/158852933-3459213c-4f3a-4404-8d95-f94c041189fd.png)
![image](https://user-images.githubusercontent.com/101821962/158852997-6e4e9361-1ddb-4f20-8fa8-f52cc12c2590.png)

**Comment by allanpk716** [comment]
#238 #241

**Comment by yeysxh** [comment]
> #238 #241
重新配置容器后能识别电影，不能识别电视剧路径
![image](https://user-images.githubusercontent.com/101821962/158942764-21d91549-0ca2-42ba-b89c-d8cd4b722e9a.png)
![image](https://user-images.githubusercontent.com/101821962/158942788-24d8ea4d-b1e1-49e0-b258-056decdb45f7.png)
![image](https://user-images.githubusercontent.com/101821962/158942917-c49ebf7d-c7aa-4c1f-a332-eaa23be012e7.png)
![image](https://user-images.githubusercontent.com/101821962/158942956-c2a3a511-f1ba-44fb-a05e-5f3878a1cca6.png)
[2022-03-18 10_55_59.log](https://github.com/allanpk716/ChineseSubFinder/files/8301836/2022-03-18.10_55_59.log)

**Comment by allanpk716** [comment]
看 #241 给出 emby 信息

**Comment by yeysxh** [comment]
> 看 #241 给出 emby 信息

现在填写绝对路径还是只有电影可以，电视剧还是目录不可以用。是我没有映射对目录？
![image](https://user-images.githubusercontent.com/101821962/158960301-7c520c16-bce5-4d18-9104-336cbb7ccd8d.png)

![image](https://user-images.githubusercontent.com/101821962/158960353-d535a75d-2354-4f0a-b539-13bb1b7d532f.png)

**Comment by allanpk716** [comment]
连续剧的目录结构呢？

**Comment by yeysxh** [comment]
> 连续剧的目录结构呢？

![image](https://user-images.githubusercontent.com/101821962/159622648-4ad8eb32-702b-42d1-bf85-fa1242c86c55.png)
![image](https://user-images.githubusercontent.com/101821962/159622673-2b3f8f25-0e01-4f04-a44a-e5901474bb71.png)

**Comment by allanpk716** [comment]
https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md
