### ISSUE TITLE
能不能把不是中文的字幕当没有字幕处理

### ISSUE THREAD

**Issue by a597232887** [allanpk716/ChineseSubFinder#249]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.20.10

环境: docker

## 你想要新增或者改进什么功能？

能不能把检测是否下载字幕改成检测到中文字幕才跳过，检测到别的依然检测是否超过三个月，不超过当没有字幕处理。或者加个开关。
同时，web端“任务”那一栏的日志和进度并不能准确显示。我有927部电影，11918集电视剧。

## 这个功能有什么可以参考的资料吗？

我看日志里已经能识别出字幕语言了。

**Comment by allanpk716** [comment]
https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md

**Comment by allanpk716** [comment]
以及 see #238

**Comment by a597232887** [comment]
我的意思是，判断本地是否有字幕那里，变成是否有中文字幕。因为有一些视频它本身带了个英文字幕在文件夹里，而且是超过三个月的片，但是它有中文字幕。而这种情况会被跳过，同时也不会被人察觉，必须要播放这个视频的时候才知道是个英文字幕。比如yts下的老片，就经常会有个字幕一起下下来，这种情况就被跳过搜索中文字幕了。

**Comment by a597232887** [comment]
本地是否有字幕->是->获取时间->是否超过三个月->(否->下载)是->本地字幕是否中文->(是->跳)否->本程序是否搜索过(是->跳)->否->下载

**Comment by allanpk716** [comment]
已经判了，有问题，就合理的反馈问题，不然无法定位问题

**Comment by wmgylc** [comment]
同样有这个问题，流程图中“检测本地是否有字幕”这一栏，会把电影自带的英文字幕也判定为有字幕，这样就会直接跳过下载字幕流程，最终导致中文字幕无法下载。

附上一个日志：

Skip 功夫熊猫3 (2016) 1080p DTSHD-MA.mkv Sub Download, because movie has sub and published more than 2 years

实际上该电影只有自带的英文字幕。

**Comment by a597232887** [comment]
> 已经判了，有问题，就合理的反馈问题，不然无法定位问题

确实是判断了字幕的语言，但是并没有用这个结果做什么，依然是跳过的。然而这个片子是有中文字幕的。所以希望这个结果能发挥作用，只有非中文字幕且未搜索过不要跳过，当没有字幕处理。

还是说这里是2年而不是3个月就是它的作用？那建议内容从原内容改成“取消只有非中文字幕影片上映不超过两年才搜索字幕的限制，改为进行过一次成功的字幕搜索且无中文结果才在以后的扫描中跳过该影片”

[WARNING]: 2022-03-19 12:21:03 - IsSubHasChinese.HasChineseLang /media/许愿 - Unrated (2017)/许愿 - Unrated (2017) 1080p AAC.eng.srt not chinese sub, is 英
[INFO]: 2022-03-19 12:21:04 - Skip 许愿 - Unrated (2017) 1080p AAC.mp4 Sub Download, because movie has sub and published more than 2 years
[WARNING]: 2022-03-19 12:21:10 - IsSubHasChinese.HasChineseLang /media/诺曼人：维京传奇 (2014)/诺曼人：维京传奇 (2014) 1080p AAC.eng.srt not chinese sub, is 英
[INFO]: 2022-03-19 12:21:10 - Skip 诺曼人：维京传奇 (2014) 1080p AAC.mp4 Sub Download, because movie has sub and published more than 2 years

**Comment by allanpk716** [comment]
需要定位这个问题，反馈内容大概应该有：
1. 什么版本？
2. 完整日志。
3. 给出有问题影片的目录结构截图，包含你们提到的 xx.mp4 and xx.srt 
4. 这个 srt 是什么语言需要描述清楚
5. 最好有文件的创建时间等字段

## 截图
![image](https://user-images.githubusercontent.com/1176000/159194551-262198cc-2fe1-4f30-89d9-e1bb4da2cbda.png)

**Comment by wmgylc** [comment]
## 版本
v0.21.1 docker部署
## 完整日志
[https://github.com/wmgylc/chinesesubfinder_report/blob/main/2022-03-21%2011_38_03.log](url)
## 给出有问题影片的目录结构截图
[https://github.com/wmgylc/chinesesubfinder_report/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-03-21%20194723.png](url)
另外我重新确认了一下，我的问题应该是:
**无论有没有提供字幕，无论字幕的形式是什么形式，电影原声是什么语言，结果都统一被判定成字幕已经下载并跳过**。
## 这个 srt 是什么语言需要描述清楚
因为重新确认了问题，所以跟字幕形式和类型无关了，都是统一被跳过了。
## 最好有文件的创建时间等字段
跨度比较大，有最近创建的，也有好几年前的，因为重新整理了文件，所以创建时间丢失了。

谢谢大佬。

**Comment by allanpk716** [comment]
> ## 版本
> v0.21.1 docker部署
> 
> ## 完整日志
> [https://github.com/wmgylc/chinesesubfinder_report/blob/main/2022-03-21%2011_38_03.log](url)
> 
> ## 给出有问题影片的目录结构截图
> [https://github.com/wmgylc/chinesesubfinder_report/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-03-21%20194723.png](url) 另外我重新确认了一下，我的问题应该是: **无论有没有提供字幕，无论字幕的形式是什么形式，电影原声是什么语言，结果都统一被判定成字幕已经下载并跳过**。
> 
> ## 这个 srt 是什么语言需要描述清楚
> 因为重新确认了问题，所以跟字幕形式和类型无关了，都是统一被跳过了。
> 
> ## 最好有文件的创建时间等字段
> 跨度比较大，有最近创建的，也有好几年前的，因为重新整理了文件，所以创建时间丢失了。
> 
> 谢谢大佬。

你上传的两个文件都无法下载，你直接拖进去回复的窗体就能自动上传的。

**Comment by wmgylc** [comment]
## 版本
v0.21.1 docker部署
重装无效

## 完整日志
[log.txt](https://github.com/allanpk716/ChineseSubFinder/files/8355805/log.txt)

## 给出有问题影片的目录结构截图
![屏幕截图 2022-03-21 194723](https://user-images.githubusercontent.com/19822246/160247319-2692807b-83c5-44b3-a913-91008f42aa2b.png)
另外我重新确认了一下，我的问题应该是:
无论有没有外挂字幕，电影是否内置字幕，字幕的形式是什么形式，电影原声是什么语言，所有情况都统一被判定成字幕已经下载并跳过。

## 这个 srt 是什么语言需要描述清楚
因为重新确认了问题，所以跟字幕形式和类型无关了，都是统一被跳过了。

## 最好有文件的创建时间等字段
跨度比较大，有最近创建的，也有好几年前的，因为重新整理了文件，所以创建时间丢失了。

谢谢大佬。

**Comment by allanpk716** [comment]
去看电影目录格式要求文档

**Comment by wmgylc** [comment]
> 去看电影目录格式要求文档

好吧，的确怀疑是这个原因，但是主要是现在我都是使用jellyfin自动刮的，而jellyfin似乎不会自动整理文件，再使用tmm的话就太麻烦了。总之谢谢大佬了

**Comment by allanpk716** [comment]
> 



> > 去看电影目录格式要求文档
> 
> 好吧，的确怀疑是这个原因，但是主要是现在我都是使用jellyfin自动刮的，而jellyfin似乎不会自动整理文件，再使用tmm的话就太麻烦了。总之谢谢大佬了

其实没有你想象的麻烦，TMM 效果极佳，后续只要使用 jellyfin 手动刷新你的媒体库即可，就是挂机，找个通宵就好了
