### ISSUE TITLE
zmk 对剧集优先使用imdb查询

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#253]
最近遇到有剧集被下载了另一个不相干剧集的字幕, 于是简单调查了一番.
目前使用 剧集名+“第x季” 关键词来查询zmk, 但是似乎不够准确:
https://zmk.pw/search?q=Minx+%E7%AC%AC%E4%B8%80%E5%AD%A3 返回了另一个剧集, 正确的应该是 https://zmk.pw/subs/60982.html

如果使用imdb查询的话, 第一季可以直接用series的idmb id, 后面的季需要使用每季第一集对应的imdb

**Comment by allanpk716** [comment]
IMDB 仅仅是使用到连续剧最上一级的 ID 去搜索的，每一季、每一集的 IMDB ID 搜索还没有测试过是否可行

**Comment by wloot** [comment]
似乎只有电影才会使用imdb号搜索? https://github.com/allanpk716/ChineseSubFinder/blob/master/internal/logic/sub_supplier/zimuku/zimuku.go#L90

每季第一集的imdb id是豆瓣的规范, 目前看来zmk就是用的豆瓣的元数据

**Comment by allanpk716** [comment]
> 似乎只有电影才会使用imdb号搜索? https://github.com/allanpk716/ChineseSubFinder/blob/master/internal/logic/sub_supplier/zimuku/zimuku.go#L90
> 
> 每季第一集的imdb id是豆瓣的规范, 目前看来zmk就是用的豆瓣的元数据

那估计是当时实现的时候发现 IMDB 在搜索连续剧的时候效果比较差所以就暂时不实现了

**Comment by wloot** [comment]
> > 似乎只有电影才会使用imdb号搜索? https://github.com/allanpk716/ChineseSubFinder/blob/master/internal/logic/sub_supplier/zimuku/zimuku.go#L90
> > 每季第一集的imdb id是豆瓣的规范, 目前看来zmk就是用的豆瓣的元数据
> 
> 那估计是当时实现的时候发现 IMDB 在搜索连续剧的时候效果比较差所以就暂时不实现了

用imdb可能不是所有剧集都支持, 但是至少准确度是最高的, 基本不会出错. 能否考虑支持一下吗

**Comment by allanpk716** [comment]
> > > 似乎只有电影才会使用imdb号搜索? https://github.com/allanpk716/ChineseSubFinder/blob/master/internal/logic/sub_supplier/zimuku/zimuku.go#L90
> > > 每季第一集的imdb id是豆瓣的规范, 目前看来zmk就是用的豆瓣的元数据
> > 
> > 
> > 那估计是当时实现的时候发现 IMDB 在搜索连续剧的时候效果比较差所以就暂时不实现了
> 
> 用imdb可能不是所有剧集都支持, 但是至少准确度是最高的, 基本不会出错. 能否考虑支持一下吗

会支持的，不过这个需要根据 zimuku 和  subhd 的情况，测试一段时间，看效果如何。

**Comment by wloot** [comment]
> 网站直接使用 IMDB 搜索剧集每一季效果不佳
> 
> ## 图1
> ![image](https://user-images.githubusercontent.com/1176000/165880449-6b5ef61f-1ec6-4f0a-83e8-c2d5f2959df1.png)
> 
> ## 图2
> ![image](https://user-images.githubusercontent.com/1176000/165880466-7c960389-a0c5-4452-b1dc-22f4c1bd32f3.png)
> 
> ## 图3
> ![image](https://user-images.githubusercontent.com/1176000/165880475-3a8799cd-93bb-4591-850e-da0ea17f4cdb.png)

imdb每集有单独的编号, zmk使用的是每季的第一集作为这一季的imdb编号.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/30223095/165880771-1b81e509-fe02-49b8-9c51-ee59a8e52e34.png">
<img width="859" alt="image" src="https://user-images.githubusercontent.com/30223095/165880789-63816e9d-7a67-4700-b7f3-39b9ce49cbfa.png">

**Comment by wloot** [comment]
> 每一集的 imdb id 我去看看是否能够稳定获取到，之前观察我这里的情况是未必能够获取到

请问有希望实现吗?

**Comment by allanpk716** [comment]
只是搜索逻辑多加一次而已，都是按关键词搜索的，没差别。问题是我这里看到每一集的 nfo 没得 IMDB 信息啊，你是怎么设置削刮器做每一集削刮的？

**Comment by wloot** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/30223095/167520967-caf9014b-2bc6-4166-b632-a2690e6c7c09.png">
emby的话应该有吧

**Comment by wloot** [comment]
媒体库的设置里没有, 但实际有获取imdb数据

**Comment by allanpk716** [comment]
我是正常使用 sonarr 提交给 qbit 下载，然后 Emby 自己处理，然后本程序是读取这一集的 nfo 文件，我没看到。你说的 Emby API 是可以获取到的。我是想没有使用 Emby 这类媒体工具的也能用上这个搜索逻辑。

**Comment by wloot** [comment]
emby api是可以读, nfo文件里也有的

**Comment by allanpk716** [comment]
我去看看 Emby 的设置，我这里 nfo 没有。现在的下载逻辑是传入视频的路径来做的，附带的所有信息都是当时解析，不太想再绕一圈去 emby api 拿（一是耦合度高，二是因为本来就是前置拿过，且传入的查询函数的接口不太想改）

## nfo
![image](https://user-images.githubusercontent.com/1176000/167524892-9cc80b55-9d9e-4d86-bee1-ed632ae16fd7.png)

**Comment by wloot** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/30223095/167525089-b7577326-ccfc-4940-99a7-54c85baf0c8b.png">
估计是这个设置

**Comment by allanpk716** [comment]
我看了，之前就已经设置了，没得用，而且你勾选的不是 IMDB Info，是 TMDB，你还有其他削刮器工作嘛？

**Comment by wloot** [comment]
我记得是emby不会直接去imdb搜索，而是从tvdb api返回imdb id的信息，emby直接保存的。

**Comment by wloot** [comment]
> 

你的nfo文件好像跟我的很多都不一样, 是有用其他外部挂削嘛

**Comment by allanpk716** [comment]
没有啊，我还专门找了《绝命律师》最新一季来看的，直接 sonarr 订阅自动下载，然后 Emby 去做削刮。搜索关键词这个梗我想一下怎么做，之前是读取到什么名称就用什么去搜索，估计得转换成中文译名，但是估计也由风险，毕竟国内翻译名称有点怪，而且会有几种（有些剧集）。IMDB API 可以获取到其他译名，我看看效果怎么样先。如果不行，我再看豆瓣的，主要是要主流的中文译名。

**Comment by wloot** [comment]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/30223095/167526942-df6db3b2-d3bd-45a5-8fa2-517400382a42.png">
可能是启用了sonarr的这个metadata?

**Comment by allanpk716** [comment]
你意思是 sonarr 启用了这个，所以 Emby 就不继续写入了？

我看我是开启的

## 截图
![image](https://user-images.githubusercontent.com/1176000/167575122-b33b7e61-1bf8-45ae-9a1c-10a35dce8a7b.png)

**Comment by wloot** [comment]
是的，emby会读取sonarr的nfo文件，就不会自己再挂削了

Chin allan ***@***.***> 于 2022年5月10日周二 下午3:40写道：

**Comment by allanpk716** [comment]
我先关闭看看，如果能下载到 imdb info 的信息，我就可以本地测试这个功能

**Comment by allanpk716** [comment]
这个功能改起来不难，但是有个细节啊。如果你想要开启这个功能，那么就代表，subhd 使用 imdb 和 名称搜索也是有问题的字幕，且会下载下来，那么就会出现，假如你**没有开启**保存多个字幕的功能（这个功能最好是使用 Emby 的字幕命名规则），如果 zimuku 先下载了字幕（假设是对的），然后才到 subhd（假设是错误的），最后进行 best sub 选择的评分阶段，subhd 的权重更高，那么你的 zimuku 的字幕就被覆盖了，最终还是不行啊···

是不是我得再将要出现的 Web 视频列表界面，给你个选项，这个电影、连续剧都只走那些字幕源下载的逻辑，这样就能排除掉你觉得不合适的字幕源，就没得覆盖的问题了。

**Comment by wloot** [comment]
不如开放各个字幕站点的优先级，让用户自己排序，不知道实现起来可不可行

Chin allan ***@***.***> 于 2022年5月12日周四 上午9:29写道：

**Comment by allanpk716** [comment]
可以，但是我依然是建议开启多字幕保存···以及配合 Emby 字幕命名格式。不然都自动下载的，如果字幕的格式一样的，多字幕也依然会被覆盖的。

我个人是宁愿一个视频对应多个字幕，大不了看的时候选择几次就能找到一个最佳的，总比只有一个字幕（所以才说 Emby 字幕命名有它的优势）看了不对，还得想办法去触发下载任务。

我还是考虑给你们自己选择某个连续剧或者电影，设置只用那些字幕源下载吧，大多数的下载情况应该都不会有问题，有问题的再用这个功能自己设置下，我觉得应该还算能接受吧。

**Comment by allanpk716** [comment]
我设置了 sonarr 还得没发现 Emby 会给每一集下载 IMDB ID 信息，不过我把这个搜索的逻辑加了，本地没有测试，感觉问题不大（都是关键词搜索），如果你发现搜索的时候提示获取的 IMDB id 不对，你反馈下对应这一季第一集的 nfo 文件给我，这个文件花样太多，可能我没有覆盖到的话是读取不到 IMDB ID 的。

v0.26-DockerBeta4 之后才会有这个功能

**Comment by allanpk716** [comment]
已经支持了，不过···zimuku 应该不会支持下载了，后续会在共享字幕中补全这个部分的字幕下载
