### ISSUE TITLE
新版本CPU爆炸

### ISSUE THREAD

**Issue by xxzj990** [allanpk716/ChineseSubFinder#255]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.21.1
>
> 环境: docker or Linux（unraid）
>

## 你遇到什么问题了？

> 启动后，过一段时间，具体多长时间不清楚，CPU就会一直处于占满状态，我是12核的CPU，全部占满！上一个版本也有这个问题，就升级到了v0.21.1，问题依旧存在。

## 你的问题弄重现嘛？

> 能够重新，在我的机器上是必现问题

## 你期望的结果

> 正常运行，不要占那么多CPU

## 给出当前程序的配置文件

```json
{
    "user_info": {
    },
    "common_settings": {
        "scan_interval": "6h",
        "threads": 1,
        "run_scan_at_start_up": false,
        "movie_paths": [
            "/media/movies"
        ],
        "series_paths": [
            "/media/tv"
        ]
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_http_proxy": false,
            "http_proxy_address": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 1,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": true,
        "topic": 1
    },
    "emby_settings": {
        "enable": false,
        "address_url": "",
        "api_key": "",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/movies": ""
        },
        "series_paths_mapping": {
            "/media/tv": ""
        }
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 120,
        "min_offset": 0.1
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 端口 19035:19035
> 路径 /mnt/user/appdata/chinesesubfinder:/config
> 路径 /mnt/user/download/media/movies/:/media/movies/data1
> 路径 /mnt/user/download/media/movies2/:/media/movies/data2
> 路径 /mnt/user/download/media/tv/:/media/tv/data1
> 变量 PUID=99
> 变量 GUID=100

## 请给出当次问题的完整日志

[ChineseSubFinder.log](https://github.com/allanpk716/ChineseSubFinder/files/8321671/ChineseSubFinder.log)

**Comment by allanpk716** [comment]
你需要进入 docker 输出进程相关信息

**Comment by xxzj990** [comment]
抱歉，不知道怎么搞了一下，现在服务会报错：

> (EE)
> Fatal server error:
> 
> (EE) Server is already active for display 99
> If this server is no longer running, remove /tmp/.X99-lock
> and start again.
> (EE)

我今天重新部署一套再试试

**Comment by xxzj990** [comment]
重新部署了一套没有问题了，我后续再观察，感谢大佬的回复！

**Comment by xxzj990** [comment]
用了几天问题又出来了，容器的命令行进去后使用top会卡死所以在unraid下截了top命了，见如下截图：

容器里top卡死-
<img width="203" alt="截屏2022-03-28 下午8 14 20" src="https://user-images.githubusercontent.com/5134154/160395907-42b529fe-2aab-4de2-b861-4b6e508955b3.png">

unraid top-
<img width="900" alt="截屏2022-03-28 下午8 13 46" src="https://user-images.githubusercontent.com/5134154/160396168-d2ec4091-71ca-4952-8f22-d2e6db4dd18b.png">

unraid cpu占用-
<img width="745" alt="截屏2022-03-28 下午8 13 21" src="https://user-images.githubusercontent.com/5134154/160396312-047e66fd-d746-4a95-93df-d55ef15d0dea.png">

**Comment by xxzj990** [comment]
我看ChineseSubFinder的容器里会用到chrome，应该是这个导致的

**Comment by allanpk716** [comment]
你的设备的性能如何（硬件配置和资源给docker这个容器的分配）？方便给出来嘛？

**Comment by xxzj990** [comment]
> 

给ChineseSubFinder容器没有任何限制，CPU是i5-10600T 12核的，内存是32GB，512GB的SSD

**Comment by allanpk716** [comment]
> 给ChineseSubFinder容器没有任何限制，CPU是i5-10600T 12核的，内存是32GB，512GB的SSD

1. chrome 虽然占资源但是不至于这么高才对
2. 真正占资源的是 ffmpeg 的操作

我是群晖 918+ 比你这个弱多了···稳的很啊

**Comment by xxzj990** [comment]
> > 给ChineseSubFinder容器没有任何限制，CPU是i5-10600T 12核的，内存是32GB，512GB的SSD
> 
> 1. chrome 虽然占资源但是不至于这么高才对
> 2. 真正占资源的是 ffmpeg 的操作
> 
> 我是群晖 918+ 比你这个弱多了···稳的很啊

我也很郁闷，可能和unraid有关系

**Comment by SteinX** [comment]
我也遇到了同样的问题，我是部署在 DSM 7.0 的 docker 上的，我没留下确切的进程日志，但我怀疑是并发数过高了，我昨天看了下 chinesesubfinder 的后台日志，提到 queue 大概的有 200～300 个，不知道这个是不是并发数。然后当时 chrome 进程大概不下十来个吧。
我现在又卡死了，没办法到后台 dump 日志下来了.....

**Comment by allanpk716** [comment]
已经强制线程为1了，除非手动修改配置。怀疑是 #271  提到的问题，不知道你们是否跟他的使用方式一样?

**Comment by SteinX** [comment]
> 已经强制线程为1了，除非手动修改配置。怀疑是 #271 提到的问题，不知道你们是否跟他的使用方式一样?

嗯，我这边配置也是显示线程为 1。我这边就是正常使用而已，没有用什么高级用法才是......

**Comment by allanpk716** [comment]
因为 zimuku 也使用了 chrome ，所以这个用量估计明显增加了，我看了下代码还能再少点资源，稍等。

**Comment by viqbgrg** [comment]
我这边一开始就几个chrome进程,跑着跑着就变成了20+个进程,而且还在增长

**Comment by SteinX** [comment]
我最多可以有接近 500 的 chrome 进程，CPU 峰值 1000%，内存占用十几个G。但愿只是初始化比较猛吧，后面增量扫描不知道是不是会好很多

<img width="1777" alt="截屏2022-04-01 00 53 11" src="https://user-images.githubusercontent.com/3668417/161361578-8c89ab77-7394-48dc-93df-fbe861dd5331.png">

**Comment by allanpk716** [comment]
难道并发控制在你们那都失效了？你们的下载日志呢，里面会详细记录下载情况的

**Comment by SteinX** [comment]
[2022-04-01 09_45_51.log](https://github.com/allanpk716/ChineseSubFinder/files/8401623/2022-04-01.09_45_51.log)
[2022-04-01 15_45_50.log](https://github.com/allanpk716/ChineseSubFinder/files/8401624/2022-04-01.15_45_50.log)
[2022-04-02 01_47_29.log](https://github.com/allanpk716/ChineseSubFinder/files/8401625/2022-04-02.01_47_29.log)

**Comment by wloot** [comment]
> 难道并发控制在你们那都失效了？你们的下载日志呢，里面会详细记录下载情况的
> 
> 推送了 v0.24 你们再试试，该释放的地方都看了一遍，如果这样都不行没啥好办法了。不行我就只能每次下载一个视频，就强制结束一次 chrome 。

可以能是, zimuku在下载页面加了一个ip检测, 而当前如果没有新下载就会一直等待, 造成问题, 所以加个超时比较好 https://github.com/wloot/ChineseSubFinder/commit/9937fbf56351a3124aa58c819d6698580d608cad#diff-858a1a26e7f1022d449c8f81b0f7c1e74161102053e2d5dfce4814820dd42f1cR610

**Comment by allanpk716** [comment]
> 可以能是, zimuku在下载页面加了一个ip检测, 而当前如果没有新下载就会一直等待, 造成问题, 所以加个超时比较好 [wloot@9937fbf#diff-858a1a26e7f1022d449c8f81b0f7c1e74161102053e2d5dfce4814820dd42f1cR610](https://github.com/wloot/ChineseSubFinder/commit/9937fbf56351a3124aa58c819d6698580d608cad#diff-858a1a26e7f1022d449c8f81b0f7c1e74161102053e2d5dfce4814820dd42f1cR610)

嗯，加这个检查的时候大意了，我改改。

**Comment by xxzj990** [comment]
> > 可以能是, zimuku在下载页面加了一个ip检测, 而当前如果没有新下载就会一直等待, 造成问题, 所以加个超时比较好 [wloot@9937fbf#diff-858a1a26e7f1022d449c8f81b0f7c1e74161102053e2d5dfce4814820dd42f1cR610](https://github.com/wloot/ChineseSubFinder/commit/9937fbf56351a3124aa58c819d6698580d608cad#diff-858a1a26e7f1022d449c8f81b0f7c1e74161102053e2d5dfce4814820dd42f1cR610)
> 
> 嗯，加这个检查的时候大意了，我改改。

大佬，你看一下是不是可以用这个东西替换chrome：
https://github.com/FlareSolverr/FlareSolverr

**Comment by allanpk716** [comment]
这个在爬取动漫花园的时候测试过，效果不佳，还不如放过自己，直接上浏览器模拟点击去做。这也就是为什么我喜欢 go-rod

**Comment by xxzj990** [comment]
> 这个在爬取动漫花园的时候测试过，效果不佳，还不如放过自己，直接上浏览器模拟点击去做。这也就是为什么我喜欢 go-rod

哦，明白了
