### ISSUE TITLE
能不能提供一个HTTP API

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#256]
可以传入参数（例如path）去刷新/下载某个目录下的电影/电视剧的字幕
这样可以自己在emby手动配置反过来调用csf
也可以在qb/tr中配置下载完成后自动调用csf
也可以配合其他的应用来使用
可以提供webhook，http调用即可

**Comment by allanpk716** [comment]
还需要重构一版才能够把子任务的概念做出来，在这之前无法提供

**Comment by jasonhorga** [comment]
> 还需要重构一版才能够把子任务的概念做出来，在这之前无法提供

收到，期待

**Comment by allanpk716** [comment]
see #318 的讨论，有啥接口问题就提，我也是第一次整这个，也没用过别的下载器的这类功能，以及我也没用过类似这种触发的方法去做这类任务。

**Comment by allanpk716** [comment]
这个已经有了，具体见主页 readme 中的 http api 文档和示例代码
