### ISSUE TITLE
can not find Ep Aired Time 无法下载对应字幕

### ISSUE THREAD

**Issue by 907739769** [allanpk716/ChineseSubFinder#258]
[ERROR]: 2022-03-23 03:02:39 - model.GetImdbInfo4OneSeriesEpisode /media/TV Shows/Star Trek - Discovery/Season 3/Star Trek - Discovery - S03E02 - Far from Home Bluray-1080p Remux.mkv can not find Ep Aired Time

出现如上日志，字幕就不会进行下载。请问有什么解决办法吗？

**Comment by allanpk716** [comment]
削刮器要能把连续剧的内容都整理好，比如每一集得有 nfo

**Comment by 907739769** [comment]
下载字幕的时候nfo文件还没有生成导致的，后面下载成功了。
