### ISSUE TITLE
爆 docker image

### ISSUE THREAD

**Issue by iamsweet** [allanpk716/ChineseSubFinder#259]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.21.1
>
> 环境: docker on unraid
>
开始 chinesesubfinder  任务之后， docker image 的体积就以肉眼可见的速度增加，几分钟增加1%，一直到 80% unraid报警，到90%的时候我停掉了任务，并停掉了 chinesesubfinder ，这时 docker image 体积不再增加。移除 chinesesubfinder 之后，docker image 体积恢复正常。本身我的 docker image 设置为40G，平常只占用20%而已。不知道是我的媒体库太大了还是别的原因。

**Comment by allanpk716** [comment]
#238

**Comment by iamsweet** [comment]
知道什么原因了， cache 目录按照前面几个版本设置成 /app/SubFixCache 就会这样，应该是从0.20.0开始改的，我第一次装是装的0.20.1，但是安装参考了一个老版的教程。
