### ISSUE TITLE
文件夹名称含中文就会被认为是中文电影

### ISSUE THREAD

**Issue by mhqschen** [allanpk716/ChineseSubFinder#26]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.11.1

环境: docker 

## 你遇到什么问题了？

文件夹名称含中文就被视为了中国电影然后被SkipChineseMovie。
从log看貌似这样就不会读取根目录下的nfo文件，转而直接用文件名搜索？

## 你的问题弄重现嘛？

能够重新

## 可以提供遇到问题时候，电影、连续剧的信息吗？

视频的目录: /Movie/夏日友晴天 Luca (2021)

视频的信息: Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.mkv

## 出错的日志信息可以复制一些出来吗？

[INFO]: 2021-07-19 15:31:53 - MovieFolder: /media/Movie

[INFO]: 2021-07-19 15:31:53 - SeriesFolder: /media/TV

[INFO]: 2021-07-19 15:31:59 - First Time Download Start

[INFO]: 2021-07-19 15:31:59 - Download One Started...

[INFO]: 2021-07-19 15:31:59 - Download Movie Sub Started...

[WARNING]: 2021-07-19 15:31:59 - SkipChineseMovie /media/Movie/夏日友晴天 Luca (2021)/Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.mkv can not find IMDB Id

[ERROR]: 2021-07-19 15:31:59 - MovieNeedDlSub.GetImdbInfo4Movie can not find IMDB Id

[INFO]: 2021-07-19 15:31:59 - DlSub Start /media/Movie/夏日友晴天 Luca (2021)/Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.mkv

**Comment by allanpk716** [comment]
> [WARNING]: 2021-07-19 15:31:59 - SkipChineseMovie /media/Movie/夏日友晴天 Luca (2021)/Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.mkv can not find IMDB Id
> 
> [ERROR]: 2021-07-19 15:31:59 - MovieNeedDlSub.GetImdbInfo4Movie can not find IMDB Id
> 
> [INFO]: 2021-07-19 15:31:59 - DlSub Start /media/Movie/夏日友晴天 Luca (2021)/Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.mkv


WARNING 这里的意思是在 SkipChineseMovie  这个函数中，需要用到  IMDB Id 去 IMDB 网站去查询这个视频是什么语言的。不是因为是中文而跳过。

ERROR 这里保存，应该是你的这个视频文件没有经过削刮器处理，所以无法使用 IMDB ID 去走后续的逻辑，但是依然可以用文件名去查询字幕的。

[INFO] 往后应该有对应的搜索记录，因为是用文件名去搜索的，这个视频的文件命名是否能够被提取出正确的视频名称，关系着是否能够找到字幕。建议削刮器处理一下。

稍等，我补一个文档说明一下 IMDB ID 是从本地哪里读取到的。

**Comment by mhqschen** [comment]
![image](https://user-images.githubusercontent.com/9138710/126128392-84f30d3b-351a-420c-8b74-01ab0b8de630.png)

是有刮削过的，nfo和视频文件同名

**Comment by allanpk716** [comment]
> Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.nfo


能发一下这个文件的内容看看吗？最好发全。

**Comment by mhqschen** [comment]
> > Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.nfo
> 
> 能发一下这个文件的内容看看吗？最好发全。

nfo是Jellyfin生成的，应该和Emby一样吧。
`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movie>
  <plot>在意大利的利古里亚海岸上，一个名为路卡（Luca）的小男孩与好朋友们一起渡过难忘的夏天，过程中充满了冰淇淋、意大利面和摩托车。然而，路卡却有一个秘密：他是来自水底世界的海怪，且只要一接触到水，就会原形毕露。</plot>
  <outline />
  <lockdata>false</lockdata>
  <dateadded>2021-07-09 15:59:11</dateadded>
  <title>夏日友晴天</title>
  <originaltitle>Luca</originaltitle>
  <director>Enrico Casarosa</director>
  <writer>Jesse Andrews</writer>
  <writer>Mike Jones</writer>
  <writer>Nicolle Castro</writer>
  <writer>James Reinhart Robertson</writer>
  <credits>Jesse Andrews</credits>
  <credits>Mike Jones</credits>
  <credits>Nicolle Castro</credits>
  <credits>James Reinhart Robertson</credits>
  <rating>7.6</rating>
  <year>2021</year>
  <mpaa>PG</mpaa>
  <imdbid>tt12801262</imdbid>
  <tmdbid>508943</tmdbid>
  <premiered>2021-06-17</premiered>
  <releasedate>2021-06-17</releasedate>
  <criticrating>91</criticrating>
  <runtime>95</runtime>
  <country>United States of America</country>
  <genre>动画</genre>
  <genre>喜剧</genre>
  <genre>家庭</genre>
  <genre>奇幻</genre>
  <studio>Walt Disney Pictures</studio>
  <studio>Pixar</studio>
  <tag>italy</tag>
  <tag>monster</tag>
  <tag>secret</tag>
  <tag>friendship</tag>
  <tag>friends</tag>
  <tag>coming of age</tag>
  <tag>sea monster</tag>
  <tag>seaside town</tag>
  <tag>1950s</tag>
  <tag>water</tag>
  <tag>italian riviera</tag>
  <art>
    <poster>/data/Movie/夏日友晴天 Luca (2021)/folder.jpg</poster>
    <fanart>/data/Movie/夏日友晴天 Luca (2021)/backdrop.jpg</fanart>
  </art>
  <actor>
    <name>Jacob Tremblay</name>
    <role>Luca Paguro (voice)</role>
    <type>Actor</type>
    <sortorder>0</sortorder>
    <thumb>/config/data/metadata/People/J/Jacob Tremblay/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Jack Dylan Grazer</name>
    <role>Alberto Scorfano (voice)</role>
    <type>Actor</type>
    <sortorder>1</sortorder>
    <thumb>/config/data/metadata/People/J/Jack Dylan Grazer/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Emma Berman</name>
    <role>Giulia Marcovaldo (voice)</role>
    <type>Actor</type>
    <sortorder>2</sortorder>
    <thumb>/config/data/metadata/People/E/Emma Berman/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Saverio Raimondo</name>
    <role>Ercole Visconti (voice)</role>
    <type>Actor</type>
    <sortorder>3</sortorder>
    <thumb>/config/data/metadata/People/S/Saverio Raimondo/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Maya Rudolph</name>
    <role>Daniela Paguro (voice)</role>
    <type>Actor</type>
    <sortorder>4</sortorder>
    <thumb>/config/data/metadata/People/M/Maya Rudolph/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Marco Barricelli</name>
    <role>Massimo Marcovaldo (voice)</role>
    <type>Actor</type>
    <sortorder>5</sortorder>
    <thumb>/config/data/metadata/People/M/Marco Barricelli/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Jim Gaffigan</name>
    <role>Lorenzo Paguro (voice)</role>
    <type>Actor</type>
    <sortorder>6</sortorder>
    <thumb>/config/data/metadata/People/J/Jim Gaffigan/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Peter Sohn</name>
    <role>Ciccio (voice)</role>
    <type>Actor</type>
    <sortorder>7</sortorder>
    <thumb>/config/data/metadata/People/P/Peter Sohn/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Lorenzo Crisci</name>
    <role>Guido (voice)</role>
    <type>Actor</type>
    <sortorder>8</sortorder>
  </actor>
  <actor>
    <name>Marina Massironi</name>
    <role>Signora Marsigliese (voice)</role>
    <type>Actor</type>
    <sortorder>9</sortorder>
    <thumb>/config/data/metadata/People/M/Marina Massironi/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Luigi La Monica</name>
    <role>Tomasso (Old Fisherman) (voice)</role>
    <type>Actor</type>
    <sortorder>10</sortorder>
    <thumb>/config/data/metadata/People/L/Luigi La Monica/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Sandy Martin</name>
    <role>Grandma Paguro (voice)</role>
    <type>Actor</type>
    <sortorder>11</sortorder>
    <thumb>/config/data/metadata/People/S/Sandy Martin/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Giacomo Gianniotti</name>
    <role>Giacomo (Young Fisherman) (voice)</role>
    <type>Actor</type>
    <sortorder>12</sortorder>
    <thumb>/config/data/metadata/People/G/Giacomo Gianniotti/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Elisa Gabrielli</name>
    <role>Concetta Aragosta (voice)</role>
    <type>Actor</type>
    <sortorder>13</sortorder>
    <thumb>/config/data/metadata/People/E/Elisa Gabrielli/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Mimi Maynard</name>
    <role>Pinuccia Aragosta (voice)</role>
    <type>Actor</type>
    <sortorder>14</sortorder>
    <thumb>/config/data/metadata/People/M/Mimi Maynard/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Andrea Warren</name>
    <role>Producer</role>
    <type>Producer</type>
  </actor>
  <actor>
    <name>Pete Docter</name>
    <role>Executive Producer</role>
    <type>Producer</type>
    <thumb>/config/data/metadata/People/P/Pete Docter/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Peter Sohn</name>
    <role>Executive Producer</role>
    <type>Producer</type>
    <thumb>/config/data/metadata/People/P/Peter Sohn/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Kiri Hart</name>
    <role>Executive Producer</role>
    <type>Producer</type>
  </actor>
  <id>tt12801262</id>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>hevc</codec>
        <micodec>hevc</micodec>
        <bitrate>20782174</bitrate>
        <width>3840</width>
        <height>2160</height>
        <aspect>16:9</aspect>
        <aspectratio>16:9</aspectratio>
        <framerate>23.976025</framerate>
        <scantype>progressive</scantype>
        <default>True</default>
        <forced>False</forced>
        <duration>95</duration>
        <durationinseconds>5718</durationinseconds>
      </video>
      <audio>
        <codec>eac3</codec>
        <micodec>eac3</micodec>
        <bitrate>640000</bitrate>
        <language>eng</language>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>True</default>
        <forced>False</forced>
      </audio>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>eng</language>
        <scantype>progressive</scantype>
        <default>True</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>zho</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>zho</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>zho</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>cmn</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>dan</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>deu</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>deu</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>eng</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>spa</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>spa</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>spa</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>fra</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>fra</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>ita</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>jpn</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>jpn</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>kor</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>kor</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>nld</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>nor</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>por</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>por</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>por</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>por</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>fin</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>swe</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
      <subtitle>
        <codec>subrip</codec>
        <micodec>subrip</micodec>
        <language>yue</language>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
      </subtitle>
    </streamdetails>
  </fileinfo>
</movie>`

**Comment by allanpk716** [comment]
> > > Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.nfo
> > 
> > 
> > 能发一下这个文件的内容看看吗？最好发全。
> 
> nfo是Jellyfin生成的，应该和Emby一样吧。
> `
> 
> 在意大利的利古里亚海岸上，一个名为路卡（Luca）的小男孩与好朋友们一起渡过难忘的夏天，过程中充满了冰淇淋、意大利面和摩托车。然而，路卡却有一个秘密：他是来自水底世界的海怪，且只要一接触到水，就会原形毕露。
> 
> false
> 2021-07-09 15:59:11
> 
> <title>夏日友晴天</title> Luca Enrico Casarosa Jesse Andrews Mike Jones Nicolle Castro James Reinhart Robertson Jesse Andrews Mike Jones Nicolle Castro James Reinhart Robertson 7.6 2021 PG tt12801262 508943 2021-06-17 2021-06-17 91 95 United States of America 动画 喜剧 家庭 奇幻 Walt Disney Pictures Pixar italy monster secret friendship friends coming of age sea monster seaside town 1950s water italian riviera /data/Movie/夏日友晴天 Luca (2021)/folder.jpg /data/Movie/夏日友晴天 Luca (2021)/backdrop.jpg Jacob Tremblay Luca Paguro (voice) Actor 0 /config/data/metadata/People/J/Jacob Tremblay/folder.jpg Jack Dylan Grazer Alberto Scorfano (voice) Actor 1 /config/data/metadata/People/J/Jack Dylan Grazer/folder.jpg Emma Berman Giulia Marcovaldo (voice) Actor 2 /config/data/metadata/People/E/Emma Berman/folder.jpg Saverio Raimondo Ercole Visconti (voice) Actor 3 /config/data/metadata/People/S/Saverio Raimondo/folder.jpg Maya Rudolph Daniela Paguro (voice) Actor 4 /config/data/metadata/People/M/Maya Rudolph/folder.jpg Marco Barricelli Massimo Marcovaldo (voice) Actor 5 /config/data/metadata/People/M/Marco Barricelli/folder.jpg Jim Gaffigan Lorenzo Paguro (voice) Actor 6 /config/data/metadata/People/J/Jim Gaffigan/folder.jpg Peter Sohn Ciccio (voice) Actor 7 /config/data/metadata/People/P/Peter Sohn/folder.jpg Lorenzo Crisci Guido (voice) Actor 8 Marina Massironi Signora Marsigliese (voice) Actor 9 /config/data/metadata/People/M/Marina Massironi/folder.jpg Luigi La Monica Tomasso (Old Fisherman) (voice) Actor 10 /config/data/metadata/People/L/Luigi La Monica/folder.jpg Sandy Martin Grandma Paguro (voice) Actor 11 /config/data/metadata/People/S/Sandy Martin/folder.jpg Giacomo Gianniotti Giacomo (Young Fisherman) (voice) Actor 12 /config/data/metadata/People/G/Giacomo Gianniotti/folder.jpg Elisa Gabrielli Concetta Aragosta (voice) Actor 13 /config/data/metadata/People/E/Elisa Gabrielli/folder.jpg Mimi Maynard Pinuccia Aragosta (voice) Actor 14 /config/data/metadata/People/M/Mimi Maynard/folder.jpg Andrea Warren Producer Producer Pete Docter Executive Producer Producer /config/data/metadata/People/P/Pete Docter/folder.jpg Peter Sohn Executive Producer Producer /config/data/metadata/People/P/Peter Sohn/folder.jpg Kiri Hart Executive Producer Producer tt12801262 eac3 eac3 640000 eng progressive 6 48000 True False subrip subrip eng progressive True False subrip subrip zho progressive False False subrip subrip zho progressive False False subrip subrip zho progressive False False subrip subrip cmn progressive False False subrip subrip dan progressive False False subrip subrip deu progressive False False subrip subrip deu progressive False False subrip subrip eng progressive False False subrip subrip spa progressive False False subrip subrip spa progressive False False subrip subrip spa progressive False False subrip subrip fra progressive False False subrip subrip fra progressive False False subrip subrip ita progressive False False subrip subrip jpn progressive False False subrip subrip jpn progressive False False subrip subrip kor progressive False False subrip subrip kor progressive False False subrip subrip nld progressive False False subrip subrip nor progressive False False subrip subrip por progressive False False subrip subrip por progressive False False subrip subrip por progressive False False subrip subrip por progressive False False subrip subrip fin progressive False False subrip subrip swe progressive False False subrip subrip yue progressive False False `

这文件里面没得 IMDB 关键词

**Comment by mhqschen** [comment]
发现贴上来格式不对。。。贴到这了https://pastebin.com/kTXTCJUK
有IMDB的号的
![image](https://user-images.githubusercontent.com/9138710/126129708-9b6ee6d1-b56d-4c7a-a437-1487b2bb5dda.png)

**Comment by allanpk716** [comment]
> [Luca (2021) [imdb-tt12801262][WEBDL-2160p][8bit][x265][EAC3 Atmos 5.1]-FLUX.zip](https://github.com/allanpk716/ChineseSubFinder/files/6839298/Luca.2021.imdb-tt12801262.WEBDL-2160p.8bit.x265.EAC3.Atmos.5.1.-FLUX.zip)
> 发现贴上来格式不对。。。贴到这了https://pastebin.com/kTXTCJUK


= =
看了，还是那个梗，有一些 imdbid 字段的值是不对的，这个导致会故障。所以改了读取 imdb id 的逻辑。如下图，搜索以下关键词去找到的。

![image](https://user-images.githubusercontent.com/1176000/126131371-0107daf3-2068-41d7-8910-5585aeb2c8c0.png)

因为我这里是用 sonarr 和 radarr 来下载的，所以他们处理完基本都能够适应这样的读取逻辑。其实还会读取 movie.xml 文件内容。

当然我提到这个情况应该是个例（但我这里遇到不少），这样的写法可能会影响其他人使用的削刮器正确处理的内容。我会再把你这种情况也加进去，但是这样的 imdb id 搜索逻辑优先级会调低。

在 v0.12.x 中一并修复吧

**Comment by mhqschen** [comment]
其实我也是arr们下载的，不过没有让他们保存metadata文件，而是用jellyfin刮削。
刚刚试了下Emby，和Jellyfin生成的nfo文件格式基本一致。IMDB ID都是”<imdbid>tt12801262</imdbid>"

**Comment by allanpk716** [comment]
> 其实我也是arr们下载的，不过没有让他们保存metadata文件，而是用jellyfin刮削。
> 刚刚试了下Emby，和Jellyfin生成的nfo文件格式基本一致。IMDB ID都是”tt12801262"

v0.12.x  发布后，可以看看是否正确读取了。
