### ISSUE TITLE
希望能支持繁體字幕

### ISSUE THREAD

**Issue by brucetangian** [allanpk716/ChineseSubFinder#260]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
指的是简体繁体互转？还是下载繁体？后者会下载仅仅是优先级是简体优先。

**Comment by brucetangian** [comment]
請問如何選擇繁體優先？還是預設已是繁 簡 都會下載，感謝你抽空回覆。

**Comment by allanpk716** [comment]
没有留出接口可以设置简体还是繁体优先，不过可以给出简繁互转的开关，这样就算下载的是简体也能够转成繁体。但是，不知道从简体转繁体，这样的翻译、语法是否会怪怪的。如果可能你可以试试把一个简体字幕转换成繁体，然后看看能接受没。

**Comment by brucetangian** [comment]
其實就書寫來說 翻譯跟語法應該是差不多 希望能推出個繁簡互換的開關

**Comment by allanpk716** [comment]
> 其實就書寫來說 翻譯跟語法應該是差不多 希望能推出個繁簡互換的開關

争取下个版本给出来，应该会在“实验室”页面。

**Comment by brucetangian** [comment]
收到 十分感謝你

**Comment by allanpk716** [comment]
推送了 v0.23.x 去实验室开启即可，这个功能首先得转码为 UTF-8 然后才可用，也就是有一定几率会乱码，有的话记得反馈对应的原始字幕过来（因为不会备份字幕，所以要反馈就得关闭该功能，再次下载该视频字幕，手动保存一下···）

**Comment by brucetangian** [comment]
我先試用一下 有問題再反馈 這次謝謝你

**Comment by brucetangian** [comment]
你好 我已試用繁体字幕功能 但體驗不太友好 原因有些字幕不能翻譯 有些翻譯成別的字 體驗感很差 建議還是先取消這個功能吧 我也怕別人用到這個功能有不好的體驗 先謝謝你～

**Comment by allanpk716** [comment]
> 你好 我已試用繁体字幕功能 但體驗不太友好 原因有些字幕不能翻譯 有些翻譯成別的字 體驗感很差 建議還是先取消這個功能吧 我也怕別人用到這個功能有不好的體驗 先謝謝你～

能否举例一下你遇到的情况嘛，比如什么字转换错误了，是乱码还是？

**Comment by brucetangian** [comment]
好像比喻這個 是 ，它會翻譯這個字（昰），這種情況很多。也有很多句子漏翻譯。

**Comment by allanpk716** [comment]
see #328

**Comment by allanpk716** [comment]
最新版本使用 opencc 来做简繁转换了，可以去试试。
