### ISSUE TITLE
关于“程序启动立即开始扫描”这一选项的功能优化

### ISSUE THREAD

**Issue by Lcc1ccl** [allanpk716/ChineseSubFinder#261]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.21.1

环境: docker

## 你想要新增或者改进什么功能？

Web设置界面的一些优化和注释，比如“程序启动立即开始扫描”和“保存整季的缓存字幕”

“程序启动立即开始扫描” 这个选项的名字有点迷惑性，刚开始以为是类似于群晖docker自动重启的功能，实际上需要打开这一开关才能在点击运行任务后立即开始扫描。导致有些朋友在安装完成后，点击运行日志不刷，以为自己哪里配置错了。。

**Comment by allanpk716** [comment]
这里有点绕，也没想好怎么描述，起因是，有部分人是使用 watchdog 来自动实现本程序的 latest 的自动拉取更新的。那么就会在某个大版本中，因为本程序某个时间段内会频繁的修复问题（发子的修复版本），导致他们会不停的拉取最新的进行更新，一更新就马上扫描，这样就反反复复重复的扫描。然后就有了启动程序不要马上开始扫描的功能出现。

“保存整季的缓存字幕”这个更加像是调试功能，目前会给出来，后续会逐步弱化或者换地方归类。

**Comment by Lcc1ccl** [comment]
> 这里有点绕，也没想好怎么描述，起因是，有部分人是使用 watchdog 来自动实现本程序的 latest 的自动拉取更新的。那么就会在某个大版本中，因为本程序某个时间段内会频繁的修复问题（发子的修复版本），导致他们会不停的拉取最新的进行更新，一更新就马上扫描，这样就反反复复重复的扫描。然后就有了启动程序不要马上开始扫描的功能出现。
> 
> “保存整季的缓存字幕”这个更加像是调试功能，目前会给出来，后续会逐步弱化或者换地方归类。

了解！但是感觉可以将这个功能独立出来，或者初次运行时手动点击运行任务时可以不依赖这个设置的开关，不然的话第一次运行点击以后没有反应确实有点怪怪的。

**Comment by allanpk716** [comment]
这个可以在下个版本默认第一次使用是 true，应该就好了，如果有需求再手动设置为 false。  @iMyon 看看是否是在 Web 那边配置初始化的时候第一次就默认传递 true 就好了。

**Comment by iMyon** [comment]
@allanpk716 
初始化时候的默认配置是从`/def-settings`接口获取的，后台改一下这个接口返回，Web就会按照新的初始化

**Comment by allanpk716** [comment]
> @allanpk716 初始化时候的默认配置是从`/def-settings`接口获取的，后台改一下这个接口返回，Web就会按照新的初始化

ok
