### ISSUE TITLE
每次重启都会强制改变一次media目录所有文件的所属权

### ISSUE THREAD

**Issue by skiinder** [allanpk716/ChineseSubFinder#263]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
0.21.1 docker

## 你遇到什么问题了？

容器重启会强制更改/media目录下所有文件的user和group，其中有我nextcloud网盘的文件夹，而那个文件夹和chinese sub finder的user不一样，也就是说每次重启都会造成nextcloud失效

## 你的问题弄重现嘛？

能

## 你期望的结果

不要在启动时候自动chown？或者请告诉我哪里可以自定义代码也行

**Comment by allanpk716** [comment]
尝试更新 v0.22.x，见 #266

**Comment by skiinder** [comment]
谢谢，我更新一下
