### ISSUE TITLE
从 v0.21.x 开始，gorelease 编译可执行文件错误，暂时没有头绪

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#267]
见相关的 #240 ，脚本在某个时间后就出错了，看日志是因为找不到对应的包下载导致的。因为对 linux 相关都不熟悉，所以之前能写完这个脚本就很头疼，暂时也没有精力去解决这个问题。

当然大多数人应该是使用 docker 为主，影响范围有限，所以也没怎么关注。

如果可能还是希望这个脚本能够正确执行的。如果你对这块熟悉，期望能够帮忙解决该问题。

**Comment by wloot** [comment]
看起来就是软件源缓存问题，尝试apt install 之前apt update下呢?

**Comment by allanpk716** [comment]
> 看起来就是软件源缓存问题，尝试apt install 之前apt update下呢?

可以了，谢谢。
