### ISSUE TITLE
使用 Github Action 编译 Docker 时间很长，是否有办法缩短？

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#268]
如果仅仅是编译输出 x86 的 docker，其实时间可以接受（几分钟），但是如果编译多个架构的速度现在很慢，得 1h。

因为本人对这个部分不熟悉，有办法可以优化提速嘛？

PS：现在的自动化编译是通过 git 的 tag 标记版本来触发的。

**Comment by SuperNG6** [comment]
构建非x86镜像，docker用的是qemu模拟其他架构，所以非常慢，可以考虑在ubuntu x86镜像里，交叉编译出二进制，然后再分发到不同架构的镜像里
1、编译这块可以参照 https://github.com/XTLS/Xray-core/blob/main/.github/workflows/release.yml
2、编译后的文件可以放到 GitHub action cache里，别的镜像在拉取缓存里对应架构的二进制 https://github.com/actions/cache

**Comment by allanpk716** [comment]
> 构建非x86镜像，docker用的是qemu模拟其他架构，所以非常慢，可以考虑在ubuntu x86镜像里，交叉编译出二进制，然后再分发到不同架构的镜像里 1、编译这块可以参照 https://github.com/XTLS/Xray-core/blob/main/.github/workflows/release.yml 2、编译后的文件可以放到 GitHub action cache里，别的镜像在拉取缓存里对应架构的二进制 https://github.com/actions/cache https://docs.github.com/cn/actions/using-workflows/caching-dependencies-to-speed-up-workflows
> 
> 我觉得比较好的方法，可能就是用GitHub action编译出各个架构的二进制文件，提交到release里，然后构建不同镜像时再下载 https://github.com/SuperNG6/Docker-qBittorrent-Enhanced-Edition/blob/master/install.sh

谢谢，我抽时间看看
