### ISSUE TITLE
每次重启都会被认为是First Time Download Start

### ISSUE THREAD

**Issue by mhqschen** [allanpk716/ChineseSubFinder#27]
你使用的 chinesesubfinder 是什么版本，什么环境？
chinesesubfinder 版本: v0.11.1

环境: docker

你遇到什么问题了？
部署在NAS上，然后每天定时开关NAS。
每次重启都会被认为是First Time Download Start。然后重新扫一遍所有文件夹。

**Comment by allanpk716** [comment]
> 你使用的 chinesesubfinder 是什么版本，什么环境？
> chinesesubfinder 版本: v0.11.1
> 
> 环境: docker
> 
> 你遇到什么问题了？
> 部署在NAS上，然后每天定时开关NAS。
> 每次重启都会被认为是First Time Download Start。然后重新扫一遍所有文件夹。

这个不是问题，本程序是没有记录那些视频被扫描过和下载过字幕的功能的。

依赖的是文件的下载时间和发布时间，以及是否有下载过字幕来复合判断的，条件符合会自动跳过。

如果想要更快的扫描，见 [高阶设置 - Emby API 支持](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md)

没有测试过 Jellyfin 是否有对应的 API

**Comment by allanpk716** [comment]
之所以写 First Time Download Start，是因为第三方定时器模块补支持启动马上执行，得手动执行，所以就单独标记下是手动再定时器前执行的任务。

**Comment by mhqschen** [comment]
了解。
