### ISSUE TITLE
使用 arm64 的机器会使用 linux amd 64

### ISSUE THREAD

**Issue by viqbgrg** [allanpk716/ChineseSubFinder#270]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.22.6
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> chromium 并没有使用arm64的而是使用的amd64的,导致chromium启动不起来,日志报 Exec format error

## 你的问题弄重现嘛？

> 能够重现

## 请给出当次问题的完整日志

[INFO]: 2022-03-31 09:23:06 - UrlConnectednessTest Target Site https://baidu.com Speed: 1382 ms, Status: true
[INFO]: 2022-03-31 09:23:06 - Check Sub Supplier Start...
[INFO]: 2022-03-31 09:23:06 - releaseAdblock start
[INFO]: 2022-03-31 09:23:06 - releaseAdblock end
Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/901912/chrome-linux.zip
Progress: 00% 100%
Unzip to: /root/.cache/rod/browser/chromium-901912
Progress: 00% 22% 40% 73% 100%

**Comment by sheldon-lu** [comment]
咋解决啊。应该没有支持arm的版本二进制吧

**Comment by allanpk716** [comment]
已经推出 Lite 版本，试试。具体见首页的部署教程。
