### ISSUE TITLE
bug: context 超时未处理回收

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#271]
当前获取字幕操作超时/或者出错后, 未做任何处理. 这至少会导致ffmpeg和chrome的进程不会被回收, 继续占用内存.

可能的方案:
将defer回收统一放到一个回调函数内, context生命周期结束后统一执行.

**Comment by allanpk716** [comment]
之前的重构没有彻底，能具体给出问题的代码地方嘛（写的断断续续，很多记不清楚了···）

就我目前观察自己这边的情况，遇到超时最终完成一次扫描后，应该是清理干净的（还是说下图的截图其实是有 ffmpeg 和 chrome 的残留，其实 portainer 看不到而已？）。

## 截图1
![image](https://user-images.githubusercontent.com/1176000/160961219-c19fa279-fc91-49c3-ac37-c1c7b1465b12.png)

## 截图2
![image](https://user-images.githubusercontent.com/1176000/160961364-48098abd-f9d8-43f3-9f02-f732eea555b1.png)

**Comment by wloot** [comment]
主要是在获取字幕中, 超时的ffmpeg进程会在提取完成后自行退出, chrome会统一被CloseChrome()杀掉. 因为我是rclone挂在谷歌盘, 每一次修正字幕时基本会会下载整个视频文件, 所以特别容易触发超时.

**Comment by allanpk716** [comment]
chrome 这个我其实都有写  defer browser.Close() 的，但是就是结束不掉···所以只能很傻的使用系统命令去全局杀

**Comment by wloot** [comment]
> chrome 这个我其实都有写 defer browser.Close() 的，但是就是结束不掉···所以只能很傻的使用系统命令去全局杀

chrome不退出的原因有一部分是 https://github.com/wloot/ChineseSubFinder/commit/ba1e0fe5f9c81f0aa6b28d6fa5033e46d1848ba0 这个主要做了:
1. rodHelper函数内, 之前已经创建了page或者browser, 下面继续执行的时候出现错误, 之前创建的不会被关闭
2. userdata似乎不需要使用随机目录, 共享目录的话总共只会占用200来m, 所以也就不需要清理了

但是上面那个超时问题还是存在....

**Comment by allanpk716** [comment]
1. 嗯，rod_helper.NewBrowser 新建的对象都配有 defer browser.Close() 的，page 也有在最后使用的位置进行释放。
2. userdata 我在这边测试，如果不是随机的目录，有梗，释放后运行 chrome 会有问题，所以才写的随机目录名称，而且貌似反馈几次都说之前的i清理方式有问题，我去看 rod 的代码感觉也没问题，所以才最终改成这样，貌似能用了。
3. 我看你使用 NewBrowser 选择不加载 adblocker ，这个也会有梗的，他们的广告会挡住操作页面元素的，checkAlive 确实无需加载，其他时候一定得加，而且后续会把这个 adblocker 的静态文件丢到外部，或者说去其他地方下载，不然以后为了这个我还得再次发布新版本···
4. NewBrowser 里面为什么要加载一个 qq.com ,原因也是有的，因为加载太快了，导致 adblocker 没有加载完成就开始后续的爬取页面的刷新，会导致广告无法被过滤
5. 为什么会在 NewBrowser 完毕后，有些代码会开启 zimuku 主页呢，比如 zimuku 你提到的它第一次会调用 js 获取屏幕信息，然后传递到后续的页面使用，如果一开始就直接进行爬取，就会导致获取 html string 是错误的，必须得完整打开一次 zimuku 主页才能跳过这个问题，所以也不要改，不然会出错的。

**Comment by allanpk716** [comment]
NewPageNavigate 你也不能在里面关闭 page 实例，因为在后面需要复用这个实例的，你提前关闭也会导致故障，后面调用的代码会手动释放的（除非我漏了），虽然这样用法有点像 C 的玩法（不像 defer 的套路），但是暂时没想好怎么改进

**Comment by wloot** [comment]
> NewPageNavigate 你也不能在里面关闭 page 实例，因为在后面需要复用这个实例的，你提前关闭也会导致故障，后面调用的代码会手动释放的（除非我漏了），虽然这样用法有点像 C 的玩法（不像 defer 的套路），但是暂时没想好怎么改进

我只在返回error时执行了close(), 这时候rod.Page指针返回nil, 上层根本无法执行close的

**Comment by wloot** [comment]
> 1. 嗯，rod_helper.NewBrowser 新建的对象都配有 defer browser.Close() 的，page 也有在最后使用的位置进行释放。
> 2. userdata 我在这边测试，如果不是随机的目录，有梗，释放后运行 chrome 会有问题，所以才写的随机目录名称，而且貌似反馈几次都说之前的i清理方式有问题，我去看 rod 的代码感觉也没问题，所以才最终改成这样，貌似能用了。
> 3. 我看你使用 NewBrowser 选择不加载 adblocker ，这个也会有梗的，他们的广告会挡住操作页面元素的，checkAlive 确实无需加载，其他时候一定得加，而且后续会把这个 adblocker 的静态文件丢到外部，或者说去其他地方下载，不然以后为了这个我还得再次发布新版本···
> 4. NewBrowser 里面为什么要加载一个 qq.com ,原因也是有的，因为加载太快了，导致 adblocker 没有加载完成就开始后续的爬取页面的刷新，会导致广告无法被过滤
> 5. 为什么会在 NewBrowser 完毕后，有些代码会开启 zimuku 主页呢，比如 zimuku 你提到的它第一次会调用 js 获取屏幕信息，然后传递到后续的页面使用，如果一开始就直接进行爬取，就会导致获取 html string 是错误的，必须得完整打开一次 zimuku 主页才能跳过这个问题，所以也不要改，不然会出错的。

因为之前checkalive时候已经打开了一个zmk主页, 而我选择复用userdata, 所以应该是不会有问题的. 我本地也试了无痕直接打开zmk的详情页, 貌似没遇到问题

**Comment by allanpk716** [comment]
最新版本应该好一点了吧，当然依然会在 subhd 验证机制更新后，由于不支持对应的验证逻辑了，所以会卡住，再触发超时。
