### ISSUE TITLE
版本: v0.22.6 检查EMBY配置页面提示EMBY目录不可达，都已经严格按照部署教程写的

### ISSUE THREAD

**Issue by ppponce** [allanpk716/ChineseSubFinder#273]
> chinesesubfinder 版本: [v0.22.6] 
>
> 环境: docker , 群晖NAS，内网IP 192.168.2.8

> 无法自动下载字幕，检查EMBY配置页面提示EMBY目录不可达，都已经严格按照部署教程写的

EMBY也是同一台NAS上跑的Docker，目录就是严格按照EMBY媒体库显示的抄写：/media/Movie

EMBY容器运行挂载的本地主机目录是8T3movie，挂载目录/media

chinesesubfinder容器运行挂载的本地主机目录是8T3movie，挂载目录/media，两个容器都是一样设置的，EMBY是正常工作的

## 你的问题弄重现嘛？

> 能够重 现

## 你期望的结果

> EMBY目录搞不清楚要写哪种，最好是能够选取式的

[ChineseSubFinder--202203310000--.log](https://github.com/allanpk716/ChineseSubFinder/files/8387427/ChineseSubFinder--202203310000--.log)
![Snipaste_2022-03-31_16-18-07](https://user-images.githubusercontent.com/101972888/161010187-33c15507-90c6-4c24-b810-3f3ac7c91001.jpg)
![Snipaste_2022-03-31_16-39-35](https://user-images.githubusercontent.com/101972888/161014127-ce8928d7-ebea-4754-9cb9-27d007c9ec27.jpg)
![Snipaste_2022-03-31_16-21-39](https://user-images.githubusercontent.com/101972888/161014520-1df5f812-7951-4f4c-bf88-3968793bc51b.jpg)

**Comment by ppponce** [comment]
日志
![Snipaste_2022-03-31_16-22-55](https://user-images.githubusercontent.com/101972888/161012343-dfc20df1-031b-43c3-858a-36fe58a9fcc3.jpg)
![Snipaste_2022-03-31_16-23-49](https://user-images.githubusercontent.com/101972888/161012358-f456edca-e91a-4899-8626-891031abb9b9.jpg)
[ChineseSubFinder--202203310000--.log](https://github.com/allanpk716/ChineseSubFinder/files/8387534/ChineseSubFinder--202203310000--.log)

**Comment by laobanbiefangcu** [comment]
请问你解决了吗，我和你一样的问题，不知道为什么emby读取不到

**Comment by Nothend** [comment]
请问你解决了吗，我和你一样的问题，不知道为什么emby读取不到

**Comment by allanpk716** [comment]
最近版本更新后，有朋友录了视频，到时候会链接对应的教程。
