### ISSUE TITLE
建议单独设置一个执行结果的输出界面或者文本框

### ISSUE THREAD

**Issue by Lcc1ccl** [allanpk716/ChineseSubFinder#274]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.22.6

环境: docker

## 你想要新增或者改进什么功能？

现在的日志是全量日志，看起来实在过于冗余和复杂，普通用户正常运行时其实不需要知道整个程序的执行过程，因此是否能够单独开辟一个位置用来输出单次运行的结果呢？比如，在日志页下方仍有一块空白，可以增加一个结果页，显示

- 执行时间
- 字幕库调用情况
- 成功下载字幕
- 失败条目
- 跳过数量
- 报错日志
- 字幕自动校正情况
- Emby刷新情况
- 缓存清理情况
- 。。。等等

**Comment by allanpk716** [comment]
最新版本已经是独立的下载任务，会有对应的日志
