### ISSUE TITLE
请问如何定位到电影文件夹

### ISSUE THREAD

**Issue by fireflycao** [allanpk716/ChineseSubFinder#28]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本:最新

环境: unraid docker 

## 你遇到什么问题了？

如何定位到电影文件夹

修改config.yaml
分别试了：
MovieFolder: /mnt/user/Media/Movies/
MovieFolder:\\10.53.*.*\Media\Movies\
运行后均显示“[ERROR]: 2021-07-20 05:23:23 - MovieFolder not found”
![image](https://user-images.githubusercontent.com/20470524/126230879-688986fa-d181-4d63-942b-6e3370f2b88e.png)

**Comment by allanpk716** [comment]
需要你截图你的 unraid 的 SHARES 对应电影文件夹的整个界面的信息看一下。我这里是举例我的界面，你得截图你的电影文件夹界面。

![image](https://user-images.githubusercontent.com/1176000/126251380-f4840507-d1ff-4595-a804-ff504a66cc5a.png)

![image](https://user-images.githubusercontent.com/1176000/126251511-2a02f450-49ad-4809-aaa4-b209150f7553.png)


同时你需要把你的 ChineseSubFinder 的配置 config.yaml 文件也发一下看看。

**Comment by allanpk716** [comment]
或者是 SMB Shares 的界面也行。zhu主要是能定位到你的电影文件夹在 unraid 上的目录

![image](https://user-images.githubusercontent.com/1176000/126251636-749d7929-714a-4ce3-b895-abb728510021.png)

**Comment by fireflycao** [comment]
电影文件夹 /mnt/user/Media/Movies
![image](https://user-images.githubusercontent.com/20470524/126257047-457d5c3b-e294-4a37-9ccb-90cdd2621990.png)
config位置
![image](https://user-images.githubusercontent.com/20470524/126257115-347814cc-f9b4-4d44-b22a-5af6072b83d2.png)
`UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 4
SubTypePriority: 0
DebugMode: false
SaveMultiSub: true
MovieFolder: \\10.53.*.1*\Media\Movies\
or /mnt/user/Media/Movies
上面两个都试过
SeriesFolder: X:\连续剧
AnimeFolder: X:\动画`

**Comment by fireflycao** [comment]
![image](https://user-images.githubusercontent.com/20470524/126257426-ec120900-547b-4d67-987a-9e0b3f23d1e1.png)

**Comment by allanpk716** [comment]
config.yaml 路径是容器内的路径，不是物理路径。

```
MovieFolder: /media/电影
SeriesFolder: /media/连续剧
```

见：

[How To Use - 原生文档](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/HowToUse.md)

[配置建议以及解释](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%85%8D%E7%BD%AE%E5%BB%BA%E8%AE%AE%E4%BB%A5%E5%8F%8A%E8%A7%A3%E9%87%8A.md)

**Comment by fireflycao** [comment]
已搞定，多谢！
