### ISSUE TITLE
0.24.0启动错误

### ISSUE THREAD

**Issue by jasonhorga** [allanpk716/ChineseSubFinder#281]
[INFO]: 2022-04-02 13:46:16 - ChineseSubFinder Version: v0.24.0
[INFO]: 2022-04-02 13:46:16 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-04-02 13:46:16 - Setup is Done
[INFO]: 2022-04-02 13:46:16 - First Time coreSubDownloadProcess Start
[INFO]: 2022-04-02 13:46:16 - Reload Log Settings, level = Info
[INFO]: 2022-04-02 13:46:16 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-02 13:46:16 - Try Start Server At Port 19035
[INFO]: 2022-04-02 13:46:16 - matches logs: 20
[INFO]: 2022-04-02 13:46:16 - OneTimeSubtitleScanStart
[INFO]: 2022-04-02 13:46:16 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-04-02 13:46:16 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202242c31ViaG5Q.txt
[INFO]: 2022-04-02 13:46:16 - GetCode 2022-04-02 951275
[INFO]: 2022-04-02 13:46:16 - ClearRodTmpRootFolder Done
[INFO]: 2022-04-02 13:46:16 - PreDownloadProcess.Init() End
[INFO]: 2022-04-02 13:46:16 - PreDownloadProcess.Check() Start...
[INFO]: 2022-04-02 13:46:16 - UseHttpProxy = false
[INFO]: 2022-04-02 13:46:16 - UrlConnectednessTest Target Site https://baidu.com Speed: 75 ms, Status: true
[INFO]: 2022-04-02 13:46:16 - Check Sub Supplier Start...
[INFO]: 2022-04-02 13:46:16 - releaseAdblock start
[INFO]: 2022-04-02 13:46:17 - releaseAdblock end
[INFO]: 2022-04-02 13:46:44 - zimuku Check Alive = true, Speed = 7340 ms
[INFO]: 2022-04-02 13:46:45 - xunlei Check Alive = true, Speed = 1241 ms
[INFO]: 2022-04-02 13:46:46 - shooter Check Alive = true, Speed = 237 ms
[INFO]: 2022-04-02 13:46:47 - subhd Check Alive = true, Speed = 902 ms
[INFO]: 2022-04-02 13:46:47 - Check Sub Supplier End
[INFO]: 2022-04-02 13:46:47 - MovieFolder Index 0 -- /media/movie
[INFO]: 2022-04-02 13:46:47 - SeriesPaths Index 0 -- /media/tv
[INFO]: 2022-04-02 13:46:47 - PreDownloadProcess.Check() End
[INFO]: 2022-04-02 13:46:47 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-04-02 13:46:47 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-02 13:46:48 - PreDownloadProcess.HotFix() End
[INFO]: 2022-04-02 13:46:48 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-04-02 13:46:48 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-02 13:46:48 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-04-02 13:46:48 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-04-02 13:46:48 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-04-02 13:46:48 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-04-02 13:46:48 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-04-02 13:46:48 - matches logs: 21
[INFO]: 2022-04-02 13:46:48 - OneTimeSubtitleScanEnd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbf7668]

goroutine 7 [running]:
github.com/allanpk716/ChineseSubFinder/internal/pkg/rod_helper.NewBrowserEx(0x70, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, ...)
	/homelab/buildspace/internal/pkg/rod_helper/rodHelper.go:27 +0x28
github.com/allanpk716/ChineseSubFinder/internal/pkg/rod_helper.ReloadBrowser()
	/homelab/buildspace/internal/pkg/rod_helper/rodHelper.go:240 +0x71
github.com/allanpk716/ChineseSubFinder/internal/logic/pre_download_process.(*PreDownloadProcess).ReloadBrowser(0xc00137bd20)
	/homelab/buildspace/internal/logic/pre_download_process/pre_download_proces.go:253 +0xca
github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).coreSubDownloadProcess(0xc000f35800)
	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:193 +0x38f
github.com/allanpk716/ChineseSubFinder/internal/logic/cron_helper.(*CronHelper).Start(0xc000f35800, 0x1)
	/homelab/buildspace/internal/logic/cron_helper/cron_helper.go:48 +0x385
main.main.func1()
	/homelab/buildspace/cmd/chinesesubfinder/main.go:38 +0x85
created by main.main
	/homelab/buildspace/cmd/chinesesubfinder/main.go:36 +0xef
(EE) 
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
(EE)

**Comment by wloot** [comment]
https://github.com/wloot/ChineseSubFinder/commit/c685de5394fd2ce93db45a8232801f8dccdf5cff
