### ISSUE TITLE
## v0.24.1 Zimuku内存报错

### ISSUE THREAD

**Issue by ppponce** [allanpk716/ChineseSubFinder#282]
## v0.24.1 Zimuku内存报错

> chinesesubfinder 版本: v.0.24.1
>
> 环境: 群晖 920+ , docker 

我的群晖920+跑Docker，群晖已经扩到20G内存。

CSF v0.24.1运行2小时后，随便看了下，Docker内存占用4.5G，但是当前下载日志有大量的Zimuku内存地址报错，几乎每个下载都是。

[info]: 2022-04-02 18:00:03 - OrgSubName: [subhd]_0_Ode.To.The.Goose.2018.KOREAN.1080p.BluRay.x264.DTS-FGT.chs.srt
[info]: 2022-04-02 18:00:03 - SubDownAt: /media/Movie/咏鹅.2018.1080p.韩语.简繁中字￡CMCT槿年/[咏鹅].Ode.to.the.Goose.2018.BluRay.1080p.x264.DTS-CMCT.chinese(简).default.srt
[info]: 2022-04-02 18:00:03 - ----------------------------------
[error]: 2022-04-02 18:01:15 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:01:15 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:01:32 - subhd step2Ex context deadline exceeded
[error]: 2022-04-02 18:01:34 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:01:34 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:01:52 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:01:52 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:02:10 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:02:10 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:02:28 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:02:28 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:02:46 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:02:46 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:03:03 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:03:03 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:03:20 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:03:20 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:04:02 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-02 18:04:02 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[info]: 2022-04-02 18:04:02 - Queue 114 zimuku End...
>
![image](https://user-images.githubusercontent.com/101972888/161378267-20e34477-da8f-47ca-8fee-e6e672fa1cfa.png)

**Comment by allanpk716** [comment]
大概率下载超限触发了超时逻辑

**Comment by allanpk716** [comment]
暂时不在 Client 端支持了，何时支持不定
