### ISSUE TITLE
开启任务跑完无反应，大佬们帮我看看啥原因

### ISSUE THREAD

**Issue by 747195109ch** [allanpk716/ChineseSubFinder#284]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
>0.24.1
> 环境: docker or Window or Linux or MAC
> Window
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 描述一下你遇到的问题
开启任务跑完无反应

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
	"user_info": {
		"username": "adxxx",
		"password": "wx*****"
	},
	"common_settings": {
		"scan_interval": "6h",
		"threads": 1,
		"run_scan_at_start_up": true,
		"movie_paths": ["F:\\硬链接\\电影\\", "F:\\硬链接\\动画\\电影\\", "G:\\硬链接\\电影\\", "G:\\硬链接\\动画\\电影\\"],
		"series_paths": ["F:\\硬链接\\剧集\\", "F:\\硬链接\\动画\\剧集\\", "G:\\硬链接\\剧集\\", "G:\\硬链接\\动画\\剧集\\"]
	},
	"advanced_settings": {
		"proxy_settings": {
			"use_http_proxy": false,
			"http_proxy_address": ""
		},
		"debug_mode": false,
		"save_full_season_tmp_subtitles": true,
		"sub_type_priority": 0,
		"sub_name_formatter": 0,
		"save_multi_sub": true,
		"custom_video_exts": [],
		"fix_time_line": true,
		"topic": 1
	},
	"emby_settings": {
		"enable": true,
		"address_url": "http://10.10.10.150:8096",
		"api_key": "*****************",
		"max_request_video_number": 3000,
		"skip_watched": true,
		"movie_paths_mapping": {
			"F:\\硬链接\\动画\\电影\\": "F:\\硬链接\\动画\\电影\\",
			"F:\\硬链接\\电影\\": "F:\\硬链接\\电影\\",
			"G:\\硬链接\\动画\\电影\\": "G:\\硬链接\\动画\\电影\\",
			"G:\\硬链接\\电影\\": "G:\\硬链接\\电影\\"
		},
		"series_paths_mapping": {
			"F:\\硬链接\\剧集\\": "F:\\硬链接\\剧集\\",
			"F:\\硬链接\\动画\\剧集\\": "F:\\硬链接\\动画\\剧集\\",
			"G:\\硬链接\\剧集\\": "G:\\硬链接\\剧集\\",
			"G:\\硬链接\\动画\\剧集\\": "G:\\硬链接\\动画\\剧集\\"
		}
	},
	"developer_settings": {
		"enable": false,
		"bark_server_address": ""
	},
	"timeline_fixer_settings": {
		"max_offset_time": 120,
		"min_offset": 0.1
	},
	"experimental_function": {
		"auto_change_sub_encode": {
			"enable": false,
			"des_encode_type": 0
		},
		"chs_cht_changer": {
			"enable": false,
			"des_chinese_language_type": 0
		},
		"remote_chrome_settings": {
			"enable": false,
			"remote_docker_url": "",
			"remote_adblock_path": "",
			"remote_user_data_dir": ""
		}
	}
}
```
## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
[INFO]: 2022-04-03 18:22:03 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-04-03 18:22:04 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202243c31ViaG5Q.txt
[INFO]: 2022-04-03 18:22:04 - GetCode 2022-04-03 951275
[INFO]: 2022-04-03 18:22:04 - ClearRodTmpRootFolder Done
[INFO]: 2022-04-03 18:22:04 - PreDownloadProcess.Init() End
[INFO]: 2022-04-03 18:22:04 - PreDownloadProcess.Check() Start...
[INFO]: 2022-04-03 18:22:04 - UseHttpProxy = false
[INFO]: 2022-04-03 18:22:04 - UrlConnectednessTest Target Site https://baidu.com Speed: 129 ms, Status: true
[INFO]: 2022-04-03 18:22:04 - Check Sub Supplier Start...
[INFO]: 2022-04-03 18:22:27 - zimuku Check Alive = true, Speed = 6793 ms
[INFO]: 2022-04-03 18:22:50 - xunlei Check Alive = true, Speed = 22254 ms
[INFO]: 2022-04-03 18:22:50 - shooter Check Alive = true, Speed = 291 ms
[INFO]: 2022-04-03 18:22:50 - subhd Check Alive = true, Speed = 610 ms
[INFO]: 2022-04-03 18:22:50 - Check Sub Supplier End
[INFO]: 2022-04-03 18:22:50 - MovieFolder Index 0 -- F:\硬链接\电影\
[INFO]: 2022-04-03 18:22:50 - MovieFolder Index 1 -- F:\硬链接\动画\电影\
[INFO]: 2022-04-03 18:22:50 - MovieFolder Index 2 -- G:\硬链接\电影\
[INFO]: 2022-04-03 18:22:50 - MovieFolder Index 3 -- G:\硬链接\动画\电影\
[INFO]: 2022-04-03 18:22:50 - SeriesPaths Index 0 -- F:\硬链接\剧集\
[INFO]: 2022-04-03 18:22:50 - SeriesPaths Index 1 -- F:\硬链接\动画\剧集\
[INFO]: 2022-04-03 18:22:50 - SeriesPaths Index 2 -- G:\硬链接\剧集\
[INFO]: 2022-04-03 18:22:50 - SeriesPaths Index 3 -- G:\硬链接\动画\剧集\
[INFO]: 2022-04-03 18:22:50 - PreDownloadProcess.Check() End
[INFO]: 2022-04-03 18:22:50 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-04-03 18:22:50 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-03 18:22:50 - PreDownloadProcess.HotFix() End
[INFO]: 2022-04-03 18:22:50 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-04-03 18:22:50 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-03 18:22:50 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-04-03 18:22:50 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-04-03 18:22:50 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-04-03 18:23:01 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-04-03 18:23:01 - PreDownloadProcess.Wait() Done.
[ERROR]: 2022-04-03 18:23:01 - Need Install ffmpeg and ffprobe !
[INFO]: 2022-04-03 18:23:01 - Download One Started...
[INFO]: 2022-04-03 18:23:01 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-04-03 18:23:01 - Refresh Emby Sub List Start...
[INFO]: 2022-04-03 18:23:01 - Refresh Emby Sub List Success
[INFO]: 2022-04-03 18:23:01 - GetUpdateVideoListFromEmby Start...
[INFO]: 2022-04-03 18:23:01 - GetUpdateVideoListFromEmby End
[INFO]: 2022-04-03 18:23:01 - Download Movie Sub Started...
[INFO]: 2022-04-03 18:23:01 - Movie Sub Dl From Emby API...
[INFO]: 2022-04-03 18:23:01 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2022-04-03 18:23:01 - Download Movie Sub End...
[INFO]: 2022-04-03 18:23:01 - Download Series Sub Started...
[INFO]: 2022-04-03 18:23:01 - --------------------------------------
[INFO]: 2022-04-03 18:23:01 - successList 0
[INFO]: 2022-04-03 18:23:01 - --------------------------------------
[INFO]: 2022-04-03 18:23:01 - noExecuteList 0
[INFO]: 2022-04-03 18:23:01 - --------------------------------------
[INFO]: 2022-04-03 18:23:01 - errorList 0
[INFO]: 2022-04-03 18:23:01 - --------------------------------------
[INFO]: 2022-04-03 18:23:01 - Download Series Sub End...
[INFO]: 2022-04-03 18:23:02 - CloseChrome
[INFO]: 2022-04-03 18:23:02 - Refresh Emby Sub List Start...
[INFO]: 2022-04-03 18:23:02 - Refresh Emby Sub List Success
[INFO]: 2022-04-03 18:23:02 - Will Scan SubFixCache Folder, Clear files that are more than 7 * 24 hours old
[INFO]: 2022-04-03 18:23:02 - Download One End...
[WARNING]: 2022-04-03 18:23:02 - CloseChrome exit status 1
[INFO]: 2022-04-03 18:23:02 - ClearRodTmpRootFolder Done

**Comment by allanpk716** [comment]
开 debug

**Comment by MatrixShoo** [comment]
我也是这种情况，日记基本相同，就什么也没下载。
