### ISSUE TITLE
希望可以简化群晖下docker目录

### ISSUE THREAD

**Issue by Cyberxxt** [allanpk716/ChineseSubFinder#286]
群晖自带的docker不能设置volume目录，但是资料分别存放在/volume2/series和/volume2/movie下。
希望大佬对映射目录的条件可以优化一下支持一下群晖的多目录！！非常感谢大佬的程序，希望越做越好！

**Comment by allanpk716** [comment]
你可以装了 portainer 去管理群晖的 docker，我个人也是用这个工具的，好用很多。

**Comment by SuperNG6** [comment]
你可以`/volume2/series`挂载到/media/series ，`/volume2/movie`挂载到`/media/movie`

**Comment by allanpk716** [comment]
看看最新主页的部署教程和目录结构要求，应该算简化了吧
