### ISSUE TITLE
无法运行: unsupported protocol scheme 

### ISSUE THREAD

**Issue by Cyberxxt** [allanpk716/ChineseSubFinder#287]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.24.1
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 描述一下你遇到的问题
无法运行，且无法更改emby目录
![image](https://user-images.githubusercontent.com/40683077/161544238-272d1168-0dbe-4c51-9dfe-9ffd289661cf.png)

> Get "//%2F192.168.1.6%2Femby%2FItems%3FFilters=IsNotFolder&IncludeItemTypes=Episode%252CMovie&IsUnaired=false&Limit=2000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=45468f051fe2462fbc8bcbfcb1d01d56+-+sub/192.168.1.6/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=2000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=45468f051fe2462fbc8bcbfcb1d01d56+-+sub": unsupported protocol scheme 

>

## 你的问题弄重现嘛？

> 能够重现

## 给出当前程序的配置文件

{
    "user_info":{
        "username":"",
        "password":""
    },
    "common_settings":{
        "scan_interval":"6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/movie"
        ],
        "series_paths":[
            "/series"
        ]
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_http_proxy":false,
            "http_proxy_address":""
        },
        "debug_mode":true,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1
    },
    "emby_settings":{
        "enable":true,
        "address_url":"192.168.1.6",
        "api_key":"xxxxxxxxx - sub",
        "max_request_video_number":3000,
        "skip_watched":true,
        "movie_paths_mapping":{
            "/movie":"nfs://192.168.1.9/volume2/movie/"
        },
        "series_paths_mapping":{
            "/series":"nfs://192.168.1.9/volume2/series/"
        }
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        }
    }
}

## 如果是使用 Docker，请给出对应的配置信息
![image](https://user-images.githubusercontent.com/40683077/161544152-70192644-7636-44e5-8002-ff0d4af21a59.png)

## 请给出当次问题的完整日志
[INFO]: 2022-04-04 20:17:42 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-04-04 20:17:43 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202244c31ViaG5Q.txt
[INFO]: 2022-04-04 20:17:43 - GetCode 2022-04-04 951275
[INFO]: 2022-04-04 20:17:43 - ClearRodTmpRootFolder Done
[INFO]: 2022-04-04 20:17:43 - PreDownloadProcess.Init() End
[INFO]: 2022-04-04 20:17:43 - PreDownloadProcess.Check() Start...
[INFO]: 2022-04-04 20:17:43 - UseHttpProxy = false
[INFO]: 2022-04-04 20:17:43 - UrlConnectednessTest Target Site https://baidu.com Speed: 302 ms, Status: true
[INFO]: 2022-04-04 20:17:43 - Check Sub Supplier Start...
[INFO]: 2022-04-04 20:18:19 - zimuku Check Alive = true, Speed = 9362 ms
[INFO]: 2022-04-04 20:18:54 - xunlei Check Alive = true, Speed = 35236 ms
[INFO]: 2022-04-04 20:18:55 - shooter Check Alive = true, Speed = 1130 ms
[INFO]: 2022-04-04 20:18:56 - subhd Check Alive = true, Speed = 601 ms
[INFO]: 2022-04-04 20:18:56 - Check Sub Supplier End
[INFO]: 2022-04-04 20:18:56 - MovieFolder Index 0 -- /movie
[INFO]: 2022-04-04 20:18:56 - SeriesPaths Index 0 -- /series
[INFO]: 2022-04-04 20:18:56 - PreDownloadProcess.Check() End
[INFO]: 2022-04-04 20:18:56 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-04-04 20:18:56 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-04 20:18:56 - PreDownloadProcess.HotFix() End
[INFO]: 2022-04-04 20:18:56 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-04-04 20:18:56 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-04 20:18:56 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-04-04 20:18:56 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-04-04 20:18:56 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-04-04 20:19:18 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-04-04 20:19:18 - PreDownloadProcess.Wait() Done.
[INFO]: 2022-04-04 20:19:18 - Download One Started...
[INFO]: 2022-04-04 20:19:18 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-04-04 20:19:18 - Refresh Emby Sub List Start...
[ERROR]: 2022-04-04 20:19:18 - Refresh Emby Sub List Error
[ERROR]: 2022-04-04 20:19:18 - RefreshEmbySubList Get "//%2F192.168.1.6%2Femby%2FUsers%2FQuery%3Fapi_key=45468f051fe2462fbc8bcbfcb1d01d56+-+sub/192.168.1.6/emby/Users/Query?api_key=45468f051fe2462fbc8bcbfcb1d01d56+-+sub": unsupported protocol scheme ""
[INFO]: 2022-04-04 20:19:18 - Download One End...
[INFO]: 2022-04-04 20:19:19 - ClearRodTmpRootFolder Done
[ERROR]: 2022-04-04 20:19:19 - downloader_helper.Start() Error: Get "//%2F192.168.1.6%2Femby%2FUsers%2FQuery%3Fapi_key=45468f051fe2462fbc8bcbfcb1d01d56+-+sub/192.168.1.6/emby/Users/Query?api_key=45468f051fe2462fbc8bcbfcb1d01d56+-+sub": unsupported protocol scheme ""

**Comment by allanpk716** [comment]
没有测试过 nfs 协议，建议 smb，这个有人试过可以。

**Comment by allanpk716** [comment]
最新版本无需手动映射，可以试试。
