### ISSUE TITLE
未检索时资源占用似乎偏高

### ISSUE THREAD

**Issue by fireflycao** [allanpk716/ChineseSubFinder#29]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 最新版

环境: docker on unraid
## 你遇到什么问题了？

未检索时资源占用似乎偏高
![image](https://user-images.githubusercontent.com/20470524/126402752-9ea620d2-c0e4-427a-948e-e1762527447b.png)

**Comment by allanpk716** [comment]
已知问题，超时控制执行后， Chrome 无法正确关闭。需要下个版本更新结束 Chrome 的代码，有待多人测试后反馈效果。

**Comment by allanpk716** [comment]
源头问题是超时控制导致的，找个得多测试几次才清楚是否可以，毕竟 func 都写了 defer 的清理逻辑了。

目前粗暴的方案就是每次轮询结束后执行

`pkill chrome`

v0.12.x 版本先使用找个方案，然后我再看看源头怎么解决吧。
