### ISSUE TITLE
建议远程Chrome可以填多个，搞成分布式

### ISSUE THREAD

**Issue by viqbgrg** [allanpk716/ChineseSubFinder#291]
## 你想要新增或者改进什么功能？

有一些闲置的主机，或者内网穿透的个人电脑，都能用来下载字幕

**Comment by allanpk716** [comment]
后续会给出 slave 模式出来，cfs 是 master，把任务提交给 slave，这里提及的是单机情况。也可能在共享字幕做出来后，会在用户同意的情况下，获取公有的缺失字幕列表，然后下发给协作者分布式完成下载任务，无需大家都下载一样的东西。

**Comment by viqbgrg** [comment]
@allanpk716 还有一个问题, rod 不能提供arm64的chrome版本下载, 能不能不完全依赖go rod的chrome的下载安装,可以使用系统安装的chrome吗?

**Comment by allanpk716** [comment]
可以的，我在 Windows 开发就是直接用 chrome 的

**Comment by viqbgrg** [comment]
rod 是可以指定chrome执行文件的路径,但是chinesesubfinder没有这样的入口,如果不进行设置,rod就自己去下载chrome,下载也没啥问题,主要是他没有提供arm64的版本的下载

**Comment by allanpk716** [comment]
https://go-rod.github.io/i18n/zh-CN/#/custom-launch

**Comment by allanpk716** [comment]
如果没有很特别的情况出现，大概率后续会把计算量大的任务放在服务器，或者分布式计算，交给一部分愿意当计算节点的用户上
