### ISSUE TITLE
强制停止无效

### ISSUE THREAD

**Issue by Cyberxxt** [allanpk716/ChineseSubFinder#294]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.25.0
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？
强制停止无效，点击了停止但是仍在运行任务

##当次日志
[info]: 2022-04-07 12:18:41 - PreDownloadProcess.Init() Start...
[warning]: 2022-04-07 12:18:41 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202247c31ViaG5Q.txt
[info]: 2022-04-07 12:18:41 - GetCode 2022-04-07 951275
[info]: 2022-04-07 12:18:41 - ClearRodTmpRootFolder Done
[info]: 2022-04-07 12:18:41 - PreDownloadProcess.Init() End
[info]: 2022-04-07 12:18:41 - PreDownloadProcess.Check() Start...
[info]: 2022-04-07 12:18:41 - UseHttpProxy = false
[info]: 2022-04-07 12:18:42 - UrlConnectednessTest Target Site https://baidu.com Speed: 309 ms, Status: true
[info]: 2022-04-07 12:18:42 - Check Sub Supplier Start...
[info]: 2022-04-07 12:18:42 - releaseAdblock start
[info]: 2022-04-07 12:18:42 - releaseAdblock end
[info]: 2022-04-07 12:18:59 - CronHelper.Stop() Done.
[info]: 2022-04-07 12:19:25 - zimuku Check Alive = true, Speed = 6384 ms
[info]: 2022-04-07 12:19:25 - xunlei Check Alive = true, Speed = 83 ms
[info]: 2022-04-07 12:19:25 - shooter Check Alive = true, Speed = 264 ms
[info]: 2022-04-07 12:19:26 - subhd Check Alive = true, Speed = 635 ms
[info]: 2022-04-07 12:19:26 - Check Sub Supplier End
[info]: 2022-04-07 12:19:26 - MovieFolder Index 0 -- /movie
[info]: 2022-04-07 12:19:26 - SeriesPaths Index 0 -- /series
[info]: 2022-04-07 12:19:26 - PreDownloadProcess.Check() End
[info]: 2022-04-07 12:19:26 - PreDownloadProcess.HotFix() Start...
[info]: 2022-04-07 12:19:26 - If you have a lot of videos, it may take a lot of time, just wait...
[info]: 2022-04-07 12:19:27 - PreDownloadProcess.HotFix() End
[info]: 2022-04-07 12:19:27 - PreDownloadProcess.ChangeSubNameFormat() Start...
[info]: 2022-04-07 12:19:27 - If you have a lot of videos, it may take a lot of time, just wait...
[info]: 2022-04-07 12:19:27 - DesSubFormatter == LateTimeSubFormatter then skip process
[info]: 2022-04-07 12:19:27 - PreDownloadProcess.ChangeSubNameFormat() End
[info]: 2022-04-07 12:19:27 - PreDownloadProcess.ReloadBrowser() Start...
[info]: 2022-04-07 12:19:39 - PreDownloadProcess.ReloadBrowser() End
[info]: 2022-04-07 12:19:39 - PreDownloadProcess.Wait() Done.
[info]: 2022-04-07 12:19:39 - Download One Started...
[info]: 2022-04-07 12:19:39 - NeedRestoreFixTimeLineBK == false
[info]: 2022-04-07 12:19:39 - Download Movie Sub Started...
[warning]: 2022-04-07 12:19:44 - IsSubHasChinese.HasChineseLang /movie/A.Hard.Day.2014.BluRay.1080p.x264.DTS-HDWinG/A.Hard.Day.2014.BluRay.1080p.x264.DTS-HDWinG.en.srt not chinese sub, is  英
[info]: 2022-04-07 12:19:44 - Skip A.Hard.Day.2014.BluRay.1080p.x264.DTS-HDWinG.mkv Sub Download, because movie has sub and published more than 2 years
[info]: 2022-04-07 12:19:44 - Skip A.Rainy.Day.in.New.York.2019.1080p.BluRay.x265.10bit.DTS-PTH.mkv Sub Download, because movie has sub and published more than 2 years
[info]: 2022-04-07 12:19:44 - Skip /movie/A.Sun.2019.2160p.NF.WEB-DL.DDP5.1.H265-NoGroup/A.Sun.2019.2160p.NF.WEB-DL.DDP5.1.H265-NoGroup.mkv Sub Download, because movie is Chinese
[warning]: 2022-04-07 12:19:44 - IsSubHasChinese.HasChineseLang /movie/A.Taxi.Driver.2017.BluRay.1080p.TrueHD.5.1.x265.10bit-BeiTai/A.Taxi.Driver.2017.BluRay.1080p.TrueHD.5.1.x265.10bit-BeiTai.en.srt not chinese sub, is  英
[info]: 2022-04-07 12:19:44 - Skip A.Taxi.Driver.2017.BluRay.1080p.TrueHD.5.1.x265.10bit-BeiTai.mkv Sub Download, because movie has sub and published more than 2 years
[info]: 2022-04-07 12:19:44 - Skip abgeschnitten.2018.german.1080p.bluray.x264-imperium.mkv Sub Download, because movie has sub and published more than 2 years
[info]: 2022-04-07 12:19:44 - Skip About.Time.2013.REPACK.TW.BluRay.1080p.AVC.DTS-HD.MA.5.1-DIY@CHDBits.ISO Sub Download, because movie has sub and published more than 2 years
[info]: 2022-04-07 12:19:44 - Queue 6 DlSub Start /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.mkv
[info]: 2022-04-07 12:19:44 - Queue 6 zimuku /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.mkv
[info]: 2022-04-07 12:19:44 - Queue 6 zimuku Start...
[error]: 2022-04-07 12:21:48 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:21:48 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:03 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:03 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:19 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:19 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:38 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:38 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:54 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:22:54 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:12 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:12 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:28 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:28 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:45 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:45 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:23:52 - zimuku keyword: Adam by Eve A Live in Animation 2022
[info]: 2022-04-07 12:23:52 - Queue 6 zimuku End...
[error]: 2022-04-07 12:23:52 - Queue 6 zimuku oneMovieDlSubInOneSite zimuku search keyword step0 not found, detail page url
[info]: 2022-04-07 12:23:52 - Queue 6 xunlei /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.mkv
[info]: 2022-04-07 12:23:52 - Queue 6 xunlei Start...
[info]: 2022-04-07 12:23:53 - Queue 6 xunlei End...
[info]: 2022-04-07 12:23:53 - Queue 6 shooter /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.mkv
[info]: 2022-04-07 12:23:53 - Queue 6 shooter Start...
[info]: 2022-04-07 12:23:53 - Queue 6 shooter End...
[info]: 2022-04-07 12:23:53 - Queue 6 subhd /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.mkv
[info]: 2022-04-07 12:23:53 - Queue 6 subhd Start...
[info]: 2022-04-07 12:24:34 - Queue 6 subhd End...
[info]: 2022-04-07 12:24:34 - Queue 6 DlSub End /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.mkv
[info]: 2022-04-07 12:24:34 - ----------------------------------
[info]: 2022-04-07 12:24:34 - OrgSubName: [subhd]_0_Turning.Red.2022.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-CM.chs.srt
[info]: 2022-04-07 12:24:34 - SubDownAt: /movie/Adam.by.Eve.A.Live.in.Animation.2022.1080p.NF.WEB-DL.DDP5.1.x264-PuTao.chinese(简).default.srt
[info]: 2022-04-07 12:24:34 - ----------------------------------
[info]: 2022-04-07 12:24:34 - Skip Adele One Night Only - 1080p H264  HDTV AAC [CC].mkv Sub Download, because movie has sub and downloaded or aired more than 3 months
[info]: 2022-04-07 12:24:35 - Queue 8 DlSub Start /movie/After.Yang.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES/After.Yang.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mkv
[info]: 2022-04-07 12:24:35 - Queue 8 zimuku /movie/After.Yang.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES/After.Yang.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mkv
[info]: 2022-04-07 12:24:35 - Queue 8 zimuku Start...
[error]: 2022-04-07 12:26:08 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:26:08 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:26:26 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:26:26 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:26:45 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:26:45 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:27:02 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:27:02 - zimukustep 3runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:27:19 - ZiMuKu step3 DownloadFile runtime error: invalid memory address or nil pointer dereference
[error]: 2022-04-07 12:27:19 - zimukustep 3runtime error: invalid memory address or nil pointer dereference

![image](https://user-images.githubusercontent.com/40683077/162120193-50e70275-02dd-4a52-9565-51e677b518a1.png)

**Comment by HansRen1024** [comment]
同样的问题~
我设备是Sonology DS920+， DSM7.x， 通过docker-compose安装的chinesesubfinder v0.25.0。

**Comment by zoengzihaam** [comment]
同样的问题+1
Sonology DS920+， DSM6.x，通过docker-cli安装的chinesesubfinder v0.25.0。

**Comment by allanpk716** [comment]
1. 你们需要去收集 docker 的日志，那边完整些
2. 教程里提了两点：
    * 第一次使用会进行原有字幕的扫描和格式化改名操作
    * 部分扫描耗时操作暂时还没空把 context 传入进去，也就是某些情况下无法马上终止
3. 最近大范围重构，等更新

**Comment by allanpk716** [comment]
最新版本调整了下载的逻辑，现在是每个任务是独立的。试试新的。
