### ISSUE TITLE
出现 HotFixProcess() open /media/movies2 premisson denied

### ISSUE THREAD

**Issue by nzl5423** [allanpk716/ChineseSubFinder#296]
版本号 v0.25.0
按照教程
HotFixProcess() open /media/movies premisson denied

已经把docker 权限设置成everyone 读写权限，依然出现此问题

需要把实际的媒体路径设置成everyone 读写权限，才可以正常运行

**Comment by allanpk716** [comment]
权限相关的问题你可以看看 https://sleele.com/2021/06/25/docker-chinesesubfinder-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E8%87%AA%E5%8A%A8%E4%B8%8B%E8%BD%BD/  的教程
