### ISSUE TITLE
能否支持下文件名匹配的模式，而不是只有nfo或者xml匹配

### ISSUE THREAD

**Issue by xcgx** [allanpk716/ChineseSubFinder#299]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.24.0

环境: docker

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？
针对[movie_robot](https://github.com/pofey/movie_robot)或类似项目优化
其刮削过的目录如下：
电影
\movie\加勒比海盗1：黑珍珠号的诅咒 (2003) [tmdbid=22]\加勒比海盗1：黑珍珠号的诅咒 (2003) [tmdbid=22] - 2160p x265 10bit.mkv
电视剧
\tv\良医 (2017) [tmdbid=71712]\Season 1\良医 S01E01 - 2160p H265 AAC.mp4
能不能优化基于规范填写的文件名的匹配，目前的规则似乎只会读取nfo或xml没有则跳过

附上目前跳过的日志
[WARNING]: 2022-04-13 10:14:46 - SkipChineseMovie /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv no metadata file, movie.xml or *.nfo
[ERROR]: 2022-04-13 10:14:46 - MovieNeedDlSub.GetImdbInfo4Movie no metadata file, movie.xml or *.nfo
[INFO]: 2022-04-13 10:14:46 - Queue 4 DlSub Start /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv
[INFO]: 2022-04-13 10:14:46 - Queue 4 zimuku /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv
[INFO]: 2022-04-13 10:14:46 - Queue 4 zimuku Start...
Download: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Linux_x64/901912/chrome-linux.zip
[INFO]: 2022-04-13 10:14:47 - Queue 4 zimuku End...
[ERROR]: 2022-04-13 10:14:47 - Queue 4 zimuku oneMovieDlSubInOneSite mkdir /.cache: permission denied
[INFO]: 2022-04-13 10:14:47 - Queue 4 xunlei /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv
[INFO]: 2022-04-13 10:14:47 - Queue 4 xunlei Start...
[INFO]: 2022-04-13 10:14:47 - Queue 4 xunlei End...
[INFO]: 2022-04-13 10:14:47 - Queue 4 subhd /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv
[INFO]: 2022-04-13 10:14:47 - Queue 4 subhd Start...
[ERROR]: 2022-04-13 10:14:47 - model.GetImdbInfo no metadata file, movie.xml or *.nfo
[ERROR]: 2022-04-13 10:14:47 - VideoNameSearchKeywordMaker year to int strconv.Atoi: parsing "": invalid syntax
Download: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Linux_x64/901912/chrome-linux.zip
[ERROR]: 2022-04-13 10:14:47 - subhd keyword: 生化危机：欢迎来到浣熊市
[INFO]: 2022-04-13 10:14:47 - Queue 4 subhd End...
[ERROR]: 2022-04-13 10:14:47 - Queue 4 subhd oneMovieDlSubInOneSite mkdir /.cache: permission denied
[INFO]: 2022-04-13 10:14:47 - Queue 4 DlSub End /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv
[INFO]: 2022-04-13 10:14:47 - no sub found 生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.
https://github.com/pofey/movie_robot

**Comment by allanpk716** [comment]
没打算，以后对没有削刮器处理过的都不会优先支持。不像浪费时间解决命名读取和解析的问题。

**Comment by allanpk716** [comment]
1. 既然都削刮了，那是把 nfo 和 xml 缓存到视频相同目录吧
2. 两个项目的目标不一样

再给你理一下思路：
1. 国内那些字幕站点出字幕的质量和速度快？zimuku、subhd（不考虑具体字幕组的网站为前提）
2. 他们都支持 IMDB ID 搜索
3. 既然你们都做了自动化下载了，IMDB ID 是不是默认就有

基于上述三点，你再想想，文件名搜索的意义多大，以前为何那么多字幕下载工具没有满足大家的需求呢。

**Comment by pofey** [comment]
> 1. 既然都削刮了，那是把 nfo 和 xml 缓存到视频相同目录吧
> 2. 两个项目的目标不一样
> 
> 再给你理一下思路：
> 
> 1. 国内那些字幕站点出字幕的质量和速度快？zimuku、subhd（不考虑具体字幕组的网站为前提）
> 2. 他们都支持 IMDB ID 搜索
> 3. 既然你们都做了自动化下载了，IMDB ID 是不是默认就有
> 
> 基于上述三点，你再想想，文件名搜索的意义多大，以前为何那么多字幕下载工具没有满足大家的需求呢。

刮削是指自动下载相关的简介、海报、缩略图等资料，这件事emby、plex、jellyfin等任何一款软件都完成得很好，他们只是弱在中文资源识别准确率，这个轮子不必造。
至于issue作者提及的需求，无外乎是你的程序对标准元数据降级做文件名简单解析，而且要求的还是对emby标准命名规范文件做解析，从哪个角度来看这都非常合理，你只是拿到tmdbid查一下imdbid，仍然不破坏坚持使用imdbid搜索的实现。不过你不支持没关系，尊重你对自己设计软件的理解和思考。
你这个软件当初觉得设计的还不错，专注字幕下载挺好，之前一直都是推用户在用，很无奈，很多事情这么久了也没解决好，不得不自己做。

**Comment by allanpk716** [comment]
我还是觉得你回到我提的三点来讨论，文件名搜索的必要性。如果你不削刮，文件名搜索就有用，也说过不削刮，文件名搜索准确度低，何必纠结这个呢？你项目挺好的啊，加油。

**Comment by pofey** [comment]
> 我还是觉得你回到我提的三点来讨论，文件名搜索的必要性。如果你不削刮，文件名搜索就有用，也说过不削刮，文件名搜索准确度低，何必纠结这个呢？你项目挺好的啊，加油。

有数据证明文件名搜索那几个字幕网站准确度低于imdbid么？拉对比，以及imdbid搜得到，但名称搜不到的案例出来看看。做技术的下结论要严谨，主观评估没什么值得讨论的。

**Comment by allanpk716** [comment]
嗨，我说不想优先考虑字幕搜索，应该是 IMDB ID 优先，我真的不严谨，没得数据，你觉得你对就好了啊。

代码一直都是 IMDB ID 优先，然后才是文件名搜索，如果有问题，看提交记录嘛。

这个 issues 我理解是想不在削刮后的文件名也想支持文件名搜索，所以我说不支持啊，我理解错是我的问题嘛。

以及你看看这文件名 ` /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv` 这种取巧 把 tmdbid 放在文件名上的规范合适嘛，说了规范很重要，文件名就是规范松散。我又不做削刮器，我没法控制大家的文件名规范，那么我说用 IMDB ID 有啥问题嘛。

## zimuku
![image](https://user-images.githubusercontent.com/1176000/167785961-3a077836-1adf-4b40-8ceb-7b2319878079.png)
## subhd
![image](https://user-images.githubusercontent.com/1176000/167786089-e7217000-44ab-4ca0-9e2d-13ce74950926.png)

**Comment by allanpk716** [comment]
代码明显的逻辑就是，如果 IMDB ID 找不到，那么就认为削刮程度低，不想浪费时间去解析文件名

**Comment by allanpk716** [comment]
你项目挺好的啊，我不支持的你可以去优化新增啊，这个不就是我做字幕下载器的初衷嘛，找到自己的痛点去做啊。设计边界这个每个人有每个人的想法啊，你又何必说服我呢。

真心等你的工具强大啊，花钱买服务有人帮搞定，我一直觉得很爽啊。不折腾我了吧，有啥还能够聊一下实现细节呢···要不加个？

**Comment by pofey** [comment]
> 以及你看看这文件名 ` /media/movie/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458]/生化危机：欢迎来到浣熊市 (2021) [tmdbid=460458] - 2160p Remux HEVC TrueHD Atmos.mkv` 这种取巧 把 tmdbid 放在文件名上的规范合适嘛，说了规范很重要，文件名就是规范松散。我又不做削刮器，我没法控制大家的文件名规范，那么我说用 IMDB ID 有啥问题嘛。

我只在回应1个你说取巧的点，建议你好好读读，这是Emby官方定义的命名标准，这有助于帮助Emby解决同名同年电影误识别最有效的方式，在你眼里成不规范命名了，下结论有点太草率了。
https://support.emby.media/support/solutions/articles/44001159102-movie-naming

**Comment by allanpk716** [comment]
我觉得吧，咱们还是别说这个了，既然你觉得你对，就对啊。

Emby 说支持这样的命名，意思是广泛认可了？别杠了，散了吧。

**Comment by pofey** [comment]
> 我觉得吧，咱们还是别说这个了，既然你觉得你对，就对啊。
> 
> Emby 说支持这样的命名，意思是广泛认可了？别杠了，散了吧。

都说是杠了，就不砸你场子了。

**Comment by allanpk716** [comment]
别啊，你都来这里宣传你的工具了，我也没说什么啊。

我没场子啊，也不靠这个赚钱，做开源给大家爽一爽，不用我也没得损失啊，这玩意本来就是满足我自己的需求，顺带给大家用。

**Comment by pofey** [comment]
> 别啊，你都来这里宣传你的工具了，我也没说什么啊。
> 
> 我没场子啊，也不靠这个赚钱，做开源给大家爽一爽，不用我也没得损失啊，这玩意本来就是满足我自己的需求，顺带给大家用。

哈哈哈，别把话说的好像谁要指望这么小众个领域赚钱一样，天花板太低，钱还不够折腾设备的。

**Comment by pofey** [comment]
卡个门槛，就看不惯白嫖的，不过对你可以不用钱设门槛，留邮箱我给你发一个
