### ISSUE TITLE
docker, /app/SeriesFolder 剧集没有下载字幕

### ISSUE THREAD

**Issue by shichao402** [allanpk716/ChineseSubFinder#3]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.7.1

环境: docker

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/1974733/123400569-7bb45480-d5d8-11eb-9daa-13b71ace23ca.png)
看起来/app/SeriesFolder下的剧集没有下载字幕, 日志里只看到/app/MovieFolder相关信息, 没有SeriesFolder的

目录映射看起来是对的.
![image](https://user-images.githubusercontent.com/1974733/123400779-b1593d80-d5d8-11eb-8a91-29ed308d8f35.png)

## 你的问题弄重现嘛？

能够重现, 重启docker依然如此

## 你期望的结果

剧集目录可以正确的拉到字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

![image](https://user-images.githubusercontent.com/1974733/123401422-5aa03380-d5d9-11eb-831f-aa6e0c504562.png)

## 出错的日志信息可以复制一些出来吗？
[ChineseSubFinder--202106250000--.log](https://github.com/allanpk716/ChineseSubFinder/files/6715051/ChineseSubFinder--202106250000--.log)

**Comment by SuperNG6** [comment]
如果是新版，请填写PUID和GUID，否则没有写入权限，具体请参照这篇文章  
https://sleele.com/2021/06/25/docker-chinesesubfinder-中文字幕自动下载/

**Comment by allanpk716** [comment]
1. 你的 config.xml 文件可以也发来看看吗？
2. 你的连续剧有用削刮器（TinyMediaManager 或者 Emby ）处理过吗？比如你的《白色巨塔》，目录内是否有 tvshow.nfo 这个文件？连续剧必须读取这个文件内的 IMDB ID ；
![image](https://user-images.githubusercontent.com/1176000/123403358-46f5cc80-d5db-11eb-8cb1-0ca063fd08f5.png)

3. 连续剧中的每一集的命名是否规范，如果用削刮器处理过应该没问题；
![image](https://user-images.githubusercontent.com/1176000/123403219-22015980-d5db-11eb-839e-6b83711090e8.png)

**Comment by allanpk716** [comment]
> 如果是新版，请填写PUID和GUID，否则没有写入权限，具体请参照这篇文章  
> 
> https://sleele.com/2021/06/25/docker-chinesesubfinder-中文字幕自动下载/

合并了你的改动，目前还没有推送到 docker hub，再测试 work flow …所以等 v0.8 的镜像再用对应新的 media 目录…得晚上晚一些

**Comment by shichao402** [comment]
> 1. 你的 config.xml 文件可以也发来看看吗？
> 2. 你的连续剧有用削刮器（TinyMediaManager 或者 Emby ）处理过吗？比如你的《白色巨塔》，目录内是否有 tvshow.nfo 这个文件？连续剧必须读取这个文件内的 IMDB ID ；
>    ![image](https://user-images.githubusercontent.com/1176000/123403358-46f5cc80-d5db-11eb-8cb1-0ca063fd08f5.png)
> 3. 连续剧中的每一集的命名是否规范，如果用削刮器处理过应该没问题；
>    ![image](https://user-images.githubusercontent.com/1176000/123403219-22015980-d5db-11eb-839e-6b83711090e8.png)

1. 
config.yaml
`
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 2h
Threads: 4
SubTypePriority: 0
DebugMode: true
SaveMultiSub: false
MovieFolder: /app/MovieFolder
SeriesFolder: /app/SeriesFolder
`

2,3. 我没有使用tmm或者emby, 目前用jellyfin的插件完成刮削, rarbg来的文件命名比较规范绝大部分元数据都能刮削到. 没有单独存储nfo. 一定要目录下有tvshow.nfo么, 我不确定jellyfin能不能把nfo存储到同目录并且命名为tvshow

**Comment by allanpk716** [comment]
> config.yaml
> `UseProxy: false HttpProxy: http://127.0.0.1:10809 EveryTime: 2h Threads: 4 SubTypePriority: 0 DebugMode: true SaveMultiSub: false MovieFolder: /app/MovieFolder SeriesFolder: /app/SeriesFolder`
> 
> 2,3. 我没有使用tmm或者emby, 目前用jellyfin的插件完成刮削, rarbg来的文件命名比较规范绝大部分元数据都能刮削到. 没有单独存储nfo. 一定要目录下有tvshow.nfo么, 我不确定jellyfin能不能把nfo存储到同目录并且命名为tvshow

那你现在某一个连续剧的目录下面，有什么 nfo 文件吗？能发来看看么

**Comment by allanpk716** [comment]
> 2,3. 我没有使用tmm或者emby, 目前用jellyfin的插件完成刮削, rarbg来的文件命名比较规范绝大部分元数据都能刮削到. 没有单独存储nfo. 一定要目录下有tvshow.nfo么, 我不确定jellyfin能不能把nfo存储到同目录并且命名为tvshow

jellyfin 就是 emby 的分支，你可以在相应的媒体目录设置中把 nfo 文件保存到视频的同级目录。这个忘记在 ReadMe 描述了。

**Comment by allanpk716** [comment]
> 2,3. 我没有使用tmm或者emby, 目前用jellyfin的插件完成刮削, rarbg来的文件命名比较规范绝大部分元数据都能刮削到. 没有单独存储nfo. 一定要目录下有tvshow.nfo么, 我不确定jellyfin能不能把nfo存储到同目录并且命名为tvshow

可以看看这两个文档的描述：

[削刮器的推荐设置](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%89%8A%E5%88%AE%E5%99%A8%E7%9A%84%E6%8E%A8%E8%8D%90%E8%AE%BE%E7%BD%AE.md)

[连续剧如何搜索字幕](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E5%A6%82%E4%BD%95%E6%90%9C%E7%B4%A2%E5%AD%97%E5%B9%95.md)

**Comment by shichao402** [comment]
![image](https://user-images.githubusercontent.com/1974733/123534808-5186a200-d752-11eb-8ea2-418603c3823b.png)
找了一部没字幕的, 确定nfo有了, 重启docker,看起来仍然没有处理

日志
[ChineseSubFinder--202106270000--.log](https://github.com/allanpk716/ChineseSubFinder/files/6721112/ChineseSubFinder--202106270000--.log)
相关nfo
[Key.and.Peele.S02.1080p.BluRay.x264-SADPANDA[rartv].zip](https://github.com/allanpk716/ChineseSubFinder/files/6721113/Key.and.Peele.S02.1080p.BluRay.x264-SADPANDA.rartv.zip)

**Comment by allanpk716** [comment]
> ![image](https://user-images.githubusercontent.com/1974733/123534808-5186a200-d752-11eb-8ea2-418603c3823b.png)
> 找了一部没字幕的, 确定nfo有了, 重启docker,看起来仍然没有处理
> 
> 日志
> [ChineseSubFinder--202106270000--.log](https://github.com/allanpk716/ChineseSubFinder/files/6721112/ChineseSubFinder--202106270000--.log)
> 相关nfo
> [Key.and.Peele.S02.1080p.BluRay.x264-SADPANDA[rartv].zip](https://github.com/allanpk716/ChineseSubFinder/files/6721113/Key.and.Peele.S02.1080p.BluRay.x264-SADPANDA.rartv.zip)

看了你提供的 nfo 文件，我对 tvshow.nfo 单独处理了 imdb_id 字段（之前没有处理，是因为在我这边 imdbid 以及 imdb_id 有些剧集这个字段信息是错误的） 这个字段。对于每一集程序需要的是 nfo 中的 aired 字段，以及对应每一集 nfo 名称包含 SxEx ，所以应该解析没有问题。推送了 v0.8.6 ，可以试试再反馈。

**Comment by shichao402** [comment]
<img width="973" alt="截屏2021-06-28 02 00 39" src="https://user-images.githubusercontent.com/1974733/123554824-7f9cce00-d7b4-11eb-9ef8-fee08dc8d3a5.png">
目录结构和之前一样. 重启容器后的日志.

[ChineseSubFinder--202106280000--.log](https://github.com/allanpk716/ChineseSubFinder/files/6722080/ChineseSubFinder--202106280000--.log)

**Comment by allanpk716** [comment]
> <img alt="截屏2021-06-28 02 00 39" width="973" src="https://user-images.githubusercontent.com/1974733/123554824-7f9cce00-d7b4-11eb-9ef8-fee08dc8d3a5.png">
> 
> 目录结构和之前一样. 重启容器后的日志.
> [ChineseSubFinder--202106280000--.log](https://github.com/allanpk716/ChineseSubFinder/files/6722080/ChineseSubFinder--202106280000--.log)

如果用的是最新的版本，建议看看最新的 docker-compose 以及 config.xml 的变更，现在是使用 /media  /conif 来挂载视频文件和配置日志的。

以及，连续剧仅仅支持搜索一级目录。比如你挂载的连续剧为，

SeriesFolder: /media/连续剧

那么支持搜索 

* /media/连续剧/连续剧1 
* /media/连续剧/连续剧2

不支持搜索
*  /media/连续剧/连续剧3/连续剧3-1

暂时的想法是这个搜索的逻辑，推荐的目录结构稍后会补齐文档

**Comment by shichao402** [comment]
原来不支持多级目录, 我的目录结构特殊一点, 一个drive同步, 一个下载, 所以多一层子目录.
处理了一下目录结构, 可以了, 感谢

**Comment by allanpk716** [comment]
> 原来不支持多级目录, 我的目录结构特殊一点, 一个drive同步, 一个下载, 所以多一层子目录.
> 处理了一下目录结构, 可以了, 感谢

后续考虑下，连续剧是否以当前目录找到 tvshow.nfo 来判断是否是一部连续剧。这样就映射总目录，程序遍历所有的子目录。
