### ISSUE TITLE
v0.12.0 lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#30]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.12.0

环境: docker

## 你遇到什么问题了？

出现

`lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found`

应该是引入 gorm go-sqlite 导致的，编译版本需求过高，部署的 linux 版本只到 2.27，linux 不是很熟，需要找一下解决方案。最差需要去除 gorm 模块。

**Comment by allanpk716** [comment]
临时方案是使用 v0.11.1

**Comment by allanpk716** [comment]
docker hub 的 v0.12.0 以及 latest 删除了，避免更多人受影响。同时是带来一个问题，在家和公司在配置 docker 镜像也无法拉取 v0.11.1 ···所以没法推送 v0.11.1 为 latest ····现在再测试 github 的 Actions 重新编译推送 v0.11.1 的 docker 镜像上去

**Comment by SuperNG6** [comment]
如果说是运行环境glibc版本低到是好解决，镜像换成`lsiobase/ubuntu:focal`就可以了
```
root@fa34a2cb26ce:/# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by allanpk716** [comment]
> 如果说是运行环境glibc版本低到是好解决，镜像换成`lsiobase/ubuntu:focal`就可以了
> 
> ```
> root@fa34a2cb26ce:/# ldd --version
> ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> ```

lsiobase/ubuntu:bionic 的 glibc 是2.27

而 chinesesubfinder 在  FROM golang:1.15-buster 中编译出来，因为加入了 gorm 和 sqlite3 所以要求 glibc 是2.28 ···

这几天再测试怎么找合适的编译或者部署的镜像。比如把部署的镜像用来编译，目前坑很多···

**Comment by SuperNG6** [comment]
> > 如果说是运行环境glibc版本低到是好解决，镜像换成`lsiobase/ubuntu:focal`就可以了
> > ```
> > root@fa34a2cb26ce:/# ldd --version
> > ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
> > Copyright (C) 2020 Free Software Foundation, Inc.
> > This is free software; see the source for copying conditions.  There is NO
> > warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> > Written by Roland McGrath and Ulrich Drepper.
> > ```
> 
> lsiobase/ubuntu:bionic 的 glibc 是2.27
> 
> 而 chinesesubfinder 在 FROM golang:1.15-buster 中编译出来，因为加入了 gorm 和 sqlite3 所以要求 glibc 是2.28 ···
> 
> 这几天再测试怎么找合适的编译或者部署的镜像。比如把部署的镜像用来编译，目前坑很多···

我基于ubuntu官方镜像简单了构建一个带有go环境的镜像，你试一下
https://github.com/SuperNG6/ubuntu-golang

```
> Executing task: docker run --rm -it  ubuntu-go:latest <

root@d5602d827f2b:/downloads# go version
go version go1.15.14 linux/amd64
```

**Comment by allanpk716** [comment]
> > > 如果说是运行环境glibc版本低到是好解决，镜像换成`lsiobase/ubuntu:focal`就可以了
> > > ```
> > > root@fa34a2cb26ce:/# ldd --version
> > > ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
> > > Copyright (C) 2020 Free Software Foundation, Inc.
> > > This is free software; see the source for copying conditions.  There is NO
> > > warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> > > Written by Roland McGrath and Ulrich Drepper.
> > > ```
> > 
> > 
> > lsiobase/ubuntu:bionic 的 glibc 是2.27
> > 而 chinesesubfinder 在 FROM golang:1.15-buster 中编译出来，因为加入了 gorm 和 sqlite3 所以要求 glibc 是2.28 ···
> > 这几天再测试怎么找合适的编译或者部署的镜像。比如把部署的镜像用来编译，目前坑很多···
> 
> 我基于ubuntu官方镜像简单了构建一个带有go环境的镜像，你试一下
> https://github.com/SuperNG6/ubuntu-golang
> 
> ```
> > Executing task: docker run --rm -it  ubuntu-go:latest <
> 
> root@d5602d827f2b:/downloads# go version
> go version go1.15.14 linux/amd64
> ```

刚去看了还没有编译发布到 docker hub ，看到了会试试

**Comment by SuperNG6** [comment]
armv7版构建失败，所以没推到docker hub，目前先构建了两个架构的，x64和arm64版本
https://hub.docker.com/r/superng6/go/tags?page=1&ordering=last_updated

**Comment by allanpk716** [comment]
> armv7版构建失败，所以没推到docker hub，目前先构建了两个架构的，x64和arm64版本
> https://hub.docker.com/r/superng6/go/tags?page=1&ordering=last_updated

看到了，正在测试。

我想整的方向是这个 https://stackoverflow.com/questions/55450061/go-build-with-another-glibc

想在编译的时候指定 glibc 的版本，这样万一以后部署的镜像升级了，也能有版本指定到对应的版本去用。但是看了下都是要额外编译的，貌似挺麻烦以及耗时。

**Comment by allanpk716** [comment]
> armv7版构建失败，所以没推到docker hub，目前先构建了两个架构的，x64和arm64版本
> https://hub.docker.com/r/superng6/go/tags?page=1&ordering=last_updated

刚测试了下，本地编译会提示这个，如下截图：
![image](https://user-images.githubusercontent.com/1176000/126762051-647381bf-780c-4a2b-935c-85498f877afe.png)

如果是用 github actions 去build 会提示如下信息：
![image](https://user-images.githubusercontent.com/1176000/126762110-56c79d1f-3cf8-4376-8e84-03f52ec9efc0.png)

编译链接如下：
https://github.com/allanpk716/ChineseSubFinder/runs/3142156780?check_suite_focus=true

貌似是你提到的 arm7 不支持，准备从 Build Image.yml 先去除

`platforms: linux/amd64,linux/arm/v7,linux/arm64`

arm7 支持。如果你那边 arm7 过了，再加回来。但是，目前本地编译是不过的，见图1。

**Comment by SuperNG6** [comment]
gcc没有安

**Comment by allanpk716** [comment]
整个项目翻了下，就是为了自带解压缩包的功能，所以引用的第三方库需要 CGO=1 的支持，估计后续会慎重考虑要不要外置解压的功能，毕竟现在的第三方的包没有默认支持 io.reader 的接口，也不想去改。所以说白了无法在纯内存中完成压缩包的下载解压，逻辑判断再写目标目录。

**Comment by SuperNG6** [comment]
更新了镜像依赖，现在应该可以了

**Comment by allanpk716** [comment]
> 更新了镜像依赖，现在应该可以了
> 可以考虑通过apt安装unrar，unzip，实现解压功能

OK，我去试试。arm7 这个我翻了下官方的 golang 1.15 buster  [dockerfile](https://github.com/docker-library/golang/blob/d23c409d5096cd3e6b18d977e1f70473e2726461/1.15/buster/Dockerfile)，晚点我也试试看能改成你推荐的这个 ubuntu 没有

**Comment by allanpk716** [comment]
> 更新了镜像依赖，现在应该可以了
> 可以考虑通过apt安装unrar，unzip，实现解压功能

还是遇到问题呢，跟我自己弄的镜像遇到的问题类似。会提示 go 找不到或者使用系统的 source /etc/profile 这种系统的 source  命令都提示找不到。单独启动 build 使用的 from 镜像，进去使用 cmd 是没问题的，只要在 dockerfile 中使用就有问题。

![image](https://user-images.githubusercontent.com/1176000/126783827-a6d4aa46-d8a1-4907-8bac-473e5ea0fee4.png)

**Comment by allanpk716** [comment]
网络太难了，心累···本地没法愉快的玩···用 actions 故障描述又太模糊了

![image](https://user-images.githubusercontent.com/1176000/126789925-62743aa0-ca35-429e-b438-02d02ef8c18a.png)

**Comment by SuperNG6** [comment]
网络问题很好解决，安装clash，开启局域网共享，dockerfile中，添加代理即可
`export https_proxy=http://172.17.0.1:7890 http_proxy=http://172.17.0.1:7890 all_proxy=socks5://172.17.0.1:7891`
运行环境干脆不用 LSIO的镜像了，简单处理debian buster 加入s6，这样开发环境和运行环境就一致了
superng6/debian

**Comment by allanpk716** [comment]
> 网络问题很好解决，安装clash，开启局域网共享，dockerfile中，添加代理即可
> `export https_proxy=http://172.17.0.1:7890 http_proxy=http://172.17.0.1:7890 all_proxy=socks5://172.17.0.1:7891`
> 运行环境干脆不用 LSIO的镜像了，简单处理debian buster 加入s6，这样开发环境和运行环境就一致了
> https://github.com/SuperNG6/docker-debian
> superng6/debian

代理开了也不行，感觉是这个 fake-useragent 有问题，fork 了一份重新指向到自己的项目也遇到问题。Windows 下 go mod tidy 是没得问题的，在 docker 下或者是在 github actions 执行 go mod tidy  也是遇到问题。估计不是我本地代理的问题了。

这个是手动编译的结果， go mod tidy  就是过不了。
https://github.com/allanpk716/ChineseSubFinder/runs/3144404261?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1176000/126797501-bac016f9-3af6-4996-8743-4af99f95c59a.png)

**Comment by allanpk716** [comment]
更换了  fake-useragent 还是一样的问题。docker （无论是 Windows 还是 github actions）里面 go mod tidy 就是连不上服务器···

![image](https://user-images.githubusercontent.com/1176000/126802392-fb42817c-e1a9-4c37-a66f-6317033a422d.png)

**Comment by allanpk716** [comment]
v0.12.1 将依赖 CGO 的 7z 解压库和 Sqlite 给移除了。替换为 golang 原生版本开发的版本。所以跳过了这个问题。
