### ISSUE TITLE
为什么启动的时候会访问很多qq.com相关的网址?

### ISSUE THREAD

**Issue by wjjchen** [allanpk716/ChineseSubFinder#300]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.25.0

环境: docker

## 你想要新增或者改进什么功能？

为什么启动的时候会访问很多qq.com相关的网址?
![截屏2022-04-13 下午3 03 20](https://user-images.githubusercontent.com/8358044/163119085-0ccbed43-343e-40e9-b01a-4785997cd69d.png)

**Comment by allanpk716** [comment]
你得问字幕下载网站
