### ISSUE TITLE
很多电影扫描不到

### ISSUE THREAD

**Issue by xfate** [allanpk716/ChineseSubFinder#301]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: lastet
>
> 环境: 群晖918+docker
>

## 你遇到什么问题了？

> 很多电影扫描不到

## 你的问题弄重现嘛？

> 能重现

## 你期望的结果

> 扫描到全部电影

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "user_info":{
        "username":"xxx",
        "password":"xxx"
    },
    "common_settings":{
        "scan_interval":"6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/movie",
            "/media/movie1"
        ],
        "series_paths":[
            "/media/tv",
            "/media/tv1",
            "/media/tv2"
        ]
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_http_proxy":false,
            "http_proxy_address":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1
    },
    "emby_settings":{
        "enable":true,
        "address_url":"http://192.168.50.182:8096/",
        "api_key":"xxxxxx",
        "max_request_video_number":3000,
        "skip_watched":false,
        "movie_paths_mapping":{
            "/media/movie":"/volume2/video2/喜剧",
            "/media/movie1":"/volume1/video/电影"
        },
        "series_paths_mapping":{
            "/media/tv":"/volume2/video2/tv",
            "/media/tv1":"/volume1/video/电视剧",
            "/media/tv2":"/volume1/video/纪录片"
        }
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息
```
json
{
   "cap_add" : null,
   "cap_drop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "devices" : null,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : true,
   "entrypoint_default" : "/init",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "LANGUAGE",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "LANG",
         "value" : "en_US.UTF-8"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "TZ",
         "value" : "Asia/Shanghai"
      },
      {
         "key" : "PUID",
         "value" : "1026"
      },
      {
         "key" : "PGID",
         "value" : "100"
      }
   ],
   "exporting" : false,
   "id" : "kk",
   "image" : "allanpk716/chinesesubfinder:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "allanpk716-chinesesubfinder1",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 19035,
         "host_port" : 19035,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/video/纪录片",
         "mount_point" : "/media/tv2",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/video/电视剧",
         "mount_point" : "/media/tv1",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/video/电影",
         "mount_point" : "/media/movie1",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/video2/喜剧",
         "mount_point" : "/media/movie",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/video2/tv",
         "mount_point" : "/media/tv",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/ChineseSubFinder",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}

```

## 请给出当次问题的完整日志

9 - shooter CheckAlive Error Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:28:28+08:00 is after 2022-04-10T23:59:59Z
[WARNING]: 2022-04-14 01:28:29 - shooter Check Alive = false
[INFO]: 2022-04-14 01:28:29 - Check Sub Supplier End
[INFO]: 2022-04-14 01:28:29 - MovieFolder Index 0 -- /media/movie1
[INFO]: 2022-04-14 01:28:29 - MovieFolder Index 1 -- /media/movie
[INFO]: 2022-04-14 01:28:29 - SeriesPaths Index 0 -- /media/tv
[INFO]: 2022-04-14 01:28:29 - SeriesPaths Index 1 -- /media/tv1
[INFO]: 2022-04-14 01:28:29 - SeriesPaths Index 2 -- /media/tv2
[INFO]: 2022-04-14 01:28:29 - PreDownloadProcess.Check() End
[INFO]: 2022-04-14 01:28:29 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-04-14 01:28:29 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-14 01:28:29 - PreDownloadProcess.HotFix() End
[INFO]: 2022-04-14 01:28:29 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-04-14 01:28:29 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-04-14 01:28:29 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-04-14 01:28:29 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-04-14 01:28:29 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-04-14 01:28:33 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-04-14 01:28:33 - PreDownloadProcess.Wait() Done.
[INFO]: 2022-04-14 01:28:33 - Download One Started...
[INFO]: 2022-04-14 01:28:33 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-04-14 01:28:33 - Refresh Emby Sub List Start...
[INFO]: 2022-04-14 01:28:33 - Refresh Emby Sub List Success
[INFO]: 2022-04-14 01:28:33 - GetUpdateVideoListFromEmby Start...
[INFO]: 2022-04-14 01:28:35 - GetUpdateVideoListFromEmby End
[INFO]: 2022-04-14 01:28:35 - Download Movie Sub Started...
[INFO]: 2022-04-14 01:28:35 - Movie Sub Dl From Emby API...
[INFO]: 2022-04-14 01:28:40 - Skip /media/movie/这个杀手不太冷静.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-04-14 01:28:44 - Queue 1 DlSub Start /media/movie/哥斯拉大战金刚[国英语音轨+中文字幕].Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS/Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS.mkv
[INFO]: 2022-04-14 01:28:44 - Queue 1 shooter Start...
[INFO]: 2022-04-14 01:28:44 - Queue 1 zimuku Start...
[INFO]: 2022-04-14 01:28:44 - Queue 1 xunlei Start...
[ERROR]: 2022-04-14 01:28:45 - shooter NewHttpClient: Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS.mkv Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:28:44+08:00 is after 2022-04-10T23:59:59Z
[INFO]: 2022-04-14 01:28:45 - Queue 1 shooter End...
[ERROR]: 2022-04-14 01:28:45 - Queue 1 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:28:44+08:00 is after 2022-04-10T23:59:59Z
[ERROR]: 2022-04-14 01:28:46 - zimuku keyword: tt5034838
[ERROR]: 2022-04-14 01:28:46 - getSubListFromKeyword IMDBID can not found sub /media/movie/哥斯拉大战金刚[国英语音轨+中文字幕].Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS/Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS.mkv Get "https://zmk.pw/search?q=tt5034838": x509: certificate is valid for pianyuan.org, www.pianyuan.org, not zmk.pw
[ERROR]: 2022-04-14 01:28:48 - zimuku keyword: Godzilla vs Kong 2021
[INFO]: 2022-04-14 01:28:48 - Queue 1 zimuku End...
[ERROR]: 2022-04-14 01:28:48 - Queue 1 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Godzilla+vs+Kong+2021": x509: certificate is valid for pianyuan.org, www.pianyuan.org, not zmk.pw
[INFO]: 2022-04-14 01:29:05 - Queue 1 xunlei End...
[INFO]: 2022-04-14 01:29:05 - Queue 1 DlSub End /media/movie/哥斯拉大战金刚[国英语音轨+中文字幕].Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS/Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS.mkv
[INFO]: 2022-04-14 01:29:05 - no sub found Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS.mkv
[INFO]: 2022-04-14 01:29:10 - Skip /media/movie/我和我的父辈 (2021)/我和我的父辈 (2021) 1080p AAC.mp4 Sub Download, because movie is Chinese
[INFO]: 2022-04-14 01:29:14 - Skip 哥斯拉大战金刚 (2021).MKV Sub Download, because movie has sub and downloaded or aired more than 3 months
[INFO]: 2022-04-14 01:29:18 - Skip Spider-Man.-.Into.the.Spider-Verse.蜘蛛侠：平行宇宙.(2018).1080p.DTS.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:22 - Skip 阿丽塔：战斗天使 (2019) 1080p DTSHD-MA.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:27 - Skip Mad.Max.-.Fury.Road.疯狂的麦克斯4：狂暴之路.(2015).1080p.Atmos.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:32 - Skip 阿凡达 (2009) 1080p DTSHD-MA.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:37 - Skip 少年派的奇幻漂流 (2012) 1080p DTSHD-MA.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:41 - Skip 极盗者 (2015) 1080p DTSHD-MA.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:45 - Skip /media/movie1/龙门飞甲 (2011)/龙门飞甲 (2011) 1080p PCM.iso Sub Download, because movie is Chinese
[INFO]: 2022-04-14 01:29:50 - Skip 云中行走 (2015) 1080p DTSHD-MA.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:29:57 - Skip 火星救援 (2015) 1080p DTSHD-MA.iso Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:02 - Queue 13 DlSub Start /media/movie/音乐僵尸 (1992)/音乐僵尸 (1992) 1080p AAC.ts
[INFO]: 2022-04-14 01:30:02 - Queue 13 shooter Start...
[INFO]: 2022-04-14 01:30:02 - Queue 13 xunlei Start...
[INFO]: 2022-04-14 01:30:02 - Queue 13 zimuku Start...
[INFO]: 2022-04-14 01:30:02 - Queue 13 xunlei End...
[ERROR]: 2022-04-14 01:30:03 - shooter NewHttpClient: 音乐僵尸 (1992) 1080p AAC.ts Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:30:02+08:00 is after 2022-04-10T23:59:59Z
[INFO]: 2022-04-14 01:30:03 - Queue 13 shooter End...
[ERROR]: 2022-04-14 01:30:03 - Queue 13 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:30:02+08:00 is after 2022-04-10T23:59:59Z
[ERROR]: 2022-04-14 01:30:04 - zimuku keyword: tt0121906
[ERROR]: 2022-04-14 01:30:04 - getSubListFromKeyword IMDBID can not found sub /media/movie/音乐僵尸 (1992)/音乐僵尸 (1992) 1080p AAC.ts Get "https://zmk.pw/search?q=tt0121906": x509: certificate is valid for pianyuan.org, www.pianyuan.org, not zmk.pw
[ERROR]: 2022-04-14 01:30:06 - zimuku keyword: 音乐僵尸
[INFO]: 2022-04-14 01:30:06 - Queue 13 zimuku End...
[ERROR]: 2022-04-14 01:30:06 - Queue 13 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=%E9%9F%B3%E4%B9%90%E5%83%B5%E5%B0%B8": x509: certificate is valid for pianyuan.org, www.pianyuan.org, not zmk.pw
[INFO]: 2022-04-14 01:30:06 - Queue 13 DlSub End /media/movie/音乐僵尸 (1992)/音乐僵尸 (1992) 1080p AAC.ts
[INFO]: 2022-04-14 01:30:06 - no sub found 音乐僵尸 (1992) 1080p AAC.ts
[INFO]: 2022-04-14 01:30:11 - Skip 星际穿越 - IMAX (2014) 1080p AC3.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:15 - Skip El.laberinto.del.fauno.潘神的迷宫.(2006).2160p.DTSHD-MA.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:19 - Skip Toy.Story.4.玩具总动员4.(2019).2160p.Atmos.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:24 - Skip Incredibles.2.超人总动员2.(2018).1080p.Atmos.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:28 - Skip 小丑 (2019) 2160p Atmos.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:33 - Skip 第一滴血5：最后的血 (2019) 2160p Atmos.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:37 - Skip V.for.Vendetta.V字仇杀队.(2006).720p.AAC.mp4 Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:42 - Skip John.Wick.-.Chapter.2.疾速特攻.(2017).1080p.AAC.mp4 Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:46 - Skip 一本漫画闯天涯 (1990) 1080p AAC.mp4 Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:50 - Skip 新精武门1991 (1991) 1080p AAC.mkv Sub Download, because movie has sub and published more than 2 years
[INFO]: 2022-04-14 01:30:55 - Queue 24 DlSub Start /media/movie/花田喜事 (1993)/花田喜事 (1993) 1080p AC3.mkv
[INFO]: 2022-04-14 01:30:55 - Queue 24 shooter Start...
[INFO]: 2022-04-14 01:30:55 - Queue 24 xunlei Start...
[INFO]: 2022-04-14 01:30:55 - Queue 24 zimuku Start...
[WARNING]: 2022-04-14 01:30:56 - DownFile.GetFileName is string.empty http://subtitle.v.geilijiasu.com/13/11/131194E8A2404C99F5CC9470D4737BA69E0DD2B7.srt
[WARNING]: 2022-04-14 01:30:56 - DownFile.GetFileName is string.empty http://subtitle.v.geilijiasu.com/56/9B/569B585EC1D494FFC5F09F2F45AA3EC323BF3318.srt
[WARNING]: 2022-04-14 01:30:56 - DownFile.GetFileName is string.empty http://subtitle.v.geilijiasu.com/21/2F/212F100D66499CD8493881BED5C0505C0D647C0B.srt
[INFO]: 2022-04-14 01:30:56 - Queue 24 xunlei End...
[ERROR]: 2022-04-14 01:30:56 - shooter NewHttpClient: 花田喜事 (1993) 1080p AC3.mkv Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:30:56+08:00 is after 2022-04-10T23:59:59Z
[INFO]: 2022-04-14 01:30:56 - Queue 24 shooter End...
[ERROR]: 2022-04-14 01:30:56 - Queue 24 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": x509: certificate has expired or is not yet valid: current time 2022-04-14T01:30:56+08:00 is after 2022-04-10T23:59:59Z
[ERROR]: 2022-04-14 01:30:58 - zimuku keyword: tt0107159
[ERROR]: 2022-04-14 01:30:58 - getSubListFromKeyword IMDBID can not found sub /media/movie/花田喜事 (1993)/花田喜事 (1993) 1080p AC3.mkv Get "https://zmk.pw/search?q=tt0107159": x509: certificate is valid for pianyuan.org, www.pianyuan.org, not zmk.pw
[ERROR]: 2022-04-14 01:31:00 - zimuku keyword: 花田喜事
[INFO]: 2022-04-14 01:31:00 - Queue 24 zimuku End...
[ERROR]: 2022-04-14 01:31:00 - Queue 24 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=%E8%8A%B1%E7%94%B0%E5%96%9C%E4%BA%8B": x509: certificate is valid for pianyuan.org, www.pianyuan.org, not zmk.pw
[INFO]: 2022-04-14 01:31:00 - Queue 24 DlSub End /media/movie/花田喜事 (1993)/花田喜事 (1993) 1080p AC3.mkv
[ERROR]: 2022-04-14 01:31:00 - PollName: MoviePool Index: 24 NewPoolWithFunc got panic runtime error: slice bounds out of range [18:13]
[INFO]: 2022-04-14 01:31:00 - --------------------------------------
[INFO]: 2022-04-14 01:31:00 - successList 24
[INFO]: 2022-04-14 01:31:00 - 0 /media/movie/第一滴血5：最后的血 (2019)/第一滴血5：最后的血 (2019) 2160p Atmos.mkv
[INFO]: 2022-04-14 01:31:00 - 1 /media/movie/新精武门1991 (1991)/新精武门1991 (1991) 1080p AAC.mkv
[INFO]: 2022-04-14 01:31:00 - 2 /media/movie/我和我的父辈 (2021)/我和我的父辈 (2021) 1080p AAC.mp4
[INFO]: 2022-04-14 01:31:00 - 3 /media/movie1/疯狂的麦克斯4：狂暴之路 (2015)/Mad.Max.-.Fury.Road.疯狂的麦克斯4：狂暴之路.(2015).1080p.Atmos.iso
[INFO]: 2022-04-14 01:31:00 - 4 /media/movie1/阿凡达 (2009)/阿凡达 (2009) 1080p DTSHD-MA.iso
[INFO]: 2022-04-14 01:31:00 - 5 /media/movie1/火星救援 (2015)/火星救援 (2015) 1080p DTSHD-MA.iso
[INFO]: 2022-04-14 01:31:00 - 6 /media/movie/音乐僵尸 (1992)/音乐僵尸 (1992) 1080p AAC.ts
[INFO]: 2022-04-14 01:31:00 - 7 /media/movie/潘神的迷宫 (2006)/El.laberinto.del.fauno.潘神的迷宫.(2006).2160p.DTSHD-MA.mkv
[INFO]: 2022-04-14 01:31:00 - 8 /media/movie1/极盗者 (2015)/极盗者 (2015) 1080p DTSHD-MA.iso
[INFO]: 2022-04-14 01:31:00 - 9 /media/movie1/龙门飞甲 (2011)/龙门飞甲 (2011) 1080p PCM.iso
[INFO]: 2022-04-14 01:31:00 - 10 /media/movie/这个杀手不太冷静.mp4
[INFO]: 2022-04-14 01:31:00 - 11 /media/movie/哥斯拉大战金刚[国英语音轨+中文字幕].Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS/Godzilla.vs.Kong.2021.2160p.HDR.UHD.BluRay.TrueHD.7.1.Atmos.2Audio.x265-10bit-HDS.mkv
[INFO]: 2022-04-14 01:31:00 - 12 /media/movie/哥斯拉大战金刚 (2021)/哥斯拉大战金刚 (2021).MKV
[INFO]: 2022-04-14 01:31:00 - 13 /media/movie/蜘蛛侠：平行宇宙 (2018)/Spider-Man.-.Into.the.Spider-Verse.蜘蛛侠：平行宇宙.(2018).1080p.DTS.mkv
[INFO]: 2022-04-14 01:31:00 - 14 /media/movie1/阿丽塔：战斗天使 (2019)/阿丽塔：战斗天使 (2019) 1080p DTSHD-MA.iso
[INFO]: 2022-04-14 01:31:00 - 15 /media/movie1/少年派的奇幻漂流 (2012)/少年派的奇幻漂流 (2012) 1080p DTSHD-MA.iso
[INFO]: 2022-04-14 01:31:00 - 16 /media/movie/一本漫画闯天涯 (1990)/一本漫画闯天涯 (1990) 1080p AAC.mp4
[INFO]: 2022-04-14 01:31:00 - 17 /media/movie1/云中行走 (2015)/云中行走 (2015) 1080p DTSHD-MA.iso
[INFO]: 2022-04-14 01:31:00 - 18 /media/movie1/星际穿越 - IMAX (2014)/星际穿越 - IMAX (2014) 1080p AC3.mkv
[INFO]: 2022-04-14 01:31:00 - 19 /media/movie/玩具总动员4 (2019)/Toy.Story.4.玩具总动员4.(2019).2160p.Atmos.mkv
[INFO]: 2022-04-14 01:31:00 - 20 /media/movie/小丑 (2019)/小丑 (2019) 2160p Atmos.mkv
[INFO]: 2022-04-14 01:31:00 - 21 /media/movie/V字仇杀队 (2006)/V.for.Vendetta.V字仇杀队.(2006).720p.AAC.mp4
[INFO]: 2022-04-14 01:31:00 - 22 /media/movie/疾速特攻 (2017)/John.Wick.-.Chapter.2.疾速特攻.(2017).1080p.AAC.mp4
[INFO]: 2022-04-14 01:31:00 - 23 /media/movie/超人总动员2 (2018)/Incredibles.2.超人总动员2.(2018).1080p.Atmos.mkv
[INFO]: 2022-04-14 01:31:00 - --------------------------------------
[INFO]: 2022-04-14 01:31:00 - noExecuteList 0
[INFO]: 2022-04-14 01:31:00 - --------------------------------------
[INFO]: 2022-04-14 01:31:00 - errorList 1
[INFO]: 2022-04-14 01:31:00 - 0 /media/movie/花田喜事 (1993)/花田喜事 (1993) 1080p AC3.mkv
[INFO]: 2022-04-14 01:31:00 - --------------------------------------
[INFO]: 2022-04-14 01:31:00 - Download Movie Sub End...
[INFO]: 2022-04-14 01:31:00 - Download Series Sub Started...

很多电影都扫描不到：
![image](https://user-images.githubusercontent.com/514000/163531930-5847ef6c-6b92-4368-aa08-a90188da1e11.png)

**Comment by allanpk716** [comment]
开debug，然后取看具体那个电影不进行扫描。目前的策略是中文电影是默认跳过的。

**Comment by xfate** [comment]
> 开debug，然后取看具体那个电影不进行扫描。目前的策略是中文电影是默认跳过的。

4-19 06:03:07 - GetRecentlyAddVideoListWithNoChineseSubtitle - GetRecentlyItems Count 1402
[DEBUG]: 2022-04-19 06:03:07 - Episode: 0 小猪佩奇 1 44
[DEBUG]: 2022-04-19 06:03:07 - Episode: 1 汪汪队立大功 5 13
[DEBUG]: 2022-04-19 06:03:07 - Episode: 2 CoComelon 0 53
[DEBUG]: 2022-04-19 06:03:07 - Movie: 3 人吓人
[DEBUG]: 2022-04-19 06:03:07 - Movie: 4 这个杀手不太冷
4-19 06:03:07 - Episode: 5 绝命毒师 2 6
[DEBUG]: 2022-04-19 06:03:07 - Episode: 6 生活大爆炸 9 2
[DEBUG]: 2022-04-19 06:03:07 - Episode: 7 生活大爆炸 3 3
[DEBUG]: 2022-04-19 06:03:07 - Movie: 8 少林足球
[DEBUG]: 2022-04-19 06:03:07 - Episode: 9 汪汪队立大功 2 38
[DEBUG]: 2022-04-19 06:03:07 - Movie: 10 末代皇帝
[DEBUG]: 2022-04-19 06:03:07 - Episode: 11 小猪佩奇 1 29
[DEBUG]: 2022-04-19 06:03:07 - Episode: 12 汪汪队立大功 1 27
[DEBUG]: 2022-04-19 06:03:07 - Episode: 13 皆大歡喜 古裝版 1 16
[DEBUG]: 2022-04-19 06:03:07 - Episode: 14 小猪佩奇 2 50
[DEBUG]: 2022-04-19 06:03:07 - Episode: 15 汪汪队立大功 1 34
[DEBUG]: 2022-04-19 06:03:07 - Episode: 16 汪汪队立大功 4 18
[DEBUG]: 2022-04-19 06:03:07 - Episode: 17 CoComelon 0 15
[DEBUG]: 2022-04-19 06:03:07 - Episode: 18 生活大爆炸 7 19
[DEBUG]: 2022-04-19 06:03:07 - Movie: 334 疯狂原始人2：新纪元
[DEBUG]: 2022-04-19 06:03:07 - Episode: 335 生活大爆炸 9 8
[DEBUG]: 2022-04-19 06:03:07 - Episode: 336 皆大歡喜 古裝版 1 60
[DEBUG]: 2022-04-19 06:03:07 - Episode: 337 皆大歡喜 古裝版 1 45
[DEBUG]: 2022-04-19 06:03:07 - Movie: 338 海底总动员
[DEBUG]: 2022-04-19 06:03:07 - Episode: 339 小猪佩奇 1 48
[DEBUG]: 2022-04-19 06:03:07 - Episode: 340 小猪佩奇 2 12
[DEBUG]: 2022-04-19 06:03:07 - Episode: 341 汪汪队立大功 1 5
[DEBUG]: 2022-04-19 06:03:07 - Movie: 342 马达加斯加的企鹅
Debug下是可以看到扫描到了这些电影的，但是最后没有去下载字幕，比如马达加斯加的企鹅，他是没有任何字幕的，但是他又台配国语音频（这个有影响？），也没搜到Skip的原因

**Comment by allanpk716** [comment]
详细日志在后面，这里是有那些。大概率是已经触发每次的字幕源下载次数限制。现在版本没得办法解决的，等我更新。
