### ISSUE TITLE
字幕功能較正之後的字幕在JELLYFIN裡沒法顯示

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#306]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: latest
>
> 环境: docker synology ds920+
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 只要是使用字幕較正功能調整過的字幕全部都沒法在jellyfin上顯示，這個問題從0.19的時候已經存在了

## 你的问题弄重现嘛？

> 能够重现，之前嘗試過較正之後沒法顯示，然後按照你的教程把較正弄回去之後就能正常顯示了

## 你期望的结果

> 字幕時間較正之後的字幕仍然能正常顯示

## 请给出当次问题的完整日志

> 日志:
[2022-04-18 00_55_19.log](https://github.com/allanpk716/ChineseSubFinder/files/8504803/2022-04-18.00_55_19.log)
有問題的電影是這幾部，全都是有經過字幕時間修正的
![image](https://user-images.githubusercontent.com/66216186/163787211-6d660bb1-d844-4b38-b8cc-11d12d8eb469.png)

**Comment by allanpk716** [comment]
你先排除这个字幕能够用其他视频播放器用，以及，没得具体数据，看不出。

**Comment by xiNeRoar** [comment]
請問我要提供什麼具體數據可以方便你查找問題? 
我嘗試過用edge, firefox跟chrome去開jellyfin 都一樣顯示不到這個字幕 反而我在電腦上直接用classic media player跟vlc player都可以看到字幕

**Comment by allanpk716** [comment]
那是因为没法操作 jellyfin 的api，等他们把 API 设计清楚了，不崩溃了，在考虑对接。目前没得对接的计划。人肉取点击它的扫描媒体库。

**Comment by xiNeRoar** [comment]
我可以提供其中一部電影 The Batman的字幕檔案給你
https://drive.google.com/file/d/1V_oCJJ73N-2YRz2FhwM47irrjPOaHKB7/view?usp=sharing, https://drive.google.com/file/d/1zNKhaUSzALYaII0lBsixlg4GOf5RmKJ4/view?usp=sharing

**Comment by xiNeRoar** [comment]
> 那是因为没法操作 jellyfin 的api，等他们把 API 设计清楚了，不崩溃了，在考虑对接。目前没得对接的计划。人肉取点击它的扫描媒体库。

不好意思，前半段能理解，後半段"人肉取點擊它的掃瞄媒體庫"是什麼意思? 我能做什麼讓你方法查找問題嗎?

**Comment by xiNeRoar** [comment]
不知道是不是讓你理解錯了，我說的沒法顯示不是說在選擇電影的時候看不到"CHI"的字幕可以選擇，而是在電影頁面選擇了"CHI"字幕點進去播放之後什麼都沒顯示出來，如下圖:
![image](https://user-images.githubusercontent.com/66216186/163790809-aea955ed-afe8-4ae4-9d42-65de7ef41fe8.png)

**Comment by allanpk716** [comment]
1. 流程是这样的。举个例子：如果你使用的是 Emby，先会从 Emby 获取最新的视频列表（每个视频有一个内部的 ID），然后去下载字幕，下载完毕后，我会调用 Emby 的 API 通知 Emby 去刷新加载识别这个字幕（对应上述的内部 ID）。如果不是使用 Emby，那么下载完字幕，媒体服务器是不会自动刷新的（有可能开启监控文件变化可以自动刷新，没测试过），所以你可以在媒体服务器中找到一个类似“扫描媒体库”的功能，也就是人肉刷新一次。或者等待它的扫描周期来触发。

2. 你说到的能看到字幕列表，但是无法加载字幕，这个梗应该是媒体服务器的，因为还是上面描述的，你可以用排除法使用其他的媒体播放器去使用字幕。如果其他的也不行，那就是字幕问题，那么就需要反馈字幕给我看看，是否是乱码了。如果其他媒体播放器能够正常使用，那么还是 jellyfin 或者 emby 的问题。

3. 你反馈的字幕我看了，编码是对的，使用 QQ影音也是能够跟我的视频匹配加载的。

**Comment by xiNeRoar** [comment]
非常感謝 那我嘗試去跟JELLYFIN的開發者反映一下吧 目前來說只要不使用字幕時間校正就好 其他功能都能正常使用
