### ISSUE TITLE
能否添加The Movie Data Base(TMDB) ID的支持

### ISSUE THREAD

**Issue by oh-ao** [allanpk716/ChineseSubFinder#308]
## Chinese Sub Finder版本 v0.25.0

环境: 群晖 docker

## 你想要新增或者改进什么功能？

能否添加对TMDBID的支持，似乎IMDB对中文搜索的支持不太好，我的数据库都是基于TMDB刮削的

**Comment by allanpk716** [comment]
之前做的时候字幕源不支持 TMDB 搜索，除非他们支持。

**Comment by katsuya82** [comment]
由於Kodi 和Plex 目前支援TMDB 較好，我也使用TMDB
