### ISSUE TITLE
通过 imdb id 可以在 字幕库 / subhd 搜索到字幕，但无法下载

### ISSUE THREAD

**Issue by irockstar** [allanpk716/ChineseSubFinder#309]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.25.0
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

通过 imdb id 可以在 字幕库 / subhd 搜索到字幕，但无法下载

[INFO]: 2022-04-20 13:26:35 - Download Movie Sub Started...
[INFO]: 2022-04-20 13:26:35 - Movie Sub Dl From Emby API...
[INFO]: 2022-04-20 13:26:38 - Queue 0 DlSub Start /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv
[INFO]: 2022-04-20 13:26:38 - Queue 0 zimuku /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv
[INFO]: 2022-04-20 13:26:38 - Queue 0 zimuku Start...
[INFO]: 2022-04-20 13:26:58 - Queue 0 zimuku End...
[ERROR]: 2022-04-20 13:26:58 - Queue 0 zimuku oneMovieDlSubInOneSite context deadline exceeded
[INFO]: 2022-04-20 13:26:58 - Queue 0 xunlei /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv
[INFO]: 2022-04-20 13:26:58 - Queue 0 xunlei Start...
[ERROR]: 2022-04-20 13:27:04 - xunlei NewHttpClient: /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv invalid character ',' looking for beginning of value
[INFO]: 2022-04-20 13:27:04 - Queue 0 xunlei End...
[ERROR]: 2022-04-20 13:27:04 - Queue 0 xunlei oneMovieDlSubInOneSite invalid character ',' looking for beginning of value
[INFO]: 2022-04-20 13:27:04 - Queue 0 subhd /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv
[INFO]: 2022-04-20 13:27:04 - Queue 0 subhd Start...
[ERROR]: 2022-04-20 13:27:23 - subhd keyword: tt1877830
[ERROR]: 2022-04-20 13:27:23 - getSubListFromKeyword4Movie IMDBID can not found sub /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv context deadline exceeded
[WARNING]: 2022-04-20 13:28:20 - DownFile.GetFileName is string.empty https://t.captcha.qq.com/hycdn?index=1&image=937375286785731072?aid=2010745797&sess=s0_k1O0shLmjQmucQT9W3p_F-Td5OumjaYbH8bZn5hJVZ-jtS_5VfuKKVwScXtTrDtFr7Pm7hO8amUJ5diBLwZwDBOMcTKbPaQ_PhOEt6e_zn3UbgyEVro27czXaLFe3LDVfIc4AGN9Zn9SpJ-D7aOHyuPIbfWbmoI-_TKa1UqbGLIDYk0fIM2EwdlLYySpjThG5X7uaQwSU4RSHwYwtd6v7QvnOuVnWydDzp_CFRnd_cvQ6n5zAwmvoyWXziCl5jNkJh41IiR7zfDLkeTnyDnNfOPLcVfj85YMOT_3k3mqzcr8QHV9kldrw**&sid=6922415622644711424&img_index=0&subsid=3
[INFO]: 2022-04-20 13:28:24 - Queue 0 subhd End...
[INFO]: 2022-04-20 13:28:24 - Queue 0 DlSub End /media/Movie/The Batman (2022)/The Batman (2022) WEBRip-2160p.mkv
[INFO]: 2022-04-20 13:28:24 - no sub found The Batman (2022) WEBRip-2160p.mkv

![image](https://user-images.githubusercontent.com/1676743/164173121-6bf7eebd-84c2-4c2b-8b25-49b92d6b94d2.png)

![image](https://user-images.githubusercontent.com/1676743/164173219-53501dcd-b5b0-400f-8f28-d16f79dc6958.png)

![image](https://user-images.githubusercontent.com/1676743/164173301-22531250-476e-4178-9483-dec72c7a1297.png)

![image](https://user-images.githubusercontent.com/1676743/164175068-4ad4ae2a-dfdf-452e-92cd-b35a5ea17b65.png)

**Comment by allanpk716** [comment]
see #304

**Comment by irockstar** [comment]
收到。关于【共享字幕】 有个建议，通过 阿里云盘（淘宝12块钱第一年8T）挂载 WebDAV，通过 用户名/密码 方式获取共建字幕。https://github.com/messense/aliyundrive-webdav

**Comment by allanpk716** [comment]
好思路，就是字幕有版权风险，我看看其他的 WebDAV 方案

**Comment by xiNeRoar** [comment]
建議不要阿里雲盤 因為中國以外地區的人用不到 可以考試一些全世界通用的雲端伺服

**Comment by allanpk716** [comment]
> 建議不要阿里雲盤 因為中國以外地區的人用不到 可以考試一些全世界通用的雲端伺服

有什么推荐的嘛？

**Comment by xiNeRoar** [comment]
> > 建議不要阿里雲盤 因為中國以外地區的人用不到 可以考試一些全世界通用的雲端伺服
> 
> 有什么推荐的嘛？

不好意思沒注意到你留言...我想google cloud, aws, blackbaze, digitalocean, pcloud, mega.nz這些都可以考慮看看?

**Comment by 287138531** [comment]
> 

存云盘不错，毕竟下载字幕其实群体还是不大的，建议可以加密，存阿里云盘，走webdav协议。用服务器的话投入太高

**Comment by xiaogtw** [comment]
作者您好，如果需要文件服务器提供索引的话，我这边可以免费提供。 IDC万兆网络，这个理论上不会占用我过多的带宽。 是我自己建立emby影视库所使用的。    可以联系tg "huang yu"
