### ISSUE TITLE
是否能支持多层连续剧结构，和themoviedb的id？

### ISSUE THREAD

**Issue by fzfz** [allanpk716/ChineseSubFinder#31]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.11.x 

环境: QNAP NAS下的docker 

## 你想要新增或者改进什么功能？
一 是否能支持多层连续剧目录，如：
/media/tv1
/media/tv2
因为我的nas是多盘的，我会保存在多个盘上，目前好像不能支持这种目录结构？

二 是否能支持www.themoviedb.org的id，因为imdb很多片子没有中文资料，但是www.themoviedb.org的中文更全，所以一般刮削时候，会优先用这个网站的资料，导致有些片子没有imdb的id

最后，感谢作者的辛勤劳动！

**Comment by allanpk716** [comment]
> ## 你使用的 chinesesubfinder 是什么版本，什么环境？
> chinesesubfinder 版本: v0.11.x
> 
> 环境: QNAP NAS下的docker
> 
> ## 你想要新增或者改进什么功能？
> 一 是否能支持多层连续剧目录，如：
> /media/tv1
> /media/tv2
> 因为我的nas是多盘的，我会保存在多个盘上，目前好像不能支持这种目录结构？
> 
> 二 是否能支持www.themoviedb.org的id，因为imdb很多片子没有中文资料，但是www.themoviedb.org的中文更全，所以一般刮削时候，会优先用这个网站的资料，导致有些片子没有imdb的id
> 
> 最后，感谢作者的辛勤劳动！

1. 这个是有计划的，但是没有那么快，考虑是搞定 Web 的设置页面后会加上去。见 #16 
2. 之所以选择 IMDB ID，是因为字幕网站支持，themoviedb id 字幕网站不支持所以就没有考虑去做。后续在做  #14 的时候应该会支持多个网站 ID 的查询，但是需要评估。
