### ISSUE TITLE
强制停止失效

### ISSUE THREAD

**Issue by kalvinses** [allanpk716/ChineseSubFinder#310]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.25.0

环境: docker

## 你想要新增或者改进什么功能？

强制停止运行经常无效，不知道能不能再优化一下

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by laobanbiefangcu** [comment]
emby，chinesesubfinder不是都可以添加多目录的吗，你这个跟nastool有什么关系吗

**Comment by allanpk716** [comment]
没有把 go 的 context 传递到很深入的函数中，所以这个功能未必能正确停下来。而且，什么版本？日志？

**Comment by allanpk716** [comment]
更新到最新版本，已经调整下载的逻辑，现在的每次一个独立的任务，停下来问题不大。
