### ISSUE TITLE
网页上配置emby的时候 emby读取的目录老是提示不争取，我是按第三方教程复制的emby读取的目录，是哪里权限问题吗？都给了啊

### ISSUE THREAD

**Issue by bingbaicai** [allanpk716/ChineseSubFinder#312]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
你这样反馈没法给你定位问题啊

**Comment by allanpk716** [comment]
还是先看看主页的部署教程吧，里面单独提到了权限的设置，以及需要自行去补 docker 和 linux 相关的知识。
