### ISSUE TITLE
无法登录网页版

### ISSUE THREAD

**Issue by JamesW99** [allanpk716/ChineseSubFinder#314]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.25.0
>
> 环境: docker or Window or Linux or MAC
> docker
 
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？
无法登录，网络错误

> 描述一下你遇到的问题
开始运行后被退出登录，提示“Websocket验证失败，请重新登录”

## 你的问题弄重现嘛？
可以，有时提示网络错误，有时提示websocket失败

> 描述以下你期望的结果

登陆成功

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "user_info": {
        "username": "root",
        "password": ""
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 1,
        "run_scan_at_start_up": true,
        "movie_paths": [
            "/E5/root/movie"
        ],
        "series_paths": [
            "/E5/root/tv"
        ]
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_http_proxy": false,
            "http_proxy_address": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 0,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": false,
        "topic": 1
    },
    "emby_settings": {
        "enable": true,
        "address_url": "ip:8096",
        "api_key": "",
        "max_request_video_number": 3000,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/E5/root/movie": "/E5/root/movie"
        },
        "series_paths_mapping": {
            "/E5/root/tv": "/E5/root/电视剧"
        }
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 120,
        "min_offset": 0.1
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略
root@ ~/chinesesubfinder: cat docker-compose.yml
# 这个配置是举例，如果你是单个视频目录，就用上面的配置好了。
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /root/chinesesubfinder/cache:/app/cache
      - /root/chinesesubfinder/config:/config

      - /E5/root/movie:/E5/root/movie
      - /E5/root/电视剧:/E5/root/tv # 举例
        #- /volume1/Video2:/media/video2 # 举例
    ports:
      - "19035:19035"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    restart: unless-stopped

## 请给出当次问题的完整日志

https://1drv.ms/t/s!Au0KeNQqDiKGgrZIouZ17ddzCBrSug?e=khDy6R

**Comment by JamesW99** [comment]
补一个compose

root@ ~/chinesesubfinder: cat docker-compose.yml
# 这个配置是举例，如果你是单个视频目录，就用上面的配置好了。
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /root/chinesesubfinder/cache:/app/cache
      - /root/chinesesubfinder/config:/config

      - /E5/root/movie:/E5/root/movie
      - /E5/root/电视剧:/E5/root/tv # 举例
        #- /volume1/Video2:/media/video2 # 举例
    ports:
      - "19035:19035"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    restart: unless-stopped

**Comment by JamesW99** [comment]
现在登陆可以看到3小时前的日志了，但是过几秒还会被强制登出
......
[info]: 2022-04-23 14:29:41 - Check Sub Supplier Start...
[info]: 2022-04-23 14:29:41 - releaseAdblock start
[info]: 2022-04-23 14:29:41 - releaseAdblock end

**Comment by bingbaicai** [comment]
我的也WEBUI无法打开

**Comment by irockstar** [comment]
如果使用了 阿里云docker 加速，latest  并不是最新版本，所以无法打开 web ui

/etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": ["https://xxxx.aliyuncs.com"]
}
EOF

我关闭了阿里云docker加速后，重新下载镜像，allanpk716/chinesesubfinder:latest 才是 最新版本

**Comment by Colin-XKL** [comment]
同样问题，刚注册登陆进去就出现这样的错误，再刷新已经进不去了。控制台报错多个js和css资源无法加载，错误为net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
但是docker compose文件是按照文档里写的，config和cache目录都映射了，不知道是哪里有问题

**Comment by allanpk716** [comment]
开 debug，上日志。

**Comment by JamesW99** [comment]
> 开 debug，上日志。

这是打开调试模式，运行一小时后得所有日志

https://1drv.ms/u/s!Au0KeNQqDiKGgrp1F-mjzCz7s2F9Hg?e=d57avb

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/167257634-b0da903d-fed5-44d5-aab1-ce988b93487a.png)

尽可能不要嵌套，虽然写过应对的逻辑，但是不能确定能用。你现在的日志看不到问题。看看 docker 容器获取的日志，有些 panic 日志体现不了。

**Comment by JamesW99** [comment]
> ![image](https://user-images.githubusercontent.com/1176000/167257634-b0da903d-fed5-44d5-aab1-ce988b93487a.png)
> 
> 尽可能不要嵌套，虽然写过应对的逻辑，但是不能确定能用。你现在的日志看不到问题。看看 docker 容器获取的日志，有些 panic 日志体现不了。

抱歉，实在不知道怎么导出docker日志为文件，我用 docker logs -f 6adca1b02e4a 展示了一些我登陆时的日志，里面包含一些error，不知道是否有影响
https://1drv.ms/t/s!Au0KeNQqDiKGgrZIouZ17ddzCBrSug?e=oqIdGK

btw，“- /E5/root/:/media” 已删除，问题依然存在

**Comment by allanpk716** [comment]
这个是程序崩溃了，所以一直再重启。你是什么硬件，我看有人反馈某些硬件下的软件系统是不支持 Chrome 无头浏览器的，我看你的崩溃就是本程序调用浏览器的时候挂了。

**Comment by allanpk716** [comment]
如果是 docker 部署的话。我个人喜欢用 portainer 去管理 docker 相关的东西，你可以试试（我个人 Windows 用户，一般纯命令也难受，能图形化一定图形化）

**Comment by JamesW99** [comment]
> 如果是 docker 部署的话。我个人喜欢用 portainer 去管理 docker 相关的东西，你可以试试（我个人 Windows 用户，一般纯命令也难受，能图形化一定图形化）

ssh连接hyperv ubuntu 20桌面版和oracle arm，确实都没有头，我试试portainer吧

**Comment by JamesW99** [comment]
> 如果是 docker 部署的话。我个人喜欢用 portainer 去管理 docker 相关的东西，你可以试试（我个人 Windows 用户，一般纯命令也难受，能图形化一定图形化）

用portainer部署跑起来了，感谢开发者！
