### ISSUE TITLE
功能需求：指定视频文件路径，让ChineseSubFinder仅下载该视频的字幕

### ISSUE THREAD

**Issue by devome** [allanpk716/ChineseSubFinder#318]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.25.0

环境: docker

## 你想要新增或者改进什么功能？

指定视频文件路径，让ChineseSubFinder仅下载该视频的字幕。当前ChineseSubFinder没有提供命令行参数功能，如果提供命令行参数的话，可以类似于下面这种：

```
chinesesubfinder -f "/movies/White.Snake.2019.1080p.BluRay.x264.DTS-WiKi/White.Snake.2019.1080p.BluRay.x264.DTS-WiKi.mkv"
```

同时提供api接口，POST一个路径给api接口，实现上述功能。但api可能需要考虑先返回（比如立即返回POST过来的文件路径存在不存在？），再异步处理下载字幕的任务，如果要处理完成字幕下载再返回，可能时间太长了。

感觉上api接口比命令行参数的使用场景更多一些。在一些群中讨论了下，需要此功能的用户确实不少。它有一个最典型的应用场景：当qBittorrent/transmission下载完成后运行脚本，立即向ChineseSubFinder的api触发给刚刚下载完成的视频下载字幕，这样下载完成后几乎可以立即观看，无需等待。

目前的api文档：[API-design.md](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/Web%E7%95%8C%E9%9D%A2%E8%AE%BE%E8%AE%A1/api%20%E6%8E%A5%E5%8F%A3%E8%AE%BE%E8%AE%A1.md) 。

## 这个功能有什么可以参考的资料吗？

暂无。

**Comment by allanpk716** [comment]
1. 下个版本应该可以给出 UI 手动选择视频去下载字幕（实现了下载任务队列的逻辑，才能够比较容易给出这个功能）
2. API 接口的前提都是视频被正确的削刮器处理过，否则直接调用搜索字幕的效果其实并不好。1 完成了，那么其实也可以开放出来，但是得在往后一个版本

**Comment by devome** [comment]
> 1. 下个版本应该可以给出 UI 手动选择视频去下载字幕（实现了下载任务队列的逻辑，才能够比较容易给出这个功能）
> 2. API 接口的前提都是视频被正确的削刮器处理过，否则直接调用搜索字幕的效果其实并不好。1 完成了，那么其实也可以开放出来，但是得在往后一个版本

好的。

**Comment by allanpk716** [comment]
到时候可以分享一下你的整套流程的

**Comment by devome** [comment]
> 到时候可以分享一下你的整套流程的

这个没问题，其实很简单，就几句命令的事。

**Comment by terrellgf** [comment]
+1
之前使用ausaki/subfinder项目的时候，就是通过tr或者qb下完一个电影自动运行自己的脚本，通过命令调subfinder的命令来第一时间对这个刚刚下载的电影进行主动拉字幕，这样效率高而且省资源。
如果能实现这个，就可以不用过多纠结缩短轮询时间了。正常的轮询仅用作避免三月内新字幕的机翻问题，或者因其他原因漏网的电影。
辛苦作者来实现。

**Comment by allanpk716** [comment]
最近发出 v0.26 这个版本其实就可以实现这个功能了的，然后 v0.27 我去把程序的 API KEY 做出来，就能够接受外部程序传递任务了

但是我想了下，传递任务过来的时候，必须是在 CSF 映射下的完整视频路径才行，不知道能接受这个限制嘛？

**Comment by devome** [comment]
> 最近发出 v0.26 这个版本其实就可以实现这个功能了的，然后 v0.27 我去把程序的 API KEY 做出来，就能够接受外部程序传递任务了
> 
> 但是我想了下，传递任务过来的时候，必须是在 CSF 映射下的完整视频路径才行，不知道能接受这个限制嘛？

可以啊，如果qb/tr和csf的映射路径一模一样，直接传递即可；如果不完全一样，让用户自定义一个转换关系，也可以实现。

**Comment by terrellgf** [comment]
> 
就我个人而言，无论是HTTP API，还是直接在宿主机上直接调chinesesubfinder的container中的命令都可以。我的tr/qb和subfinder在同一个宿主机上。映射不对称的问题也很容易解决，用户知道自己事先是如何定义的。

**Comment by allanpk716** [comment]
有个问题啊，因为现在的下载单个视频的耗时非常长，如果 http api 做同步的，感觉不太合适，如果做异步的，比如：

1. post add 一个任务，返回一个任务的 ID
2. 用这个任务 ID 去查询任务是否完成，有没有下载到字幕，是否有错误

这样可以嘛？

**Comment by devome** [comment]
> 有个问题啊，因为现在的下载单个视频的耗时非常长，如果 http api 做同步的，感觉不太合适，如果做异步的，比如：
> 
> 1. post add 一个任务，返回一个任务的 ID
> 2. 用这个任务 ID 去查询任务是否完成，有没有下载到字幕，是否有错误
> 
> 这样可以嘛？

是下载完成后执行的，所以触发csf下载字幕时，视频是保证下载完成了的。我看了你前两天发的文档，你说手动添加的任务优先级是3，3会是立即执行吗？我在群里也和一些人讨论了一下，大家一致认为手动触发下载的任务应该是优先级最高，最好能立即执行。但这个立即执行也会有一个较长的时间，所以我认为csf收到指令后先返回任务ID是没有问题的，至于发起指令一端是否关注下载成功了没有，是发起端的事，他关心他就等待一段时间自行再csf查询；如果不关心那么就发出指令就结束了。

**Comment by allanpk716** [comment]
优先级是 0-10 默认是5，每次取任务是从 0 - 10 的优先级去找，每个优先级也是一个队列（也就是有11个队列，过度设计···）。目前3是足够插队的。

**Comment by devome** [comment]
> 

足够插队感觉可以的，不知这个收到指定到启动下载，理论上最长和最短时间大概是多少？

**Comment by allanpk716** [comment]
就我调试的观察，一个视频的下载大概耗时3分钟左右（其实之前并发很快，但是不少人反馈来看机器性能堪忧，就强制单线程了，4个字幕源一个个去下载的），最差6分钟应该足够能得到你想要的字幕。

前提还有就是你的 IP 还有足够的下载次数（我现在还没有测试出来具体是限制多少次一天）

**Comment by allanpk716** [comment]
这个是暂定的对外的 API 接口文档，有啥问题可以提，我先做着先

https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/ApiKey%E8%AE%BE%E8%AE%A1/ApiKey%E8%AE%BE%E8%AE%A1.md

**Comment by devome** [comment]
> 就我调试的观察，一个视频的下载大概耗时3分钟左右（其实之前并发很快，但是不少人反馈来看机器性能堪忧，就强制单线程了，4个字幕源一个个去下载的），最差6分钟应该足够能得到你想要的字幕。
> 
> 前提还有就是你的 IP 还有足够的下载次数（我现在还没有测试出来具体是限制多少次一天）

好的，没问题。

**Comment by devome** [comment]
> 这个是暂定的对外的 API 接口文档，有啥问题可以提，我先做着先
> 
> 因为是你们会用这个功能啊，所以具体的需求得你们提，合理与否得你们提哈。内部实现基本都完成了，就是对外接口加一下，不难。
> 
> https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/ApiKey%E8%AE%BE%E8%AE%A1/ApiKey%E8%AE%BE%E8%AE%A1.md

一个小疑惑，media_server_inside_video_id这个键如果没有值，需要post时带上一个空值，还是直接这一整个键都不post？

**Comment by allanpk716** [comment]
> 一个小疑惑，media_server_inside_video_id这个键如果没有值，需要post时带上一个空值，还是直接这一整个键都不post？

没有不传，填空都行，没有强制去要求。

**Comment by devome** [comment]
> 这个是暂定的对外的 API 接口文档，有啥问题可以提，我先做着先
> 
> 因为是你们会用这个功能啊，所以具体的需求得你们提，合理与否得你们提哈。内部实现基本都完成了，就是对外接口加一下，不难。
> 
> https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/ApiKey%E8%AE%BE%E8%AE%A1/ApiKey%E8%AE%BE%E8%AE%A1.md

api文档看了，脚本也准备好了，我没有别的问题了，就等api正式上线了。

**Comment by allanpk716** [comment]
> api文档看了，脚本也准备好了，我没有别的问题了，就等api正式上线了。
> 
> 不过发现在文档中一处写的是 `POST /video/list/add`，而一处又写的是`POST /add-job`，是笔误吗？

啊，我还没实现完呢，会在具体实现的时候微调文档，然后我提前发布个 v0.26-DockerBeta4 出来，你可以先拉取试试有啥问题

**Comment by devome** [comment]
> > api文档看了，脚本也准备好了，我没有别的问题了，就等api正式上线了。
> > 不过发现在文档中一处写的是 `POST /video/list/add`，而一处又写的是`POST /add-job`，是笔误吗？
> 
> 啊，我还没实现完呢，会在具体实现的时候微调文档，然后我提前发布个 v0.26-DockerBeta4 出来，你可以先拉取试试有啥问题

好的

**Comment by allanpk716** [comment]
我推送代码上去了，现在编译 v0.26-DockerBeta4

**Comment by devome** [comment]
> 

现在CSF还没有生成apikey的地方，所以我用`/login`获取到的token来POST数据到`/apt/v1/add-job`，我确信token已经获取到了，但无论如何，`/apt/v1/add-job`返回的都是`{"message":"AccessToken Error"}`

**Comment by devome** [comment]
> 我推送代码上去了，现在编译 v0.26-DockerBeta4
> 
> 有些界面功能没做完，别纠结先哈···前端代码量多，等对接调试这个部分。

现在CSF还没有生成apikey的地方，所以我用`/login`获取到的token来POST数据到`/apt/v1/add-job`，我确信token已经获取到了，但无论如何，`/apt/v1/add-job`返回的都是`{"message":"AccessToken Error"}`

**Comment by allanpk716** [comment]
更新了文档，这个由于没有对接前端，所以需要手动去设置下配置文件。

**Comment by devome** [comment]
> 更新了文档，这个由于没有对接前端，所以需要手动去设置下配置文件。

收到了，提交任务功能正常，不过似乎通过`/api/v1/change-job-status`修改任务优先级不成功，返回是`ok`，但在webui中查询仍然是默认的优先级，不过在webui中提升优先级倒是正常的。

**Comment by terrellgf** [comment]
我这边测试没有问题，返回200，队列里也有，但是对应任务日志的第一条是：
[WARNING]: 2022-05-14 00:05:06 - cancel Downloader.QueueDownloader()
应该是没找到字幕。
总之API功能上没有任何问题。

文档有个小遗漏：
![image](https://user-images.githubusercontent.com/54665471/168325054-e2d58a40-598a-409b-8097-22271a11327c.png)

**Comment by allanpk716** [comment]
[WARNING]: 2022-05-14 00:05:06 - cancel Downloader.QueueDownloader()

这一句话还是因为在界面上触发了，**强制停止**的逻辑，所以所有的线程都 cancel 了。当然配置的时候肯定需要停下来。但是什么时候停下来现在还是不确定的···这个梗，估计很长一段时间懒得解决了。又不是不能用 doge

如果因为这个**强制停止**导致的各种怪异问题，我建议，可以考虑，在停下来修改完成配置文件后，直接**重启**容器或者程序，反正又不会经常去修改。等哪天功能做的差不多了，闲的慌，我再去把耗时操作拆分传入 context 来做 （大概率这个改进会鸽）:joy:

对了， API 文档会不定时更新，会根据使用的情况调整细节。有啥不清楚再问吧。

## 截图
![image](https://user-images.githubusercontent.com/1176000/168404235-9ceca808-0409-45d5-94f0-bacd6970cf85.png)

**Comment by terrellgf** [comment]
> [WARNING]: 2022-05-14 00:05:06 - cancel Downloader.QueueDownloader()
> 
> 这一句话还是因为在界面上触发了，**强制停止**的逻辑，所以所有的线程都 cancel 了。当然配置的时候肯定需要停下来。但是什么时候停下来现在还是不确定的···这个梗，估计很长一段时间懒得解决了。又不是不能用 doge
> 
> 如果因为这个**强制停止**导致的各种怪异问题，我建议，可以考虑，在停下来修改完成配置文件后，直接**重启**容器或者程序，反正又不会经常去修改。等哪天功能做的差不多了，闲的慌，我再去把耗时操作拆分传入 context 来做 （大概率这个改进会鸽）😂
> 
> 对了， API 文档会不定时更新，会根据使用的情况调整细节。有啥不清楚再问吧。
> 
> ## 截图
> ![image](https://user-images.githubusercontent.com/1176000/168404235-9ceca808-0409-45d5-94f0-bacd6970cf85.png)

明白，等正式版我再测试一波，有问题我再反馈给您。
询问一个题外话，emby刮削时，选择中文还是英文对CSF识别成功率高？

我测试的是一个中文的，没找到字幕
![image](https://user-images.githubusercontent.com/54665471/168422678-5a8500e6-ee0b-4074-9c41-d665ee0cb5bf.png)
![image](https://user-images.githubusercontent.com/54665471/168422700-7b142642-e338-412e-9ad2-8069fb16b736.png)
![image](https://user-images.githubusercontent.com/54665471/168422715-948638ab-aa9a-4a24-9657-be68db4b3ab4.png)

**Comment by devome** [comment]
> emby刮削时，选择中文还是英文对CSF识别成功率高？

CSF应该是按IMDB编号。

**Comment by terrellgf** [comment]
> 

OK，所以说nfo的title是什么并不关心，对吧。

**Comment by allanpk716** [comment]
> OK，所以说nfo的title是什么并不关心，对吧。

也不完全，有限是 nfo 中的  IMDB ID 搜索，然后才到文件名搜索。连续剧需要文件名获取 Season 和 Eps 信息，削刮完一般这些都不是问题

**Comment by terrellgf** [comment]
> 

您这边更倾向于我刮削为纯英文nfo还是中文呢？

**Comment by terrellgf** [comment]
> > OK，所以说nfo的title是什么并不关心，对吧。
> 
> 也不完全，有限是 nfo 中的 IMDB ID 搜索，然后才到文件名搜索。连续剧需要文件名获取 Season 和 Eps 信息，削刮完一般这些都不是问题

您这边更倾向于我刮削为纯英文nfo还是中文呢？

**Comment by devome** [comment]
> > > OK，所以说nfo的title是什么并不关心，对吧。
> > 
> > 
> > 也不完全，有限是 nfo 中的 IMDB ID 搜索，然后才到文件名搜索。连续剧需要文件名获取 Season 和 Eps 信息，削刮完一般这些都不是问题
> 
> 您这边更倾向于我刮削为纯英文nfo还是中文呢？

不影响，有IMDB ID就行，当然出于用户的需要，刮削为中文对用户友好一些。

**Comment by allanpk716** [comment]
> 您这边更倾向于我刮削为纯英文nfo还是中文呢？

别那么客气···我看国内的字幕源对影片的英文标题搜索也没啥问题的（除非是很老的视频），只要削刮过，一般问题不大。

**Comment by terrellgf** [comment]
> > 您这边更倾向于我刮削为纯英文nfo还是中文呢？
> 
> 别那么客气···我看国内的字幕源对影片的英文标题搜索也没啥问题的（除非是很老的视频），只要削刮过，一般问题不大。

好的，那我改成英文吧，感谢回复~

**Comment by terrellgf** [comment]
> > 您这边更倾向于我刮削为纯英文nfo还是中文呢？
> 
> 别那么客气···我看国内的字幕源对影片的英文标题搜索也没啥问题的（除非是很老的视频），只要削刮过，一般问题不大。

在使用过程中发现了一个兼容性问题。

chinesesubfinder 版本: v0.26-DockerBeta6
transmission版本：3.00-20
环境: docker

你遇到什么问题了？
我下载器用的是transmission。在某个种子完成时，它可以触发一个shell脚本，可以获取到下载目录和文件名。
例如：
下载目录为/media/movie3
种子文件名为：Over.the.Rainbow.2002.BluRay.REMUX.1080p.AVC.DTS-HD.MA5.1-HDS（这其实是个文件夹，里面包含了mkv和nfo文件）
问题就在于如果这个种子包含了多个文件，种子文件名就是一个文件夹的名字。
而CSF的API中，经测试似乎只支持全路径到具体某个媒体文件才行，不支持到某个电影的文件夹，然后递归查找里面的文件进行字幕搜索。

日志：
1. 如果指定的路径是个文件夹，则失败：
![image](https://user-images.githubusercontent.com/54665471/168520222-cde1e78f-584b-43f3-bad3-c53a462f5925.png)

2. 如果指定的路径是全路径，则成功：
![image](https://user-images.githubusercontent.com/54665471/168520364-7ef36ea8-115a-4441-bc46-96227704e776.png)

**Comment by devome** [comment]
> > > 您这边更倾向于我刮削为纯英文nfo还是中文呢？
> > 
> > 别那么客气···我看国内的字幕源对影片的英文标题搜索也没啥问题的（除非是很老的视频），只要削刮过，一般问题不大。
> 
> 在使用过程中发现了一个兼容性问题。
> 
> chinesesubfinder 版本: v0.26-DockerBeta6
> transmission版本：3.00-20
> 环境: docker
> 
> 你遇到什么问题了？
> 我下载器用的是transmission。在某个种子完成时，它可以触发一个shell脚本，可以获取到下载目录和文件名。
> 例如：
> 下载目录为/media/movie3
> 种子文件名为：Over.the.Rainbow.2002.BluRay.REMUX.1080p.AVC.DTS-HD.MA5.1-HDS（这其实是个文件夹，里面包含了mkv和nfo文件）
> 问题就在于如果这个种子包含了多个文件，种子文件名就是一个文件夹的名字。
> 而CSF的API中，经测试似乎只支持全路径到具体某个媒体文件才行，不支持到某个电影的文件夹，然后递归查找里面的文件进行字幕搜索。
> 
> 日志：
> 1. 如果指定的路径是个文件夹，则失败：
> ![image](https://user-images.githubusercontent.com/54665471/168520222-cde1e78f-584b-43f3-bad3-c53a462f5925.png)
> 
> 2. 如果指定的路径是全路径，则成功：
> ![image](https://user-images.githubusercontent.com/54665471/168520364-7ef36ea8-115a-4441-bc46-96227704e776.png)
> 
> 

作者目前的实现就是这样的，必须媒体文件全路径。

**Comment by terrellgf** [comment]
> > > > 您这边更倾向于我刮削为纯英文nfo还是中文呢？
> > > 
> > > 
> > > 别那么客气···我看国内的字幕源对影片的英文标题搜索也没啥问题的（除非是很老的视频），只要削刮过，一般问题不大。
> > 
> > 
> > 在使用过程中发现了一个兼容性问题。
> > chinesesubfinder 版本: v0.26-DockerBeta6
> > transmission版本：3.00-20
> > 环境: docker
> > 你遇到什么问题了？
> > 我下载器用的是transmission。在某个种子完成时，它可以触发一个shell脚本，可以获取到下载目录和文件名。
> > 例如：
> > 下载目录为/media/movie3
> > 种子文件名为：Over.the.Rainbow.2002.BluRay.REMUX.1080p.AVC.DTS-HD.MA5.1-HDS（这其实是个文件夹，里面包含了mkv和nfo文件）
> > 问题就在于如果这个种子包含了多个文件，种子文件名就是一个文件夹的名字。
> > 而CSF的API中，经测试似乎只支持全路径到具体某个媒体文件才行，不支持到某个电影的文件夹，然后递归查找里面的文件进行字幕搜索。
> > 日志：
> > 
> > 1. 如果指定的路径是个文件夹，则失败：
> >    ![image](https://user-images.githubusercontent.com/54665471/168520222-cde1e78f-584b-43f3-bad3-c53a462f5925.png)
> > 2. 如果指定的路径是全路径，则成功：
> >    ![image](https://user-images.githubusercontent.com/54665471/168520364-7ef36ea8-115a-4441-bc46-96227704e776.png)
> 
> 作者目前的实现就是这样的，必须媒体文件全路径。

也就是说，我得知道所有可能的媒体文件的格式，然后自己用正则自动筛选出媒体文件？

**Comment by devome** [comment]
> 也就是说，我得知道所有可能的媒体文件的格式，然后自己用正则自动筛选出媒体文件？

用不到正则，find后缀就行。

**Comment by terrellgf** [comment]
> > 也就是说，我得知道所有可能的媒体文件的格式，然后自己用正则自动筛选出媒体文件？
> 
> 用不到正则，find后缀就行。

重点是，得知道所有可能得媒体格式，大概率是mkv、mp4、rmvb，但也不能保证没有缝漏出去，不能百分之百定位到媒体文件。

**Comment by devome** [comment]
> 重点是，得知道所有可能得媒体格式，大概率是mkv、mp4、rmvb，但也不能保证没有缝漏出去，不能百分之百定位到媒体文件。

你把csf中填的所有后缀全部执行find就行了。

**Comment by terrellgf** [comment]
> > 重点是，得知道所有可能得媒体格式，大概率是mkv、mp4、rmvb，但也不能保证没有缝漏出去，不能百分之百定位到媒体文件。
> 
> 你把csf中填的所有后缀全部执行find就行了，不在这个范围的也没用啊。

明白了，自己实现递归是吧，只要find出是普通文件类型的，全发job，不用关心是不是媒体文件。比如10个文件就会生成10个job。然后还要忽略掉蓝光的文件夹，因为里面文件太多了，触发CSF没有意义，所有就需要自己实现一个能够识别蓝光文件并忽略的逻辑。

**Comment by devome** [comment]
蓝光是m2ts，不find这个后缀就行。

**Comment by terrellgf** [comment]
> 蓝光是m2ts，不find这个后缀就行。 指定了后缀find，find的结果肯定是媒体。

我的意思是，我得知道所有媒体后缀，比如漏了一个我不知道得，就有可能匹配不上了。

**Comment by devome** [comment]
> > 蓝光是m2ts，不find这个后缀就行。 指定了后缀find，find的结果肯定是媒体。
> 
> 我的意思是，我得知道所有媒体后缀，比如漏了一个我不知道得，就有可能匹配不上了。

我说了，find指定的后缀和csf中你设置的后缀一样就行，不在csf中设置的后缀范围内的，你发了也没用。超出这个后缀范围的你得先修改csf中的设置。

**Comment by terrellgf** [comment]
> > > 蓝光是m2ts，不find这个后缀就行。 指定了后缀find，find的结果肯定是媒体。
> > 
> > 
> > 我的意思是，我得知道所有媒体后缀，比如漏了一个我不知道得，就有可能匹配不上了。
> 
> 我说了，find指定的后缀和csf中你设置的后缀一样就行，不在csf中设置的后缀范围内的，你发了也没用。超出这个后缀范围的你得先修改csf中的设置。

明白了，我忽略了csf中还要设置后缀，谢谢，有劳了！

**Comment by allanpk716** [comment]
蓝光我还没兼容 http api，估计会额外加一个参数。应该不难，等我更新就好了。你升级到 v0.26.0 已经发布正式版本了，需要收集一段时间反馈，再更新。

**Comment by terrellgf** [comment]
@allanpk716 有了API，跳过蓝光已经基本满足我的需求了。对于蓝光字幕的刮削，我的需求倒是没那么强烈。而且蓝光的母文件夹的标题，也不是很理想地按规矩命名的。比如没有发行年份的蓝光原盘文件是很常见的，仅凭一个影片名字（还有可能原始发布者加上自己的名字），我感觉成功率不高。

**Comment by allanpk716** [comment]
> @allanpk716 有了API，跳过蓝光已经基本满足我的需求了。对于蓝光字幕的刮削，我的需求倒是没那么强烈。而且蓝光的母文件夹的标题，也不是很理想地按规矩命名的。比如没有发行年份的蓝光原盘文件是很常见的，仅凭一个影片名字（还有可能原始发布者加上自己的名字），我感觉成功率不高。

削刮完其实也是没问题的，我在 Web UI 上点击一个蓝光电影下载是能够正确下载的。HTTP API 还没有做，先修复其他问题再加一下就好了。

**Comment by allanpk716** [comment]
已经提交 http api 蓝光的代码，主要看 http api 的设计文档中的解释，使用方法比较取巧（为了内部逻辑的一致性）。

**Comment by terrellgf** [comment]
> 削刮完其实也是没问题的，我在 Web UI 上点击一个蓝光电影下载是能够正确下载的。HTTP API 还没有做，先修复其他问题再加一下就好了。

经过一轮遍历，目前我有586部电影刮削显示没有找到字幕：有nfo的非蓝光332部（可能就是没匹配到？），蓝光248部（有6部是因为套了两级目录）。
找到字幕的蓝光 51部。

**Comment by allanpk716** [comment]
> 经过一轮遍历，目前我有586部电影刮削显示没有找到字幕：有nfo的非蓝光332部（可能就是没匹配到？），蓝光248部（有6部是因为套了两级目录）。 找到字幕的蓝光 51部。

你去看每个任务的日志

**Comment by terrellgf** [comment]
> 你去看每个任务的日志。以及，还在修复一些隐蔽的bug，如果想用，可以试试最新的 beta 版本
每个任务的日志也都是没找到字幕
我随便选了两个带nfo的看了一下：一个是emby没刮对（我去imdb核实了一下），另一个是刮对了，但这俩在日志上都是没从任何网站找到字幕。由于没办法自动化来确认nfo的正确性（如果能自动化100%准确核验，就不需要emby :笑哭），所以我只能抽样看了一下，不具有普遍性结果。

**Comment by allanpk716** [comment]
> 
> 每个任务的日志也都是没找到字幕 我随便选了两个带nfo的看了一下：一个是emby没刮对（我去imdb核实了一下），另一个是刮对了，但这俩在日志上都是没从任何网站找到字幕。由于没办法自动化来确认nfo的正确性（如果能自动化100%准确核验，就不需要emby :笑哭），所以我只能抽样看了一下，不具有普遍性结果。

有可能是bug，之前版本 series 任务取出来的时候可能有问题，已经在最新的 beta 修复

**Comment by terrellgf** [comment]
> series

OK, Series任务的bug会影响电影么？我暂时只测试了电影，剧集还没有加进目录里。

**Comment by allanpk716** [comment]
> > series
> 
> OK, Series任务的bug会影响电影么？我暂时只测试了电影，剧集还没有加进目录里。

最新版本应该都修复了，如果有问题再新开 issues 吧
