### ISSUE TITLE
movie路径会多出一个s来

### ISSUE THREAD

**Issue by luoban** [allanpk716/ChineseSubFinder#319]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.25.0
>
> 环境: docker 
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 识别目录多了一个s，现在配置的路径是/media/movies ，结果查找目录会查/media/moviess

## 你的问题弄重现嘛？

> 必现

## 你期望的结果

> 能够正常读取路径

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "user_info":{
        "username":"xx",
        "password":"xx"
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":1,
        "run_scan_at_start_up":false,
        "movie_paths":[
            "/media/movies"
        ],
        "series_paths":[
            "/media/tv"
        ]
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_http_proxy":false,
            "http_proxy_address":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":true,
        "custom_video_exts":[

        ],
        "fix_time_line":true,
        "topic":1
    },
    "emby_settings":{
        "enable":true,
        "address_url":"xx",
        "api_key":"xx",
        "max_request_video_number":5000,
        "skip_watched":true,
        "movie_paths_mapping":{
            "/media/movies":"/Medias/movie"
        },
        "series_paths_mapping":{
            "/media/tv":"/Medias/tv"
        }
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":true,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
[ERROR]: 2022-05-01 16:22:41 - zimuku CheckAlive Error Get "https://zmk.pw": x509: certificate is valid for zimuku.org, www.zimuku.org, not zmk.pw
[WARNING]: 2022-05-01 16:22:41 - zimuku Check Alive = false
[ERROR]: 2022-05-01 16:22:42 - xunlei NewHttpClient: CheckFileName Get "http://sub.xmp.sandai.net:8000/subxl/FB4E2AFF106112136DFC5ACC7339EB29D1EC0CF8.json": read tcp 172.17.0.7:44644->106.14.221.44:8000: read: connection reset by peer
[ERROR]: 2022-05-01 16:22:42 - xunlei CheckAlive Error Get "http://sub.xmp.sandai.net:8000/subxl/FB4E2AFF106112136DFC5ACC7339EB29D1EC0CF8.json": read tcp 172.17.0.7:44644->106.14.221.44:8000: read: connection reset by peer
[WARNING]: 2022-05-01 16:22:42 - xunlei Check Alive = false
[INFO]: 2022-05-01 16:22:44 - shooter Check Alive = true, Speed = 1952 ms
[INFO]: 2022-05-01 16:22:44 - Check Sub Supplier End
[INFO]: 2022-05-01 16:22:44 - MovieFolder Index 0 -- /media/movies
[INFO]: 2022-05-01 16:22:44 - SeriesPaths Index 0 -- /media/tv
[INFO]: 2022-05-01 16:22:44 - PreDownloadProcess.Check() End
[INFO]: 2022-05-01 16:22:44 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-05-01 16:22:44 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-01 16:22:44 - PreDownloadProcess.HotFix() End
[INFO]: 2022-05-01 16:22:44 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-05-01 16:22:44 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-01 16:22:44 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-05-01 16:22:44 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-05-01 16:22:44 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-05-01 16:22:46 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-05-01 16:22:46 - PreDownloadProcess.Wait() Done.
[INFO]: 2022-05-01 16:22:47 - ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
[INFO]: 2022-05-01 16:22:47 - Download One Started...
[INFO]: 2022-05-01 16:22:47 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-05-01 16:22:47 - Refresh Emby Sub List Start...
[INFO]: 2022-05-01 16:22:47 - Refresh Emby Sub List Success
[INFO]: 2022-05-01 16:22:47 - GetUpdateVideoListFromEmby Start...
[INFO]: 2022-05-01 16:22:49 - GetUpdateVideoListFromEmby End
[INFO]: 2022-05-01 16:22:49 - Download Movie Sub Started...
[INFO]: 2022-05-01 16:22:49 - Movie Sub Dl From Emby API...
[WARNING]: 2022-05-01 16:22:49 - SkipChineseMovie /media/moviess/Uncharted (2022)/Uncharted (2022) Bluray-1080p.mkv open /media/moviess/Uncharted (2022): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - subSupplierHub.DownloadSub4Movie /media/moviess/Uncharted (2022)/Uncharted (2022) Bluray-1080p.mkv MovieNeedDlSub /media/moviess/Uncharted (2022)/Uncharted (2022) Bluray-1080p.mkv open /media/moviess/Uncharted (2022): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - PollName: MoviePool Index: 0 NewPoolWithFunc done with Error MovieNeedDlSub /media/moviess/Uncharted (2022)/Uncharted (2022) Bluray-1080p.mkv open /media/moviess/Uncharted (2022): no such file or directory
[WARNING]: 2022-05-01 16:22:49 - SkipChineseMovie /media/moviess/Charlie's Angels (2019)/Charlie's Angels (2019) Bluray-1080p.mkv open /media/moviess/Charlie's Angels (2019): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - subSupplierHub.DownloadSub4Movie /media/moviess/Charlie's Angels (2019)/Charlie's Angels (2019) Bluray-1080p.mkv MovieNeedDlSub /media/moviess/Charlie's Angels (2019)/Charlie's Angels (2019) Bluray-1080p.mkv open /media/moviess/Charlie's Angels (2019): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - PollName: MoviePool Index: 1 NewPoolWithFunc done with Error MovieNeedDlSub /media/moviess/Charlie's Angels (2019)/Charlie's Angels (2019) Bluray-1080p.mkv open /media/moviess/Charlie's Angels (2019): no such file or directory
[WARNING]: 2022-05-01 16:22:49 - SkipChineseMovie /media/moviess/The Batman (2022)/The Batman (2022) WEBDL-1080p Proper.mkv open /media/moviess/The Batman (2022): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - subSupplierHub.DownloadSub4Movie /media/moviess/The Batman (2022)/The Batman (2022) WEBDL-1080p Proper.mkv MovieNeedDlSub /media/moviess/The Batman (2022)/The Batman (2022) WEBDL-1080p Proper.mkv open /media/moviess/The Batman (2022): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - PollName: MoviePool Index: 2 NewPoolWithFunc done with Error MovieNeedDlSub /media/moviess/The Batman (2022)/The Batman (2022) WEBDL-1080p Proper.mkv open /media/moviess/The Batman (2022): no such file or directory
[WARNING]: 2022-05-01 16:22:49 - SkipChineseMovie /media/moviess/Obsessed (2014)/Obsessed (2014) Bluray-1080p.mkv open /media/moviess/Obsessed (2014): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - subSupplierHub.DownloadSub4Movie /media/moviess/Obsessed (2014)/Obsessed (2014) Bluray-1080p.mkv MovieNeedDlSub /media/moviess/Obsessed (2014)/Obsessed (2014) Bluray-1080p.mkv open /media/moviess/Obsessed (2014): no such file or directory
[ERROR]: 2022-05-01 16:22:49 - PollName: MoviePool Index: 3 NewPoolWithFunc done with Error MovieNeedDlSub /media/moviess/Obsessed (2014)/Obsessed (2014) Bluray-1080p.mkv open /media/moviess/Obsessed (2014): no such file or directory
[WARNING]: 2022-05-01 16:22:49 - SkipChineseMovie /media/moviess/Moonfall (2022)/Moonfall (2022) Remux-1080p.mkv open /media/moviess/Moonfall (2022): no such file or directory

**Comment by allanpk716** [comment]
新版本还会有这个问题嘛？
