### ISSUE TITLE
docker hub上的镜像缺少了latest标签

### ISSUE THREAD

**Issue by mhqschen** [allanpk716/ChineseSubFinder#32]
没法docker pull allanpk716/chinesesubfinder或者docker pull allanpk716/chinesesubfinder:latest了。

**Comment by mhqschen** [comment]
发现已经修复了，给力

**Comment by allanpk716** [comment]
> 发现已经修复了，给力

昨天更新出 bug 了 见 #30 ，刚才才在本地 pull v0.11.1 所以才补 latest 上去了
