### ISSUE TITLE
任务启动后，就停不下来了，无法调整配置

### ISSUE THREAD

**Issue by muziriyue021** [allanpk716/ChineseSubFinder#320]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: latest
>
> 环境: docker 
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 在PANEL无法关闭进程，导致无法调整配置

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 可以强制关闭任务

## 给出当前程序的配置文件

{"user_info":{"username":"admin","password":""},"common_settings":{"interval_or_assign_or_custom":0,"scan_interval":"@every 6h","threads":1,"run_scan_at_start_up":true,"movie_paths":["/media1"],"series_paths":["/media2"]},"advanced_settings":{"proxy_settings":{"use_http_proxy":false,"http_proxy_address":""},"debug_mode":false,"save_full_season_tmp_subtitles":false,"sub_type_priority":0,"sub_name_formatter":1,"save_multi_sub":false,"custom_video_exts":[],"fix_time_line":false,"topic":1},"emby_settings":{"enable":false,"address_url":"","api_key":"","max_request_video_number":500,"skip_watched":false,"movie_paths_mapping":{},"series_paths_mapping":{}},"developer_settings":{"enable":false,"bark_server_address":""},"timeline_fixer_settings":{"max_offset_time":120,"min_offset":0.1},"experimental_function":{"auto_change_sub_encode":{"enable":false,"des_encode_type":0},"chs_cht_changer":{"enable":false,"des_chinese_language_type":0},"remote_chrome_settings":{"enable":false,"remote_docker_url":"","remote_adblock_path":"","remote_user_data_dir":""}}}

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by allanpk716** [comment]
手动改配置，有个 run_scan_at_start_up
