### ISSUE TITLE
簡轉繁

### ISSUE THREAD

**Issue by katsuya82** [allanpk716/ChineseSubFinder#328]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.25.0
>
> 环境: Synology docker 
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

簡轉繁的結果非常糟糕，非常不通順，錯字連篇

## 你的问题弄重现嘛？

可以

00:01:06,459 --> 00:01:08,209
一萬公裏

4
00:01:08,209 --> 00:01:09,626
一百五十天

5
00:01:10,792 --> 00:01:12,042
跑不完

6
00:01:12,751 --> 00:01:14,501
便塟身絲路

7
00:02:28,251 --> 00:02:29,834
很多人問我

8
00:02:29,834 --> 00:02:31,126
爲什麼要跑

9
00:02:31,542 --> 00:02:34,001
跑 就像謼吸一樣

## 你期望的结果

請調用繁化姬
https://zhconvert.org/

**Comment by katsuya82** [comment]
原字幕

1
00:01:01,667 --> 00:01:03,001
星空

2
00:01:03,667 --> 00:01:05,042
守护着我

3
00:01:06,459 --> 00:01:08,209
一万公里

4
00:01:08,209 --> 00:01:09,626
一百五十天

5
00:01:10,792 --> 00:01:12,042
跑不完

6
00:01:12,751 --> 00:01:14,501
便葬身丝路

7
00:02:28,251 --> 00:02:29,834
很多人问我

8
00:02:29,834 --> 00:02:31,126
为什么要跑

9
00:02:31,542 --> 00:02:34,001
跑 就像呼吸一样

**Comment by katsuya82** [comment]
繁化姬後

0
00:00:00,000 --> 00:00:00,000
Processed by 繁化姬 dict-b2d801a3-r1004 @ 2022/05/08 12:21:08 | https://zhconvert.org

1
00:01:01,667 --> 00:01:03,001
星空

2
00:01:03,667 --> 00:01:05,042
守護著我

3
00:01:06,459 --> 00:01:08,209
一萬公里

4
00:01:08,209 --> 00:01:09,626
一百五十天

5
00:01:10,792 --> 00:01:12,042
跑不完

6
00:01:12,751 --> 00:01:14,501
便葬身絲路

7
00:02:28,251 --> 00:02:29,834
很多人問我

8
00:02:29,834 --> 00:02:31,126
為什麼要跑

9
00:02:31,542 --> 00:02:34,001
跑 就像呼吸一樣

**Comment by allanpk716** [comment]
1. golang 暂时没有发现有好用的简繁转换第三方库，需要找一下
2. 如果可能的话，是否可以给一些语句作为对比测试的参照，方便验证新选型的简繁转换库是正确的，符合你们预期的

**Comment by katsuya82** [comment]
你可以直接參考繁化姬翻譯後的結果。

https://zhconvert.org/

**Comment by katsuya82** [comment]
聲明一下本人跟繁化姬一點關係都沒有，只是很愛用而已。

**Comment by allanpk716** [comment]
OK，我去看看

**Comment by katsuya82** [comment]
繁化姬有開放api 供別的程式使用，只要不營利都可以

https://docs.zhconvert.org/api/getting-started/

**Comment by allanpk716** [comment]
看起来不错，但是它的协议本项目无法直接使用，后续我把插件机制做出来，由其他人去补充这些功能吧

![image](https://user-images.githubusercontent.com/1176000/167294534-e94fd481-6086-422a-985e-8840b5205619.png)

**Comment by allanpk716** [comment]
跟换了转换的库，依然是离线的。暂时是繁体转简体。还有其他的一些转换的选项，我没有开放出来。

具体看这个[项目](https://github.com/longbridgeapp/opencc)，如果你需要用到某个转换的逻辑，可以再提。下面是简体转换繁体的效果，如果你有繁体可以给到我更加，简体字幕也行，我可以测试下。

预计再 v0.27 上线，如果 v0.26 还有 bug 要修复也会在最新的 v0.26 出现

[简体转繁体效果.zip](https://github.com/allanpk716/ChineseSubFinder/files/8704674/default.zip)

**Comment by shanyan-wcx** [comment]
简繁转换可以试试opencc
https://github.com/BYVoid/OpenCC

**Comment by allanpk716** [comment]
> 简繁转换可以试试opencc https://github.com/BYVoid/OpenCC

最新的已经用上了，如果你遇到有什么字幕转换有问题id，需要上传给我看看。现在的效果看上面一个回复我给的示例效果。
