### ISSUE TITLE
first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by bigwenoopsie** [allanpk716/ChineseSubFinder#329]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本:
latest
[info]: 2022-05-09 23:45:17 - GetCode 2022-05-09 951275
> 环境:
docker-compose

## 你遇到什么问题了？
[info]: 2022-05-09 23:47:41 - Refresh Emby Sub List Start...
[error]: 2022-05-09 23:47:41 - Refresh Emby Sub List Error
[error]: 2022-05-09 23:47:41 - RefreshEmbySubList parse "10.1.1.6:8096/emby/Items": first path segment in URL cannot contain colon
[info]: 2022-05-09 23:47:41 - Download One End...
[info]: 2022-05-09 23:47:42 - ClearRodTmpRootFolder Done
[error]: 2022-05-09 23:47:42 - downloader_helper.Start() Error: parse "10.1.1.6:8096/emby/Items": first path segment in URL cannot contain colon

## 你的问题弄重现嘛？

yes

## 你期望的结果

no error

## 给出当前程序的配置文件

{
    "user_info": {
        "username": "",
        "password": ""
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 1,
        "run_scan_at_start_up": true,
        "movie_paths": [],
        "series_paths": []
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_http_proxy": false,
            "http_proxy_address": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 0,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": false,
        "topic": 1
    },
    "emby_settings": {
        "enable": false,
        "address_url": "",
        "api_key": "",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {},
        "series_paths_mapping": {}
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 120,
        "min_offset": 0.1
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        }
    }
}

## 如果是使用 Docker，请给出对应的配置信息

  chinesesubfinder: # 19035
    network_mode: host
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /volume2/files/docker/chinesesubfinder/app/cache:/app/cache
      - /volume2/files/docker/chinesesubfinder/config:/config
      - /volume1/data:/data
    restart: unless-stopped

## 请给出当次问题的完整日志

完整日志太长，中间的媒体部分删除了

[INFO]: 2022-05-09 21:19:45 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-05-09 21:19:45 - matches logs: 0
[INFO]: 2022-05-09 21:19:47 - ChineseSubFinder Version: v0.25.0
[INFO]: 2022-05-09 21:19:47 - Need do Setup
[INFO]: 2022-05-09 21:19:47 - WebUI will listen at 0.0.0.0:19035
[INFO]: 2022-05-09 21:19:47 - Try Start Server At Port 19035
[ERROR]: 2022-05-09 21:24:05 - SetupHandler parse "10.1.1.6:8096": first path segment in URL cannot contain colon
[INFO]: 2022-05-09 21:24:53 - First Time coreSubDownloadProcess Start
[INFO]: 2022-05-09 21:24:53 - Reload Log Settings, level = Info
[INFO]: 2022-05-09 21:24:53 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-05-09 21:24:53 - matches logs: 0
[INFO]: 2022-05-09 21:24:53 - OneTimeSubtitleScanStart
[INFO]: 2022-05-09 21:24:53 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-05-09 21:24:54 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202259c31ViaG5Q.txt
[INFO]: 2022-05-09 21:24:54 - GetCode 2022-05-09 951275
[INFO]: 2022-05-09 21:24:54 - ClearRodTmpRootFolder Done
[INFO]: 2022-05-09 21:24:54 - PreDownloadProcess.Init() End
[INFO]: 2022-05-09 21:24:54 - PreDownloadProcess.Check() Start...
[INFO]: 2022-05-09 21:24:54 - UseHttpProxy = false
[INFO]: 2022-05-09 21:24:54 - UrlConnectednessTest Target Site https://baidu.com Speed: 311 ms, Status: true
[INFO]: 2022-05-09 21:24:54 - Check Sub Supplier Start...
[INFO]: 2022-05-09 21:24:54 - releaseAdblock start
[INFO]: 2022-05-09 21:24:55 - releaseAdblock end
[INFO]: 2022-05-09 21:25:56 - zimuku Check Alive = true, Speed = 5829 ms
[INFO]: 2022-05-09 21:26:39 - xunlei Check Alive = true, Speed = 42687 ms
[INFO]: 2022-05-09 21:26:40 - shooter Check Alive = true, Speed = 589 ms
[INFO]: 2022-05-09 21:26:40 - subhd Check Alive = true, Speed = 611 ms
[INFO]: 2022-05-09 21:26:40 - Check Sub Supplier End
[INFO]: 2022-05-09 21:26:40 - MovieFolder Index 0 -- /data/media/movies
[INFO]: 2022-05-09 21:26:40 - SeriesPaths Index 0 -- /data/media/series
[INFO]: 2022-05-09 21:26:40 - PreDownloadProcess.Check() End
[INFO]: 2022-05-09 21:26:40 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-05-09 21:26:40 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-09 21:26:41 - Hotfix 001 Start...
[INFO]: 2022-05-09 21:26:41 - Fix Movie Dir Index 0 /data/media/movies Start...
[WARNING]: 2022-05-09 21:26:44 - IsSubHasChinese.HasChineseLang /data/media/movies/Another.Cinderella.Story.2008.1080p.BluRay.H264.AAC-RARBG/Another Cinderella Story (2008) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:45 - IsSubHasChinese.HasChineseLang /data/media/movies/Camp.Rock.2.The.Final.Jam.2010.EXTENDED.1080p.BluRay.x265-RARBG/Camp Rock 2 The Final Jam (2010) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:45 - IsSubHasChinese.HasChineseLang /data/media/movies/Camp.Rock.2008.1080p.BluRay.x265-RARBG/Camp Rock (2008) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:47 - IsSubHasChinese.HasChineseLang /data/media/movies/Freaky.Friday.2003.1080p.BluRay.x265-RARBG/Freaky Friday (2003) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:47 - IsSubHasChinese.HasChineseLang /data/media/movies/Free.Solo.2018.limited.1080p.bluray.x264-cadaver[EtHD]/Free Solo (2018) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:48 - IsSubHasChinese.HasChineseLang /data/media/movies/Hannah.Montana.The.Movie.(2009)/Hannah Montana The Movie (2009) HDTV-720p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:48 - IsSubHasChinese.HasChineseLang /data/media/movies/High.School.Musical.2006.1080p.BluRay.x265-RARBG/High School Musical (2006) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:26:49 - IsSubHasChinese.HasChineseLang /data/media/movies/Home.Alone.1.1990.1080p.BluRay.x264.YIFY/Home Alone (1990) Bluray-1080p.en.srt not chinese sub, is  英
[INFO]: 2022-05-09 21:26:59 - Fix Movie Dir Index 0 /data/media/movies End...
[INFO]: 2022-05-09 21:26:59 - Fix Series Dir Index 0 /data/media/series Start...
[INFO]: 2022-05-09 21:27:15 - Fix Series Dir Index 0 /data/media/series End...
[INFO]: 2022-05-09 21:27:15 - Hotfix 001 End
[INFO]: 2022-05-09 21:27:15 - Hotfix 001 is Recorded
[INFO]: 2022-05-09 21:27:15 - PreDownloadProcess.HotFix() End
[INFO]: 2022-05-09 21:27:15 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-05-09 21:27:15 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-09 21:27:15 - AutoDetectThenChangeTo Movie Index 0 /data/media/movies Start
[WARNING]: 2022-05-09 21:27:18 - IsSubHasChinese.HasChineseLang /data/media/movies/Another.Cinderella.Story.2008.1080p.BluRay.H264.AAC-RARBG/Another Cinderella Story (2008) Bluray-1080p.en.srt not chinese sub, is  英
[WARNING]: 2022-05-09 21:27:19 - IsSubHasChinese.HasChineseLang /data/media/movies/Camp.Rock.2.The.Final.Jam.2010.EXTENDED.1080p.BluRay.x265-RARBG/Camp Rock 2 The Final Jam (2010) Bluray-1080p.en.srt not chinese sub, is  英

[INFO]: 2022-05-09 21:39:10 - AutoDetectThenChangeTo Series Index 0 /data/media/series Start
[INFO]: 2022-05-09 21:39:10 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-05-09 21:39:10 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-05-09 21:39:35 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-05-09 21:39:35 - PreDownloadProcess.Wait() Done.
[INFO]: 2022-05-09 21:39:35 - Download One Started...
[INFO]: 2022-05-09 21:39:35 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-05-09 21:39:35 - Refresh Emby Sub List Start...
[ERROR]: 2022-05-09 21:39:35 - Refresh Emby Sub List Error
[ERROR]: 2022-05-09 21:39:35 - RefreshEmbySubList parse "10.1.1.6:8096/emby/Items": first path segment in URL cannot contain colon
[INFO]: 2022-05-09 21:39:35 - Download One End...
[INFO]: 2022-05-09 21:39:36 - ClearRodTmpRootFolder Done
[ERROR]: 2022-05-09 21:39:36 - downloader_helper.Start() Error: parse "10.1.1.6:8096/emby/Items": first path segment in URL cannot contain colon
[INFO]: 2022-05-09 21:39:36 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-05-09 21:39:36 - matches logs: 1
[INFO]: 2022-05-09 21:39:36 - OneTimeSubtitleScanEnd
[INFO]: 2022-05-09 21:39:36 - First Time coreSubDownloadProcess End
[INFO]: 2022-05-09 21:39:36 - CronHelper Start...
[INFO]: 2022-05-09 21:39:36 - Next Sub Scan Will Process At: 2022-05-10 03:39:36
[INFO]: 2022-05-09 23:45:04 - CronHelper.Stop() Done.
[INFO]: 2022-05-09 23:45:16 - First Time coreSubDownloadProcess Start
[INFO]: 2022-05-09 23:45:16 - Reload Log Settings, level = Info
[INFO]: 2022-05-09 23:45:16 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-05-09 23:45:16 - matches logs: 1
[INFO]: 2022-05-09 23:45:16 - OneTimeSubtitleScanStart
[INFO]: 2022-05-09 23:45:16 - PreDownloadProcess.Init() Start...
[WARNING]: 2022-05-09 23:45:17 - DownFile.GetFileName is string.empty https://cdn.jsdelivr.net/gh/allanpk716/SomeThingsStatic/202259c31ViaG5Q.txt
[INFO]: 2022-05-09 23:45:17 - GetCode 2022-05-09 951275
[INFO]: 2022-05-09 23:45:17 - ClearRodTmpRootFolder Done
[INFO]: 2022-05-09 23:45:17 - PreDownloadProcess.Init() End
[INFO]: 2022-05-09 23:45:17 - PreDownloadProcess.Check() Start...
[INFO]: 2022-05-09 23:45:17 - UseHttpProxy = false
[INFO]: 2022-05-09 23:45:17 - UrlConnectednessTest Target Site https://baidu.com Speed: 183 ms, Status: true
[INFO]: 2022-05-09 23:45:17 - Check Sub Supplier Start...
[INFO]: 2022-05-09 23:46:38 - zimuku Check Alive = true, Speed = 25090 ms
[INFO]: 2022-05-09 23:47:11 - xunlei Check Alive = true, Speed = 32473 ms
[INFO]: 2022-05-09 23:47:12 - shooter Check Alive = true, Speed = 479 ms
[INFO]: 2022-05-09 23:47:12 - subhd Check Alive = true, Speed = 648 ms
[INFO]: 2022-05-09 23:47:12 - Check Sub Supplier End
[INFO]: 2022-05-09 23:47:12 - MovieFolder Index 0 -- /data/media/movies
[INFO]: 2022-05-09 23:47:12 - SeriesPaths Index 0 -- /data/media/series
[INFO]: 2022-05-09 23:47:12 - PreDownloadProcess.Check() End
[INFO]: 2022-05-09 23:47:12 - PreDownloadProcess.HotFix() Start...
[INFO]: 2022-05-09 23:47:12 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-09 23:47:12 - PreDownloadProcess.HotFix() End
[INFO]: 2022-05-09 23:47:12 - PreDownloadProcess.ChangeSubNameFormat() Start...
[INFO]: 2022-05-09 23:47:12 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-09 23:47:12 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-05-09 23:47:12 - PreDownloadProcess.ChangeSubNameFormat() End
[INFO]: 2022-05-09 23:47:12 - PreDownloadProcess.ReloadBrowser() Start...
[INFO]: 2022-05-09 23:47:41 - PreDownloadProcess.ReloadBrowser() End
[INFO]: 2022-05-09 23:47:41 - PreDownloadProcess.Wait() Done.
[INFO]: 2022-05-09 23:47:41 - Download One Started...
[INFO]: 2022-05-09 23:47:41 - NeedRestoreFixTimeLineBK == false
[INFO]: 2022-05-09 23:47:41 - Refresh Emby Sub List Start...
[ERROR]: 2022-05-09 23:47:41 - Refresh Emby Sub List Error
[ERROR]: 2022-05-09 23:47:41 - RefreshEmbySubList parse "10.1.1.6:8096/emby/Items": first path segment in URL cannot contain colon
[INFO]: 2022-05-09 23:47:41 - Download One End...
[INFO]: 2022-05-09 23:47:42 - ClearRodTmpRootFolder Done
[ERROR]: 2022-05-09 23:47:42 - downloader_helper.Start() Error: parse "10.1.1.6:8096/emby/Items": first path segment in URL cannot contain colon
[INFO]: 2022-05-09 23:47:42 - ConfigRootDirFPath /config/Logs
[INFO]: 2022-05-09 23:47:42 - matches logs: 2
[INFO]: 2022-05-09 23:47:42 - OneTimeSubtitleScanEnd
[INFO]: 2022-05-09 23:47:43 - First Time coreSubDownloadProcess End
[INFO]: 2022-05-09 23:47:43 - CronHelper Start...
[INFO]: 2022-05-09 23:47:43 - Next Sub Scan Will Process At: 2022-05-10 05:47:43

**Comment by allanpk716** [comment]
加上 http://10.1.1.6:8096

**Comment by qinxianyuzou** [comment]
> 加上 http://10.1.1.6:8096

加不上啊，没法保存新的，只要开头没有加上http，后面就没法改

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/177023114-ccad8834-0f63-45d4-b168-d2c3edcca7dd.png)


停止再改
