### ISSUE TITLE
群晖docker部署无法找到媒体目录，报错“MovieFolder not found”

### ISSUE THREAD

**Issue by alexTse824** [allanpk716/ChineseSubFinder#33]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
chinesesubfinder 版本: v0.4.0
环境: 群晖docker部署

## 你遇到什么问题了？
**无法找媒体目录**

**NAS媒体文件目录结构：**
|- /volume1/video
|-- Movie
|--- 头号玩家.2018
|---- 头号玩家.2018.2160p.AAC.mkv
|---- 头号玩家.2018.2160p.AAC.nfo
|-- TV series

**docker部署命令**
docker create \
  --name=chinesesubfinder \
  -e PUID=1026 \
  -e PGID=100 \
  -e TZ=Asia/Shanghai \
  -v /volume1/docker/chinesesubfinder/config:/config \
  -v /volume1/video:/media \
  -v /volume1/docker/chinesesubfinder/log:/app/Logs \
  --restart unless-stopped \
  allanpk716/chinesesubfinder:latest

**配置文件config.yaml**
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 4
SubTypePriority: 1
DebugMode: false
SaveMultiSub: true
MovieFolder: /media/Movie
SeriesFolder: /media/TV series

## 出错的日志信息可以复制一些出来吗？
[ERROR]: 2021-07-23 21:04:10 - MovieFolder not found
[ERROR]: 2021-07-23 21:04:11 - MovieFolder not found
[ERROR]: 2021-07-23 21:04:12 - MovieFolder not found
[ERROR]: 2021-07-23 21:04:13 - MovieFolder not found

**Comment by allanpk716** [comment]
你的版本太低了，但是配置版本又很高。v0.11.1 用这个

**Comment by alexTse824** [comment]
docker重新获取v0.11.1版本还是找不到媒体目录

```
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS              PORTS                              NAMES
a8388e621401   allanpk716/chinesesubfinder:v0.11.1   "/init"                  2 minutes ago   Up About a minute                                      chinesesubfinder
```
```
# config.yaml
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 4
SubTypePriority: 1
DebugMode: false
SaveMultiSub: true
MovieFolder: /media/Movie
SeriesFolder: /media/TV series
```

**Comment by alexTse824** [comment]
我在创建容器时使用root的UID和GID就可以了识别媒体文件夹了
