### ISSUE TITLE
Docker/root/etc/cont-init.d/50-config 内存在错误

### ISSUE THREAD

**Issue by ipuppet** [allanpk716/ChineseSubFinder#338]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.26.0
>
> 环境: docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

`Docker/root/etc/cont-init.d/50-config` 中
```shell
# bug: 等号两边需要有空格
if [ "${PERMS}"=true ]
then
  chown -R abc:abc /media
fi
```

如：
```shell
if [ "$PERMS" = "true" ]; then
  chown -R abc:abc /media
fi
```

可尝试运行如下脚本：
```shell
PERMS=0
if [ "${PERMS}"=true ]
then
  echo "1"
fi
```

将输出 `1`

**Comment by allanpk716** [comment]
能提交一个修复的 Pull request 嘛，这部分代码不是我写的，我对于 linux 相关东西都不太清楚。然后我可以找其他人看看。

**Comment by ipuppet** [comment]
> 能提交一个修复的 Pull request 嘛，这部分代码不是我写的，我对于 linux 相关东西都不太清楚。然后我可以找其他人看看。

好的，已经提交
