### ISSUE TITLE
不要搞了大哥们 zimuku.org服务器都被弄崩溃了 

### ISSUE THREAD

**Issue by zimuku** [allanpk716/ChineseSubFinder#343]
你们想要下载字幕就不能直接去网站吗
网站又没广告的 公益性的网站(已经租不起更大的服务器了） 经不起各位大哥们折腾啊...  
实在要搞能不能想办法把服务器负载降到最低...

**Comment by allanpk716** [comment]
很低了啊，所有请求都要15s 延迟，每个任务之间差不多 min 级别延迟。而且最新版本直接排除 zimuku 了啊。

**Comment by zimuku** [comment]
谢谢理解

**Comment by allanpk716** [comment]
> 谢谢理解

真的非常抱歉，不知道是否能够加个联系方式。

因为想自行做本程序的下载分流，所以字幕上有些事情想慎重的跟你们讨论下。

后续对应的代码也会逐步移除或者停止维护。

**Comment by zimuku** [comment]
zimuku.pw@gmail.com
