### ISSUE TITLE
谢谢老大帮我解决问题，老是显示没有挂载目录

### ISSUE THREAD

**Issue by menloveszedking** [allanpk716/ChineseSubFinder#344]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 2.0.6
>
> 环境: docker 
>
> 在程序运行日志头部或者 Web UI 可以看到 ：MoviePaths not set, len == 0，MoviePaths not set, len == 0

## 你遇到什么问题了？
挂载目录为
-v /share/CACHEDEV1_DATA/docker/clouddrive/CloudDrive:/media1:shared \
-v /share/CACHEDEV2_DATA/4T:/media:shared \
-v /share/CACHEDEV1_DATA/docker/chinesesubfinder/config:/Config \
-v /share/CACHEDEV1_DATA/docker/chinesesubfinder/cache:/app/cache \

## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "user_info": {
    "username": "xx", // 这里是用户名，需要替换掉
    "password": "xx" // 这里是密码，需要替换掉
  },
  "common_settings": {
    "scan_interval": "6h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": ["X:\\电影"],
    "series_paths": ["X:\\连续剧"]
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": false,
      "http_proxy_address": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://192.168.50.xxx:xxx", // 这里替换掉
    "api_key": "xxxxxxxxxxxxxx", // 这里替换掉
    "max_request_video_number": 100,
    "skip_watched": true,
    "movie_paths_mapping": {
      "X:\\电影": "/mnt/share1/电影"
    },
    "series_paths_mapping": {
      "X:\\连续剧": "/mnt/share1/连续剧"
    }
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 威联通contanerstation

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
[ChineseSubFinder--202205160000--.log](https://github.com/allanpk716/ChineseSubFinder/files/8699650/ChineseSubFinder--202205160000--.log)

**Comment by allanpk716** [comment]
你去看教程先吧
