### ISSUE TITLE
更新后还是报错

### ISSUE THREAD

**Issue by EdoQ** [allanpk716/ChineseSubFinder#345]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.26.1
>
> 环境: docker for ubuntu
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 后台日志一直报错

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```{
    "SpeedDevMode":false,
    "user_info":{
        "username":"root",
        "password":"passwd"
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/Movies"
        ],
        "series_paths":[
            "/media/TV"
        ],
        "local_static_file_port":"19037"
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"http",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"10809",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":1,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv/",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org/",
                "daily_download_limit":20
            }
        },
        "scan_logic":{
            "skip_chinese_movie":true,
            "skip_chinese_series":true
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":100000,
            "download_sub_during_x_days":100000,
            "one_sub_download_interval":6,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":false,
        "address_url":"",
        "api_key":"",
        "max_request_video_number":500,
        "skip_watched":false,
        "movie_paths_mapping":{
            "/media/Movies":""
        },
        "series_paths_mapping":{
            "/media/TV":""
        },
        "auto_or_manual":false,
        "threads":4
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":false,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 请给出当次问题的完整日志

> [INFO]: 2022-05-16 19:40:21 - updateLocalVideoCacheInfo 49 /media/TV/爱，死亡与机器人
[INFO]: 2022-05-16 19:40:21 - updateLocalVideoCacheInfo 50 /media/TV/鱿鱼游戏.Squid.Game.2021.EP01-09.HD1080P.X264.AAC.Korean.CHS.Mp4er
[INFO]: 2022-05-16 19:40:21 - ScanNormalMovieAndSeries End
[INFO]: 2022-05-16 19:40:21 - ScanEmbyMovieAndSeries Start...
[INFO]: 2022-05-16 19:40:21 - EmbyHelper == nil
[INFO]: 2022-05-16 19:40:21 - ScanEmbyMovieAndSeries End
[INFO]: 2022-05-16 19:40:23 - Video Scan End By webui
[INFO]: 2022-05-16 19:40:23 - ------------------------------------
[ERROR]: 2022-05-16 19:40:30 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:40:45 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:41:00 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:41:15 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:41:30 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:41:45 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:42:00 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:42:15 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:42:30 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:42:45 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:43:00 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:43:15 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:43:30 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:43:45 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:44:00 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:44:15 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:44:30 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:44:45 - Downloader.QueueDownloader() panic
[ERROR]: 2022-05-16 19:45:00 - Downloader.QueueDownloader() panic
> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by EdoQ** [comment]
> ## 你使用的 chinesesubfinder 是什么版本，什么环境？
> > chinesesubfinder 版本: v0.26.1
> > 环境: docker for ubuntu
> > 在程序运行日志头部或者 Web UI 可以看到
> 
> ## 你遇到什么问题了？
> > 后台日志一直报错
> 
> ## 你的问题弄重现嘛？
> > 能够重现
> 
> ## 你期望的结果
> > 描述以下你期望的结果
> 
> ## 给出当前程序的配置文件
> > /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
> > 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)
> 
> ```
>     "SpeedDevMode":false,
>     "user_info":{
>         "username":"root",
>         "password":"passwd"
>     },
>     "common_settings":{
>         "interval_or_assign_or_custom":0,
>         "scan_interval":"@every 6h",
>         "threads":1,
>         "run_scan_at_start_up":true,
>         "movie_paths":[
>             "/media/Movies"
>         ],
>         "series_paths":[
>             "/media/TV"
>         ],
>         "local_static_file_port":"19037"
>     },
>     "advanced_settings":{
>         "proxy_settings":{
>             "use_proxy":false,
>             "use_which_proxy_protocol":"http",
>             "local_http_proxy_server_port":"19036",
>             "input_proxy_address":"127.0.0.1",
>             "input_proxy_port":"10809",
>             "need_pwd":false,
>             "input_proxy_username":"",
>             "input_proxy_password":""
>         },
>         "debug_mode":false,
>         "save_full_season_tmp_subtitles":false,
>         "sub_type_priority":0,
>         "sub_name_formatter":1,
>         "save_multi_sub":false,
>         "custom_video_exts":[
> 
>         ],
>         "fix_time_line":false,
>         "topic":1,
>         "suppliers_settings":{
>             "xunlei":{
>                 "name":"xunlei",
>                 "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
>                 "daily_download_limit":-1
>             },
>             "shooter":{
>                 "name":"shooter",
>                 "root_url":"https://www.shooter.cn/api/subapi.php",
>                 "daily_download_limit":-1
>             },
>             "subhd":{
>                 "name":"subhd",
>                 "root_url":"https://subhd.tv/",
>                 "daily_download_limit":20
>             },
>             "zimuku":{
>                 "name":"zimuku",
>                 "root_url":"https://zimuku.org/",
>                 "daily_download_limit":20
>             }
>         },
>         "scan_logic":{
>             "skip_chinese_movie":true,
>             "skip_chinese_series":true
>         },
>         "task_queue":{
>             "max_retry_times":3,
>             "one_job_time_out":300,
>             "interval":10,
>             "expiration_time":100000,
>             "download_sub_during_x_days":100000,
>             "one_sub_download_interval":6,
>             "check_pulic_ip_target_site":""
>         },
>         "download_file_cache":{
>             "ttl":4320,
>             "unit":"hour"
>         }
>     },
>     "emby_settings":{
>         "enable":false,
>         "address_url":"",
>         "api_key":"",
>         "max_request_video_number":500,
>         "skip_watched":false,
>         "movie_paths_mapping":{
>             "/media/Movies":""
>         },
>         "series_paths_mapping":{
>             "/media/TV":""
>         },
>         "auto_or_manual":false,
>         "threads":4
>     },
>     "developer_settings":{
>         "enable":false,
>         "bark_server_address":""
>     },
>     "timeline_fixer_settings":{
>         "max_offset_time":120,
>         "min_offset":0.1
>     },
>     "experimental_function":{
>         "auto_change_sub_encode":{
>             "enable":false,
>             "des_encode_type":0
>         },
>         "chs_cht_changer":{
>             "enable":false,
>             "des_chinese_language_type":0
>         },
>         "remote_chrome_settings":{
>             "enable":false,
>             "remote_docker_url":"",
>             "remote_adblock_path":"",
>             "remote_user_data_dir":""
>         },
>         "api_key_settings":{
>             "enabled":false,
>             "key":""
>         },
>         "local_chrome_settings":{
>             "enabled":false,
>             "local_chrome_exe_f_path":""
>         }
>     }
> }
> ```
> 
> ## 如果是使用 Docker，请给出对应的配置信息
> > 比如 Docker-Compose 信息，如果是其他方式使用忽略
> version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /root/docker/chinesesubfinder/config:/config
      - /root/docker/chinesesubfinder/cache:/app/cache
      - /qnap:/media
    ports:
      - "19035:19035"
      - "19037:19037"   # v0.26 开始用于开启静态文件服务
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - PERMS=true
    restart: unless-stopped
> ## 请给出当次问题的完整日志
> > [INFO]: 2022-05-16 19:40:21 - updateLocalVideoCacheInfo 49 /media/TV/爱，死亡与机器人
> > [INFO]: 2022-05-16 19:40:21 - updateLocalVideoCacheInfo 50 /media/TV/鱿鱼游戏.Squid.Game.2021.EP01-09.HD1080P.X264.AAC.Korean.CHS.Mp4er
> > [INFO]: 2022-05-16 19:40:21 - ScanNormalMovieAndSeries End
> > [INFO]: 2022-05-16 19:40:21 - ScanEmbyMovieAndSeries Start...
> > [INFO]: 2022-05-16 19:40:21 - EmbyHelper == nil
> > [INFO]: 2022-05-16 19:40:21 - ScanEmbyMovieAndSeries End
> > [INFO]: 2022-05-16 19:40:23 - Video Scan End By webui
> > [INFO]: 2022-05-16 19:40:23 - ------------------------------------
> > [ERROR]: 2022-05-16 19:40:30 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:40:45 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:41:00 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:41:15 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:41:30 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:41:45 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:42:00 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:42:15 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:42:30 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:42:45 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:43:00 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:43:15 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:43:30 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:43:45 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:44:00 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:44:15 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:44:30 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:44:45 - Downloader.QueueDownloader() panic
> > [ERROR]: 2022-05-16 19:45:00 - Downloader.QueueDownloader() panic
> > /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by colufoo** [comment]
https://github.com/allanpk716/ChineseSubFinder/issues/339

**Comment by PQ0000** [comment]
相同+1

**Comment by PQ0000** [comment]
{
  "SpeedDevMode": false,
  "common_settings": {
    "interval_or_assign_or_custom": 1,
    "scan_interval": "0 16 * * *",
    "run_scan_at_start_up": false,
    "movie_paths": [
      "/media/movie"
    ],
    "series_paths": [
      "/media/tv"
    ],
    "local_static_file_port": "19037"
  },
  "advanced_settings": {
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": true,
    "topic": 1,
    "suppliers_settings": {
      "xunlei": {
        "name": "xunlei",
        "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
        "daily_download_limit": -1
      },
      "shooter": {
        "name": "shooter",
        "root_url": "https://www.shooter.cn/api/subapi.php",
        "daily_download_limit": -1
      },
      "subhd": {
        "name": "subhd",
        "root_url": "https://subhd.tv",
        "daily_download_limit": 20
      },
      "zimuku": {
        "name": "zimuku",
        "root_url": "https://zimuku.org",
        "daily_download_limit": 20
      }
    },
    "scan_logic": {
      "skip_chinese_movie": true,
      "skip_chinese_series": true
    },
    "task_queue": {
      "max_retry_times": 3,
      "one_job_time_out": 300,
      "interval": 10,
      "expiration_time": 90,
      "download_sub_during_x_days": 7,
      "one_sub_download_interval": 12,
      "check_pulic_ip_target_site": ""
    },
    "download_file_cache": {
      "ttl": 4320,
      "unit": "hour"
    }
  },
  "emby_settings": {
    "enable": false,
    "max_request_video_number": 500,
    "skip_watched": false,
    "movie_paths_mapping": {
      "/media/movie": ""
    },
    "series_paths_mapping": {
      "/media/tv": ""
    },
    "auto_or_manual": false,
    "threads": 6
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  },
  "experimental_function": {
    "auto_change_sub_encode": {
      "enable": true,
      "des_encode_type": 0
    },
    "chs_cht_changer": {
      "enable": true,
      "des_chinese_language_type": 0
    },
    "remote_chrome_settings": {
      "enable": false,
      "remote_docker_url": "",
      "remote_adblock_path": "",
      "remote_user_data_dir": ""
    },
    "local_chrome_settings": {
      "enabled": false,
      "local_chrome_exe_f_path": ""
    }
  }
}

**Comment by allanpk716** [comment]
删除 cache 文件夹中的内容呢？

**Comment by allanpk716** [comment]
我推送 v0.26.2 打印 panic 的日志看看是什么。你们更新到这个版本后，发一下日志。

**Comment by EdoQ** [comment]
> 删除 cache 文件夹中的内容呢？因为是写文件的，如果文件内容异常也会出现这个问题。或者切换到 v0.26.0 #339 的设置方式。看看是否有问题。排除下是否是文件损坏的问题。

应该可以排除这个，因为升级的时候是删除了cache和config全新部署的，之后又删除了一次问题依旧

**Comment by eadorothy86** [comment]
> 我推送 v0.26.2 打印 panic 的日志看看是什么。你们更新到这个版本后，发一下日志。

日志一直再跳这个错误

(EE)
--


<pre class="allowDefCtxMenu selectabletext" ext:qtip="	and start again.
">	and start again.</pre>

**Comment by eadorothy86** [comment]
> 我推送 v0.26.2 打印 panic 的日志看看是什么。你们更新到这个版本后，发一下日志。

<img width="1225" alt="图片" src="https://user-images.githubusercontent.com/85786428/168627584-af8d1f99-bb3d-4bbe-822c-0b7e1e88032e.png">
一直提示这个错误？

**Comment by allanpk716** [comment]
> > 我推送 v0.26.2 打印 panic 的日志看看是什么。你们更新到这个版本后，发一下日志。
> 
> <img alt="图片" width="1225" src="https://user-images.githubusercontent.com/85786428/168627584-af8d1f99-bb3d-4bbe-822c-0b7e1e88032e.png">
> 
> 一直提示这个错误？

如果你搞不清楚怎么用本地的 chrome，那就先不用。

**Comment by allanpk716** [comment]
> windows exe版本也再报错
> 
> ```shell
> failed to rotate: failed to create new symlink: symlink ChineseSubFinder--202205170000--.log Logs\ChineseSubFinder--202205170000--.log_symlink: A required privilege is not held by the client.
> ```

这个是日志写入权限问题，不用管

**Comment by allanpk716** [comment]
> > [ERROR]: 2022-05-16 23:26:54 - Downloader.QueueDownloader() panic [ERROR]: 2022-05-16 23:26:54 - goroutine 118230 [running]: github.com/allanpk716/ChineseSubFinder/internal/pkg/my_util.PrintPanicStack(0xc000501ce0) /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/my_util/util.go:852 +0x3d github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader.func1() /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/downloader/downloader.go:176 +0x7c panic({0x10ec280, 0x1f1c9c0}) /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/panic.go:1047 +0x266 github.com/allanpk716/ChineseSubFinder/internal/logic/emby_helper.(*EmbyHelper).IsVideoPlayed(0x0, {0x0, 0x0}) /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/logic/emby_helper/embyhelper.go:317 +0x41 github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader(0xc0002f25a0) /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/downloader/downloader.go:202 +0x365 github.com/robfig/cron/v3.FuncJob.Run(0xc00091af68) /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a github.com/robfig/cron/v3.SkipIfStillRunning.func1.1() /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:85 +0x63 github.com/robfig/cron/v3.FuncJob.Run(0xc0000a03c0) /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a github.com/robfig/cron/v3.(*Cron).startJob.func1() /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a created by github.com/robfig/cron/v3.(*Cron).startJob /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2
> 
> docker logs 我试了下也是一样的报错

emby 执行错误，你使用 Emby 的吗？

**Comment by EdoQ** [comment]
> > > [ERROR]: 2022-05-16 23:26:54 - Downloader.QueueDownloader() panic [ERROR]: 2022-05-16 23:26:54 - goroutine 118230 [running]: github.com/allanpk716/ChineseSubFinder/internal/pkg/my_util.PrintPanicStack(0xc000501ce0) /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/my_util/util.go:852 +0x3d github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader.func1() /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/downloader/downloader.go:176 +0x7c panic({0x10ec280, 0x1f1c9c0}) /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/panic.go:1047 +0x266 github.com/allanpk716/ChineseSubFinder/internal/logic/emby_helper.(*EmbyHelper).IsVideoPlayed(0x0, {0x0, 0x0}) /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/logic/emby_helper/embyhelper.go:317 +0x41 github.com/allanpk716/ChineseSubFinder/internal/pkg/downloader.(*Downloader).QueueDownloader(0xc0002f25a0) /home/runner/work/ChineseSubFinder/ChineseSubFinder/internal/pkg/downloader/downloader.go:202 +0x365 github.com/robfig/cron/v3.FuncJob.Run(0xc00091af68) /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a github.com/robfig/cron/v3.SkipIfStillRunning.func1.1() /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:85 +0x63 github.com/robfig/cron/v3.FuncJob.Run(0xc0000a03c0) /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a github.com/robfig/cron/v3.(*Cron).startJob.func1() /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a created by github.com/robfig/cron/v3.(*Cron).startJob /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2
> > 
> > 
> > docker logs 我试了下也是一样的报错
> 
> emby 执行错误，你使用 Emby 的吗？

不是，我是用的是plex+jellyfin

**Comment by allanpk716** [comment]
推送了 v0.26.3，修复你遇到的这个问题 @EdoQ 

@eadorothy86  实验室的功能如果没得什么必须用的理由，我的建议还是不要随意用，是不稳定的功能，仅仅是在我这里测试通过的。

**Comment by allanpk716** [comment]
最新 v0.27-DockerBeta1 ，开 Debug
