### ISSUE TITLE
外挂字幕识别问题

### ISSUE THREAD

**Issue by millsguo** [allanpk716/ChineseSubFinder#346]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.26.1
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 不能识别以下字幕，还是会待在下载队列中，而srt的字幕能识别到

`Bosch - Legacy - S01E01 - The Wrong Side of Goodbye WEBDL-2160p.zh.ass`

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 有已下载的ASS中文字幕时，跳过处理

**Comment by allanpk716** [comment]
1. 一个是需要你上传这个字幕给我分析，看是否是解析器的bug未能识别为中文
2. 你需要看这个[文档](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md)
3. 如果你不想下载，可以去任务队列设置这个任务为 ignore（忽略）

**Comment by millsguo** [comment]
[Bosch - Legacy - S01E01 - The Wrong Side of Goodbye WEBDL-2160p.zh.zip](https://github.com/allanpk716/ChineseSubFinder/files/8704456/Bosch.-.Legacy.-.S01E01.-.The.Wrong.Side.of.Goodbye.WEBDL-2160p.zh.zip)

这个是字幕文件，解压即可

**Comment by allanpk716** [comment]
字幕是正确解析的，你需要看上面的文档，以及描述清楚问题。本程序就不是一次性下载字幕的，会在一个时间范围内反复下载，除非你设置任务忽略，或者提交 HTTP API 通知本程序这个视频配合什么字幕已经观看，又或者你使用 Emby 勾选了跳过已看视频
