### ISSUE TITLE
除了 douban 还有什么地方能够从英文影片名查询到中文译名的?

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#350]
如题，IMDB 的翻译很多在国内不通用，那么就遇到一个问题，英文怎么对应大陆的翻译译名，以及 IMDB 怎么对应对应的中文翻译？

douban 看了下效果是不过的，但是，没得公开接口。

**Comment by pofey** [comment]
imdbid to tmdbid
tmdbid 查tmdb中文名 tmdb开放api。质量不比豆瓣差 还能纠正。

**Comment by terrellgf** [comment]
烂番茄、时光网、猫眼，就知道这么多，至于有没有api或者效果如何，不太清楚

**Comment by allanpk716** [comment]
> imdbid to tmdbid tmdbid 查tmdb中文名 tmdb开放api。质量不比豆瓣差 还能纠正。

ok，我去看看

**Comment by katsuya82** [comment]
Sonarr, Radarr, kodi 和 plex 都轉換到 [themovie](https://www.themoviedb.org/)，建議使用以免造成混亂。

**Comment by allanpk716** [comment]
TMDB 大陆我试了 API 不可访问。不是说转 TMDB 就转，zimuku  subhd 都不支持这个查询，不要为了用而用，要逻辑和业务用的上才用。

**Comment by katsuya82** [comment]
哈哈，所以我說支援，沒說轉過去。TMDB api 似乎有支援使用 imdb id 來做搜尋。

**Comment by allanpk716** [comment]
> 哈哈，所以我說支援，沒說轉過去。TMDB api 似乎有支援使用 imdb id 來做搜尋。

对，真的好用，问题···大陆···你懂的，我想想办法

**Comment by CDC202003** [comment]
> 

网上不都是修改HOST来达成搜刮TMDB吗？

**Comment by allanpk716** [comment]
本程序内置搞定 IMDB 转 TMDB 以及查询对应的英文、中文、OrgName 的接口，如果哪天失效了再考虑第三方的。
