### ISSUE TITLE
重启镜像日志重复不间断

### ISSUE THREAD

**Issue by eadorothy86** [allanpk716/ChineseSubFinder#352]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 0.27bate6
>
> 环境: docker 
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 配置好重启镜像日志重复出错一直不间断

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 清楚问题出在哪里？

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "SpeedDevMode":false,
    "user_info":{
        "username":"",
        "password":""
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 4h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/Movie"
        ],
        "series_paths":[
            "/media/TV"
        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "token":""
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":true,
            "use_which_proxy_protocol":"[http](https://www.json.cn/http)",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"10.10.10.10",
            "input_proxy_port":"7890",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":true,
        "custom_video_exts":[

        ],
        "fix_time_line":true,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv/",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org/",
                "daily_download_limit":20
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":false,
            "skip_chinese_series":false
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":true,
        "address_url":"",
        "api_key":"",
        "max_request_video_number":3000,
        "skip_watched":true,
        "movie_paths_mapping":{
            "/media/Movie":""
        },
        "series_paths_mapping":{
            "/media/TV":""
        },
        "auto_or_manual":true,
        "threads":4
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":true,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        }
    }
}
```
## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

docker run \
--network=bridge \
-p '19035:19035' \
-p '19037:19037' \
-v /volume1/docker/chinesesubfinder/cache:/app/cache \
-v /volume1/docker/chinesesubfinder/config:/config \
-v /volume1/video/link:/media \
-e TZ="Asia/Shanghai" \
--device /dev/dri:/dev/dri \
-e PUID=1026 \
-e PGID=100 \
-e PERMS=true \
--restart always \
--name ChineseSubFinder \
-d allanpk716/chinesesubfinder:v0.27-DockerBeta6

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

 goroutine 1 [running]:

github.com/allanpk716/ChineseSubFinder/internal/pkg/rod_helper.NewBrowser(0xc0001f10a0, {0xc000039b00, 0x30}, {0x0, 0x0}, 0x1, {0x0, 0x0, 0x30})

	/homelab/buildspace/internal/pkg/rod_helper/rodHelper.go:66 +0x569

github.com/allanpk716/ChineseSubFinder/internal/pkg/rod_helper.NewBrowserEx(0x0, 0x80, 0x4826cf, {0x0, 0x0, 0x0})

	/homelab/buildspace/internal/pkg/rod_helper/rodHelper.go:32 +0xb7

github.com/allanpk716/ChineseSubFinder/internal/pkg/rod_helper.ReloadBrowser(0xc0001f10a0)

	/homelab/buildspace/internal/pkg/rod_helper/rodHelper.go:285 +0x4d

github.com/allanpk716/ChineseSubFinder/internal/logic/pre_job.(*PreJob).ReloadBrowser(0xc00046bf40)

	/homelab/buildspace/internal/logic/pre_job/pro_job.go:102 +0x108

main.main()

	/homelab/buildspace/cmd/chinesesubfinder/main.go:97 +0x2ca

(EE) 

Fatal server error:

(EE) Server is already active for display 99

	If this server is no longer running, remove /tmp/.X99-lock

	and start again.

(EE) 

[INFO]: 2022-05-18 22:36:23 - ChineseSubFinder Version: v0.26.3

[INFO]: 2022-05-18 22:36:23 - Reload Log Settings, level = Info

[INFO]: 2022-05-18 22:36:23 - PreJob.HotFix() Start...

[INFO]: 2022-05-18 22:36:23 - If you have a lot of videos, it may take a lot of time, just wait...

[INFO]: 2022-05-18 22:36:23 - PreJob.HotFix() End

[INFO]: 2022-05-18 22:36:23 - PreJob.ChangeSubNameFormat() Start...

[INFO]: 2022-05-18 22:36:23 - If you have a lot of videos, it may take a lot of time, just wait...

[INFO]: 2022-05-18 22:36:23 - DesSubFormatter == LateTimeSubFormatter then skip process

[INFO]: 2022-05-18 22:36:23 - PreJob.ChangeSubNameFormat() End

[INFO]: 2022-05-18 22:36:23 - PreJob.ReloadBrowser() Start...

[INFO]: 2022-05-18 22:36:23 - releaseAdblock start

[INFO]: 2022-05-18 22:36:24 - releaseAdblock end

[ERROR]: 2022-05-18 22:36:24 - localChromeFPath is not a file

[INFO]: 2022-05-18 22:36:24 - PreJob.ReloadBrowser() End

panic: localChromeFPath is not a file

**Comment by allanpk716** [comment]
你确定你上传的配置文件复制对了？你还是把 config 文件直接以文件压缩包的形式上传给我看看吧。我再推送一个版本加强日志输出。

我看到的是你配置了实验室中的本地 Chrome 的功能导致的，检测你本地的 Chrome 不存在

**Comment by eadorothy86** [comment]
> 你试试 v0.27-DockerBeta8 ，以及把你的 config 文件打包发上来，记得去除敏感信息，但是也别把 Chrome 相关的配置给删除了，不然也可能看不出问题。打 ** 就好了

我没有打开Chrome的按钮，是需要打开的吗？
