### ISSUE TITLE
希望加入https://www.a4k.net/这个字幕来源，没什么验证，挺好用的

### ISSUE THREAD

**Issue by shanyan-wcx** [allanpk716/ChineseSubFinder#353]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by boin** [comment]
+1

**Comment by allanpk716** [comment]
它对 xxx s0xe0x 这种搜索效果很差，不如 assrt，唯一支持的可能性是在视频列表处手动触发搜索，弹出结果列表让人自己选择并下载。

**Comment by shanyan-wcx** [comment]
我在搜索框搜S0XE0X都能搜出来啊

**Comment by allanpk716** [comment]
你需要多试，如果好用我会主动集成的

![image](https://user-images.githubusercontent.com/1176000/169466311-258101bc-fd25-4d4b-a2a7-7695178f8c4f.png)

**Comment by xiNeRoar** [comment]
> 你需要多试，如果好用我会主动集成的
> 
> ![image](https://user-images.githubusercontent.com/1176000/169466311-258101bc-fd25-4d4b-a2a7-7695178f8c4f.png)

這個網站我常用 他字幕的確更新很快 可是需要用英文搜尋才比較準確 用中文會經常搜不到

**Comment by allanpk716** [comment]
> > 你需要多试，如果好用我会主动集成的
> > ![image](https://user-images.githubusercontent.com/1176000/169466311-258101bc-fd25-4d4b-a2a7-7695178f8c4f.png)
> 
> 這個網站我常用 他字幕的確更新很快 可是需要用英文搜尋才比較準確 用中文會經常搜不到

OK，那我试试英文搜索看，如果我追的剧集都能搞定，可以应该很快可以集成

**Comment by allanpk716** [comment]
最近事情比较多，这个功能我拉了个新手来练手做爬虫，所以他搞定了，我就来对接哈 :joy:

**Comment by allanpk716** [comment]
最新版本已经支持，暂时看到的反馈是褒贬不一。如果不想用这个源，就去每日下载次数限制中设置为 0.
