### ISSUE TITLE
能否将已经完成的任务从队列中清理掉

### ISSUE THREAD

**Issue by ihola777** [allanpk716/ChineseSubFinder#354]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
chinesesubfinder 版本: v0.27.1
环境: docker 

## 你想要新增或者改进什么功能？
将已经下载完成的任务从队列中清理掉

## 这个功能有什么可以参考的资料吗？
nope

**Comment by allanpk716** [comment]
界面的逻辑和交互还有改进的空间，现在叫做能用。我跟 @iMyon 商量下先，以最小代价先做稍微好用先，得先做其他功能
