### ISSUE TITLE
能否增设同时下载字幕数量

### ISSUE THREAD

**Issue by eadorothy86** [allanpk716/ChineseSubFinder#356]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.27.1

环境: docker 群辉918+

## 你想要新增或者改进什么功能？

限制下载字幕数量同时运行，例如10个？

## 这个功能有什么可以参考的资料吗？

 一下子运行几十个字幕下载CPU马上吃满

**Comment by allanpk716** [comment]
一次一个视频下载字幕的任务，都是单线程，不考虑给多线程，避免目标网站扛不住。
