### ISSUE TITLE
手动提交下载字幕出错

### ISSUE THREAD

**Issue by lostiv** [allanpk716/ChineseSubFinder#357]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 
>v0.27.1
> 环境: 
>docker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 手动添加下载失败

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 手动添加下载任务成功

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "SpeedDevMode":false,
    "user_info":{
        "username":"忽略",
        "password":"忽略"
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":6,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media",
            "/media3",
            "/media4"
        ],
        "series_paths":[
            "/media2",
            "/media5",
            "/media6",
            "/media7",
            "/media8",
            "/media9"
        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "enabled":true,
            "token":"忽略"
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"[http](https://www.json.cn/http)",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"忽略",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":1,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv/",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org/",
                "daily_download_limit":20
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":true,
            "skip_chinese_series":true
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":true,
        "address_url":"忽略",
        "api_key":"忽略",
        "max_request_video_number":3000,
        "skip_watched":true,
        "movie_paths_mapping":{
            "/media":"/volume2/shr/video/movie",
            "/media3":"/volume1/pt/nastool/links/华语电影",
            "/media4":"/volume1/pt/nastool/links/外语电影"
        },
        "series_paths_mapping":{
            "/media2":"/volume2/shr/video/tv show",
            "/media5":"/volume1/pt/nastool/links/国产剧",
            "/media6":"/volume1/pt/nastool/links/日韩剧",
            "/media7":"/volume1/pt/nastool/links/欧美剧",
            "/media8":"/volume1/pt/nastool/links/纪录片",
            "/media9":"/volume1/pt/nastool/links/动漫"
        },
        "auto_or_manual":true,
        "threads":6
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":true,
            "key":"忽略"
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
[INFO]: 2022-05-20 10:02:46 - ------------------------------------------
[INFO]: 2022-05-20 10:02:46 - CloseChrome End
[INFO]: 2022-05-20 10:06:50 - Download.SupplierCheck() Start ...
[INFO]: 2022-05-20 10:06:50 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2022-05-20 10:06:50 - PreDownloadProcess.Init() Start...
[INFO]: 2022-05-20 10:07:07 - GetCode 2022-05-20 951275
[INFO]: 2022-05-20 10:07:07 - ClearRodTmpRootFolder Done
[INFO]: 2022-05-20 10:07:07 - PreDownloadProcess.Init() End
[INFO]: 2022-05-20 10:07:07 - PreDownloadProcess.Check() Start...
[INFO]: 2022-05-20 10:07:07 - UseHttpProxy = false
[INFO]: 2022-05-20 10:07:07 - UrlConnectednessTest Target Site https://baidu.com Speed: 242 ms, Status: true
[INFO]: 2022-05-20 10:07:07 - Check Sub Supplier Start...
[INFO]: 2022-05-20 10:07:08 - xunlei Check Alive = true, Speed = 158 ms
[INFO]: 2022-05-20 10:07:08 - shooter Check Alive = true, Speed = 450 ms
[INFO]: 2022-05-20 10:07:08 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 0
[INFO]: 2022-05-20 10:07:08 - assrt Check Alive = true, Speed = 300 ms
[INFO]: 2022-05-20 10:07:09 - subhd Check Alive = true, Speed = 751 ms
[INFO]: 2022-05-20 10:07:10 - [GetPublicIP] 154.198.214.49
[INFO]: 2022-05-20 10:07:10 - subhd DailyDownloadLimit: 20 Now Is: 0
[INFO]: 2022-05-20 10:07:10 - Alive Supplier: xunlei
[INFO]: 2022-05-20 10:07:10 - Alive Supplier: shooter
[INFO]: 2022-05-20 10:07:10 - Alive Supplier: assrt
[INFO]: 2022-05-20 10:07:10 - Alive Supplier: subhd
[INFO]: 2022-05-20 10:07:10 - Check Sub Supplier End
[INFO]: 2022-05-20 10:07:10 - MovieFolder Index 0 -- /media
[INFO]: 2022-05-20 10:07:10 - MovieFolder Index 1 -- /media3
[INFO]: 2022-05-20 10:07:10 - MovieFolder Index 2 -- /media4
[INFO]: 2022-05-20 10:07:10 - SeriesPaths Index 0 -- /media2
[INFO]: 2022-05-20 10:07:10 - SeriesPaths Index 1 -- /media5
[INFO]: 2022-05-20 10:07:10 - SeriesPaths Index 2 -- /media6
[INFO]: 2022-05-20 10:07:10 - SeriesPaths Index 3 -- /media7
[INFO]: 2022-05-20 10:07:10 - SeriesPaths Index 4 -- /media8
[INFO]: 2022-05-20 10:07:10 - SeriesPaths Index 5 -- /media9
[INFO]: 2022-05-20 10:07:10 - PreDownloadProcess.Check() End
[INFO]: 2022-05-20 10:07:10 - PreDownloadProcess.Wait() Done.
[INFO]: 2022-05-20 10:07:10 - Download.SupplierCheck() End
[ERROR]: 2022-05-20 10:08:25 - VideoListAddHandler decode.GetSeriesDirRootFPath == Empty, /media4/瞬息全宇宙 (2022)/瞬息全宇宙 (2022).mkv
[ERROR]: 2022-05-20 10:15:47 - VideoListAddHandler decode.GetSeriesDirRootFPath == Empty, /media4/浪客剑心最终章：追忆篇 (2021)/浪客剑心最终章：追忆篇 (2021).mkv

**Comment by allanpk716** [comment]
我需要新增一些出错的日志输出，看看是为什么。

你先反馈下这一集的文件夹目录结构给我看看，以及还有什么内容在里面。

` /media4/瞬息全宇宙 (2022)/瞬息全宇宙 (2022).mkv`  这个是一部电影对吧，你去看看任务界面，它是被认为是电影还是连续剧，你需要截图给我看。

下面那个浪客剑心也是，需要你截图。这个是因为走错了下载逻辑，把电影当连续剧去处理了。

**Comment by lostiv** [comment]
新版本已解决
