### ISSUE TITLE
truenas scale 拉取docker镜像失败

### ISSUE THREAD

**Issue by 1061875478** [allanpk716/ChineseSubFinder#368]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
docker
## 你遇到什么问题了？
拉取镜像提示
Failed to pull image "allanpk716/chinesesubfinder:latest": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry-1.docker.io/v2/": unexpected EOF

**Comment by ZCkyle** [comment]
> 

老板，不知道为什么，latest标签拉到的都不是最新的镜像.....每次都是手动更改docker-compose后面的版本号...
