### ISSUE TITLE
群晖docker下无法下载字幕

### ISSUE THREAD

**Issue by ferdinand474** [allanpk716/ChineseSubFinder#369]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.27.3
>v0.27.3
> 环境: docker or Window or Linux or MAC
>doecker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 所以视频字幕无法下载

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

{
  "SpeedDevMode": false,
  "common_settings": {
    "interval_or_assign_or_custom": 0,
    "scan_interval": "@every 6h",
    "run_scan_at_start_up": true,
    "movie_paths": [
      "/media/video1",
      "/media/video2"
    ],
    "series_paths": [
      "/media/video2"
    ],
    "local_static_file_port": "19037"
  },
  "subtitle_sources": {
    "assrt_settings": {
      "enabled": false,
      "token": ""
    }
  },
  "advanced_settings": {
    "debug_mode": false,
    "save_full_season_tmp_subtitles": false,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": false,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1,
    "suppliers_settings": {
      "xunlei": {
        "name": "xunlei",
        "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
        "daily_download_limit": 100
      },
      "shooter": {
        "name": "shooter",
        "root_url": "https://www.shooter.cn/api/subapi.php",
        "daily_download_limit": 100
      },
      "subhd": {
        "name": "subhd",
        "root_url": "https://subhd.tv",
        "daily_download_limit": 20
      },
      "zimuku": {
        "name": "zimuku",
        "root_url": "https://zimuku.org",
        "daily_download_limit": 20
      },
      "assrt": {
        "name": "assrt",
        "root_url": "https://api.assrt.net/v1",
        "daily_download_limit": -1
      }
    },
    "scan_logic": {
      "skip_chinese_movie": false,
      "skip_chinese_series": false
    },
    "task_queue": {
      "max_retry_times": 3,
      "one_job_time_out": 300,
      "interval": 10,
      "expiration_time": 90,
      "download_sub_during_x_days": 7,
      "one_sub_download_interval": 12,
      "check_pulic_ip_target_site": ""
    },
    "download_file_cache": {
      "ttl": 4320,
      "unit": "hour"
    }
  },
  "emby_settings": {
    "enable": true,
    "max_request_video_number": 3000,
    "skip_watched": false,
    "movie_paths_mapping": {
      "/media/video1": "/volume1/个人资料/岛国资料",
      "/media/video2": "/volume1/电影"
    },
    "series_paths_mapping": {
      "/media/video2": "/volume1/电影"
    },
    "auto_or_manual": false,
    "threads": 4
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  },
  "experimental_function": {
    "auto_change_sub_encode": {
      "enable": false,
      "des_encode_type": 0
    },
    "chs_cht_changer": {
      "enable": false,
      "des_chinese_language_type": 0
    },
    "remote_chrome_settings": {
      "enable": false,
      "remote_docker_url": "",
      "remote_adblock_path": "",
      "remote_user_data_dir": ""
    },
    "local_chrome_settings": {
      "enabled": false,
      "local_chrome_exe_f_path": ""
    }
  }
}

## 如果是使用 Docker，请给出对应的配置信息

> {
    "AppArmorProfile": "docker-default",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/init"
        ],
        "Env": [
            "PUID=1026",
            "PGID=100",
            "TZ=Asia/Shanghai",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME=/root",
            "LANGUAGE=en_US.UTF-8",
            "LANG=en_US.UTF-8",
            "TERM=xterm",
            "PERMS=true"
        ],
        "ExposedPorts": {
            "19035/tcp": {},
            "19037/tcp": {}
        },
        "Hostname": "GuiSynology",
        "Image": "allanpk716/chinesesubfinder:latest",
        "Labels": {
            "build_version": "Linuxserver.io version:- 507fb928-ls52 Build-date:- 2022-05-17T07:05:03+02:00",
            "maintainer": "TheLamer",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2022-05-17T07:05:03+02:00",
            "org.opencontainers.image.description": "baseimage-ubuntu image by linuxserver.io",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-baseimage-ubuntu",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "edbc571210d38a77becbde666a584739433940e6",
            "org.opencontainers.image.revision": "edbc571210d38a77becbde666a584739433940e6",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-baseimage-ubuntu",
            "org.opencontainers.image.title": "Baseimage-ubuntu",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-baseimage-ubuntu/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "507fb928-ls52"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/app/cache": {},
            "/config": {},
            "/media": {},
            "/media/video1": {},
            "/media/video2": {}
        },
        "WorkingDir": ""
    },
    "Created": "2022-05-24T19:21:59.259287806Z",
    "Driver": "vfs",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": null,
        "Name": "vfs"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/volume1/docker/chinesesubfinder/cache:/app/cache",
            "/volume1/docker/chinesesubfinder/config:/config",
            "/volume1/电影:/media/video1",
            "/volume1/个人资料/岛国资料:/media/video2"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "host",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "19035/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "19035"
                }
            ],
            "19037/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "19037"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/volume1/@appstore/Docker/data/Docker/containers/e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e/hostname",
    "HostsPath": "/volume1/@appstore/Docker/data/Docker/containers/e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e/hosts",
    "Id": "e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e",
    "Image": "sha256:2d555176cfaa3d6a7cba381907f74d28ea2dc8c0c5abe8c9f897474111dc36ef",
    "LogPath": "/volume1/@appstore/Docker/data/Docker/containers/e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e/e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/docker/chinesesubfinder/config",
            "Type": "bind"
        },
        {
            "Destination": "/media/video1",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/电影",
            "Type": "bind"
        },
        {
            "Destination": "/media/video2",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/个人资料/岛国资料",
            "Type": "bind"
        },
        {
            "Destination": "/media",
            "Driver": "local",
            "Mode": "",
            "Name": "47b94858555ceb0abc6b814b240b6c3ef483cb14d4b9ca61e6ba68271ce6cea8",
            "Propagation": "",
            "RW": true,
            "Source": "/volume1/@appstore/Docker/data/Docker/volumes/47b94858555ceb0abc6b814b240b6c3ef483cb14d4b9ca61e6ba68271ce6cea8/_data",
            "Type": "volume"
        },
        {
            "Destination": "/app/cache",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/volume1/docker/chinesesubfinder/cache",
            "Type": "bind"
        }
    ],
    "Name": "/chinesesubfinder",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "host": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "afe07d99b2ea90c0e5e9dfbc8e4cae7b15139f4ddbb2ed522c0781691fdec50b",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "774606423c63a5572420349ceed6a6bcd15c28d7c557993f8d8e6712020bf244"
            }
        },
        "Ports": {},
        "SandboxID": "cd1ffa2cbf287b8e289712faad55c82fc259dfcbda50d784dd19a25718d21d14",
        "SandboxKey": "/var/run/docker/netns/default",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 3,
            "ResourceId": "e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [
                {
                    "UserId": 1,
                    "AccessLevel": 1
                }
            ],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": false,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/volume1/@appstore/Docker/data/Docker/containers/e3e1566b8da22991ce4ff66a784ff87ac63fa62138777804b91cedf156238e1e/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2022-05-24T19:38:19.521886921Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 21250,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2022-05-24T19:38:29.284302305Z",
        "Status": "running"
    }
}

## 请给出当次问题的完整日志

> [INFO]: 2022-05-25 03:50:12 - Queue 1 DlSub Start /media/video1/ssis-241-C/ssis-241-C.mp4
[INFO]: 2022-05-25 03:50:12 - Queue 1 xunlei /media/video1/ssis-241-C/ssis-241-C.mp4
[INFO]: 2022-05-25 03:50:12 - Queue 1 xunlei Start...
[ERROR]: 2022-05-25 03:50:12 - xunlei /media/video1/ssis-241-C/ssis-241-C.mp4 not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:12 - Queue 1 xunlei End...
[ERROR]: 2022-05-25 03:50:12 - Queue 1 xunlei oneMovieDlSubInOneSite xunlei /media/video1/ssis-241-C/ssis-241-C.mp4 not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:12 - Queue 1 shooter /media/video1/ssis-241-C/ssis-241-C.mp4
[INFO]: 2022-05-25 03:50:12 - Queue 1 shooter Start...
[ERROR]: 2022-05-25 03:50:12 - shooter /media/video1/ssis-241-C/ssis-241-C.mp4 not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:12 - Queue 1 shooter End...
[ERROR]: 2022-05-25 03:50:12 - Queue 1 shooter oneMovieDlSubInOneSite shooter /media/video1/ssis-241-C/ssis-241-C.mp4 not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:12 - Queue 1 DlSub End /media/video1/ssis-241-C/ssis-241-C.mp4
[WARNING]: 2022-05-25 03:50:12 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2022-05-25 03:50:12 - No Sub Found ssis-241-C.mp4
[ERROR]: 2022-05-25 03:50:12 - SearchMatchedSubFileByOneVideo open /media/video1/ssis-241-C: no such file or directory

> [INFO]: 2022-05-25 03:50:26 - Queue 1 DlSub Start /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv
[INFO]: 2022-05-25 03:50:26 - Queue 1 xunlei /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv
[INFO]: 2022-05-25 03:50:26 - Queue 1 xunlei Start...
[ERROR]: 2022-05-25 03:50:26 - xunlei /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:26 - Queue 1 xunlei End...
[ERROR]: 2022-05-25 03:50:26 - Queue 1 xunlei oneMovieDlSubInOneSite xunlei /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:26 - Queue 1 shooter /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv
[INFO]: 2022-05-25 03:50:26 - Queue 1 shooter Start...
[ERROR]: 2022-05-25 03:50:26 - shooter /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:26 - Queue 1 shooter End...
[ERROR]: 2022-05-25 03:50:26 - Queue 1 shooter oneMovieDlSubInOneSite shooter /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:50:26 - Queue 1 DlSub End /media/video2/The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv
[WARNING]: 2022-05-25 03:50:26 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2022-05-25 03:50:26 - No Sub Found The.Bourne.Identity.2002.1080p.BluRay.x264.DTS-X.7.1-SWTYBLZ.mkv
[INFO]: 2022-05-25 03:50:26 - CloseChrome Start...

> [INFO]: 2022-05-25 03:46:42 - Queue 1 DlSub Start /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv
[INFO]: 2022-05-25 03:46:42 - Queue 1 xunlei /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv
[INFO]: 2022-05-25 03:46:42 - Queue 1 xunlei Start...
[ERROR]: 2022-05-25 03:46:42 - xunlei /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:46:42 - Queue 1 xunlei End...
[ERROR]: 2022-05-25 03:46:42 - Queue 1 xunlei oneMovieDlSubInOneSite xunlei /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:46:42 - Queue 1 shooter /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv
[INFO]: 2022-05-25 03:46:42 - Queue 1 shooter Start...
[ERROR]: 2022-05-25 03:46:42 - shooter /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:46:42 - Queue 1 shooter End...
[ERROR]: 2022-05-25 03:46:42 - Queue 1 shooter oneMovieDlSubInOneSite shooter /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv not exist, and it`s not a Blue ray Video FakeFileName
[INFO]: 2022-05-25 03:46:42 - Queue 1 DlSub End /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv
[WARNING]: 2022-05-25 03:46:42 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2022-05-25 03:46:42 - No Sub Found Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv
[INFO]: 2022-05-25 04:06:16 - Queue 1 DlSub Start /media/video2/Persian.Lessons.2020.GERMAN.1080p.BluRay.x264.DD5.1-BdC.mkv
[WARNING]: 2022-05-25 04:06:16 - cancel Downloader.QueueDownloader()

以上是我下载3部不同的电影字幕时候的任务日志，均是无法成功下载
![image](https://user-images.githubusercontent.com/38850880/170125354-e5ce2f6e-ca02-448d-83c0-1e0cb6960f31.png)

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/170153896-350d0765-f1c9-4a26-bfcc-ec9dca7c0180.png)

配置问题？
