### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by BanKnight** [allanpk716/ChineseSubFinder#37]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

docker的最新版本

环境: docker  on 群晖

## 你遇到什么问题了？

启动内存偏高 + 内存持续上涨
启动内存600+m，一直飙升，到达700+后回落

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

用go编写的程序，建议内存占用30m内吧

## 可以提供遇到问题时候，电影、连续剧的信息吗？

暂不提供

## 出错的日志信息可以复制一些出来吗？

查看了一下，日志中没有报错信息

**Comment by allanpk716** [comment]
subhd 和 zimuku 是用浏览器去爬的字幕，内存高很正常。可以开低并发量。

**Comment by allanpk716** [comment]
起因也是为了解决反爬虫的问题，应该没有更好的解决方案。
