### ISSUE TITLE
docker版本更新需要重新拉取么？

### ISSUE THREAD

**Issue by wab201** [allanpk716/ChineseSubFinder#370]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
是的，晚几个版本才会考虑在线更新

**Comment by wab201** [comment]
早啊，谢谢，难怪我重启好多次都更新不了，我重新拉取算啦

**Comment by allanpk716** [comment]
现在优化了容器的编译逻辑，后续下载会小很多，应该会在 v0.31 发布，然后基于这个镜像后续的更新会下载起来更小。

**Comment by avsba001** [comment]
watchtower可以帮你拉取更新

**Comment by allanpk716** [comment]
> watchtower可以帮你拉取更新

如果使用国内的镜像源，有可能拉取的 latest 是错误的，这个没啥好办法，我自己也放弃这个方案了，也是手动更新 😂

**Comment by westay1984** [comment]
> > watchtower可以帮你拉取更新
> 
> 如果使用国内的镜像源，有可能拉取的 latest 是错误的，这个没啥好办法，我自己也放弃这个方案了，也是手动更新 😂

请问docker 上的v0.2x 镜像是给清理了吗 tag里面也找不到 在哪里还能拉取

**Comment by allanpk716** [comment]
> > > watchtower可以帮你拉取更新
> > 
> > 
> > 如果使用国内的镜像源，有可能拉取的 latest 是错误的，这个没啥好办法，我自己也放弃这个方案了，也是手动更新 😂
> 
> 请问docker 上的v0.2x 镜像是给清理了吗 tag里面也找不到 在哪里还能拉取

docker 发布版本数量限制，且新版本显然修复了很多问题，不建议使用老版本

**Comment by allanpk716** [comment]
在线更新的问题，我个人觉得是没有足够的带宽和流量供大家下载···具体能更新到这个方式，得等 cloudflare 的对象存储正式上线再评估
