### ISSUE TITLE
群晖docker。搜索搜不到字幕，日志如图

### ISSUE THREAD

**Issue by wang923345843** [allanpk716/ChineseSubFinder#372]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: last
>
> 环境: 群晖docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 字幕No Sub Found

## 你的问题弄重现嘛？

以下是群晖docker 日志
<html>

[INFO]: 2022-05-27 21:04:56 - OneTimeSubtitleScanStart#3fde160f5f70d332aa4ae4afcc2393566147cd85f5a65e85de7328113f0d8904
[WARNING]: 2022-05-27 21:04:56 - cancel Downloader.QueueDownloader()
[INFO]: 2022-05-27 21:04:56 - OneTimeSubtitleScanEnd
[INFO]: 2022-05-27 21:04:56 - ------------------------------------------
[INFO]: 2022-05-27 21:04:56 - Queue 1 DlSub Start /media1/电影/误杀2/误杀2 (2021).mkv
[INFO]: 2022-05-27 21:04:56 - Queue 1 xunlei /media1/电影/误杀2/误杀2 (2021).mkv
[INFO]: 2022-05-27 21:04:56 - Queue 1 xunlei Start...
2022/05/27 21:04:57.072368 ERROR RESTY Get "http://sub.xmp.sandai.net:8000/subxl/A944AE376B2D480D9B08AF00AD64C9D9136CCA86.json": read tcp 172.17.0.6:58768->106.14.221.44:8000: read: connection reset by peer, Attempt 1
[INFO]: 2022-05-27 21:05:27 - Queue 1 xunlei End...
[INFO]: 2022-05-27 21:05:27 - Queue 1 shooter /media1/电影/误杀2/误杀2 (2021).mkv
[INFO]: 2022-05-27 21:05:27 - Queue 1 shooter Start...
[INFO]: 2022-05-27 21:05:27 - Queue 1 shooter End...
[INFO]: 2022-05-27 21:05:27 - Queue 1 subhd /media1/电影/误杀2/误杀2 (2021).mkv
[INFO]: 2022-05-27 21:05:28 - [GetPublicIP] 103.156.243.58
[INFO]: 2022-05-27 21:05:28 - subhd DailyDownloadLimit: 10000 Now Is: 0
[INFO]: 2022-05-27 21:05:28 - Queue 1 subhd Start...
[INFO]: 2022-05-27 21:05:28 - Search Keyword: tt16117346
[INFO]: 2022-05-27 21:05:58 - Search Keyword: 误杀2 2021
[INFO]: 2022-05-27 21:06:27 - Queue 1 subhd End...
[INFO]: 2022-05-27 21:06:27 - Queue 1 DlSub End /media1/电影/误杀2/误杀2 (2021).mkv
[WARNING]: 2022-05-27 21:06:27 - OneMovieDlSubInAllSite.subInfos == 0, No Sub Downloaded.
[INFO]: 2022-05-27 21:06:27 - No Sub Found 误杀2 (2021).mkv
2022/05/27 21:06:27 /homelab/buildspace/internal/pkg/cache_center/task_queue_info.go:49 SLOW SQL >= 200ms
[705.823ms] [rows:1] UPDATE `task_queue_infos` SET `created_at`="2022-05-27 20:07:26.675",`updated_at`="2022-05-27 21:06:27.088",`deleted_at`=NULL,`priority`=0,`rel_path`="0.tq" WHERE `id` = 4 AND `task_queue_infos`.`deleted_at` IS NULL

2022/05/27 21:06:28 /homelab/buildspace/internal/pkg/cache_center/task_queue_info.go:49 SLOW SQL >= 200ms
[552.846ms] [rows:1] UPDATE `task_queue_infos` SET `created_at`="2022-05-27 19:18:41.283",`updated_at`="2022-05-27 21:06:27.794",`deleted_at`=NULL,`priority`=5,`rel_path`="5.tq" WHERE `id` = 2 AND `task_queue_infos`.`deleted_at` IS NULL
[INFO]: 2022-05-27 21:06:28 - CloseChrome Start...
[INFO]: 2022-05-27 21:06:28 - CloseChrome End
-- | --

</div>
</body>
</html>

**Comment by allanpk716** [comment]
有什么问题？

**Comment by wang923345843** [comment]
> 

搜不到字幕，请问是什么问题，EMBY都刮削过了，有nfo

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/170830839-0f9219fd-210b-4e95-a324-96b04cb9019f.png)

![image](https://user-images.githubusercontent.com/1176000/170830849-e8eda34b-6413-45f4-b6df-7134e8c70ef4.png)


没得问题

**Comment by wang923345843** [comment]
不知道是哪里的错误，搜不到字幕，请指点下





------------------ 原始邮件 ------------------
发件人: Chin allan ***@***.***&gt;
发送时间: 2022年5月28日 09:32
收件人: allanpk716/ChineseSubFinder ***@***.***&gt;
抄送: wang923345843 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[allanpk716/ChineseSubFinder] 群晖docker。搜索搜不到字幕，日志如图 (Issue #372)
