### ISSUE TITLE
群晖docker 29.3最新版，配置里面，字幕数量没法修改，一个都改不了

### ISSUE THREAD

**Issue by wang923345843** [allanpk716/ChineseSubFinder#376]
群晖docker 29.3最新版，配置里面，字幕数量没法修改，一个都改不了
![次数无法修改](https://user-images.githubusercontent.com/100781270/171010695-4ebd5117-300d-4dde-a187-4bd9d9461881.PNG)

**Comment by wang923345843** [comment]
顺便在问下，下载列表好几百个，怎么删除？太多了

**Comment by wang923345843** [comment]
实测，整个29版本都不能改

**Comment by allanpk716** [comment]
https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.26%E6%95%99%E7%A8%8B/%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E.md

![image](https://user-images.githubusercontent.com/1176000/171025218-01d19dc6-d397-4104-b320-9118789b3044.png)

**Comment by wang923345843** [comment]
> https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/v0.26%E6%95%99%E7%A8%8B/%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E.md
> 
> ![image](https://user-images.githubusercontent.com/1176000/171025218-01d19dc6-d397-4104-b320-9118789b3044.png)

但是现在一个都设置不了。我刚才测试了28版本可以改，29都改不了，每项1都改不了

**Comment by allanpk716** [comment]
收到，我们定位下问题。

**Comment by allanpk716** [comment]
> 顺便在问下，下载列表好几百个，怎么删除？太多了

没有提供直接的删除逻辑（因为懒得做，任务的生命周期由本程序自动控制），你可以选择升级某些任务，或者降级。
