### ISSUE TITLE
docker 部署  不能打开wengui

### ISSUE THREAD

**Issue by 757020177** [allanpk716/ChineseSubFinder#377]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
>29.3
> 环境: docker or Window or Linux or MAC
>lubuntu 20.04LTs        docker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 部署完毕以后等了好久 也不能打开webgui   ip：19035

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 可以打开webgui

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "SpeedDevMode":false,
    "user_info":{
        "username":"",
        "password":""
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[

        ],
        "series_paths":[

        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "enabled":false,
            "token":""
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"[http](https://www.json.cn/http)",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"10809",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv/",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org/",
                "daily_download_limit":20
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "daily_download_limit":-1
            },
            "a4k":{
                "name":"a4k",
                "root_url":"https://www.a4k.net/",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":false,
            "skip_chinese_series":false
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":false,
        "address_url":"",
        "api_key":"",
        "max_request_video_number":500,
        "skip_watched":false,
        "movie_paths_mapping":{

        },
        "series_paths_mapping":{

        },
        "auto_or_manual":false,
        "threads":4
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":false,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        },
        "share_sub_settings":{
            "share_sub_enabled":false
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 我是Ubuntu20.04 LTs  
docker-composer部署

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /mnt/chinesesubfinder/config:/config
      - /mnt/chinesesubfinder/cache:/app/cache
      - /mnt/film/film:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PERMS=true
    ports:
      - 19035:19035
      - 19037:19037 
    restart: unless-stopped

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> [INFO]: 2022-05-31 14:57:17 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-05-31 14:57:17 - Reload Log Settings, level = Info
[INFO]: 2022-05-31 14:57:17 - Speed Dev Mode is Off
[INFO]: 2022-05-31 14:57:17 - PreJob.HotFix() Start...
[INFO]: 2022-05-31 14:57:17 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-31 14:57:17 - PreJob.HotFix() End
[INFO]: 2022-05-31 14:57:17 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-05-31 14:57:17 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-05-31 14:57:17 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-05-31 14:57:17 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-05-31 14:57:17 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-05-31 14:57:17 - releaseAdblock start
[INFO]: 2022-05-31 14:57:18 - releaseAdblock end

**Comment by allanpk716** [comment]
把要填写的信息补充完

**Comment by 757020177** [comment]
我都没有进入到webgui  所以没有配置

**Comment by 757020177** [comment]
{
    "SpeedDevMode":false,
    "user_info":{
        "username":"",
        "password":""
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[

        ],
        "series_paths":[

        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "enabled":false,
            "token":""
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"[http](https://www.json.cn/http)",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"10809",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv/",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org/",
                "daily_download_limit":20
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "daily_download_limit":-1
            },
            "a4k":{
                "name":"a4k",
                "root_url":"https://www.a4k.net/",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":false,
            "skip_chinese_series":false
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":false,
        "address_url":"",
        "api_key":"",
        "max_request_video_number":500,
        "skip_watched":false,
        "movie_paths_mapping":{

        },
        "series_paths_mapping":{

        },
        "auto_or_manual":false,
        "threads":4
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":false,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        },
        "share_sub_settings":{
            "share_sub_enabled":false
        }
    }
}

**Comment by JKAIR001** [comment]
我升级最新版本后也是进入不了webui，之前升级是正常的

**Comment by 757020177** [comment]
> 我升级最新版本后也是进入不了webui，之前升级是正常的


请问你升级前是什么版本 升级以后可以继续使用么？？单纯的不能见webgui么？？另外 您是纯ubuntu系统+docker吗

**Comment by 757020177** [comment]
> @JKAIR001 见 #314

谢谢你 我看一下

**Comment by allanpk716** [comment]
你日志最好从容器启动开始截取，然后到你觉得不动的地方。如果视频多，启动会有权限设置的时间，具体看项目主页的教程，里面提了如果是第二次启动可以关闭的设置。

**Comment by 757020177** [comment]
我尝试一下。。。稍后我在发这里

**Comment by 757020177** [comment]
我跟换了portainer  部署了软件 也是不能打开webgui    我的视频文件只有5个  下面是新的日志 完整的


[INFO]: 2022-06-01 14:22:27 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:27 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:27 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:27 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:27 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:27 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:27 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:27 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:27 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:27 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:27 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:27 - releaseAdblock start
[INFO]: 2022-06-01 14:22:27 - releaseAdblock end
[INFO]: 2022-06-01 14:22:27 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:27 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:27 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:27 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:27 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:27 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:27 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:27 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:27 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:27 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:27 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:27 - releaseAdblock start
[INFO]: 2022-06-01 14:22:28 - releaseAdblock end
[INFO]: 2022-06-01 14:22:28 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:28 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:28 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:28 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:28 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:28 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:28 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:28 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:28 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:28 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:28 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:28 - releaseAdblock start
[INFO]: 2022-06-01 14:22:29 - releaseAdblock end
[INFO]: 2022-06-01 14:22:29 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:29 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:29 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:29 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:29 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:29 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:29 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:29 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:29 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:29 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:29 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:29 - releaseAdblock start
[INFO]: 2022-06-01 14:22:30 - releaseAdblock end
[INFO]: 2022-06-01 14:22:30 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:30 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:30 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:30 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:30 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:30 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:30 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:30 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:30 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:30 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:30 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:30 - releaseAdblock start
[INFO]: 2022-06-01 14:22:31 - releaseAdblock end
[INFO]: 2022-06-01 14:22:31 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:31 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:31 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:31 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:31 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:32 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:32 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:32 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:32 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:32 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:32 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:32 - releaseAdblock start
[INFO]: 2022-06-01 14:22:32 - releaseAdblock end
[INFO]: 2022-06-01 14:22:32 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:32 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:32 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:32 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:32 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:32 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:32 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:32 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:32 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:32 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:32 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:32 - releaseAdblock start
[INFO]: 2022-06-01 14:22:33 - releaseAdblock end
[INFO]: 2022-06-01 14:22:33 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:33 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:33 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:33 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:33 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:33 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:33 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:33 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:33 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:33 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:33 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:33 - releaseAdblock start
[INFO]: 2022-06-01 14:22:34 - releaseAdblock end
[INFO]: 2022-06-01 14:22:34 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:34 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:34 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:34 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:34 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:34 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:34 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:34 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:34 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:34 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:34 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:34 - releaseAdblock start
[INFO]: 2022-06-01 14:22:35 - releaseAdblock end
[INFO]: 2022-06-01 14:22:35 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:35 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:35 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:35 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:35 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:36 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:36 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:36 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:36 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:36 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:36 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:36 - releaseAdblock start
[INFO]: 2022-06-01 14:22:36 - releaseAdblock end
[INFO]: 2022-06-01 14:22:36 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:36 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:36 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:36 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:36 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:36 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:36 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:36 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:36 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:36 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:36 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:36 - releaseAdblock start
[INFO]: 2022-06-01 14:22:37 - releaseAdblock end
[INFO]: 2022-06-01 14:22:37 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:37 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:37 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:37 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:37 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:38 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:38 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:38 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:38 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:38 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:38 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:38 - releaseAdblock start
[INFO]: 2022-06-01 14:22:38 - releaseAdblock end
[INFO]: 2022-06-01 14:22:38 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:38 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:38 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:38 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:38 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:38 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:38 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:38 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:38 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:38 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:38 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:38 - releaseAdblock start
[INFO]: 2022-06-01 14:22:39 - releaseAdblock end
[INFO]: 2022-06-01 14:22:39 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:39 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:39 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:39 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:39 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:40 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:40 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:40 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:40 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:40 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:40 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:40 - releaseAdblock start
[INFO]: 2022-06-01 14:22:40 - releaseAdblock end
[INFO]: 2022-06-01 14:22:40 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:40 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:40 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:40 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:40 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:40 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:40 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:40 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:40 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:40 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:40 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:40 - releaseAdblock start
[INFO]: 2022-06-01 14:22:41 - releaseAdblock end
[INFO]: 2022-06-01 14:22:41 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:22:41 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:22:41 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:22:41 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:22:41 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:41 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:22:41 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:22:41 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:22:41 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:22:41 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:22:41 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:22:41 - releaseAdblock start
[INFO]: 2022-06-01 14:22:42 - releaseAdblock end

**Comment by 757020177** [comment]
后面的日志  就是下面的这一段  重复

[INFO]: 2022-06-01 14:23:45 - ChineseSubFinder Version: v0.29-DockerBeta0
[INFO]: 2022-06-01 14:23:45 - Reload Log Settings, level = Info
[INFO]: 2022-06-01 14:23:45 - Speed Dev Mode is Off
[INFO]: 2022-06-01 14:23:45 - PreJob.HotFix() Start...
[INFO]: 2022-06-01 14:23:45 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:23:45 - PreJob.HotFix() End
[INFO]: 2022-06-01 14:23:45 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-06-01 14:23:45 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-06-01 14:23:45 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-06-01 14:23:45 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-06-01 14:23:45 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-06-01 14:23:45 - releaseAdblock start
[INFO]: 2022-06-01 14:23:45 - releaseAdblock end

**Comment by 757020177** [comment]
我不仅有chrome   我换了 360也不可以。。。。用 portainer部署就可以用   我下载beta版本  是我把所有的 版本都测试了一边   我现在不是beta版本。。。。。  我仔细观察了  portainer 部署的  env参数 和我的  docker-compose的部署参数 是一样的   但是 doker直接部署的就不行。。。

**Comment by 757020177** [comment]
我不太明白  您说的意思    chrome不是谷歌浏览器？容器我已经用的不是beta版本了。。我换了29.2也不行。。。

**Comment by 757020177** [comment]
我的已经是esxi 内部署的虚拟机 4核心4线程。。。。60g硬盘 4g内存

**Comment by 757020177** [comment]
我本别进入了两个容器内对比了一下   在/root/.cache/下面 确实  docker部署的没有  chrome  ，portainer 部署的 就有  这个有办法解决吗？

**Comment by allanpk716** [comment]
收到几个 反馈都是 chrome 无法下载或者使用导致的，这个没啥好办法。我个人的以见是，我继续推荐共享字幕的功能，然后分离出两个 csf，一个全功能的，一个 lite 版本。前者会带有 chrome也就是可以搜索 subhd 这类网站，对于想快速追剧的用户。后者则会主要依赖共享字幕功能，所以如果有人有字幕了，你就有了。但是前提是你也愿意共享你的字幕，否则应该不会考虑只下载不共享的情况。

**Comment by yilin101** [comment]
> 收到几个 反馈都是 chrome 无法下载或者使用导致的，这个没啥好办法。我个人的以见是，我继续推进共享字幕的功能，然后分离出两个 csf，一个全功能的，一个 lite 版本。前者会带有 chrome也就是可以搜索 subhd 这类网站，对于想快速追剧的用户。后者则会主要依赖共享字幕功能，所以如果有人有字幕了，你就有了。但是前提是你也愿意共享你的字幕，否则应该不会考虑只下载不共享的情况。

群晖 docker 
同样进不了webui

**Comment by allanpk716** [comment]
已经推出了 Lite 版本，具体见主页的部署教程。

**Comment by 757020177** [comment]
好的 谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chin ***@***.***&gt;; 
发送时间: 2022年7月3日(星期天) 上午10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [allanpk716/ChineseSubFinder] docker 部署  不能打开wengui (Issue #377)





 
已经推出了 Lite 版本，具体见主页的部署教程。

**Comment by 757020177** [comment]
esxi的虚拟机&nbsp; &nbsp;分了4核心&nbsp; 4g内存&nbsp; &nbsp;60g硬盘&nbsp; &nbsp;ubuntu 20.04lts



---原始邮件---
发件人: "Chin ***@***.***&gt;
发送时间: 2022年6月1日(周三) 晚上9:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [allanpk716/ChineseSubFinder] docker 部署  不能打开wengui (Issue #377)




 
docker 里面用 chrome，你部署的硬件是什么
