### ISSUE TITLE
三个月的限制能否自己开关？

### ISSUE THREAD

**Issue by fireflycao** [allanpk716/ChineseSubFinder#38]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v01.21

环境: docker in unraid

## 你想要新增或者改进什么功能？

用本软件以前电影库已经建立很久了，好多三个月前电影用别的方式下载的字幕并不完美，请问能否手动开关设置“三个月以前跳过”的设置？或者可以强制覆盖搜索？

**Comment by allanpk716** [comment]
> ## 你使用的 chinesesubfinder 是什么版本，什么环境？
> chinesesubfinder 版本: v01.21
> 
> 环境: docker in unraid
> 
> ## 你想要新增或者改进什么功能？
> 用本软件以前电影库已经建立很久了，好多三个月前电影用别的方式下载的字幕并不完美，请问能否手动开关设置“三个月以前跳过”的设置？或者可以强制覆盖搜索？

我可以理解为，需要一个功能，强制进行一次媒体库所有视频的字幕搜索吗？

**Comment by fireflycao** [comment]
就是这个意思！可能大部分人的媒体库都运行很久了，有些早期电影可能下载的都是机翻字幕。

**Comment by allanpk716** [comment]
> 就是这个意思！可能大部分人的媒体库都运行很久了，有些早期电影可能下载的都是机翻字幕。

可以做，但是没有那么快。估计会跟 Web 设置界面一起出来。保守估计到年底了吧，最近有点忙。

如果很急的话，可以简单的用 Windows 文件夹管理这样的工具，全局搜索 *.ass or *.srt 把字幕都删除了，然后再运行本程序会帮你搞定字幕下载的（这样算风险操作，慎重）。

**Comment by fireflycao** [comment]
好的，多谢！

**Comment by allanpk716** [comment]
暂时打算给个临时方案：

* 需要人工在 config 目录下新建一个特定的文件，类似 ForceFullScanAndDownloadSub 这样一个文件，内容无所谓
* 本程序重启的时候，识别这个文件，会进行一次全目录的扫描（不跳过已有的字幕的视频），然后进行字幕的下载
* 下载的字幕会覆盖原由字幕
* 删除 ForceFullScanAndDownloadSub  文件
