### ISSUE TITLE
subhd下载出现403 forbidden

### ISSUE THREAD

**Issue by zoengzihaam** [allanpk716/ChineseSubFinder#381]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.29.5
>
> 环境: docker 
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> subhd 下载字幕出现403

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> subhd 可以下载

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "user_info": {
        "username": "",
        "password": ""
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 1,
        "run_scan_at_start_up": true,
        "movie_paths": [
            "/media/movies"
        ],
        "series_paths": [
            "/media/tv"
        ]
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_http_proxy": false,
            "http_proxy_address": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 0,
        "save_multi_sub": true,
        "custom_video_exts": [],
        "fix_time_line": false,
        "topic": 1
    },
    "emby_settings": {
        "enable": true,
        "address_url": "http://192.168.5.250:8096",
        "api_key": "",
        "max_request_video_number": 3000,
        "skip_watched": true,
        "movie_paths_mapping": {
            "/media/movies": "/volume2/aria2/movies"
        },
        "series_paths_mapping": {
            "/media/tv": "/volume2/aria2/tv"
        }
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 120,
        "min_offset": 0.1
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        }
    }
}

```

## 如果是使用 Docker，请给出对应的配置信息

> docker run -d \
--name chinesesubfinder_aria2 \
--restart unless-stopped \
-e PUID=$UID \
-e PGID=$GID \
-e TZ=Asia/Shanghai \
-p 19035:19035 \
-p 19037:19037 \
-v /volume1/docker/chinesesubfinder/aria2/config:/config \
-v /volume1/docker/chinesesubfinder/aria2/cache:/app/cache \
-v /volume2/aria2:/media \
allanpk716/chinesesubfinder:v0.29.5

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

[INFO]: 2022-06-03 19:04:27 - Queue 1 DlSub Start /media/tv/The Boys (2019) [imdbid-tt1190634]
[INFO]: 2022-06-03 19:04:27 - Queue 1 IMDB ID: tt1190634 NeedDownloadSubs: 1
[INFO]: 2022-06-03 19:04:27 - Queue 1 NeedDownloadEps - S3E3
[INFO]: 2022-06-03 19:04:27 - ------------------------------------------
[INFO]: 2022-06-03 19:04:27 - Queue 1 xunlei Start...
[ERROR]: 2022-06-03 19:05:27 - xunlei NewHttpClient: /media/tv/The Boys (2019) [imdbid-tt1190634]/The Boys - S03E03 - Barbary Coast.mkv Get "http://sub.xmp.sandai.net:8000/subxl/ABEC86E9952388926974DDBA1BB6E7E04E272CFE.json": read tcp 172.17.0.2:37076->101.132.109.27:8000: read: connection reset by peer
[ERROR]: 2022-06-03 19:05:27 - xunlei getSubListFromFile 3 3 /media/tv/The Boys (2019) [imdbid-tt1190634]/The Boys - S03E03 - Barbary Coast.mkv
[INFO]: 2022-06-03 19:05:27 - Queue 1 xunlei End
[INFO]: 2022-06-03 19:05:27 - ------------------------------------------
[INFO]: 2022-06-03 19:05:27 - ------------------------------------------
[INFO]: 2022-06-03 19:05:27 - Queue 1 shooter Start...
[INFO]: 2022-06-03 19:05:28 - shooter Not Find Sub can be download The Boys 3 3
[INFO]: 2022-06-03 19:05:28 - Queue 1 shooter End
[INFO]: 2022-06-03 19:05:28 - ------------------------------------------
[INFO]: 2022-06-03 19:05:28 - ------------------------------------------
[INFO]: 2022-06-03 19:05:28 - Queue 1 subhd Start...
[INFO]: 2022-06-03 19:05:29 - [GetPublicIP] 114.221.141.112
[INFO]: 2022-06-03 19:05:29 - subhd DailyDownloadLimit: 20 Now Is: 3
[INFO]: 2022-06-03 19:05:48 - Search Keyword: 黑袍纠察队 第三季
[ERROR]: 2022-06-03 19:06:15 - subhd GetEx the.boys.s03e03.1080p.web.h264-cakes-简体中文盘子巴士 3 3 403 forbidden
[INFO]: 2022-06-03 19:06:15 - Queue 1 subhd End

**Comment by zoengzihaam** [comment]
看了以往的issue，是因为subhd 下载限制问题吗？我尝试我手动好像还能下载。

**Comment by allanpk716** [comment]
你手动调整任务优先级呢

**Comment by zoengzihaam** [comment]
> 你手动调整任务优先级呢

我是从v28升到v29.5最新 然后手动调整到第一优先级，然后发现subhd找到了 但是下载就是403 forbidden

**Comment by allanpk716** [comment]
> > 你手动调整任务优先级呢
> 
> 我是从v28升到v29.5最新 然后手动调整到第一优先级，然后发现subhd找到了 但是下载就是403 forbidden

我自己测试的情况是今天超限了，你改了程序默认一天 20 次得限制嘛?

**Comment by zoengzihaam** [comment]
> > > 你手动调整任务优先级呢
> > 
> > 
> > 我是从v28升到v29.5最新 然后手动调整到第一优先级，然后发现subhd找到了 但是下载就是403 forbidden
> 
> 我自己测试的情况是今天超限了，你改了程序默认一天 20 次得限制嘛?

没改，估计是旧版本今天给我刷完了 晚点试试改一下 然后手动再下载看看是不是这个问题

**Comment by terrellgf** [comment]
@allanpk716 
一样的问题，最大值从20-10-5-3，都不行，但是只要关上CSF，呆一天就解封了。
应该还是有什么bug
字幕库的维护者说因为咱们这类的软件，已经升级好几次服务器了，他有些怨念了，有劳作者尽快找出原因吧。辛苦！
![image](https://user-images.githubusercontent.com/54665471/173482649-f0781b65-946a-4161-ab56-49e308e2e58a.png)

**Comment by allanpk716** [comment]
不用猜了，下载超过网站自身的限制了，所以默认20肯定能用的，自己改大了，就等一天就结了。

**Comment by terrellgf** [comment]
> @allanpk716 一样的问题，最大值从20-10-5-3，都不行，但是只要关上CSF，呆一天就解封了。 应该还是有什么bug 字幕库的维护者说因为咱们这类的软件，已经升级好几次服务器了，他有些怨念了，有劳作者尽快找出原因吧。辛苦！ ![image](https://user-images.githubusercontent.com/54665471/173482649-f0781b65-946a-4161-ab56-49e308e2e58a.png)
![image](https://user-images.githubusercontent.com/54665471/173511566-0dd2c93a-9faf-450b-bc85-3caa0ed1a3f3.png)

**Comment by allanpk716** [comment]
subhd 最近更新了下载验证的细节，需要花点时间规划一下后续的字幕下载功能，所以暂时下线 subhd 的字幕下载。并且不确定重新支持的时间，同时大概率不会公开相应的代码。
