### ISSUE TITLE
太平洋战争 字幕 下载不了

### ISSUE THREAD

**Issue by ihola777** [allanpk716/ChineseSubFinder#382]
看起来找错了片名, 用imdbid能查到。
```
[INFO]: 2022-06-02 00:01:38 - subhd DailyDownloadLimit: 20 Now Is: 0
[INFO]: 2022-06-02 00:02:05 - Search Keyword: The Pacific 第一季
[ERROR]: 2022-06-02 00:02:41 - subhd GetEx Pacific.Rim.The.Black.S01.JAPANESE.1080p.WEBRip.x265-RARBGMalcolm 1 0 error value: &rod.ErrObjectNotFound{RuntimeRemoteObject:(*proto.RuntimeRemoteObject)(0xc0006c27e0)}
goroutine 24029 [running]:
```
![image](https://user-images.githubusercontent.com/38958623/171909778-e1c47ca0-d238-4a5c-8b65-619bb0aec494.png)

**Comment by allanpk716** [comment]
升级最新，搜索策略改了，借助了 IMDB 转 TMDB 获取更优的中文译名去搜索，然后才是英文搜索。

**Comment by ihola777** [comment]
> 升级最新，搜索策略改了，借助了 IMDB 转 TMDB 获取更优的中文译名去搜索，然后才是英文搜索。

当时是最新版的0.29.5，忘了写版本号。我再升级到更新的版本看看。
另外重复拉字幕问题好像也存在，没咋个仔细看，就是每天的log看到subhd剩余次数都很少，但是又没有下载新的剧集。

**Comment by allanpk716** [comment]
目前的策略，如果不是 Emby 且选择了跳过已看视频，那么就会按这个逻辑来。因为刚开始的字幕可能比较差（机翻），过几天才会真正的好一些的字幕。

https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md

**Comment by ihola777** [comment]
好的，谢谢
