### ISSUE TITLE
启动之后就卡住了

### ISSUE THREAD

**Issue by joker1489** [allanpk716/ChineseSubFinder#383]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
>
> 环境: docker or Window or Linux or MAC
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 你的问题弄重现嘛？

> 能够重新，不能够重现

## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "user_info": {
    "username": "xx", // 这里是用户名，需要替换掉
    "password": "xx" // 这里是密码，需要替换掉
  },
  "common_settings": {
    "scan_interval": "6h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": ["X:\\电影"],
    "series_paths": ["X:\\连续剧"]
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": false,
      "http_proxy_address": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://192.168.50.xxx:xxx", // 这里替换掉
    "api_key": "xxxxxxxxxxxxxx", // 这里替换掉
    "max_request_video_number": 100,
    "skip_watched": true,
    "movie_paths_mapping": {
      "X:\\电影": "/mnt/share1/电影"
    },
    "series_paths_mapping": {
      "X:\\连续剧": "/mnt/share1/连续剧"
    }
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by joker1489** [comment]
以下是log，一直这样重复

chinesesubfinder_1  |   /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x3b
chinesesubfinder_1  | created by internal/singleflight.(*Group).DoChan
chinesesubfinder_1  |   /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2f1
chinesesubfinder_1  |
chinesesubfinder_1  | goroutine 34 [select]:
chinesesubfinder_1  | net/http.(*Transport).getConn(0xc0003243c0, 0xc0002141c0, {{}, 0x0, {0xc0001e81e0, 0x5}, {0xc000424520, 0x1c}, 0x0})
chinesesubfinder_1  |   /usr/local/go/src/net/http/transport.go:1372 +0x5d2
chinesesubfinder_1  | net/http.(*Transport).roundTrip(0xc0003243c0, 0xc0004c2700)
chinesesubfinder_1  |   /usr/local/go/src/net/http/transport.go:581 +0x774
chinesesubfinder_1  | net/http.(*Transport).RoundTrip(0x30, 0x1886500)
chinesesubfinder_1  |   /usr/local/go/src/net/http/roundtrip.go:18 +0x19
chinesesubfinder_1  | net/http.send(0xc0004c2700, {0x1886500, 0xc0003243c0}, {0x1207000, 0x1, 0x0})
chinesesubfinder_1  |   /usr/local/go/src/net/http/client.go:252 +0x5d8
chinesesubfinder_1  | net/http.(*Client).send(0xc00007f7d0, 0xc0004c2700, {0xc0004c2700, 0x2f, 0x0})
chinesesubfinder_1  |   /usr/local/go/src/net/http/client.go:176 +0x9b
chinesesubfinder_1  | net/http.(*Client).do(0xc00007f7d0, 0xc0004c2700)
chinesesubfinder_1  |   /usr/local/go/src/net/http/client.go:725 +0x908
chinesesubfinder_1  | net/http.(*Client).Do(...)
chinesesubfinder_1  |   /usr/local/go/src/net/http/client.go:593
chinesesubfinder_1  | github.com/go-rod/rod/lib/launcher.(*Browser).fastestHost.func1()
chinesesubfinder_1  |   /go/pkg/mod/github.com/go-rod/rod@v0.106.8/lib/launcher/browser.go:166 +0x189
chinesesubfinder_1  | created by github.com/go-rod/rod/lib/launcher.(*Browser).fastestHost
chinesesubfinder_1  |   /go/pkg/mod/github.com/go-rod/rod@v0.106.8/lib/launcher/browser.go:154 +0x185
chinesesubfinder_1  |
chinesesubfinder_1  | goroutine 35 [select]:
chinesesubfinder_1  | net.(*Resolver).lookupIPAddr(0x2622120, {0x189d160, 0xc000214080}, {0x12339be, 0xc00007e1e0}, {0xc000424520, 0x18})
chinesesubfinder_1  |   /usr/local/go/src/net/lookup.go:302 +0x5c7
chinesesubfinder_1  | net.(*Resolver).internetAddrList(0x189d160, {0x189d160, 0xc000214080}, {0x12339be, 0x3}, {0xc000424520, 0x1c})
chinesesubfinder_1  |   /usr/local/go/src/net/ipsock.go:288 +0x67a
chinesesubfinder_1  | net.(*Resolver).resolveAddrList(0x26609e8, {0x189d160, 0xc000214080}, {0x1235290, 0x4}, {0x12339be, 0x208a0b0}, {0xc000424520, 0x1c}, {0x0, ...})
chinesesubfinder_1  |   /usr/local/go/src/net/dial.go:221 +0x41b
chinesesubfinder_1  | net.(*Dialer).DialContext(0x2623460, {0x189d160, 0xc000214080}, {0x12339be, 0xc00005fa40}, {0xc000424520, 0x118})
chinesesubfinder_1  |   /usr/local/go/src/net/dial.go:406 +0x448
chinesesubfinder_1  | net/http.(*Transport).dial(0xc00005fc30, {0x189d160, 0xc000214080}, {0x12339be, 0xc0003243c0}, {0xc000424520, 0x7f25af91f280})
chinesesubfinder_1  |   /usr/local/go/src/net/http/transport.go:1175 +0xb8
chinesesubfinder_1  | net/http.(*Transport).dialConn(0xc0003243c0, {0x189d160, 0xc000214080}, {{}, 0x0, {0xc0001e81e0, 0x5}, {0xc000424520, 0x1c}, 0x0})
chinesesubfinder_1  |   /usr/local/go/src/net/http/transport.go:1604 +0x845
chinesesubfinder_1  | net/http.(*Transport).dialConnFor(0x0, 0xc00042e840)
chinesesubfinder_1  |   /usr/local/go/src/net/http/transport.go:1446 +0xb0
chinesesubfinder_1  | created by net/http.(*Transport).queueForDial
chinesesubfinder_1  |   /usr/local/go/src/net/http/transport.go:1415 +0x3d7
chinesesubfinder_1  |
chinesesubfinder_1  | goroutine 36 [select]:
chinesesubfinder_1  | net.cgoLookupIP({0x189d160, 0xc000214200}, {0x12339be, 0x18}, {0xc000424520, 0x5d1ea5})
chinesesubfinder_1  |   /usr/local/go/src/net/cgo_unix.go:231 +0x1b7
chinesesubfinder_1  | net.(*Resolver).lookupIP(0x2622120, {0x189d160, 0xc000214200}, {0x12339be, 0x3}, {0xc000424520, 0x18})
chinesesubfinder_1  |   /usr/local/go/src/net/lookup_unix.go:97 +0x128
chinesesubfinder_1  | net.glob..func1({0x189d160, 0xc000214200}, 0xb66657, {0x12339be, 0xc000214080}, {0xc000424520, 0x6c64f0})
chinesesubfinder_1  |   /usr/local/go/src/net/hook.go:23 +0x3d
chinesesubfinder_1  | net.(*Resolver).lookupIPAddr.func1()
chinesesubfinder_1  |   /usr/local/go/src/net/lookup.go:296 +0x9f
chinesesubfinder_1  | internal/singleflight.(*Group).doCall(0x2622130, 0xc0003881e0, {0xc000424540, 0x1c}, 0xc00042e840)
chinesesubfinder_1  |   /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x3b
chinesesubfinder_1  | created by internal/singleflight.(*Group).DoChan
chinesesubfinder_1  |   /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2f1
chinesesubfinder_1  |
chinesesubfinder_1  | goroutine 37 [syscall]:
chinesesubfinder_1  | net._C2func_getaddrinfo(0xc000424a20, 0x0, 0xc0004ec5d0, 0xc000406060)
chinesesubfinder_1  |   _cgo_gotypes.go:91 +0x56 fp=0xc000048590 sp=0xc000048568 pc=0x5c8156
chinesesubfinder_1  | net.cgoLookupIPCNAME.func1({0xc000424a20, 0x0, 0x0}, 0xc000424520, 0xc000048650)
chinesesubfinder_1  |   /usr/local/go/src/net/cgo_unix.go:163 +0x9f fp=0xc0000485e8 sp=0xc000048590 pc=0x5c9e9f
chinesesubfinder_1  | net.cgoLookupIPCNAME({0x12339be, 0x3}, {0xc000424520, 0x5})
chinesesubfinder_1  |   /usr/local/go/src/net/cgo_unix.go:163 +0x16d fp=0xc000048738 sp=0xc0000485e8 pc=0x5c96ed
chinesesubfinder_1  | net.cgoIPLookup(0x2622130, {0x12339be, 0xc000424540}, {0xc000424520, 0xc00042e840})
chinesesubfinder_1  |   /usr/local/go/src/net/cgo_unix.go:220 +0x3b fp=0xc0000487a8 sp=0xc000048738 pc=0x5c9f5b
chinesesubfinder_1  | created by net.cgoLookupIP
chinesesubfinder_1  |   /usr/local/go/src/net/cgo_unix.go:230 +0x125
chinesesubfinder_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f2585f26448]
chinesesubfinder_1  |
chinesesubfinder_1  | runtime stack:
chinesesubfinder_1  | runtime.throw({0x1284305, 0x7f2588320840})
chinesesubfinder_1  |   /usr/local/go/src/runtime/panic.go:1198 +0x71
chinesesubfinder_1  | runtime.sigpanic()
chinesesubfinder_1  |   /usr/local/go/src/runtime/signal_unix.go:719 +0x396
chinesesubfinder_1  | (EE)
chinesesubfinder_1  | Fatal server error:
chinesesubfinder_1  | (EE) Server is already active for display 99
chinesesubfinder_1  |   If this server is no longer running, remove /tmp/.X99-lock
chinesesubfinder_1  |   and start again.
chinesesubfinder_1  | (EE)
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - ChineseSubFinder Version: v0.30.1
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - Reload Log Settings, level = Info
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - Speed Dev Mode is Off
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - PreJob.HotFix() Start...
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - If you have a lot of videos, it may take a lot of time, just wait...
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - Hotfix 004 Start...
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - Hotfix 004 End
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - PreJob.HotFix() End
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - PreJob.ChangeSubNameFormat() Start...
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - If you have a lot of videos, it may take a lot of time, just wait...
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - DesSubFormatter == LateTimeSubFormatter then skip process
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - PreJob.ChangeSubNameFormat() End
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - PreJob.ReloadBrowser() Start...
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:17 - releaseAdblock start
chinesesubfinder_1  | [INFO]: 2022-06-05 16:47:18 - releaseAdblock end
chinesesubfinder_1  | [launcher.Browser]2022/06/05 16:47:18 try to find the fastest host to download the browser binary
chinesesubfinder_1  | [launcher.Browser]2022/06/05 16:47:18 check https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1003583/chrome-linux.zip
chinesesubfinder_1  | [launcher.Browser]2022/06/05 16:47:18 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1003583/chrome-linux.zip
chinesesubfinder_1  | [launcher.Browser]2022/06/05 16:47:18 check https://playwright.azureedge.net/builds/chromium/1003583/chromium-linux-arm64.zip
chinesesubfinder_1  | fatal error: unexpected signal during runtime execution
chinesesubfinder_1  | fatal error: unexpected signal during runtime execution

**Comment by joker1489** [comment]
这是docker-compose.yml文件
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /home/zimu/chinesesubfinder/cache:/app/cache
      - /home/zimu/chinesesubfinder/config:/config
    
     
      - /home/Movies:/media/Movies # 举例
    ports:
      - "19035:19035"
      - "19037:19037"
    environment:
      - PUID=0000
      - PGID=0000
      - TZ=Asia/Shanghai
    restart: unless-stopped

**Comment by joker1489** [comment]
WEB UI怎么都登不上去

**Comment by joker1489** [comment]
[ChineseSubFinder.log](https://github.com/allanpk716/ChineseSubFinder/files/8839783/ChineseSubFinder.log)

**Comment by allanpk716** [comment]
大概概率你的docker允许环境不支持 chrome

**Comment by joker1489** [comment]
那怎么办？？换个浏览器。？？

Chin allan ***@***.***> 于 2022年6月5日周日 20:08写道：

**Comment by joker1489** [comment]
那升级或者降低chrome版本可行吗

**Comment by allanpk716** [comment]
已经推出了 Lite 版本，具体见主页的部署教程。
