### ISSUE TITLE
docker镜像 chrome 无法下载或者使用的解决办法

### ISSUE THREAD

**Issue by DDSRem** [allanpk716/ChineseSubFinder#386]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 0.31.0

环境: docker
## 你想要新增或者改进什么功能？
安装时出现chrome 无法下载或者使用的问题

我看到您上次对于这个问题的回答是：
收到几个 反馈都是 chrome 无法下载或者使用导致的，这个没啥好办法。我个人的以见是，我继续推进共享字幕的功能，然后分离出两个 csf，一个全功能的，一个 lite 版本。前者会带有 chrome也就是可以搜索 subhd 这类网站，对于想快速追剧的用户。后者则会主要依赖共享字幕功能，所以如果有人有字幕了，你就有了。但是前提是你也愿意共享你的字幕，否则应该不会考虑只下载不共享的情况。

我想请教一下这个问题有没有手动安装或解决的方法的方法

**Comment by DDSRem** [comment]
并且我发现我使用另一个大佬编译的镜像https://hub.docker.com/r/wloot/chinesesubfinder
https://github.com/wloot/ChineseSubFinder
是正常的
而使用您官方的镜像却会有问题
我观察过文件，发现都是一样的，并且连dockerfile文件都一样，那么按照理论您的镜像应该和wloot大佬镜像一致，但是我这边怎么样都无法使用您的镜像，而wloot大佬镜像却可以正常使用

我发现唯一的一个不同点就是wloot大佬镜像只有amd64版本，而您的镜像还有arm版本，我猜想是不是一起编译了arm版本才会出现这个问题

**Comment by DDSRem** [comment]
以上是我的推测，希望对于解决这个问题有帮助

**Comment by DDSRem** [comment]
我也编译过许多镜像，这种问题以前遇到过，就是使用buildx同时编译amd64和arm镜像时会出现bug，但是那些问题不影响使用

再次说明一下，这些仅是我的猜想，实际并不确定，我希望对于解决这个问题有帮助，因为我发现许多人都是因为这个问题而被劝退的，我希望这么好的项目可以越来越好。
如果需要，我也可以提供力所能及的帮助

**Comment by allanpk716** [comment]
你现在是使用 amd64 也不行嘛？现在应该有少部分人使用 arm 但是没得统计数据，之前取消过一段时间，后来有人反馈又加回来了。还是说我分离出多个build的配置，然后一个个触发试试？

**Comment by allanpk716** [comment]
推送了 v0.30.4 你再试试看？

**Comment by allanpk716** [comment]
see #387 无法分开编译不同架构相同 tag 推送。如果你有需要，可以更新 Beta 版本测试，就目前群里的反馈，Beta 只有 amd64 也是会有 chrome 相关的问题

**Comment by allanpk716** [comment]
推送了 v0.31-DockerBeta0 你试试

**Comment by DDSRem** [comment]
好的

**Comment by DDSRem** [comment]
我这边测试还是有问题

**Comment by DDSRem** [comment]
我这边尝试自己编译试试看

**Comment by joker1489** [comment]
> 并且我发现我使用另一个大佬编译的镜像https://hub.docker.com/r/wloot/chinesesubfinder https://github.com/wloot/ChineseSubFinder 是正常的 而使用您官方的镜像却会有问题 我观察过文件，发现都是一样的，并且连dockerfile文件都一样，那么按照理论您的镜像应该和wloot大佬镜像一致，但是我这边怎么样都无法使用您的镜像，而wloot大佬镜像却可以正常使用
> 
> 我发现唯一的一个不同点就是wloot大佬镜像只有amd64版本，而您的镜像还有arm版本，我猜想是不是一起编译了arm版本才会出现这个问题

还真是，我拉去这位大佬的镜像就可以用了

**Comment by DDSRem** [comment]
目前使用wloot大佬镜像没问题，那么也就继续用他的镜像了
我正在与wloot大佬联系，问问他是怎么编译的

**Comment by DDSRem** [comment]
我本身来讨论这个问题就是想着解决这个问题，所以wloot/chinesesubfinder镜像作者我也联系了，在等待他的回复

**Comment by allanpk716** [comment]
有 TG 群，在issueswith 置顶的讨论，共享字幕，这个下面的评论区
