### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by boer0327** [allanpk716/ChineseSubFinder#388]
最新版本又出现这个问题， 日志如下，麻烦看一下 @allanpk716 

panic: runtime error: invalid memory address or nil pointer dereference
chinesesubfinder    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa049f9]
chinesesubfinder    |
chinesesubfinder    | goroutine 162 [running]:
chinesesubfinder    | github.com/emirpasic/gods/maps/treemap.(*Map).Each(0xc0005aa150, 0xc00005cfc0)
chinesesubfinder    | 	/go/pkg/mod/github.com/emirpasic/gods@v1.12.0/maps/treemap/enumerable.go:18 +0x19
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).ScanNormalMovieAndSeries.func3()
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:207 +0xc5
chinesesubfinder    | created by github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).ScanNormalMovieAndSeries
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:200 +0x2b2
chinesesubfinder    | (EE)
chinesesubfinder    | Fatal server error:
chinesesubfinder    | (EE) Server is already active for display 99
chinesesubfinder    | 	If this server is no longer running, remove /tmp/.X99-lock
chinesesubfinder    | 	and start again.
chinesesubfinder    | (EE)

_Originally posted by @boer0327 in https://github.com/allanpk716/ChineseSubFinder/issues/11#issuecomment-1148380688_

**Comment by allanpk716** [comment]
能给出具体的 docker 版本 tag 嘛

**Comment by boer0327** [comment]
allanpk716/chinesesubfinder      latest        2e445f2fd5ba   3 hours ago    695MB

**Comment by boer0327** [comment]
我这次也是运行了几天， 刚刚看不能用了。 然后看日志是这个问题。 然后我就试着更新了最新的版本。 发现还是出现这个问题。

**Comment by allanpk716** [comment]
你需要从容器运行开始的地方看内部日志输出的版本 latest 版本不能确认拉取到的是真正最新的

**Comment by boer0327** [comment]
哦哦， 好的。 

chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - Video Scan Started...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - ScanNormalMovieAndSeries Start...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - ------------------------------------------
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - GetSeriesListFromDirs Start...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - GetSeriesListFromDirs End
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - ------------------------------------------
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 -  --------------------------------------------------
chinesesubfinder    | panic: runtime error: invalid memory address or nil pointer dereference
chinesesubfinder    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa049f9]
chinesesubfinder    |
chinesesubfinder    | goroutine 162 [running]:
chinesesubfinder    | github.com/emirpasic/gods/maps/treemap.(*Map).Each(0xc0005aa150, 0xc00005cfc0)
chinesesubfinder    | 	/go/pkg/mod/github.com/emirpasic/gods@v1.12.0/maps/treemap/enumerable.go:18 +0x19
chinesesubfinder    | github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).ScanNormalMovieAndSeries.func3()
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:207 +0xc5
chinesesubfinder    | created by github.com/allanpk716/ChineseSubFinder/internal/pkg/video_scan_and_refresh_helper.(*VideoScanAndRefreshHelper).ScanNormalMovieAndSeries
chinesesubfinder    | 	/homelab/buildspace/internal/pkg/video_scan_and_refresh_helper/video_scan_and_refresh_helper.go:200 +0x2b2
chinesesubfinder    | (EE)
chinesesubfinder    | Fatal server error:
chinesesubfinder    | (EE) Server is already active for display 99
chinesesubfinder    | 	If this server is no longer running, remove /tmp/.X99-lock
chinesesubfinder    | 	and start again.
chinesesubfinder    | (EE)
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - ChineseSubFinder Version: v0.30.5
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - Reload Log Settings, level = Debug
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - Speed Dev Mode is Off
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - PreJob.HotFix() Start...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:17 - If you have a lot of videos, it may take a lot of time, just wait...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - Hotfix 004 Start...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - Hotfix 004 End
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - PreJob.HotFix() End
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - PreJob.ChangeSubNameFormat() Start...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - If you have a lot of videos, it may take a lot of time, just wait...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - DesSubFormatter == LateTimeSubFormatter then skip process
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - PreJob.ChangeSubNameFormat() End
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - PreJob.ReloadBrowser() Start...
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - releaseAdblock start
chinesesubfinder    | [INFO]: 2022-06-07 16:44:18 - releaseAdblock end
chinesesubfinder    | [INFO]: 2022-06-07 16:44:38 - PreJob.ReloadBrowser() End
chinesesubfinder    | [INFO]: 2022-06-07 16:44:38 - PreJob.Wait() Done.
chinesesubfinder    |
chinesesubfinder    | 2022/06/07 16:44:40 /go/pkg/mod/gorm.io/driver/sqlite@v1.2.6/migrator.go:240 SLOW SQL >= 200ms
chinesesubfinder    | [344.558ms] [rows:0] CREATE INDEX `idx_daily_download_infos_deleted_at` ON `daily_download_infos`(`deleted_at`)
chinesesubfinder    | [INFO]: 2022-06-07 16:44:40 - Download.SupplierCheck() Start ...

**Comment by boer0327** [comment]
好的， 多谢多谢。

**Comment by allanpk716** [comment]
v0.30.7 等下试试这个版本

**Comment by boer0327** [comment]
好的， 我一会试一下再反馈

**Comment by boer0327** [comment]
解决了，昨天晚上跑了一晚。 到现在还在运行中。。多谢修复

**Comment by allanpk716** [comment]
程序的目标就是挂机，如果想要优先下载某一些字幕，就用 web 界面去操作吧

**Comment by boer0327** [comment]
嗯，知道， 主要是我发现的问题是每次刚刚跑着的时候是好的。不知道什么时候就出现了一个bug. 所以我的意思是我昨天晚上更新以后， 然后就没管他，早上看了一下日志确定没有问题才回消息，把issue关掉的。
