### ISSUE TITLE
v0.31-Beta3版本问题

### ISSUE THREAD

**Issue by DDSRem** [allanpk716/ChineseSubFinder#393]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
> v0.31-Beta8
> 环境: docker or Window or Linux or MAC
> docker
> 在程序运行日志头部或者 Web UI 可以看到

created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:1415 +0x3d7

goroutine 50 [select]:
net.cgoLookupIP({0x18c7080, 0xc0000a4000}, {0x125d9bb, 0x19}, {0xc000521800, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x2656120, {0x18c7080, 0xc0000a4000}, {0x125d9bb, 0x3}, {0xc000521800, 0x19})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x18c7080, 0xc0000a4000}, 0x0, {0x125d9bb, 0x0}, {0xc000521800, 0x6c6810})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x2656130, 0xc00007a0f0, {0xc0000aa1e0, 0x1d}, 0xc00052c790)
	/opt/hostedtoolcache/go/1.17.10/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.10/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f653c567ef4]

runtime stack:
runtime.throw({0x12ae2f2, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 21 [syscall]:
runtime.cgocall(0xe57960, 0xc000051590)
	/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc000051568 sp=0xc000051530 pc=0x405fdc
net._C2func_getaddrinfo(0xc000524120, 0x0, 0xc000097200, 0xc000498028)
	_cgo_gotypes.go:91 +0x56 fp=0xc000051590 sp=0xc000051568 pc=0x5c85b6
net.cgoLookupIPCNAME.func1({0xc000524120, 0x0, 0x0}, 0xc00049c060, 0xc000051650)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc0000515e8 sp=0xc000051590 pc=0x5ca2ff
net.cgoLookupIPCNAME({0x125d9bb, 0x3}, {0xc00049c060, 0x5})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc000051738 sp=0xc0000515e8 pc=0x5c9b4d
net.cgoIPLookup(0x2656130, {0x125d9bb, 0xc0005240e0}, {0xc00049c060, 0xc00012e2c0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc0000517a8 sp=0xc000051738 pc=0x5ca3bb
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc0000517e0 sp=0xc0000517a8 pc=0x5ca836
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000517e8 sp=0xc0000517e0 pc=0x46b961
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net/http.(*Transport).getConn(0xc000288000, 0xc000506000, {{}, 0x0, {0xc00007c0c0, 0x5}, {0xc00049c060, 0x1d}, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc000288000, 0xc000532000)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0x30, 0x18b03a0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc000532000, {0x18b03a0, 0xc000288000}, {0x1231000, 0x1, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000502030, 0xc000532000, {0xc000532000, 0x24, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000502030, 0xc000532000)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/client.go:593
github.com/EDDYCJY/fake-useragent/downloader.(*Download).Get(0xc0005b73f0, {0xc00007c0c0, 0x60})
	/home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/downloader/http.go:37 +0x188
github.com/EDDYCJY/fake-useragent/useragent/cache.(*raw).Get(0x1290969)
	/home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/useragent/cache/rawgithub.go:32 +0x48
github.com/allanpk716/fake-useragent.(*browser).load(0xc000459040)
	/home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:77 +0x2c6
github.com/allanpk716/fake-useragent.NewBrowser({0xc0005b75b0, 0x20c4f88, 0x12bd848}, {0x4a})
	/home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:51 +0x90
github.com/allanpk716/fake-useragent.init()
	/home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:30 +0x2f

goroutine 34 [select]:
net.(*Resolver).lookupIPAddr(0x2656120, {0x18c70f0, 0xc00009c240}, {0x125d9bb, 0xc0000a8a00}, {0xc00049c060, 0x19})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x18c70f0, {0x18c70f0, 0xc00009c240}, {0x125d9bb, 0x3}, {0xc00049c060, 0x1d})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x26949c8, {0x18c70f0, 0xc00009c240}, {0x125f28d, 0x4}, {0x125d9bb, 0x41a286}, {0xc00049c060, 0x1d}, {0x0, ...})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc000500060, {0x18c70b8, 0xc0000360a0}, {0x125d9bb, 0x7f653d79a208}, {0xc00049c060, 0x118})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0x0, {0x18c70b8, 0xc0000360a0}, {0x125d9bb, 0x0}, {0xc00049c060, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0xc000288000, {0x18c70b8, 0xc0000360a0}, {{}, 0x0, {0xc00007c0c0, 0x5}, {0xc00049c060, 0x1d}, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x0, 0xc00012e2c0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/http/transport.go:1415 +0x3d7

goroutine 20 [select]:
net.cgoLookupIP({0x18c7080, 0xc0000a4000}, {0x125d9bb, 0x19}, {0xc00049c060, 0x0})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x2656120, {0x18c7080, 0xc0000a4000}, {0x125d9bb, 0x3}, {0xc00049c060, 0x19})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x18c7080, 0xc0000a4000}, 0x0, {0x125d9bb, 0x0}, {0xc00049c060, 0x6c6810})
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.10/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x2656130, 0xc0000a8a50, {0xc0005240e0, 0x1d}, 0xc00012e2c0)
	/opt/hostedtoolcache/go/1.17.10/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.10/x64/src/internal/singleflight/singleflight.go:88 +0x2f1

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 你的问题弄重现嘛？

> 能够重新，不能够重现

## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "user_info": {
    "username": "xx", // 这里是用户名，需要替换掉
    "password": "xx" // 这里是密码，需要替换掉
  },
  "common_settings": {
    "scan_interval": "6h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": ["X:\\电影"],
    "series_paths": ["X:\\连续剧"]
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": false,
      "http_proxy_address": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://192.168.50.xxx:xxx", // 这里替换掉
    "api_key": "xxxxxxxxxxxxxx", // 这里替换掉
    "max_request_video_number": 100,
    "skip_watched": true,
    "movie_paths_mapping": {
      "X:\\电影": "/mnt/share1/电影"
    },
    "series_paths_mapping": {
      "X:\\连续剧": "/mnt/share1/连续剧"
    }
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略
version: "3"
services:
    chinesesubfinder:
        image: allanpk716/chinesesubfinder:v0.31-Beta8
        volumes:
          - /home/暂存/docker/film/chinesesubfinder/config:/config
          - /home/video2/NEW/movies:/media/movies
          - /home/video2/NEW/tv:/media/tv
          - /home/暂存/docker/film/chinesesubfinder/browser:/root/.cache/rod/browser
        environment:
          - PUID=1000         # uid
          - PGID=1000         # gid
          - PERMS=true        # 是否重设/media权限
          - TZ=Asia/Shanghai  # 时区
          - UMASK=022         # 权限掩码
        restart: always
        container_name: chinesesubfinder
        ports:
          - 19035:19035
          - 19037:19037
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
> config目录下没有logs文件

**Comment by DDSRem** [comment]
据我估计是网络问题

**Comment by allanpk716** [comment]
fake agant 需要联网从 github 拉取缓存数据，所以依然是网络问题。我考虑下把这个部分也缓存到本地使用吧。

## 截图
![image](https://user-images.githubusercontent.com/1176000/172966984-121150ad-a9e9-41f0-98aa-cf32cd39fad2.png)


![image](https://user-images.githubusercontent.com/1176000/172967045-080d462f-83ad-4240-8c3f-e6d9ce110abb.png)

**Comment by DDSRem** [comment]
我这边发现原因了，是docker-compose文件的网络设置被我删掉了，造成无法联网下载

**Comment by allanpk716** [comment]
OK，后续看有人遇到这个问题也给他们提一下你这里的解决方案
