### ISSUE TITLE
是否可以根据tmdbid进行搜索

### ISSUE THREAD

**Issue by jinfeng1985** [allanpk716/ChineseSubFinder#397]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.30.7

环境: docker

## 你想要新增或者改进什么功能？

是否可以根据tmdbid进行字幕搜索，因为发现很多电视剧在imdb中无法搜索到，如暗夜行者，金田一少年事件簿 都么有。另外，库中搜索出来的是不是还没有加入图片的功能，现在都是一块灰

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
see #390

**Comment by allanpk716** [comment]
你需要反馈具体任务的日志

**Comment by allanpk716** [comment]
以及发 tvshow.nfo 或者是一集的 nfo 文件过来，电影和连续剧的都需要反馈。我可以优化搜索逻辑

**Comment by jinfeng1985** [comment]
[INFO]: 2022-06-09 16:41:35 - updateLocalVideoCacheInfo 0 /media/movie/我们的父亲 (2022) [tmdbid=962697]/我们的父亲 (2022) [tmdbid=962697] - 1080p x264 DDP5.1.mkv
[INFO]: 2022-06-09 16:41:35 - updateLocalVideoCacheInfo 1 /media/movie/网络炼狱：揭发N号房 (2022) [tmdbid=965143]/网络炼狱：揭发N号房 (2022) [tmdbid=965143] - 1080p H265 DDP5.1.mkv
[INFO]: 2022-06-09 16:41:35 - updateLocalVideoCacheInfo 2 /media/movie/瞬息全宇宙 (2022) [tmdbid=545611]/瞬息全宇宙 (2022) [tmdbid=545611] - 2160p x265 60fps 10bit DDP5.1.mkv
[INFO]: 2022-06-09 16:41:35 - updateLocalVideoCacheInfo 3 /media/movie/神奇动物：邓布利多之谜 (2022) [tmdbid=338953]/神奇动物：邓布利多之谜 (2022) [tmdbid=338953] - 1080p H264 AAC.mkv
[INFO]: 2022-06-09 16:41:35 - updateLocalVideoCacheInfo 0 /media/tv/Love, Death & Robots (2019) [tmdbid=86831]
[INFO]: 2022-06-09 16:41:36 - updateLocalVideoCacheInfo 1 /media/tv/光环 (2022) [tmdbid=52814]
[INFO]: 2022-06-09 16:41:36 - updateLocalVideoCacheInfo 2 /media/tv/史前星球 (2022) [tmdbid=95171]
[INFO]: 2022-06-09 16:41:37 - updateLocalVideoCacheInfo 3 /media/tv/怪奇物语 (2016) [tmdbid=66732]
[INFO]: 2022-06-09 16:41:37 - updateLocalVideoCacheInfo 4 /media/tv/暗夜行者 (2022) [tmdbid=202253]
[WARNING]: 2022-06-09 16:41:37 - GetImdbInfo4SeriesDir /media/tv/暗夜行者 (2022) [tmdbid=202253] can not find IMDB Id
[ERROR]: 2022-06-09 16:41:37 - PollName: updateLocalVideoCacheInfo Index: 4 NewPoolWithFunc done with Error can not find IMDB Id
[INFO]: 2022-06-09 16:41:37 - updateLocalVideoCacheInfo 5 /media/tv/杀人者的购物目录 (2022) [tmdbid=138246]
[INFO]: 2022-06-09 16:41:37 - updateLocalVideoCacheInfo 6 /media/tv/金田一少年事件簿 (2022) [tmdbid=194852]
[WARNING]: 2022-06-09 16:41:37 - GetImdbInfo4SeriesDir /media/tv/金田一少年事件簿 (2022) [tmdbid=194852] can not find IMDB Id
[ERROR]: 2022-06-09 16:41:37 - PollName: updateLocalVideoCacheInfo Index: 6 NewPoolWithFunc done with Error can not find IMDB Id
[INFO]: 2022-06-09 16:41:37 - ScanNormalMovieAndSeries End
[INFO]: 2022-06-09 16:41:37 - ScanEmbyMovieAndSeries Start...
[INFO]: 2022-06-09 16:41:37 - EmbyHelper == nil
[INFO]: 2022-06-09 16:41:37 - ScanEmbyMovieAndSeries End #

**Comment by jinfeng1985** [comment]
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<tvshow>
  <plot>小男孩突然失踪，神秘疑云笼罩小镇：秘密的实验，可怕的超自然力量，奇怪的小女孩，背后的真相到底是什么？</plot>
  <outline>小男孩突然失踪，神秘疑云笼罩小镇：秘密的实验，可怕的超自然力量，奇怪的小女孩，背后的真相到底是什么？</outline>
  <lockdata>false</lockdata>
  <dateadded>2022-05-31 10:03:00</dateadded>
  <title>怪奇物语</title>
  <originaltitle>Stranger Things</originaltitle>
  <rating>8.6</rating>
  <year>2016</year>
  <mpaa>TV-14</mpaa>
  <imdb_id>tt4574334</imdb_id>
  <tmdbid>66732</tmdbid>
  <premiered>2016-07-15</premiered>
  <releasedate>2016-07-15</releasedate>
  <runtime>50</runtime>
  <genre>Sci-Fi &amp; Fantasy</genre>
  <genre>剧情</genre>
  <genre>悬疑</genre>
  <studio>Netflix</studio>
  <tag>friendship</tag>
  <tag>small town</tag>
  <tag>sheriff</tag>
  <tag>monster</tag>
  <tag>experiment</tag>
  <tag>supernatural</tag>
  <tag>forest</tag>
  <tag>telekinesis</tag>
  <tag>horror</tag>
  <tag>role playing</tag>
  <tag>psychological thriller</tag>
  <tag>parallel world</tag>
  <tag>missing person</tag>
  <tag>missing child</tag>
  <tag>government conspiracy</tag>
  <tag>1980s</tag>
  <tag>mk ultra</tag>
  <tag>speculative fiction</tag>
  <tag>teenager</tag>
  <tvrageid>48493</tvrageid>
  <tvdbid>305288</tvdbid>
  <art>
    <poster>/video/info/tv/怪奇物语 (2016) [tmdbid=66732]/folder.jpg</poster>
    <fanart>/video/info/tv/怪奇物语 (2016) [tmdbid=66732]/backdrop2.jpg</fanart>
  </art>
  <actor>
    <name>Millie Bobby Brown</name>
    <role>Eleven</role>
    <type>Actor</type>
    <sortorder>0</sortorder>
    <thumb>/config/metadata/People/M/Millie Bobby Brown/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Finn Wolfhard</name>
    <role>Mike Wheeler</role>
    <type>Actor</type>
    <sortorder>1</sortorder>
    <thumb>/config/metadata/People/F/Finn Wolfhard/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Caleb McLaughlin</name>
    <role>Lucas Sinclair</role>
    <type>Actor</type>
    <sortorder>2</sortorder>
    <thumb>/config/metadata/People/C/Caleb McLaughlin/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Gaten Matarazzo</name>

**Comment by jinfeng1985** [comment]
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<tvshow>
  <plot>2022年四月NTV日曜剧《金田一少年事件簿》改编天树征丸连载30年的漫画作品，由道枝骏佑出演天才高中生探侦的名义金田一一，描述在因缘巧合转学到许久不见的青梅竹马七瀬美雪所就读的高中，开始和警方合作解开悬案的故事。由上白石萌歌出演金田一一（道枝骏佑）的青梅竹马七瀬美雪，泽村一树饰演警视厅搜查一课的剑持警部。</plot>
  <outline>2022年四月NTV日曜剧《金田一少年事件簿》改编天树征丸连载30年的漫画作品，由道枝骏佑出演天才高中生探侦的名义金田一一，描述在因缘巧合转学到许久不见的青梅竹马七瀬美雪所就读的高中，开始和警方合作解开悬案的故事。由上白石萌歌出演金田一一（道枝骏佑）的青梅竹马七瀬美雪，泽村一树饰演警视厅搜查一课的剑持警部。</outline>
  <lockdata>false</lockdata>
  <dateadded>2022-06-07 23:16:01</dateadded>
  <title>金田一少年事件簿</title>
  <originaltitle>金田一少年の事件簿</originaltitle>
  <director>Hisashi Kimura</director>
  <director>Syunpei Maruya</director>
  <writer>Yuuko Kawabe</writer>
  <writer>Tetsuya Oishi</writer>
  <writer>Shin Kibayashi</writer>
  <writer>Yozaburo Kanari</writer>
  <writer>Fumiya Sato</writer>
  <credits>Yuuko Kawabe</credits>
  <credits>Tetsuya Oishi</credits>
  <credits>Shin Kibayashi</credits>
  <credits>Yozaburo Kanari</credits>
  <credits>Fumiya Sato</credits>
  <rating>0</rating>
  <year>2022</year>
  <tmdbid>194852</tmdbid>
  <premiered>2022-04-24</premiered>
  <releasedate>2022-04-24</releasedate>
  <runtime>60</runtime>
  <genre>剧情</genre>
  <genre>悬疑</genre>
  <studio>Nippon TV</studio>
  <studio>Hulu</studio>
  <studio>Disney+</studio>
  <art>
    <poster>/video/info/tv/金田一少年事件簿 (2022) [tmdbid=194852]/folder.jpg</poster>
    <fanart>/video/info/tv/金田一少年事件簿 (2022) [tmdbid=194852]/backdrop2.jpg</fanart>
  </art>
  <actor>
    <name>Shunsuke Michieda</name>
    <type>Actor</type>
    <sortorder>500</sortorder>
    <thumb>/config/metadata/People/S/Shunsuke Michieda/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Moka Kamishiraishi</name>
    <type>Actor</type>
    <sortorder>500</sortorder>
    <thumb>/config/metadata/People/M/Moka Kamishiraishi/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Ikki Sawamura</name>
    <type>Actor</type>
    <sortorder>500</sortorder>
    <thumb>/config/metadata/People/I/Ikki Sawamura/folder.jpg</thumb>
  </actor>
  <actor>
    <name>Iwasaki Taisho</name>
    <type>Actor</type>

**Comment by allanpk716** [comment]
你可以把 nfo 文件打包发上来，复制不行。

**Comment by jinfeng1985** [comment]
请问打包后怎么上传压缩包的？没找到上传文件地方

**Comment by jinfeng1985** [comment]
[归档.zip](https://github.com/allanpk716/ChineseSubFinder/files/8870122/default.zip)

**Comment by jinfeng1985** [comment]
请问是不是有问题呀？

**Comment by allanpk716** [comment]
升级最新
