### ISSUE TITLE
对于 Plex 的字幕命名支持

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#40]
> > 能否加上对于Plex的支持，比如下载后的字母自动变更为Movies.zh.ass之类的文件名，plex只根据文件名来识别字幕的语言，Movies.en.ass就是英文字幕。
> 

类似这样。

![image](https://user-images.githubusercontent.com/42395/128674365-51cfe423-9f77-41ee-95ff-2051ea3cca41.png)

参考URL：
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/

_Originally posted by @ibeyond in https://github.com/allanpk716/ChineseSubFinder/issues/20#issuecomment-895019822_

**Comment by minghsinlee** [comment]
+1,plex目前无法正确显示语言，因为emby和plex的字幕命名规则不同，只会显示成unknown，建议可以自定义规则或者适配，plex的命名规则为 $文件名.chi.srt或ass

**Comment by allanpk716** [comment]
> +1,plex目前无法正确显示语言，因为emby和plex的字幕命名规则不同，只会显示成unknown，建议可以自定义规则或者适配，plex的命名规则为 $文件名.chi.srt或ass

嗯，因为有了其他媒体软件识别字幕命名的需求，所以需要重构这个部分，然后才能给出自定义命名格式设置。还好 plex 的格式并不麻烦，简单改改能用是可以做到的。这周吧，应该可以发布更新。

**Comment by ibeyond** [comment]
我fork后搞了一版，没写过golang照猫画虎修改了一点。
https://github.com/ibeyond/ChineseSubFinder/
似乎能工作，不过还是等你的正式版。

**Comment by allanpk716** [comment]
> 我fork后搞了一版，没写过golang照猫画虎修改了一点。
> https://github.com/ibeyond/ChineseSubFinder/
> 似乎能工作，不过还是等你的正式版。
> PS:
> 程序似乎可以正常在mac下运行，至少我在vscode里运行是没有啥问题，也能够调试。

能临时用就最好，因为个人项目写的比较随意，怕你们改的时候，很可能有隐藏的修改点不容易覆盖到，怕出问题 :sweat_smile:

没到正式版本发布···很可能都会有大调整···

**Comment by allanpk716** [comment]
v0.14.x 支持，见字幕格式命名文档
