### ISSUE TITLE
无法找到视频，但是日志中显示能够识别

### ISSUE THREAD

**Issue by edhnt455** [allanpk716/ChineseSubFinder#401]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.30.7
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> webui界面不显示视频，也无法下载字幕，但是日志中显示能够识别

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 能够解决该问题

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```{
    "SpeedDevMode":false,
    "user_info":{
        "username":,
        "password":
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":3,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/movie"
        ],
        "series_paths":[
            "/media/tv"
        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "enabled":false,
            "token":""
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"http",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"10809",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org",
                "daily_download_limit":20
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "daily_download_limit":-1
            },
            "a4k":{
                "name":"a4k",
                "root_url":"https://www.a4k.net",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":true,
            "skip_chinese_series":true
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":true,
        "address_url":"",
        "api_key":"",
        "max_request_video_number":3000,
        "skip_watched":true,
        "movie_paths_mapping":{
            "/media/movie":""
        },
        "series_paths_mapping":{
            "/media/tv":""
        },
        "auto_or_manual":true,
        "threads":3
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":120,
        "min_offset":0.1
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":true,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        },
        "share_sub_settings":{
            "share_sub_enabled":false
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 
![Snipaste_2022-06-10_15-53-37](https://user-images.githubusercontent.com/59108157/173170032-32ef18e5-8d91-4da6-8d9d-59630d4cdfe6.png)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> [INFO]: 2022-06-11 10:49:52 - ------------------------------------
[INFO]: 2022-06-11 10:49:52 - Video Scan Started By webui...
[INFO]: 2022-06-11 10:49:52 - ScanNormalMovieAndSeries Start...
[INFO]: 2022-06-11 10:49:52 - Forced Scan And DownSub
[INFO]: 2022-06-11 10:49:52 - ------------------------------------------
[INFO]: 2022-06-11 10:49:52 - GetSeriesListFromDirs Start...
[INFO]: 2022-06-11 10:49:52 -  --------------------------------------------------
[INFO]: 2022-06-11 10:49:52 - SearchMatchedVideoFileFromDirs Start...
[INFO]: 2022-06-11 10:49:52 - GetSeriesListFromDirs End
[INFO]: 2022-06-11 10:49:52 - ------------------------------------------
[INFO]: 2022-06-11 10:49:52 - SearchMatchedVideoFileFromDirs End
[INFO]: 2022-06-11 10:49:52 -  --------------------------------------------------
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 0 /media/movie/冒牌天神2 (2007)/冒牌天神2 (2007) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 1 /media/movie/冒牌天神 (2003)/冒牌天神 (2003) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 3 /media/movie/星际穿越 (2014)/星际穿越 (2014) - 2160p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 4 /media/movie/死亡诗社 (1989)/死亡诗社 (1989) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 5 /media/movie/肖申克的救赎 (1994)/肖申克的救赎 (1994) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 6 /media/movie/超脱 (2011)/超脱 (2011) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 7 /media/movie/我不是药神 (2018)/我不是药神 (2018) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 8 /media/movie/了不起的盖茨比 (2013)/了不起的盖茨比 (2013) - 2160p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 9 /media/movie/泰坦尼克号 (1997)/泰坦尼克号 (1997) - 2160p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 2 /media/movie/追梦赤子心 (1993)/追梦赤子心 (1993) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 10 /media/movie/罗密欧与朱丽叶 (1996)/罗密欧与朱丽叶 (1996) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 11 /media/movie/大上海 (2012)/大上海 (2012) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 12 /media/movie/B级文件 (2022)/B级文件 (2022) - 1080p.mp4
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 13 /media/movie/霍比特人：意外之旅 (2012)/霍比特人：意外之旅 (2012).mp4
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 14 /media/movie/神奇动物：邓布利多之谜 (2022)/神奇动物：邓布利多之谜 (2022) - 2160p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 15 /media/movie/大象席地而坐 (2018)/大象席地而坐 (2018) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 16 /media/movie/成为简·奥斯汀 (2007)/成为简·奥斯汀 (2007) - 1080p.mkv
[WARNING]: 2022-06-11 10:49:52 - GetImdbInfo4Movie 12 can not find IMDB Id
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 17 /media/movie/崖上的波妞 (2008)/崖上的波妞 (2008) - 1080p.mkv
[ERROR]: 2022-06-11 10:49:52 - PollName: updateLocalVideoCacheInfo Index: 12 NewPoolWithFunc done with Error can not find IMDB Id
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 18 /media/movie/教父3 (1990)/教父3 (1990)-Part - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 19 /media/movie/教父2 (1974)/教父2 (1974)-Part - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 21 /media/movie/霸王别姬 (1993)/霸王别姬 (1993) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 20 /media/movie/教父 (1972)/教父 (1972) - 1080p.mkv
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 1 /media/tv/进击的巨人 (2013)
[INFO]: 2022-06-11 10:49:52 - updateLocalVideoCacheInfo 0 /media/tv/天蝎 (2014)
[INFO]: 2022-06-11 10:49:52 - ScanNormalMovieAndSeries End
[INFO]: 2022-06-11 10:49:52 - ScanEmbyMovieAndSeries Start...
[INFO]: 2022-06-11 10:49:52 - Forced Scan And DownSub, tmpSetting.EmbySettings.MaxRequestVideoNumber = 1000000
[INFO]: 2022-06-11 10:49:52 - Movie Sub Dl From Emby API...
[INFO]: 2022-06-11 10:49:52 - Refresh Emby Sub List Start...
[ERROR]: 2022-06-11 10:49:52 - Refresh Emby Sub List Error
[ERROR]: 2022-06-11 10:49:52 - refreshEmbySubList Get "//%2F192.168.50.2%2Femby%2FItems%3FFilters=IsNotFolder&IncludeItemTypes=Episode%252CMovie&IsUnaired=false&Limit=1000000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=cde21029bc6f4ca08b8a89a46043dca8/192.168.50.2/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=1000000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=cde21029bc6f4ca08b8a89a46043dca8": unsupported protocol scheme ""
[INFO]: 2022-06-11 10:49:52 - ScanEmbyMovieAndSeries End
[ERROR]: 2022-06-11 10:49:52 - ScanEmbyMovieAndSeries Get "//%2F192.168.50.2%2Femby%2FItems%3FFilters=IsNotFolder&IncludeItemTypes=Episode%252CMovie&IsUnaired=false&Limit=1000000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=cde21029bc6f4ca08b8a89a46043dca8/192.168.50.2/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=1000000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=cde21029bc6f4ca08b8a89a46043dca8": unsupported protocol scheme ""
[INFO]: 2022-06-11 10:49:52 - Video Scan End By webui
[INFO]: 2022-06-11 10:49:52 - ------------------------------------

**Comment by edhnt455** [comment]
![image](https://user-images.githubusercontent.com/59108157/173170165-a20fc6a4-e02c-4b98-b385-828f4409452e.png)

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/173170199-58fa86b0-f99d-43d6-abb4-cae6430b5f82.png)


你需要看你的 docker 配置

**Comment by edhnt455** [comment]
我用的是群晖6.2的docker套件部署
![image](https://user-images.githubusercontent.com/59108157/173172006-b79ee61c-ddfc-420b-a120-3bb0054797c3.png)
![image](https://user-images.githubusercontent.com/59108157/173172009-8b905a0c-4273-4e89-a1ee-91eaa1cbad1b.png)
![image](https://user-images.githubusercontent.com/59108157/173172013-94d86483-492d-4f43-ba7a-3a8a098a87cf.png)
![image](https://user-images.githubusercontent.com/59108157/173172020-2afc305b-9c8b-44ed-87cd-447ae9752f5e.png)

**Comment by edhnt455** [comment]
Emby用的套件版

**Comment by edhnt455** [comment]
这是CSF的设置
![image](https://user-images.githubusercontent.com/59108157/173172140-6adc4d8a-bcd9-4fec-8e34-8000e21fbdee.png)
![image](https://user-images.githubusercontent.com/59108157/173172150-43f3924f-42fd-415d-84d4-f77d90c4920e.png)
![image](https://user-images.githubusercontent.com/59108157/173172155-5c4e048a-be72-4821-879c-99e78f8446a0.png)
![image](https://user-images.githubusercontent.com/59108157/173172161-036c96ee-f98b-4519-a962-304337edf208.png)
![image](https://user-images.githubusercontent.com/59108157/173172169-ba9007f1-724f-46fc-bafe-49fb5bf7bbde.png)
![image](https://user-images.githubusercontent.com/59108157/173172173-ef564cc9-024b-49a8-a6e4-e21c1d76a6aa.png)
![image](https://user-images.githubusercontent.com/59108157/173172185-131284d4-cc4e-4a2f-82cc-65baa2a4234f.png)

**Comment by allanpk716** [comment]
![image](https://user-images.githubusercontent.com/1176000/173181746-cfa41a76-f646-4f3f-a7a6-36004e639404.png)

http://

**Comment by edhnt455** [comment]
webui里还是没有，这是最新的log
[INFO]: 2022-06-11 17:25:11 - ------------------------------------
[INFO]: 2022-06-11 17:25:11 - Video Scan Started By webui...
[INFO]: 2022-06-11 17:25:11 - ScanNormalMovieAndSeries Start...
[INFO]: 2022-06-11 17:25:11 - Forced Scan And DownSub
[INFO]: 2022-06-11 17:25:11 - ------------------------------------------
[INFO]: 2022-06-11 17:25:11 - GetSeriesListFromDirs Start...
[INFO]: 2022-06-11 17:25:11 -  --------------------------------------------------
[INFO]: 2022-06-11 17:25:11 - SearchMatchedVideoFileFromDirs Start...
[INFO]: 2022-06-11 17:25:11 - GetSeriesListFromDirs End
[INFO]: 2022-06-11 17:25:11 - ------------------------------------------
[INFO]: 2022-06-11 17:25:11 - SearchMatchedVideoFileFromDirs End
[INFO]: 2022-06-11 17:25:11 -  --------------------------------------------------
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 0 /media/movie/冒牌天神2 (2007)/冒牌天神2 (2007) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 1 /media/movie/冒牌天神 (2003)/冒牌天神 (2003) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 3 /media/movie/星际穿越 (2014)/星际穿越 (2014) - 2160p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 4 /media/movie/死亡诗社 (1989)/死亡诗社 (1989) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 5 /media/movie/肖申克的救赎 (1994)/肖申克的救赎 (1994) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 6 /media/movie/超脱 (2011)/超脱 (2011) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 7 /media/movie/我不是药神 (2018)/我不是药神 (2018) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 2 /media/movie/追梦赤子心 (1993)/追梦赤子心 (1993) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 8 /media/movie/了不起的盖茨比 (2013)/了不起的盖茨比 (2013) - 2160p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 9 /media/movie/泰坦尼克号 (1997)/泰坦尼克号 (1997) - 2160p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 10 /media/movie/罗密欧与朱丽叶 (1996)/罗密欧与朱丽叶 (1996) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 11 /media/movie/大上海 (2012)/大上海 (2012) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 12 /media/movie/B级文件 (2022)/B级文件 (2022) - 1080p.mp4
[WARNING]: 2022-06-11 17:25:11 - GetImdbInfo4Movie 12 can not find IMDB Id
[ERROR]: 2022-06-11 17:25:11 - PollName: updateLocalVideoCacheInfo Index: 12 NewPoolWithFunc done with Error can not find IMDB Id
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 13 /media/movie/霍比特人：意外之旅 (2012)/霍比特人：意外之旅 (2012).mp4
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 14 /media/movie/神奇动物：邓布利多之谜 (2022)/神奇动物：邓布利多之谜 (2022) - 2160p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 16 /media/movie/成为简·奥斯汀 (2007)/成为简·奥斯汀 (2007) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 15 /media/movie/大象席地而坐 (2018)/大象席地而坐 (2018) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 17 /media/movie/崖上的波妞 (2008)/崖上的波妞 (2008) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 18 /media/movie/教父3 (1990)/教父3 (1990)-Part - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 19 /media/movie/教父2 (1974)/教父2 (1974)-Part - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 21 /media/movie/霸王别姬 (1993)/霸王别姬 (1993) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 20 /media/movie/教父 (1972)/教父 (1972) - 1080p.mkv
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 1 /media/tv/进击的巨人 (2013)
[INFO]: 2022-06-11 17:25:11 - updateLocalVideoCacheInfo 0 /media/tv/天蝎 (2014)
[INFO]: 2022-06-11 17:25:11 - ScanNormalMovieAndSeries End
[INFO]: 2022-06-11 17:25:11 - ScanEmbyMovieAndSeries Start...
[INFO]: 2022-06-11 17:25:11 - Forced Scan And DownSub, tmpSetting.EmbySettings.MaxRequestVideoNumber = 1000000
[INFO]: 2022-06-11 17:25:11 - Movie Sub Dl From Emby API...
[INFO]: 2022-06-11 17:25:11 - Refresh Emby Sub List Start...
[INFO]: 2022-06-11 17:25:11 - Refresh Emby Sub List Success
[INFO]: 2022-06-11 17:25:11 - getUpdateVideoListFromEmby Start...
[INFO]: 2022-06-11 17:25:11 - getUpdateVideoListFromEmby End
[INFO]: 2022-06-11 17:25:11 - ScanEmbyMovieAndSeries End
[INFO]: 2022-06-11 17:25:11 - Video Scan End By webui
[INFO]: 2022-06-11 17:25:11 - ------------------------------------

**Comment by houskii** [comment]
我在#400碰到了和你一样的bug一样的日志

**Comment by qinxianyuzou** [comment]
重新设置了正确的emby地址之后，重启字幕容器

**Comment by edhnt455** [comment]
还是一样的问题

**Comment by edhnt455** [comment]
找到问题了，我的emby密钥有问题，貌似只能生效一个？使用它最开始的密钥就行了。
