### ISSUE TITLE
判断是否需要下载字幕时，能否判断是否已经内置中文字幕

### ISSUE THREAD

**Issue by yang0026** [allanpk716/ChineseSubFinder#405]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.31.2
环境: 群晖 Docker

## 你想要新增或者改进什么功能？

判断是否需要下载字幕时，能否判断是否已经内置中文字幕

**Comment by allanpk716** [comment]
有内置字幕且7天内都搜索不到会跳过
