### ISSUE TITLE
## 目录结构问题

### ISSUE THREAD

**Issue by ShangWangNUST** [allanpk716/ChineseSubFinder#41]
## 目录结构问题
作者你好，请问一下，例如我在emby里设置的挂载目录是/mnt/video，/mnt/tvshow，我想知道，卷映射中可否这样写，- /volume1/video:/mnt，也就是为了所谓一致性（虽然并没有什么用，有点强迫症～～），将media改为mnt，或者是emby中将mnt改为media

**Comment by allanpk716** [comment]
至少在这个版本是不会改动这个设置了，会导致不少人的配置出问题。你提这个可能会在 Web 设置界面出来后，类似 sonarr 的导入媒体目录方式来设置。

**Comment by ShangWangNUST** [comment]
好的，谢谢
