### ISSUE TITLE
主页的进度UI没了

### ISSUE THREAD

**Issue by paysenyu** [allanpk716/ChineseSubFinder#413]
![image](https://user-images.githubusercontent.com/51367628/174431351-5d8920fb-bab2-4088-97df-2fdf10a1a3e8.png)

之前在这一块位置有两个圈,会显示字幕下载进度等 .  从上个月不知道什么版本更新之后就没了, 

请问是我这边的问题还是去掉这个显示了.

**Comment by paysenyu** [comment]
另外一个问题就是 docker pull 的latest 永远不是最新的..必须每次更新都要去 yml 里面改一下版本号

然后重新推..

**Comment by devome** [comment]
使用了docker国内加速镜像，就会造成这个难拉到最新的镜像的问题。

**Comment by paysenyu** [comment]
请问群晖可以关闭这个加速吗？> 使用了docker国内加速镜像，就会造成这个难拉到最新的镜像的问题。

**Comment by binsir1** [comment]
同样的问题，进度条消失了。。。。

**Comment by allanpk716** [comment]
去掉进度条的原因是，扫描和下载分离，已经变成对接的任务机制。还是之前提到的，这个程序目标是挂机，而不是交互。需要交互给了简单的视频列表可以手动调整任务。
