### ISSUE TITLE
 无法使用，扫不到媒体文件

### ISSUE THREAD

**Issue by china31** [allanpk716/ChineseSubFinder#417]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.33.0
>
> 环境: docker/Jellyfin
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> **扫面不到电影及电视剧目录。必须按照你的/media/电影，/media/连续剧吗？你的教程写的非常模糊，这个路径是docker路径还是实际片源路径？如果我的路径不是你的电影，连续剧就无法使用吗？   -v /srv/sdb1/media:/media \ #映射的路径，不懂为何路径规则又是“/media/电影”，我media文件夹下没有再次创建media文件夹啊？你的这个路径规则是何意呢？如此设置岂不是成了/srv/sdb1/media/media/电影？直接写入“/电影”又提示目录不存在**

## 你的问题弄重现嘛？

> 能够重新，不能够重现

## 你期望的结果

> 描述以下你期望的结果

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "user_info": {
    "username": "xx", // 这里是用户名，需要替换掉
    "password": "xx" // 这里是密码，需要替换掉
  },
  "common_settings": {
    "scan_interval": "6h",
    "threads": 1,
    "run_scan_at_start_up": false,
    "movie_paths": ["X:\\电影"],
    "series_paths": ["X:\\连续剧"]
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_http_proxy": false,
      "http_proxy_address": ""
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 0,
    "save_multi_sub": true,
    "custom_video_exts": [],
    "fix_time_line": false,
    "topic": 1
  },
  "emby_settings": {
    "enable": true,
    "address_url": "http://192.168.50.xxx:xxx", // 这里替换掉
    "api_key": "xxxxxxxxxxxxxx", // 这里替换掉
    "max_request_video_number": 100,
    "skip_watched": true,
    "movie_paths_mapping": {
      "X:\\电影": "/mnt/share1/电影"
    },
    "series_paths_mapping": {
      "X:\\连续剧": "/mnt/share1/连续剧"
    }
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> openmediavault 6.0.28-3/Docker 5:20.10.17~3-0

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

**Comment by china31** [comment]
-v /srv/sdb1/media:/media \   #映射的路径，不懂为何路径规则又是“/media/电影”，我media文件夹下没有再次创建media文件夹啊？你的这个路径规则是何意呢？

**Comment by allanpk716** [comment]
主页的几个教程都看不懂？那你应该去看 docker 的教程

![image](https://user-images.githubusercontent.com/1176000/174548991-6791d4c7-7c3a-4ef3-b960-29914d591a76.png)

**Comment by china31** [comment]
> 主页的几个教程都看不懂？那你应该去看 docker 的教程
> 
> ![image](https://user-images.githubusercontent.com/1176000/174548991-6791d4c7-7c3a-4ef3-b960-29914d591a76.png)

教程看了很多变，最主要你这个教程看的我真的糊里糊涂的。

**Comment by allanpk716** [comment]
几个教程的目录映射都是一脉相承，都是向后兼容的。如果你对这一块不清，那么还是去看 docker 的教程。我只能假设你们有基础的 docker 使用经验。

**Comment by avsba001** [comment]
教程已经很明白了，emby映射路径都已经自动识别了，现在只要弄明白映射路径是啥，填进去就行了，Docker基础

**Comment by scientificCommunity** [comment]
目录符合文档描述(sonar+jellyfin)，tvshow.nfo文件也有，不过什么东西也扫不出来。看日志倒是扫到了剧集，不过没有做任何工作

**Comment by allanpk716** [comment]
该反馈的信息都没有写，猜不出来，先关闭了。
