### ISSUE TITLE
https://raw.githubusercontents.com/allanpk716/。。。根据我们的服务条款，您的访问请求被服务器拒绝，请点击此页面查看被拒绝的原因。

### ISSUE THREAD

**Issue by touchstoness** [allanpk716/ChineseSubFinder#418]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.33.1
>
> 环境: unraid docker  

https://raw.githubusercontents.com/allanpk716/SomeThingsStatic/master/2022622c31ViaG5Q.txt
站长封了该服务
“根据我们的服务条款，您的访问请求被服务器拒绝，请点击[此页面](https://github.com/7ednet/yard/discussions/5)查看被拒绝的原因。”

**Comment by allanpk716** [comment]
谢谢反馈。新版本我会移除这个服务。不会影响后续的使用。

**Comment by touchstoness** [comment]
这个工具做的非常好。加油加油！   现在还有一些小的不稳定，但慢慢应该都会修正。比如电视，电影的缓存，经常加载不出来，是空的。

**Comment by allanpk716** [comment]
> 这个工具做的非常好。加油加油！ 现在还有一些小的不稳定，但慢慢应该都会修正。比如电视，电影的缓存，经常加载不出来，是空的。

这个功能是临时加的，会在后续一个比较重要的功能中重写，应该会在未来几个月由更大的更新。也许需要更多人的参与和使用后续才会更加好用的。
