### ISSUE TITLE
字幕源下载次数限制不能设置为0

### ISSUE THREAD

**Issue by millsguo** [allanpk716/ChineseSubFinder#419]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.33.4
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 字幕源下载次数限制不能为0，但需要设置成0才可以禁用字幕源

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 禁用字幕源
![不能设置为0](https://user-images.githubusercontent.com/2242891/175091137-c5e5294f-558b-41e9-bbe6-99bfe3bb2768.png)

**Comment by iMyon** [comment]
之前没考虑禁用逻辑，下个发布版本会修复这个问题

**Comment by millsguo** [comment]
收到，谢谢
