### ISSUE TITLE
对io受限设备的优化

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#427]
对于一些io受限的设备, 或者使用rclone挂载云盘, 读取文件的操作往往会很慢, 可能低至1秒1次左右. 而程序会在运行的时候大量重复读取文件(nfo, 视频, 字幕文件等等), 比如在开始尝试将视频加入队列, 生成视频文件id的过程, 每个视频就会多次读取, 导致在我的环境上每次加入队列阶段就会有几个小时. 

能否尝试减少媒体文件夹内的文件读取次数, 可能可以利用数据库缓存. 对于一些io操作(比如视频文件id生成), 可能可以做一个选项, 来使用不消耗io, 但次优的替代算法?

**Comment by allanpk716** [comment]
1. 重复读取是 24 小时一次，原因是假定媒体库库目录可能有大范围的变动。
2. 为了写的方便，信息的读取没有做缓存，因为有多个流程可能是并行的，缓存过期时机不好选择。
3. 视频 ID 读取我记得是抽取十几KB的数据来计算的。
4. 某些流程下，判断字幕的时候需要大量读写完整的字幕。


对于你提到这类型的设备，后续应该会提供额外的策略：
1. 需要手动执行，第一次的待下载字幕队列扫描新建
2. 关闭定时扫描
3. 需要使用者自行对接媒体服务器使用 http api 去添加新增的媒体文件，[对外的 http api](https://github.com/allanpk716/ChineseSubFinder/tree/docs/DesignFile/ApiKey%E8%AE%BE%E8%AE%A1),以及[示例](https://github.com/allanpk716/ChineseSubFinder/issues/336)
