### ISSUE TITLE
搜索每一套電影都遇到error訊息

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#43]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: lastest

环境: synology ds218+ 的docker套件

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/66216186/131229047-9cd58ac6-a6ee-4fd8-b55f-a39cf10965e3.png)
搜尋每一套電影都出現error 想請問這是正常的嗎?

**Comment by xiNeRoar** [comment]
下面是我的config配置
```
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 3h
Threads: 4
SubTypePriority: 1
DebugMode: false
SaveMultiSub: false
MovieFolder: /media/Movies
SeriesFolder: /media/TV Shows
```

**Comment by allanpk716** [comment]
> 下面是我的config配置
> 
> ```
> UseProxy: false
> HttpProxy: http://127.0.0.1:10809
> EveryTime: 3h
> Threads: 4
> SubTypePriority: 1
> DebugMode: false
> SaveMultiSub: false
> MovieFolder: /media/Movies
> SeriesFolder: /media/TV Shows
> ```

这个故障主要还是现在 subhd 的搜索限制比较严格，建议并发量降低到 1 。
`Threads: 1`

如果你使用的媒体服务器软件是 Emby，建议看看 [高阶设置 - Emby API 支持](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md)
这样搜索效率会很高。

**Comment by xiNeRoar** [comment]
我是用jellyfin的 可以照樣把jellyfin的api放下去嗎？
