### ISSUE TITLE
使用docker部署，文件夹映射默认media不可改

### ISSUE THREAD

**Issue by woshijie120** [allanpk716/ChineseSubFinder#433]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

>chinesesubfinder 版本: v0.33.12
> 环境: docker 

## 你遇到什么问题了？

> 描述一下你遇到的问题
nas环境为威联通，使用Container station部署，映射文件夹必须且只能为小写media，自行修改无效（程序会默认创建小写media进行挂载）
## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 描述以下你期望的结果
由于部署了一套nas-tool，且全部配置完成，希望可以联动使用chinesesubfinder，但是需要挂在目录一致。目前nas-tool映射目录为Media，而当前chinesesubfinder只能映射media，希望可以得到修改的办法

**Comment by avsba001** [comment]
?这是你的问题吧?
![截图_20220701235958](https://user-images.githubusercontent.com/29015932/176929699-f86fafd2-cfb9-4b0e-b5b8-139576827795.png)

**Comment by devome** [comment]
可以映射/Media同时不映射/media

**Comment by allanpk716** [comment]
nas-tool 是容器内部要求是 Media 吗?

**Comment by woshijie120** [comment]
已解决，虽然默认映射为media，新增映射Media也可以生效，感谢大佬支持。
