### ISSUE TITLE
存在ERROR日志:getFrontNameAndOrgName

### ISSUE THREAD

**Issue by macazy** [allanpk716/ChineseSubFinder#437]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.34.2
>
> 环境: windows

## 你遇到什么问题了？

> 出现ERROR日志，看起来是写字幕文件失败了
[ERROR]: 2022-07-07 06:58:50 - getFrontNameAndOrgName - WriteFile a4k G:\TV SHOW\The Expanse\Season 4\The Expanse _S4E9.zip 0 mkdir D:\chinesesubfinder\cache\tmp\The Expanse\[a4k]_0_G:: The filename, directory name, or volume label syntax is incorrect.
[ERROR]: 2022-07-07 06:58:50 - getFrontNameAndOrgName - WriteFile a4k G:\TV SHOW\The Expanse\Season 4\The Expanse _S4E9.zip 0 mkdir D:\chinesesubfinder\cache\tmp\The Expanse\[a4k]_0_G:: The filename, directory name, or volume label syntax is incorrect.
[ERROR]: 2022-07-07 06:58:50 - getFrontNameAndOrgName - WriteFile a4k G:\TV SHOW\The Expanse\Season 4\The Expanse _S4E9.rar 0 mkdir D:\chinesesubfinder\cache\tmp\The Expanse\[a4k]_0_G:: The filename, directory name, or volume label syntax is incorrect.
[ERROR]: 2022-07-07 06:58:50 - getFrontNameAndOrgName - WriteFile a4k G:\TV SHOW\The Expanse\Season 4\The Expanse _S4E9.zip 0 mkdir D:\chinesesubfinder\cache\tmp\The Expanse\[a4k]_0_G:: The filename, directory name, or volume label syntax is incorrect.
[ERROR]: 2022-07-07 06:58:50 - getFrontNameAndOrgName - WriteFile a4k G:\TV SHOW\The Expanse\Season 4\The Expanse _S4E9.zip 0 mkdir D:\chinesesubfinder\cache\tmp\The Expanse\[a4k]_0_G:: The filename, directory name, or volume label syntax is incorrect.

## 你的问题弄重现嘛？

> 能够重现

## 描述一下你期望的结果

>  如果这个ERROR日志影响字幕写入文件·，麻烦定位原因；不影响的话，就调整日志级别

## 给出当前程序的配置文件

> [ChineseSubFinderSettings.zip](https://github.com/allanpk716/ChineseSubFinder/files/9068481/ChineseSubFinderSettings.zip)

## 给出媒体文件夹的目录结构

![image](https://user-images.githubusercontent.com/3964839/177906684-1734c25e-044e-40f3-ac7d-06efb7adbeac.png)

## 请给出当次问题的完整日志

> [Logs.zip](https://github.com/allanpk716/ChineseSubFinder/files/9068497/Logs.zip)

**Comment by allanpk716** [comment]
下载的文件名有特殊字符导致的，我改一下，如果发现是类似的问题，就由程序随机一个文件名来存储
