### ISSUE TITLE
建议添加启动信息，docker容器正常启动到应用开始http服务这段时间有些长

### ISSUE THREAD

**Issue by Trim21** [allanpk716/ChineseSubFinder#438]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.34.3

环境: docker 

## 你想要新增或者改进什么功能？

今天正常启动容器，然后一直无法打开web ui。

docker exec进去之后看到应用已经正常启动了，然后等了一段时间才正常打开web ui。

只能看到cont-init的日志说`[services.d] starting services` 和 `[services.d] done.` 

可能是因为我的nas配置比较低，所以应用启动用了比较长的时间。

建议为应用添加一些启动日志，比如启动rod等的日志，通知用户此时应用仍然在初始化中。

**Comment by allanpk716** [comment]
日志写了的，教程也提到了要等
