### ISSUE TITLE
字幕下载优先级判断以及中英双语字幕下载

### ISSUE THREAD

**Issue by flowdesign-github** [allanpk716/ChineseSubFinder#446]
在CSF的web页面配置中, 有关于下载字幕的优先级以及多字幕下载的设置
![image](https://user-images.githubusercontent.com/87160795/178638592-7ec5834c-a480-461c-ad08-0d9c275b3a88.png)
 对于assrt这个源也做了相应的设定
![image](https://user-images.githubusercontent.com/87160795/178641670-c1c4a681-8fd4-4b94-9305-1442c620460e.png)
按照你在#406 里的描述， _目前几个字幕源的下载顺序是： zimuku > subhd > csf > assrt > shooter > xunlei，也许后续会给出对应抉择顺序的接口，暂时是写死的。_
但似乎从log里面看到正好相反？排在最前面的是Xunlei,然后shooter然后a4k然后assrt
![image](https://user-images.githubusercontent.com/87160795/178642383-1658e4c2-8adb-4c04-bf20-b6da9bd67fb9.png)
是这一段逻辑变化了么?

另外就是我在[https://post.smzdm.com/p/axz7gol4/](url) 提及了双语字幕下载的优先级大于单语言, 现在这个功能还存在么? 似乎我没有下载成功过双语的字幕

**Comment by allanpk716** [comment]
你截图的是多个字幕源下载的顺序，所有源都下载完毕后，会有个“评价”的阶段，才会按我说的那个抉择顺序。

双语肯定是有的，最新一集的西部世界就有。

下载那个字幕是下载当时决定的，如果每个下载周期字幕都有新增或者删减（指的是所有字幕源能够找到的），那么下载的情况也会变化，以当前次为准，特别是最新剧集。老剧集会相对稳定且可选择不多。

## 截图
![image](https://user-images.githubusercontent.com/1176000/178664440-f0d6f17e-7b31-48ee-899f-381ddc6b60cc.png)

**Comment by flowdesign-github** [comment]
理解了, 然后关于双语的我还要试试看,  刚刚开始尝试CSF, 因为现有的视频基本都有了字幕, 所以跑了很久都是skip的结果, 只有两个视频可以下载字幕然后都是单语的, 多谢解惑~
