### ISSUE TITLE
不能正常运行

### ISSUE THREAD

**Issue by JamLiang** [allanpk716/ChineseSubFinder#45]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: latest

环境: nas 黑群晖

## 你遇到什么问题了？

不能运行

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

正常运行

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

## 出错的日志信息可以复制一些出来吗？

![image](https://user-images.githubusercontent.com/31915092/132219897-5140186e-ecd1-4506-b786-3eaece53433c.png)

**Comment by allanpk716** [comment]
配置有问题，贴配置

**Comment by JamLiang** [comment]
已解决 谢谢 是配置问题
