### ISSUE TITLE
panic: db AutoMigrate error, database is locked

### ISSUE THREAD

**Issue by a597232887** [allanpk716/ChineseSubFinder#455]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.35.1
>
> 环境: docker
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 程序启动时，提示“panic: db AutoMigrate error, database is locked”然后自动重试，然后继续失败

## 你的问题弄重现嘛？

> 能重现

## 你期望的结果

> 程序正常启动

## 给出当前程序的配置文件

{"SpeedDevMode":false,"user_info":{"username":"","password":""},"common_settings":{"interval_or_assign_or_custom":1,"scan_interval":"0 18 * * *","threads":1,"run_scan_at_start_up":false,"movie_paths":["/media","/media1","/media2"],"series_paths":["/media3","/media4","/media5"],"local_static_file_port":"19037"},"subtitle_sources":{"assrt_settings":{"token":""}},"advanced_settings":{"proxy_settings":{"use_proxy":false,"use_which_proxy_protocol":"http","local_http_proxy_server_port":"19036","input_proxy_address":"127.0.0.1","input_proxy_port":"10809","need_pwd":false,"input_proxy_username":"","input_proxy_password":""},"debug_mode":false,"save_full_season_tmp_subtitles":false,"sub_type_priority":1,"sub_name_formatter":1,"save_multi_sub":true,"custom_video_exts":["ts","m2ts","avi","flv","wmv","mov","rm"],"fix_time_line":true,"topic":1,"suppliers_settings":{"xunlei":{"name":"xunlei","root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json","daily_download_limit":-1},"shooter":{"name":"shooter","root_url":"https://www.shooter.cn/api/subapi.php","daily_download_limit":-1},"subhd":{"name":"subhd","root_url":"https://subhd.tv","daily_download_limit":20},"zimuku":{"name":"zimuku","root_url":"https://zimuku.org","daily_download_limit":20},"assrt":{"name":"assrt","root_url":"https://api.assrt.net/v1","daily_download_limit":-1}},"scan_logic":{"skip_chinese_movie":false,"skip_chinese_series":false},"task_queue":{"max_retry_times":3,"one_job_time_out":300,"interval":10,"expiration_time":90,"download_sub_during_x_days":7,"one_sub_download_interval":12,"check_pulic_ip_target_site":""},"download_file_cache":{"ttl":72,"unit":"hour"}},"emby_settings":{"enable":false,"address_url":"","api_key":"","max_request_video_number":500,"skip_watched":false,"movie_paths_mapping":{"/media":"","/media1":"","/media2":""},"series_paths_mapping":{"/media3":"","/media4":"","/media5":""},"auto_or_manual":false,"threads":1},"developer_settings":{"enable":false,"bark_server_address":""},"timeline_fixer_settings":{"max_offset_time":120,"min_offset":0.1},"experimental_function":{"auto_change_sub_encode":{"enable":false,"des_encode_type":0},"chs_cht_changer":{"enable":false,"des_chinese_language_type":0},"remote_chrome_settings":{"enable":false,"remote_docker_url":"","remote_adblock_path":"","remote_user_data_dir":""},"api_key_settings":{"enabled":false,"key":""},"local_chrome_settings":{"enabled":false,"local_chrome_exe_f_path":""}}}

## 如果是使用 Docker，请给出对应的配置信息

> 由很早的版本一路通过portainer添加变量升级而来，在0.26版本可以正常工作

## 给出媒体文件夹的目录结构

> 不是这个问题

## 请给出当次问题的完整日志

[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-fixuser: executing... 
检测到映射了 '/app/cache'，创建软连接 '/config/cache' -> '/app/cache'
[cont-init.d] 10-fixuser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO]: 2022-07-22 16:57:53 - ChineseSubFinder Version: v0.35.1
[INFO]: 2022-07-22 16:57:53 - Reload Log Settings, level = Info
[INFO]: 2022-07-22 16:57:53 - Speed Dev Mode is Off
[INFO]: 2022-07-22 16:57:53 - PreJob.HotFix() Start...
[INFO]: 2022-07-22 16:57:53 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-07-22 16:57:53 - PreJob.HotFix() End
[INFO]: 2022-07-22 16:57:53 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-07-22 16:57:53 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-07-22 16:57:53 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-07-22 16:57:53 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-07-22 16:57:53 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-07-22 16:57:53 - releaseAdblock start
[INFO]: 2022-07-22 16:57:59 - releaseAdblock end
[INFO]: 2022-07-22 16:58:01 - PreJob.ReloadBrowser() End
[INFO]: 2022-07-22 16:58:01 - PreJob.Wait() Done.

2022/07/22 16:58:06 /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/cache_center/cache_center.go:52 database is locked
[5100.240ms] [rows:0] CREATE TABLE `daily_download_infos` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`supplier_name` varchar(255) NOT NULL,`public_ip` varchar(255) NOT NULL,`which_day` varchar(255) NOT NULL,`count` integer,PRIMARY KEY (`id`))
panic: db AutoMigrate error, database is locked

goroutine 1 [running]:
github.com/allanpk716/ChineseSubFinder/pkg/cache_center.NewCacheCenter({0x1272e09, 0x10}, 0xc0001ced80, 0xc000651dc0)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/cache_center/cache_center.go:54 +0x519
main.main()
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/cmd/chinesesubfinder/main.go:142 +0x1af
[INFO]: 2022-07-22 16:58:06 - ChineseSubFinder Version: v0.35.1
[INFO]: 2022-07-22 16:58:07 - Reload Log Settings, level = Info
[INFO]: 2022-07-22 16:58:07 - Speed Dev Mode is Off
[INFO]: 2022-07-22 16:58:07 - PreJob.HotFix() Start...
[INFO]: 2022-07-22 16:58:07 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-07-22 16:58:07 - PreJob.HotFix() End
[INFO]: 2022-07-22 16:58:07 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-07-22 16:58:07 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-07-22 16:58:07 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-07-22 16:58:07 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-07-22 16:58:07 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-07-22 16:58:07 - releaseAdblock start
[INFO]: 2022-07-22 16:58:11 - releaseAdblock end
[INFO]: 2022-07-22 16:58:13 - PreJob.ReloadBrowser() End
[INFO]: 2022-07-22 16:58:13 - PreJob.Wait() Done.

2022/07/22 16:58:18 /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/cache_center/cache_center.go:52 database is locked
[5027.664ms] [rows:0] CREATE TABLE `daily_download_infos` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`supplier_name` varchar(255) NOT NULL,`public_ip` varchar(255) NOT NULL,`which_day` varchar(255) NOT NULL,`count` integer,PRIMARY KEY (`id`))
panic: db AutoMigrate error, database is locked

goroutine 1 [running]:
github.com/allanpk716/ChineseSubFinder/pkg/cache_center.NewCacheCenter({0x1272e09, 0x10}, 0xc0000788a0, 0xc00050f880)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/cache_center/cache_center.go:54 +0x519
main.main()
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/cmd/chinesesubfinder/main.go:142 +0x1af
[INFO]: 2022-07-22 16:58:18 - ChineseSubFinder Version: v0.35.1
[INFO]: 2022-07-22 16:58:19 - Reload Log Settings, level = Info
[INFO]: 2022-07-22 16:58:19 - Speed Dev Mode is Off
[INFO]: 2022-07-22 16:58:19 - PreJob.HotFix() Start...
[INFO]: 2022-07-22 16:58:19 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-07-22 16:58:19 - PreJob.HotFix() End
[INFO]: 2022-07-22 16:58:19 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2022-07-22 16:58:19 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2022-07-22 16:58:19 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2022-07-22 16:58:19 - PreJob.ChangeSubNameFormat() End
[INFO]: 2022-07-22 16:58:19 - PreJob.ReloadBrowser() Start...
[INFO]: 2022-07-22 16:58:19 - releaseAdblock start
[INFO]: 2022-07-22 16:58:22 - releaseAdblock end
[INFO]: 2022-07-22 16:58:24 - PreJob.ReloadBrowser() End
[INFO]: 2022-07-22 16:58:24 - PreJob.Wait() Done.

2022/07/22 16:58:29 /home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/cache_center/cache_center.go:52 database is locked
[5012.897ms] [rows:0] CREATE TABLE `daily_download_infos` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`supplier_name` varchar(255) NOT NULL,`public_ip` varchar(255) NOT NULL,`which_day` varchar(255) NOT NULL,`count` integer,PRIMARY KEY (`id`))
panic: db AutoMigrate error, database is locked

goroutine 1 [running]:
github.com/allanpk716/ChineseSubFinder/pkg/cache_center.NewCacheCenter({0x1272e09, 0x10}, 0xc0004e9860, 0xc00014dd50)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/cache_center/cache_center.go:54 +0x519
main.main()
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/cmd/chinesesubfinder/main.go:142 +0x1af
后面都是一样的不停循环

**Comment by allanpk716** [comment]
确认是否有两个容器开启了，读写了相同的 db。数据库锁死了，不行就删除。

**Comment by a597232887** [comment]
因为字幕自动调整的缓存巨大，所以config文件夹我映射到了smb共享的文件夹里。挂载的时候添加nobrl解决了
