### ISSUE TITLE
“共享字幕”相关

### ISSUE THREAD

**Issue by qiuyuyang910** [allanpk716/ChineseSubFinder#456]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.30.0

环境: docker or Window or Linux or MAC
docker
## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？
有没有一种可能，从mkv的视频里面分离字幕然后上传？
## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.
无

**Comment by allanpk716** [comment]
内置字幕也有一定概率是“错误”的，还是人看完人肉确认的更加。后续会有额外的“共享字幕”的功能上线，如果划水时间够的话，大概率年底上线。
