### ISSUE TITLE
库中不显示任何文件

### ISSUE THREAD

**Issue by ReddotCleaner** [allanpk716/ChineseSubFinder#457]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.35.1
>
> 环境: docker（unraid）
>
> 在程序运行日志头部或者 Web UI 可以看到
![image](https://user-images.githubusercontent.com/34325738/180935793-6c696a29-c050-4104-947c-ac0e4a2d67c8.png)
![image](https://user-images.githubusercontent.com/34325738/180935810-7b5961f1-58a8-4a9c-8efb-158df4642a7a.png)

## 你遇到什么问题了？

> 库中不显示任何媒体文件，文件在控制台可以正常读取，日志中也有显示，目录已经过刮削，存在nfo文件

## 你的问题弄重现嘛？

> 稳定重现

## 你期望的结果

> 库中不显示电影或剧集文件

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "SpeedDevMode":false,
    "user_info":{
        "username":"admin",
        "password":"pwd"
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 6h",
        "threads":1,
        "run_scan_at_start_up":true,
        "movie_paths":[
            "/media/movies"
        ],
        "series_paths":[
            "/media/TVShows"
        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "enabled":false,
            "token":""
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"[http](https://www.json.cn/http)",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"10809",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":false,
        "custom_video_exts":[

        ],
        "fix_time_line":false,
        "topic":1,
        "suppliers_settings":{
            "csf":{
                "name":"csf",
                "root_url":"haha",
                "daily_download_limit":-1
            },
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv/",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org/",
                "daily_download_limit":20
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "daily_download_limit":-1
            },
            "a4k":{
                "name":"a4k",
                "root_url":"https://www.a4k.net/",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":false,
            "skip_chinese_series":false
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":true,
        "address_url":"http://192.168.31.21:8096/",
        "api_key":"embyapikey",
        "max_request_video_number":3000,
        "skip_watched":false,
        "movie_paths_mapping":{
            "/media/movies":""
        },
        "series_paths_mapping":{
            "/media/TVShows":""
        },
        "auto_or_manual":true,
        "threads":4
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":700,
        "min_offset":0.2
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":false,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        },
        "share_sub_settings":{
            "share_sub_enabled":false
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略
docker-cli和unraid自带的CA都试过了
docker run -d \
    -v /mnt/user/appdata/chinesesubfinder/config:/config   `# 冒号左边请修改为你想在主机上保存配置、日志等文件的路径` \
    -v /mnt/user/mydata:/media     `# 请修改为需要下载字幕的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要添加多个-v映射` \
    -v /mnt/user/appdata/chinesesubfinder/browser:/root/.cache/rod/browser `# 容器重启后无需再次下载 chrome，除非 go-rod 更新` \
    -e PUID=1026 \
    -e PGID=100 \
    -e PERMS=true       `# 是否重设/media权限` \
    -e TZ=Asia/Shanghai `# 时区` \
    -e UMASK=022        `# 权限掩码` \
    -p 19035:19035 `# 从0.20.0版本开始，通过webui来设置` \
    -p 19037:19037 `# webui 的视频列表读取图片用，务必设置不要暴露到外网` \
    --name chinesesubfinder \
    --hostname chinesesubfinder \
    --log-driver "json-file" \
    --log-opt "max-size=100m" `# 限制docker控制台日志大小，可自行调整` \
    allanpk716/chinesesubfinder

## 给出媒体文件夹的目录结构
![image](https://user-images.githubusercontent.com/34325738/180937035-f16ca4ae-7eed-4574-8d82-c777604802a7.png)

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 57 /media/TVShows/甜蜜家园 (2020)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 58 /media/TVShows/神探夏洛克 (2010)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 59 /media/TVShows/美好的日子
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 60 /media/TVShows/致不灭的你 (2021)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 61 /media/TVShows/虹猫蓝兔七侠传 The Story Of Hongmao And Lantu
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 62 /media/TVShows/行尸走肉 (2010)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 63 /media/TVShows/豪斯医生
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 64 /media/TVShows/赘婿 (2021)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 65 /media/TVShows/邊域謎城 (2016)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 66 /media/TVShows/雪国列车 (2020)
[INFO]: 2022-07-26 13:59:17 - updateLocalVideoCacheInfo 67 /media/TVShows/鱿鱼游戏 (2021)
[INFO]: 2022-07-26 13:59:17 - ScanNormalMovieAndSeries End
[INFO]: 2022-07-26 13:59:17 - ScanEmbyMovieAndSeries Start...
[INFO]: 2022-07-26 13:59:17 - Forced Scan And DownSub, tmpSetting.EmbySettings.MaxRequestVideoNumber = 1000000
[INFO]: 2022-07-26 13:59:17 - Movie Sub Dl From Emby API...
[INFO]: 2022-07-26 13:59:17 - Refresh Emby Sub List Start...
[ERROR]: 2022-07-26 13:59:20 - Refresh Emby Sub List Error
[ERROR]: 2022-07-26 13:59:20 - refreshEmbySubList Get "http://192.168.31.21:8096/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=1000000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=embyapikey": dial tcp 192.168.31.21:8096: connect: no route to host
[INFO]: 2022-07-26 13:59:20 - ScanEmbyMovieAndSeries End
[ERROR]: 2022-07-26 13:59:20 - ScanEmbyMovieAndSeries Get "http://192.168.31.21:8096/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=1000000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=embyapikey": dial tcp 192.168.31.21:8096: connect: no route to host
[INFO]: 2022-07-26 13:59:20 - Video Scan Finished By webui, cost: 0.27129502095 min
[INFO]: 2022-07-26 13:59:20 - ------------------------------------
![image](https://user-images.githubusercontent.com/34325738/180938210-0ce3a9db-c560-43cd-aa44-6a98452e16e2.png)
程序有媒体文件777权限

**Comment by allanpk716** [comment]
你点击“刷新缓存”，然后看后续的日志是那些，缓存点击不会建立的，因为这个是手动操作的部分，自动扫描不会去建立这个部分的缓存（两个扫描的性能代价不一样）

**Comment by ReddotCleaner** [comment]
> 

![image](https://user-images.githubusercontent.com/34325738/181262048-f7e96aab-6fa3-45df-97d2-67a134f57aef.png)
![image](https://user-images.githubusercontent.com/34325738/181262130-e7ad9485-cdff-48e8-93fa-3b1458063e4a.png)
刷新后日志如图1，库中仍未出现内容

**Comment by allanpk716** [comment]
因为你连接不上本程序的解析服务器，后续 IMDB 转 TMDB ID 需要服务器中转

![image](https://user-images.githubusercontent.com/1176000/181400698-9b7bde3c-d64a-4634-98f0-08f41cc28424.png)

**Comment by czw1259** [comment]
![屏幕截图 2022-07-29 203507](https://user-images.githubusercontent.com/75195638/181760122-f60bcfc6-87c6-4765-aee5-29599be5a09a.png)

**Comment by ReddotCleaner** [comment]
![image](https://user-images.githubusercontent.com/34325738/181765249-d7505225-0e88-41ff-8ed4-2835da9610c3.png)
事实上我的网络环境是可以正常连接IMDB、TMDB这两个网站的，后面的文件也没有40错误

**Comment by allanpk716** [comment]
查看这两个文件是否生成，以及日志，完整扫描日志

![image](https://user-images.githubusercontent.com/1176000/181915951-13b5d50b-3cf7-4939-a451-15f2633c72b5.png)

**Comment by ReddotCleaner** [comment]
未生成两个json文件
![image](https://user-images.githubusercontent.com/34325738/182008328-16424e31-42ce-406c-9969-776574d8d96f.png)
[ChineseSubFinder--202207310000--.log](https://github.com/allanpk716/ChineseSubFinder/files/9227991/ChineseSubFinder--202207310000--.log)
完整的log文件如上

**Comment by jinfeng1985** [comment]
我是0.37.2也是，没有任何库文件，nfo都是有的

**Comment by leonchanithotmail** [comment]
我也是同样的问题，使用的是nas-tools、emby。
[https://www.z4a.net/images/2022/08/04/6da0289ad555b46b428a96468b1c34eb.png](url)

**Comment by allanpk716** [comment]
> 未生成两个json文件 ![image](https://user-images.githubusercontent.com/34325738/182008328-16424e31-42ce-406c-9969-776574d8d96f.png) [ChineseSubFinder--202207310000--.log](https://github.com/allanpk716/ChineseSubFinder/files/9227991/ChineseSubFinder--202207310000--.log) 完整的log文件如上

升级到 v0.37.6 ，开 Debug 在从 WebUI 触发一次，也需要完整日志。这个版本新增了更多的 Debug 信息，你这扫描速度太快了，是有问题的。正常一个扫描流程应该是分钟级别的，除非没啥视频。

**Comment by ReddotCleaner** [comment]
> > 未生成两个json文件 ![image](https://user-images.githubusercontent.com/34325738/182008328-16424e31-42ce-406c-9969-776574d8d96f.png) [ChineseSubFinder--202207310000--.log](https://github.com/allanpk716/ChineseSubFinder/files/9227991/ChineseSubFinder--202207310000--.log) 完整的log文件如上
> 
> 升级到 v0.37.6 ，开 Debug 在从 WebUI 触发一次，也需要完整日志。这个版本新增了更多的 Debug 信息，你这扫描速度太快了，是有问题的。正常一个扫描流程应该是分钟级别的，除非没啥视频。
> 
> 输出的 Debug 信息会包含你视频相对于 CSF 的绝对路径信息，你观察下看是否有误的，我担心是自动映射路径出错导致的。
> 
> 比如，关注“GetPathUrlMap”、“pathUrlMap”这两个关键词，的 Debug 输出的日志信息。

![image](https://user-images.githubusercontent.com/34325738/183661788-dfc2e715-5d97-496d-80a9-0ecf1b47834e.png)
![image](https://user-images.githubusercontent.com/34325738/183661901-87768a50-0be0-4167-bc62-a9dc0f9e0273.png)
看起来路径映射也没有问题，附上日志
[ChineseSubFinder--202208090000--.log](https://github.com/allanpk716/ChineseSubFinder/files/9291085/ChineseSubFinder--202208090000--.log)

**Comment by flywalt** [comment]
同样的问题……持续关注

**Comment by yixiar** [comment]
同样 关注。另外一个帖子反馈了信息，但是被关闭了！ :(

**Comment by PKC278** [comment]
同样的问题

**Comment by xuanqb** [comment]
同样的问题 群晖

**Comment by hurttttr** [comment]
同样的问题 openwrt 树莓派

**Comment by allanpk716** [comment]
日志里面有一个错误：

[ERROR]: 2022-08-09 04:43:20 - ScanNormalMovieAndSeries open /media/movies: no such file or directory

你能够尝试在  CSF 容器中去访问看看吗？

@ReddotCleaner

**Comment by allanpk716** [comment]
以及你的 Emby 是什么版本的，近期没有放新视频进去吗？我看 API 获取的信息是空的。 @ReddotCleaner

**Comment by ReddotCleaner** [comment]
> 以及你的 Emby 是什么版本的，近期没有放新视频进去吗？我看 API 获取的信息是空的。 @ReddotCleaner
> 
> 如果 Emby 都获取不到数据，又开启了 Emby 的功能，那么这里是无法正确去缓存数据的。先排查 Emby 的问题吧

额，有点怪，我换了一个emby的APIkey之后，库里面的文件就全显示出来了，字幕也在下载了，之前的key是有毒还是怎的
![image](https://user-images.githubusercontent.com/34325738/185621617-16034ea2-c1d5-4e3c-91ba-8f37d1ceaec9.png)
![image](https://user-images.githubusercontent.com/34325738/185621683-868b9ee4-ba21-4462-9fb4-eef40f90fcbf.png)
ChineseSubFinder（ver：0.37.6） emby（ver：4.7.2.0）

**Comment by allanpk716** [comment]
因为你开启了 Emby，所以在常规扫描完成后，会与 Emby 的结果交叉，如果你的 Emby API 错误，那么得到的结果也是空的，一交叉就也是空的，所以你才没有得到上面提到的两个缓存文件。应该也算一个 bug，我想想怎么应对先。

**Comment by ReddotCleaner** [comment]
能用就是好事，这个issue就留给作者大大看关不关吧

**Comment by allanpk716** [comment]
会放入到常见问题中，给后续人一个参考吧。

**Comment by ReddotCleaner** [comment]
@allanpk716 想到一个enhancement，能不能参考隔壁的nas-tools，在填入emby api key 后增加一个测试按钮，这样就可以直观的看到emby有没有连接成功
![image](https://user-images.githubusercontent.com/34325738/187010416-94b943c9-42e8-4f4e-91f7-0132886c6f2f.png)

**Comment by allanpk716** [comment]
可以的
