### ISSUE TITLE
搜刮字幕建议

### ISSUE THREAD

**Issue by qiuyuyang910** [allanpk716/ChineseSubFinder#464]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.37.2

环境: docker

## 你想要新增或者改进什么功能？

你想要新增或者改进什么功能？
一般下载的资源需要做种，不方便更改文件名，所以搜索字幕的时候能不能读取nfo文件里面的剧集名等进行搜刮字幕，而不是直接使用文件名搜刮字幕
## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.
无

**Comment by allanpk716** [comment]
现在使用的是 TMDB ID 去查询中文译名来搜索的
