### ISSUE TITLE
当电视剧的imdb语言信息为mandarin时判断为非中文电视剧

### ISSUE THREAD

**Issue by xjn819** [allanpk716/ChineseSubFinder#47]
if len(t.Languages) > 0 && strings.ToLower(t.Languages[0]) == "chinese" {
		log_helper.GetLogger().Infoln("Skip", filepath.Base(seriesRootPath), "Sub Download, because series is Chinese")
		return true, t, nil

例如 云南虫谷
https://www.imdb.com/title/tt15299712/

**Comment by allanpk716** [comment]
谢谢反馈，晚点修复
