### ISSUE TITLE
subhd 只有一条查询结果无法下载字幕

### ISSUE THREAD

**Issue by irockstar** [allanpk716/ChineseSubFinder#48]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

环境: docker  镜像 版本: allanpk716/chinesesubfinder:latest  (20210913)

## 你遇到什么问题了？

subhd 只有一条查询结果无法下载字幕，从网站可以进入详情页下载字幕

IMDBID：tt3626476

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

能够下载字幕

## 可以提供遇到问题时候，电影、连续剧的信息吗？

chinesesubfinder_1  | [ERROR]: 2021-09-15 15:37:48 - subhd keyword: tt3626476
chinesesubfinder_1  | [ERROR]: 2021-09-15 15:37:48 - getSubListFromKeyword4Movie IMDBID can not found sub /media/Movie/Vacation Friends (2021)/Vacation Friends (2021) WEBRip-1080p.mp4 subhd step0 Img Parent less than 2
chinesesubfinder_1  | [ERROR]: 2021-09-15 15:38:25 - subhd keyword: Vacation Friends 2021
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - 2 subhd End...
chinesesubfinder_1  | [ERROR]: 2021-09-15 15:38:25 - 2 subhd oneMovieDlSubInOneSite subhd step0 Img Parent less than 2
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - 2 DlSub End /media/Movie/Vacation Friends (2021)/Vacation Friends (2021) WEBRip-1080p.mp4
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - Download Movie Sub End...
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - Download Series Sub Started...
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - Download Series Sub End...
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - Download One End...
chinesesubfinder_1  | [INFO]: 2021-09-15 15:38:25 - First Time Download End

![网站截图](https://user-images.githubusercontent.com/1676743/133396809-3dd3c129-f267-4810-b482-b655d64b5396.png)

![HTML](https://user-images.githubusercontent.com/1676743/133396940-c180c473-340c-4f6f-852d-9ad7248507d1.png)

**Comment by allanpk716** [comment]
你 chinesesubfinder  版本太低了，建议升级到最新的 v0.13.x 或者 latest，近期还会有新功能发布

**Comment by irockstar** [comment]
![docker版本](https://user-images.githubusercontent.com/1676743/133407288-365784cb-7a3f-4e9c-a997-4ecde8963d5d.png)

版本号写错了，我拉的最新的镜像

**Comment by allanpk716** [comment]
subhud 搜索界面的页面又更新了，需要更新解析器。

这个电影在 zimuku 应该可以找到字幕的，还是也找不到？zimuku 我这边测试是有的，如果有问题希望给出更多的日志。

![image](https://user-images.githubusercontent.com/1176000/133413927-585cf9b1-f7d0-458e-a8c5-60facf0faaaa.png)

**Comment by irockstar** [comment]
好的，我用最新的代码编译个镜像再试试，3Q

**Comment by allanpk716** [comment]
> 好的，我用最新的代码编译个镜像再试试，3Q

最新代码也没解决呢，晚上回去改了推送吧。

**Comment by allanpk716** [comment]
v0.14.x 会修复这个问题，dev 上传了解决方案。等这个版本目标的功能块做完了，估计今晚能够推送···
