### ISSUE TITLE
Emby 的对接可以不扫描所有library只扫描指定的几个吗

### ISSUE THREAD

**Issue by xingfanxia** [allanpk716/ChineseSubFinder#489]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.40.1   docker on synlogy dsm 7.0

## 你想要新增或者改进什么功能？

Emby 的对接可以不扫描所有library只扫描指定的几个吗

## 这个功能有什么可以参考的资料吗？

现在会扫描我所有的影片并匹配, 但我的emby还包括了我的影音素材和拍的视频, 现在回尝试对这些也进行imdb匹配非常耗时间

**Comment by xingfanxia** [comment]
那很奇怪还是扫描了我整个emby library, 里面有几个并不在映射的media path里面

**Comment by allanpk716** [comment]
读取 Emby 的时候是按“最大量”来获取**最近加入**视频的，这个时候 Emby 是从数据库加载数据的，应该不至于慢，或者很吃硬盘。

如果要实现你提到的“排除”，那么无形中就增加了 Emby 设置的复杂度。现在的实现方案就是只要物理路径（必要关注的视频目录信息）填写对了，后续的设置尽可能从简，由程序帮你们进行交叉排除。

倒是有人提过需要物理路径的排除，或者说是某个视频文件夹的排除功能，还没空做出来···Emby 的排除也不是不能做，就是感觉必要性不大。
