### ISSUE TITLE
如何解决字幕同步的问题是关键

### ISSUE THREAD

**Issue by netduke777** [allanpk716/ChineseSubFinder#499]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
docker
chinesesubfinder 版本: v0.4.0
最新版本
环境: docker or Window or Linux or MAC
docker
## 你想要新增或者改进什么功能？
现在翻译软件也还好, 有subtitledit+google+英语底子, 只要有英文字幕就基本可以解决了. 感觉更为重要的是字幕同步的问题, 不同步的中文字幕还不如直接看英文.
用了一段时间感觉下载的字幕能完全同步的不高, 自己上网手动搜索了一些, 感觉也是同样的问题. 而且字幕同步的问题, 还不简单的是整体落后或是提前的问题, 而是多个时序点不准, 可能压制的时候速率不同造成的. 中文字幕问题更为严重, 基本上是下载3-4个字幕才能找到一个匹配的, 英文好些,从opensubtitles下载最新的英文字幕, 完全同步的命中率大概有8-9层以上, 然后用subtitledit自动翻译, 保存为中英双字,虽然机翻难免存在错误, 但是下面有英文可以对照, 而且一般的生活类型基本上感觉能看. 总之这种比看不同步的中文更舒服一些.
也试过手工调整中文字幕的同步, 如果是整体提前或落后的好办些, 打开视频文件, 找个点字影同步下就好, 但是发现更多的问题是整个字幕不同步, 这样就需要多点对照同步, 此时一个准确同步的英文字幕就很关键, 对照时序准确的英文字幕, 设置多个同步点, 来强制同步中文字幕同步解决了一部分,但是很耗时间(根据设置的同步点多少),基本一个要20-30分钟.

你想要新增或者改进什么功能？
希望项目能在字幕同步的方向上发展, 如果能解决这个问题, 才是真正的可用的 . 前面盲目让chinesesubfinder重新下载了所有片子的字幕结果发现同步问题很严重, 完全同步的命中率很低, 反而把以前的字幕替换掉了, 最后不得已, 重新导入了片库, 2000多部, 扒了我一层皮, 现在csf我仅手工使用了 ,  不敢让他再自动替换了 . 感觉同步问题不解决, 项目发展会受到很大的限制. 感谢项目组的辛勤无私工作, 仅提些小的建议, 谢谢.

## 这个功能有什么可以参考的资料吗？

 这个功能有什么可以参考的资料吗？是否可以列举一些.

**Comment by allanpk716** [comment]
不要想的太复杂，自己去用 https://github.com/smacke/ffsubsync 这个项目手动同步，如果解决不了就没得办法，目前业内最佳的方案。

这个方案的限制上面项目说的很清楚了，对比自己的情况

**Comment by allanpk716** [comment]
然后我就对这个项目转写的go， 0.0几秒的校正误差，从功能出来我用到现在没见校正不对的，除非片源是导演剪辑或者被删减了，不然稳的很
