### ISSUE TITLE
有没有非容器版使用的方式

### ISSUE THREAD

**Issue by x91270** [allanpk716/ChineseSubFinder#5]
多数情况下 NAS ，都是通过局域网挂载。有时候会通过 Windows + TMM  进行更新维护，
再通过 DOCKER 进行字幕的处理，有点麻烦

**Comment by allanpk716** [comment]
> 多数情况下 NAS ，都是通过局域网挂载。有时候会通过 Windows + TMM  进行更新维护，
> 
> 再通过 DOCKER 进行字幕的处理，有点麻烦

是想一次性运行呢，还是作为服务？

**Comment by x91270** [comment]
一次性运行，如果是做服务。就会选择 DOCKER 了

**Comment by allanpk716** [comment]
> 一次性运行，如果是做服务。就会选择 DOCKER 了

OK，这两天应该可以给出支持传参的版本，同时搞定 github action 编译输出多平台可执行程序版本。

**Comment by x91270** [comment]
谢谢，大佬

**Comment by allanpk716** [comment]
> 谢谢，大佬

刚搞定自动化编译，你试试这个版本，暂时不是一次性运行的，还是通过 config.xml 控制扫描间隔的。明天有空再更新传参一次性运行的。
https://github.com/allanpk716/ChineseSubFinder/releases/tag/v0.8.8

**Comment by x91270** [comment]
TinyMediaManager  NFO语言设置  以及文件名 必须用英语么？

**Comment by x91270** [comment]
TinyMediaManager  NFO语言设置  以及文件名 必须用英语么？

**Comment by x91270** [comment]
能够增加超过三个月也进行字幕下载 的参数

**Comment by allanpk716** [comment]
> TinyMediaManager NFO语言设置 以及文件名 必须用英语么？

中文英文都行，主要是读取 IMDB ID 或者 播出的时间

**Comment by allanpk716** [comment]
> 能够增加超过三个月也进行字幕下载 的参数

需求新开了一个 ISSUS #6 ，具体的会在这里讨论

**Comment by allanpk716** [comment]
见 https://github.com/allanpk716/ChineseSubFinder/releases ，内有 actions 编译输出的 Windows 版本，暂时没有支持传参运行。
