### ISSUE TITLE
建议增加 启动容器/程序时，是否开始搜索并下载 选项

### ISSUE THREAD

**Issue by SuperNG6** [allanpk716/ChineseSubFinder#50]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker or Window or Linux or MAC

## 你想要新增或者改进什么功能？

建议增加 启动容器/程序时，是否开始搜索并下载 选项
场景：一天内多次更新镜像 | 一天内多次重启NAS
问题：以上场景并不需要启动容器/程序时搜索并下载字幕
建议：在配置文件中加入选项`RunAtStartup: false`
           第一次开始运时间为启动容器/程序时间+EveryTime设定的时间

## 这个功能有什么可以参考的资料吗？
无

**Comment by allanpk716** [comment]
要不记录一下扫描的最后一次时间，然后判断一下间隔，如何？

**Comment by SuperNG6** [comment]
可以，但是实际效果最终差不多，记录一下扫描的最后一次时间要更好一些

**Comment by allanpk716** [comment]
> 可以，但是实际效果最终差不多，记录一下扫描的最后一次时间要更好一些

先按你提的方案做了，这样快···
