### ISSUE TITLE
电视剧目录缺失nfo文件,描时间为01:49:02  创建NFO时间为01:49:09

### ISSUE THREAD

**Issue by wy2705** [allanpk716/ChineseSubFinder#500]
chinesesubfinder 版本: v0.40.1

环境: docker

## 你想要新增或者改进什么功能？
nas-tool通知后，延迟30秒扫描NFO

## 这个功能有什么可以参考的资料吗？
扫电视剧时总提示当前目录缺失nfo文件，但是一看是有的，查看日志发现nas_tool通知扫描的时间早于建立NFO的时间，电影正常。
扫描时间为01:49:02  创建NFO时间为01:49:09

**Comment by AWSOMEALEX** [comment]
兄弟，有解决吗？我联动MP，也遇到一样的问题。
