### ISSUE TITLE
电影字幕可以正常下载，电视剧一个都不能下。

### ISSUE THREAD

**Issue by du724931566** [allanpk716/ChineseSubFinder#503]
## 你使用的 chinesesubfinder 是什么版本，什么环境？
0.40版本和0.41beta2都试过了，环境是docker，配置正常。
读取电影也都正常。
问题现在是无法对电视剧正确读取，应该是通过nastool自动刮削完成的电视剧，把剧集内容改成了第几集这样的或者具体某一集的名字，然后chinesesubfinder无法读取电视剧名称。目前没有一个电视剧是能够正常下载了的。电影下了不少

> chinesesubfinder 版本: vx.x.x
>v0.41-Beta2

> 环境: docker or Window or Linux or MAC
>docker

> 在程序运行日志头部或者 Web UI 可以看到

[WARNING]: 2022-10-06 00:05:01 - cancel Downloader.QueueDownloader()
webUI只有仅此一条日志。

以下是docker日志内容随机举例一条美剧
2022/10/6 1:13:34  [INFO]: 2022-10-06 01:13:34 - ------------------------------------------
2022/10/6 1:13:34  [INFO]: 2022-10-06 01:13:34 - Queue 1 a4k End
2022/10/6 1:13:34  [ERROR]: 2022-10-06 01:13:34 - Queue 1 a4k GetSubListFromFile4Series Get "https://www.imdb.com/title/tt3230854": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022/10/6 1:13:34  [ERROR]: 2022-10-06 01:13:34 - a4k GetMixMediaInfo Get "https://www.imdb.com/title/tt3230854": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022/10/6 1:13:34  [ERROR]: 2022-10-06 01:13:34 - getVideoInfoFromIMDBWeb, 苍穹浩瀚 Get "https://www.imdb.com/title/tt3230854": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022/10/6 1:13:32  [INFO]: 2022-10-06 01:13:32 - Queue 1 a4k Start...
2022/10/6 1:13:32  [INFO]: 2022-10-06 01:13:32 - ------------------------------------------

## 你遇到什么问题了？
无法下载电视剧的字幕。

> 
读取电视剧时读取状态应该不对，没法获取正确的电视剧名称和某一集。也有可能是不同站的搜索逻辑不一样？
尝试了几百条影视资源最后总结只有电视剧全部都无法正常下载字幕。没有例外

## 你的问题弄重现嘛？
> 
能够重现

## 你期望的结果

> 描述以下你期望的结果

希望大佬能够优化这个问题，目前下到有些美剧没有字幕，美剧不能自动下载更新字幕实在是让人头疼
辛苦了

**Comment by du724931566** [comment]
![image](https://user-images.githubusercontent.com/49524705/194123166-b388dd69-9cbc-4408-bc1e-dc17316e8e20.png)
目前的已完成全都是电影。。。。

**Comment by allanpk716** [comment]
a4k GetMixMediaInfo Get "https://www.imdb.com/title/tt3230854": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

无法连接 IMDB

**Comment by 759071793** [comment]
同样的问题，美剧无法下载字幕，一会儿就消失了

**Comment by 759071793** [comment]
> Reference

/media/TV/American.Gods.S03.1080p.BluRay.x265-RARBG/American.Gods.S03E03.1080p.BluRay.x265-RARBG.mp4
j[INFO]: 2022-10-13 13:36:30 - you need check the directory structure of a series, so will delete this job
找到问题了，目录结构不对

**Comment by du724931566** [comment]
挂了代理之后目前问题好像解决了。谢谢
