### ISSUE TITLE
咨询：pcm是什么格式，占了很大空间，如何关闭

### ISSUE THREAD

**Issue by sapipoZZZ** [allanpk716/ChineseSubFinder#504]
> chinesesubfinder 版本: v0.40.1
>
> 环境: docker
>
CSF-subFixCache下，每一集电影/连续剧，都有一个目录，每个目录下有30~90Mb的pcm文件，已经把磁盘撑爆，如何关闭？

**Comment by allanpk716** [comment]
关闭，自动校正时间轴功能，手动清理对应缓存。这个是视频对应的音频文件，基于音频校正字幕时间轴，如果启用就会自身管理缓存，一周没有被使用就移除。

**Comment by livebelive** [comment]
@allanpk716 请问，这个一周的时限是否受参数影响？
比如：下载缓存过期时间设置 这个参数？这个参数默认时间是多少？我的设置了4320小时，也就是180天。。。请问是否是因为这个原因所以一直没有自动清理缓存，导致越来越大？
