### ISSUE TITLE
 请问下作者 windows如何使用？

### ISSUE THREAD

**Issue by Mabisi** [allanpk716/ChineseSubFinder#51]
可以出一个简单的教程吗。。

**Comment by allanpk716** [comment]
> 可以出一个简单的教程吗。。

可以啊，抽点时间写一个。跟现在的教程差不多的。但是 emby api 功能应该用不了，估计地址转换会出问题。

**Comment by allanpk716** [comment]
> 可以出一个简单的教程吗。。

看看这个[文档](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%9C%A8%20Windows%20%E4%B8%8A%E4%BD%BF%E7%94%A8.md)
