### ISSUE TITLE
字幕扫描设置成不扫描，每次应用重新启动，又会变成每6小时扫描

### ISSUE THREAD

**Issue by hijakke** [allanpk716/ChineseSubFinder#517]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.41.0
>
> 环境: docke
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 字幕扫描设置成不扫描，每次应用重新启动，又会变成每6小时扫描

> 可以重现

## 你期望的结果

> 反馈问题

**Comment by allanpk716** [comment]
v0.42 修复了，试试

**Comment by hijakke** [comment]
已经没有问题了
