### ISSUE TITLE
非常高RAM使用率

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#52]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.16.0

环境: docker on Synology NAS

## 你遇到什么问题了？

由0.13.0升級到0.16.0，使用了SubNameFormatter: 1之後，RAM使用率暴增，在Docker的日誌裡也發現字幕網站的搜尋量從個位數急升到百位數，如圖下
![image](https://user-images.githubusercontent.com/66216186/133915015-f46c27b5-c665-4636-a1ae-4c334eaf0907.png)
![image](https://user-images.githubusercontent.com/66216186/133915020-54e928c0-530c-49ba-b973-7f8084234858.png)

## 你的问题弄重现嘛？

不知道

## 你期望的结果

應該像之前一樣，字幕網站搜尋量只有個位到十位數?

## 出错的日志信息可以复制一些出来吗？

![image](https://user-images.githubusercontent.com/66216186/133915046-12f5621b-c5d5-410e-baa3-359a851296bd.png)
這是我的Config
![image](https://user-images.githubusercontent.com/66216186/133915057-7a8b4f65-8a3c-4aed-a254-baf160804c00.png)

**Comment by allanpk716** [comment]
## 问题1
![image](https://user-images.githubusercontent.com/1176000/133919581-d25fd241-729f-4fe2-bae4-9d5366af4ce9.png)
针对你提及的这个问题，这个 Index 是第几个视频在处理的意思，这样再并发的时候才能便于看出哪些日志的关联的。

## 问题2
RAM使用率暴增

SubNameFormatter 的设置跟内存无关。RAM 用量增加的原因还是使用了模拟操作浏览器去爬取 subhd 的字幕（现在反爬虫规则比之前严格了，之前的纯 http 去提交内存低，但是容易本检测）。因为使用的 Chrome 的浏览器，所以内存高是正常的。所以也推荐是 2 线程并发。

也想要麻烦你关注一下，如果完成一轮扫描了，内存是否有降低。如果还有请提交 issue

**Comment by allanpk716** [comment]
我看你设置是 1 的并发线程，那我需要去修改推荐设置的描述了。

**Comment by allanpk716** [comment]
见 #53

**Comment by xiNeRoar** [comment]
> ## 问题1
> ![image](https://user-images.githubusercontent.com/1176000/133919581-d25fd241-729f-4fe2-bae4-9d5366af4ce9.png)
> 针对你提及的这个问题，这个 Index 是第几个视频在处理的意思，这样再并发的时候才能便于看出哪些日志的关联的。
> 
> ## 问题2
> RAM使用率暴增
> 
> SubNameFormatter 的设置跟内存无关。RAM 用量增加的原因还是使用了模拟操作浏览器去爬取 subhd 的字幕（现在反爬虫规则比之前严格了，之前的纯 http 去提交内存低，但是容易本检测）。因为使用的 Chrome 的浏览器，所以内存高是正常的。所以也推荐是 2 线程并发。
> 
> 也想要麻烦你关注一下，如果完成一轮扫描了，内存是否有降低。如果还有请提交 issue

將Thread改成2再重啟之後 RAM使用率回歸正常 大概300~400RAM左右
