### ISSUE TITLE
使用docker-compose.yml手动配置network参数后，服务无法启动

### ISSUE THREAD

**Issue by iwsyt** [allanpk716/ChineseSubFinder#524]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
>v0.41.0
> 环境: docker or Window or Linux or MAC
>docker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 存在多服务不同网络通信需求，所以当手动配置当前服务的network参数时，服务无法正常启动

## 你的问题弄重现嘛？

> 能够重现，而且是100%

## 你期望的结果

> docker-compose.yml部署方式能够指定服务的多个docker network，实现多服务网络通信

## 给出当前程序的配置文件

> 程序未启动成功，均为默认配置

## 如果是使用 Docker，请给出对应的配置信息

> docker-compose.yml配置如下

 37   chinesesubfinder:
 38     image: allanpk716/chinesesubfinder:v0.41.0
 39     volumes:
 40       - ./chinesesubfinder/config:/config
 41       - /home/iwsyt/hdd/hdd2/jellyfin-media:/media
 42       - ./chinesesubfinder/browser:/root/.cache/rod/browser
 43     environment:
 44       - PUID=1000
 45       - PGID=1000
 46       - PERMS=false
 47       - TZ=Asia/Shanghai
 48       - UMASK=022
 49     restart: always
 50     hostname: chinesesubfinder
 51       #network_mode: bridge
 52     container_name: chinesesubfinder
 53     ports:
 54       - 19035:19035  # 从0.20.0版本开始，通过webui来设置
 55       - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
 56     logging:
 57       driver: "json-file"
 58       options:
 59         max-size: "100m" # 限制docker控制台日志大小，可自行调整
 60     networks:
 61       nas-tools-net:
 
 82 networks:
 83   nas-tools-net:
 84     driver: bridge
 85     external: false

## 请给出当次问题的完整日志
docker-compose启动容器日志如下：
[error.log](https://github.com/allanpk716/ChineseSubFinder/files/9878515/error.log)

**Comment by allanpk716** [comment]
换 lite

**Comment by iwsyt** [comment]
使用lite版本可以正常启动了，感谢，请问非lite版能解决这个问题吗，还是说这是必要的配置？

**Comment by allanpk716** [comment]
不是你配置的问题，是你系统的问题导致的。无法使用 chrome

**Comment by iwsyt** [comment]
是的，宿主机是ubuntu server版，谢谢解答。
