### ISSUE TITLE
v0.14.x 之后内存占用较高的原因以及后续考虑的解决方案

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#53]
## 之前版本的实现
在这个版本之前，基本都是优先使用 http 去直接与 api 接口和网站交互的，那么内存占用就小很多。仅仅是下载字幕的那个页面才是使用 Chrome 去模拟提交下载。这样的考虑就是尽可能内存占用率低。

## 起因
随着这几个月的使用，发现 subhd 的爬虫检测加强了，经常收到函数“超时”的提醒，也就是 subhd 相关的逻辑不能正常执行被服务器终止了。

## 起因的解决方案
为了解决这个问题，就把 subhd 所有的逻辑切换到了模拟操作 Chrome 上了。众所周知的，Chrome 的内存消耗的大户。所以内存占用会很高···一般的小破设备可能就吃力或者没法用了。

## 后续的应对方案
应该还是做 opensubtitles 的上传，然后大家可以选择分享自己下载好的字幕上去，从这里去统一下载吧。又或者会搭建独立的服务完成这个任务，还在评估中。这样某些“重活”可以分担出去，没必要大家都跑一样的任务，当然这个会给出**手动开关开启分享**。

## 目前运行截图

等待执行任务的资源占用情况

![image](https://user-images.githubusercontent.com/1176000/133920444-b5698eec-4a33-46f8-9c0a-ecc035dd3e36.png)

进程情况

![image](https://user-images.githubusercontent.com/1176000/133920463-ad278a5b-c803-45e0-8412-8da7c64b5b6e.png)

**Comment by wloot** [comment]
遇到一个问题 subhd 获取字幕会等待很久然后超时:
`DownloadSub4Movie.NewPoolWithFunc got time out context deadline exceeded`
不确定是环境问题还是bug，不过我直接 curl subhd 网站是能很快返回内容的。

**Comment by wloot** [comment]
> 遇到一个问题 subhd 获取字幕会等待很久然后超时: `DownloadSub4Movie.NewPoolWithFunc got time out context deadline exceeded` 不确定是环境问题还是bug，不过我直接 curl subhd 网站是能很快返回内容的。

发现只有使用 ForceFullScanAndDownloadSub 才会触发这个问题。

**Comment by allanpk716** [comment]
> 遇到一个问题 subhd 获取字幕会等待很久然后超时: `DownloadSub4Movie.NewPoolWithFunc got time out context deadline exceeded` 不确定是环境问题还是bug，不过我直接 curl subhd 网站是能很快返回内容的。

偶发问题，调试模式下 go-rod 也会遇到，肉眼看到浏览器刷新完毕了，但是获取到的页面内容是空的，又或者肉眼看到刷新完毕，但是 go-rod 的 mustload 超时了。暂时没得什么好办法，只能等待下一次扫描，可能又好了。会关注 go-rod 的更新，有就尽可能尝试最新的。

**Comment by allanpk716** [comment]
> > > 遇到一个问题 subhd 获取字幕会等待很久然后超时: `DownloadSub4Movie.NewPoolWithFunc got time out context deadline exceeded` 不确定是环境问题还是bug，不过我直接 curl subhd 网站是能很快返回内容的。
> > 
> > 
> > 偶发问题，调试模式下 go-rod 也会遇到，肉眼看到浏览器刷新完毕了，但是获取到的页面内容是空的，又或者肉眼看到刷新完毕，但是 go-rod 的 mustload 超时了。暂时没得什么好办法，只能等待下一次扫描，可能又好了。会关注 go-rod 的更新，有就尽可能尝试最新的。
> 
> 出问题后chrome进程不会退出, 导致后台累计了几十个chrome进程

1. 目前只会在最后才进行 Chrome 的清理。测试过超时调用 go-rod 的清理，docker 中无效， Windows 下调试没得问题。见测试代码，https://github.com/allanpk716/ChineseSubFinder/blob/master/TestCode/test_timeout_test.go

2. 考虑到用户可能设置多线程，所以不会在出错后马上清理。也不是不能做，就是逻辑会复杂一些，暂时不打算改动。
