### ISSUE TITLE
同样电影windows版都能下载，docker一个都不行

### ISSUE THREAD

**Issue by samzzzz** [allanpk716/ChineseSubFinder#55]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.16.0

环境: docker or Window
## 你遇到什么问题了？

Window可以正常下载，docker就不行

## 你的问题弄重现嘛？

能够重现

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

[INFO]: 2021-09-22 14:19:24 - ChineseSubFinder Version: v0.16.0
[INFO]: 2021-09-22 14:19:24 - MovieFolder: /media/movie
[INFO]: 2021-09-22 14:19:24 - SeriesFolder: /media/tv
[INFO]: 2021-09-22 14:19:24 - HotFix Start...
[INFO]: 2021-09-22 14:19:24 - HotFix End
[INFO]: 2021-09-22 14:19:24 - Change Sub Name Format Start...
[INFO]: 2021-09-22 14:19:24 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-09-22 14:19:24 - Change Sub Name Format End
[INFO]: 2021-09-22 14:19:24 - ReloadBrowser Start...
[INFO]: 2021-09-22 14:19:25 - ReloadBrowser End
[INFO]: 2021-09-22 14:19:25 - First Time Download Start
[INFO]: 2021-09-22 14:19:25 - Download One Started...
[INFO]: 2021-09-22 14:19:25 - Download Movie Sub Started...
[WARNING]: 2021-09-22 14:19:25 - SkipChineseMovie /media/movie/Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH/Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH.mkv can not find IMDB Id
[ERROR]: 2021-09-22 14:19:26 - MovieNeedDlSub.GetImdbInfo4Movie can not find IMDB Id
[INFO]: 2021-09-22 14:19:26 - 1 DlSub Start /media/movie/Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH/Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH.mkv
[INFO]: 2021-09-22 14:19:26 - 1 shooter Start...
[INFO]: 2021-09-22 14:19:26 - 1 subhd Start...
[INFO]: 2021-09-22 14:19:26 - 1 zimuku Start...
[INFO]: 2021-09-22 14:19:26 - 1 xunlei Start...
[ERROR]: 2021-09-22 14:19:26 - model.GetImdbInfo can not find IMDB Id
[ERROR]: 2021-09-22 14:19:26 - VideoNameSearchKeywordMaker year to int strconv.Atoi: parsing "": invalid syntax
[ERROR]: 2021-09-22 14:19:26 - model.GetImdbInfo can not find IMDB Id
[ERROR]: 2021-09-22 14:19:26 - VideoNameSearchKeywordMaker year to int strconv.Atoi: parsing "": invalid syntax
[ERROR]: 2021-09-22 14:19:26 - subhd keyword: Black Widow
[INFO]: 2021-09-22 14:19:26 - 1 subhd End...
[ERROR]: 2021-09-22 14:19:26 - 1 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:26 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:19:26 - 1 xunlei End...
[ERROR]: 2021-09-22 14:19:26 - 1 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/15326BCF6AD5846342A593685FFB00EB2E7D8CFE.json": dial tcp 101.132.109.27:8000: connect: connection refused
[INFO]: 2021-09-22 14:19:26 - 1 shooter End...
[ERROR]: 2021-09-22 14:19:26 - 1 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.36:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:26 - zimuku keyword: Black Widow
[INFO]: 2021-09-22 14:19:26 - 1 zimuku End...
[ERROR]: 2021-09-22 14:19:26 - 1 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Black+Widow": dial tcp 104.21.74.105:443: connect: connection refused
[INFO]: 2021-09-22 14:19:26 - 1 DlSub End /media/movie/Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH/Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH.mkv
[INFO]: 2021-09-22 14:19:26 - no sub found Black.Widow.2021.2160p.UHD.BluRay.x265-MVLBITCH.mkv
[INFO]: 2021-09-22 14:19:33 - 0 DlSub Start /media/movie/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM.mkv
[INFO]: 2021-09-22 14:19:33 - 0 shooter Start...
[INFO]: 2021-09-22 14:19:33 - 0 zimuku Start...
[INFO]: 2021-09-22 14:19:33 - 0 xunlei Start...
[INFO]: 2021-09-22 14:19:33 - 0 subhd Start...
[ERROR]: 2021-09-22 14:19:33 - subhd keyword: tt12885852
[ERROR]: 2021-09-22 14:19:33 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM.mkv Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:33 - subhd keyword: Batman Soul of the Dragon 2021
[INFO]: 2021-09-22 14:19:33 - 0 subhd End...
[ERROR]: 2021-09-22 14:19:33 - 0 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:33 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:19:33 - 0 xunlei End...
[ERROR]: 2021-09-22 14:19:33 - 0 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/EC08E5ABBC7B582DA35EF9705556BAB6859389A7.json": dial tcp 106.14.221.44:8000: connect: connection refused
[INFO]: 2021-09-22 14:19:33 - 0 shooter End...
[ERROR]: 2021-09-22 14:19:33 - 0 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.32:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:33 - zimuku keyword: tt12885852
[ERROR]: 2021-09-22 14:19:33 - getSubListFromKeyword IMDBID can not found sub /media/movie/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM.mkv Get "https://zmk.pw/search?q=tt12885852": dial tcp 104.21.74.105:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:34 - zimuku keyword: Batman Soul of the Dragon 2021
[INFO]: 2021-09-22 14:19:34 - 0 zimuku End...
[ERROR]: 2021-09-22 14:19:34 - 0 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Batman+Soul+of+the+Dragon+2021": dial tcp 104.21.74.105:443: connect: connection refused
[INFO]: 2021-09-22 14:19:34 - 0 DlSub End /media/movie/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM/Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM.mkv
[INFO]: 2021-09-22 14:19:34 - no sub found Batman.Soul.of.the.Dragon.2021.1080p.WEBRip.DDP5.1.x264-CM.mkv
[WARNING]: 2021-09-22 14:19:35 - IsSubHasChinese.DetermineFileTypeFromFile /media/movie/Honest.Thief.2020.720p.BluRay.x264-PiGNUS[rarbg]/honest.thief.2020.720p.bluray.x264-pignus.zh.ass can not matching any sub type
[INFO]: 2021-09-22 14:19:35 - Skip honest.thief.2020.720p.bluray.x264-pignus.mkv Sub Download, because movie has sub and downloaded or aired more than 3 months
[INFO]: 2021-09-22 14:19:40 - 3 DlSub Start /media/movie/Horizon.Line.2020.1080p.WEBRip.x264-RARBG/Horizon.Line.2020.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:19:40 - 3 zimuku Start...
[INFO]: 2021-09-22 14:19:40 - 3 xunlei Start...
[INFO]: 2021-09-22 14:19:40 - 3 subhd Start...
[INFO]: 2021-09-22 14:19:40 - 3 shooter Start...
[ERROR]: 2021-09-22 14:19:40 - subhd keyword: tt5498354
[ERROR]: 2021-09-22 14:19:40 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Horizon.Line.2020.1080p.WEBRip.x264-RARBG/Horizon.Line.2020.1080p.WEBRip.x264-RARBG.mp4 Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:40 - subhd keyword: Horizon 2020
[INFO]: 2021-09-22 14:19:40 - 3 subhd End...
[ERROR]: 2021-09-22 14:19:40 - 3 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:40 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:19:40 - 3 xunlei End...
[ERROR]: 2021-09-22 14:19:40 - 3 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/03707D6B653BF500672837C74C488D591DEE1286.json": dial tcp 101.132.109.27:8000: connect: connection refused
[INFO]: 2021-09-22 14:19:40 - 3 shooter End...
[ERROR]: 2021-09-22 14:19:40 - 3 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.36:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:41 - zimuku keyword: tt5498354
[ERROR]: 2021-09-22 14:19:41 - getSubListFromKeyword IMDBID can not found sub /media/movie/Horizon.Line.2020.1080p.WEBRip.x264-RARBG/Horizon.Line.2020.1080p.WEBRip.x264-RARBG.mp4 Get "https://zmk.pw/search?q=tt5498354": dial tcp 104.21.74.105:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:41 - zimuku keyword: Horizon 2020
[INFO]: 2021-09-22 14:19:41 - 3 zimuku End...
[ERROR]: 2021-09-22 14:19:41 - 3 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Horizon+2020": dial tcp 104.21.74.105:443: connect: connection refused
[INFO]: 2021-09-22 14:19:41 - 3 DlSub End /media/movie/Horizon.Line.2020.1080p.WEBRip.x264-RARBG/Horizon.Line.2020.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:19:41 - no sub found Horizon.Line.2020.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:19:43 - 4 DlSub Start /media/movie/Mulan.2020.1080p.WEBRip.x264-RARBG/Mulan.2020.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:19:43 - 4 shooter Start...
[INFO]: 2021-09-22 14:19:43 - 4 subhd Start...
[INFO]: 2021-09-22 14:19:43 - 4 zimuku Start...
[INFO]: 2021-09-22 14:19:43 - 4 xunlei Start...
[ERROR]: 2021-09-22 14:19:43 - subhd keyword: tt4566758
[ERROR]: 2021-09-22 14:19:43 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Mulan.2020.1080p.WEBRip.x264-RARBG/Mulan.2020.1080p.WEBRip.x264-RARBG.mp4 Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:43 - subhd keyword: Mulan 2020
[INFO]: 2021-09-22 14:19:43 - 4 subhd End...
[ERROR]: 2021-09-22 14:19:43 - 4 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:43 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:19:43 - 4 xunlei End...
[ERROR]: 2021-09-22 14:19:43 - 4 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/6DEE51E1F9FA261105B8C46613A4C54FC93FC0BB.json": dial tcp 106.14.221.44:8000: connect: connection refused
[INFO]: 2021-09-22 14:19:43 - 4 shooter End...
[ERROR]: 2021-09-22 14:19:43 - 4 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.37:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:44 - zimuku keyword: tt4566758
[ERROR]: 2021-09-22 14:19:44 - getSubListFromKeyword IMDBID can not found sub /media/movie/Mulan.2020.1080p.WEBRip.x264-RARBG/Mulan.2020.1080p.WEBRip.x264-RARBG.mp4 Get "https://zmk.pw/search?q=tt4566758": dial tcp 104.21.74.105:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:44 - zimuku keyword: Mulan 2020
[INFO]: 2021-09-22 14:19:44 - 4 zimuku End...
[ERROR]: 2021-09-22 14:19:44 - 4 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Mulan+2020": dial tcp 104.21.74.105:443: connect: connection refused
[INFO]: 2021-09-22 14:19:44 - 4 DlSub End /media/movie/Mulan.2020.1080p.WEBRip.x264-RARBG/Mulan.2020.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:19:44 - no sub found Mulan.2020.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:19:48 - 5 DlSub Start /media/movie/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP.mkv
[INFO]: 2021-09-22 14:19:48 - 5 zimuku Start...
[INFO]: 2021-09-22 14:19:48 - 5 shooter Start...
[INFO]: 2021-09-22 14:19:48 - 5 xunlei Start...
[INFO]: 2021-09-22 14:19:48 - 5 subhd Start...
[ERROR]: 2021-09-22 14:19:48 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:19:48 - 5 xunlei End...
[ERROR]: 2021-09-22 14:19:48 - 5 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/F143012AFE3DB1C25A8FAEAA6C55F14B0E23DE4C.json": dial tcp 101.132.109.27:8000: connect: connection refused
[ERROR]: 2021-09-22 14:19:48 - subhd keyword: tt9620292
[ERROR]: 2021-09-22 14:19:48 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP.mkv Get "": unsupported protocol scheme ""
[INFO]: 2021-09-22 14:19:48 - 5 shooter End...
[ERROR]: 2021-09-22 14:19:48 - 5 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.40:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:48 - subhd keyword: Promising Young Woman 2020
[INFO]: 2021-09-22 14:19:48 - 5 subhd End...
[ERROR]: 2021-09-22 14:19:48 - 5 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:19:49 - zimuku keyword: tt9620292
[ERROR]: 2021-09-22 14:19:49 - getSubListFromKeyword IMDBID can not found sub /media/movie/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP.mkv Get "https://zmk.pw/search?q=tt9620292": dial tcp 104.21.74.105:443: connect: connection refused
[ERROR]: 2021-09-22 14:19:49 - zimuku keyword: Promising Young Woman 2020
[INFO]: 2021-09-22 14:19:49 - 5 zimuku End...
[ERROR]: 2021-09-22 14:19:49 - 5 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Promising+Young+Woman+2020": dial tcp 104.21.74.105:443: connect: connection refused
[INFO]: 2021-09-22 14:19:49 - 5 DlSub End /media/movie/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP/Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP.mkv
[INFO]: 2021-09-22 14:19:49 - no sub found Promising.Young.Woman.2020.720p.WEBSCR.DD2.0.x264-NOGRP.mkv
[INFO]: 2021-09-22 14:20:08 - 6 DlSub Start /media/movie/Redemption.Day.2021.1080p.WEBRip.x264-RARBG/Redemption.Day.2021.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:20:08 - 6 shooter Start...
[INFO]: 2021-09-22 14:20:08 - 6 xunlei Start...
[INFO]: 2021-09-22 14:20:08 - 6 subhd Start...
[INFO]: 2021-09-22 14:20:08 - 6 zimuku Start...
[INFO]: 2021-09-22 14:20:08 - 7 DlSub Start /media/movie/Run.2020.1080p.BluRay.x265-RARBG/Run.2020.1080p.BluRay.x265-RARBG.mp4
[INFO]: 2021-09-22 14:20:08 - 7 shooter Start...
[INFO]: 2021-09-22 14:20:08 - 7 zimuku Start...
[INFO]: 2021-09-22 14:20:08 - 7 subhd Start...
[INFO]: 2021-09-22 14:20:08 - 7 xunlei Start...
[ERROR]: 2021-09-22 14:20:08 - subhd keyword: tt4439620
[ERROR]: 2021-09-22 14:20:08 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Redemption.Day.2021.1080p.WEBRip.x264-RARBG/Redemption.Day.2021.1080p.WEBRip.x264-RARBG.mp4 Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:08 - subhd keyword: Redemption Day 2021
[INFO]: 2021-09-22 14:20:08 - 6 subhd End...
[ERROR]: 2021-09-22 14:20:08 - 6 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:08 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:20:08 - 6 xunlei End...
[ERROR]: 2021-09-22 14:20:08 - 6 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/DD7188EE5B4CB62121642128BB8684140B01F4EC.json": dial tcp 106.14.221.44:8000: connect: connection refused
[INFO]: 2021-09-22 14:20:08 - 6 shooter End...
[ERROR]: 2021-09-22 14:20:08 - 6 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.25:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:08 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:20:08 - 7 xunlei End...
[ERROR]: 2021-09-22 14:20:08 - 7 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/930B6B08C086ACCB55D1B85004977BAF1CC73F95.json": dial tcp 101.132.109.27:8000: connect: connection refused
[INFO]: 2021-09-22 14:20:08 - 7 shooter End...
[ERROR]: 2021-09-22 14:20:08 - 7 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.26:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:08 - subhd keyword: tt8633478
[ERROR]: 2021-09-22 14:20:08 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Run.2020.1080p.BluRay.x265-RARBG/Run.2020.1080p.BluRay.x265-RARBG.mp4 Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:08 - subhd keyword: Run 2020
[INFO]: 2021-09-22 14:20:08 - 7 subhd End...
[ERROR]: 2021-09-22 14:20:08 - 7 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:08 - zimuku keyword: tt4439620
[ERROR]: 2021-09-22 14:20:08 - getSubListFromKeyword IMDBID can not found sub /media/movie/Redemption.Day.2021.1080p.WEBRip.x264-RARBG/Redemption.Day.2021.1080p.WEBRip.x264-RARBG.mp4 Get "https://zmk.pw/search?q=tt4439620": dial tcp 104.21.74.105:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:09 - zimuku keyword: tt8633478
[ERROR]: 2021-09-22 14:20:09 - getSubListFromKeyword IMDBID can not found sub /media/movie/Run.2020.1080p.BluRay.x265-RARBG/Run.2020.1080p.BluRay.x265-RARBG.mp4 Get "https://zmk.pw/search?q=tt8633478": dial tcp 104.21.74.105:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:09 - zimuku keyword: Redemption Day 2021
[INFO]: 2021-09-22 14:20:09 - 6 zimuku End...
[ERROR]: 2021-09-22 14:20:09 - 6 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Redemption+Day+2021": dial tcp 104.21.74.105:443: connect: connection refused
[INFO]: 2021-09-22 14:20:09 - 6 DlSub End /media/movie/Redemption.Day.2021.1080p.WEBRip.x264-RARBG/Redemption.Day.2021.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:20:09 - no sub found Redemption.Day.2021.1080p.WEBRip.x264-RARBG.mp4
[ERROR]: 2021-09-22 14:20:09 - zimuku keyword: Run 2020
[INFO]: 2021-09-22 14:20:09 - 7 zimuku End...
[ERROR]: 2021-09-22 14:20:09 - 7 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Run+2020": dial tcp 172.67.157.51:443: connect: connection refused
[INFO]: 2021-09-22 14:20:09 - 7 DlSub End /media/movie/Run.2020.1080p.BluRay.x265-RARBG/Run.2020.1080p.BluRay.x265-RARBG.mp4
[INFO]: 2021-09-22 14:20:09 - no sub found Run.2020.1080p.BluRay.x265-RARBG.mp4
[WARNING]: 2021-09-22 14:20:10 - SkipChineseMovie /media/movie/The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT[rarbg]/The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT.mkv can not find IMDB Id
[ERROR]: 2021-09-22 14:20:10 - MovieNeedDlSub.GetImdbInfo4Movie can not find IMDB Id
[INFO]: 2021-09-22 14:20:10 - 9 DlSub Start /media/movie/The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT[rarbg]/The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT.mkv
[INFO]: 2021-09-22 14:20:10 - 9 zimuku Start...
[INFO]: 2021-09-22 14:20:10 - 9 shooter Start...
[INFO]: 2021-09-22 14:20:10 - 9 subhd Start...
[INFO]: 2021-09-22 14:20:10 - 9 xunlei Start...
[ERROR]: 2021-09-22 14:20:10 - model.GetImdbInfo can not find IMDB Id
[ERROR]: 2021-09-22 14:20:10 - VideoNameSearchKeywordMaker year to int strconv.Atoi: parsing "": invalid syntax
[ERROR]: 2021-09-22 14:20:10 - model.GetImdbInfo can not find IMDB Id
[ERROR]: 2021-09-22 14:20:10 - VideoNameSearchKeywordMaker year to int strconv.Atoi: parsing "": invalid syntax
[ERROR]: 2021-09-22 14:20:10 - subhd keyword: The Suicide Squad
[INFO]: 2021-09-22 14:20:10 - 9 subhd End...
[ERROR]: 2021-09-22 14:20:10 - 9 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:10 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:20:10 - 9 xunlei End...
[ERROR]: 2021-09-22 14:20:10 - 9 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/E985A03C580ADBCC53F2366AF4B1A011EE1F2002.json": dial tcp 106.14.221.44:8000: connect: connection refused
[INFO]: 2021-09-22 14:20:10 - 9 shooter End...
[ERROR]: 2021-09-22 14:20:10 - 9 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.27:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:10 - zimuku keyword: The Suicide Squad
[INFO]: 2021-09-22 14:20:10 - 9 zimuku End...
[ERROR]: 2021-09-22 14:20:10 - 9 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=The+Suicide+Squad": dial tcp 172.67.157.51:443: connect: connection refused
[INFO]: 2021-09-22 14:20:10 - 9 DlSub End /media/movie/The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT[rarbg]/The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT.mkv
[INFO]: 2021-09-22 14:20:10 - no sub found The.Suicide.Squad.2021.720p.WEB.H264-TIMECUT.mkv
[INFO]: 2021-09-22 14:20:43 - 8 DlSub Start /media/movie/Synchronic.2019.1080p.WEBRip.x264-RARBG/Synchronic.2019.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:20:43 - 8 shooter Start...
[INFO]: 2021-09-22 14:20:43 - 8 zimuku Start...
[INFO]: 2021-09-22 14:20:43 - 8 subhd Start...
[INFO]: 2021-09-22 14:20:43 - 8 xunlei Start...
[ERROR]: 2021-09-22 14:20:43 - subhd keyword: tt9016974
[ERROR]: 2021-09-22 14:20:43 - getSubListFromKeyword4Movie IMDBID can not found sub /media/movie/Synchronic.2019.1080p.WEBRip.x264-RARBG/Synchronic.2019.1080p.WEBRip.x264-RARBG.mp4 Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:43 - subhd keyword: Synchronic 2020
[INFO]: 2021-09-22 14:20:43 - 8 subhd End...
[ERROR]: 2021-09-22 14:20:43 - 8 subhd oneMovieDlSubInOneSite Get "": unsupported protocol scheme ""
[ERROR]: 2021-09-22 14:20:43 - xunlei NewHttpClient: 
[INFO]: 2021-09-22 14:20:43 - 8 xunlei End...
[ERROR]: 2021-09-22 14:20:43 - 8 xunlei oneMovieDlSubInOneSite Get "http://sub.xmp.sandai.net:8000/subxl/DE6B129D7C7B0FA91C10107B0E897E830AD87E70.json": dial tcp 101.132.109.27:8000: connect: connection refused
[INFO]: 2021-09-22 14:20:43 - 8 shooter End...
[ERROR]: 2021-09-22 14:20:43 - 8 shooter oneMovieDlSubInOneSite Post "https://www.shooter.cn/api/subapi.php": dial tcp 60.28.226.40:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:43 - zimuku keyword: tt9016974
[ERROR]: 2021-09-22 14:20:43 - getSubListFromKeyword IMDBID can not found sub /media/movie/Synchronic.2019.1080p.WEBRip.x264-RARBG/Synchronic.2019.1080p.WEBRip.x264-RARBG.mp4 Get "https://zmk.pw/search?q=tt9016974": dial tcp 172.67.157.51:443: connect: connection refused
[ERROR]: 2021-09-22 14:20:46 - zimuku keyword: Synchronic 2020
[INFO]: 2021-09-22 14:20:46 - 8 zimuku End...
[ERROR]: 2021-09-22 14:20:46 - 8 zimuku oneMovieDlSubInOneSite Get "https://zmk.pw/search?q=Synchronic+2020": dial tcp 172.67.157.51:443: connect: connection refused
[INFO]: 2021-09-22 14:20:46 - 8 DlSub End /media/movie/Synchronic.2019.1080p.WEBRip.x264-RARBG/Synchronic.2019.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:20:46 - no sub found Synchronic.2019.1080p.WEBRip.x264-RARBG.mp4
[INFO]: 2021-09-22 14:20:46 - Download Movie Sub End...
[INFO]: 2021-09-22 14:20:46 - Download Series Sub Started...
[WARNING]: 2021-09-22 14:20:46 - SkipChineseSeries /media/tv/Shameless.US.S10.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] no metadata file, movie.xml or *.nfo
[ERROR]: 2021-09-22 14:20:46 - subSupplierHub.DownloadSub4Series /media/tv/Shameless.US.S10.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] ReadSeriesInfoFromDir /media/tv/Shameless.US.S10.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] no metadata file, movie.xml or *.nfo
[ERROR]: 2021-09-22 14:20:46 - DownloadSub4Series.NewPoolWithFunc done with Error ReadSeriesInfoFromDir /media/tv/Shameless.US.S10.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] no metadata file, movie.xml or *.nfo
[INFO]: 2021-09-22 14:20:46 - Download Series Sub End...
[INFO]: 2021-09-22 14:20:46 - Download One End...
[ERROR]: 2021-09-22 14:20:46 - CloseChrome exit status 1
[INFO]: 2021-09-22 14:20:46 - First Time Download End

**Comment by allanpk716** [comment]
感觉是代理设置问题，需要贴 config.xml 文件出来

**Comment by samzzzz** [comment]
没找到config.xml 
是config.yaml么？


```
UseProxy: false
HttpProxy: http://127.0.0.1:10809
EveryTime: 12h
Threads: 2
RunAtStartup: true
MovieFolder: /media/movie
SeriesFolder: /media/tv
```

**Comment by allanpk716** [comment]
> 没找到config.xml
> 是config.yaml么？
> 
> ```
> UseProxy: false
> HttpProxy: http://127.0.0.1:10809
> EveryTime: 12h
> Threads: 2
> RunAtStartup: true
> MovieFolder: /media/movie
> SeriesFolder: /media/tv
> ```

配置没看出问题，应该还是你使用环境的网络问题

**Comment by samzzzz** [comment]
查不出原因，同网络下电脑版就没有问题，N1 openwrt docker下就不行

**Comment by allanpk716** [comment]
看错误是国内迅雷的接口访问都有问题，因为没有在类似的 N1 openwrt docker 环境下测试，没有很好办法帮你定位网络问题。

## pic
![image](https://user-images.githubusercontent.com/1176000/134763644-354e8fd4-3626-46ec-a3bd-d08643d1f1e4.png)
