### ISSUE TITLE
字幕下载过程中发生 TMDB 相关错误

### ISSUE THREAD

**Issue by SteinX** [allanpk716/ChineseSubFinder#555]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.43.2
>
>
> 在程序运行日志头部或者 Web UI 可以看到

docker

## 你遇到什么问题了？

> 描述一下你遇到的问题

下载字幕出现如下错误信息: 
`seriesDlFunc.ReadSeriesInfoFromDir, Error: id type is not supported: tmdb` 

怀疑和 tmdb api 调用失败有关，但和 API 的连通性无关，已通过连通性测试

## 你的问题弄重现嘛？

必现

## 你期望的结果

能够正常下载字幕

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
  "SpeedDevMode": false,
  "user_info": {
    "username": "xxxxx",
    "password": "xxxxx"
  },
  "common_settings": {
    "interval_or_assign_or_custom": 0,
    "scan_interval": "@every 6h",
    "threads": 3,
    "run_scan_at_start_up": false,
    "movie_paths": [
      "/media/rr/Movies",
      "/media/nts/Movies"
    ],
    "series_paths": [
      "/media/rr/Shows",
      "/media/nts/Shows"
    ],
    "local_static_file_port": "19037"
  },
  "subtitle_sources": {
    "assrt_settings": {
      "enabled": true,
      "token": "xxxxxxxxx"
    }
  },
  "advanced_settings": {
    "proxy_settings": {
      "use_proxy": false,
      "use_which_proxy_protocol": "http",
      "local_http_proxy_server_port": "19036",
      "input_proxy_address": "127.0.0.1",
      "input_proxy_port": "10809",
      "need_pwd": false,
      "input_proxy_username": "",
      "input_proxy_password": ""
    },
    "tmdb_api_settings": {
      "enable": true,
      "api_key": "my_token_here"
    },
    "debug_mode": false,
    "save_full_season_tmp_subtitles": true,
    "sub_type_priority": 0,
    "sub_name_formatter": 1,
    "save_multi_sub": true,
    "custom_video_exts": [

    ],
    "fix_time_line": true,
    "topic": 1,
    "suppliers_settings": {
      "csf": {
        "name": "csf",
        "root_url": "haha",
        "search_url": "haha",
        "daily_download_limit": -1
      },
      "xunlei": {
        "name": "xunlei",
        "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
        "search_url": "",
        "daily_download_limit": -1
      },
      "shooter": {
        "name": "shooter",
        "root_url": "https://www.shooter.cn/api/subapi.php",
        "search_url": "",
        "daily_download_limit": -1
      },
      "subhd": {
        "name": "subhd",
        "root_url": "https://subhd.tv",
        "search_url": "/search/%s",
        "daily_download_limit": 20
      },
      "zimuku": {
        "name": "zimuku",
        "root_url": "https://zimuku.org",
        "search_url": "/search?q=%s",
        "daily_download_limit": 20
      },
      "assrt": {
        "name": "assrt",
        "root_url": "https://api.assrt.net/v1",
        "search_url": "",
        "daily_download_limit": -1
      },
      "a4k": {
        "name": "a4k",
        "root_url": "https://www.a4k.net",
        "search_url": "/search?term=",
        "daily_download_limit": -1
      }
    },
    "scan_logic": {
      "skip_chinese_movie": false,
      "skip_chinese_series": false
    },
    "task_queue": {
      "max_retry_times": 3,
      "one_job_time_out": 300,
      "interval": 10,
      "expiration_time": 90,
      "download_sub_during_x_days": 7,
      "one_sub_download_interval": 12,
      "check_pulic_ip_target_site": ""
    },
    "download_file_cache": {
      "ttl": 4320,
      "unit": "hour"
    }
  },
  "emby_settings": {
    "enable": false,
    "address_url": "http://192.168.2.202:8096",
    "api_key": "xxxxxxxx",
    "max_request_video_number": 500,
    "skip_watched": false,
    "movie_paths_mapping": {
      "/media/nts/Movies": "",
      "/media/rr/Movies": ""
    },
    "series_paths_mapping": {
      "/media/nts/Shows": "",
      "/media/rr/Shows": ""
    },
    "auto_or_manual": false,
    "threads": 3
  },
  "developer_settings": {
    "enable": false,
    "bark_server_address": ""
  },
  "timeline_fixer_settings": {
    "max_offset_time": 120,
    "min_offset": 0.1
  },
  "experimental_function": {
    "auto_change_sub_encode": {
      "enable": false,
      "des_encode_type": 0
    },
    "chs_cht_changer": {
      "enable": false,
      "des_chinese_language_type": 0
    },
    "remote_chrome_settings": {
      "enable": false,
      "remote_docker_url": "",
      "remote_adblock_path": "",
      "remote_user_data_dir": ""
    },
    "api_key_settings": {
      "enabled": true,
      "key": "xxxxxxx"
    },
    "local_chrome_settings": {
      "enabled": false,
      "local_chrome_exe_f_path": ""
    },
    "share_sub_settings": {
      "share_sub_enabled": true
    },
    "extend_log": {
      "SysLog": {
        "enable": false,
        "network": "",
        "address": "",
        "priority": 0,
        "tag": ""
      }
    }
  }
}
```

## 如果是使用 Docker，请给出对应的配置信息

和 docker 配置无关

## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中

[ChineseSubFinder--202211190000--.log](https://github.com/allanpk716/ChineseSubFinder/files/10046713/ChineseSubFinder--202211190000--.log)

**Comment by allanpk716** [comment]
你需要看你这个连续剧的 TMDB 是什么，正常来说是 int64 的数值。

**Comment by SteinX** [comment]
这个是我用 sonarr 刮削的剧集的 nfo，出现了 
`SeriesNeedDlSub ReadSeriesInfoFromDir xxxxxxx id type is not supported: tmdb` 错误，这个是对应的剧集 nfo 文件，希望有助于排查问题

[nfos.zip](https://github.com/allanpk716/ChineseSubFinder/files/10076353/nfos.zip)

**Comment by SteinX** [comment]
另外一个例子是用 nas-tools 刮削的剧集也出了点问题，但错误信息稍微有点不一样
`GetIMDBInfoFromVideoNfoInfo,IMDB:  /media/nts/Shows/静雪 (2022) id type is not supported: tmdb`

[nts_nfos.zip](https://github.com/allanpk716/ChineseSubFinder/files/10076383/nts_nfos.zip)

**Comment by allanpk716** [comment]
推送了 v0.44.2 你试试

**Comment by SteinX** [comment]
> 推送了 v0.44.2 你试试

感谢大佬的及时修复，现在 sonarr 的这个问题修好了


> 这个是我用 sonarr 刮削的剧集的 nfo，出现了 `SeriesNeedDlSub ReadSeriesInfoFromDir xxxxxxx id type is not supported: tmdb` 错误，这个是对应的剧集 nfo 文件，希望有助于排查问题
> 
> [nfos.zip](https://github.com/allanpk716/ChineseSubFinder/files/10076353/nfos.zip)

可是使用 nas-tools 刮削的剧集还是有点问题

> 另外一个例子是用 nas-tools 刮削的剧集也出了点问题，但错误信息稍微有点不一样 `GetIMDBInfoFromVideoNfoInfo,IMDB: /media/nts/Shows/静雪 (2022) id type is not supported: tmdb`
> 
> [nts_nfos.zip](https://github.com/allanpk716/ChineseSubFinder/files/10076383/nts_nfos.zip)

更新一张新的错误信息的截图:
<img width="834" alt="截屏2022-11-24 22 38 34" src="https://user-images.githubusercontent.com/3668417/203810630-a320150c-7a93-48c2-8bf2-ae6c56d9ea2a.png">

**Comment by allanpk716** [comment]
这个 ID 找不到资源

**Comment by SteinX** [comment]
好的，那我没什么问题了
