### ISSUE TITLE
过滤器屏蔽小文件，导致软链接形式的媒体文件也无法被识别

### ISSUE THREAD

**Issue by muztag** [allanpk716/ChineseSubFinder#558]
下列代码在屏蔽小文件的同时，也屏蔽了软链接形式的媒体文件，而对于PT下载用户来说，使用软链接是有必要的。
建议此处使用is_symlink方法进行判断

https://github.com/allanpk716/ChineseSubFinder/blob/1760f600d19b338e2ef221dbaf4e6105f0180a84/pkg/filter/filter.go#L19-L22

**Comment by muztag** [comment]
> 手头没有测试条件，找了些资料，是否可以这样判断？或者说你是否可以执行 go 的代码简单判断下这样的代码是否能够判断是否是软连接。
> 
> * https://stackoverflow.com/questions/31888955/check-whether-a-file-is-a-hard-link
> * https://blog.csdn.net/weixin_34240657/article/details/93070693
> 
> 如果ok，我就可以修复这个问题。


经测试，第二个代码可用。第一个代码是测试硬链接的，不适用。

**Comment by allanpk716** [comment]
1. 软连接的话 go 默认的文件打开方法能正确读取嘛？直接可以读取到真实文件的数据，比如： `os.Open` 函数
2. 如果你是使用 docker，你映射的资源都是软连接的，但是没有把真实文件目录映射进容器，那么使用 `filepath.EvalSymlinks` 或者 [os.Readlink](http://golang.org/pkg/os/#Readlink) 能得到正确的映射后的路径嘛? ps:https://stackoverflow.com/questions/18062026/resolve-symlinks-in-go

如果 1 直接可以从软连接读取到真实文件的数据，那么就没得 2 的问题。

不然就需要考虑 2 的问题，如果也能够解决，然后就需要把项目中所有的文件读取的部分重构才能够支持软连接。

如果 2 确实是个问题，那么就需要考虑类似你这样情况的用户怎么去做映射配置才能够正确使用该方法，而且不能够复杂，否则可能又是一个能用，但是没几个人能弄清楚的功能。

**Comment by muztag** [comment]
> 1. 软连接的话 go 默认的文件打开方法能正确读取嘛？直接可以读取到真实文件的数据，比如： `os.Open` 函数
> 2. 如果你是使用 docker，你映射的资源都是软连接的，但是没有把真实文件目录映射进容器，那么使用 `filepath.EvalSymlinks` 或者 [os.Readlink](http://golang.org/pkg/os/#Readlink) 能得到正确的映射后的路径嘛? ps:https://stackoverflow.com/questions/18062026/resolve-symlinks-in-go
> 
> 如果 1 直接可以从软连接读取到真实文件的数据，那么就没得 2 的问题。
> 
> 不然就需要考虑 2 的问题，如果也能够解决，然后就需要把项目中所有的文件读取的部分重构才能够支持软连接。
> 
> 如果 2 确实是个问题，那么就需要考虑类似你这样情况的用户怎么去做映射配置才能够正确使用该方法，而且不能够复杂，否则可能又是一个能用，但是没几个人能弄清楚的功能。

经测试，使用 `os.Open` 方法打开一个软链接，实际上是打开真实文件。因此，将软链接文件按照现有逻辑操作，预期不会有问题。

**Comment by allanpk716** [comment]
推送了 v0.45-Beta0 你先试试

**Comment by muztag** [comment]
> 推送了 v0.45-Beta0 你先试试

经测试可用，问题解决。
