### ISSUE TITLE
SeriesFolder not found

### ISSUE THREAD

**Issue by chyaww** [allanpk716/ChineseSubFinder#58]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: 2021/09/25 22：00 latest

环境: 群晖docker 

视频的目录: /wd/电影，此文件夹下有50多部电影，如/volume5/wd/电影/Anna.2019.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT/Anna.2019.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT.mkv
docker文件夹映射的是  /wd/电影:/media/电影       或者     /wd:/media， 或者 /wd/电影:/media 都是一样的报错
config.yaml 里的 MovieFolder: /media/电影

## 出错的日志信息可以复制一些出来吗？

[INFO]: 2021-09-25 22:23:17 - ChineseSubFinder Version: v0.17.1
[INFO]: 2021-09-25 22:23:17 - UseProxy: http://192.168.1.100:7890
[INFO]: 2021-09-25 22:23:18 - ProxyTest Target Site http://google.com Speed: 531 Status: 200
[ERROR]: 2021-09-25 22:23:18 - SeriesFolder not found
[INFO]: 2021-09-25 22:23:18 - ChineseSubFinder Version: v0.17.1

**Comment by allanpk716** [comment]
需要把 config.yaml 文件发上来看看。以及，[连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

**Comment by chyaww** [comment]
找到原因了，media文件夹下面必须有“电影”和“连续剧”两个文件夹，我映射的是wd/电影：media，实际所有电影应该放在 wd/电影/电影，感觉这个文件夹映射搞的有点复杂了

**Comment by allanpk716** [comment]
> 找到原因了，media文件夹下面必须有“电影”和“连续剧”两个文件夹，我映射的是wd/电影：media，实际所有电影应该放在 wd/电影/电影，感觉这个文件夹映射搞的有点复杂了

嗯，我更新下文档描述下
