### ISSUE TITLE
Docker出現Error訊息

### ISSUE THREAD

**Issue by xiNeRoar** [allanpk716/ChineseSubFinder#59]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.17.1

环境: docker on synology Nas

## 你遇到什么问题了？

出現ERROR訊息

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

沒有ERROR

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs

![image](https://user-images.githubusercontent.com/66216186/134776313-f85266eb-095a-40fe-88f0-9b7200407143.png)
![image](https://user-images.githubusercontent.com/66216186/134776330-845f556c-a1dd-4f11-b4bf-c03157a69423.png)
![image](https://user-images.githubusercontent.com/66216186/134776374-d5e5f381-2570-4cf9-9a4a-1cb31e15d9b0.png)

Config設定
![image](https://user-images.githubusercontent.com/66216186/134776384-c58b3cd0-90b1-4cc1-8e7c-c98c34d7be5f.png)

**Comment by xiNeRoar** [comment]
貼錯了舊的Config設定...以下才是新的
![image](https://user-images.githubusercontent.com/66216186/134776431-40e31eb8-c3cf-4f35-97b7-b92050c276aa.png)

**Comment by xiNeRoar** [comment]
我也不知道該怎麼形容....log裡面很多不同類型的ERROR 我把完整的LOG放上來給你研究 
[allanpk716-chinesesubfinder (1).csv](https://github.com/allanpk716/ChineseSubFinder/files/7230045/allanpk716-chinesesubfinder.1.csv)

**Comment by allanpk716** [comment]
运行的时候出现一些 error 有时候是正常的，大多数可能是网络问题。

比如你的日志里面：

### 日志截图1
![image](https://user-images.githubusercontent.com/1176000/134789553-d9f9b97c-9f04-4992-9ae8-d75fd5591a7e.png)

这个是一个视频的下载总调度任务超时（一个总任务包含了：xunlei、shooter、zimuku、subhd，记得好像是 5 min就超时）

### 日志截图2
![image](https://user-images.githubusercontent.com/1176000/134789579-d7aadb59-a9a6-4cc7-b3a2-f1021acf5584.png)

这个是 xunlei 下载的接口超时。

## 使用建议

先挂机一段时间，你的新下载的视频是否能够找到字幕，如果不行，再看看日志。可能这时候的 error 才是需要关注的。当然，又任务日志上体现的 error 有问题都可以问的，很可能确实是 bug。
