### ISSUE TITLE
字幕还是会重复下载

### ISSUE THREAD

**Issue by laobanbiefangcu** [allanpk716/ChineseSubFinder#60]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.17.1

环境: docker

## 你遇到什么问题了？

设置了1个小时刮削一次，新下载的剧集就会不断重复下载字幕

## 你的问题弄重现嘛？

能够重现

## 你期望的结果

只需要下载一次就够了

## 可以提供遇到问题时候，电影、连续剧的信息吗？

如下填写

视频的目录: F:\tv\Foundation (2021)\Season 1

视频的信息: Foundation (2021) - S01E01 - The Emperor's Peace WEBDL-2160p.mkv
<a href="https://sm.ms/image/FbImwiGUzvTteks" target="_blank"><img src="https://i.loli.net/2021/09/26/FbImwiGUzvTteks.png" alt="1.png"></a>
## 出错的日志信息可以复制一些出来吗？

[INFO]: 2021-09-26 12:00:21 - ChineseSubFinder Version: v0.17.1

[INFO]: 2021-09-26 12:00:21 - UseProxy = false
[INFO]: 2021-09-26 12:00:21 - MovieFolder: /media/movie
[INFO]: 2021-09-26 12:00:21 - SeriesFolder: /media/tv
[INFO]: 2021-09-26 12:00:21 - HotFix Start...
[INFO]: 2021-09-26 12:00:21 - HotFix End
[INFO]: 2021-09-26 12:00:21 - Change Sub Name Format Start...
[INFO]: 2021-09-26 12:00:21 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2021-09-26 12:00:21 - Change Sub Name Format End
[INFO]: 2021-09-26 12:00:21 - ReloadBrowser Start...
[INFO]: 2021-09-26 12:00:26 - ReloadBrowser End
[INFO]: 2021-09-26 12:00:26 - First Time Download Start
[INFO]: 2021-09-26 12:00:26 - Download One Started...
[INFO]: 2021-09-26 12:00:26 - Refresh Emby Sub List
[INFO]: 2021-09-26 12:00:27 - Download Movie Sub Started...
[INFO]: 2021-09-26 12:00:27 - Movie Sub Dl From Emby API...
[INFO]: 2021-09-26 12:00:27 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-09-26 12:00:27 - Download Movie Sub End...
[INFO]: 2021-09-26 12:00:27 - Download Series Sub Started...
[INFO]: 2021-09-26 12:00:32 - 1 DlSub Start /media/tv/Foundation (2021)
[DEBUG]: 2021-09-26 12:00:32 - Foundation IMDB ID: tt0804484 NeedDownloadSubs: 2
[DEBUG]: 2021-09-26 12:00:32 - S1E2
[DEBUG]: 2021-09-26 12:00:32 - S1E1
[INFO]: 2021-09-26 12:00:32 - 1 shooter Start...
[INFO]: 2021-09-26 12:00:32 - 1 xunlei Start...
[INFO]: 2021-09-26 12:00:32 - 1 zimuku Start...
[INFO]: 2021-09-26 12:00:32 - 1 subhd Start...
[INFO]: 2021-09-26 12:00:33 - 1 xunlei End...
[INFO]: 2021-09-26 12:00:33 - 0 DlSub Start /media/tv/Superman & Lois
[DEBUG]: 2021-09-26 12:00:33 - Superman and Lois IMDB ID: tt11192306 NeedDownloadSubs: 4
[DEBUG]: 2021-09-26 12:00:33 - S1E13
[DEBUG]: 2021-09-26 12:00:33 - S1E14
[DEBUG]: 2021-09-26 12:00:33 - S1E15
[DEBUG]: 2021-09-26 12:00:33 - S1E12
[INFO]: 2021-09-26 12:00:33 - 0 shooter Start...
[INFO]: 2021-09-26 12:00:33 - 0 zimuku Start...
[INFO]: 2021-09-26 12:00:33 - 0 subhd Start...
[INFO]: 2021-09-26 12:00:33 - 0 xunlei Start...
[INFO]: 2021-09-26 12:00:34 - 1 shooter End...
[INFO]: 2021-09-26 12:00:34 - 0 xunlei End...
[INFO]: 2021-09-26 12:00:38 - 0 shooter End...
[INFO]: 2021-09-26 12:00:43 - 1 zimuku End...
[INFO]: 2021-09-26 12:00:49 - 0 zimuku End...
[DEBUG]: 2021-09-26 12:01:10 - 對比完畢, 偏移量:232.5
[DEBUG]: 2021-09-26 12:01:13 - 對比完畢, 偏移量:205.5
[INFO]: 2021-09-26 12:01:31 - 1 subhd End...
[INFO]: 2021-09-26 12:01:31 - 1 DlSub End /media/tv/Foundation (2021)
[INFO]: 2021-09-26 12:01:32 - OrgSubName: [zimuku]_0_Foundation.S01E02.Preparing.to.Live.1080p.ATVP.WEB-DL.DDP5.1.H.264-CasStudio.简体&英文.ass
[INFO]: 2021-09-26 12:01:32 - SubDownAt: /media/tv/Foundation (2021)/Season 1/Foundation (2021) - S01E02 - Preparing to Live WEBDL-2160p.chinese(简英).default.ass
[INFO]: 2021-09-26 12:01:34 - OrgSubName: [zimuku]_1_Foundation.S01E01.The.Emperors.Peace.1080p.ATVP.WEB-DL.DDP5.1.H.264-CasStudio.简体&英文.ass
[INFO]: 2021-09-26 12:01:34 - SubDownAt: /media/tv/Foundation (2021)/Season 1/Foundation (2021) - S01E01 - The Emperor's Peace WEBDL-2160p.chinese(简英).default.ass
[DEBUG]: 2021-09-26 12:01:41 - 對比完畢, 偏移量:212.5
[INFO]: 2021-09-26 12:02:02 - 0 subhd End...
[INFO]: 2021-09-26 12:02:02 - 0 DlSub End /media/tv/Superman & Lois
[INFO]: 2021-09-26 12:02:03 - OrgSubName: [xunlei]_0_H3A5CE_S8E15.srt
[INFO]: 2021-09-26 12:02:03 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E15 - Last Sons of Krypton WEBDL-1080p.chinese(简英).default.srt
[INFO]: 2021-09-26 12:02:03 - OrgSubName: [zimuku]_2_Superman.and.Lois.S01E12.Through.the.Valley.of.Death.1080p.AMZN.WEB-DL.DDP5.1.H.264.简体&英文.ass
[INFO]: 2021-09-26 12:02:03 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E12 - Through the Valley of Death WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 12:02:04 - OrgSubName: [zimuku]_0_Superman.and.Lois.S01E13.Fail.Safe.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.简体&英文.ass
[INFO]: 2021-09-26 12:02:04 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E13 - Fail Safe WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 12:02:04 - OrgSubName: [zimuku]_1_Superman.and.Lois.S01E14.The.Eradicator.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.DivX.简体&英文.ass
[INFO]: 2021-09-26 12:02:04 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E14 - The Eradicator WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 12:02:05 - Download Series Sub End...
[INFO]: 2021-09-26 12:02:05 - Refresh Emby Sub List
[INFO]: 2021-09-26 12:02:05 - Download One End...
[INFO]: 2021-09-26 12:02:05 - First Time Download End
[INFO]: 2021-09-26 13:02:05 - Download One Started...
[INFO]: 2021-09-26 13:02:05 - Refresh Emby Sub List
[INFO]: 2021-09-26 13:02:06 - Download Movie Sub Started...
[INFO]: 2021-09-26 13:02:06 - Movie Sub Dl From Emby API...
[INFO]: 2021-09-26 13:02:06 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-09-26 13:02:06 - Download Movie Sub End...
[INFO]: 2021-09-26 13:02:06 - Download Series Sub Started...
[INFO]: 2021-09-26 13:02:09 - 0 DlSub Start /media/tv/Foundation (2021)
[DEBUG]: 2021-09-26 13:02:09 - Foundation IMDB ID: tt0804484 NeedDownloadSubs: 2
[DEBUG]: 2021-09-26 13:02:09 - S1E2
[DEBUG]: 2021-09-26 13:02:09 - S1E1
[INFO]: 2021-09-26 13:02:09 - 0 shooter Start...
[INFO]: 2021-09-26 13:02:09 - 0 subhd Start...
[INFO]: 2021-09-26 13:02:09 - 0 zimuku Start...
[INFO]: 2021-09-26 13:02:09 - 0 xunlei Start...
[INFO]: 2021-09-26 13:02:09 - 0 xunlei End...
[INFO]: 2021-09-26 13:02:10 - 0 shooter End...
[INFO]: 2021-09-26 13:02:12 - 1 DlSub Start /media/tv/Superman & Lois
[DEBUG]: 2021-09-26 13:02:12 - Superman and Lois IMDB ID: tt11192306 NeedDownloadSubs: 4
[DEBUG]: 2021-09-26 13:02:12 - S1E14
[DEBUG]: 2021-09-26 13:02:12 - S1E15
[DEBUG]: 2021-09-26 13:02:12 - S1E13
[DEBUG]: 2021-09-26 13:02:12 - S1E12
[INFO]: 2021-09-26 13:02:12 - 1 shooter Start...
[INFO]: 2021-09-26 13:02:12 - 1 subhd Start...
[INFO]: 2021-09-26 13:02:12 - 1 zimuku Start...
[INFO]: 2021-09-26 13:02:12 - 1 xunlei Start...
[INFO]: 2021-09-26 13:02:13 - 1 xunlei End...
[INFO]: 2021-09-26 13:02:17 - 1 shooter End...
[INFO]: 2021-09-26 13:02:23 - 0 zimuku End...
[INFO]: 2021-09-26 13:02:29 - 1 zimuku End...
[DEBUG]: 2021-09-26 13:02:40 - 對比完畢, 偏移量:229.5
[DEBUG]: 2021-09-26 13:02:42 - 對比完畢, 偏移量:225.5
[INFO]: 2021-09-26 13:02:52 - 0 subhd End...
[INFO]: 2021-09-26 13:02:52 - 0 DlSub End /media/tv/Foundation (2021)
[INFO]: 2021-09-26 13:02:53 - OrgSubName: [zimuku]_1_Foundation.S01E01.The.Emperors.Peace.1080p.ATVP.WEB-DL.DDP5.1.H.264-CasStudio.简体&英文.ass
[INFO]: 2021-09-26 13:02:53 - SubDownAt: /media/tv/Foundation (2021)/Season 1/Foundation (2021) - S01E01 - The Emperor's Peace WEBDL-2160p.chinese(简英).default.ass
[INFO]: 2021-09-26 13:02:54 - OrgSubName: [zimuku]_0_Foundation.S01E02.Preparing.to.Live.1080p.ATVP.WEB-DL.DDP5.1.H.264-CasStudio.简体&英文.ass
[INFO]: 2021-09-26 13:02:54 - SubDownAt: /media/tv/Foundation (2021)/Season 1/Foundation (2021) - S01E02 - Preparing to Live WEBDL-2160p.chinese(简英).default.ass
[DEBUG]: 2021-09-26 13:03:24 - 對比完畢, 偏移量:220.5
[INFO]: 2021-09-26 13:03:41 - 1 subhd End...
[INFO]: 2021-09-26 13:03:41 - 1 DlSub End /media/tv/Superman & Lois
[INFO]: 2021-09-26 13:03:42 - OrgSubName: [zimuku]_1_Superman.and.Lois.S01E13.Fail.Safe.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.简体&英文.ass
[INFO]: 2021-09-26 13:03:42 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E13 - Fail Safe WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 13:03:43 - OrgSubName: [zimuku]_2_Superman.and.Lois.S01E12.Through.the.Valley.of.Death.1080p.AMZN.WEB-DL.DDP5.1.H.264.简体&英文.ass
[INFO]: 2021-09-26 13:03:43 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E12 - Through the Valley of Death WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 13:03:43 - OrgSubName: [zimuku]_0_Superman.and.Lois.S01E14.The.Eradicator.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.DivX.简体&英文.ass
[INFO]: 2021-09-26 13:03:43 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E14 - The Eradicator WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 13:03:43 - OrgSubName: [xunlei]_0_H3A5CE_S8E15.srt
[INFO]: 2021-09-26 13:03:43 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E15 - Last Sons of Krypton WEBDL-1080p.chinese(简英).default.srt
[INFO]: 2021-09-26 13:03:43 - Download Series Sub End...
[INFO]: 2021-09-26 13:03:43 - Refresh Emby Sub List
[INFO]: 2021-09-26 13:03:43 - Download One End...
[ERROR]: 2021-09-26 13:03:43 - CloseChrome exit status 1

[INFO]: 2021-09-26 14:02:05 - Download One Started...
[INFO]: 2021-09-26 14:02:05 - Refresh Emby Sub List
[INFO]: 2021-09-26 14:02:06 - Download Movie Sub Started...
[INFO]: 2021-09-26 14:02:06 - Movie Sub Dl From Emby API...
[INFO]: 2021-09-26 14:02:06 - Movie Sub Dl From Emby API no movie need Dl sub
[INFO]: 2021-09-26 14:02:06 - Download Movie Sub End...
[INFO]: 2021-09-26 14:02:06 - Download Series Sub Started...
[INFO]: 2021-09-26 14:02:10 - 1 DlSub Start /media/tv/Superman & Lois
[DEBUG]: 2021-09-26 14:02:10 - Superman and Lois IMDB ID: tt11192306 NeedDownloadSubs: 4
[DEBUG]: 2021-09-26 14:02:10 - S1E12
[DEBUG]: 2021-09-26 14:02:10 - S1E13
[DEBUG]: 2021-09-26 14:02:10 - S1E15
[DEBUG]: 2021-09-26 14:02:10 - S1E14
[INFO]: 2021-09-26 14:02:10 - 1 shooter Start...
[INFO]: 2021-09-26 14:02:10 - 1 subhd Start...
[INFO]: 2021-09-26 14:02:10 - 1 zimuku Start...
[INFO]: 2021-09-26 14:02:10 - 1 xunlei Start...
[INFO]: 2021-09-26 14:02:10 - 0 DlSub Start /media/tv/Foundation (2021)
[DEBUG]: 2021-09-26 14:02:10 - Foundation IMDB ID: tt0804484 NeedDownloadSubs: 2
[DEBUG]: 2021-09-26 14:02:10 - S1E2
[DEBUG]: 2021-09-26 14:02:10 - S1E1
[INFO]: 2021-09-26 14:02:10 - 0 shooter Start...
[INFO]: 2021-09-26 14:02:10 - 0 subhd Start...
[INFO]: 2021-09-26 14:02:10 - 0 xunlei Start...
[INFO]: 2021-09-26 14:02:10 - 0 zimuku Start...
[INFO]: 2021-09-26 14:02:11 - 1 xunlei End...
[INFO]: 2021-09-26 14:02:11 - 0 xunlei End...
[INFO]: 2021-09-26 14:02:13 - 0 shooter End...
[INFO]: 2021-09-26 14:02:16 - 1 shooter End...
[INFO]: 2021-09-26 14:02:25 - 0 zimuku End...
[INFO]: 2021-09-26 14:02:30 - 1 zimuku End...
[DEBUG]: 2021-09-26 14:02:45 - 對比完畢, 偏移量:217.5
[DEBUG]: 2021-09-26 14:02:52 - 對比完畢, 偏移量:218.5
[INFO]: 2021-09-26 14:03:18 - 0 subhd End...
[INFO]: 2021-09-26 14:03:18 - 0 DlSub End /media/tv/Foundation (2021)
[INFO]: 2021-09-26 14:03:19 - OrgSubName: [zimuku]_1_Foundation.S01E01.The.Emperors.Peace.1080p.ATVP.WEB-DL.DDP5.1.H.264-CasStudio.简体&英文.ass
[INFO]: 2021-09-26 14:03:19 - SubDownAt: /media/tv/Foundation (2021)/Season 1/Foundation (2021) - S01E01 - The Emperor's Peace WEBDL-2160p.chinese(简英).default.ass
[INFO]: 2021-09-26 14:03:20 - OrgSubName: [zimuku]_0_Foundation.S01E02.Preparing.to.Live.1080p.ATVP.WEB-DL.DDP5.1.H.264-CasStudio.简体&英文.ass
[INFO]: 2021-09-26 14:03:20 - SubDownAt: /media/tv/Foundation (2021)/Season 1/Foundation (2021) - S01E02 - Preparing to Live WEBDL-2160p.chinese(简英).default.ass
[DEBUG]: 2021-09-26 14:03:29 - 對比完畢, 偏移量:229.5
[INFO]: 2021-09-26 14:03:33 - 1 subhd End...
[INFO]: 2021-09-26 14:03:33 - 1 DlSub End /media/tv/Superman & Lois
[INFO]: 2021-09-26 14:03:33 - OrgSubName: [zimuku]_1_Superman.and.Lois.S01E12.Through.the.Valley.of.Death.1080p.AMZN.WEB-DL.DDP5.1.H.264.简体&英文.ass
[INFO]: 2021-09-26 14:03:33 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E12 - Through the Valley of Death WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 14:03:34 - OrgSubName: [zimuku]_2_Superman.and.Lois.S01E13.Fail.Safe.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.简体&英文.ass
[INFO]: 2021-09-26 14:03:34 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E13 - Fail Safe WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 14:03:34 - OrgSubName: [xunlei]_0_H3A5CE_S8E15.srt
[INFO]: 2021-09-26 14:03:34 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E15 - Last Sons of Krypton WEBDL-1080p.chinese(简英).default.srt
[INFO]: 2021-09-26 14:03:34 - OrgSubName: [zimuku]_0_Superman.and.Lois.S01E14.The.Eradicator.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.DivX.简体&英文.ass
[INFO]: 2021-09-26 14:03:34 - SubDownAt: /media/tv/Superman & Lois/Season 1/Superman & Lois - S01E14 - The Eradicator WEBDL-1080p.chinese(简英).default.ass
[INFO]: 2021-09-26 14:03:34 - Download Series Sub End...
[INFO]: 2021-09-26 14:03:35 - Refresh Emby Sub List
[INFO]: 2021-09-26 14:03:35 - Download One End...
[ERROR]: 2021-09-26 14:03:35 - CloseChrome exit status 1

**Comment by allanpk716** [comment]
见，[如何判断视频是否需要下载、更新字幕的](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md)
