### ISSUE TITLE
windows 下程序闪退，docker下运行也是出错

### ISSUE THREAD

**Issue by chyaww** [allanpk716/ChineseSubFinder#61]
windows下闪退，出现最后一行日志后闪退，日志如下：

> [INFO]: 2021-09-26 18:50:53 - ChineseSubFinder Version: v0.17.1
> [INFO]: 2021-09-26 18:50:53 - UseProxy: http://192.168.1.100:7890
> [INFO]: 2021-09-26 18:50:53 - ProxyTest Target Site http://google.com Speed: 356 Status: 200
> [INFO]: 2021-09-26 18:50:53 - MovieFolder: Z:\media\电影
> [INFO]: 2021-09-26 18:50:53 - SeriesFolder: Z:\media\连续剧
> [INFO]: 2021-09-26 18:50:53 - HotFix Start...
> [INFO]: 2021-09-26 18:50:53 - hotfix 001 start...
> [WARNING]: 2021-09-26 18:50:55 - IsSubHasChinese.HasChineseLang Z:\media\电影\Beyond.Skyline.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT\Beyond.Skyline.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT.zh.srt not chinese sub, is  未知语言

J1900装的的DS918Plus黑群晖，docker运行出现最后一行日志就不运行了，日志如下：

> [INFO]: 2021-09-26 18:52:08 - ChineseSubFinder Version: v0.17.1
> [INFO]: 2021-09-26 18:52:08 - UseProxy: http://192.168.1.100:7890
> [INFO]: 2021-09-26 18:52:08 - ProxyTest Target Site http://google.com Speed: 386 Status: 200
> [INFO]: 2021-09-26 18:52:08 - MovieFolder: /media/电影
> [INFO]: 2021-09-26 18:52:08 - SeriesFolder: /media/连续剧
> [INFO]: 2021-09-26 18:52:08 - HotFix Start...
> [INFO]: 2021-09-26 18:52:08 - HotFix End
> [INFO]: 2021-09-26 18:52:08 - Change Sub Name Format Start...
> [INFO]: 2021-09-26 18:52:08 - DesSubFormatter == LateTimeSubFormatter then skip process
> [INFO]: 2021-09-26 18:52:08 - Change Sub Name Format End
> [INFO]: 2021-09-26 18:52:08 - ReloadBrowser Start...
> [INFO]: 2021-09-26 18:52:21 - ReloadBrowser End
> [INFO]: 2021-09-26 18:52:21 - First Time Download Start
> [INFO]: 2021-09-26 18:52:21 - Download One Started...
> [INFO]: 2021-09-26 18:52:25 - Refresh Emby Sub List
> [INFO]: 2021-09-26 18:52:36 - Download Movie Sub Started...
> [INFO]: 2021-09-26 18:52:36 - Movie Sub Dl From Emby API...
> [INFO]: 2021-09-26 18:52:41 - 0 DlSub Start /media/电影/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP.mkv
> [INFO]: 2021-09-26 18:52:41 - 0 shooter Start...
> [INFO]: 2021-09-26 18:52:41 - 0 zimuku Start...
> [INFO]: 2021-09-26 18:52:41 - 0 subhd Start...
> [INFO]: 2021-09-26 18:52:41 - 0 xunlei Start...
> [INFO]: 2021-09-26 18:52:42 - 0 xunlei End...
> [INFO]: 2021-09-26 18:52:43 - 0 shooter End...
> [INFO]: 2021-09-26 18:52:53 - 0 zimuku End...
> [INFO]: 2021-09-26 18:53:24 - 0 subhd End...
> [INFO]: 2021-09-26 18:53:24 - 0 DlSub End /media/电影/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP.mkv
> [INFO]: 2021-09-26 18:53:29 - OrgSubName: [zimuku]_0_The.Forever.Purge.2021.1080p.WEBRip.DD5.1.x264-CM.EN&CN.ass
> [INFO]: 2021-09-26 18:53:29 - SubDownAt: /media/电影/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP.chinese(简英).default.ass
> [INFO]: 2021-09-26 18:53:33 - 1 DlSub Start /media/电影/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT.mkv
> [INFO]: 2021-09-26 18:53:33 - 1 shooter Start...
> [INFO]: 2021-09-26 18:53:33 - 1 zimuku Start...
> [INFO]: 2021-09-26 18:53:33 - 1 subhd Start...
> [INFO]: 2021-09-26 18:53:33 - 1 xunlei Start...
> [INFO]: 2021-09-26 18:53:34 - 1 xunlei End...
> [INFO]: 2021-09-26 18:53:36 - 1 shooter End...
> [INFO]: 2021-09-26 18:54:05 - 1 zimuku End...
> [INFO]: 2021-09-26 18:54:16 - 1 subhd End...
> [INFO]: 2021-09-26 18:54:16 - 1 DlSub End /media/电影/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT.mkv
> [INFO]: 2021-09-26 18:54:24 - OrgSubName: [zimuku]_0_The Suicide Squad_S0E0.ass
> [INFO]: 2021-09-26 18:54:24 - SubDownAt: /media/电影/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT.chinese(简英).default.ass
> [INFO]: 2021-09-26 18:54:24 - Download Movie Sub End...
> [INFO]: 2021-09-26 18:54:24 - Download Series Sub Started...
> [INFO]: 2021-09-26 18:54:24 - Download Series Sub End...
> [INFO]: 2021-09-26 18:54:27 - Refresh Emby Sub List
> [INFO]: 2021-09-26 18:54:27 - Download One End...
> [ERROR]: 2021-09-26 18:54:27 - CloseChrome exit status 1
> [INFO]: 2021-09-26 18:54:27 - First Time Download End
> [INFO]: 2021-09-26 18:55:20 - ChineseSubFinder Version: v0.17.1
> [INFO]: 2021-09-26 18:55:20 - UseProxy: http://192.168.1.100:7890
> [INFO]: 2021-09-26 18:55:20 - ProxyTest Target Site http://google.com Speed: 382 Status: 200
> [INFO]: 2021-09-26 18:55:20 - MovieFolder: /media/电影
> [INFO]: 2021-09-26 18:55:20 - SeriesFolder: /media/连续剧
> [INFO]: 2021-09-26 18:55:20 - HotFix Start...
> [INFO]: 2021-09-26 18:55:20 - HotFix End
> [INFO]: 2021-09-26 18:55:20 - Change Sub Name Format Start...
> [INFO]: 2021-09-26 18:55:20 - DesSubFormatter == LateTimeSubFormatter then skip process
> [INFO]: 2021-09-26 18:55:20 - Change Sub Name Format End
> [INFO]: 2021-09-26 18:55:20 - ReloadBrowser Start...
> [INFO]: 2021-09-26 18:55:29 - ReloadBrowser End
> [INFO]: 2021-09-26 18:55:29 - First Time Download Start
> [INFO]: 2021-09-26 18:55:29 - Download One Started...
> [INFO]: 2021-09-26 18:55:32 - Refresh Emby Sub List
> [INFO]: 2021-09-26 18:55:43 - Download Movie Sub Started...
> [INFO]: 2021-09-26 18:55:43 - Movie Sub Dl From Emby API...
> [INFO]: 2021-09-26 18:55:47 - 0 DlSub Start /media/电影/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT.mkv
> [INFO]: 2021-09-26 18:55:47 - 0 shooter Start...
> [INFO]: 2021-09-26 18:55:47 - 0 subhd Start...
> [INFO]: 2021-09-26 18:55:47 - 0 xunlei Start...
> [INFO]: 2021-09-26 18:55:47 - 0 zimuku Start...
> [INFO]: 2021-09-26 18:55:47 - 1 DlSub Start /media/电影/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP.mkv
> [INFO]: 2021-09-26 18:55:47 - 1 shooter Start...
> [INFO]: 2021-09-26 18:55:47 - 1 subhd Start...
> [INFO]: 2021-09-26 18:55:47 - 1 zimuku Start...
> [INFO]: 2021-09-26 18:55:47 - 1 xunlei Start...
> [INFO]: 2021-09-26 18:55:47 - 1 xunlei End...
> [INFO]: 2021-09-26 18:55:47 - 0 xunlei End...
> [INFO]: 2021-09-26 18:55:49 - 0 shooter End...
> [INFO]: 2021-09-26 18:55:49 - 1 shooter End...
> [INFO]: 2021-09-26 18:55:59 - 1 zimuku End...
> [INFO]: 2021-09-26 18:56:32 - 0 zimuku End...
> [INFO]: 2021-09-26 18:57:33 - 1 subhd End...
> [INFO]: 2021-09-26 18:57:33 - 1 DlSub End /media/电影/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP.mkv
> [DEBUG]: 2021-09-26 18:57:38 - 對比完畢, 偏移量:233.5
> [INFO]: 2021-09-26 18:57:40 - OrgSubName: [zimuku]_0_The.Forever.Purge.2021.1080p.WEBRip.DD5.1.x264-CM.EN&CN.ass
> [INFO]: 2021-09-26 18:57:40 - SubDownAt: /media/电影/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP/The.Forever.Purge.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-NOGRP.chinese(简英).default.ass
> [INFO]: 2021-09-26 18:57:44 - 0 subhd End...
> [INFO]: 2021-09-26 18:57:44 - 0 DlSub End /media/电影/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT.mkv
> [INFO]: 2021-09-26 18:57:52 - OrgSubName: [zimuku]_0_The Suicide Squad_S0E0.ass
> [INFO]: 2021-09-26 18:57:52 - SubDownAt: /media/电影/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT/The.Suicide.Squad.2021.HDR.2160p.WEB.H265-TIMECUT.chinese(简英).default.ass
> [INFO]: 2021-09-26 18:57:52 - Download Movie Sub End...
> [INFO]: 2021-09-26 18:57:52 - Download Series Sub Started...
> [INFO]: 2021-09-26 18:57:52 - Download Series Sub End...
> [INFO]: 2021-09-26 18:57:55 - Refresh Emby Sub List
> [INFO]: 2021-09-26 18:57:55 - Download One End...
> [ERROR]: 2021-09-26 18:57:55 - CloseChrome exit status 1
> [INFO]: 2021-09-26 18:57:55 - First Time Download End

**Comment by allanpk716** [comment]
指的是这一段吗？如果是，那么就是正常的。

## pic
![image](https://user-images.githubusercontent.com/1176000/134808218-57713d6f-be91-467f-85a7-76d538475359.png)

**Comment by chyaww** [comment]
问题是我有50多个文件啊，下了一个就不动了？

**Comment by allanpk716** [comment]
你启用了 Emby API，会自动跳过已经看过的视频，特别是已经有中文字幕的。

![image](https://user-images.githubusercontent.com/1176000/134808628-24149bb7-b839-4378-aac2-7970241c43e0.png)

**Comment by chyaww** [comment]
好的，谢谢~看来还得把Emby API关了啊~

**Comment by allanpk716** [comment]
> 好的，谢谢~
> 看来还得把Emby API关了啊~

可以在 EmbyAPI 上设置 SkipWatched: false 就不会跳过了。
