### ISSUE TITLE
有中文字幕了的资源还会重复下载

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#66]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

v0.17.3

## 你遇到什么问题了？

对于 emby 已经获取到中文字幕（格式为 movie name.zh-cn.(ass|srt|...)）了的资源, csf还会重复寻找下载。

**Comment by allanpk716** [comment]
> ## 你使用的 chinesesubfinder 是什么版本，什么环境？
> v0.17.3
> 
> ## 你遇到什么问题了？
> 对于 emby 已经获取到中文字幕（格式为 movie name.zh-cn.(ass|srt|...)）了的资源, csf还会重复寻找下载。

看文档，[如何判断视频是否需要下载、更新字幕的](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E8%A7%86%E9%A2%91%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81%E4%B8%8B%E8%BD%BD%E3%80%81%E6%9B%B4%E6%96%B0%E5%AD%97%E5%B9%95%E7%9A%84.md)
