### ISSUE TITLE
字幕语言识别不准确

### ISSUE THREAD

**Issue by wloot** [allanpk716/ChineseSubFinder#68]
部分中文字幕文件会被错误识别成英文或者其他类型, 例如:
```
[WARNING]: 2021-10-04 20:42:16 - IsSubHasChinese.HasChineseLang <movie path>/Bridge of Spies (2015)/Bridge of Spies (2015) (1080p BluRay x265 Silence).zh-cn.srt not chinese sub, is  英
```
https://drive.google.com/file/d/1ogSR8_5J6WIY2A0XFwDEAOcKlUBjGgb2/view?usp=sharing

是否可以通过正则表达式辅助判断? 正则表达式 `\p{Han}` 可以识别出是否包含中文字符, 借此可以判断出是否是纯英文字幕.

**Comment by allanpk716** [comment]
> 部分中文字幕文件会被错误识别成英文或者其他类型, 例如:
> 
> ```
> [WARNING]: 2021-10-04 20:42:16 - IsSubHasChinese.HasChineseLang <movie path>/Bridge of Spies (2015)/Bridge of Spies (2015) (1080p BluRay x265 Silence).zh-cn.srt not chinese sub, is  英
> ```
> 
> https://drive.google.com/file/d/1ogSR8_5J6WIY2A0XFwDEAOcKlUBjGgb2/view?usp=sharing
> 
> 是否可以通过正则表达式辅助判断? 正则表达式 `\p{Han}` 可以识别出是否包含中文字符, 借此可以判断出是否是纯英文字幕.

1. 这里的 bug 是 srt 和 ass 字幕有比较多的怪异“对话”内部定义，字体，特效等。需要修复的是匹配“对话”正则表达式。
2. 正则表达式无法区分简体和繁体，其他国家的语言也会有一定的限制，所以判断语言还是交给其他的库完成，正则表达式还是做解析字幕即可。

**Comment by allanpk716** [comment]
这里会根据大家的反馈，修复正则表达式匹配以下类似的问题。欢迎给出出问题的字幕，方便修复，谢谢。

下图就是这里的问题，修复就好了。

## 举例图片
![image](https://user-images.githubusercontent.com/1176000/135870229-b4be0a45-18be-4d10-a4df-3874f92ccff1.png)

**Comment by allanpk716** [comment]
推送更新了， v0.17.4 ，如果还有遇到类似的问题，也麻烦提供字幕文件，谢谢反馈。

**Comment by wloot** [comment]
> 推送更新了， v0.17.4 ，如果还有遇到类似的问题，也麻烦提供字幕文件，谢谢反馈。

感谢更新. 还发现这个字幕也被错误识别成英字了:
https://drive.google.com/file/d/1WTiZi8ZqVrXb5lhW1Oq8Qw2AIwsrSzVN/view?usp=sharing

**Comment by wloot** [comment]
还有这几个字幕, 版本已更新到0.17.4:
https://drive.google.com/file/d/1en25tJQhtEGnuThQ2vp6ROFf0d3ZnhUu/view?usp=sharing
https://drive.google.com/file/d/1kVWdwDP-WrFrBk4eag5QpYgBjajujqKt/view?usp=sharing
https://drive.google.com/file/d/1teaNl1cf7neG2Yq8FBzhArX-B30VsN9o/view?usp=sharing
https://drive.google.com/file/d/130qoYn1_86r5CtuFdv6GTtUsloJK62lu/view?usp=sharing
https://drive.google.com/file/d/1LiVcTFB-wEzi3sbqbFE-mb1yZdo9DMLr/view?usp=sharing

**Comment by allanpk716** [comment]
`Empire.Of.Dreams.The.Story.Of.The.Star.Wars.Trilogy.2004.1080p.BluRay.x264.AAC5.1-[YTS.MX].zh-cn.srt`

这个字幕有点奇怪，没看过这视频，里面怎么一段是英文一段是中文的？

## 字幕截图
![image](https://user-images.githubusercontent.com/1176000/135968960-d760bdd4-0c58-40dd-ad4a-09283ea13a12.png)

**Comment by allanpk716** [comment]
其他几个 ass 的字幕，看了下，有办法解析，估计要点时间调整代码

**Comment by wloot** [comment]
> `Empire.Of.Dreams.The.Story.Of.The.Star.Wars.Trilogy.2004.1080p.BluRay.x264.AAC5.1-[YTS.MX].zh-cn.srt`
> 
> 这个字幕有点奇怪，没看过这视频，里面怎么一段是英文一段是中文的？
> 
> ## 字幕截图
> ![image](https://user-images.githubusercontent.com/1176000/135968960-d760bdd4-0c58-40dd-ad4a-09283ea13a12.png)

这个应该是字幕本身的问题，从迅雷获取的字幕之前也遇到过这种情况。麻烦忽略这个吧。

**Comment by toniexly** [comment]
> 推送更新了， v0.17.4 ，如果还有遇到类似的问题，也麻烦提供字幕文件，谢谢反馈。

你好，plex除了支持.chi, zh, zho, 也支持zh-hans。。。我发现在现在zh-hans是会被识别的未知字幕 的，希望能修正。

**Comment by allanpk716** [comment]
> > 推送更新了， v0.17.4 ，如果还有遇到类似的问题，也麻烦提供字幕文件，谢谢反馈。
> 
> 
> 
> 你好，plex除了支持.chi, zh, zho, 也支持zh-hans。。。我发现在现在zh-hans是会被识别的未知字幕 的，希望能修正。

本程序不会标记这个关键词zh-hans，所以我无法解决 plex 的问题。
