### ISSUE TITLE
能否提供非群晖的docker版本？

### ISSUE THREAD

**Issue by banditsmile** [allanpk716/ChineseSubFinder#7]
能否提供一个非群晖环境下的docker版本？

**Comment by allanpk716** [comment]
> 能否提供一个非群晖环境下的docker版本？
> 
> 

只是举例是群晖，docker 只跟处理器相关吧。

1. linux/amd64

2. linux/arm/v7

3. linux/arm64

多个架构的 CPU 都支持应该足够用了。
