### ISSUE TITLE
docker 最新的版本内存占用爆炸

### ISSUE THREAD

**Issue by caolicong** [allanpk716/ChineseSubFinder#74]
chinesesubfinder 版本: Latest
docker
运行20分钟内存占用爆炸到1G，开启后内存占用直线上升。由600M上升到1.4G。看趋势内存要被撑爆。日志显示正常运行（UNRAID，8G内存，正常全部内存持续占用60%左右。）。
[INFO]: 2021-10-09 10:57:26 - 3 zimuku End...
[INFO]: 2021-10-09 10:57:27 - 3 xunlei End...
[INFO]: 2021-10-09 10:57:31 - 3 shooter End...

能够重现
希望控制下内存占用，。

**Comment by NV3S** [comment]
没有抓具体数据 但0.17.5更新后跑了一晚第二天nas没响应了，硬重启后看日志发现“chrome”进程把内存占完了
现在给container限制了内存在跑。

caolicong ***@***.***>于2021年10月9日 周六上午11:10写道：

**Comment by caolicong** [comment]
早上起来UNRAID打开很慢，看资源发现内存100%才明白有问题。早上重启之后留意了占用情况，发现确实是被：chinesesubfinder 吃了

**Comment by NV3S** [comment]
限制一下container内存先跑着吧

caolicong ***@***.***>于2021年10月9日 周六下午12:46写道：

**Comment by allanpk716** [comment]
看来是概率问题，这个在 #53 中讨论了。还是网络问题导致故障，然后 go-rod 清理的逻辑没有正确执行（可能是我使用问题，未必是这个库的问题）。近期会改进chrome清理的逻辑（之前在完全一次扫描后才清理，看来得提前，而且需要考虑并发使用chrome的情况）。先忍一下，用 docker 限制下内存使用量，会尽快修复的（这个月有点忙，暂定月底把）:joy:

**Comment by allanpk716** [comment]
对了，你的并发量是多少，大概有多少的视频待扫描字幕，能提供下信息吗？

**Comment by caolicong** [comment]
高阶功能 JELLYFIN能用吗

**Comment by allanpk716** [comment]
因为需要需要重新评估 subhd 的功能，所以现在 v0.18.x 直接屏蔽这个功能了。建议更新最新的。这个bug还是有的，但是估计会重做这个功能，具体时间不能确定。思路有一些，后续完成后会通知。这个问题先挂着，免得我忘了。

**Comment by allanpk716** [comment]
试一试 v0.20.x
