### ISSUE TITLE
ChineseSubFinder在Dokcer bridge网络下，与EMBY（套件安装）的通信配置

### ISSUE THREAD

**Issue by NV3S** [allanpk716/ChineseSubFinder#75]
配置EMBY API功能时候，发现有报错，解决以后发现可以做一些配置建议。

环境：
宿主：Synology DS920+ (192.168.100.150)
EMBY（套件）
ChineseSubFinder On Docker（网络使用bridge方式）（因为我host有IPv6，也会出错，可以另外说）

在配置ChineseSubFinder中EmbyConfig部分的时候，EMBY的地址如果填写成
```
EmbyConfig:
    Url: http://192.168.100.150:8096
    ApiKey: MyKEY
    LimitCount: 3000
    SkipWatched: tru
```
会有如下错误：
```
[INFO]: 2021-10-09 23:22:10 - Download One Started...

[ERROR]: 2021-10-09 23:22:41 - RefreshEmbySubList Get "http://192.168.100.150:8096/emby/Users/Query?api_key=MyKEY": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[INFO]: 2021-10-09 23:22:41 - Download One End...

[ERROR]: 2021-10-09 23:22:41 - CloseChrome exit status 1
```
猜测是无法到192.168.100.150（进container的console发现没ping 不会测了）

然后把Emby的地址，**改成docker bridge的网关**

```
EmbyConfig:
    Url: http://172.17.0.1:8096
    ApiKey: MyKEY
    LimitCount: 3000
    SkipWatched: true
```

就能够正常去抓EMBY了。

**Comment by allanpk716** [comment]
反馈附加到 [高阶设置 - Emby API 支持](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E9%AB%98%E9%98%B6%E8%AE%BE%E7%BD%AE%20-%20Emby%20API%20%E6%94%AF%E6%8C%81.md) 中，谢谢。

**Comment by flywalt** [comment]
按此设置了emby地址，得到如下日志

[ERROR]: 2022-08-12 14:32:39 - Refresh Emby Sub List Error
[ERROR]: 2022-08-12 14:32:39 - refreshEmbySubList Get "http://127.17.0.1:8096/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=3000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=920d6a79a8184335b024943f2c4b7bb5": dial tcp 127.17.0.1:8096: connect: connection refused
[INFO]: 2022-08-12 14:32:39 - ScanEmbyMovieAndSeries End
[ERROR]: 2022-08-12 14:32:39 - ScanEmbyMovieAndSeries Get "http://127.17.0.1:8096/emby/Items?Filters=IsNotFolder&IncludeItemTypes=Episode%2CMovie&IsUnaired=false&Limit=3000&Recursive=true&SortBy=DateCreated&SortOrder=Descending&api_key=920d6a79a8184335b024943f2c4b7bb5": dial tcp 127.17.0.1:8096: connect: connection refused
[INFO]: 2022-08-12 14:32:39 - VideoScanAndRefreshHelper finished, cost: 0.002680542 min
[INFO]: 2022-08-12 14:32:39 - Video Scan End


似乎还是访问不能
目前我的问题就是库里有视频但是文件名，没有封面，似乎抓不到nfo信息，经过仔细查找教程找到本篇，对照修改后还是无法解决

**Comment by NV3S** [comment]
你确认下是172还是127 你这里配的是127

发自我的iPhone
