### ISSUE TITLE
群辉挂载windows硬盘，docker运行显示找不到电影文件夹

### ISSUE THREAD

**Issue by willie91** [allanpk716/ChineseSubFinder#77]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.4.0

环境: docker 
## 你遇到什么问题了？
群辉挂载windows硬盘，docker运行显示找不到电影文件夹你遇到的问题
描述一下
![_20212711032709](https://user-images.githubusercontent.com/32695308/136749423-6c8fb3bd-2af1-4d63-8919-e24d368a0a62.png)
![_20212711032748](https://user-images.githubusercontent.com/32695308/136749519-94c25c76-7335-492a-a7c0-b72f3ef8b1b8.png)
![_20212811032848](https://user-images.githubusercontent.com/32695308/136749667-2c7a9b72-dcd3-4aa3-b510-0b05987581e3.png)

## 你的问题弄重现嘛？

能够重新

## 出错的日志信息可以复制一些出来吗？

日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/logs:/app/Logs
[ChineseSubFinder--202110110000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7320331/ChineseSubFinder--202110110000--.log)

另外我尝试在windows运行，但是不知道为什么，就运行了几部就停了，下面这是windows的log
[ChineseSubFinder--202110110000--.log](https://github.com/allanpk716/ChineseSubFinder/files/7320353/ChineseSubFinder--202110110000--.log)
还有就是我是两个硬盘的，所以要添加两个电影和电视的文件夹，请问配置是添加两个MovieFolder: SeriesFolder: 吗？

**Comment by willie91** [comment]
> 作者你好，我在群晖里尝试使用也出现同样问题，media的容器地址和物理路径设置的是对的。

你应该是配置写错了，我能跑起来了

**Comment by allanpk716** [comment]
> > 看你的截图，我理解应该是这样写 docker 的映射：
> > `volume1/win/d -> /media`
> > 然后配置文件 config.yaml
> > ```
> > MovieFolder: /media/movies
> > SeriesFolder: /media/tv
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后看到日志下载连续剧的时候有问题，感觉怪怪的，能截图连续剧的目录结构看看嘛，多几层的。我没懂，如果 docker 映射和 config 写对了，为啥还能识别到 D:\tv 这样的路径。以及，你需要看看这个文档，[连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)
> > ## 日志截图
> > ![image](https://user-images.githubusercontent.com/1176000/136770604-351564c0-8ff8-4571-b052-a0784f4a8053.png)
> > 配置文件我按照这个写就能跑起来了
> > MovieFolder: /media/movies
> > SeriesFolder: /media/tv
> > 然后就出现我上面发的log这情况了
> 
> 这是我的电视剧的目录结构 ![_20210811060809](https://user-images.githubusercontent.com/32695308/136772873-17b66975-180b-44d9-9abf-c6ade96a8c09.png) ![_20210911060915](https://user-images.githubusercontent.com/32695308/136773033-4dbb2333-6c09-4a8d-8e05-f7bc32b00dfb.png)
> 
> 在windows的路径是D:\tv\功勋
> 
> 我的使用环境是这样的，我电影电视在windows主机上，然后我群辉docker挂载了windows的这个文件夹，docker运行ChineseSubFinder

连续剧的字幕下载还是有要求的，看上面提到的那个文档吧。

**Comment by allanpk716** [comment]
应该是 AA/Season 1/aa S01E01.mp4 这样的结构。你没有 Season 的结构应该会遇到问题的

**Comment by willie91** [comment]
> 应该是 AA/Season 1/aa S01E01.mp4 这样的结构。你没有 Season 的结构应该会遇到问题的

这样啊..那我中文跟英文电视剧都放在一起的就没办法用了吧

**Comment by allanpk716** [comment]
没问题的，这个不影响。我都是混合的。只要目录结构管理好就可以了。给你看看我的截图。后两张中的这几个文件削刮后才有的，比较重要。没得会影响自动识别。

## 截图
![image](https://user-images.githubusercontent.com/1176000/136875099-a3fa850f-08fc-4340-a328-042c648792a7.png)

![image](https://user-images.githubusercontent.com/1176000/136875192-d56ed015-e0c2-40e1-aea0-e2a3cf17419f.png)

![image](https://user-images.githubusercontent.com/1176000/136875219-7ea7180e-7f5d-4711-ada4-a7d767379c19.png)
