### ISSUE TITLE
剧集字幕查询疑问

### ISSUE THREAD

**Issue by JesseZhang97** [allanpk716/ChineseSubFinder#79]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.17.5

环境: 群晖7.0 docker

## 你遇到什么问题了？

1. 剧集被错误识别为中文剧集
2. 是否需要下载判断错误
3. keyword提取错误

## 你的问题弄重现嘛？

能够重现。
问题1，在**强制全局扫描**下，log显示 **SkipChineseSeries**。但是经过nfo以及emby中的imdb id检查发现无误。log中显示的剧集部分在之前的定时轮询中，也有成功的下载字幕。比如《Only Murders in the Building》和《What If…!》就无感下载并整理好了所有剧集的字幕。只是在本次强制全局中被误认为中文剧集。
而“Friends”在某次轮询中成功下载了第一季字幕，可是后面的剧集只有零星的几集下载了字幕。之后的轮询中都没有检查并下载剧集字幕（已检查nfo）。
问题2，在普通轮询log中，行21 剧集What if显示NeedDownloadSubs:8，但其实之前已经下载并整理好了全部字幕。
问题3，行36显示美国恐怖故事和实际缺少字幕相符，但是中文关键词有误。实际为第十季，显示为十一季。同时下面的关键词如
“American Horror Story  10 3”并没有搜索到字幕，同时这里搜索的季为正确值，手动到网站可以搜索到相应字幕。

## 你期望的结果

搜索到正确的缺少字幕的剧集并下载字幕。

## 可以提供遇到问题时候，电影、连续剧的信息吗？

大楼里只有谋杀 IMDB ID: tt12851524
American Horror Story IMDB ID: tt1844624
What If...? IMDB ID: tt10168312
Friends IMDB ID: tt0108778
Modern Love IMDB ID: tt8543390

视频的目录: 
'//volume1/video/SHOWS/Only Murders in the Building'
'//volume1/video/SHOWS/American Horror Story'
'//volume1/video/SHOWS/What If…!'
'//volume1/video/SHOWS/Friends'
'//volume1/video/SHOWS/Modern.Love'

**Comment by allanpk716** [comment]
强制全局扫描的逻辑跟常规的一致的，只不过在检测已存在字幕这一步跳过了

**Comment by JesseZhang97** [comment]
关于问题3，我觉得应该不是目录结构问题。因为what if和only murders in the building的字幕在第一次轮询的时候就成功下载完了，只是在后续的轮询中反复查询。
关于其他没有扫描的剧集我用sonarr重新rename了结构，同时刷新了nfo，发现比如摩登家庭只下载了第一季的字幕。老友记下载了几集的字幕。

**Comment by JesseZhang97** [comment]
![image](https://user-images.githubusercontent.com/40453270/137578115-b7decfca-4017-4720-98b8-1b68177181d4.png)
这是没有进行搜索的其中一季，其余季目录相同。

**Comment by allanpk716** [comment]
那就需要截取日志发上来了，上面会记录为什么的。

**Comment by JesseZhang97** [comment]
剩下出问题的剧集没有log，看似是没有扫描。

**Comment by allanpk716** [comment]
看看能清理当天的日志，然后截图以下你的连续剧目录结构，以及开启程序把完整的日志文件传上来。我对着你的的目录结构看看吧。不然不好定位问题。

**Comment by allanpk716** [comment]
Emby 设置中，你使用了 `SkipWatched: true` ，你得确认下 Modern Famlily 是否有任意的 Emby 用户账号标记看过了，如果看过了，就会跳过。
