### ISSUE TITLE
subhd, zimuku 无法下载字幕

### ISSUE THREAD

**Issue by yueyingjuesha** [allanpk716/ChineseSubFinder#8]
现在zimuku, subhd的默认地址貌似都无法下载了，zimuku 可以通过更改地址成zimuku.org进行下载，但是subhd地址没有变，没有报错，但是试过所有剧目搜索出来的字幕个数都是0个
chinesesubfinder 版本: v0.4.0

**Comment by yueyingjuesha** [comment]
nit: 现在zimuzu已经关站了，是否考虑移除支持

**Comment by allanpk716** [comment]
> 现在zimuku, subhd的默认地址貌似都无法下载了，zimuku 可以通过更改地址成zimuku.org进行下载，但是subhd地址没有变，没有报错，但是试过所有剧目搜索出来的字幕个数都是0个
> chinesesubfinder 版本: v0.4.0

1. 建议先更新到 latest 版本，现在应该是 v0.10.0，刚才测试都是可用的。

2. zimuzu 应该没有支持过。
