### ISSUE TITLE
v0.18.x 开始支持字幕时间轴的自动校正，欢迎试用反馈

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#81]
如题，先试试水。具体见文档，[字幕时间轴校正](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%AD%97%E5%B9%95%E6%97%B6%E9%97%B4%E8%BD%B4%E6%A0%A1%E6%AD%A3.md)

务必按文档中的反馈方式来反馈，不然很难定位问题的哈。

还在自测，晚点会推送到 master 分支，发布出来。:stuck_out_tongue_winking_eye:

**Comment by ibeyond** [comment]
期待一下。

**Comment by allanpk716** [comment]
> > 从本版本开始，暂时强制屏蔽了 subhd 的字幕下载逻辑，需要想一下先。
> 
> subhd现在增加了加他们公众号才能获取解锁码下载, 手段越来越多了. 其实很大程度上 字幕库 就已经足够了, 字幕库资源的质量一般要比subhd好上不少.

感谢反馈，还没来得急看是为啥不能用了···那这样程序的体积可以回归正常了···:joy:

**Comment by OliverGrace** [comment]
应用程序无法正常启动(0xc000007b)
Win10 Server 2020

**Comment by allanpk716** [comment]
> 应用程序无法正常启动(0xc000007b) Win10 Server 2020

#101

**Comment by kfstorm** [comment]
不知道有没有考虑直接使用[ffsubsync](https://github.com/smacke/ffsubsync)呢？ffsubsync既可以按照参考字幕时间轴修正，也可以按照语音识别结果修正。bazarr应该就是用的ffsubsync。

我用了几天ChineseSubFinder和bazarr，感觉还是bazarr功能更完备，管理也更方便，不知道有没有考虑把ChineseSubFinder里独有的字幕站支持贡献到bazarr。

**Comment by allanpk716** [comment]
> 不知道有没有考虑直接使用[ffsubsync](https://github.com/smacke/ffsubsync)呢？ffsubsync既可以按照参考字幕时间轴修正，也可以按照语音识别结果修正。bazarr应该就是用的ffsubsync。
> 
> 我用了几天ChineseSubFinder和bazarr，感觉还是bazarr功能更完备，管理也更方便，不知道有没有考虑把ChineseSubFinder里独有的字幕站支持贡献到bazarr。

1. 已经将 ffsubsync 的功能重写成 go 版本了，因为有 windows 用户，所以不太想依赖过多的外部的程序。
2. 有打算开放 API 接口，至于是什么工具去使用应该都会方便。后续做出来了，再去给 bazarr 他们提一下建议吧。
3. 个人觉得下载字幕这件事，使用者是不想“感知”的。之所以需要大量界面和交互，个人认为需要从需求的源头的解决问题，而不是修修补补。

**Comment by allanpk716** [comment]
终于把 ffsubsync 重写成 golang 集成到软件中啦，v0.19.x 正式启用。之前被绕进去了，想要解决被剪切过的视频字幕匹配问题，现在是暂时放弃解决这个问题。也就是说，如果你下载的视频是导演截切版本或者说是和谐版本，那么字幕识别还是不准的。但是这个是小部分问题···暂时没法搞定。

如果你是下载 web 版本和 dvd 版本，那么本功能是可以正常使用的。详细见文档。

[字幕时间轴校正 V2](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E5%AD%97%E5%B9%95%E6%97%B6%E9%97%B4%E8%BD%B4%E6%A0%A1%E6%AD%A3V2.md)

遇到问题记得看文档提及的“如何反馈问题”哈。

**Comment by allanpk716** [comment]
务必注意一下文档中提及的额外的一个文件夹映射问题

## 图
![image](https://user-images.githubusercontent.com/1176000/147747332-335588ef-5196-4595-b638-e86747e9a1fc.png)

**Comment by palemoky** [comment]
@allanpk716 我目前用的 docker 版 0.19.6，《罪夜之奔》的视频资源是  magnet:?xt=urn:btih:fc9ddfd43bdf159e6c5ce722158be3702ceb23e8，这个资源是有影片分级和前情回顾的，以第一集为例，我发现不仅字幕无法对其，而且时间轴修复后的字幕内容都是错的，以下是缓存中的相关文件和修正后的字幕，麻烦看下是什么问题
https://pan.baidu.com/s/1gdL0iA07jPp05317pVyzeA?pwd=cmsj

**Comment by allanpk716** [comment]
> @allanpk716 我目前用的 docker 版 0.19.6，《罪夜之奔》的视频资源是 magnet:?xt=urn:btih:fc9ddfd43bdf159e6c5ce722158be3702ceb23e8，这个资源是有影片分级和前情回顾的，以第一集为例，我发现不仅字幕无法对其，而且时间轴修复后的字幕内容都是错的，以下是缓存中的相关文件和修正后的字幕，麻烦看下是什么问题 https://pan.baidu.com/s/1gdL0iA07jPp05317pVyzeA?pwd=cmsj

近期比较忙，会晚几天猜有空看。

**Comment by allanpk716** [comment]
> @allanpk716 我目前用的 docker 版 0.19.6，《罪夜之奔》的视频资源是 magnet:?xt=urn:btih:fc9ddfd43bdf159e6c5ce722158be3702ceb23e8，这个资源是有影片分级和前情回顾的，以第一集为例，我发现不仅字幕无法对其，而且时间轴修复后的字幕内容都是错的，以下是缓存中的相关文件和修正后的字幕，麻烦看下是什么问题 https://pan.baidu.com/s/1gdL0iA07jPp05317pVyzeA?pwd=cmsj

你需要把 debug 开启，看看这个字幕是什么地方下载的（zimuku xunlei shooter 或者你开启保存多个字幕的选项，也可以知道），字幕都是匹配错误的，自然是校正不会正确的。
