### ISSUE TITLE
subhd大量出错，后台开启一堆chromium页面，并且无法自动关闭，导致windows卡死

### ISSUE THREAD

**Issue by czahoi** [allanpk716/ChineseSubFinder#82]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

Window，线程数为1

## 你遇到什么问题了？

![image.png](https://i.loli.net/2021/10/14/jJQOtN9KHeSTDwA.png)
<a href="https://sm.ms/image/jJQOtN9KHeSTDwA" target="_blank"><img src="https://i.loli.net/2021/10/14/jJQOtN9KHeSTDwA.png" ></a>

subhd大量出错，后台开启一堆chromium页面，并且无法自动关闭，导致windows卡死

## 你的问题弄重现嘛？

能够重新
## 你期望的结果

跳过subhd源，或者自动关闭无法下载字幕的页面

## 出错的日志信息可以复制一些出来吗？

<a href="https://sm.ms/image/XUPQx2SvRurjWtM" target="_blank"><img src="https://i.loli.net/2021/10/14/XUPQx2SvRurjWtM.png" ></a>
![image.png](https://i.loli.net/2021/10/14/XUPQx2SvRurjWtM.png)

**Comment by allanpk716** [comment]
更新 v0.18.x 吧，暂时屏蔽了 subhd 的功能，需要想一下先。有更新会通知。
