### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by yueyingjuesha** [allanpk716/ChineseSubFinder#9]
请问有考虑过直接用go get ….. 直接安装为一个module, 并且提供一个command line 的binary的入口程序吗？
感觉现在所有的支持都是基于docker和gui的，不是太方便

**Comment by allanpk716** [comment]
1. 想用本程序的那个模块或者说功能呢？如果有需求也是可用拆分出独立的项目，前提是没有提高维护的复杂度。

2. 目前还在开发阶段，调整很可能很大，经常重构，基本是怎么快怎么来，所以怕你们用起来很麻烦，经常改。

**Comment by yueyingjuesha** [comment]
就是提供一个像这个project一样的命令行就很好：
https://github.com/ausaki/subfinder

**Comment by lizenghui** [comment]
> 就是提供一个像这个project一样的命令行就很好：
> https://github.com/ausaki/subfinder

嗯 嗯  同样需要  希望大佬支持，不怕麻烦，在gh上混都爱折腾。哈哈。

**Comment by allanpk716** [comment]
> 就是提供一个像这个project一样的命令行就很好：
> 
> https://github.com/ausaki/subfinder

是想运行一次么？还是想命令行做到啥效果？

**Comment by allanpk716** [comment]
> > 就是提供一个像这个project一样的命令行就很好：
> 
> > https://github.com/ausaki/subfinder
> 
> 
> 
> 嗯 嗯  同样需要  希望大佬支持，不怕麻烦，在gh上混都爱折腾。哈哈。

具体说说想要做成啥效果？

**Comment by lizenghui** [comment]
> > > 就是提供一个像这个project一样的命令行就很好：
> > 
> > 
> > > https://github.com/ausaki/subfinder
> > 
> > 
> > 嗯 嗯  同样需要  希望大佬支持，不怕麻烦，在gh上混都爱折腾。哈哈。
> 
> 具体说说想要做成啥效果？

大佬，可以先来个简单的。
例如入参：
-p --path （用来指定目录，找到nfo文件）
-t --type （指定字幕文件格式 srt ass等，jellyfin对ass不好搞）
-l --lang （指定语言，zh,en 这样，或者zh&en）
最后下载到path中
``
./ChineseSubFinder -t srt,ass -l zh -p /movie/
``

类似这样就行  大佬 可以根据您的具体架构以最小成本来个，感谢。

**Comment by allanpk716** [comment]
> 大佬，可以先来个简单的。
> 例如入参：
> -p --path （用来指定目录，找到nfo文件）
> -t --type （指定字幕文件格式 srt ass等，jellyfin对ass不好搞）
> -l --lang （指定语言，zh,en 这样，或者zh&en）
> 最后下载到path中
> `./ChineseSubFinder -t srt,ass -l zh -p /movie/`
> 
> 类似这样就行 大佬 可以根据您的具体架构以最小成本来个，感谢。

1. 我理解你们的需求是在面向于桌面操作系统（也可以是非UI console 中），编写简单的调用脚本，然后可以通过快捷方式去针对某个路径或者某个视频文件进行找字幕对吗？
2. 运行平台需求呢？

Windows amd64 自动化编译有了，其他平台和 CPU 架构还没在 Github actions 中试过。
本地环境测试 gorelease 多平台都能编译，脚本弄上来 Github actions 就各种蛋疼。

近期有新功能发布，先整完再看看怎么改你们的需求吧。

**Comment by lizenghui** [comment]
ok  我先试试windows版的。

我的环境都是在linux x64上弄的。一直没怎么用过docker。

**Comment by allanpk716** [comment]
考虑了下，还是不打算实现命令行的功能了，这个会跟 Web 设置界面的功能冲突。Web 应该也会实现类似的管理界面，应该可以满足基本的命令行功能的。

**Comment by lizenghui** [comment]
> 考虑了下，还是不打算实现命令行的功能了，这个会跟 Web 设置界面的功能冲突。Web 应该也会实现类似的管理界面，应该可以满足基本的命令行功能的。

那可以有个非docker版的安装教程么？  在linux上可以直接跑的。

**Comment by yueyingjuesha** [comment]
> 考虑了下，还是不打算实现命令行的功能了，这个会跟 Web 设置界面的功能冲突。Web 应该也会实现类似的管理界面，应该可以满足基本的命令行功能的。

是的，主要我现在的影片都不在本地，都是在远程服务器上seedbox上的，平时都是用plex在看，有一个能在linux下面运行的command line就很方便了

**Comment by allanpk716** [comment]
> > 考虑了下，还是不打算实现命令行的功能了，这个会跟 Web 设置界面的功能冲突。Web 应该也会实现类似的管理界面，应该可以满足基本的命令行功能的。
> 
> 是的，主要我现在的影片都不在本地，都是在远程服务器上seedbox上的，平时都是用plex在看，有一个能在linux下面运行的command line就很方便了
> 

其实本程序启动起来后，如果要去爬 zimuku 和 subhd 的字幕，是需要启动浏览器的，所以你用命令行估计速度和效率很低，因为每次都需要初始化。一般建议是程序常驻（先提前运行起来），然后通过web 去管理，或者通过 client 去与核心服务通信，应该效率高一些，但是就是不清爽。

**Comment by allanpk716** [comment]
> > 考虑了下，还是不打算实现命令行的功能了，这个会跟 Web 设置界面的功能冲突。Web 应该也会实现类似的管理界面，应该可以满足基本的命令行功能的。
> 
> 
> 
> 那可以有个非docker版的安装教程么？  在linux上可以直接跑的。

这个可以做的，首先我去看看 linux 的自动化编译有啥问题，然后可以在 release 页面下载。使用其实差不多的，主要是能理解剧目的对应逻辑。你看看项目有个文档，说目录关系的。手机不好给你指路。

**Comment by allanpk716** [comment]
> > > 考虑了下，还是不打算实现命令行的功能了，这个会跟 Web 设置界面的功能冲突。Web 应该也会实现类似的管理界面，应该可以满足基本的命令行功能的。
> > 
> > 是的，主要我现在的影片都不在本地，都是在远程服务器上seedbox上的，平时都是用plex在看，有一个能在linux下面运行的command line就很方便了
> > 
> 
> 其实本程序启动起来后，如果要去爬 zimuku 和 subhd 的字幕，是需要启动浏览器的，所以你用命令行估计速度和效率很低，因为每次都需要初始化。一般建议是程序常驻（先提前运行起来），然后通过web 去管理，或者通过 client 去与核心服务通信，应该效率高一些，但是就是不清爽。

再则，现在反爬比较麻烦，命令行你会等的不耐烦的…还是考虑挂机吧🤪
