### ISSUE TITLE
每次执行完都报错

### ISSUE THREAD

**Issue by devilcell** [allanpk716/ChineseSubFinder#92]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.3

环境: docker

## 你遇到什么问题了？

请问下为什么每次运行完都会提示
[ERROR]: 2021-10-26 15:06:54 - CloseChrome exit status 1
而且定时任务也不会执行了
## 出错的日志信息可以复制一些出来吗？

![image](https://user-images.githubusercontent.com/14147582/138846049-4f69adf4-505d-4c58-bc94-44f89d4dc1ab.png)

**Comment by allanpk716** [comment]
最新版本去掉了 Chrome 的执行逻辑，应该不会出现了。
