### ISSUE TITLE
yaml配置文件中的 SeriesFolder 能否支持多文件夹？

### ISSUE THREAD

**Issue by AAlexDing** [allanpk716/ChineseSubFinder#93]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.4

环境: docker

## 你想要新增或者改进什么功能？

yaml配置文件中的 SeriesFolder 能否支持多文件夹？  比如：
SeriesFolder: [/mnt/user/AA/国产剧,/mnt/user/BB/英美剧,/mnt/user/Movie/日韩剧]

**Comment by allanpk716** [comment]
现在升级至 v0.20.x 应该可以满足你现在的需求。
