### ISSUE TITLE
【建议】能否屏蔽隐藏文件夹的字幕搜索功能？

### ISSUE THREAD

**Issue by dskblh** [allanpk716/ChineseSubFinder#94]
目前用的是chinesesubfinder 版本: v0.18.4 Windows 版。

观察了一下，发现字幕插件会自动下去载隐藏文件夹中的视频字幕，这些隐藏文件夹通常是NAS的RECYCLE文件夹或者是TMM的.DELETE文件夹，都是被删除的内容，是否可以屏蔽这部分内容下载？因为还蛮费时间的，并且我发现有几次，下载这些隐藏文件夹字幕会导致程序运行过不去的情况。

**Comment by wloot** [comment]
可以直接使用emby api, 这样应该只会处理emby返回的影集。

**Comment by allanpk716** [comment]
如果有空的话，可以给出这些隐藏文件夹的结构就更好，目前仅仅是处理了 MAC OS 下载的缓存文件问题，其他情况的暂时没有解决。
