### ISSUE TITLE
自动字幕校正，emby 获取内置和外置字幕解析 bug

### ISSUE THREAD

**Issue by allanpk716** [allanpk716/ChineseSubFinder#98]
会不会是这里的问题
https://github.com/allanpk716/ChineseSubFinder/blob/0a419cfd2a3787fc1b7666a4a56e61ab754fc414/internal/logic/emby_helper/embyhelper.go#L340
emby api返回的是chi/chs这样的language类型, 这里断言的是MatchLangChsEn/MatchLangChtEn, 对应的都是中文.

ps. 如果可能建议把SubNameFormatter: 1模式的字幕文件名格式从zh改成zh-cn, 因为zh在emby只会显示chinese, zh-cn才会显示成chinese simplified.

_Originally posted by @wloot in https://github.com/allanpk716/ChineseSubFinder/issues/81#issuecomment-954443432_

**Comment by allanpk716** [comment]
1. 推送了 v0.18.6 ，可以试试看。但是有一点比较特殊，就是如果你设置的是 `SubNameFormatter: 1` ，保存的字幕的时候写固定的是 'zh' （见下图）。原因也比较简单，一个是图简单，先实现看反馈在调整，另一个是非 Emby 的媒体播放器，没有 emby 那么方便去表达这个字幕的额外信息（没法标记是 fixed ）。后续可能还会调整。有什么想法可以反馈。
2. 你提及的 zh-CN 这种中文编码变种已经支持了，不过是内置解析器的支持，并非保存字幕时候会写入对应的信息。如果后续有需要，再调整吧。就算调整估计也是 Emby 模式调整意义更大，不然其他媒体播放器的支持未知情况太多。

## 截图
![image](https://user-images.githubusercontent.com/1176000/139583718-4c39fdf3-39e7-4fec-b522-557c5ebe9ae0.png)

**Comment by allanpk716** [comment]
试试最新的 v0.19.x，注意看看文档。直接使用感觉不适合你的使用情况，因为需要导出内置字幕或者内置的音频文件，而你是用网盘的，这里会有大量读取视频的文件的需求。不过缓存的位置其实是可以自定义的，文档没有直接写，如果是用 docker 是可以设置到你自定义的路劲的。Windows 暂时不支持。

**Comment by wloot** [comment]
> 试试最新的 v0.19.x，注意看看文档。直接使用感觉不适合你的使用情况，因为需要导出内置字幕或者内置的音频文件，而你是用网盘的，这里会有大量读取视频的文件的需求。不过缓存的位置其实是可以自定义的，文档没有直接写，如果是用 docker 是可以设置到你自定义的路劲的。Windows 暂时不支持。

CSF-SubFixCache 文件夹放在 /app 下面的话, 如果docker重建, 会不会就会没了.

**Comment by allanpk716** [comment]
啊，忘记写文档提示 docker 用户需要把这个目录隐射出去了！我去补下文档。
